/* Heal: onceki hint INSERT PT yazdi ama LOADED/MAP kismi kaldi.
   Identity ile ikinci satir YASAK. */
SET NOCOUNT ON;
SET IMPLICIT_TRANSACTIONS OFF;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

RAISERROR('597 heal LOADED/MAP from existing PT LREF_HINT START', 0, 1) WITH NOWAIT;

DECLARE @n1 INT, @n2 INT, @n3 INT;

/* MAP adopt */
UPDATE m SET m.ENERGY_LREF = p.LREF_HINT
FROM dbo.MIG_OV_ID_MAP m
INNER JOIN dbo.MIG_597_STG_PAY p ON p.SRC_KEY = m.SRC_KEY
WHERE p.LOADED = 0
  AND p.LREF_HINT IS NOT NULL
  AND m.ENERGY_LREF IS NULL
  AND EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
        WHERE t.LREF = p.LREF_HINT
      )
OPTION (RECOMPILE, MAXDOP 8);
SET @n1 = @@ROWCOUNT;

/* STG LOADED */
UPDATE p SET p.LOADED = 1
FROM dbo.MIG_597_STG_PAY p
WHERE p.LOADED = 0
  AND p.LREF_HINT IS NOT NULL
  AND EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
        WHERE t.LREF = p.LREF_HINT
      )
OPTION (RECOMPILE, MAXDOP 8);
SET @n2 = @@ROWCOUNT;

/* yanlis identity kuyrugundan cikar (hint'e don) — LOADED=1 zaten */
UPDATE p SET p.USE_HINT = 1
FROM dbo.MIG_597_STG_PAY p
WHERE p.USE_HINT = 0
  AND p.LOADED = 1
  AND p.LREF_HINT IS NOT NULL
  AND EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
        WHERE t.LREF = p.LREF_HINT
      );
SET @n3 = @@ROWCOUNT;

RAISERROR('597 heal MAP=%d LOADED=%d USE_HINT_fix=%d', 0, 1, @n1, @n2, @n3) WITH NOWAIT;

SELECT
  SUM(CASE WHEN USE_HINT=1 AND LOADED=0 THEN 1 ELSE 0 END) hint_left,
  SUM(CASE WHEN USE_HINT=0 AND LOADED=0 THEN 1 ELSE 0 END) id_left,
  SUM(CASE WHEN LOADED=1 THEN 1 ELSE 0 END) loaded
FROM dbo.MIG_597_STG_PAY WITH (NOLOCK);
