SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET IMPLICIT_TRANSACTIONS OFF;
SET XACT_ABORT ON;

RAISERROR('597 resume CLEAN=0 BatchSize=250000 (hint MERGE OUTPUT)', 0, 1) WITH NOWAIT;

EXEC dbo.SP_MIG_597_ALL
    @AGR_ID = NULL,
    @CLEAN = 0,
    @DEBUG = 1,
    @BatchSize = 250000;
