/* =============================================================================
   prodREADY_ENERGY3007 / 00d_perf_bank_indexes.sql
   597/35 bank resolve hiz — kritik MGR + ENERGY indexleri.

   Neden:
     - LS_PAYMENT (64M) join PAY_LREF → index yoktu (scan)
     - LS_OV_TAH_INVOICE (66M) ABYS_ID index yoktu; OR join felaket
     - MIG_OV_ID_MAP AGR filtre cover yoktu

   Calistir: sqlcmd -S ... -d izgazMGR -I -i 00d_perf_bank_indexes.sql
   (ENERGY MAP index icin energy context asagida)
   ============================================================================= */
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;

USE izgazMGR;
GO

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00d PERF IX START (izgazMGR)';

/* PAY_LREF: WIRE/35 tahsilat bank join anahtari — UNIQUE (1:1) */
IF OBJECT_ID('dbo.LS_PAYMENT', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_PAYMENT') AND name = 'UX_MIG_LS_PAYMENT_PAY_LREF'
)
BEGIN
    PRINT 'CREATE UX_MIG_LS_PAYMENT_PAY_LREF ...';
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_PAYMENT_PAY_LREF
        ON dbo.LS_PAYMENT (PAY_LREF)
        INCLUDE (BANKA_ID, SOZLESME, CANCELED)
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK UX_MIG_LS_PAYMENT_PAY_LREF';
END
ELSE
    PRINT 'SKIP UX_MIG_LS_PAYMENT_PAY_LREF (exists)';
GO

/* TAH ABYS_ID: LREF join yedegi — OR join YASAK, ayri seek */
IF OBJECT_ID('dbo.LS_OV_TAH_INVOICE', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_TAH_INVOICE') AND name = 'IX_MIG_LS_OV_TAH_INVOICE_ABYS'
)
BEGIN
    PRINT 'CREATE IX_MIG_LS_OV_TAH_INVOICE_ABYS ...';
    CREATE NONCLUSTERED INDEX IX_MIG_LS_OV_TAH_INVOICE_ABYS
        ON dbo.LS_OV_TAH_INVOICE (ABYS_ID)
        INCLUDE (LREF, BANKREF, ABYS_AGREEMENT_ID)
        WHERE ABYS_ID IS NOT NULL
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_LS_OV_TAH_INVOICE_ABYS';
END
ELSE
    PRINT 'SKIP IX_MIG_LS_OV_TAH_INVOICE_ABYS (exists)';
GO

/* ---- Overlay FULL: MAHSUP / IADE / IPP ---- */
IF OBJECT_ID('dbo.LS_OV_MAHSUP_CLOSED', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_MAHSUP_CLOSED') AND name = 'IX_MIG_OV_MAHSUP_CLOSED_MAIN'
)
BEGIN
    PRINT 'CREATE IX_MIG_OV_MAHSUP_CLOSED_MAIN ...';
    CREATE NONCLUSTERED INDEX IX_MIG_OV_MAHSUP_CLOSED_MAIN
        ON dbo.LS_OV_MAHSUP_CLOSED (MAIN_LREF)
        INCLUDE (ABYS_AGREEMENT_ID, EXPLAIN_MARK)
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_OV_MAHSUP_CLOSED_MAIN';
END
ELSE
    PRINT 'SKIP IX_MIG_OV_MAHSUP_CLOSED_MAIN (exists)';
GO

IF OBJECT_ID('dbo.LS_OV_IADE_PAYTRANS', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_OV_IADE_PAYTRANS', 'ABYS_ID') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_IADE_PAYTRANS') AND name = 'IX_MIG_OV_IADE_PT_ABYS'
)
BEGIN
    PRINT 'CREATE IX_MIG_OV_IADE_PT_ABYS ...';
    CREATE NONCLUSTERED INDEX IX_MIG_OV_IADE_PT_ABYS
        ON dbo.LS_OV_IADE_PAYTRANS (ABYS_ID)
        INCLUDE (SRC_KEY, ABYS_AGREEMENT_ID, LREF_HINT)
        WHERE ABYS_ID IS NOT NULL
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_OV_IADE_PT_ABYS';
END
ELSE
    PRINT 'SKIP IX_MIG_OV_IADE_PT_ABYS (exists)';
GO

IF OBJECT_ID('dbo.LS_OV_IADE_INVLINES', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_OV_IADE_INVLINES', 'SRC_KEY') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_IADE_INVLINES') AND name = 'IX_MIG_LS_OV_IADE_INVLINES_SRC'
)
BEGIN
    PRINT 'CREATE IX_MIG_LS_OV_IADE_INVLINES_SRC ...';
    CREATE NONCLUSTERED INDEX IX_MIG_LS_OV_IADE_INVLINES_SRC
        ON dbo.LS_OV_IADE_INVLINES (SRC_KEY)
        INCLUDE (INVOICE_SRC_KEY, ABYS_AGREEMENT_ID)
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_LS_OV_IADE_INVLINES_SRC';
END
ELSE
    PRINT 'SKIP IX_MIG_LS_OV_IADE_INVLINES_SRC (exists)';
GO

IF OBJECT_ID('dbo.LS_INSTALLMENT_PLAN', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_INSTALLMENT_PLAN', 'INSTALLMENT_ID') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INSTALLMENT_PLAN') AND name = 'IX_MIG_LS_IPP_INSTALLMENT_ID'
)
BEGIN
    PRINT 'CREATE IX_MIG_LS_IPP_INSTALLMENT_ID ...';
    CREATE NONCLUSTERED INDEX IX_MIG_LS_IPP_INSTALLMENT_ID
        ON dbo.LS_INSTALLMENT_PLAN (INSTALLMENT_ID)
        INCLUDE (ABYS_ID, ORDER_NUMBER, AMOUNT, DUE_DATE)
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_LS_IPP_INSTALLMENT_ID';
END
ELSE
    PRINT 'SKIP IX_MIG_LS_IPP_INSTALLMENT_ID (exists)';
GO

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00d PERF IX izgazMGR DONE';
GO

USE energy;
GO

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00d PERF IX START (energy MAP)';

IF OBJECT_ID('dbo.MIG_OV_ID_MAP', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_OV_ID_MAP') AND name = 'IX_MIG_OV_ID_MAP_KIND_AGR'
)
BEGIN
    PRINT 'CREATE IX_MIG_OV_ID_MAP_KIND_AGR ...';
    CREATE NONCLUSTERED INDEX IX_MIG_OV_ID_MAP_KIND_AGR
        ON dbo.MIG_OV_ID_MAP (OV_KIND, ABYS_AGREEMENT_ID)
        INCLUDE (ENERGY_LREF, ABYS_ACCOUNT_ID, SRC_KEY)
        WITH (MAXDOP = 8, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_OV_ID_MAP_KIND_AGR';
END
ELSE
    PRINT 'SKIP IX_MIG_OV_ID_MAP_KIND_AGR (exists)';
GO

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00d PERF IX ALL DONE';
GO
