/* =============================================================================
   prodREADY_ENERGY3007 / 00e_mgr_cs_installment_indexes.sql
   izgazMGR — 611/613 seek destegi (CS_INSTALLMENT / CS_INSTALLMENT_PLAN)
   ============================================================================= */
USE izgazMGR;
GO
SET NOCOUNT ON;

IF OBJECT_ID('dbo.CS_INSTALLMENT', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.CS_INSTALLMENT')
      AND name = 'IX_MIG_CS_INST_AGR'
)
BEGIN
    PRINT 'CREATE IX_MIG_CS_INST_AGR ...';
    CREATE NONCLUSTERED INDEX IX_MIG_CS_INST_AGR
        ON dbo.CS_INSTALLMENT (AGREEMENT_ID)
        INCLUDE (ID, CANCEL_CAUSE_ID, CANCELLATION_DATE, CANCELLATION_USER_ID, DUE_DATE)
        WITH (MAXDOP = 24, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_CS_INST_AGR';
END
ELSE
    PRINT 'SKIP IX_MIG_CS_INST_AGR';

IF OBJECT_ID('dbo.CS_INSTALLMENT_PLAN', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.CS_INSTALLMENT_PLAN')
      AND name = 'IX_MIG_CS_IP_INSTALLMENT'
)
BEGIN
    PRINT 'CREATE IX_MIG_CS_IP_INSTALLMENT ...';
    CREATE NONCLUSTERED INDEX IX_MIG_CS_IP_INSTALLMENT
        ON dbo.CS_INSTALLMENT_PLAN (INSTALLMENT_ID)
        INCLUDE (ID, ORDER_NUMBER, AMOUNT, LATE_CHARGE, OVERDUE)
        WITH (MAXDOP = 24, ONLINE = ON, SORT_IN_TEMPDB = ON);
    PRINT 'OK IX_MIG_CS_IP_INSTALLMENT';
END
ELSE
    PRINT 'SKIP IX_MIG_CS_IP_INSTALLMENT';

PRINT '00e MGR CS installment indexes DONE';
GO
