/* =============================================================================
   prodREADY_ENERGY3007 / 00e_taksit_staging.sql
   611 / 613 / 40 — fiziksel staging (tempdb #table YOK)
   Onkosul: USE energy; 611/613 SP deploy ONCESI veya yeniden deploy ile birlikte
   Kullanim: SP basinda TRUNCATE; SERIAL AGR (paralel worker paylasimli tablo carpismasin)
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00e TAKSIT STAGING START';

/* ---------- 611 key-list ---------- */
IF OBJECT_ID('dbo.MIG_611_STG_IP_KEYS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_611_STG_IP_KEYS (
        ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_611_STG_IP_KEYS PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'CREATE MIG_611_STG_IP_KEYS';
END

IF OBJECT_ID('dbo.MIG_611_STG_IP_BATCH_KEYS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_611_STG_IP_BATCH_KEYS (
        ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_611_STG_IP_BATCH_KEYS PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'CREATE MIG_611_STG_IP_BATCH_KEYS';
END

/* ---------- 613 cancel normalize ---------- */
IF OBJECT_ID('dbo.MIG_613_STG_CANCEL_PLAN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_CANCEL_PLAN (
        PLAN_ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_613_STG_CANCEL_PLAN PRIMARY KEY CLUSTERED (PLAN_ID)
    );
    PRINT 'CREATE MIG_613_STG_CANCEL_PLAN';
END

IF OBJECT_ID('dbo.MIG_613_STG_INV_CANCEL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_INV_CANCEL (
        INV_LREF INT NOT NULL,
        PLAN_ID  BIGINT NOT NULL,
        CONSTRAINT PK_MIG_613_STG_INV_CANCEL PRIMARY KEY CLUSTERED (INV_LREF)
    );
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_INV_CANCEL_PLAN
        ON dbo.MIG_613_STG_INV_CANCEL (PLAN_ID) INCLUDE (INV_LREF);
    PRINT 'CREATE MIG_613_STG_INV_CANCEL';
END

IF OBJECT_ID('dbo.MIG_613_STG_MAIN_PT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_MAIN_PT (
        INV_LREF     INT NOT NULL,
        PLAN_ID      BIGINT NOT NULL,
        MAIN_PT_LREF INT NOT NULL,
        CONSTRAINT PK_MIG_613_STG_MAIN_PT PRIMARY KEY CLUSTERED (INV_LREF)
    );
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_613_STG_MAIN_PT_LREF
        ON dbo.MIG_613_STG_MAIN_PT (MAIN_PT_LREF) INCLUDE (INV_LREF, PLAN_ID);
    PRINT 'CREATE MIG_613_STG_MAIN_PT';
END

/* ---------- 613 split ---------- */
IF OBJECT_ID('dbo.MIG_613_STG_CS_CANCEL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_CS_CANCEL (
        ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_613_STG_CS_CANCEL PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'CREATE MIG_613_STG_CS_CANCEL';
END

IF OBJECT_ID('dbo.MIG_613_STG_ACTIVE_PL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_ACTIVE_PL (
        PLAN_LREF           INT NOT NULL,
        PLAN_ID             BIGINT NULL,
        ABYS_INSTALLMENT_ID BIGINT NULL,
        TOTAL_AMOUNT        DECIMAL(18,2) NOT NULL,
        CONSTRAINT PK_MIG_613_STG_ACTIVE_PL PRIMARY KEY CLUSTERED (PLAN_LREF)
    );
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_ACTIVE_PL_ABYS
        ON dbo.MIG_613_STG_ACTIVE_PL (ABYS_INSTALLMENT_ID) INCLUDE (TOTAL_AMOUNT, PLAN_ID);
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_ACTIVE_PL_PLAN
        ON dbo.MIG_613_STG_ACTIVE_PL (PLAN_ID) INCLUDE (TOTAL_AMOUNT, ABYS_INSTALLMENT_ID);
    PRINT 'CREATE MIG_613_STG_ACTIVE_PL';
END

IF OBJECT_ID('dbo.MIG_613_STG_PLAN_SUM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_PLAN_SUM (
        PLAN_KEY BIGINT NOT NULL,
        SUM_AMT  DECIMAL(18,2) NOT NULL,
        CONSTRAINT PK_MIG_613_STG_PLAN_SUM PRIMARY KEY CLUSTERED (PLAN_KEY)
    );
    PRINT 'CREATE MIG_613_STG_PLAN_SUM';
END

IF OBJECT_ID('dbo.MIG_613_STG_INV', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_INV (
        INV_LREF INT NOT NULL,
        PLAN_ID BIGINT NOT NULL,
        ABYS_AGREEMENT_ID BIGINT NULL,
        CLIENTREF INT NULL,
        OWNERTYPE INT NULL,
        INV_TYPE INT NULL,
        CURID INT NULL,
        DATE_ DATETIME NULL,
        DUEDATE DATETIME NULL,
        TLTOTAL FLOAT NULL,
        CURTOTAL FLOAT NULL,
        TAX FLOAT NULL,
        GRANDTOTAL FLOAT NULL,
        CANCELED BIT NULL,
        ADDUSER INT NULL,
        BN_TYPE INT NULL,
        XTYPE INT NULL,
        ABYS_ID BIGINT NULL,
        ABYS_ACCOUNT_ID BIGINT NULL,
        ABYS_ACTION_TYPE_ID INT NULL,
        ABYS_ACCRUE_TYPE_ID INT NULL,
        ABYS_REGISTER_ID BIGINT NULL,
        CONSTRAINT PK_MIG_613_STG_INV PRIMARY KEY CLUSTERED (INV_LREF)
    );
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_INV_PLAN
        ON dbo.MIG_613_STG_INV (PLAN_ID) INCLUDE (INV_LREF);
    PRINT 'CREATE MIG_613_STG_INV';
END

IF OBJECT_ID('dbo.MIG_613_STG_OLD_PT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_OLD_PT (
        INV_LREF    INT NOT NULL,
        PLAN_ID     BIGINT NOT NULL,
        OLD_PT_LREF INT NOT NULL,
        OLD_PAID    DECIMAL(18,2) NOT NULL,
        CONSTRAINT PK_MIG_613_STG_OLD_PT PRIMARY KEY CLUSTERED (INV_LREF)
    );
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_613_STG_OLD_PT_LREF
        ON dbo.MIG_613_STG_OLD_PT (OLD_PT_LREF) INCLUDE (INV_LREF, PLAN_ID, OLD_PAID);
    PRINT 'CREATE MIG_613_STG_OLD_PT';
END

IF OBJECT_ID('dbo.MIG_613_STG_NEW', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_NEW (
        INV_LREF INT NOT NULL,
        PLAN_ID BIGINT NOT NULL,
        OLD_PT_LREF INT NOT NULL,
        OLD_PAID DECIMAL(18,2) NOT NULL,
        PLAN_LREF INT NOT NULL,
        INST_NR INT NOT NULL,
        INST_AMT DECIMAL(18,2) NOT NULL,
        ABYS_DUE_DATE DATETIME NULL,
        ABYS_EXPIRY_DATE DATETIME NULL,
        CLIENTREF INT NULL,
        OWNERTYPE INT NULL,
        INV_TYPE INT NULL,
        CURID INT NULL,
        DATE_ DATETIME NULL,
        DUEDATE DATETIME NULL,
        CANCELED BIT NULL,
        ADDUSER INT NULL,
        BN_TYPE INT NULL,
        XTYPE INT NULL,
        ABYS_ID BIGINT NULL,
        ABYS_ACCOUNT_ID BIGINT NULL,
        ABYS_ACTION_TYPE_ID INT NULL,
        ABYS_ACCRUE_TYPE_ID INT NULL,
        ABYS_REGISTER_ID BIGINT NULL,
        ABYS_AGREEMENT_ID BIGINT NULL,
        RN INT NOT NULL,
        CUM_AMT DECIMAL(18,2) NOT NULL,
        NEW_PAID DECIMAL(18,2) NOT NULL,
        CONSTRAINT PK_MIG_613_STG_NEW PRIMARY KEY CLUSTERED (INV_LREF, INST_NR, PLAN_LREF)
    );
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_NEW_PLAN
        ON dbo.MIG_613_STG_NEW (PLAN_LREF) INCLUDE (INV_LREF, INST_NR, DUEDATE);
    CREATE NONCLUSTERED INDEX IX_MIG_613_STG_NEW_OLD
        ON dbo.MIG_613_STG_NEW (OLD_PT_LREF) INCLUDE (INV_LREF, INST_NR, NEW_PAID);
    PRINT 'CREATE MIG_613_STG_NEW';
END

IF OBJECT_ID('dbo.MIG_613_STG_AGR_LIST', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_STG_AGR_LIST (
        ORD    INT NOT NULL,
        AGR_ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_613_STG_AGR_LIST PRIMARY KEY CLUSTERED (ORD)
    );
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_613_STG_AGR_LIST_AGR
        ON dbo.MIG_613_STG_AGR_LIST (AGR_ID);
    PRINT 'CREATE MIG_613_STG_AGR_LIST';
END

/* ---------- 613 ERR (driver CATCH — sessiz fail yok) ---------- */
IF OBJECT_ID('dbo.MIG_613_ERR', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_613_ERR (
        ERR_ID       BIGINT IDENTITY(1,1) NOT NULL,
        RUN_TS       DATETIME2(3) NOT NULL CONSTRAINT DF_MIG_613_ERR_TS DEFAULT (SYSDATETIME()),
        AGR_ID       BIGINT NOT NULL,
        TRY_N        INT NULL,
        ERR_NUM      INT NULL,
        ERR_MSG      NVARCHAR(4000) NULL,
        CONSTRAINT PK_MIG_613_ERR PRIMARY KEY CLUSTERED (ERR_ID)
    );
    CREATE NONCLUSTERED INDEX IX_MIG_613_ERR_AGR
        ON dbo.MIG_613_ERR (AGR_ID, RUN_TS DESC);
    PRINT 'CREATE MIG_613_ERR';
END

/* ---------- 40 IPP apply ---------- */
IF OBJECT_ID('dbo.MIG_40_STG_IPP', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_40_STG_IPP (
        INSTALLMENT_ID BIGINT NOT NULL,
        INST_NR INT NOT NULL,
        AGREEMENT_ID BIGINT NULL,
        MAIN_LREF INT NULL,
        ACCOUNT_ID BIGINT NULL,
        PAYMENT_DATE DATETIME NULL,
        BANKREF INT NULL,
        BANK_RECORD_REF NVARCHAR(50) NULL,
        PAYTYPE INT NOT NULL,
        XTYPE INT NOT NULL,
        AMOUNT DECIMAL(18,2) NOT NULL
    );
    CREATE CLUSTERED INDEX CX_MIG_40_STG_IPP
        ON dbo.MIG_40_STG_IPP (INSTALLMENT_ID, INST_NR);
    CREATE NONCLUSTERED INDEX IX_MIG_40_STG_IPP_MAIN
        ON dbo.MIG_40_STG_IPP (MAIN_LREF, INST_NR) INCLUDE (BANKREF, BANK_RECORD_REF, PAYMENT_DATE, XTYPE);
    CREATE NONCLUSTERED INDEX IX_MIG_40_STG_IPP_ACC
        ON dbo.MIG_40_STG_IPP (ACCOUNT_ID, INST_NR) INCLUDE (BANKREF, PAYMENT_DATE);
    CREATE NONCLUSTERED INDEX IX_MIG_40_STG_IPP_AGR
        ON dbo.MIG_40_STG_IPP (AGREEMENT_ID) INCLUDE (INSTALLMENT_ID, INST_NR);
    PRINT 'CREATE MIG_40_STG_IPP';
END

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00e TAKSIT STAGING DONE';
SELECT name
FROM sys.tables
WHERE name LIKE 'MIG_611_STG_%'
   OR name LIKE 'MIG_613_STG_%'
   OR name LIKE 'MIG_40_STG_%'
   OR name = 'MIG_613_ERR'
ORDER BY name;
GO
