/* =============================================================================
   prodREADY_ENERGY3007 / 00e_invoice_staging.sql
   571 — fiziksel staging (#temp YOK; paket kurali — 575 ile ayni model)
   Tablolar: MIG_571_STG_BATCH_KEYS / MIG_571_STG_KEYS / MIG_571_STG_SKIP
   Kullanim: SP basinda TRUNCATE; SERIAL
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00e INVOICE STAGING START';

IF OBJECT_ID('dbo.MIG_571_STG_BATCH_KEYS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_571_STG_BATCH_KEYS (
        ACTION_ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_571_STG_BATCH_KEYS PRIMARY KEY CLUSTERED (ACTION_ID)
    );
    PRINT 'CREATE MIG_571_STG_BATCH_KEYS';
END

IF OBJECT_ID('dbo.MIG_571_STG_KEYS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_571_STG_KEYS (
        ACTION_ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_571_STG_KEYS PRIMARY KEY CLUSTERED (ACTION_ID)
    );
    PRINT 'CREATE MIG_571_STG_KEYS';
END

IF OBJECT_ID('dbo.MIG_571_STG_SKIP', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_571_STG_SKIP (
        ID BIGINT NOT NULL,
        CONSTRAINT PK_MIG_571_STG_SKIP PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'CREATE MIG_571_STG_SKIP';
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.MIG_571_STG_BATCH_KEYS') AND name = N'IX_MIG_571_STG_BATCH_KEYS_AID')
    CREATE NONCLUSTERED INDEX IX_MIG_571_STG_BATCH_KEYS_AID ON dbo.MIG_571_STG_BATCH_KEYS (ACTION_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.MIG_571_STG_KEYS') AND name = N'IX_MIG_571_STG_KEYS_AID')
    CREATE NONCLUSTERED INDEX IX_MIG_571_STG_KEYS_AID ON dbo.MIG_571_STG_KEYS (ACTION_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.MIG_571_STG_SKIP') AND name = N'IX_MIG_571_STG_SKIP_ID')
    CREATE NONCLUSTERED INDEX IX_MIG_571_STG_SKIP_ID ON dbo.MIG_571_STG_SKIP (ID);

TRUNCATE TABLE dbo.MIG_571_STG_BATCH_KEYS;
TRUNCATE TABLE dbo.MIG_571_STG_KEYS;
TRUNCATE TABLE dbo.MIG_571_STG_SKIP;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 00e INVOICE STAGING OK';
GO
