/*
  00g_597_bankref_indexes.sql
  ---------------------------------------------------------------
  WIRE BANKREF (MAIN/TAH/PT) — covering / filtered index paketi.
  Keyset staging ile birlikte kullan; tek başına eski SELECT TOP
  mismatch picker'ı çözmez, UPDATE/seek maliyetini düşürür.

  KURAL: SP_MIG_597_* çalışırken CREATE etme (82 gibi).
  ONLINE=ON (Enterprise); fail olursa ONLINE=OFF dene.
*/
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET IMPLICIT_TRANSACTIONS OFF;

USE energy;
GO

RAISERROR('========== 00g BANKREF indexes ==========', 0, 1) WITH NOWAIT;
GO

/* TAH INV: TYPE=101 seek + BANKREF cover (keyset UPDATE) */
IF OBJECT_ID('dbo.LS_005_01_INVOICE', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVOICE')
      AND name = 'IX_LS005_INV_TAH_LREF_BANKREF'
)
BEGIN
    RAISERROR('CREATE IX_LS005_INV_TAH_LREF_BANKREF ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_LS005_INV_TAH_LREF_BANKREF
        ON dbo.LS_005_01_INVOICE (LREF)
        INCLUDE (BANKREF, [TYPE], ABYS_ID)
        WHERE [TYPE] = 101
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* Debt INV (TYPE<>101): LREF + BANKREF — filter SQL Server'da <> desteklemez;
   TYPE INCLUDE ile dar covering */
IF OBJECT_ID('dbo.LS_005_01_INVOICE', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVOICE')
      AND name = 'IX_LS005_INV_LREF_TYPE_BANKREF'
)
BEGIN
    RAISERROR('CREATE IX_LS005_INV_LREF_TYPE_BANKREF ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_LS005_INV_LREF_TYPE_BANKREF
        ON dbo.LS_005_01_INVOICE (LREF, [TYPE])
        INCLUDE (BANKREF, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, OWNERREF)
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* PAYTRANS: ABYS_ID → BANKREF/IOCODE (debt/tahsilat BANKREF UPDATE) */
IF OBJECT_ID('dbo.LS_005_01_PAYTRANS', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = 'IX_LS005_PT_ABYS_BANKREF'
)
BEGIN
    RAISERROR('CREATE IX_LS005_PT_ABYS_BANKREF ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_LS005_PT_ABYS_BANKREF
        ON dbo.LS_005_01_PAYTRANS (ABYS_ID)
        INCLUDE (BANKREF, IOCODE, ABYS_AGREEMENT_ID)
        WHERE ABYS_ID IS NOT NULL
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* LS_BANK SMS id → LREF (WIRE zaten UX acabiliyor; burada idempotent) */
IF OBJECT_ID('dbo.LS_BANK', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_BANK', 'ABYS_ID') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_BANK') AND name = 'UX_LS_BANK_ABYS_ID'
)
BEGIN
    RAISERROR('CREATE UX_LS_BANK_ABYS_ID ...', 0, 1) WITH NOWAIT;
    CREATE UNIQUE NONCLUSTERED INDEX UX_LS_BANK_ABYS_ID
        ON dbo.LS_BANK (ABYS_ID)
        WHERE ABYS_ID IS NOT NULL
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* Staging keyset helpers (tablolar 21 DDL ile gelir; yoksa skip) */
IF OBJECT_ID('dbo.MIG_597_STG_TAH_BANK', 'U') IS NOT NULL
AND COL_LENGTH('dbo.MIG_597_STG_TAH_BANK', 'BANK_LREF') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_597_STG_TAH_BANK')
      AND name = 'IX_MIG_597_STG_TAH_BANK_KEYSET'
)
BEGIN
    RAISERROR('CREATE IX_MIG_597_STG_TAH_BANK_KEYSET ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_597_STG_TAH_BANK_KEYSET
        ON dbo.MIG_597_STG_TAH_BANK (INV_LREF)
        INCLUDE (BANK_LREF)
        WHERE BANK_LREF IS NOT NULL;
END
GO

IF OBJECT_ID('dbo.MIG_597_STG_MAIN_BANK', 'U') IS NOT NULL
AND COL_LENGTH('dbo.MIG_597_STG_MAIN_BANK', 'BANK_LREF') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_597_STG_MAIN_BANK')
      AND name = 'IX_MIG_597_STG_MAIN_BANK_KEYSET'
)
BEGIN
    RAISERROR('CREATE IX_MIG_597_STG_MAIN_BANK_KEYSET ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_597_STG_MAIN_BANK_KEYSET
        ON dbo.MIG_597_STG_MAIN_BANK (INV_LREF)
        INCLUDE (BANK_LREF)
        WHERE BANK_LREF IS NOT NULL;
END
GO

IF OBJECT_ID('dbo.MIG_597_STG_PAY', 'U') IS NOT NULL
AND COL_LENGTH('dbo.MIG_597_STG_PAY', 'LOADED') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_597_STG_PAY')
      AND name = 'IX_MIG_597_STG_PAY_LOADED_HINT_SRC'
)
BEGIN
    RAISERROR('CREATE IX_MIG_597_STG_PAY_LOADED_HINT_SRC ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_597_STG_PAY_LOADED_HINT_SRC
        ON dbo.MIG_597_STG_PAY (LOADED, USE_HINT, SRC_KEY);
END
GO

RAISERROR('========== 00g DONE ==========', 0, 1) WITH NOWAIT;
GO
