/* =============================================================================
   prodREADY_ENERGY3007 / 36_backfill_null_agr_owner.sql
   *** PRIMARY YOL DEGIL — KULLANMA (opsiyonel diag) ***
   NO_AGR aktarim: 30b_EXEC_NO_AGR_CHAIN (@AGR_ID=-1) dogrudan kullan.

   izgazMGR.LS_INVOICE — ABYS_AGREEMENT_ID/OWNERREF NULL satirlari
   Energy LS_005_01_AGR ile cozumlenince doldur (yalniz diag).

   Oncelik:
     1) CON=CLIENTREF AND FITNO=INSTALLATION (tek)
     2) CON=CLIENTREF AND ISACTIVE=1 (tek)
     3) CON=CLIENTREF (tek)
     4) FITNO=INSTALLATION (tek)

   @DRY_RUN=1 sayim; 0=UPDATE izgazMGR
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @DRY_RUN BIT = 1;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 36 BACKFILL NULL-AGR DRY=' + CAST(@DRY_RUN AS VARCHAR(1));

IF OBJECT_ID('izgazMGR.dbo.LS_INVOICE', 'U') IS NULL
   OR OBJECT_ID('dbo.LS_005_01_AGR', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.LS_INVOICE veya LS_005_01_AGR yok', 16, 1);
    RETURN;
END

IF OBJECT_ID('tempdb..#NULL_INV') IS NOT NULL DROP TABLE #NULL_INV;
SELECT
    i.LREF,
    i.CLIENTREF,
    i.ABYS_INSTALLATION_ID,
    i.OWNERREF,
    i.ABYS_AGREEMENT_ID
INTO #NULL_INV
FROM izgazMGR.dbo.LS_INVOICE i WITH (NOLOCK)
WHERE i.ABYS_AGREEMENT_ID IS NULL;

CREATE CLUSTERED INDEX IX_NULL_INV ON #NULL_INV (LREF);
CREATE NONCLUSTERED INDEX IX_NULL_INV_CON ON #NULL_INV (CLIENTREF) INCLUDE (ABYS_INSTALLATION_ID);

IF OBJECT_ID('tempdb..#RESOLVE') IS NOT NULL DROP TABLE #RESOLVE;
SELECT
    n.LREF,
    CAST(COALESCE(
        CASE WHEN fc.cnt = 1 THEN fc.agr END,
        CASE WHEN ca.cnt = 1 THEN ca.agr END,
        CASE WHEN cu.cnt = 1 THEN cu.agr END,
        CASE WHEN fu.cnt = 1 THEN fu.agr END
    ) AS BIGINT) AS RESOLVED_AGR,
    CASE
        WHEN fc.cnt = 1 THEN N'FIT_CON'
        WHEN ca.cnt = 1 THEN N'CON_ACTIVE'
        WHEN cu.cnt = 1 THEN N'CON_UNIQUE'
        WHEN fu.cnt = 1 THEN N'FIT_UNIQUE'
        ELSE N'UNRESOLVED'
    END AS RESOLVE_KIND
INTO #RESOLVE
FROM #NULL_INV n
OUTER APPLY (
    SELECT COUNT(*) cnt, MIN(a.LREF) agr
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE a.CON = n.CLIENTREF AND a.FITNO = n.ABYS_INSTALLATION_ID
) fc
OUTER APPLY (
    SELECT COUNT(*) cnt, MIN(a.LREF) agr
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE a.CON = n.CLIENTREF AND ISNULL(a.ISACTIVE, 0) = 1
) ca
OUTER APPLY (
    SELECT COUNT(*) cnt, MIN(a.LREF) agr
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE a.CON = n.CLIENTREF
) cu
OUTER APPLY (
    SELECT COUNT(*) cnt, MIN(a.LREF) agr
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE a.FITNO = n.ABYS_INSTALLATION_ID
) fu;

SELECT RESOLVE_KIND, COUNT(*) AS n
FROM #RESOLVE
GROUP BY RESOLVE_KIND
ORDER BY n DESC;

DECLARE @Can INT = (SELECT COUNT(*) FROM #RESOLVE WHERE RESOLVED_AGR IS NOT NULL);
DECLARE @Open INT = (SELECT COUNT(*) FROM #RESOLVE WHERE RESOLVED_AGR IS NULL);
PRINT 'can_resolve=' + CAST(@Can AS VARCHAR(20)) + ' unresolved=' + CAST(@Open AS VARCHAR(20));

IF @DRY_RUN = 1
BEGIN
    SELECT TOP 30 LREF, RESOLVED_AGR, RESOLVE_KIND FROM #RESOLVE WHERE RESOLVED_AGR IS NOT NULL ORDER BY LREF;
    PRINT '========== 36 DRY_RUN — APPLY icin @DRY_RUN=0 ==========';
    RETURN;
END

BEGIN TRAN;

UPDATE i
SET i.OWNERREF = r.RESOLVED_AGR,
    i.ABYS_AGREEMENT_ID = r.RESOLVED_AGR
FROM izgazMGR.dbo.LS_INVOICE i
INNER JOIN #RESOLVE r ON r.LREF = i.LREF
WHERE r.RESOLVED_AGR IS NOT NULL
  AND i.ABYS_AGREEMENT_ID IS NULL;

DECLARE @N INT = @@ROWCOUNT;
COMMIT TRAN;

PRINT 'UPDATED izgazMGR.LS_INVOICE rows=' + CAST(@N AS VARCHAR(20));
PRINT 'Kalan NULL-AGR → EXEC 30b @AGR_ID=-1 (571/575 NO_AGR)';
PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 36 BACKFILL DONE';
GO
