/* ============================================================
   FILE : prodREADY_ENERGY3007 / 91_debt_pt_dup_cleanup.sql
   FAZ  : DUP_2X / DUP_NX — INSTALLMENT_PLAN_REF IS NULL faturalarda
          ayni INVOICEREF icin birden fazla aktif ana borc PT (INST_NR=0)

   R19 (2026-08-10):
     - GHOST: PT.ABYS_ID <> INV.ABYS_ID (odeme action → debt PT) asla KEEP
     - CP=1 (CANCELLATIONPAYMENT) asla KEEP (onceki kural korundu)
     - @INV_CSV opsiyonel daraltma (ornegin '19622456,19279896')

   Onkosul: 575 guard + 576 UX deploy (opsiyonel; cleanup once UX)
   Sonra  : UX_MIG_PT_DEBT_INV_INST0 create (bu script sonunda)
            filter: CANCELED=0 AND (CP=0 OR CP IS NULL)

   KEEP kurali (RN=1):
     0) CP=1 → DROP adayi (asla KEEP)
     1) GHOST (PT.ABYS_ID <> INV.ABYS_ID ve PT.ABYS_ID <> INV.LREF) → DROP
     2) PT.ABYS_ID = INV.ABYS_ID
     3) PT.ABYS_ID = INV.LREF
     4) uzerine tahsilat CROSSREF var
     5) MIN(PT.LREF)
   DROP  : diger aktif INST_NR=0 → CANCELED=1 (soft)
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @DryRun BIT = 1;   -- 0 = uygula
DECLARE @Eps DECIMAL(18,2) = 0.02;
/* NULL = tum; ornek: N'19622456,19279896,19612012' */
DECLARE @INV_CSV NVARCHAR(MAX) = NULL;

IF OBJECT_ID('tempdb..#INV_FILTER') IS NOT NULL DROP TABLE #INV_FILTER;
CREATE TABLE #INV_FILTER (INV_LREF INT NOT NULL PRIMARY KEY);

IF @INV_CSV IS NOT NULL AND LEN(LTRIM(RTRIM(@INV_CSV))) > 0
BEGIN
    INSERT INTO #INV_FILTER (INV_LREF)
    SELECT DISTINCT TRY_CAST(LTRIM(RTRIM(value)) AS INT)
    FROM STRING_SPLIT(@INV_CSV, ',')
    WHERE TRY_CAST(LTRIM(RTRIM(value)) AS INT) IS NOT NULL;
END

IF OBJECT_ID('tempdb..#DUP') IS NOT NULL DROP TABLE #DUP;
IF OBJECT_ID('tempdb..#KEEP') IS NOT NULL DROP TABLE #KEEP;

;WITH multi AS (
    SELECT pt.INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    WHERE pt.IOCODE = 0
      AND ISNULL(pt.INST_NR, 0) = 0
      AND ISNULL(pt.CANCELED, 0) = 0
      AND (
            NOT EXISTS (SELECT 1 FROM #INV_FILTER)
         OR EXISTS (SELECT 1 FROM #INV_FILTER f WHERE f.INV_LREF = pt.INVOICEREF)
          )
    GROUP BY pt.INVOICEREF
    HAVING COUNT(*) > 1
)
SELECT
    inv.LREF AS INV_LREF,
    inv.ABYS_ID AS INV_ABYS_ID,
    CONVERT(DECIMAL(18,2), inv.PAYABLETOTAL) AS INV_P,
    pt.LREF AS PT_LREF,
    pt.ABYS_ID AS PT_ABYS_ID,
    CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) AS PT_P,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID,
    CAST(ISNULL(pt.CANCELLATIONPAYMENT, 0) AS TINYINT) AS CP,
    CASE
        WHEN pt.ABYS_ID IS NOT NULL
         AND pt.ABYS_ID <> inv.ABYS_ID
         AND pt.ABYS_ID <> inv.LREF
        THEN CAST(1 AS TINYINT)
        ELSE CAST(0 AS TINYINT)
    END AS IS_GHOST,
    (
        SELECT COUNT(*)
        FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
        WHERE t.CROSSREF = pt.LREF
          AND ISNULL(t.IOCODE, 0) = 1
    ) AS TAH_CNT
INTO #DUP
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN multi m ON m.INVOICEREF = inv.LREF
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND pt.IOCODE = 0
   AND ISNULL(pt.INST_NR, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.INSTALLMENT_PLAN_REF IS NULL;

CREATE CLUSTERED INDEX CX_DUP ON #DUP (INV_LREF, PT_LREF);

;WITH ranked AS (
    SELECT
        d.*,
        ROW_NUMBER() OVER (
            PARTITION BY d.INV_LREF
            ORDER BY
                CASE WHEN d.CP = 1 THEN 1 ELSE 0 END,          /* CANCEL_REV asla KEEP */
                CASE WHEN d.IS_GHOST = 1 THEN 1 ELSE 0 END,    /* odeme-action ghost asla KEEP */
                CASE
                    WHEN d.PT_ABYS_ID = d.INV_ABYS_ID THEN 0
                    WHEN d.PT_ABYS_ID = d.INV_LREF THEN 1
                    WHEN d.TAH_CNT > 0 THEN 2
                    ELSE 3
                END,
                d.PT_LREF
        ) AS RN
    FROM #DUP d
)
SELECT INV_LREF, PT_LREF AS KEEP_PT
INTO #KEEP
FROM ranked
WHERE RN = 1
  AND CP = 0
  AND IS_GHOST = 0;

/* Guvenlik: INV'de hic KEEP kalmadiysa MATCH_INV / MIN(LREF) zorla */
INSERT INTO #KEEP (INV_LREF, KEEP_PT)
SELECT d.INV_LREF, MIN(d.PT_LREF)
FROM #DUP d
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.INV_LREF = d.INV_LREF)
  AND d.CP = 0
  AND d.IS_GHOST = 0
  AND d.PT_ABYS_ID = d.INV_ABYS_ID
GROUP BY d.INV_LREF;

INSERT INTO #KEEP (INV_LREF, KEEP_PT)
SELECT d.INV_LREF, MIN(d.PT_LREF)
FROM #DUP d
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.INV_LREF = d.INV_LREF)
GROUP BY d.INV_LREF;

CREATE UNIQUE CLUSTERED INDEX CX_KEEP ON #KEEP (INV_LREF);

PRINT '========== ADAY ==========';
SELECT
    COUNT(DISTINCT d.INV_LREF) AS INV_CNT,
    COUNT(*) AS PT_CNT,
    SUM(CASE WHEN d.IS_GHOST = 1 THEN 1 ELSE 0 END) AS GHOST_PT_CNT,
    CONVERT(DECIMAL(18,2), SUM(CASE WHEN k.KEEP_PT IS NULL THEN d.PT_P ELSE 0 END)) AS DROP_PAYABLE_SUM
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF;

PRINT '========== TOP 40 ==========';
SELECT TOP 40
    d.INV_LREF, d.INV_ABYS_ID, d.INV_P,
    d.PT_LREF, d.PT_ABYS_ID, d.PT_P, d.PT_PAID, d.CP, d.IS_GHOST, d.TAH_CNT,
    CASE WHEN k.KEEP_PT IS NULL THEN 'DROP' ELSE 'KEEP' END AS ACT
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF
ORDER BY d.INV_LREF, d.PT_LREF;

IF @DryRun = 1
BEGIN
    PRINT 'DRY-RUN: UPDATE yok. Uygulamak icin @DryRun=0';
    RETURN;
END

BEGIN TRAN;

UPDATE pay
SET pay.CROSSREF = k.KEEP_PT
FROM dbo.LS_005_01_PAYTRANS pay
INNER JOIN #DUP d ON d.PT_LREF = pay.CROSSREF
INNER JOIN #KEEP k ON k.INV_LREF = d.INV_LREF
WHERE ISNULL(pay.IOCODE, 0) = 1
  AND NOT EXISTS (SELECT 1 FROM #KEEP x WHERE x.KEEP_PT = pay.CROSSREF);

PRINT 'CROSSREF retarget=' + CAST(@@ROWCOUNT AS VARCHAR(20));

UPDATE pt
SET pt.CANCELED = CAST(1 AS BIT)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #DUP d ON d.PT_LREF = pt.LREF
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.KEEP_PT = pt.LREF);

PRINT 'SOFT-CANCEL drop PT=' + CAST(@@ROWCOUNT AS VARCHAR(20));

/* dogrulama */
SELECT COUNT(*) AS STILL_DUP_INV
FROM (
    SELECT INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
    WHERE IOCODE = 0 AND ISNULL(INST_NR, 0) = 0 AND ISNULL(CANCELED, 0) = 0
      AND (
            NOT EXISTS (SELECT 1 FROM #INV_FILTER)
         OR EXISTS (SELECT 1 FROM #INV_FILTER f WHERE f.INV_LREF = INVOICEREF)
          )
    GROUP BY INVOICEREF
    HAVING COUNT(*) > 1
) x;

COMMIT;

/* Unique index (cleanup sonrasi) — disabled IX ortaminda skip */
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'UX_MIG_PT_DEBT_INV_INST0'
)
AND EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'IX_MIG_PT_INVREF_IO'
      AND is_disabled = 0
)
BEGIN
    BEGIN TRY
        /* Filtered IX WHERE: OR / ISNULL YASAK — CP NULL satırlar UX dışı kalır */
        CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_PT_DEBT_INV_INST0
            ON dbo.LS_005_01_PAYTRANS (INVOICEREF)
            WHERE IOCODE = 0 AND INST_NR = 0 AND CANCELED = 0
              AND CANCELLATIONPAYMENT = 0
            WITH (MAXDOP = 8, SORT_IN_TEMPDB = ON);
        PRINT 'CREATE UX_MIG_PT_DEBT_INV_INST0 OK';
    END TRY
    BEGIN CATCH
        PRINT 'WARN UX_MIG_PT_DEBT_INV_INST0: ' + ERROR_MESSAGE();
    END CATCH
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'UX_MIG_PT_DEBT_INV_INSTN'
)
BEGIN
    BEGIN TRY
        CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_PT_DEBT_INV_INSTN
            ON dbo.LS_005_01_PAYTRANS (INVOICEREF, INST_NR)
            WHERE IOCODE = 0 AND INST_NR > 0 AND CANCELED = 0
              AND CANCELLATIONPAYMENT = 0
            WITH (MAXDOP = 8, SORT_IN_TEMPDB = ON);
        PRINT 'CREATE UX_MIG_PT_DEBT_INV_INSTN OK';
    END TRY
    BEGIN CATCH
        PRINT 'WARN UX_MIG_PT_DEBT_INV_INSTN: ' + ERROR_MESSAGE();
    END CATCH
END

PRINT '========== 91 DUP CLEANUP DONE ==========';
GO
