/* =============================================================================
   prodREADY_ENERGY3007 / 91c_tah_crossref_paid_detect.sql
   SSMS — TESPIT (doğru invariant)

   KURAL (sorun OLMAMASI gereken):
     Açık borç (IO=0, CANCELED=0, PAYABLE>0) için:
       TAH_AMT = tah.PAYABLETOTAL (<>0) → tah.PAID (<>0) → tah.TLTOTAL
         (0.01 dahil; TLTOTAL şişmesinde PAID/PAYABLE gerçek ödeme)
       TARGET  = LEAST(SUM(TAH_AMT), PAYABLE)
       PAID + 0.01 >= TARGET → OK

   DİKKAT: TAH.INVOICEREF ≠ DEBT.INVOICEREF NORMAL (tahsilat faturası ayrı)
   Heal (residual): 91d_debt_paid_sync_from_tah.sql
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @AGR_ID    BIGINT = NULL;
DECLARE @INV_LREF  INT    = NULL;
DECLARE @DEBT_LREF INT    = NULL;

DECLARE @t0 DATETIME2(3) = SYSDATETIME();
PRINT CONVERT(VARCHAR(30), @t0, 121) + N' | 91c INVARIANT DETECT';

IF OBJECT_ID('tempdb..#TAH') IS NOT NULL DROP TABLE #TAH;
SELECT
    t.CROSSREF AS DEBT_LREF,
    CONVERT(DECIMAL(18,2), SUM(
        CASE
            /* 0.01 dahil — TLTOTAL şişmesinde PAID/PAYABLE gerçek tutar */
            WHEN ISNULL(t.PAYABLETOTAL, 0) <> 0
                THEN CONVERT(DECIMAL(18,2), t.PAYABLETOTAL)
            WHEN ISNULL(t.PAID, 0) <> 0
                THEN CONVERT(DECIMAL(18,2), t.PAID)
            ELSE CONVERT(DECIMAL(18,2), ISNULL(t.TLTOTAL, 0))
        END
    )) AS SUM_AMT,
    CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(t.TLTOTAL, 0)))) AS SUM_TL_RAW,
    COUNT(*) AS TAH_CNT
INTO #TAH
FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
WHERE t.CROSSREF IS NOT NULL
  AND t.IOCODE = 1
  AND ISNULL(t.CANCELED, 0) = 0
  AND (
        ISNULL(t.PAID, 0) > 0.01
     OR ISNULL(t.PAYABLETOTAL, 0) > 0.01
     OR ISNULL(t.TLTOTAL, 0) > 0.01
  )
  AND (@DEBT_LREF IS NULL OR t.CROSSREF = @DEBT_LREF)
GROUP BY t.CROSSREF
OPTION (RECOMPILE, MAXDOP 8);

CREATE UNIQUE CLUSTERED INDEX CX_TAH ON #TAH (DEBT_LREF);

IF OBJECT_ID('tempdb..#GAP') IS NOT NULL DROP TABLE #GAP;
SELECT
    d.LREF AS DEBT_LREF,
    d.INVOICEREF,
    d.ABYS_AGREEMENT_ID AS AGR,
    ISNULL(d.INST_NR, 0) AS INST_NR,
    CONVERT(DECIMAL(18,2), ISNULL(d.PAID, 0)) AS PAID,
    CONVERT(DECIMAL(18,2), d.PAYABLETOTAL) AS PAYABLE,
    t.SUM_AMT,
    t.SUM_TL_RAW,
    t.TAH_CNT,
    CONVERT(DECIMAL(18,2),
        CASE WHEN t.SUM_AMT > CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
             THEN CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
             ELSE t.SUM_AMT END
    ) AS TARGET_PAID,
    ISNULL(inv.CLOSED, 0) AS INV_CLOSED
INTO #GAP
FROM #TAH t
INNER JOIN dbo.LS_005_01_PAYTRANS d WITH (NOLOCK)
    ON d.LREF = t.DEBT_LREF
LEFT JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.LREF = d.INVOICEREF
WHERE d.IOCODE = 0
  AND ISNULL(d.CANCELED, 0) = 0
  AND ISNULL(d.CANCELLATIONPAYMENT, 0) = 0
  AND CONVERT(DECIMAL(18,2), ISNULL(d.PAYABLETOTAL, 0)) > 0.01
  AND (@AGR_ID IS NULL OR d.ABYS_AGREEMENT_ID = @AGR_ID)
  AND (@INV_LREF IS NULL OR d.INVOICEREF = @INV_LREF)
  AND CONVERT(DECIMAL(18,2), ISNULL(d.PAID, 0)) + 0.01 <
      CASE WHEN t.SUM_AMT > CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
           THEN CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
           ELSE t.SUM_AMT END
OPTION (RECOMPILE, MAXDOP 8);

PRINT N'ms=' + CAST(DATEDIFF(MILLISECOND, @t0, SYSDATETIME()) AS VARCHAR(20));

PRINT '========== KONTROL OZET ==========';
DECLARE @open_n BIGINT, @ok_n BIGINT, @gap_n INT, @delta DECIMAL(18,2);
SELECT @open_n = COUNT_BIG(*)
FROM #TAH t
INNER JOIN dbo.LS_005_01_PAYTRANS d WITH (NOLOCK) ON d.LREF = t.DEBT_LREF
WHERE d.IOCODE = 0 AND ISNULL(d.CANCELED, 0) = 0 AND ISNULL(d.CANCELLATIONPAYMENT, 0) = 0
  AND CONVERT(DECIMAL(18,2), ISNULL(d.PAYABLETOTAL, 0)) > 0.01
  AND (@AGR_ID IS NULL OR d.ABYS_AGREEMENT_ID = @AGR_ID)
  AND (@INV_LREF IS NULL OR d.INVOICEREF = @INV_LREF);

SELECT @gap_n = COUNT(*), @delta = CONVERT(DECIMAL(18,2), SUM(TARGET_PAID - PAID)) FROM #GAP;
SET @ok_n = @open_n - @gap_n;

SELECT
    @open_n AS OPEN_DEBT_WITH_TAH,
    @ok_n AS OK_PAID,
    @gap_n AS PAID_LOW_RESIDUAL,
    @delta AS RESIDUAL_DELTA,
    CASE WHEN @gap_n = 0 THEN N'PASS — sorun yok'
         WHEN @gap_n <= 20 THEN N'RESIDUAL — 91d heal (kucuk)'
         ELSE N'FAIL — incele' END AS STATUS;

/* Yanlis alarm karsilastirma: SUM(TLTOTAL) ile kac 'sahte' gap */
DECLARE @fake INT;
;WITH fake AS (
    SELECT d.LREF
    FROM #TAH t
    INNER JOIN dbo.LS_005_01_PAYTRANS d WITH (NOLOCK) ON d.LREF = t.DEBT_LREF
    WHERE d.IOCODE = 0 AND ISNULL(d.CANCELED, 0) = 0 AND ISNULL(d.CANCELLATIONPAYMENT, 0) = 0
      AND CONVERT(DECIMAL(18,2), ISNULL(d.PAYABLETOTAL, 0)) > 0.01
      AND CONVERT(DECIMAL(18,2), ISNULL(d.PAID, 0)) + 0.01 <
          CASE WHEN t.SUM_TL_RAW > CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
               THEN CONVERT(DECIMAL(18,2), d.PAYABLETOTAL) ELSE t.SUM_TL_RAW END
      AND NOT EXISTS (SELECT 1 FROM #GAP g WHERE g.DEBT_LREF = d.LREF)
)
SELECT @fake = COUNT(*) FROM fake;
SELECT @fake AS FALSE_ALARM_IF_USED_TLTOTAL;

PRINT '========== RESIDUAL LIST ==========';
SELECT
    DEBT_LREF, INVOICEREF, AGR, INST_NR,
    PAID, PAYABLE, SUM_AMT, SUM_TL_RAW, TAH_CNT, TARGET_PAID,
    CONVERT(DECIMAL(18,2), TARGET_PAID - PAID) AS DELTA,
    INV_CLOSED
FROM #GAP
ORDER BY (TARGET_PAID - PAID) DESC, DEBT_LREF;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + N' | 91c DONE';
GO
