/* ============================================================
   FILE : prodEnergy/90_afl_frk/93_tuketim_tutar_kontrol.sql
   FAZ  : B10 standalone — energy.dbo.TUKETIM_TUTAR_KONTROL snapshot
   Grain: ACCOUNT_ID = INVOICE.ABYS_ACCOUNT_ID (= CS_ACCOUNT.ID = AFL.FATURAID)
   Onkosul: LS_005_01_INVOICE + INVLINES + PAYTRANS yuklu
            izgazMGR.LS_AFL_OPEN_DEBT (opsiyonel; yoksa AFL_* NULL)
   Kolonlar: Oracle O59 + AFL LEFT JOIN check kolonlari
   Esleme:
     M3/KWH/CONSUMPTION ← INV.ABYS_*
     GAZ/SKB/KDV/TOPLAM ← INVLINES ABYS_AMOUNT_RAW * ABYS_STATUS
                          (939 / 7658 / 169)
     ODENEN             ← -SUM(borc PT.PAID)
     KALAN              ← TOPLAM + ODENEN
     AFL_*              ← LS_AFL_OPEN_DEBT LEFT ON FATURAID = ACCOUNT_ID
   Sonraki: 94_tuketim_tutar_frk.sql (izgazMGR dump vs bu tablo)
   ============================================================ */
USE energy;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @Msg NVARCHAR(400);
DECLARE @Cnt BIGINT;
DECLARE @Eps DECIMAL(18,2) = 0.02;
DECLARE @HasAfl BIT = 0;

IF OBJECT_ID('energy.dbo.LS_005_01_INVOICE', 'U') IS NULL
   OR OBJECT_ID('energy.dbo.LS_005_01_INVLINES', 'U') IS NULL
   OR OBJECT_ID('energy.dbo.LS_005_01_PAYTRANS', 'U') IS NULL
BEGIN
    RAISERROR('INV/INVLINES/PAYTRANS yok. Once 571/581/575 yukleme.', 16, 1);
    RETURN;
END

IF OBJECT_ID('energy.dbo.LS_AFL_OPEN_DEBT', 'U') IS NOT NULL
    SET @HasAfl = 1;
ELSE
    RAISERROR('UYARI: energy.LS_AFL_OPEN_DEBT yok — AFL_* kolonlari NULL.', 0, 1) WITH NOWAIT;

SET @Msg = N'TTK ENERGY START | drop+create energy.dbo.TUKETIM_TUTAR_KONTROL'
    + CASE WHEN @HasAfl = 1 THEN N' + AFL LEFT' ELSE N' (AFL yok)' END;
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('tempdb..#EN_HDR') IS NOT NULL DROP TABLE #EN_HDR;
IF OBJECT_ID('tempdb..#EN_LINE') IS NOT NULL DROP TABLE #EN_LINE;
IF OBJECT_ID('tempdb..#EN_PAY') IS NOT NULL DROP TABLE #EN_PAY;

/* ---------- Fatura baslik (tuketim) ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    MAX(inv.ABYS_AGREEMENT_ID) AS AGREEMENT_ID,
    MAX(inv.ABYS_ACCRUE_TYPE_ID) AS ACCRUE_TYPE_ID,
    MAX(inv.DUEDATE) AS SON_ODEME_TARIHI,
    MAX(CAST(inv.DATE_ AS DATE)) AS TAHAKKUK_TARIHI,
    MAX(LEFT(CAST(inv.FICHENO AS VARCHAR(45)), 45)) AS FATURA_SERI_SIRA,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_M3, 0)))) AS M3,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_KWH, 0)))) AS KWH,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_CONSUMPTION, 0)))) AS CONSUMPTION
INTO #EN_HDR
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID;

CREATE CLUSTERED INDEX CX_EN_HDR ON #EN_HDR (ACCOUNT_ID);

/* ---------- Satir tutarlari ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 939
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 7658
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS SKB_TUTARI,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 169
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS KDV_TUTARI,
    CONVERT(DECIMAL(18,6), MAX(
        CASE WHEN il.ABYS_INCOME_ID = 939
             THEN CONVERT(DECIMAL(18,6), ISNULL(il.UNITPRICE, il.ABYS_UNIT_PRICE))
             ELSE NULL END
    )) AS GAZ_M3_BIRIM_FIYAT,
    CONVERT(DECIMAL(18,2), SUM(
        CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
             * ISNULL(il.ABYS_STATUS, 1))
    )) AS TOPLAM_TAHAKKUK
INTO #EN_LINE
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN energy.dbo.LS_005_01_INVLINES il WITH (NOLOCK)
    ON il.INVOICEREF = inv.LREF
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(il.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID;

CREATE CLUSTERED INDEX CX_EN_LINE ON #EN_LINE (ACCOUNT_ID);

/* ---------- Odeme (borc PT) ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), SUM(
        CASE
            WHEN ISNULL(pt.CANCELED, 0) = 0
             AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
            THEN CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0))
            ELSE 0
        END
    )) AS PAID_SUM
INTO #EN_PAY
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID;

CREATE CLUSTERED INDEX CX_EN_PAY ON #EN_PAY (ACCOUNT_ID);

/* ---------- AFL (opsiyonel) — FATURAID = ACCOUNT_ID ---------- */
IF OBJECT_ID('tempdb..#AFL') IS NOT NULL DROP TABLE #AFL;

CREATE TABLE #AFL (
    ACCOUNT_ID         BIGINT NOT NULL PRIMARY KEY,
    AFL_BALANCE        DECIMAL(18,2) NULL,
    AFL_TAKSIT         VARCHAR(1) NULL,
    AFL_YT             VARCHAR(3) NULL,
    AFL_MIG_IN_SCOPE   TINYINT NULL
);

IF @HasAfl = 1
BEGIN
    INSERT INTO #AFL (ACCOUNT_ID, AFL_BALANCE, AFL_TAKSIT, AFL_YT, AFL_MIG_IN_SCOPE)
    SELECT
        CAST(a.FATURAID AS BIGINT),
        CONVERT(DECIMAL(18,2), a.BALANCE),
        LEFT(CAST(a.TAKSIT_DURUMU AS VARCHAR(1)), 1),
        LEFT(CAST(a.YT_DURUMU AS VARCHAR(3)), 3),
        CAST(ISNULL(a.MIG_IN_SCOPE, 1) AS TINYINT)
    FROM energy.dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK);
END

/* ---------- DROP (ayri batch: SELECT INTO / RECON derleme Msg 207 onleme) ---------- */
IF OBJECT_ID('energy.dbo.TUKETIM_TUTAR_KONTROL', 'U') IS NOT NULL
    DROP TABLE energy.dbo.TUKETIM_TUTAR_KONTROL;
GO

DECLARE @Eps DECIMAL(18,2) = 0.02;

SELECT
    CAST(h.ACCOUNT_ID AS BIGINT)                                  AS ACCOUNT_ID,
    CAST(h.AGREEMENT_ID AS BIGINT)                                AS AGREEMENT_ID,
    CAST(NULL AS VARCHAR(200))                                    AS ACCRUE_TYPE_NAME,
    CAST(h.ACCRUE_TYPE_ID AS INT)                                 AS ACCRUE_TYPE_ID,
    CAST(h.SON_ODEME_TARIHI AS DATETIME)                          AS SON_ODEME_TARIHI,
    CAST(h.TAHAKKUK_TARIHI AS DATE)                               AS TAHAKKUK_TARIHI,
    CAST(h.FATURA_SERI_SIRA AS VARCHAR(45))                       AS FATURA_SERI_SIRA,
    CAST(NULL AS DECIMAL(18,6))                                   AS FIRST_INDEX,
    CAST(NULL AS DECIMAL(18,6))                                   AS LAST_INDEX,
    CONVERT(DECIMAL(18,6), h.M3)                                  AS M3,
    CAST(NULL AS DECIMAL(18,6))                                   AS CORRECTED_M3,
    CONVERT(DECIMAL(18,6), h.KWH)                                 AS KWH,
    CONVERT(DECIMAL(18,6), h.CONSUMPTION)                         AS CONSUMPTION,
    CAST(NULL AS DECIMAL(18,6))                                   AS CONSUMPTION_1,
    CAST(NULL AS DECIMAL(18,6))                                   AS CONSUMPTION_2,
    CAST(NULL AS DECIMAL(18,6))                                   AS CONSUMPTION_3,
    CONVERT(DECIMAL(18,2), ISNULL(l.GAZ_TUTARI, 0))               AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), ISNULL(l.SKB_TUTARI, 0))               AS SKB_TUTARI,
    CONVERT(DECIMAL(18,2), ISNULL(l.KDV_TUTARI, 0))               AS KDV_TUTARI,
    CONVERT(DECIMAL(18,6), l.GAZ_M3_BIRIM_FIYAT)                  AS GAZ_M3_BIRIM_FIYAT,
    CONVERT(DECIMAL(18,2), ISNULL(l.TOPLAM_TAHAKKUK, 0))          AS TOPLAM_TAHAKKUK,
    CONVERT(DECIMAL(18,2), -ISNULL(p.PAID_SUM, 0))                AS ODENEN_TUTAR,
    CONVERT(DECIMAL(18,2),
        ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
    )                                                             AS KALAN_TUTAR,
    /* AFL LEFT — FATURAID = ACCOUNT_ID */
    CASE WHEN afl.ACCOUNT_ID IS NOT NULL THEN CAST(1 AS TINYINT) ELSE CAST(0 AS TINYINT) END AS AFL_HIT,
    afl.AFL_BALANCE,
    afl.AFL_TAKSIT,
    afl.AFL_YT,
    afl.AFL_MIG_IN_SCOPE,
    CONVERT(DECIMAL(18,2),
        CASE WHEN afl.ACCOUNT_ID IS NULL THEN NULL
             ELSE ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
                - ISNULL(afl.AFL_BALANCE, 0)
        END
    )                                                             AS DELTA_AFL_KALAN,
    CASE
        WHEN afl.ACCOUNT_ID IS NULL THEN 'NO_AFL'
        WHEN ABS(
                ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
              - ISNULL(afl.AFL_BALANCE, 0)
             ) <= @Eps THEN 'MATCH'
        ELSE 'AMT_DIFF'
    END                                                           AS AFL_CHECK,
    CAST(CONVERT(DATE, GETDATE()) AS DATE)                        AS AS_OF_DATE,
    CAST(GETDATE() AS DATETIME)                                   AS SNAPSHOT_DATE
INTO energy.dbo.TUKETIM_TUTAR_KONTROL
FROM #EN_HDR h
LEFT JOIN #EN_LINE l ON l.ACCOUNT_ID = h.ACCOUNT_ID
LEFT JOIN #EN_PAY  p ON p.ACCOUNT_ID = h.ACCOUNT_ID
LEFT JOIN #AFL afl ON afl.ACCOUNT_ID = h.ACCOUNT_ID;
GO

CREATE UNIQUE CLUSTERED INDEX CX_TTK_ACC
    ON energy.dbo.TUKETIM_TUTAR_KONTROL (ACCOUNT_ID);
CREATE NONCLUSTERED INDEX IX_TTK_AGR
    ON energy.dbo.TUKETIM_TUTAR_KONTROL (AGREEMENT_ID);
CREATE NONCLUSTERED INDEX IX_TTK_ACR
    ON energy.dbo.TUKETIM_TUTAR_KONTROL (ACCRUE_TYPE_ID);
CREATE NONCLUSTERED INDEX IX_TTK_AFL
    ON energy.dbo.TUKETIM_TUTAR_KONTROL (AFL_CHECK, AFL_HIT)
    INCLUDE (ACCOUNT_ID, KALAN_TUTAR, AFL_BALANCE, DELTA_AFL_KALAN);
GO

/* RECON — yeni batch (yeni kolon metadata) */
DECLARE @Msg NVARCHAR(400);
DECLARE @Cnt BIGINT;
DECLARE @HasAfl BIT = CASE WHEN OBJECT_ID('energy.dbo.LS_AFL_OPEN_DEBT', 'U') IS NOT NULL THEN 1 ELSE 0 END;

SELECT
    COUNT(*) AS TTK_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(M3)) AS M3_SUM,
    CONVERT(DECIMAL(18,2), SUM(TOPLAM_TAHAKKUK)) AS TAH_SUM,
    CONVERT(DECIMAL(18,2), SUM(ODENEN_TUTAR)) AS ODE_SUM,
    CONVERT(DECIMAL(18,2), SUM(KALAN_TUTAR)) AS KALAN_SUM,
    SUM(CASE WHEN AFL_HIT = 1 THEN 1 ELSE 0 END) AS AFL_HIT_CNT,
    CONVERT(DECIMAL(18,2), SUM(AFL_BALANCE)) AS AFL_BAL_SUM
FROM energy.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK);

SELECT
    AFL_CHECK,
    COUNT(*) AS CNT,
    CONVERT(DECIMAL(18,2), SUM(KALAN_TUTAR)) AS KALAN_SUM,
    CONVERT(DECIMAL(18,2), SUM(AFL_BALANCE)) AS AFL_BAL_SUM,
    CONVERT(DECIMAL(18,2), SUM(DELTA_AFL_KALAN)) AS DELTA_SUM
FROM energy.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK)
GROUP BY AFL_CHECK
ORDER BY AFL_CHECK;

IF @HasAfl = 1
BEGIN
    SELECT COUNT(*) AS AFL_ONLY_CNT
    FROM izgazMGR.dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    WHERE NOT EXISTS (
        SELECT 1 FROM energy.dbo.TUKETIM_TUTAR_KONTROL t WITH (NOLOCK)
        WHERE t.ACCOUNT_ID = CAST(a.FATURAID AS BIGINT)
    );

    SELECT TOP (50)
        t.ACCOUNT_ID, t.AGREEMENT_ID, t.ACCRUE_TYPE_ID,
        t.KALAN_TUTAR, t.AFL_BALANCE, t.DELTA_AFL_KALAN,
        t.AFL_TAKSIT, t.AFL_YT, t.AFL_MIG_IN_SCOPE, t.AFL_CHECK
    FROM energy.dbo.TUKETIM_TUTAR_KONTROL t WITH (NOLOCK)
    WHERE t.AFL_CHECK = 'AMT_DIFF'
    ORDER BY ABS(ISNULL(t.DELTA_AFL_KALAN, 0)) DESC;
END

SELECT @Cnt = COUNT(*) FROM energy.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK);

SET @Msg = N'TTK ENERGY OK | ttk=' + CAST(@Cnt AS NVARCHAR(20))
    + N' | AFL LEFT check | tablo=energy.dbo.TUKETIM_TUTAR_KONTROL | sonra 94';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
