/* =============================================================================
   FILE : prodEnergy/90_afl_frk/98_tam_iade_main_pt_close_temp.sql
   Eski dar varyant (sadece OV_TAM+IADE).

   TEST ortami icin tercih et:
     98_TEST_tam_iade_main_close.sql  (log + IADE_ONLY fallback)

   KURAL (dar kapsam):
     OV_EKS KIND=TAM + TYPE92 + AFL≈0 + MAIN PT acik
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun    BIT           = 1;      -- 0 = APPLY
DECLARE @Agr       BIGINT        = 3;      -- NULL = tum (dikkat)
DECLARE @AccountId BIGINT        = NULL;   -- ornek: 28077306
DECLARE @Eps       DECIMAL(18,2) = 0.02;
-- SET @DryRun = 0;
-- SET @AccountId = 28077306;

DECLARE @t0 DATETIME2(3) = SYSDATETIME();
PRINT CONVERT(VARCHAR(30), @t0, 121)
    + N' | 98 TAM-IADE MAIN close DryRun=' + CAST(@DryRun AS VARCHAR(1))
    + N' Agr=' + CASE WHEN @Agr IS NULL THEN N'TUM' ELSE CONVERT(NVARCHAR(20), @Agr) END
    + N' Acc=' + CASE WHEN @AccountId IS NULL THEN N'*' ELSE CONVERT(NVARCHAR(20), @AccountId) END;

IF OBJECT_ID('izgazMGR.dbo.LS_OV_EKS_CLASS', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.dbo.LS_OV_EKS_CLASS yok.', 16, 1);
    RETURN;
END;

IF OBJECT_ID('tempdb..#CAND') IS NOT NULL DROP TABLE #CAND;

;WITH tam AS (
    SELECT
        CAST(e.AGREEMENT_ID AS BIGINT) AS AGREEMENT_ID,
        CAST(e.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
        CAST(e.MAIN_LREF AS INT) AS MAIN_LREF,
        CONVERT(DECIMAL(18,2), ISNULL(e.EKS_AMT, 0)) AS EKS_AMT
    FROM izgazMGR.dbo.LS_OV_EKS_CLASS e WITH (NOLOCK)
    WHERE e.KIND = 'TAM'
      AND e.MAIN_LREF IS NOT NULL
      AND (@Agr IS NULL OR e.AGREEMENT_ID = @Agr)
      AND (@AccountId IS NULL OR e.ACCOUNT_ID = @AccountId)
),
iade AS (
    SELECT
        inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
        MAX(inv.LREF) AS IADE_LREF,
        CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL, 0)))) AS IADE_AMT
    FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    WHERE inv.TYPE = 92
      AND ISNULL(inv.CANCELED, 0) = 0
      AND inv.ABYS_ACCOUNT_ID IS NOT NULL
      AND (@Agr IS NULL OR inv.ABYS_AGREEMENT_ID = @Agr)
      AND (@AccountId IS NULL OR inv.ABYS_ACCOUNT_ID = @AccountId)
    GROUP BY inv.ABYS_ACCOUNT_ID
)
SELECT
    t.AGREEMENT_ID,
    t.ACCOUNT_ID,
    t.MAIN_LREF,
    t.EKS_AMT,
    i.IADE_LREF,
    i.IADE_AMT,
    inv.TYPE AS MAIN_TYPE,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED,
    CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL, 0)) AS INV_PAYABLE,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAID_NEW,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(afl.BALANCE, 0)) AS AFL_BALANCE
INTO #CAND
FROM tam t
INNER JOIN iade i
    ON i.ACCOUNT_ID = t.ACCOUNT_ID
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.LREF = t.MAIN_LREF
   AND ISNULL(inv.IOCODE, 0) = 0
   AND ISNULL(inv.CANCELED, 0) = 0
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
LEFT JOIN dbo.LS_AFL_OPEN_DEBT afl WITH (NOLOCK)
    ON CAST(afl.FATURAID AS BIGINT) = t.ACCOUNT_ID
WHERE CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
  AND CONVERT(DECIMAL(18,2), ISNULL(afl.BALANCE, 0)) <= @Eps
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_CAND ON #CAND (PT_LREF);

PRINT N'build_ms=' + CAST(DATEDIFF(MILLISECOND, @t0, SYSDATETIME()) AS VARCHAR(20));

PRINT '========== TESPIT OZET ==========';
SELECT
    COUNT(*) AS PT_OPEN_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN)) AS SUM_PT_KALAN
FROM #CAND;

PRINT '========== ADAYLAR ==========';
SELECT
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, MAIN_TYPE, MAIN_CLOSED,
    EKS_AMT, IADE_LREF, IADE_AMT,
    PT_LREF, PT_PAYABLE, PT_PAID_OLD, PT_PAID_NEW, PT_KALAN, AFL_BALANCE
FROM #CAND
ORDER BY PT_KALAN DESC, AGREEMENT_ID, ACCOUNT_ID, PT_LREF;

IF NOT EXISTS (SELECT 1 FROM #CAND)
BEGIN
    PRINT N'Aday yok — cikis.';
    RETURN;
END;

IF @DryRun = 1
BEGIN
    PRINT N'DRY_RUN=1 — UPDATE yok.';
    PRINT N'Uygulamak: SET @DryRun=0; (gerekirse @Agr / @AccountId daralt)';
    PRINT N'Sonra: EXEC dbo.SP_AGR_FRK_ALL @Agr = <agr>;  -- DELTA_KALAN~0 beklenir';
    RETURN;
END;

/* ---------- APPLY ---------- */
PRINT '========== APPLY ==========';
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, c.PT_PAID_NEW)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #CAND c ON c.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

PRINT N'PT PAID=PAYABLE n=' + CAST(@@ROWCOUNT AS VARCHAR(20));

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (
    SELECT DISTINCT MAIN_LREF FROM #CAND
) c ON c.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 0;

PRINT N'INV CLOSED=1 n=' + CAST(@@ROWCOUNT AS VARCHAR(20));

COMMIT TRAN;

PRINT '========== POST CHECK (ayni filtre) ==========';
SELECT
    c.AGREEMENT_ID, c.ACCOUNT_ID, c.MAIN_LREF, c.PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_NOW,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED_NOW
FROM #CAND c
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = c.PT_LREF
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = c.MAIN_LREF
ORDER BY c.AGREEMENT_ID, c.ACCOUNT_ID, c.PT_LREF;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + N' | 98 DONE (apply)';
GO
