/* ============================================================
   FILE : hotfix/01_diag_kurus_src_en.sql
   Amac : Gelir/tahsilat "yanlis kurus" — SRC(OV) vs EN + ALLOC grain
   Salt okuma. SSMS → energy → F5
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @Sample INT = 500000;  -- hizli ornek; full icin NULL yapmayin (uzun)

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 01_diag start';

/* ---- 1) PAYTRANS: OV_PAY vs energy (ornek) ---- */
IF OBJECT_ID('tempdb..#pay') IS NOT NULL DROP TABLE #pay;
SELECT TOP (@Sample)
    CAST(TRY_CAST(s.LREF AS BIGINT) AS INT) AS LREF,
    CONVERT(DECIMAL(18,2), s.PAYABLETOTAL) AS SRC,
    CONVERT(DECIMAL(18,2), s.PAY_FULL_AMT) AS FULL_AMT,
    s.ALLOC_RN,
    s.ALLOC_SRC
INTO #pay
FROM izgazMGR.dbo.LS_OV_PAY_PT s WITH (NOLOCK)
WHERE TRY_CAST(s.LREF AS BIGINT) BETWEEN 1 AND 2147483647;

CREATE CLUSTERED INDEX CX_pay ON #pay (LREF);

SELECT
    COUNT(*) AS sample_n,
    SUM(CASE WHEN p.SRC <> CONVERT(DECIMAL(18,2), e.PAYABLETOTAL) THEN 1 ELSE 0 END) AS src_ne_en,
    SUM(CASE WHEN p.FULL_AMT IS NOT NULL AND p.SRC <> p.FULL_AMT THEN 1 ELSE 0 END) AS payable_ne_full
FROM #pay p
INNER JOIN dbo.LS_005_01_PAYTRANS e WITH (NOLOCK) ON e.LREF = p.LREF;

PRINT '=== SRC<>EN ornekleri (PAY) — bos olmali ===';
SELECT TOP 30
    p.LREF,
    p.SRC AS OV_PAYABLE,
    CONVERT(DECIMAL(18,2), e.PAYABLETOTAL) AS EN_PAYABLE,
    p.FULL_AMT AS OV_FULL,
    p.ALLOC_RN,
    p.ALLOC_SRC
FROM #pay p
INNER JOIN dbo.LS_005_01_PAYTRANS e WITH (NOLOCK) ON e.LREF = p.LREF
WHERE p.SRC <> CONVERT(DECIMAL(18,2), e.PAYABLETOTAL)
ORDER BY ABS(p.SRC - CONVERT(DECIMAL(18,2), e.PAYABLETOTAL)) DESC;

PRINT '=== ALLOC grain (PAYABLE <> FULL) — isin "makbuz vs satir" farki ===';
SELECT TOP 30
    p.LREF,
    p.SRC AS PAYABLE_SATIR,
    p.FULL_AMT AS MAKBUZ_FULL,
    p.SRC - p.FULL_AMT AS DELTA,
    p.ALLOC_RN,
    p.ALLOC_SRC,
    e.ABYS_AGREEMENT_ID,
    e.DATE_
FROM #pay p
INNER JOIN dbo.LS_005_01_PAYTRANS e WITH (NOLOCK) ON e.LREF = p.LREF
WHERE p.FULL_AMT IS NOT NULL
  AND p.SRC <> p.FULL_AMT
ORDER BY ABS(p.SRC - p.FULL_AMT) DESC;

/* ---- 2) TAH INV 101 ---- */
IF OBJECT_ID('tempdb..#tah') IS NOT NULL DROP TABLE #tah;
SELECT TOP (@Sample)
    CAST(s.LREF AS INT) AS LREF,
    CONVERT(DECIMAL(18,2), s.PAYABLETOTAL) AS SRC_P,
    CONVERT(DECIMAL(18,2), s.TLTOTAL) AS SRC_T,
    CONVERT(DECIMAL(18,2), s.GRANDTOTAL) AS SRC_G
INTO #tah
FROM izgazMGR.dbo.LS_OV_TAH_INVOICE s WITH (NOLOCK)
WHERE s.LREF BETWEEN 1 AND 2147483647;

CREATE CLUSTERED INDEX CX_tah ON #tah (LREF);

SELECT
    COUNT(*) AS tah_sample_n,
    SUM(CASE WHEN t.SRC_P <> CONVERT(DECIMAL(18,2), e.PAYABLETOTAL) THEN 1 ELSE 0 END) AS pay_mism,
    SUM(CASE WHEN t.SRC_T <> CONVERT(DECIMAL(18,2), e.TLTOTAL) THEN 1 ELSE 0 END) AS tl_mism,
    SUM(CASE WHEN t.SRC_G <> CONVERT(DECIMAL(18,2), e.GRANDTOTAL) THEN 1 ELSE 0 END) AS gr_mism
FROM #tah t
INNER JOIN dbo.LS_005_01_INVOICE e WITH (NOLOCK) ON e.LREF = t.LREF;

/* ---- 3) GELIR satirlari: LS_INVLINES vs energy (varsa) ---- */
IF OBJECT_ID('izgazMGR.dbo.LS_INVLINES', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('tempdb..#il') IS NOT NULL DROP TABLE #il;
    SELECT TOP (@Sample)
        CAST(TRY_CAST(s.LREF AS BIGINT) AS INT) AS LREF,
        CONVERT(DECIMAL(18,2), ISNULL(s.GRANDTOTAL, 0)) AS SRC_G,
        CONVERT(DECIMAL(18,2), ISNULL(s.TLTOTAL, 0)) AS SRC_T,
        CONVERT(DECIMAL(18,2), ISNULL(s.TAX, 0)) AS SRC_TAX
    INTO #il
    FROM izgazMGR.dbo.LS_INVLINES s WITH (NOLOCK)
    WHERE TRY_CAST(s.LREF AS BIGINT) BETWEEN 1 AND 2147483647;

    CREATE CLUSTERED INDEX CX_il ON #il (LREF);

    SELECT
        COUNT(*) AS il_sample_n,
        SUM(CASE WHEN i.SRC_G <> CONVERT(DECIMAL(18,2), ISNULL(e.GRANDTOTAL, 0)) THEN 1 ELSE 0 END) AS g_mism,
        SUM(CASE WHEN i.SRC_T <> CONVERT(DECIMAL(18,2), ISNULL(e.TLTOTAL, 0)) THEN 1 ELSE 0 END) AS t_mism,
        SUM(CASE WHEN i.SRC_TAX <> CONVERT(DECIMAL(18,2), ISNULL(e.TAX, 0)) THEN 1 ELSE 0 END) AS tax_mism
    FROM #il i
    INNER JOIN dbo.LS_005_01_INVLINES e WITH (NOLOCK) ON e.LREF = i.LREF;

    PRINT '=== GELIR SRC<>EN ornek ===';
    SELECT TOP 30
        i.LREF,
        i.SRC_G, CONVERT(DECIMAL(18,2), e.GRANDTOTAL) AS EN_G,
        i.SRC_T, CONVERT(DECIMAL(18,2), e.TLTOTAL) AS EN_T,
        i.SRC_TAX, CONVERT(DECIMAL(18,2), e.TAX) AS EN_TAX
    FROM #il i
    INNER JOIN dbo.LS_005_01_INVLINES e WITH (NOLOCK) ON e.LREF = i.LREF
    WHERE i.SRC_G <> CONVERT(DECIMAL(18,2), ISNULL(e.GRANDTOTAL, 0))
       OR i.SRC_T <> CONVERT(DECIMAL(18,2), ISNULL(e.TLTOTAL, 0))
       OR i.SRC_TAX <> CONVERT(DECIMAL(18,2), ISNULL(e.TAX, 0))
    ORDER BY ABS(i.SRC_G - CONVERT(DECIMAL(18,2), ISNULL(e.GRANDTOTAL, 0))) DESC;
END
ELSE
    PRINT 'izgazMGR.dbo.LS_INVLINES yok — gelir satir diag atlandi';

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 01_diag bitti';
GO
