/* ============================================================
   FILE : hotfix/02_patch_resync_amounts_from_ov.sql
   Amac : SRC(OV) DEC2 <> EN ise energy tutarlarini OV'den geri yaz
          (tahsilat PT + TYPE=101 fis). Idempotent.

   @DRY_RUN = 1 → sadece aday sayisi
   @DRY_RUN = 0 → UPDATE

   Calistir: PG-098 local / SSMS energy
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @DRY_RUN BIT = 1;          -- <<< once 1, sonra 0
DECLARE @Msg     NVARCHAR(400);
DECLARE @N       INT;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121)
    + ' | 02_patch DRY_RUN=' + CAST(@DRY_RUN AS VARCHAR(1));

/* ---------- A) PAYTRANS (IOCODE=1 overlay) ---------- */
IF OBJECT_ID('tempdb..#fixPay') IS NOT NULL DROP TABLE #fixPay;
CREATE TABLE #fixPay (
    LREF INT NOT NULL PRIMARY KEY,
    AMT  DECIMAL(18,2) NOT NULL
);

INSERT INTO #fixPay (LREF, AMT)
SELECT
    CAST(TRY_CAST(s.LREF AS BIGINT) AS INT),
    CONVERT(DECIMAL(18,2), s.PAYABLETOTAL)
FROM izgazMGR.dbo.LS_OV_PAY_PT s WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_PAYTRANS e WITH (NOLOCK)
    ON e.LREF = CAST(TRY_CAST(s.LREF AS BIGINT) AS INT)
WHERE TRY_CAST(s.LREF AS BIGINT) BETWEEN 1 AND 2147483647
  AND CONVERT(DECIMAL(18,2), s.PAYABLETOTAL)
      <> CONVERT(DECIMAL(18,2), e.PAYABLETOTAL)
OPTION (RECOMPILE, MAXDOP 8);

SET @N = @@ROWCOUNT;
SET @Msg = N'PAY aday (SRC<>EN)=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @DRY_RUN = 0 AND @N > 0
BEGIN
    UPDATE e
    SET e.PAYABLETOTAL = CONVERT(FLOAT, f.AMT),
        e.TLTOTAL      = CONVERT(FLOAT, f.AMT),
        e.CURTOTAL     = CONVERT(FLOAT, f.AMT),
        e.GRANDTOTAL   = CONVERT(FLOAT, f.AMT)
    FROM dbo.LS_005_01_PAYTRANS e
    INNER JOIN #fixPay f ON f.LREF = e.LREF
    OPTION (RECOMPILE, MAXDOP 4);

    SET @Msg = N'PAY updated=' + CAST(@@ROWCOUNT AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END

/* ---------- B) TYPE=101 TAH INV ---------- */
IF OBJECT_ID('tempdb..#fixInv') IS NOT NULL DROP TABLE #fixInv;
CREATE TABLE #fixInv (
    LREF INT NOT NULL PRIMARY KEY,
    PAYABLE DECIMAL(18,2) NOT NULL,
    TL      DECIMAL(18,2) NOT NULL,
    GRAND   DECIMAL(18,2) NOT NULL,
    AMOUNT  DECIMAL(18,2) NULL
);

INSERT INTO #fixInv (LREF, PAYABLE, TL, GRAND, AMOUNT)
SELECT
    CAST(s.LREF AS INT),
    CONVERT(DECIMAL(18,2), s.PAYABLETOTAL),
    CONVERT(DECIMAL(18,2), s.TLTOTAL),
    CONVERT(DECIMAL(18,2), s.GRANDTOTAL),
    CONVERT(DECIMAL(18,2), s.AMOUNT)
FROM izgazMGR.dbo.LS_OV_TAH_INVOICE s WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVOICE e WITH (NOLOCK)
    ON e.LREF = CAST(s.LREF AS INT)
WHERE s.LREF BETWEEN 1 AND 2147483647
  AND (
        CONVERT(DECIMAL(18,2), s.PAYABLETOTAL) <> CONVERT(DECIMAL(18,2), e.PAYABLETOTAL)
     OR CONVERT(DECIMAL(18,2), s.TLTOTAL)      <> CONVERT(DECIMAL(18,2), e.TLTOTAL)
     OR CONVERT(DECIMAL(18,2), s.GRANDTOTAL)   <> CONVERT(DECIMAL(18,2), e.GRANDTOTAL)
  )
OPTION (RECOMPILE, MAXDOP 8);

SET @N = @@ROWCOUNT;
SET @Msg = N'TAH INV aday (SRC<>EN)=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @DRY_RUN = 0 AND @N > 0
BEGIN
    UPDATE e
    SET e.PAYABLETOTAL = CONVERT(FLOAT, f.PAYABLE),
        e.TLTOTAL      = CONVERT(FLOAT, f.TL),
        e.CURTOTAL     = CONVERT(FLOAT, f.TL),
        e.GRANDTOTAL   = CONVERT(FLOAT, f.GRAND),
        e.AMOUNT       = CONVERT(FLOAT, ISNULL(f.AMOUNT, f.PAYABLE))
    FROM dbo.LS_005_01_INVOICE e
    INNER JOIN #fixInv f ON f.LREF = e.LREF
    OPTION (RECOMPILE, MAXDOP 4);

    SET @Msg = N'TAH INV updated=' + CAST(@@ROWCOUNT AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END

/* ---------- C) GELIR INVLINES (MGR) — sadece fark varsa ---------- */
IF OBJECT_ID('izgazMGR.dbo.LS_INVLINES', 'U') IS NOT NULL
BEGIN
    IF OBJECT_ID('tempdb..#fixIl') IS NOT NULL DROP TABLE #fixIl;
    CREATE TABLE #fixIl (
        LREF INT NOT NULL PRIMARY KEY,
        TL   DECIMAL(18,2) NOT NULL,
        TAX  DECIMAL(18,2) NOT NULL,
        GRAND DECIMAL(18,2) NOT NULL,
        AMT  DECIMAL(18,2) NULL
    );

    INSERT INTO #fixIl (LREF, TL, TAX, GRAND, AMT)
    SELECT
        CAST(TRY_CAST(s.LREF AS BIGINT) AS INT),
        CONVERT(DECIMAL(18,2), ISNULL(s.TLTOTAL, 0)),
        CONVERT(DECIMAL(18,2), ISNULL(s.TAX, 0)),
        CONVERT(DECIMAL(18,2), ISNULL(s.GRANDTOTAL, 0)),
        CONVERT(DECIMAL(18,2), ISNULL(s.AMOUNT, s.GRANDTOTAL))
    FROM izgazMGR.dbo.LS_INVLINES s WITH (NOLOCK)
    INNER JOIN dbo.LS_005_01_INVLINES e WITH (NOLOCK)
        ON e.LREF = CAST(TRY_CAST(s.LREF AS BIGINT) AS INT)
    WHERE TRY_CAST(s.LREF AS BIGINT) BETWEEN 1 AND 2147483647
      AND (
            CONVERT(DECIMAL(18,2), ISNULL(s.GRANDTOTAL, 0)) <> CONVERT(DECIMAL(18,2), ISNULL(e.GRANDTOTAL, 0))
         OR CONVERT(DECIMAL(18,2), ISNULL(s.TLTOTAL, 0))    <> CONVERT(DECIMAL(18,2), ISNULL(e.TLTOTAL, 0))
         OR CONVERT(DECIMAL(18,2), ISNULL(s.TAX, 0))        <> CONVERT(DECIMAL(18,2), ISNULL(e.TAX, 0))
      )
    OPTION (RECOMPILE, MAXDOP 8);

    SET @N = @@ROWCOUNT;
    SET @Msg = N'INVLINES aday (SRC<>EN)=' + CAST(@N AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    IF @DRY_RUN = 0 AND @N > 0
    BEGIN
        UPDATE e
        SET e.TLTOTAL    = CONVERT(FLOAT, f.TL),
            e.TAX        = CONVERT(FLOAT, f.TAX),
            e.GRANDTOTAL = CONVERT(FLOAT, f.GRAND),
            e.AMOUNT     = CONVERT(FLOAT, ISNULL(f.AMT, f.GRAND))
        FROM dbo.LS_005_01_INVLINES e
        INNER JOIN #fixIl f ON f.LREF = e.LREF
        OPTION (RECOMPILE, MAXDOP 4);

        SET @Msg = N'INVLINES updated=' + CAST(@@ROWCOUNT AS VARCHAR(20));
        RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
    END
END

IF @DRY_RUN = 1
    RAISERROR('DRY_RUN=1 — UPDATE yapilmadi. @DRY_RUN=0 ile tekrar calistirin.', 0, 1) WITH NOWAIT;
ELSE
    RAISERROR('02_patch OK', 0, 1) WITH NOWAIT;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 02_patch bitti';
GO
