/* ============================================================
   hotfix / 04 — KISMI borc PAYTRANS sync (v09 R32)
   Ortam : energy (MSSQL) | Kaynak: izgazMGR.LS_OV_KISMI_HDR
   Onkosul: 590 KISMI HDR uygulanmis (INV.PAYABLE = HDR)
   Yapmaz: INVLINES / HDR / IADE; sadece IOCODE=0 PT UPDATE + eksik INSERT

   @DRY_RUN = 1 → sayim; 0 → uygula
   ============================================================ */
USE energy;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @DRY_RUN BIT = 1;   -- 1=say, 0=uygula
DECLARE @AGR_ID  BIGINT = NULL; -- NULL=full
DECLARE @Upd INT = 0, @Ins INT = 0, @Miss INT = 0, @Diff INT = 0;

IF OBJECT_ID('izgazMGR.dbo.LS_OV_KISMI_HDR', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.dbo.LS_OV_KISMI_HDR yok.', 16, 1);
    RETURN;
END;

SELECT
    @Diff = COUNT(*)
FROM izgazMGR.dbo.LS_OV_KISMI_HDR h WITH (NOLOCK)
INNER JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = CAST(h.LREF AS INT)
WHERE (@AGR_ID IS NULL OR h.ABYS_AGREEMENT_ID = @AGR_ID)
  AND ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND (
        CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) <> CONVERT(DECIMAL(18,2), h.PAYABLETOTAL)
     OR CONVERT(DECIMAL(18,2), pt.GRANDTOTAL)   <> CONVERT(DECIMAL(18,2), h.GRANDTOTAL)
      );

SELECT
    @Miss = COUNT(*)
FROM izgazMGR.dbo.LS_OV_KISMI_HDR h WITH (NOLOCK)
INNER JOIN energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.LREF = CAST(h.LREF AS INT)
WHERE (@AGR_ID IS NULL OR h.ABYS_AGREEMENT_ID = @AGR_ID)
  AND ISNULL(inv.IOCODE, 0) = 0
  AND NOT EXISTS (
        SELECT 1
        FROM energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
      );

PRINT 'KISMI PT payable/grand DIFF (upd aday)=' + CAST(@Diff AS VARCHAR(20));
PRINT 'KISMI PT MISSING (insert aday)=' + CAST(@Miss AS VARCHAR(20));

IF @DRY_RUN = 1
BEGIN
    PRINT 'DRY_RUN=1 — degisiklik yok. Uygulamak icin @DRY_RUN=0.';
    RETURN;
END;

BEGIN TRAN;

UPDATE pt
SET pt.TLTOTAL = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.TLTOTAL)),
    pt.TAX = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.TAX)),
    pt.GRANDTOTAL = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.GRANDTOTAL)),
    pt.PAYABLETOTAL = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.PAYABLETOTAL)),
    pt.CURTOTAL = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.GRANDTOTAL))
FROM energy.dbo.LS_005_01_PAYTRANS pt
INNER JOIN izgazMGR.dbo.LS_OV_KISMI_HDR h WITH (NOLOCK)
    ON pt.INVOICEREF = CAST(h.LREF AS INT)
WHERE (@AGR_ID IS NULL OR h.ABYS_AGREEMENT_ID = @AGR_ID)
  AND ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND (
        CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) <> CONVERT(DECIMAL(18,2), h.PAYABLETOTAL)
     OR CONVERT(DECIMAL(18,2), pt.GRANDTOTAL)   <> CONVERT(DECIMAL(18,2), h.GRANDTOTAL)
     OR CONVERT(DECIMAL(18,2), pt.TLTOTAL)      <> CONVERT(DECIMAL(18,2), h.TLTOTAL)
      )
OPTION (RECOMPILE, MAXDOP 24);
SET @Upd = @@ROWCOUNT;

INSERT INTO energy.dbo.LS_005_01_PAYTRANS WITH (TABLOCK) (
    INVOICEREF, INVLINEREF, DATE_, [TYPE], CLIENTREF, CLIENT_TYPE,
    IOCODE, TLTOTAL, PAID, DUEDATE, PAYTYPE, CURID, CURRATE, CURTOTAL,
    CROSSREF, TRANSTYPE, CANCELED, TAX, GRANDTOTAL, LINETYPE, INST_NR,
    PAYABLETOTAL, ADDDATE, ADDUSER, CANCELLATIONPAYMENT, BN_TYPE, XTYPE, PAYCURID,
    ABYS_ID, ABYS_ACCOUNT_ID, ABYS_AGREEMENT_ID, ABYS_INVOICE_LREF
)
SELECT
    inv.LREF,
    NULL,
    inv.DATE_,
    inv.[TYPE],
    inv.CLIENTREF,
    inv.OWNERTYPE,
    CAST(0 AS TINYINT),
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.TLTOTAL)),
    CAST(0 AS FLOAT),
    inv.DUEDATE,
    CAST(174 AS INT),
    ISNULL(inv.CURID, 160),
    CAST(1 AS FLOAT),
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.GRANDTOTAL)),
    NULL,
    CAST(113 AS INT),
    CAST(0 AS BIT),
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.TAX)),
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.GRANDTOTAL)),
    CAST(103 AS INT),
    CAST(0 AS INT),
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), h.PAYABLETOTAL)),
    inv.ADDDATE,
    ISNULL(inv.ADDUSER, 20001),
    CAST(0 AS INT),
    TRY_CAST(inv.BN_TYPE AS INT),
    ISNULL(inv.XTYPE, 1),
    ISNULL(inv.CURID, 160),
    inv.ABYS_ID,
    inv.ABYS_ACCOUNT_ID,
    inv.ABYS_AGREEMENT_ID,
    inv.LREF
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN izgazMGR.dbo.LS_OV_KISMI_HDR h WITH (NOLOCK)
    ON inv.LREF = CAST(h.LREF AS INT)
WHERE (@AGR_ID IS NULL OR h.ABYS_AGREEMENT_ID = @AGR_ID)
  AND ISNULL(inv.IOCODE, 0) = 0
  AND NOT EXISTS (
        SELECT 1
        FROM energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
      )
OPTION (RECOMPILE, MAXDOP 24);
SET @Ins = @@ROWCOUNT;

COMMIT;

PRINT 'KISMI PT UPD=' + CAST(@Upd AS VARCHAR(20)) + ' INS=' + CAST(@Ins AS VARCHAR(20));
GO
