/* ============================================================
   FILE : 613_INSTALLMENT_CANCEL_VERIFY.sql
   Iptal taksit → PAYTRANS engeli dogrulama (energy)

   Onkosul: 610/611/613 deploy + CANCEL_NORMALIZE (+ istege bagli SPLIT) calisti

   Beklenen (iptal planli fatura):
     - Aktif taksit PT (INST_NR>0, CANCELED=0) YOK
     - Ana borc PT INST_NR=0: CANCELED=0
     - INVOICE.INSTALLMENT_PLAN_REF IS NULL
     - Odeme varsa IOCODE=1 normal tahsilat (CROSSREF → ana PT)
   ============================================================ */
USE energy;
GO

SET NOCOUNT ON;

DECLARE @AGR_ID BIGINT = NULL;  -- ornek: 978259 / 1192595; NULL = tum iptal planli
DECLARE @INV_LREF INT = NULL;   -- ornek: 150404069; NULL = AGR/iptal seti

/* --- 1) Iptal plan ozeti --- */
SELECT
    pl.ABYS_AGREEMENT_ID AS AGR_ID,
    pl.PLAN_ID,
    COUNT(*) AS PLAN_ROWS,
    MAX(pl.ISACTIVE) AS ISACTIVE_MAX,
    MAX(CASE WHEN pl.ABYS_CANCELLATION_DATE IS NOT NULL THEN 1 ELSE 0 END) AS HAS_CANCEL_DATE,
    MAX(CASE WHEN pl.ABYS_CANCEL_CAUSE_ID IS NOT NULL THEN 1 ELSE 0 END) AS HAS_CANCEL_CAUSE,
    MAX(CASE WHEN pl.ABYS_CANCELLATION_USER_ID IS NOT NULL THEN 1 ELSE 0 END) AS HAS_CANCEL_USER,
    SUM(CASE WHEN pl.PAYTRANS_REF IS NOT NULL THEN 1 ELSE 0 END) AS PAYTRANS_REF_CNT
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK)
WHERE pl.ABYS_ID IS NOT NULL
  AND (
        pl.ABYS_CANCELLATION_DATE IS NOT NULL
     OR pl.ABYS_CANCEL_CAUSE_ID IS NOT NULL
     OR pl.ABYS_CANCELLATION_USER_ID IS NOT NULL
     OR ISNULL(pl.ISACTIVE, 0) = 0
      )
  AND (@AGR_ID IS NULL OR pl.ABYS_AGREEMENT_ID = @AGR_ID)
GROUP BY pl.ABYS_AGREEMENT_ID, pl.PLAN_ID
ORDER BY AGR_ID, PLAN_ID;

/* --- 2) Iptal planina bagli faturalar --- */
IF OBJECT_ID('tempdb..#INV') IS NOT NULL DROP TABLE #INV;
SELECT
    inv.LREF AS INV_LREF,
    inv.ABYS_AGREEMENT_ID,
    inv.INSTALLMENT_PLAN_REF,
    inv.ABYS_INSTALLMENT_ID,
    inv.PAYABLETOTAL,
    inv.CLOSED
INTO #INV
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND (@INV_LREF IS NULL OR inv.LREF = @INV_LREF)
  AND (@AGR_ID IS NULL OR inv.ABYS_AGREEMENT_ID = @AGR_ID)
  AND ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF) IS NOT NULL
  AND EXISTS (
        SELECT 1
        FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK)
        WHERE pl.ABYS_ID IS NOT NULL
          AND (
                pl.PLAN_ID = ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF)
             OR pl.ABYS_INSTALLMENT_ID = ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF)
              )
          AND (
                pl.ABYS_CANCELLATION_DATE IS NOT NULL
             OR pl.ABYS_CANCEL_CAUSE_ID IS NOT NULL
             OR pl.ABYS_CANCELLATION_USER_ID IS NOT NULL
             OR ISNULL(pl.ISACTIVE, 0) = 0
              )
      );

SELECT
    i.INV_LREF,
    i.ABYS_AGREEMENT_ID,
    i.INSTALLMENT_PLAN_REF,
    i.ABYS_INSTALLMENT_ID,
    i.PAYABLETOTAL,
    CASE WHEN i.INSTALLMENT_PLAN_REF IS NULL THEN N'OK' ELSE N'FAIL_REF' END AS REF_CHK
FROM #INV i
ORDER BY i.ABYS_AGREEMENT_ID, i.INV_LREF;

/* --- 3) PAYTRANS gate (iptal faturalar) --- */
SELECT
    i.INV_LREF,
    SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) AS ACTIVE_TAKSIT_PT,
    SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) AS ACTIVE_MAIN_PT,
    SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 THEN ISNULL(pt.CANCELED,0) ELSE 0 END) AS MAIN_CANCELED_FLAG,
    SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN CONVERT(DECIMAL(18,2),ISNULL(pt.PAID,0)) ELSE 0 END) AS MAIN_PAID,
    SUM(CASE WHEN ISNULL(pt.IOCODE,0)=1 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) AS PAY_PT_CNT,
    CASE
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) > 0
            THEN N'FAIL_TAKSIT_PT'
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) < 1
            THEN N'FAIL_NO_MAIN'
        WHEN MAX(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN CONVERT(DECIMAL(18,2),ISNULL(pt.PAID,0)) END) IS NOT NULL
         AND MAX(i.INSTALLMENT_PLAN_REF) IS NOT NULL
            THEN N'FAIL_REF'
        WHEN MAX(i.INSTALLMENT_PLAN_REF) IS NOT NULL
            THEN N'FAIL_REF'
        ELSE N'OK'
    END AS GATE
FROM #INV i
LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = i.INV_LREF
GROUP BY i.INV_LREF
ORDER BY GATE DESC, i.INV_LREF;

/* --- 4) Detay (tek fatura) --- */
IF @INV_LREF IS NOT NULL
BEGIN
    SELECT LREF, INVOICEREF, IOCODE, INST_NR, PAYTYPE, PAYABLETOTAL, PAID, CANCELED, CROSSREF, EXPLAIN
    FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
    WHERE INVOICEREF = @INV_LREF
    ORDER BY IOCODE, INST_NR, LREF;

    SELECT LREF, INSTALLMENT_PLAN_REF, ABYS_INSTALLMENT_ID, PAYABLETOTAL, CLOSED
    FROM energy.dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE LREF = @INV_LREF;
END
GO
