-- =============================================================================
-- prodREADY_ENERGY3007 / 01_PILOT_SPOT_197168.sql
-- pilotEnergyChain APPLY sonrası — tek AGR spot (read-only)
-- AGR = 197168
-- Önkoşul: izgazMGR dolu + Wizard Clean APPLY tamam
-- =============================================================================
USE energy;
GO
SET NOCOUNT ON;

DECLARE @Agr BIGINT = 197168;

PRINT '========== 0) SUMMARY COUNTS (ENERGY) ==========';
SELECT
  (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE (OWNERREF = @Agr OR ABYS_AGREEMENT_ID = @Agr) AND ISNULL(CANCELED,0)=0 AND ISNULL(IOCODE,0)=0) AS enInvDebt,
  (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE (OWNERREF = @Agr OR ABYS_AGREEMENT_ID = @Agr) AND ISNULL(CANCELED,0)=0 AND ISNULL(IOCODE,0)=1) AS enInvTahsilat,
  (SELECT COUNT(*) FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
   WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
     AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.CANCELED,0)=0) AS enPaytransDebt,
  (SELECT COUNT(*) FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
   WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
     AND ISNULL(pt.IOCODE,0)=1 AND ISNULL(pt.CANCELED,0)=0) AS enPaytransTahsilat,
  (SELECT COUNT(*) FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
   WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
     AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0) AS enInstNr,
  (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE (OWNERREF = @Agr OR ABYS_AGREEMENT_ID = @Agr)
      AND ISNULL(INSTALLMENT_PLAN_REF,0)>0) AS enInstPlanWired;

PRINT 'PASS: enPaytransTahsilat > 0, enInstNr > 0 (taksit varsa)';

PRINT '========== 1) MGR vs ENERGY (AGR) ==========';
SELECT
  (SELECT COUNT(*) FROM izgazMGR.dbo.LS_INVOICE WITH (NOLOCK)
    WHERE ABYS_AGREEMENT_ID = @Agr) AS mgrInv,
  (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE (OWNERREF = @Agr OR ABYS_AGREEMENT_ID = @Agr) AND ISNULL(IOCODE,0)=0) AS enInvDebt,
  (SELECT COUNT(*) FROM izgazMGR.dbo.LS_OV_PAY_PT WITH (NOLOCK)
    WHERE ABYS_AGREEMENT_ID = @Agr) AS mgrOvPayPt,
  CASE WHEN OBJECT_ID('izgazMGR.dbo.LS_INSTALLMENT_PLAN_PAY','U') IS NULL THEN NULL
       ELSE (SELECT COUNT(*) FROM izgazMGR.dbo.LS_INSTALLMENT_PLAN_PAY WITH (NOLOCK)
             WHERE AGREEMENT_ID = @Agr AND ISNULL(IS_PAID,0)=1) END AS mgrIppPaid;

PRINT '========== 2) Taksitli fatura + borç PT (PAID/banka) ==========';
SELECT inv.LREF, inv.CLOSED, inv.LASTPAIDDATE, inv.BANKREF, inv.BANK_RECORD_REF,
       inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID,
       pt.LREF AS PT, pt.INST_NR, pt.PAYTYPE, pt.PAYABLETOTAL, pt.PAID,
       pt.BANKREF AS PT_BANK, pt.BANK_RECORD_REF AS PT_REC,
       pt.LASTPAIDDATE AS PT_LPD, pt.XTYPE,
       CASE WHEN ISNULL(pt.PAID,0) + 0.01 >= ISNULL(pt.PAYABLETOTAL,0) AND ISNULL(pt.PAYABLETOTAL,0) > 0
            THEN 'PAID_OK' ELSE 'OPEN_OR_PARTIAL' END AS paidFlag
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
  ON pt.INVOICEREF = inv.LREF AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.CANCELED,0)=0
WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
  AND ISNULL(inv.INSTALLMENT_PLAN_REF,0) > 0
ORDER BY inv.LREF, pt.INST_NR;

PRINT '========== 3) Tahsilat CROSSREF (IOCODE=1 → borç PT) ==========';
SELECT inv.LREF AS invLref, debt.LREF AS debtPt, debt.INST_NR,
       debt.PAYABLETOTAL, debt.PAID AS debtPaid, pay.LREF AS payPt,
       pay.PAID AS payPaid, pay.PAYTYPE, pay.BANKREF, pay.BANK_RECORD_REF,
       pay.LASTPAIDDATE, pay.XTYPE,
       CASE WHEN ISNULL(debt.PAID,0) + 0.01 >= ISNULL(debt.PAYABLETOTAL,0)
             AND ISNULL(pay.PAID,0) > 0 THEN 'TAH_OK' ELSE 'TAH_GAP' END AS tahFlag
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
JOIN dbo.LS_005_01_PAYTRANS debt WITH (NOLOCK)
  ON debt.INVOICEREF = inv.LREF AND ISNULL(debt.IOCODE,0)=0 AND ISNULL(debt.INST_NR,0)>0
JOIN dbo.LS_005_01_PAYTRANS pay WITH (NOLOCK)
  ON pay.CROSSREF = debt.LREF AND ISNULL(pay.IOCODE,0)=1
WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
ORDER BY inv.LREF, debt.INST_NR;

PRINT '========== 4) CLOSED ama taksit unpaid (gap) ==========';
SELECT inv.LREF, pt.LREF AS debtPt, pt.INST_NR, pt.PAYABLETOTAL, pt.PAID
FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
  AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.CANCELED,0)=0 AND ISNULL(pt.INST_NR,0)>0
  AND ISNULL(inv.CLOSED,0)=1
  AND ISNULL(pt.PAID,0) + 0.01 < ISNULL(pt.PAYABLETOTAL,0);

PRINT '========== 5) FRK soft: AFL mig vs ENERGY açık (AGR) ==========';
IF OBJECT_ID('izgazMGR.dbo.LS_AFL_OPEN_DEBT','U') IS NOT NULL
SELECT
  (SELECT COUNT(*) FROM izgazMGR.dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    WHERE a.MIG_IN_SCOPE = 1 AND a.SOZLESME_HESABI = @Agr) AS aflMigOpen,
  (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    WHERE (OWNERREF = @Agr OR ABYS_AGREEMENT_ID = @Agr)
      AND ISNULL(IOCODE,0)=0 AND ISNULL(CANCELED,0)=0 AND ISNULL(CLOSED,0)=0) AS enOpenDebt;
ELSE
  PRINT 'LS_AFL_OPEN_DEBT yok — FRK skip';

PRINT '========== 6) Tüm borç faturalar (taksitli + düz) ==========';
SELECT inv.LREF, inv.TYPE, inv.IOCODE, inv.CLOSED, inv.PAYABLETOTAL,
       inv.LASTPAIDDATE, inv.BANKREF, inv.INSTALLMENT_PLAN_REF
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE (inv.OWNERREF = @Agr OR inv.ABYS_AGREEMENT_ID = @Agr)
  AND ISNULL(inv.CANCELED,0)=0
ORDER BY inv.IOCODE, inv.LREF;

PRINT '========== PILOT SPOT 197168 DONE ==========';
PRINT 'Pass: ödenen satırda debt.PAID≈PAYABLETOTAL + tahsilat pay.PAID; hepsi ödendiyse CLOSED=1';
GO
