/* ============================================================
   prodREADY_ENERGY3007 / 35b_fix_bankref_1034469.sql
   Çift resolve düzeltmesi (SMS BANK_ID → LS_BANK.LREF bir kez).
   Kaynak: izgazMGR.LS_PAYMENT.BANKA_ID (SMS CS_ACCOUNT_ACTION.BANK_ID)
           yoksa LS_OV_PAY_PT / LS_OV_TAH_INVOICE / LS_INVOICE.BANKREF
   AGR=1034469 — APPLY
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @AGR BIGINT = 1034469;
DECLARE @nPt INT = 0, @nTah INT = 0, @nMain INT = 0, @nDebt INT = 0;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 35b FIX BANKREF AGR=' + CAST(@AGR AS VARCHAR(20));

IF OBJECT_ID('dbo.LS_BANK', 'U') IS NULL
   OR COL_LENGTH('dbo.LS_BANK', 'ABYS_ID') IS NULL
BEGIN
    RAISERROR('LS_BANK.ABYS_ID yok', 16, 1);
    RETURN;
END

BEGIN TRAN;

/* ---- 1) Tahsilat PAY_PT: LS_PAYMENT.BANKA_ID tercih ---- */
IF OBJECT_ID('izgazMGR.dbo.LS_PAYMENT', 'U') IS NOT NULL
BEGIN
    UPDATE pt
    SET pt.BANKREF = b.LREF
    FROM dbo.LS_005_01_PAYTRANS pt
    INNER JOIN izgazMGR.dbo.LS_PAYMENT p WITH (NOLOCK)
        ON p.PAY_LREF = pt.ABYS_ID AND p.SOZLESME = @AGR
    INNER JOIN dbo.LS_BANK b ON b.ABYS_ID = p.BANKA_ID
    WHERE p.BANKA_ID IS NOT NULL
      AND pt.ABYS_ID IS NOT NULL
      AND (
            pt.ABYS_AGREEMENT_ID = @AGR
         OR EXISTS (
                SELECT 1 FROM dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
                WHERE m.ENERGY_LREF = pt.LREF AND m.OV_KIND = N'PAY_PT'
                  AND m.ABYS_AGREEMENT_ID = @AGR
            )
          )
      AND (pt.BANKREF IS NULL OR pt.BANKREF <> b.LREF);
    SET @nPt = @@ROWCOUNT;
END

/* fallback: OV_PAY_PT.BANKREF (SMS id) */
UPDATE pt
SET pt.BANKREF = b.LREF
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN izgazMGR.dbo.LS_OV_PAY_PT s WITH (NOLOCK) ON s.ABYS_ID = pt.ABYS_ID
INNER JOIN dbo.LS_BANK b ON b.ABYS_ID = s.BANKREF
WHERE s.ABYS_AGREEMENT_ID = @AGR
  AND s.BANKREF IS NOT NULL
  AND pt.ABYS_ID IS NOT NULL
  AND (pt.BANKREF IS NULL OR pt.BANKREF <> b.LREF);
SET @nPt = @nPt + @@ROWCOUNT;

/* ---- 2) TYPE=101 TAH_INV ---- */
UPDATE inv
SET inv.BANKREF = b.LREF
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN izgazMGR.dbo.LS_OV_TAH_INVOICE t WITH (NOLOCK)
    ON t.LREF = inv.LREF OR (t.ABYS_ID IS NOT NULL AND t.ABYS_ID = inv.ABYS_ID)
INNER JOIN dbo.LS_BANK b ON b.ABYS_ID = t.BANKREF
WHERE t.ABYS_AGREEMENT_ID = @AGR
  AND ISNULL(inv.TYPE, 0) = 101
  AND t.BANKREF IS NOT NULL
  AND (inv.OWNERREF = @AGR OR inv.ABYS_AGREEMENT_ID = @AGR)
  AND (inv.BANKREF IS NULL OR inv.BANKREF <> b.LREF);
SET @nTah = @@ROWCOUNT;

/* ---- 3) MAIN borç INV (MGR LS_INVOICE SMS BANKREF) ---- */
UPDATE inv
SET inv.BANKREF = b.LREF,
    inv.BANK_RECORD_REF = COALESCE(inv.BANK_RECORD_REF, m.BANK_RECORD_REF)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN izgazMGR.dbo.LS_INVOICE m WITH (NOLOCK) ON m.LREF = inv.LREF
INNER JOIN dbo.LS_BANK b ON b.ABYS_ID = m.BANKREF
WHERE m.ABYS_AGREEMENT_ID = @AGR
  AND ISNULL(inv.TYPE, 0) <> 101
  AND ISNULL(inv.IOCODE, 0) = 0
  AND m.BANKREF IS NOT NULL
  AND (inv.OWNERREF = @AGR OR inv.ABYS_AGREEMENT_ID = @AGR)
  AND (inv.BANKREF IS NULL OR inv.BANKREF <> b.LREF);
SET @nMain = @@ROWCOUNT;

/* ---- 4) Borç PT: parent INV bankası senkron ---- */
UPDATE d
SET d.BANKREF = inv.BANKREF,
    d.BANK_RECORD_REF = COALESCE(d.BANK_RECORD_REF, inv.BANK_RECORD_REF)
FROM dbo.LS_005_01_PAYTRANS d
INNER JOIN dbo.LS_005_01_INVOICE inv ON inv.LREF = d.INVOICEREF
WHERE ISNULL(d.IOCODE, 0) = 0
  AND inv.BANKREF IS NOT NULL
  AND (inv.OWNERREF = @AGR OR inv.ABYS_AGREEMENT_ID = @AGR)
  AND (d.BANKREF IS NULL OR d.BANKREF <> inv.BANKREF);
SET @nDebt = @@ROWCOUNT;

COMMIT TRAN;

PRINT 'UPDATED pt~' + CAST(@nPt AS VARCHAR(20))
    + ' tah=' + CAST(@nTah AS VARCHAR(20))
    + ' main=' + CAST(@nMain AS VARCHAR(20))
    + ' debtPt=' + CAST(@nDebt AS VARCHAR(20));

/* ---- Verify vs LS_PAYMENT (SMS export bank) ---- */
SELECT
    SUM(CASE WHEN pt.BANKREF = b.LREF THEN 1 ELSE 0 END) AS ok_bank,
    SUM(CASE WHEN p.BANKA_ID IS NOT NULL AND (pt.BANKREF IS NULL OR pt.BANKREF <> b.LREF) THEN 1 ELSE 0 END) AS mismatch,
    COUNT(*) AS n
FROM izgazMGR.dbo.LS_PAYMENT p WITH (NOLOCK)
INNER JOIN dbo.MIG_OV_ID_MAP m
    ON m.OV_KIND = N'PAY_PT' AND m.ABYS_AGREEMENT_ID = @AGR
   AND (m.ENERGY_LREF = TRY_CAST(p.PAY_LREF AS INT) OR m.SRC_KEY LIKE N'PAY_PT|' + CAST(p.PAY_LREF AS NVARCHAR(20)) + N'|%')
INNER JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF = m.ENERGY_LREF
LEFT JOIN dbo.LS_BANK b ON b.ABYS_ID = p.BANKA_ID
WHERE p.SOZLESME = @AGR AND ISNULL(p.CANCELED, 0) = 0 AND p.BANKA_ID IS NOT NULL;

SELECT TOP 15
    p.BANK_RECORD_REF AS dekont,
    p.BANKA_ID AS sms_bank,
    bWant.SHORTNAME AS want,
    pt.BANKREF AS got_lref,
    bGot.SHORTNAME AS got,
    p.VEZNE_ID AS vezne
FROM izgazMGR.dbo.LS_PAYMENT p WITH (NOLOCK)
INNER JOIN dbo.MIG_OV_ID_MAP m
    ON m.OV_KIND = N'PAY_PT' AND m.ABYS_AGREEMENT_ID = @AGR
   AND m.SRC_KEY LIKE N'PAY_PT|' + CAST(p.PAY_LREF AS NVARCHAR(20)) + N'|%'
INNER JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF = m.ENERGY_LREF
LEFT JOIN dbo.LS_BANK bWant ON bWant.ABYS_ID = p.BANKA_ID
LEFT JOIN dbo.LS_BANK bGot ON bGot.LREF = pt.BANKREF
WHERE p.SOZLESME = @AGR
  AND ISNULL(p.CANCELED, 0) = 0
  AND p.BANKA_ID IS NOT NULL
ORDER BY p.PAY_DATE DESC;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 35b FIX BANKREF DONE';
GO
