/* =============================================================================
   prodREADY_ENERGY3007 / 91e_debt_pt_findings_heal.sql
   ---------------------------------------------------------------
   DUP_2X / GHOST debt PT soft-cancel + INST PAID clamp (residual heal).

   @INV_CSV:
     NULL  = TUM (global) — varsayilan
     N'19279198,19622456' = daraltma

   Adimlar:
     1) DRY ozet (DUP/GHOST + INST PAID>PAYABLE)
     2) APPLY: soft-cancel DROP + CROSSREF retarget + INST PAID clamp + MAP null

   @DryRun=1 sayim; 0=apply
   sqlcmd -S 172.16.1.195 -d energy -C -I -f 65001 -i 91e_debt_pt_findings_heal.sql
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

DECLARE @DryRun BIT = 1;   /* APPLY: 0 */
DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @Eps DECIMAL(18,2) = 0.02;
DECLARE @INV_CSV NVARCHAR(MAX) = NULL;   /* NULL=tum | ornek N'19279198,19622456' */

DECLARE @Msg NVARCHAR(400);
DECLARE @N INT;
DECLARE @FilterOn BIT = 0;
DECLARE @t0 DATETIME2 = SYSDATETIME();

RAISERROR('========== 91e FINDINGS HEAL DryRun=%d ==========', 0, 1, @DryRunInt) WITH NOWAIT;

IF OBJECT_ID('tempdb..#INV') IS NOT NULL DROP TABLE #INV;
CREATE TABLE #INV (INV_LREF INT NOT NULL PRIMARY KEY);

IF @INV_CSV IS NOT NULL AND LEN(LTRIM(RTRIM(@INV_CSV))) > 0
BEGIN
    INSERT INTO #INV (INV_LREF)
    SELECT DISTINCT TRY_CAST(LTRIM(RTRIM(value)) AS INT)
    FROM STRING_SPLIT(@INV_CSV, ',')
    WHERE TRY_CAST(LTRIM(RTRIM(value)) AS INT) IS NOT NULL;

    SET @FilterOn = 1;
    SET @Msg = N'INV filter n=' + CAST((SELECT COUNT(*) FROM #INV) AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END
ELSE
BEGIN
    RAISERROR('INV filter=NULL (TUM)', 0, 1) WITH NOWAIT;
END

/* ---- 1) GHOST / DUP adaylari (INSTALLMENT_PLAN_REF IS NULL) ---- */
IF OBJECT_ID('tempdb..#DUP') IS NOT NULL DROP TABLE #DUP;
IF OBJECT_ID('tempdb..#KEEP') IS NOT NULL DROP TABLE #KEEP;

;WITH multi AS (
    SELECT pt.INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    WHERE pt.IOCODE = 0
      AND ISNULL(pt.INST_NR, 0) = 0
      AND ISNULL(pt.CANCELED, 0) = 0
      AND (
            @FilterOn = 0
         OR EXISTS (SELECT 1 FROM #INV i WHERE i.INV_LREF = pt.INVOICEREF)
          )
    GROUP BY pt.INVOICEREF
    HAVING COUNT(*) > 1
)
SELECT
    inv.LREF AS INV_LREF,
    inv.ABYS_ID AS INV_ABYS_ID,
    pt.LREF AS PT_LREF,
    pt.ABYS_ID AS PT_ABYS_ID,
    CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) AS PT_P,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID,
    CAST(ISNULL(pt.CANCELLATIONPAYMENT, 0) AS TINYINT) AS CP,
    CASE
        WHEN pt.ABYS_ID IS NOT NULL
         AND pt.ABYS_ID <> inv.ABYS_ID
         AND pt.ABYS_ID <> inv.LREF
        THEN CAST(1 AS TINYINT) ELSE CAST(0 AS TINYINT)
    END AS IS_GHOST
INTO #DUP
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN multi m ON m.INVOICEREF = inv.LREF
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND pt.IOCODE = 0
   AND ISNULL(pt.INST_NR, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND inv.INSTALLMENT_PLAN_REF IS NULL;

;WITH ranked AS (
    SELECT d.*,
        ROW_NUMBER() OVER (
            PARTITION BY d.INV_LREF
            ORDER BY
                CASE WHEN d.CP = 1 THEN 1 ELSE 0 END,
                CASE WHEN d.IS_GHOST = 1 THEN 1 ELSE 0 END,
                CASE WHEN d.PT_ABYS_ID = d.INV_ABYS_ID THEN 0
                     WHEN d.PT_ABYS_ID = d.INV_LREF THEN 1
                     ELSE 2 END,
                d.PT_LREF
        ) AS RN
    FROM #DUP d
)
SELECT INV_LREF, PT_LREF AS KEEP_PT
INTO #KEEP
FROM ranked
WHERE RN = 1 AND CP = 0 AND IS_GHOST = 0;

INSERT INTO #KEEP (INV_LREF, KEEP_PT)
SELECT d.INV_LREF, MIN(d.PT_LREF)
FROM #DUP d
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.INV_LREF = d.INV_LREF)
  AND d.CP = 0 AND d.IS_GHOST = 0 AND d.PT_ABYS_ID = d.INV_ABYS_ID
GROUP BY d.INV_LREF;

INSERT INTO #KEEP (INV_LREF, KEEP_PT)
SELECT d.INV_LREF, MIN(d.PT_LREF)
FROM #DUP d
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.INV_LREF = d.INV_LREF)
GROUP BY d.INV_LREF;

PRINT '=== DUP/GHOST ozet ===';
SELECT
    COUNT(DISTINCT d.INV_LREF) AS INV_CNT,
    COUNT(*) AS PT_CNT,
    SUM(CASE WHEN d.IS_GHOST = 1 THEN 1 ELSE 0 END) AS GHOST_PT,
    SUM(CASE WHEN k.KEEP_PT IS NULL THEN 1 ELSE 0 END) AS DROP_PT
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF;

PRINT '=== DUP/GHOST plan (TOP 50) ===';
SELECT TOP 50
       d.INV_LREF, d.PT_LREF, d.PT_ABYS_ID, d.PT_P, d.PT_PAID, d.CP, d.IS_GHOST,
       CASE WHEN k.KEEP_PT IS NULL THEN 'DROP' ELSE 'KEEP' END AS ACT
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF
ORDER BY d.INV_LREF, d.PT_LREF;

/* ---- 2) INST PAID overflow (PT uzerinden; INV NCIX kapali olsa da) ---- */
IF OBJECT_ID('tempdb..#INST_CLAMP') IS NOT NULL DROP TABLE #INST_CLAMP;

SELECT pt.LREF AS PT_LREF, pt.INVOICEREF, pt.INST_NR,
       CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) AS PAYABLE,
       CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PAID_OLD
INTO #INST_CLAMP
FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.INST_NR, 0) > 0
  AND ISNULL(pt.PAID, 0) > pt.PAYABLETOTAL + @Eps
  AND (
        @FilterOn = 0
     OR EXISTS (SELECT 1 FROM #INV i WHERE i.INV_LREF = pt.INVOICEREF)
      );

PRINT '=== INST PAID > PAYABLE ozet ===';
SELECT COUNT(*) AS PT_CNT,
       COUNT(DISTINCT INVOICEREF) AS INV_CNT,
       CONVERT(DECIMAL(18,2), SUM(PAID_OLD - PAYABLE)) AS OVER_SUM
FROM #INST_CLAMP;

PRINT '=== INST PAID > PAYABLE (TOP 50) ===';
SELECT TOP 50 PT_LREF, INVOICEREF, INST_NR, PAYABLE, PAID_OLD, PAYABLE AS PAID_NEW
FROM #INST_CLAMP
ORDER BY (PAID_OLD - PAYABLE) DESC, INVOICEREF, INST_NR;

IF @DryRun = 1
BEGIN
    RAISERROR('DRY_RUN=1 — APPLY icin @DryRun=0', 0, 1) WITH NOWAIT;
    RETURN;
END

BEGIN TRAN;

UPDATE pt
SET pt.CANCELED = CAST(1 AS BIT)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #DUP d ON d.PT_LREF = pt.LREF
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.KEEP_PT = pt.LREF);

SET @N = @@ROWCOUNT;
SET @Msg = N'SOFT-CANCEL ghost/dup PT=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE pay
SET pay.CROSSREF = k.KEEP_PT
FROM dbo.LS_005_01_PAYTRANS pay
INNER JOIN #DUP d ON d.PT_LREF = pay.CROSSREF
INNER JOIN #KEEP k ON k.INV_LREF = d.INV_LREF
WHERE ISNULL(pay.IOCODE, 0) = 1
  AND NOT EXISTS (SELECT 1 FROM #KEEP x WHERE x.KEEP_PT = pay.CROSSREF);

SET @N = @@ROWCOUNT;
SET @Msg = N'CROSSREF retarget=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE pt
SET pt.PAID = pt.PAYABLETOTAL
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #INST_CLAMP c ON c.PT_LREF = pt.LREF;

SET @N = @@ROWCOUNT;
SET @Msg = N'INST PAID clamp=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_OV_ID_MAP', 'U') IS NOT NULL
BEGIN
    UPDATE m
    SET m.ENERGY_LREF = NULL
    FROM dbo.MIG_OV_ID_MAP m
    INNER JOIN #DUP d ON d.PT_LREF = m.ENERGY_LREF
    WHERE m.OV_KIND IN (N'PAY_PT', N'CANCEL_PAY', N'CANCEL_REV')
      AND m.ENERGY_LREF IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.KEEP_PT = d.PT_LREF);

    SET @N = @@ROWCOUNT;
    SET @Msg = N'MAP ENERGY_LREF null (drop PT)=' + CAST(@N AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END

COMMIT TRAN;

PRINT '=== AFTER: hala multi INST0? ===';
SELECT COUNT(*) AS STILL_DUP_INV
FROM (
    SELECT pt.INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
    WHERE pt.IOCODE = 0
      AND ISNULL(pt.INST_NR, 0) = 0
      AND ISNULL(pt.CANCELED, 0) = 0
      AND inv.INSTALLMENT_PLAN_REF IS NULL
      AND (
            @FilterOn = 0
         OR EXISTS (SELECT 1 FROM #INV i WHERE i.INV_LREF = pt.INVOICEREF)
          )
    GROUP BY pt.INVOICEREF
    HAVING COUNT(*) > 1
) x;

PRINT '=== AFTER: hala INST PAID>PAYABLE? ===';
SELECT COUNT(*) AS STILL_OVER
FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.INST_NR, 0) > 0
  AND ISNULL(pt.PAID, 0) > pt.PAYABLETOTAL + @Eps
  AND (
        @FilterOn = 0
     OR EXISTS (SELECT 1 FROM #INV i WHERE i.INV_LREF = pt.INVOICEREF)
      );

SET @Msg = N'91e DONE elapsed_s=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
