/* =============================================================================
   prodREADY_ENERGY / 92_INV_DV_FROM_INCOME_HEAL.sql
   CREATE OR ALTER PROCEDURE dbo.SP_MIG_INV_DV_FROM_INCOME  (R23 2026-08-11)
   TYPE109/111 DV = damga gelirleri + CROSSREF tahsilat PT.
   EXEC:
     EXEC dbo.SP_MIG_INV_DV_FROM_INCOME @DryRun = 1, @Agr = NULL;
     EXEC dbo.SP_MIG_INV_DV_FROM_INCOME @DryRun = 0, @Agr = NULL;
   ============================================================================= */
USE energy;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
CREATE OR ALTER PROCEDURE dbo.SP_MIG_INV_DV_FROM_INCOME
    @DryRun BIT           = 1,
    @Agr    BIGINT        = NULL,
    @Eps    DECIMAL(18,2) = 0.02
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET IMPLICIT_TRANSACTIONS OFF;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
    DECLARE @t0 DATETIME2(3) = SYSDATETIME();
    DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
    DECLARE @Msg NVARCHAR(400);
    DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'ALL' ELSE CONVERT(VARCHAR(30), @Agr) END;
    DECLARE @N INT;
    DECLARE @NTah INT;

SET @Msg = N'========== 92 INV DV FROM INCOME DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_INV_DV_FROM_INCOME_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_INV_DV_FROM_INCOME_LOG
    (
        RUN_ID            BIGINT         NOT NULL,
        SNAPSHOT_TS       DATETIME2(3)   NOT NULL CONSTRAINT DF_MIG_INV_DV_INC_TS DEFAULT (SYSDATETIME()),
        DRY_RUN           BIT            NOT NULL,
        INV_LREF          BIGINT         NOT NULL,
        ABYS_AGREEMENT_ID BIGINT         NULL,
        ABYS_ACCOUNT_ID   BIGINT         NULL,
        INV_DATE          DATETIME       NULL,
        OLD_TLTOTAL       DECIMAL(18,2)  NULL,
        OLD_DV            DECIMAL(18,2)  NULL,
        OLD_TAX           DECIMAL(18,2)  NULL,
        OLD_GRANDTOTAL    DECIMAL(18,2)  NULL,
        WANT_DV           DECIMAL(18,2)  NOT NULL,
        WANT_TLTOTAL      DECIMAL(18,2)  NOT NULL,
        WANT_GRANDTOTAL   DECIMAL(18,2)  NOT NULL,
        PT_BORC_N         INT            NULL,
        PT_TAH_N          INT            NULL,
        IL_DV_N           INT            NULL,
        APPLIED           BIT            NOT NULL CONSTRAINT DF_MIG_INV_DV_INC_APP DEFAULT (0)
    );
    CREATE INDEX IX_MIG_INV_DV_INC_RUN ON dbo.MIG_INV_DV_FROM_INCOME_LOG (RUN_ID);
    CREATE INDEX IX_MIG_INV_DV_INC_INV ON dbo.MIG_INV_DV_FROM_INCOME_LOG (INV_LREF);
END;

IF OBJECT_ID('dbo.MIG_INV_DV_TAH_XREF_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_INV_DV_TAH_XREF_LOG
    (
        RUN_ID            BIGINT         NOT NULL,
        SNAPSHOT_TS       DATETIME2(3)   NOT NULL CONSTRAINT DF_MIG_INV_DV_TAH_TS DEFAULT (SYSDATETIME()),
        DRY_RUN           BIT            NOT NULL,
        BORC_LREF         BIGINT         NOT NULL,
        TAH_LREF          BIGINT         NOT NULL,
        INV_109_LREF      BIGINT         NULL,
        TAH_INV_LREF      BIGINT         NULL,
        ABYS_AGREEMENT_ID BIGINT         NULL,
        OLD_TAH_TL        DECIMAL(18,2)  NULL,
        OLD_TAH_DV        DECIMAL(18,2)  NULL,
        OLD_TAH_GT        DECIMAL(18,2)  NULL,
        WANT_DV           DECIMAL(18,2)  NOT NULL,
        WANT_TLTOTAL      DECIMAL(18,2)  NOT NULL,
        WANT_GRANDTOTAL   DECIMAL(18,2)  NOT NULL,
        APPLIED           BIT            NOT NULL CONSTRAINT DF_MIG_INV_DV_TAH_APP DEFAULT (0)
    );
    CREATE INDEX IX_MIG_INV_DV_TAH_RUN ON dbo.MIG_INV_DV_TAH_XREF_LOG (RUN_ID);
    CREATE INDEX IX_MIG_INV_DV_TAH_TAH ON dbo.MIG_INV_DV_TAH_XREF_LOG (TAH_LREF);
END;

/* ---------- Faz A seed: TYPE109 INV sapma ---------- */
IF OBJECT_ID('tempdb..#DV_SEED') IS NOT NULL DROP TABLE #DV_SEED;

;WITH dv_il AS (
    SELECT
        il.INVOICEREF,
        CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(il.GRANDTOTAL, 0)))) AS WANT_DV,
        COUNT(*) AS IL_DV_N
    FROM dbo.LS_005_01_INVLINES il WITH (NOLOCK)
    WHERE il.ABYS_INCOME_ID IN (23032, 938, 1863)
       OR il.TRANSTYPE IN (23032, 938, 1863)
    GROUP BY il.INVOICEREF
)
SELECT
    inv.LREF AS INV_LREF,
    CAST(inv.ABYS_AGREEMENT_ID AS BIGINT) AS ABYS_AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ABYS_ACCOUNT_ID,
    inv.DATE_ AS INV_DATE,
    CONVERT(DECIMAL(18,2), ISNULL(inv.TLTOTAL, 0)) AS OLD_TLTOTAL,
    CONVERT(DECIMAL(18,2), ISNULL(inv.DV, 0)) AS OLD_DV,
    CONVERT(DECIMAL(18,2), ISNULL(inv.TAX, 0)) AS OLD_TAX,
    CONVERT(DECIMAL(18,2), ISNULL(inv.GRANDTOTAL, 0)) AS OLD_GRANDTOTAL,
    d.WANT_DV,
    CONVERT(DECIMAL(18,2), ISNULL(inv.GRANDTOTAL, 0) - ISNULL(inv.TAX, 0) - d.WANT_DV) AS WANT_TLTOTAL,
    CONVERT(DECIMAL(18,2), ISNULL(inv.GRANDTOTAL, 0)) AS WANT_GRANDTOTAL,
    d.IL_DV_N
INTO #DV_SEED
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN dv_il d ON d.INVOICEREF = inv.LREF
WHERE inv.TYPE IN (109, 111)
  AND ISNULL(inv.CANCELED, 0) = 0
  AND d.WANT_DV > @Eps
  AND (
        @Agr IS NULL
     OR CAST(inv.ABYS_AGREEMENT_ID AS BIGINT) = @Agr
     OR CAST(inv.OWNERREF AS BIGINT) = @Agr
      )
  AND (
        ABS(CONVERT(DECIMAL(18,2), ISNULL(inv.DV, 0)) - d.WANT_DV) > @Eps
     OR ABS(
            CONVERT(DECIMAL(18,2), ISNULL(inv.TLTOTAL, 0))
          - (CONVERT(DECIMAL(18,2), ISNULL(inv.GRANDTOTAL, 0)) - CONVERT(DECIMAL(18,2), ISNULL(inv.TAX, 0)) - d.WANT_DV)
        ) > @Eps
      );

CREATE CLUSTERED INDEX IX_DV_SEED ON #DV_SEED (INV_LREF);

SELECT @N = COUNT(*) FROM #DV_SEED;
SET @Msg = N'92A seed INV n=' + CONVERT(VARCHAR(20), @N);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---------- Faz B seed: CROSSREF tahsilat (borc DV dolu, tah sapma) ---------- */
IF OBJECT_ID('tempdb..#TAH_SEED') IS NOT NULL DROP TABLE #TAH_SEED;

SELECT
    borc.LREF AS BORC_LREF,
    tah.LREF AS TAH_LREF,
    CAST(borc.INVOICEREF AS BIGINT) AS INV_109_LREF,
    CAST(tah.INVOICEREF AS BIGINT) AS TAH_INV_LREF,
    CAST(inv.ABYS_AGREEMENT_ID AS BIGINT) AS ABYS_AGREEMENT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(tah.TLTOTAL, 0)) AS OLD_TAH_TL,
    CONVERT(DECIMAL(18,2), ISNULL(tah.DV, 0)) AS OLD_TAH_DV,
    CONVERT(DECIMAL(18,2), ISNULL(tah.GRANDTOTAL, 0)) AS OLD_TAH_GT,
    CONVERT(DECIMAL(18,2), ISNULL(borc.DV, 0)) AS WANT_DV,
    CONVERT(DECIMAL(18,2), ISNULL(borc.TLTOTAL, 0)) AS WANT_TLTOTAL,
    CONVERT(DECIMAL(18,2), ISNULL(borc.GRANDTOTAL, 0)) AS WANT_GRANDTOTAL,
    CONVERT(DECIMAL(18,2), ISNULL(borc.TAX, 0)) AS WANT_TAX
INTO #TAH_SEED
FROM dbo.LS_005_01_PAYTRANS borc WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_PAYTRANS tah WITH (NOLOCK)
    ON tah.CROSSREF = borc.LREF
   AND ISNULL(tah.CANCELED, 0) = 0
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.LREF = borc.INVOICEREF
WHERE borc.TYPE IN (109, 110, 111)
  AND ISNULL(borc.IOCODE, 0) = 0
  AND ISNULL(borc.CANCELED, 0) = 0
  AND ISNULL(borc.DV, 0) > @Eps
  AND (@Agr IS NULL OR CAST(inv.ABYS_AGREEMENT_ID AS BIGINT) = @Agr
       OR CAST(inv.OWNERREF AS BIGINT) = @Agr)
  AND (
        ABS(CONVERT(DECIMAL(18,2), ISNULL(tah.DV, 0)) - CONVERT(DECIMAL(18,2), ISNULL(borc.DV, 0))) > @Eps
     OR ABS(CONVERT(DECIMAL(18,2), ISNULL(tah.TLTOTAL, 0)) - CONVERT(DECIMAL(18,2), ISNULL(borc.TLTOTAL, 0))) > @Eps
      );

CREATE CLUSTERED INDEX IX_TAH_SEED ON #TAH_SEED (TAH_LREF);

SELECT @NTah = COUNT(*) FROM #TAH_SEED;
SET @Msg = N'92B seed TAH xref n=' + CONVERT(VARCHAR(20), @NTah)
         + N' want_dv_sum=' + CONVERT(VARCHAR(30), (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(WANT_DV),0)) FROM #TAH_SEED));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0 AND @NTah = 0
BEGIN
    RAISERROR('92: aday yok (INV+TAH) — cikis', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @N > 0
    INSERT INTO dbo.MIG_INV_DV_FROM_INCOME_LOG
    (
        RUN_ID, DRY_RUN, INV_LREF, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, INV_DATE,
        OLD_TLTOTAL, OLD_DV, OLD_TAX, OLD_GRANDTOTAL,
        WANT_DV, WANT_TLTOTAL, WANT_GRANDTOTAL, IL_DV_N, APPLIED
    )
    SELECT
        @RunId, @DryRun, s.INV_LREF, s.ABYS_AGREEMENT_ID, s.ABYS_ACCOUNT_ID, s.INV_DATE,
        s.OLD_TLTOTAL, s.OLD_DV, s.OLD_TAX, s.OLD_GRANDTOTAL,
        s.WANT_DV, s.WANT_TLTOTAL, s.WANT_GRANDTOTAL, s.IL_DV_N, 0
    FROM #DV_SEED s;

IF @NTah > 0
    INSERT INTO dbo.MIG_INV_DV_TAH_XREF_LOG
    (
        RUN_ID, DRY_RUN, BORC_LREF, TAH_LREF, INV_109_LREF, TAH_INV_LREF, ABYS_AGREEMENT_ID,
        OLD_TAH_TL, OLD_TAH_DV, OLD_TAH_GT, WANT_DV, WANT_TLTOTAL, WANT_GRANDTOTAL, APPLIED
    )
    SELECT
        @RunId, @DryRun, t.BORC_LREF, t.TAH_LREF, t.INV_109_LREF, t.TAH_INV_LREF, t.ABYS_AGREEMENT_ID,
        t.OLD_TAH_TL, t.OLD_TAH_DV, t.OLD_TAH_GT, t.WANT_DV, t.WANT_TLTOTAL, t.WANT_GRANDTOTAL, 0
    FROM #TAH_SEED t;

IF @DryRun = 1
BEGIN
    IF @N > 0
        SELECT TOP 10 '92A_INV' K, INV_LREF, ABYS_AGREEMENT_ID, OLD_TLTOTAL, OLD_DV, OLD_GRANDTOTAL, WANT_TLTOTAL, WANT_DV
        FROM #DV_SEED ORDER BY INV_LREF DESC;

    IF @NTah > 0
        SELECT TOP 10 '92B_TAH' K, TAH_LREF, BORC_LREF, INV_109_LREF, ABYS_AGREEMENT_ID,
            OLD_TAH_TL, OLD_TAH_DV, OLD_TAH_GT, WANT_TLTOTAL, WANT_DV, WANT_GRANDTOTAL
        FROM #TAH_SEED ORDER BY TAH_LREF DESC;

    SET @Msg = N'92 DRY-RUN OK RunId=' + CONVERT(VARCHAR(20), @RunId)
             + N' INV=' + CONVERT(VARCHAR(20), @N)
             + N' TAH_XREF=' + CONVERT(VARCHAR(20), @NTah)
             + N' — APPLY: EXEC ... @DryRun=0';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
    RETURN;
END;

BEGIN TRAN;

IF @N > 0
BEGIN
    UPDATE il
    SET
        il.TLTOTAL  = 0,
        il.CURTOTAL = 0,
        il.DV       = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), ISNULL(il.GRANDTOTAL, 0))),
        il.TAX      = 0
    FROM dbo.LS_005_01_INVLINES il
    INNER JOIN #DV_SEED s ON s.INV_LREF = il.INVOICEREF
    WHERE il.ABYS_INCOME_ID IN (23032, 938, 1863)
       OR il.TRANSTYPE IN (23032, 938, 1863);

    SET @Msg = N'92A IL damga rows=' + CONVERT(VARCHAR(20), @@ROWCOUNT);
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    UPDATE inv
    SET
        inv.DV           = CONVERT(FLOAT, s.WANT_DV),
        inv.TLTOTAL      = CONVERT(FLOAT, s.WANT_TLTOTAL),
        inv.CURTOTAL     = CONVERT(FLOAT, s.WANT_TLTOTAL),
        inv.GRANDTOTAL   = CONVERT(FLOAT, s.WANT_GRANDTOTAL),
        inv.PAYABLETOTAL = CONVERT(FLOAT, s.WANT_GRANDTOTAL)
    FROM dbo.LS_005_01_INVOICE inv
    INNER JOIN #DV_SEED s ON s.INV_LREF = inv.LREF;

    SET @Msg = N'92A INV header rows=' + CONVERT(VARCHAR(20), @@ROWCOUNT);
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    UPDATE pt
    SET
        pt.DV           = CONVERT(FLOAT, s.WANT_DV),
        pt.TLTOTAL      = CONVERT(FLOAT, s.WANT_TLTOTAL),
        pt.CURTOTAL     = CONVERT(FLOAT, s.WANT_TLTOTAL),
        pt.TAX          = CONVERT(FLOAT, s.OLD_TAX),
        pt.GRANDTOTAL   = CONVERT(FLOAT, s.WANT_GRANDTOTAL),
        pt.PAYABLETOTAL = CONVERT(FLOAT, s.WANT_GRANDTOTAL)
    FROM dbo.LS_005_01_PAYTRANS pt
    INNER JOIN #DV_SEED s ON s.INV_LREF = pt.INVOICEREF
    WHERE ISNULL(pt.IOCODE, 0) = 0
      AND ISNULL(pt.CANCELED, 0) = 0
      AND ISNULL(pt.TYPE, 0) IN (109, 111);

    SET @Msg = N'92A PT borc rows=' + CONVERT(VARCHAR(20), @@ROWCOUNT);
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    UPDATE l SET l.APPLIED = 1
    FROM dbo.MIG_INV_DV_FROM_INCOME_LOG l
    WHERE l.RUN_ID = @RunId;
END;

IF @NTah > 0
BEGIN
    /* CROSSREF tahsilat PT — LS_001 TOTAL = GT - DV */
    UPDATE tah
    SET
        tah.DV           = CONVERT(FLOAT, t.WANT_DV),
        tah.TLTOTAL      = CONVERT(FLOAT, t.WANT_TLTOTAL),
        tah.CURTOTAL     = CONVERT(FLOAT, t.WANT_TLTOTAL),
        tah.TAX          = CONVERT(FLOAT, t.WANT_TAX),
        tah.GRANDTOTAL   = CONVERT(FLOAT, t.WANT_GRANDTOTAL)
        /* PAYABLETOTAL dokunma — tahsil edilen tutar */
    FROM dbo.LS_005_01_PAYTRANS tah
    INNER JOIN #TAH_SEED t ON t.TAH_LREF = tah.LREF;

    SET @Msg = N'92B PT tah xref rows=' + CONVERT(VARCHAR(20), @@ROWCOUNT);
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    /* TYPE101 tahsilat faturasi header (varsa) */
    UPDATE inv
    SET
        inv.DV           = CONVERT(FLOAT, x.WANT_DV),
        inv.TLTOTAL      = CONVERT(FLOAT, x.WANT_TLTOTAL),
        inv.CURTOTAL     = CONVERT(FLOAT, x.WANT_TLTOTAL),
        inv.GRANDTOTAL   = CONVERT(FLOAT, x.WANT_GRANDTOTAL),
        inv.PAYABLETOTAL = CONVERT(FLOAT, x.WANT_GRANDTOTAL)
    FROM dbo.LS_005_01_INVOICE inv
    INNER JOIN (
        SELECT TAH_INV_LREF, MAX(WANT_DV) WANT_DV, MAX(WANT_TLTOTAL) WANT_TLTOTAL, MAX(WANT_GRANDTOTAL) WANT_GRANDTOTAL
        FROM #TAH_SEED
        WHERE TAH_INV_LREF IS NOT NULL
        GROUP BY TAH_INV_LREF
    ) x ON x.TAH_INV_LREF = inv.LREF
    WHERE ISNULL(inv.TYPE, 0) = 101
      AND (
            ABS(CONVERT(DECIMAL(18,2), ISNULL(inv.DV, 0)) - x.WANT_DV) > @Eps
         OR ABS(CONVERT(DECIMAL(18,2), ISNULL(inv.TLTOTAL, 0)) - x.WANT_TLTOTAL) > @Eps
          );

    SET @Msg = N'92B INV101 header rows=' + CONVERT(VARCHAR(20), @@ROWCOUNT);
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    UPDATE l SET l.APPLIED = 1
    FROM dbo.MIG_INV_DV_TAH_XREF_LOG l
    WHERE l.RUN_ID = @RunId;
END;

COMMIT TRAN;

/* assert: kullanici sorgusu AGR ornek */
IF @Agr IS NOT NULL
BEGIN
    SELECT
        ISNULL((ISNULL(PAY_TAHSILAT.GRANDTOTAL, 0) - ISNULL(PAY_TAHSILAT.DV, 0)), 0) AS TOTAL,
        PAY_TAHSILAT.DATE_ AS SDATE,
        PAY_BORC.TYPE AS TYPE,
        CONVERT(DECIMAL(18,2), PAY_TAHSILAT.GRANDTOTAL) AS TAH_GT,
        CONVERT(DECIMAL(18,2), ISNULL(PAY_TAHSILAT.DV, 0)) AS TAH_DV,
        CONVERT(DECIMAL(18,2), ISNULL(PAY_BORC.DV, 0)) AS BORC_DV
    FROM dbo.LS_005_01_INVOICE INV WITH (NOLOCK)
    INNER JOIN dbo.LS_005_01_PAYTRANS PAY_BORC WITH (NOLOCK) ON PAY_BORC.INVOICEREF = INV.LREF
    INNER JOIN dbo.LS_005_01_PAYTRANS PAY_TAHSILAT WITH (NOLOCK) ON PAY_TAHSILAT.CROSSREF = PAY_BORC.LREF
    WHERE PAY_BORC.TYPE IN (111, 109, 110)
      AND INV.CLIENTREF = PAY_BORC.CLIENTREF
      AND INV.CLIENTREF = PAY_TAHSILAT.CLIENTREF
      AND PAY_TAHSILAT.CANCELED = 0
      AND INV.OWNERREF = @Agr
      AND INV.RETURN_TARGET_INVREF IS NULL
    ORDER BY PAY_TAHSILAT.DATE_;
END;

SET @Msg = N'========== 92 APPLY OK RunId=' + CONVERT(VARCHAR(20), @RunId)
         + N' INV=' + CONVERT(VARCHAR(20), @N)
         + N' TAH_XREF=' + CONVERT(VARCHAR(20), @NTah)
         + N' elapsed_ms=' + CONVERT(VARCHAR(20), DATEDIFF(MILLISECOND, @t0, SYSDATETIME()))
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

END
GO
/* EXEC dbo.SP_MIG_INV_DV_FROM_INCOME @DryRun = 1; */
