/* =============================================================================
   prodREADY_ENERGY / 93_AGR_FEE_COLLECTED_HEAL.sql
   CREATE OR ALTER PROCEDURE dbo.SP_MIG_93_AGR_FEE_COLLECTED  (R23 2026-08-11)
   TYPE109 + TYPE86 tahsil → AGR.FEE_COLLECTED.
   EXEC:
     EXEC dbo.SP_MIG_93_AGR_FEE_COLLECTED @DryRun = 1, @Agr = NULL;
     EXEC dbo.SP_MIG_93_AGR_FEE_COLLECTED @DryRun = 0, @Agr = NULL;
   ============================================================================= */
USE energy;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
CREATE OR ALTER PROCEDURE dbo.SP_MIG_93_AGR_FEE_COLLECTED
    @DryRun        BIT        = 1,
    @Agr           BIGINT     = NULL,
    @Tp2           VARCHAR(3) = 'KUL',
    @RequireBag   BIT        = 1,
    @ClearNonMatch BIT        = 0
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET IMPLICIT_TRANSACTIONS OFF;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
    DECLARE @ReqBothInt INT = CAST(@RequireBoth AS INT);
    DECLARE @ClearInt  INT = CAST(@ClearNonMatch AS INT);
    DECLARE @t0 DATETIME2(3) = SYSDATETIME();
    DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
    DECLARE @Msg NVARCHAR(400);
    DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'SEED' ELSE CONVERT(VARCHAR(30), @Agr) END;
    DECLARE @N INT;
    DECLARE @NSet1 INT;
    DECLARE @NSet0 INT;

SET @Msg = N'========== 93 AGR FEE_COLLECTED DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' Tp2=' + ISNULL(@Tp2, N'*')
         + N' RequireBag=' + CAST(@ReqBagInt AS VARCHAR(1))
         + N' ClearNonMatch=' + CAST(@ClearInt AS VARCHAR(1))
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_AGR_FEE_COLLECTED_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_AGR_FEE_COLLECTED_LOG
    (
        LOG_ID         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID         BIGINT         NOT NULL,
        SNAPSHOT_TS    DATETIME2(3)   NOT NULL CONSTRAINT DF_MIG_AGR_FEE_TS DEFAULT (SYSDATETIME()),
        DRY_RUN        BIT            NOT NULL,
        AGR_LREF       INT            NOT NULL,
        ABYS_ID        BIGINT         NULL,
        TP2            VARCHAR(3)     NULL,
        OLD_FC         BIT            NULL,
        WANT_FC        BIT            NOT NULL,
        HAS_GUV        BIT            NOT NULL,
        HAS_BAG        BIT            NOT NULL,
        GUV_OPEN       BIT            NOT NULL,
        BAG_OPEN       BIT            NOT NULL,
        GUV_CNT        INT            NULL,
        BAG_CNT        INT            NULL,
        ACTION_CODE    VARCHAR(10)    NOT NULL, /* SET_1 | SET_0 | KEEP */
        APPLIED        BIT            NOT NULL CONSTRAINT DF_MIG_AGR_FEE_APP DEFAULT (0)
    );
    CREATE INDEX IX_MIG_AGR_FEE_RUN ON dbo.MIG_AGR_FEE_COLLECTED_LOG (RUN_ID, DRY_RUN);
    CREATE INDEX IX_MIG_AGR_FEE_AGR ON dbo.MIG_AGR_FEE_COLLECTED_LOG (ABYS_ID);
END;

/* ---------- 109 Güvence ---------- */
IF OBJECT_ID('tempdb..#GUV') IS NOT NULL DROP TABLE #GUV;
SELECT
    COALESCE(inv.ABYS_AGREEMENT_ID, CAST(inv.OWNERREF AS BIGINT)) AS AGR_ID,
    MAX(CASE WHEN ISNULL(inv.CLOSED, 0) = 0 THEN 1 ELSE 0 END) AS GUV_OPEN,
    MAX(CASE WHEN ISNULL(inv.CLOSED, 0) = 1 THEN 1 ELSE 0 END) AS GUV_CLOSED,
    COUNT(*) AS GUV_CNT
INTO #GUV
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.TYPE = 109
  AND ISNULL(inv.CANCELED, 0) = 0
  AND (@Agr IS NULL
       OR COALESCE(inv.ABYS_AGREEMENT_ID, CAST(inv.OWNERREF AS BIGINT)) = @Agr)
GROUP BY COALESCE(inv.ABYS_AGREEMENT_ID, CAST(inv.OWNERREF AS BIGINT))
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #GUV WHERE AGR_ID IS NULL;
CREATE CLUSTERED INDEX CX_GUV ON #GUV (AGR_ID);

SET @N = (SELECT COUNT(*) FROM #GUV);
SET @Msg = N'GUV AGR n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---------- 86 Bağlantı seed + EXPLAIN parse ---------- */
IF OBJECT_ID('tempdb..#BAG_INV') IS NOT NULL DROP TABLE #BAG_INV;
SELECT
    inv.LREF,
    CAST(ISNULL(inv.CLOSED, 0) AS BIT) AS CLOSED,
    COALESCE(inv.ABYS_AGREEMENT_ID, CAST(inv.OWNERREF AS BIGINT)) AS AGR_KEY,
    TRY_CAST(
        NULLIF(LTRIM(RTRIM(
            CASE
                WHEN CHARINDEX('Abn No:', inv.EXPLAIN) > 0 THEN
                    LEFT(
                        SUBSTRING(inv.EXPLAIN, CHARINDEX('Abn No:', inv.EXPLAIN) + 7, 30),
                        PATINDEX('%[^0-9]%', SUBSTRING(inv.EXPLAIN, CHARINDEX('Abn No:', inv.EXPLAIN) + 7, 30) + 'X') - 1
                    )
            END
        )), '')
    AS BIGINT) AS ABN_NO,
    TRY_CAST(
        NULLIF(LTRIM(RTRIM(
            CASE
                WHEN CHARINDEX('Tes.No:', inv.EXPLAIN) > 0 THEN
                    LEFT(
                        SUBSTRING(inv.EXPLAIN, CHARINDEX('Tes.No:', inv.EXPLAIN) + 7, 30),
                        PATINDEX('%[^0-9]%', SUBSTRING(inv.EXPLAIN, CHARINDEX('Tes.No:', inv.EXPLAIN) + 7, 30) + 'X') - 1
                    )
            END
        )), '')
    AS BIGINT) AS TES_NO
INTO #BAG_INV
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.TYPE = 86
  AND inv.ABYS_ACCRUE_TYPE_ID IN (4, 27, 28, 544)
  AND ISNULL(inv.CANCELED, 0) = 0
OPTION (MAXDOP 8);

CREATE CLUSTERED INDEX CX_BAG_INV ON #BAG_INV (LREF);

SET @N = (SELECT COUNT(*) FROM #BAG_INV);
SET @Msg = N'BAG INV n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('tempdb..#BAG_AGR') IS NOT NULL DROP TABLE #BAG_AGR;
SELECT
    b.LREF,
    b.CLOSED,
    COALESCE(
        CASE WHEN b.AGR_KEY IS NOT NULL AND a0.ABYS_ID IS NOT NULL THEN b.AGR_KEY END,
        CASE WHEN a1.ABYS_ID IS NOT NULL THEN b.ABN_NO END,
        a2.ABYS_ID
    ) AS AGR_ID
INTO #BAG_AGR
FROM #BAG_INV b
LEFT JOIN dbo.LS_005_01_AGR a0 WITH (NOLOCK)
       ON a0.ABYS_ID = b.AGR_KEY
      AND a0.TP2 = @Tp2
OUTER APPLY (
    SELECT TOP 1 a.ABYS_ID
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE b.AGR_KEY IS NULL
      AND b.ABN_NO IS NOT NULL
      AND a.ABYS_ID = b.ABN_NO
      AND a.TP2 = @Tp2
) a1
OUTER APPLY (
    SELECT TOP 1 a.ABYS_ID
    FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
    WHERE b.AGR_KEY IS NULL
      AND a1.ABYS_ID IS NULL
      AND b.TES_NO IS NOT NULL
      AND a.FITNO = CAST(b.TES_NO AS VARCHAR(30))
      AND a.TP2 = @Tp2
) a2
WHERE (@Agr IS NULL
       OR b.AGR_KEY = @Agr
       OR b.ABN_NO = @Agr
       OR a2.ABYS_ID = @Agr)
OPTION (RECOMPILE, MAXDOP 8);

IF OBJECT_ID('tempdb..#BAG') IS NOT NULL DROP TABLE #BAG;
SELECT
    AGR_ID,
    MAX(CASE WHEN CLOSED = 0 THEN 1 ELSE 0 END) AS BAG_OPEN,
    MAX(CASE WHEN CLOSED = 1 THEN 1 ELSE 0 END) AS BAG_CLOSED,
    COUNT(*) AS BAG_CNT
INTO #BAG
FROM #BAG_AGR
WHERE AGR_ID IS NOT NULL
GROUP BY AGR_ID
OPTION (MAXDOP 8);

CREATE CLUSTERED INDEX CX_BAG ON #BAG (AGR_ID);

SET @N = (SELECT COUNT(*) FROM #BAG);
SET @Msg = N'BAG AGR resolved n=' + CAST(@N AS VARCHAR(20))
         + N' unresolved_inv=' + CAST((SELECT COUNT(*) FROM #BAG_AGR WHERE AGR_ID IS NULL) AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---------- AGR fee status + WANT ---------- */
IF OBJECT_ID('tempdb..#FEE') IS NOT NULL DROP TABLE #FEE;
SELECT
    a.LREF AS AGR_LREF,
    a.ABYS_ID,
    a.TP2,
    CAST(ISNULL(a.FEE_COLLECTED, 0) AS BIT) AS OLD_FC,
    CAST(CASE WHEN g.AGR_ID IS NOT NULL THEN 1 ELSE 0 END AS BIT) AS HAS_GUV,
    CAST(CASE WHEN b.AGR_ID IS NOT NULL THEN 1 ELSE 0 END AS BIT) AS HAS_BAG,
    CAST(ISNULL(g.GUV_OPEN, 0) AS BIT) AS GUV_OPEN,
    CAST(ISNULL(b.BAG_OPEN, 0) AS BIT) AS BAG_OPEN,
    ISNULL(g.GUV_CNT, 0) AS GUV_CNT,
    ISNULL(b.BAG_CNT, 0) AS BAG_CNT,
    CAST(
        CASE
            WHEN @RequireBag = 1 THEN
                CASE WHEN g.AGR_ID IS NOT NULL AND b.AGR_ID IS NOT NULL
                      AND ISNULL(g.GUV_OPEN, 1) = 0
                      AND ISNULL(b.BAG_OPEN, 1) = 0
                     THEN 1 ELSE 0 END
            ELSE
                CASE WHEN g.AGR_ID IS NOT NULL
                      AND ISNULL(g.GUV_OPEN, 1) = 0
                      AND (b.AGR_ID IS NULL OR ISNULL(b.BAG_OPEN, 1) = 0)
                     THEN 1 ELSE 0 END
        END
    AS BIT) AS WANT_FC
INTO #FEE
FROM dbo.LS_005_01_AGR a WITH (NOLOCK)
LEFT JOIN #GUV g ON g.AGR_ID = a.ABYS_ID
LEFT JOIN #BAG b ON b.AGR_ID = a.ABYS_ID
WHERE (@Tp2 IS NULL OR a.TP2 = @Tp2)
  AND (@Agr IS NULL OR a.ABYS_ID = @Agr)
  AND (g.AGR_ID IS NOT NULL OR b.AGR_ID IS NOT NULL)
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_FEE ON #FEE (AGR_LREF);

/* ---------- Rapor ---------- */
SELECT
    CASE
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 0 AND BAG_OPEN = 0 THEN 'BOTH_COLLECTED'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 0 AND BAG_OPEN = 1 THEN 'GUV_OK_BAG_OPEN'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 1 AND BAG_OPEN = 0 THEN 'GUV_OPEN_BAG_OK'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 THEN 'BOTH_OPEN'
        WHEN HAS_GUV = 1 AND GUV_OPEN = 0 THEN 'ONLY_GUV_COLLECTED'
        WHEN HAS_GUV = 1 THEN 'ONLY_GUV_OPEN'
        WHEN HAS_BAG = 1 AND BAG_OPEN = 0 THEN 'ONLY_BAG_COLLECTED'
        WHEN HAS_BAG = 1 THEN 'ONLY_BAG_OPEN'
        ELSE 'OTHER'
    END AS BUCKET,
    COUNT(*) AS N,
    SUM(CASE WHEN OLD_FC = 1 THEN 1 ELSE 0 END) AS CUR_FC1,
    SUM(CASE WHEN WANT_FC = 1 THEN 1 ELSE 0 END) AS WANT_FC1
FROM #FEE
GROUP BY
    CASE
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 0 AND BAG_OPEN = 0 THEN 'BOTH_COLLECTED'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 0 AND BAG_OPEN = 1 THEN 'GUV_OK_BAG_OPEN'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 AND GUV_OPEN = 1 AND BAG_OPEN = 0 THEN 'GUV_OPEN_BAG_OK'
        WHEN HAS_GUV = 1 AND HAS_BAG = 1 THEN 'BOTH_OPEN'
        WHEN HAS_GUV = 1 AND GUV_OPEN = 0 THEN 'ONLY_GUV_COLLECTED'
        WHEN HAS_GUV = 1 THEN 'ONLY_GUV_OPEN'
        WHEN HAS_BAG = 1 AND BAG_OPEN = 0 THEN 'ONLY_BAG_COLLECTED'
        WHEN HAS_BAG = 1 THEN 'ONLY_BAG_OPEN'
        ELSE 'OTHER'
    END
ORDER BY N DESC;

IF OBJECT_ID('tempdb..#APPLY') IS NOT NULL DROP TABLE #APPLY;
SELECT
    f.*,
    CASE
        WHEN f.OLD_FC = 0 AND f.WANT_FC = 1 THEN 'SET_1'
        WHEN f.OLD_FC = 1 AND f.WANT_FC = 0 AND @ClearNonMatch = 1 THEN 'SET_0'
        ELSE 'KEEP'
    END AS ACTION_CODE
INTO #APPLY
FROM #FEE f
WHERE (f.OLD_FC = 0 AND f.WANT_FC = 1)
   OR (f.OLD_FC = 1 AND f.WANT_FC = 0 AND @ClearNonMatch = 1);

CREATE CLUSTERED INDEX CX_APPLY ON #APPLY (AGR_LREF);

SELECT
    ACTION_CODE,
    COUNT(*) AS N
FROM #APPLY
GROUP BY ACTION_CODE
ORDER BY 1;

SELECT TOP 20
    'SAMPLE' AS K,
    AGR_LREF, ABYS_ID, TP2, OLD_FC, WANT_FC,
    HAS_GUV, HAS_BAG, GUV_OPEN, BAG_OPEN, GUV_CNT, BAG_CNT, ACTION_CODE
FROM #APPLY
ORDER BY ACTION_CODE, AGR_LREF;

SET @NSet1 = (SELECT COUNT(*) FROM #APPLY WHERE ACTION_CODE = 'SET_1');
SET @NSet0 = (SELECT COUNT(*) FROM #APPLY WHERE ACTION_CODE = 'SET_0');
SET @Msg = N'Apply aday SET_1=' + CAST(@NSet1 AS VARCHAR(20))
         + N' SET_0=' + CAST(@NSet0 AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

INSERT INTO dbo.MIG_AGR_FEE_COLLECTED_LOG
(
    RUN_ID, DRY_RUN, AGR_LREF, ABYS_ID, TP2,
    OLD_FC, WANT_FC, HAS_GUV, HAS_BAG, GUV_OPEN, BAG_OPEN,
    GUV_CNT, BAG_CNT, ACTION_CODE, APPLIED
)
SELECT
    @RunId, @DryRun, AGR_LREF, ABYS_ID, TP2,
    OLD_FC, WANT_FC, HAS_GUV, HAS_BAG, GUV_OPEN, BAG_OPEN,
    GUV_CNT, BAG_CNT, ACTION_CODE, 0
FROM #APPLY
OPTION (MAXDOP 8);

IF @DryRun = 1
BEGIN
    SET @Msg = N'DRY_RUN — FEE_COLLECTED UPDATE yok. APPLY: EXEC ... @DryRun=0';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
    RETURN;
END;

IF NOT EXISTS (SELECT 1 FROM #APPLY)
BEGIN
    RAISERROR('Apply bos — cikis.', 0, 1) WITH NOWAIT;
    RETURN;
END;

UPDATE a
SET a.FEE_COLLECTED = x.WANT_FC
FROM dbo.LS_005_01_AGR a
INNER JOIN #APPLY x ON x.AGR_LREF = a.LREF
OPTION (MAXDOP 8);

SET @N = @@ROWCOUNT;

UPDATE lg
SET lg.APPLIED = 1
FROM dbo.MIG_AGR_FEE_COLLECTED_LOG lg
WHERE lg.RUN_ID = @RunId
  AND lg.DRY_RUN = 0;

SET @Msg = N'APPLIED FEE_COLLECTED rowcount=' + CAST(@N AS VARCHAR(20))
         + N' elapsed_ms=' + CAST(DATEDIFF(MILLISECOND, @t0, SYSDATETIME()) AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

END
GO
/* EXEC dbo.SP_MIG_93_AGR_FEE_COLLECTED @DryRun = 1; */
