/* =============================================================================
   FILE : prodEnergy/90_afl_frk/91f_en_gt_afl_kalan_heal.sql
   PATCH (cutover EXEC zincirine KOYMA) — residual EN_GT_AFL kalan heal

   Cutover AFL master (O50 AS_OF) vs Energy:
     DELTA_KALAN_NET = EN_KALAN - AFL  (eksilten/IADE hesaplari HARIC, SP_AGR_FRK_ALL)

   Bu heal YALNIZ:
     EN > AFL  (@Eps)  VE  hesap bazinda AFL≈0 (BALANCE<=@Eps / AFL yok)
     → acik borc PT PAID=PAYABLE + INV CLOSED=1

   YAPMAZ:
     AFL > EN (Energy zaten kapali) — reopen yok
     AFL acik (BALANCE>@Eps) kismi hizalama — 91g_en_gt_afl_partial_heal.sql
     CANCEL_REV / CP=1 / IOCODE<>0
     O51/92 STG

   Onkosul: energy.dbo.MIG_AGR_FRK_ALL guncel (SP_AGR_FRK_ALL)
            energy.dbo.LS_AFL_OPEN_DEBT (cutover O50)

   Kullanim:
     @DryRun=1  — sayim + aday
     @DryRun=0  — APPLY
     @Agr       — tek sozlesme | NULL=seed’deki tum EN_GT_AFL AGR

   Sonra: EXEC dbo.SP_AGR_FRK_ALL @Agr=..., @ReturnResult=1;
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun BIT           = 1;      /* APPLY: 0 */
DECLARE @Agr    BIGINT        = NULL;   /* NULL = MIG seed EN_GT_AFL | tek AGR */
DECLARE @Eps    DECIMAL(18,2) = 0.02;
-- SET @DryRun = 0;
-- SET @Agr = 197168;

DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
DECLARE @Msg NVARCHAR(400);
DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'SEED' ELSE CONVERT(VARCHAR(30), @Agr) END;
DECLARE @N INT;

SET @Msg = N'========== 91f EN_GT_AFL KALAN HEAL DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_AGR_FRK_ALL', 'U') IS NULL
BEGIN
    RAISERROR('MIG_AGR_FRK_ALL yok — once EXEC SP_AGR_FRK_ALL', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_AFL_OPEN_DEBT yok — O50 cutover AFL gerekli', 16, 1);
    RETURN;
END;

/* Log */
IF OBJECT_ID('dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG (
        LOG_ID         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID         BIGINT         NOT NULL,
        SNAPSHOT_TS    DATETIME2(3)   NOT NULL,
        DRY_RUN        BIT            NOT NULL,
        AGREEMENT_ID   BIGINT         NULL,
        ACCOUNT_ID     BIGINT         NULL,
        MAIN_LREF      INT            NOT NULL,
        PT_LREF        INT            NOT NULL,
        PT_PAID_OLD    DECIMAL(18,2)  NULL,
        PT_PAYABLE     DECIMAL(18,2)  NULL,
        PT_KALAN       DECIMAL(18,2)  NULL,
        AFL_BALANCE    DECIMAL(18,2)  NULL,
        AGR_DELTA_NET  DECIMAL(18,2)  NULL,
        NOTE           NVARCHAR(80)   NULL
    );
    CREATE INDEX IX_EN_GT_AFL_HEAL_RUN ON dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG (RUN_ID, DRY_RUN);
END;

/* ---- Seed: AGR with EN_GT_AFL on NET band ---- */
IF OBJECT_ID('tempdb..#AGR') IS NOT NULL DROP TABLE #AGR;
SELECT
    f.AGREEMENT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(f.EN_KALAN, 0)) AS EN_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(f.AFL_KALAN, 0)) AS AFL_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(f.DELTA_KALAN_NET, 0)) AS DELTA_KALAN_NET,
    f.KIND_FRK
INTO #AGR
FROM dbo.MIG_AGR_FRK_ALL f WITH (NOLOCK)
WHERE ISNULL(f.DELTA_KALAN_NET, 0) > @Eps
  AND (@Agr IS NULL OR f.AGREEMENT_ID = @Agr)
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_AGR ON #AGR (AGREEMENT_ID);

SET @N = (SELECT COUNT(*) FROM #AGR);
SET @Msg = N'Seed EN_GT_AFL AGR n=' + CAST(@N AS VARCHAR(20))
         + N' sum_delta_net=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(DELTA_KALAN_NET), 0)) FROM #AGR));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('Seed bos — cikis (DELTA_KALAN_NET>Eps EN_GT yok).', 0, 1) WITH NOWAIT;
    RETURN;
END;

/* AFL open map (account) */
IF OBJECT_ID('tempdb..#AFL') IS NOT NULL DROP TABLE #AFL;
SELECT
    CAST(a.FATURAID AS BIGINT) AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) AS BALANCE
INTO #AFL
FROM dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
WHERE a.FATURAID IS NOT NULL
OPTION (RECOMPILE, MAXDOP 8);
CREATE CLUSTERED INDEX CX_AFL ON #AFL (ACCOUNT_ID);

/* ---- Candidates: open debt PT on AFL~0 accounts under seed AGR ---- */
IF OBJECT_ID('tempdb..#CAND') IS NOT NULL DROP TABLE #CAND;

SELECT
    CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT) AS AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    inv.LREF AS MAIN_LREF,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) AS AFL_BALANCE,
    g.DELTA_KALAN_NET AS AGR_DELTA_NET
INTO #CAND
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #AGR g
    ON g.AGREEMENT_ID = CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
LEFT JOIN #AFL a
    ON a.ACCOUNT_ID = CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
  /* AFL master kapali / yok → Energy acik kalani kapat */
  AND CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) <= @Eps
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_CAND ON #CAND (PT_LREF);

SET @N = (SELECT COUNT(*) FROM #CAND);
SET @Msg = N'Aday PT=' + CAST(@N AS VARCHAR(20))
         + N' ACC=' + CAST((SELECT COUNT(DISTINCT ACCOUNT_ID) FROM #CAND) AS VARCHAR(20))
         + N' AGR=' + CAST((SELECT COUNT(DISTINCT AGREEMENT_ID) FROM #CAND) AS VARCHAR(20))
         + N' sum_pt_kalan=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(PT_KALAN), 0)) FROM #CAND));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* Seed AGR with EN_GT but no AFL~0 open PT (likely AFL still open / partial) */
SELECT
    COUNT(*) AS AGR_EN_GT_NO_CAND
FROM #AGR g
WHERE NOT EXISTS (SELECT 1 FROM #CAND c WHERE c.AGREEMENT_ID = g.AGREEMENT_ID);

PRINT '========== TESPIT OZET ==========';
SELECT
    COUNT(*) AS PT_OPEN_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN)) AS SUM_PT_KALAN
FROM #CAND;

PRINT '========== TOP 30 ADAY ==========';
SELECT TOP 30
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAYABLE, PT_PAID_OLD, PT_KALAN, AFL_BALANCE, AGR_DELTA_NET
FROM #CAND
ORDER BY PT_KALAN DESC, AGREEMENT_ID, ACCOUNT_ID, PT_LREF;

INSERT INTO dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAYABLE, PT_KALAN,
    AFL_BALANCE, AGR_DELTA_NET, NOTE
)
SELECT
    @RunId, @t0, @DryRun, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAYABLE, PT_KALAN,
    AFL_BALANCE, AGR_DELTA_NET,
    CASE WHEN @DryRun = 1 THEN N'DRY_RUN' ELSE N'APPLY_91f' END
FROM #CAND;

IF @N = 0
BEGIN
    RAISERROR('Aday yok — AFL~0 acik PT yok (EN_GT buyuk kisim AFL acik kalabilir).', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @DryRun = 1
BEGIN
    RAISERROR('DRY_RUN=1 — UPDATE yok. APPLY: SET @DryRun=0', 0, 1) WITH NOWAIT;
    RAISERROR('Sonra: EXEC dbo.SP_AGR_FRK_ALL @Agr=<id> veya @OnlyDiff=1', 0, 1) WITH NOWAIT;
    RETURN;
END;

/* ---------- APPLY ---------- */
RAISERROR('========== APPLY ==========', 0, 1) WITH NOWAIT;
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, c.PT_PAYABLE)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #CAND c ON c.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'PT PAID=PAYABLE n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #CAND) c ON c.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'INV CLOSED=1 n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

COMMIT TRAN;

PRINT '========== POST CHECK ==========';
SELECT
    c.AGREEMENT_ID, c.ACCOUNT_ID, c.MAIN_LREF, c.PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_NOW,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED_NOW
FROM #CAND c
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = c.PT_LREF
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = c.MAIN_LREF
ORDER BY c.AGREEMENT_ID, c.ACCOUNT_ID, c.PT_LREF;

SET @Msg = CONVERT(VARCHAR(30), SYSDATETIME(), 121)
         + N' | 91f DONE apply RunId=' + CONVERT(VARCHAR(30), @RunId);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
