/* =============================================================================
   FILE : prodEnergy/90_afl_frk/91h_afl_gt_en_reopen_heal.sql
   PATCH (cutover EXEC zincirine KOYMA) — AFL>EN reopen (PAID geri al)

   Cutover AFL taban: hesapta AFL.BALANCE > eps iken EN_KALAN >= AFL.
   EN << AFL (over-close) → PAID azalt; INV CLOSED=0.

   Seed : MIG_AGR_FRK_ALL.DELTA_KALAN_NET < -@Eps
   Grain: ABYS_ACCOUNT_ID = FATURAID
   SHORTFALL = AFL_BALANCE - SUM(PT_KALAN)
   FIFO ters (PT.LREF DESC): PAID basindan geri al
     APPLY = min(PAID, kalan shortfall)
     PAID_NEW = PAID_OLD - APPLY
   INV: reopen sonrasi PT kalan > eps → CLOSED=0

   YAPMAZ:
     EN>AFL close → 91f / 91g
     CP=1 / CANCELED / IOCODE<>0
     PAID < 0

   Onkosul: MIG_AGR_FRK_ALL guncel + LS_AFL_OPEN_DEBT
   Default @DryRun=1 — once spot @Agr sonra SEED
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun BIT           = 1;      /* APPLY: 0 */
DECLARE @Agr    BIGINT        = NULL;   /* NULL = seed AFL_GT_EN | tek AGR */
DECLARE @Eps    DECIMAL(18,2) = 0.02;
-- SET @DryRun = 0;
-- SET @Agr = 1028596;

DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
DECLARE @Msg NVARCHAR(400);
DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'SEED' ELSE CONVERT(VARCHAR(30), @Agr) END;
DECLARE @N INT;

SET @Msg = N'========== 91h AFL_GT_EN REOPEN HEAL DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_AGR_FRK_ALL', 'U') IS NULL
BEGIN
    RAISERROR('MIG_AGR_FRK_ALL yok — once EXEC SP_AGR_FRK_ALL', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_AFL_OPEN_DEBT yok', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.MIG_AFL_GT_EN_REOPEN_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_AFL_GT_EN_REOPEN_LOG (
        LOG_ID          BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID          BIGINT         NOT NULL,
        SNAPSHOT_TS     DATETIME2(3)   NOT NULL,
        DRY_RUN         BIT            NOT NULL,
        AGREEMENT_ID    BIGINT         NULL,
        ACCOUNT_ID      BIGINT         NULL,
        MAIN_LREF       INT            NOT NULL,
        PT_LREF         INT            NOT NULL,
        PT_PAID_OLD     DECIMAL(18,2)  NULL,
        PT_PAID_NEW     DECIMAL(18,2)  NULL,
        APPLY_AMT       DECIMAL(18,2)  NULL,
        PT_KALAN_OLD    DECIMAL(18,2)  NULL,
        PT_PAYABLE      DECIMAL(18,2)  NULL,
        AFL_BALANCE     DECIMAL(18,2)  NULL,
        ACC_EN_KALAN    DECIMAL(18,2)  NULL,
        SHORTFALL       DECIMAL(18,2)  NULL,
        AGR_DELTA_NET   DECIMAL(18,2)  NULL,
        NOTE            NVARCHAR(80)   NULL
    );
    CREATE INDEX IX_AFL_GT_EN_REOPEN_RUN
        ON dbo.MIG_AFL_GT_EN_REOPEN_LOG (RUN_ID, DRY_RUN);
END;

/* Seed: AFL > EN on NET */
IF OBJECT_ID('tempdb..#AGR') IS NOT NULL DROP TABLE #AGR;
SELECT
    f.AGREEMENT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(f.DELTA_KALAN_NET, 0)) AS DELTA_KALAN_NET
INTO #AGR
FROM dbo.MIG_AGR_FRK_ALL f WITH (NOLOCK)
WHERE ISNULL(f.DELTA_KALAN_NET, 0) < -@Eps
  AND (@Agr IS NULL OR f.AGREEMENT_ID = @Agr)
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_AGR ON #AGR (AGREEMENT_ID);

SET @N = (SELECT COUNT(*) FROM #AGR);
SET @Msg = N'Seed AFL_GT_EN AGR n=' + CAST(@N AS VARCHAR(20))
         + N' sum_delta_net=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(DELTA_KALAN_NET), 0)) FROM #AGR));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('Seed bos — cikis.', 0, 1) WITH NOWAIT;
    RETURN;
END;

/* Tum borc PT (kalan 0 dahil — PAID geri almak icin) + AFL>eps */
IF OBJECT_ID('tempdb..#PT0') IS NOT NULL DROP TABLE #PT0;
SELECT
    CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT) AS AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    inv.LREF AS MAIN_LREF,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) AS AFL_BALANCE,
    g.DELTA_KALAN_NET AS AGR_DELTA_NET
INTO #PT0
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #AGR g
    ON g.AGREEMENT_ID = CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
INNER JOIN dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    ON CAST(a.FATURAID AS BIGINT) = CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) > @Eps
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) > @Eps
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_PT0 ON #PT0 (ACCOUNT_ID, PT_LREF);

/* Hesap shortfall */
IF OBJECT_ID('tempdb..#ACC') IS NOT NULL DROP TABLE #ACC;
SELECT
    ACCOUNT_ID,
    MAX(AFL_BALANCE) AS AFL_BALANCE,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN)) AS ACC_EN_KALAN,
    CONVERT(DECIMAL(18,2), MAX(AFL_BALANCE) - SUM(PT_KALAN)) AS SHORTFALL,
    CONVERT(DECIMAL(18,2), SUM(CASE WHEN PT_PAID_OLD > 0 THEN PT_PAID_OLD ELSE 0 END)) AS ACC_PAID_ROOM
INTO #ACC
FROM #PT0
GROUP BY ACCOUNT_ID
HAVING CONVERT(DECIMAL(18,2), MAX(AFL_BALANCE) - SUM(PT_KALAN)) > @Eps;

CREATE CLUSTERED INDEX CX_ACC ON #ACC (ACCOUNT_ID);

SET @Msg = N'ACC shortfall n=' + CAST((SELECT COUNT(*) FROM #ACC) AS VARCHAR(20))
         + N' sum_shortfall=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(SHORTFALL), 0)) FROM #ACC))
         + N' sum_paid_room=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(ACC_PAID_ROOM), 0)) FROM #ACC));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT COUNT(*) AS ACC_ROOM_LT_SHORTFALL
FROM #ACC
WHERE ACC_PAID_ROOM + @Eps < SHORTFALL;

/* FIFO DESC: PAID odasindan shortfall dagit */
IF OBJECT_ID('tempdb..#CAND') IS NOT NULL DROP TABLE #CAND;
;WITH x AS (
    SELECT
        p.AGREEMENT_ID,
        p.ACCOUNT_ID,
        p.MAIN_LREF,
        p.PT_LREF,
        p.PT_PAID_OLD,
        p.PT_PAYABLE,
        p.PT_KALAN AS PT_KALAN_OLD,
        a.AFL_BALANCE,
        a.ACC_EN_KALAN,
        a.SHORTFALL,
        p.AGR_DELTA_NET,
        CONVERT(DECIMAL(18,2), CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END) AS PAID_ROOM,
        CONVERT(DECIMAL(18,2),
            SUM(CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END) OVER (
                PARTITION BY p.ACCOUNT_ID
                ORDER BY p.PT_LREF DESC
                ROWS UNBOUNDED PRECEDING
            ) - CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END
        ) AS RUN_BEFORE
    FROM #PT0 p
    INNER JOIN #ACC a ON a.ACCOUNT_ID = p.ACCOUNT_ID
)
SELECT
    AGREEMENT_ID,
    ACCOUNT_ID,
    MAIN_LREF,
    PT_LREF,
    PT_PAID_OLD,
    PT_PAYABLE,
    PT_KALAN_OLD,
    AFL_BALANCE,
    ACC_EN_KALAN,
    SHORTFALL,
    AGR_DELTA_NET,
    PAID_ROOM,
    RUN_BEFORE,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN PAID_ROOM <= 0 THEN 0
            WHEN RUN_BEFORE >= SHORTFALL THEN 0
            WHEN RUN_BEFORE + PAID_ROOM <= SHORTFALL THEN PAID_ROOM
            ELSE SHORTFALL - RUN_BEFORE
        END
    ) AS APPLY_AMT
INTO #CAND
FROM x
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #CAND WHERE APPLY_AMT <= @Eps;

CREATE CLUSTERED INDEX CX_CAND ON #CAND (PT_LREF);

IF OBJECT_ID('tempdb..#APPLY') IS NOT NULL DROP TABLE #APPLY;
SELECT
    c.*,
    CONVERT(DECIMAL(18,2), c.PT_PAID_OLD - c.APPLY_AMT) AS PT_PAID_NEW
INTO #APPLY
FROM #CAND c;

CREATE CLUSTERED INDEX CX_APPLY ON #APPLY (PT_LREF);

SET @N = (SELECT COUNT(*) FROM #APPLY);
SET @Msg = N'Aday PT reopen n=' + CAST(@N AS VARCHAR(20))
         + N' ACC=' + CAST((SELECT COUNT(DISTINCT ACCOUNT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' AGR=' + CAST((SELECT COUNT(DISTINCT AGREEMENT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' sum_apply=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(APPLY_AMT), 0)) FROM #APPLY));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

PRINT '========== TESPIT OZET ==========';
SELECT
    COUNT(*) AS PT_REOPEN_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(APPLY_AMT)) AS SUM_APPLY
FROM #APPLY;

SELECT
    CONVERT(DECIMAL(18,2), SUM(s)) AS SUM_SHORTFALL_ACC
FROM (
    SELECT ACCOUNT_ID, MAX(SHORTFALL) AS s
    FROM #APPLY
    GROUP BY ACCOUNT_ID
) d;

PRINT '========== TOP 30 ADAY ==========';
SELECT TOP 30
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAYABLE, PT_PAID_OLD, APPLY_AMT, PT_PAID_NEW, PT_KALAN_OLD,
    AFL_BALANCE, ACC_EN_KALAN, SHORTFALL, AGR_DELTA_NET
FROM #APPLY
ORDER BY APPLY_AMT DESC, AGREEMENT_ID, ACCOUNT_ID, PT_LREF;

INSERT INTO dbo.MIG_AFL_GT_EN_REOPEN_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT,
    PT_KALAN_OLD, PT_PAYABLE, AFL_BALANCE, ACC_EN_KALAN, SHORTFALL,
    AGR_DELTA_NET, NOTE
)
SELECT
    @RunId, @t0, @DryRun, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT,
    PT_KALAN_OLD, PT_PAYABLE, AFL_BALANCE, ACC_EN_KALAN, SHORTFALL,
    AGR_DELTA_NET,
    CASE WHEN @DryRun = 1 THEN N'DRY_RUN' ELSE N'APPLY_91h' END
FROM #APPLY;

IF @N = 0
BEGIN
    RAISERROR('Aday yok — PAID odasi/shortfall yok.', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @DryRun = 1
BEGIN
    RAISERROR('DRY_RUN=1 — UPDATE yok. Spot: @Agr=... sonra SEED @DryRun=0', 0, 1) WITH NOWAIT;
    RETURN;
END;

RAISERROR('========== APPLY ==========', 0, 1) WITH NOWAIT;
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, a.PT_PAID_NEW)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #APPLY a ON a.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'PT PAID reopen n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE inv
SET inv.CLOSED = CAST(0 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #APPLY) x ON x.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 1
  AND EXISTS (
        SELECT 1
        FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
      );

SET @N = @@ROWCOUNT;
SET @Msg = N'INV CLOSED=0 reopen n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

COMMIT TRAN;

PRINT '========== POST CHECK (sample) ==========';
SELECT TOP 30
    a.AGREEMENT_ID, a.ACCOUNT_ID, a.MAIN_LREF, a.PT_LREF,
    a.APPLY_AMT, a.AFL_BALANCE, a.SHORTFALL,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_NOW,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN_NOW,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED_NOW
FROM #APPLY a
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = a.PT_LREF
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = a.MAIN_LREF
ORDER BY a.APPLY_AMT DESC;

SET @Msg = CONVERT(VARCHAR(30), SYSDATETIME(), 121)
         + N' | 91h DONE apply RunId=' + CONVERT(VARCHAR(30), @RunId);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
