/* ============================================================
   FILE : prodEnergy/90_afl_frk/100_closed_lpd_null_dayanak.sql
   REPORT: MIGRATION_SCR_20260708/REPORT/100_CLOSED_LPD_NULL_DAYANAK.SQL
   SSMS — rapor (APPLY yok)

   CLOSED=1 + LASTPAIDDATE NULL → kaynak dayanak siniflama
   TYPE IN (119,121)

   Ana kume:
     PAY_0  = PAYABLETOTAL≈0 → ZERO_PAYABLE / O33 (AFL degil)
     PAY_NZ = PAYABLETOTAL>eps → asagidaki DAYANAK

   DAYANAK (oncelik sirasi):
     D_AFL_RESIDUAL_91fgi      — 91f/g/i heal LOG hit
     C_590_TAM_LOG             — MIG_TAM_IADE_CLOSE_LOG APPLY
     B_597_AFL_CANCEL_REV_SIG  — CP=1 tarihce + AFL≈0
     C_TAM_SIG_no_log          — TYPE92 + AFL≈0 + PT kapali (log yok)
     F_TAHSILAT_PARTIAL_SIG    — BANKREF veya PT.LPD var
     X_CLOSED_PAID_NO_AFL_NO_LOG
     Y_CLOSED_BUT_AFL_STILL_OPEN
     Z_OTHER

   Kural: AFL demek icin D/B/C_LOG veya (C_SIG dikkat: log yok → kanit zayif)
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @Eps DECIMAL(18,2) = 0.02;

PRINT '=== 0) Log tablolari ===';
SELECT name
FROM sys.tables
WHERE name IN (
    N'MIG_TAM_IADE_CLOSE_LOG',
    N'MIG_EN_GT_AFL_KALAN_HEAL_LOG',
    N'MIG_EN_GT_AFL_PARTIAL_HEAL_LOG',
    N'MIG_AFL_GT_EN_REOPEN_LOG',
    N'MIG_AFL_GT_EN_REOPEN_HEAL_LOG',
    N'MIG_OVERPAY_PAID_CLAMP_LOG',
    N'MIG_AFL_OVERPAY_CLAMP_HEAL_LOG',
    N'MIG_STG_CLOSE_LOG',
    N'MIG_ASIM_CLOSE_LOG'
)
ORDER BY 1;

PRINT '=== 1) Ana kume ozet ===';
SELECT
    COUNT_BIG(*) AS CNT_ALL,
    SUM(CASE WHEN ABS(ISNULL(PAYABLETOTAL,0)) <= @Eps THEN 1 ELSE 0 END) AS PAY_0,
    SUM(CASE WHEN ABS(ISNULL(PAYABLETOTAL,0)) >  @Eps THEN 1 ELSE 0 END) AS PAY_NZ
FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
WHERE TYPE IN (119, 121)
  AND CLOSED = 1
  AND LASTPAIDDATE IS NULL
OPTION (RECOMPILE, MAXDOP 8);

IF OBJECT_ID('tempdb..#NZ') IS NOT NULL DROP TABLE #NZ;
SELECT
    inv.LREF AS MAIN_LREF,
    inv.OWNERREF AS AGR,
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    inv.TYPE,
    CONVERT(DECIMAL(18,2), inv.PAYABLETOTAL) AS INV_PAY,
    CAST(0 AS BIT) AS HIT_TAM_LOG,
    CAST(0 AS BIT) AS HIT_91F,
    CAST(0 AS BIT) AS HIT_91G,
    CAST(0 AS BIT) AS HIT_91I,
    CAST(0 AS BIT) AS HAS_CANCEL_REV_HIST,
    CAST(0 AS BIT) AS AFL_OPEN_NOW,
    CAST(0 AS BIT) AS HAS_TYPE92,
    CAST(0 AS BIT) AS PT_FULL_PAID,
    CAST(0 AS BIT) AS PT_HAS_LPD,
    CAST(0 AS BIT) AS INV_HAS_BANK
INTO #NZ
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.TYPE IN (119, 121)
  AND inv.CLOSED = 1
  AND inv.LASTPAIDDATE IS NULL
  AND ABS(ISNULL(inv.PAYABLETOTAL, 0)) > @Eps
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_NZ ON #NZ (MAIN_LREF);
CREATE NONCLUSTERED INDEX IX_NZ_ACC ON #NZ (ACCOUNT_ID);

PRINT '=== 2) Log hit ===';
IF OBJECT_ID('dbo.MIG_TAM_IADE_CLOSE_LOG', 'U') IS NOT NULL
    UPDATE z SET HIT_TAM_LOG = 1
    FROM #NZ z
    WHERE EXISTS (
        SELECT 1 FROM dbo.MIG_TAM_IADE_CLOSE_LOG t WITH (NOLOCK)
        WHERE t.MAIN_LREF = z.MAIN_LREF AND ISNULL(t.DRY_RUN,0) = 0
    );

IF OBJECT_ID('dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG', 'U') IS NOT NULL
BEGIN
    DECLARE @Has91fDry BIT = CASE WHEN COL_LENGTH('dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG','DRY_RUN') IS NOT NULL THEN 1 ELSE 0 END;
    IF @Has91fDry = 1
        UPDATE z SET HIT_91F = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF AND ISNULL(t.DRY_RUN,1) = 0);
    ELSE
        UPDATE z SET HIT_91F = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF);
END

IF OBJECT_ID('dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG','DRY_RUN') IS NOT NULL
        UPDATE z SET HIT_91G = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF AND ISNULL(t.DRY_RUN,1) = 0);
    ELSE
        UPDATE z SET HIT_91G = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF);
END

IF OBJECT_ID('dbo.MIG_OVERPAY_PAID_CLAMP_LOG', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.MIG_OVERPAY_PAID_CLAMP_LOG','DRY_RUN') IS NOT NULL
        UPDATE z SET HIT_91I = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_OVERPAY_PAID_CLAMP_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF AND ISNULL(t.DRY_RUN,1) = 0);
    ELSE
        UPDATE z SET HIT_91I = 1 FROM #NZ z
        WHERE EXISTS (SELECT 1 FROM dbo.MIG_OVERPAY_PAID_CLAMP_LOG t WITH (NOLOCK)
                      WHERE t.MAIN_LREF = z.MAIN_LREF);
END
ELSE IF OBJECT_ID('dbo.MIG_AFL_OVERPAY_CLAMP_HEAL_LOG', 'U') IS NOT NULL
    UPDATE z SET HIT_91I = 1 FROM #NZ z
    WHERE EXISTS (SELECT 1 FROM dbo.MIG_AFL_OVERPAY_CLAMP_HEAL_LOG t WITH (NOLOCK)
                  WHERE t.MAIN_LREF = z.MAIN_LREF);

UPDATE z SET HAS_CANCEL_REV_HIST = 1
FROM #NZ z
WHERE EXISTS (
    SELECT 1 FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    WHERE pt.INVOICEREF = z.MAIN_LREF
      AND ISNULL(pt.IOCODE, 0) = 0
      AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 1
);

UPDATE z SET AFL_OPEN_NOW = 1
FROM #NZ z
WHERE EXISTS (
    SELECT 1 FROM dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    WHERE a.FATURAID = z.ACCOUNT_ID
      AND CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) > @Eps
);

UPDATE z SET HAS_TYPE92 = 1
FROM #NZ z
WHERE EXISTS (
    SELECT 1 FROM dbo.LS_005_01_INVOICE i WITH (NOLOCK)
    WHERE i.OWNERREF = z.AGR
      AND i.TYPE = 92
      AND ISNULL(i.CANCELED, 0) = 0
);

UPDATE z
SET PT_FULL_PAID = CASE WHEN ISNULL(p.PT_KALAN, 0) <= @Eps THEN 1 ELSE 0 END,
    PT_HAS_LPD   = CASE WHEN p.PT_LPD IS NOT NULL THEN 1 ELSE 0 END
FROM #NZ z
OUTER APPLY (
    SELECT
        SUM(CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL,0))
          - CONVERT(DECIMAL(18,2), ISNULL(pt.PAID,0))) AS PT_KALAN,
        MAX(pt.LASTPAIDDATE) AS PT_LPD
    FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    WHERE pt.INVOICEREF = z.MAIN_LREF
      AND ISNULL(pt.IOCODE, 0) = 0
      AND ISNULL(pt.CANCELED, 0) = 0
      AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
) p;

UPDATE z SET INV_HAS_BANK = 1
FROM #NZ z
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = z.MAIN_LREF
WHERE inv.BANKREF IS NOT NULL;

PRINT '=== 3) Dayanak siniflari (PAY_NZ) ===';
SELECT
    CASE
        WHEN HIT_91F = 1 OR HIT_91G = 1 OR HIT_91I = 1
            THEN 'D_AFL_RESIDUAL_91fgi'
        WHEN HIT_TAM_LOG = 1
            THEN 'C_590_TAM_LOG'
        WHEN HAS_CANCEL_REV_HIST = 1 AND AFL_OPEN_NOW = 0
            THEN 'B_597_AFL_CANCEL_REV_SIG'
        WHEN HAS_TYPE92 = 1 AND AFL_OPEN_NOW = 0 AND PT_FULL_PAID = 1
            THEN 'C_TAM_SIG_no_log'
        WHEN INV_HAS_BANK = 1 OR PT_HAS_LPD = 1
            THEN 'F_TAHSILAT_PARTIAL_SIG'
        WHEN PT_FULL_PAID = 1 AND AFL_OPEN_NOW = 0
            THEN 'X_CLOSED_PAID_NO_AFL_NO_LOG'
        WHEN AFL_OPEN_NOW = 1
            THEN 'Y_CLOSED_BUT_AFL_STILL_OPEN'
        ELSE 'Z_OTHER'
    END AS DAYANAK,
    COUNT_BIG(*) AS N,
    CONVERT(DECIMAL(18,2), SUM(INV_PAY)) AS PAY_SUM
FROM #NZ
GROUP BY
    CASE
        WHEN HIT_91F = 1 OR HIT_91G = 1 OR HIT_91I = 1
            THEN 'D_AFL_RESIDUAL_91fgi'
        WHEN HIT_TAM_LOG = 1
            THEN 'C_590_TAM_LOG'
        WHEN HAS_CANCEL_REV_HIST = 1 AND AFL_OPEN_NOW = 0
            THEN 'B_597_AFL_CANCEL_REV_SIG'
        WHEN HAS_TYPE92 = 1 AND AFL_OPEN_NOW = 0 AND PT_FULL_PAID = 1
            THEN 'C_TAM_SIG_no_log'
        WHEN INV_HAS_BANK = 1 OR PT_HAS_LPD = 1
            THEN 'F_TAHSILAT_PARTIAL_SIG'
        WHEN PT_FULL_PAID = 1 AND AFL_OPEN_NOW = 0
            THEN 'X_CLOSED_PAID_NO_AFL_NO_LOG'
        WHEN AFL_OPEN_NOW = 1
            THEN 'Y_CLOSED_BUT_AFL_STILL_OPEN'
        ELSE 'Z_OTHER'
    END
ORDER BY N DESC
OPTION (RECOMPILE, MAXDOP 8);

PRINT '=== 4) Log hit ozet ===';
SELECT
    SUM(CAST(HIT_TAM_LOG AS INT)) AS HIT_TAM,
    SUM(CAST(HIT_91F AS INT)) AS HIT_91F,
    SUM(CAST(HIT_91G AS INT)) AS HIT_91G,
    SUM(CAST(HIT_91I AS INT)) AS HIT_91I,
    SUM(CAST(HAS_CANCEL_REV_HIST AS INT)) AS HAS_CP1,
    SUM(CAST(HAS_TYPE92 AS INT)) AS HAS_92,
    SUM(CAST(AFL_OPEN_NOW AS INT)) AS AFL_OPEN,
    SUM(CAST(PT_FULL_PAID AS INT)) AS PT_PAID_FULL,
    SUM(CAST(INV_HAS_BANK AS INT)) AS HAS_BANK
FROM #NZ;

PRINT '=== 5) Heal log satir ===';
IF OBJECT_ID('dbo.MIG_TAM_IADE_CLOSE_LOG','U') IS NOT NULL
    SELECT 'TAM' AS src, COUNT(*) AS n,
           SUM(CASE WHEN DRY_RUN=0 THEN 1 ELSE 0 END) AS applied
    FROM dbo.MIG_TAM_IADE_CLOSE_LOG WITH (NOLOCK);
IF OBJECT_ID('dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG','U') IS NOT NULL
    SELECT '91f' AS src, COUNT(*) AS n FROM dbo.MIG_EN_GT_AFL_KALAN_HEAL_LOG WITH (NOLOCK);
IF OBJECT_ID('dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG','U') IS NOT NULL
    SELECT '91g' AS src, COUNT(*) AS n FROM dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG WITH (NOLOCK);
IF OBJECT_ID('dbo.MIG_OVERPAY_PAID_CLAMP_LOG','U') IS NOT NULL
    SELECT '91i' AS src, COUNT(*) AS n FROM dbo.MIG_OVERPAY_PAID_CLAMP_LOG WITH (NOLOCK);

PRINT '=== DONE ===';
GO
