/* =============================================================================
   prodREADY_ENERGY / 26a_IX_MGR_ENSURE.sql
   CREATE OR ALTER PROCEDURE dbo.SP_MIG_IX_MGR_ENSURE  (R22 2026-08-11)

   Kritik MGR IX yoksa CREATE (idempotent). FULL 00_pre yerine P0 gate seti.
   EXEC dbo.SP_MIG_IX_MGR_ENSURE @DEBUG=1;
   Sonra: EXEC dbo.SP_MIG_IX_PRECHECK;
   ============================================================================= */
USE energy;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
CREATE OR ALTER PROCEDURE dbo.SP_MIG_IX_MGR_ENSURE
    @DEBUG BIT = 1
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET IMPLICIT_TRANSACTIONS OFF;

    DECLARE @sql NVARCHAR(MAX);
    DECLARE @msg NVARCHAR(400);

    /* ---- LS_INVOICE ---- */
    IF OBJECT_ID(N'izgazMGR.dbo.LS_INVOICE', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_INVOICE') AND name=N'IX_MIG_LSINV_ACTION')
        BEGIN
            SET @sql = N'CREATE NONCLUSTERED INDEX IX_MIG_LSINV_ACTION ON izgazMGR.dbo.LS_INVOICE (ABYS_ACTION_ID) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE IX_MIG_LSINV_ACTION', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_INVOICE') AND name=N'IX_MIG_LSINV_AGR_ACTION')
        BEGIN
            SET @sql = N'CREATE NONCLUSTERED INDEX IX_MIG_LSINV_AGR_ACTION ON izgazMGR.dbo.LS_INVOICE (ABYS_AGREEMENT_ID, ABYS_ACTION_ID) INCLUDE (PAYABLETOTAL, TLTOTAL, TAX, GRANDTOTAL, IOCODE, LREF) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE IX_MIG_LSINV_AGR_ACTION', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
    END

    /* ---- LS_INVLINES ---- */
    IF OBJECT_ID(N'izgazMGR.dbo.LS_INVLINES', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_INVLINES') AND name=N'IX_MIG_LSINVLINES_LREF')
        BEGIN
            SET @sql = N'CREATE NONCLUSTERED INDEX IX_MIG_LSINVLINES_LREF ON izgazMGR.dbo.LS_INVLINES (LREF) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE IX_MIG_LSINVLINES_LREF', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_INVLINES') AND name=N'IX_MIG_LSIL_INVREF')
        BEGIN
            SET @sql = N'CREATE NONCLUSTERED INDEX IX_MIG_LSIL_INVREF ON izgazMGR.dbo.LS_INVLINES (INVOICEREF) INCLUDE (LREF, GRANDTOTAL, ABYS_INCOME_ROW_ID) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE IX_MIG_LSIL_INVREF', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
    END

    /* ---- 00d PAY / TAH ---- */
    IF OBJECT_ID(N'izgazMGR.dbo.LS_PAYMENT', N'U') IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_PAYMENT') AND name=N'UX_MIG_LS_PAYMENT_PAY_LREF')
    BEGIN
        SET @sql = N'CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_PAYMENT_PAY_LREF ON izgazMGR.dbo.LS_PAYMENT (PAY_LREF) INCLUDE (BANKA_ID, SOZLESME, CANCELED) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
        IF @DEBUG=1 RAISERROR('CREATE UX_MIG_LS_PAYMENT_PAY_LREF', 0, 1) WITH NOWAIT;
        EXEC izgazMGR.sys.sp_executesql @sql;
    END

    IF OBJECT_ID(N'izgazMGR.dbo.LS_OV_TAH_INVOICE', N'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_OV_TAH_INVOICE') AND name=N'IX_MIG_LS_OV_TAH_INVOICE_ABYS')
        BEGIN
            SET @sql = N'CREATE NONCLUSTERED INDEX IX_MIG_LS_OV_TAH_INVOICE_ABYS ON izgazMGR.dbo.LS_OV_TAH_INVOICE (ABYS_ID) INCLUDE (LREF, BANKREF, ABYS_AGREEMENT_ID) WHERE ABYS_ID IS NOT NULL WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE IX_MIG_LS_OV_TAH_INVOICE_ABYS', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
        IF NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_OV_TAH_INVOICE') AND name=N'UX_MIG_LS_OV_TAH_INVOICE_SRC')
        BEGIN
            SET @sql = N'CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_OV_TAH_INVOICE_SRC ON izgazMGR.dbo.LS_OV_TAH_INVOICE (SRC_KEY) INCLUDE (LREF, LREF_HINT, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, ABYS_ID, BANKREF) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
            IF @DEBUG=1 RAISERROR('CREATE UX_MIG_LS_OV_TAH_INVOICE_SRC', 0, 1) WITH NOWAIT;
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
    END

    IF OBJECT_ID(N'izgazMGR.dbo.LS_OV_PAY_PT', N'U') IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_OV_PAY_PT') AND name=N'UX_MIG_LS_OV_PAY_PT_SRC')
    BEGIN
        SET @sql = N'CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_OV_PAY_PT_SRC ON izgazMGR.dbo.LS_OV_PAY_PT (SRC_KEY) INCLUDE (LREF_HINT, CROSSREF_MAIN_LREF, ABYS_ID, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, CANCELED) WITH (MAXDOP=8, ONLINE=ON, SORT_IN_TEMPDB=ON);';
        IF @DEBUG=1 RAISERROR('CREATE UX_MIG_LS_OV_PAY_PT_SRC', 0, 1) WITH NOWAIT;
        EXEC izgazMGR.sys.sp_executesql @sql;
    END

    /* ---- 00i MAP clustered (HEAP ise) ---- */
    IF OBJECT_ID(N'izgazMGR.dbo.LS_OV_ID_MAP', N'U') IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_OV_ID_MAP') AND type=1)
    BEGIN
        IF EXISTS (SELECT 1 FROM izgazMGR.sys.indexes WHERE object_id=OBJECT_ID(N'izgazMGR.dbo.LS_OV_ID_MAP') AND name=N'UX_LS_OV_ID_MAP_SRC')
        BEGIN
            IF @DEBUG=1 RAISERROR('DROP UX_LS_OV_ID_MAP_SRC (NC→clustered)', 0, 1) WITH NOWAIT;
            SET @sql = N'DROP INDEX UX_LS_OV_ID_MAP_SRC ON izgazMGR.dbo.LS_OV_ID_MAP;';
            EXEC izgazMGR.sys.sp_executesql @sql;
        END
        IF @DEBUG=1 RAISERROR('ADD PK_LS_OV_ID_MAP CLUSTERED', 0, 1) WITH NOWAIT;
        SET @sql = N'ALTER TABLE izgazMGR.dbo.LS_OV_ID_MAP ADD CONSTRAINT PK_LS_OV_ID_MAP PRIMARY KEY CLUSTERED (SRC_KEY) WITH (MAXDOP=8, ONLINE=OFF, SORT_IN_TEMPDB=ON);';
        BEGIN TRY
            EXEC izgazMGR.sys.sp_executesql @sql;
        END TRY
        BEGIN CATCH
            SET @msg = N'MAP clustered SKIP: ' + ERROR_MESSAGE();
            RAISERROR('%s', 0, 1, @msg) WITH NOWAIT;
        END CATCH
    END

    RAISERROR('SP_MIG_IX_MGR_ENSURE DONE — simdi SP_MIG_IX_PRECHECK', 0, 1) WITH NOWAIT;
END
GO
/* EXEC dbo.SP_MIG_IX_MGR_ENSURE @DEBUG=1; EXEC dbo.SP_MIG_IX_PRECHECK; */
