/* =============================================================================
   prodREADY_ENERGY / 26d_IX_IP_AGR.sql
   CREATE OR ALTER PROCEDURE dbo.SP_MIG_IX_IP_AGR  (R22 2026-08-11)

   613 P0 — LS_005_01_INSTALLMENT_PLAN (ABYS_AGREEMENT_ID) IX.
   Ne zaman: 611 INSERT BITMIS, 613 BASLAMADAN.
   EXEC dbo.SP_MIG_IX_IP_AGR;
   ============================================================================= */
USE energy;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
CREATE OR ALTER PROCEDURE dbo.SP_MIG_IX_IP_AGR
    @DEBUG BIT = 1
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET IMPLICIT_TRANSACTIONS OFF;

    IF OBJECT_ID(N'dbo.LS_005_01_INSTALLMENT_PLAN', N'U') IS NULL
    BEGIN
        RAISERROR('LS_005_01_INSTALLMENT_PLAN yok — once 611', 16, 1);
        RETURN;
    END

    IF EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.LS_005_01_INSTALLMENT_PLAN')
          AND name = N'IX_MIG_LS005_IP_AGR'
    )
    BEGIN
        IF @DEBUG = 1
            RAISERROR('SKIP IX_MIG_LS005_IP_AGR (exists)', 0, 1) WITH NOWAIT;
        RETURN;
    END

    IF @DEBUG = 1
        RAISERROR('CREATE ONLINE IX_MIG_LS005_IP_AGR ...', 0, 1) WITH NOWAIT;

    CREATE NONCLUSTERED INDEX IX_MIG_LS005_IP_AGR
        ON dbo.LS_005_01_INSTALLMENT_PLAN (ABYS_AGREEMENT_ID)
        INCLUDE (
            LREF, PLAN_ID, ABYS_ID, ABYS_INSTALLMENT_ID, ISACTIVE,
            ABYS_CANCELLATION_DATE, ABYS_CANCEL_CAUSE_ID, ABYS_CANCELLATION_USER_ID,
            TOTAL_AMOUNT, INSTALLMENT_COUNT, ABYS_ORDER_NUMBER,
            PAYTRANS_REF, INVOICE_REF, ABYS_DUE_DATE, ABYS_EXPIRY_DATE
        )
        WITH (ONLINE = ON, MAXDOP = 8, SORT_IN_TEMPDB = ON);

    RAISERROR('OK IX_MIG_LS005_IP_AGR', 0, 1) WITH NOWAIT;
END
GO
/* EXEC dbo.SP_MIG_IX_IP_AGR; */
