/* ============================================================
   00f_597_v4_indexes.sql
   597 INSERT/WIRE v4 — performans & guven indexleri

   Eksikler (2026-08-04 kontrol):
     - MGR LS_OV_TAH_INVOICE / LS_OV_PAY_PT: SRC_KEY index YOK (batch join)
     - MGR LS_OV_ID_MAP: ENERGY_LREF sadece INCLUDE; CLEAN IS NOT NULL seek yok
     - energy STG_TAH_KEYS: SRC_KEY NC yok (DELETE batch)
     - energy STG_PAY: (USE_HINT, SRC_KEY) hint batch ORDER BY

   Energy tarafinda PT INVREF_IO / MAP ELREF_KIND / BANK UX zaten var.
   ONLINE=ON (Enterprise); basarisizsa ONLINE=OFF dene.
   ============================================================ */
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ---- izgazMGR ---- */
USE izgazMGR;
GO

IF OBJECT_ID('dbo.LS_OV_TAH_INVOICE', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_OV_TAH_INVOICE', 'SRC_KEY') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_TAH_INVOICE') AND name = 'UX_MIG_LS_OV_TAH_INVOICE_SRC'
)
BEGIN
    RAISERROR('CREATE UX_MIG_LS_OV_TAH_INVOICE_SRC ...', 0, 1) WITH NOWAIT;
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_OV_TAH_INVOICE_SRC
        ON dbo.LS_OV_TAH_INVOICE (SRC_KEY)
        INCLUDE (LREF, LREF_HINT, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, ABYS_ID, BANKREF)
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

IF OBJECT_ID('dbo.LS_OV_PAY_PT', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_OV_PAY_PT', 'SRC_KEY') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_PAY_PT') AND name = 'UX_MIG_LS_OV_PAY_PT_SRC'
)
BEGIN
    RAISERROR('CREATE UX_MIG_LS_OV_PAY_PT_SRC ...', 0, 1) WITH NOWAIT;
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_LS_OV_PAY_PT_SRC
        ON dbo.LS_OV_PAY_PT (SRC_KEY)
        INCLUDE (LREF_HINT, CROSSREF_MAIN_LREF, ABYS_ID, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, CANCELED)
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* CLEAN MAP null: sadece dolu ENERGY_LREF — energy IX_MIG_OV_ID_MAP_ELREF_KIND aynisi */
IF OBJECT_ID('dbo.LS_OV_ID_MAP', 'U') IS NOT NULL
AND COL_LENGTH('dbo.LS_OV_ID_MAP', 'ENERGY_LREF') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_OV_ID_MAP') AND name = 'IX_OV_ID_MAP_ELREF_KIND'
)
BEGIN
    RAISERROR('CREATE IX_OV_ID_MAP_ELREF_KIND ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_OV_ID_MAP_ELREF_KIND
        ON dbo.LS_OV_ID_MAP (ENERGY_LREF, OV_KIND)
        INCLUDE (ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, SRC_KEY)
        WHERE ENERGY_LREF IS NOT NULL
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

/* ---- energy staging ---- */
USE energy;
GO

IF OBJECT_ID('dbo.MIG_597_STG_TAH_KEYS', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_597_STG_TAH_KEYS') AND name = 'IX_MIG_597_STG_TAH_KEYS_SRC'
)
BEGIN
    RAISERROR('CREATE IX_MIG_597_STG_TAH_KEYS_SRC ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_597_STG_TAH_KEYS_SRC
        ON dbo.MIG_597_STG_TAH_KEYS (SRC_KEY);
END
GO

IF OBJECT_ID('dbo.MIG_597_STG_PAY', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_597_STG_PAY') AND name = 'IX_MIG_597_STG_PAY_HINT_SRC'
)
BEGIN
    RAISERROR('CREATE IX_MIG_597_STG_PAY_HINT_SRC ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_597_STG_PAY_HINT_SRC
        ON dbo.MIG_597_STG_PAY (USE_HINT, SRC_KEY)
        INCLUDE (LREF_HINT);
END
GO

/* energy MAP — zaten olmali; yoksa olustur */
IF OBJECT_ID('dbo.MIG_OV_ID_MAP', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.MIG_OV_ID_MAP') AND name = 'IX_MIG_OV_ID_MAP_ELREF_KIND'
)
BEGIN
    RAISERROR('CREATE IX_MIG_OV_ID_MAP_ELREF_KIND ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_OV_ID_MAP_ELREF_KIND
        ON dbo.MIG_OV_ID_MAP (ENERGY_LREF, OV_KIND)
        INCLUDE (ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, SRC_KEY)
        WHERE ENERGY_LREF IS NOT NULL
        WITH (ONLINE = ON, MAXDOP = 8);
END
GO

RAISERROR('00f_597_v4_indexes DONE', 0, 1) WITH NOWAIT;
GO
