/*
  00h_post597_online_indexes.sql
  ---------------------------------------------------------------
  93b TTK + E8 IPP için ONLINE index.
  Enterprise ONLINE=ON. 597 RUNNING iken çalıştırma.
*/
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET IMPLICIT_TRANSACTIONS OFF;

USE energy;
GO

IF EXISTS (
    SELECT 1 FROM sys.dm_exec_requests r
    CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t
    WHERE r.session_id <> @@SPID AND t.text LIKE N'%SP_MIG_597%'
)
BEGIN
    RAISERROR('597 RUNNING — 00h iptal', 16, 1);
    RETURN;
END
GO

RAISERROR('========== 00h POST-597 ONLINE INDEXES ==========', 0, 1) WITH NOWAIT;

/* ---- P0: INVLINES (disabled → REBUILD ONLINE) ---- */
IF EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVLINES')
      AND name = N'IX_MIG_IL_INVREF'
      AND is_disabled = 1
)
BEGIN
    RAISERROR('REBUILD ONLINE IX_MIG_IL_INVREF ...', 0, 1) WITH NOWAIT;
    ALTER INDEX IX_MIG_IL_INVREF ON dbo.LS_005_01_INVLINES
        REBUILD WITH (ONLINE = ON, MAXDOP = 8, SORT_IN_TEMPDB = ON);
    RAISERROR('OK IX_MIG_IL_INVREF', 0, 1) WITH NOWAIT;
END
ELSE
    RAISERROR('SKIP IX_MIG_IL_INVREF (yok veya zaten enabled)', 0, 1) WITH NOWAIT;

IF EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVLINES')
      AND name = N'IX_MIG_IL_ABYS_AGR'
      AND is_disabled = 1
)
BEGIN
    RAISERROR('REBUILD ONLINE IX_MIG_IL_ABYS_AGR ...', 0, 1) WITH NOWAIT;
    ALTER INDEX IX_MIG_IL_ABYS_AGR ON dbo.LS_005_01_INVLINES
        REBUILD WITH (ONLINE = ON, MAXDOP = 8, SORT_IN_TEMPDB = ON);
    RAISERROR('OK IX_MIG_IL_ABYS_AGR', 0, 1) WITH NOWAIT;
END
ELSE
    RAISERROR('SKIP IX_MIG_IL_ABYS_AGR (yok veya zaten enabled)', 0, 1) WITH NOWAIT;

/* ---- P0: AFL FATURAID ---- */
IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE object_id = OBJECT_ID('dbo.LS_AFL_OPEN_DEBT')
          AND name = N'IX_MIG_AFL_FATURAID'
   )
BEGIN
    RAISERROR('CREATE ONLINE IX_MIG_AFL_FATURAID ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_AFL_FATURAID
        ON dbo.LS_AFL_OPEN_DEBT (FATURAID)
        INCLUDE (BALANCE, TAKSIT_DURUMU, YT_DURUMU, MIG_IN_SCOPE)
        WITH (ONLINE = ON, MAXDOP = 8, SORT_IN_TEMPDB = ON);
    RAISERROR('OK IX_MIG_AFL_FATURAID', 0, 1) WITH NOWAIT;
END
ELSE
    RAISERROR('SKIP IX_MIG_AFL_FATURAID', 0, 1) WITH NOWAIT;

/* ---- P1: PAYTRANS INST_NR (E8) ---- */
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'IX_MIG_PT_INST_INV'
)
BEGIN
    RAISERROR('CREATE ONLINE IX_MIG_PT_INST_INV ...', 0, 1) WITH NOWAIT;
    CREATE NONCLUSTERED INDEX IX_MIG_PT_INST_INV
        ON dbo.LS_005_01_PAYTRANS (INST_NR, INVOICEREF)
        INCLUDE (PAID, PAYABLETOTAL, IOCODE, CANCELED, BANKREF, LASTPAIDDATE, BANK_RECORD_REF, XTYPE)
        WHERE INST_NR > 0 AND IOCODE = 0
        WITH (ONLINE = ON, MAXDOP = 8, SORT_IN_TEMPDB = ON);
    RAISERROR('OK IX_MIG_PT_INST_INV', 0, 1) WITH NOWAIT;
END
ELSE
    RAISERROR('SKIP IX_MIG_PT_INST_INV (exists)', 0, 1) WITH NOWAIT;

SELECT
    OBJECT_NAME(i.object_id) AS obj,
    i.name,
    i.is_disabled,
    i.has_filter
FROM sys.indexes i
WHERE i.name IN (
    N'IX_MIG_IL_INVREF', N'IX_MIG_IL_ABYS_AGR',
    N'IX_MIG_AFL_FATURAID', N'IX_MIG_PT_INST_INV'
)
ORDER BY obj, i.name;

RAISERROR('========== 00h DONE ==========', 0, 1) WITH NOWAIT;
GO
