/* =============================================================================
   prodREADY_ENERGY / 09b_UNDO_IADE_MAIN
   Kismi 590 geri alma (MAP modeli):
     - IADE_IL / IADE_INV sil (ENERGY_LREF)
     - MAIN CANCEL_* + RETURN_TARGET sifirla (CLOSED dokunulmaz)
     - MAP ENERGY_LREF NULL (IADE_*)
   Dokunmaz: PAY_PT / TAH_INV / CANCEL_* / KISMI (ENERGY_LREF zaten NULL)

   Onkosul dry-run:
     IADE_IL ~558601 | IADE_INV ~141905 | MAIN_RESET ~141902
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @d INT, @n BIGINT, @Msg NVARCHAR(200);

RAISERROR('========== 09b UNDO IADE + MAIN START ==========', 0, 1) WITH NOWAIT;

/* ----- 0) Baslangic sayim ----- */
SELECT 'START_IADE_IL' AS K, COUNT(*) AS N
FROM dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVLINES il WITH (NOLOCK) ON il.LREF = m.ENERGY_LREF
WHERE m.OV_KIND = 'IADE_IL' AND m.ENERGY_LREF IS NOT NULL
UNION ALL
SELECT 'START_IADE_INV', COUNT(*)
FROM dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = m.ENERGY_LREF
WHERE m.OV_KIND = 'IADE_INV' AND m.ENERGY_LREF IS NOT NULL
UNION ALL
SELECT 'START_MAIN_RESET', COUNT(*)
FROM izgazMGR.dbo.LS_OV_MAIN_UPD u WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = CAST(u.LREF AS INT)
WHERE inv.CANCEL_DATE IS NOT NULL OR inv.RETURN_TARGET_INVREF IS NOT NULL;

/* ----- 1) IADE INVLINES (MAP IADE_IL) ----- */
SET @n = 0;
WHILE 1 = 1
BEGIN
    DELETE TOP (20000) il
    FROM dbo.LS_005_01_INVLINES il WITH (ROWLOCK)
    INNER JOIN dbo.MIG_OV_ID_MAP m ON m.ENERGY_LREF = il.LREF AND m.OV_KIND = 'IADE_IL';

    SET @d = @@ROWCOUNT;
    IF @d = 0 BREAK;
    SET @n += @d;
    SET @Msg = N'IADE_IL deleted +' + CAST(@d AS NVARCHAR(20)) + N' (tot ' + CAST(@n AS NVARCHAR(20)) + N')';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END
RAISERROR('--- 1/4 IADE_IL done tot=%I64d ---', 0, 1, @n) WITH NOWAIT;

/* ----- 1b) Yetim IL (INVOICEREF = IADE_INV) ----- */
SET @n = 0;
WHILE 1 = 1
BEGIN
    DELETE TOP (20000) il
    FROM dbo.LS_005_01_INVLINES il WITH (ROWLOCK)
    INNER JOIN dbo.MIG_OV_ID_MAP m ON m.ENERGY_LREF = il.INVOICEREF AND m.OV_KIND = 'IADE_INV';

    SET @d = @@ROWCOUNT;
    IF @d = 0 BREAK;
    SET @n += @d;
    SET @Msg = N'IADE_IL by INV +' + CAST(@d AS NVARCHAR(20)) + N' (tot ' + CAST(@n AS NVARCHAR(20)) + N')';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END
RAISERROR('--- 1b IADE_IL by INV done tot=%I64d ---', 0, 1, @n) WITH NOWAIT;

/* ----- 2) IADE INVOICE ----- */
SET @n = 0;
WHILE 1 = 1
BEGIN
    DELETE TOP (10000) inv
    FROM dbo.LS_005_01_INVOICE inv WITH (ROWLOCK)
    INNER JOIN dbo.MIG_OV_ID_MAP m ON m.ENERGY_LREF = inv.LREF AND m.OV_KIND = 'IADE_INV';

    SET @d = @@ROWCOUNT;
    IF @d = 0 BREAK;
    SET @n += @d;
    SET @Msg = N'IADE_INV deleted +' + CAST(@d AS NVARCHAR(20)) + N' (tot ' + CAST(@n AS NVARCHAR(20)) + N')';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END
RAISERROR('--- 2/4 IADE_INV done tot=%I64d ---', 0, 1, @n) WITH NOWAIT;

/* ----- 3) MAIN CANCEL_* + RETURN_TARGET (CLOSED dokunma) ----- */
UPDATE inv
SET inv.RETURN_TARGET_INVREF = NULL,
    inv.CANCEL_DATE = NULL,
    inv.CANCEL_REASON_ID = NULL,
    inv.CANCEL_USER_ID = NULL
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN izgazMGR.dbo.LS_OV_MAIN_UPD u WITH (NOLOCK)
    ON inv.LREF = CAST(u.LREF AS INT)
WHERE inv.CANCEL_DATE IS NOT NULL
   OR inv.RETURN_TARGET_INVREF IS NOT NULL
   OR inv.CANCEL_REASON_ID IS NOT NULL
   OR inv.CANCEL_USER_ID IS NOT NULL
OPTION (RECOMPILE, MAXDOP 24);

SET @d = @@ROWCOUNT;
RAISERROR('--- 3/4 MAIN reset rows=%d (CLOSED untouched) ---', 0, 1, @d) WITH NOWAIT;

/* ----- 4) MAP ENERGY_LREF NULL ----- */
UPDATE dbo.MIG_OV_ID_MAP
SET ENERGY_LREF = NULL
WHERE OV_KIND IN ('IADE_INV', 'IADE_IL', 'IADE_PT')
  AND ENERGY_LREF IS NOT NULL;

SET @d = @@ROWCOUNT;
RAISERROR('--- 4a MIG_OV_ID_MAP cleared=%d ---', 0, 1, @d) WITH NOWAIT;

IF OBJECT_ID('izgazMGR.dbo.LS_OV_ID_MAP', 'U') IS NOT NULL
BEGIN
    UPDATE izgazMGR.dbo.LS_OV_ID_MAP
    SET ENERGY_LREF = NULL
    WHERE OV_KIND IN ('IADE_INV', 'IADE_IL', 'IADE_PT')
      AND ENERGY_LREF IS NOT NULL;

    SET @d = @@ROWCOUNT;
    RAISERROR('--- 4b LS_OV_ID_MAP cleared=%d ---', 0, 1, @d) WITH NOWAIT;
END
GO

/* ----- Dogrulama ----- */
SELECT 'LEFT_IADE_INV' AS K, COUNT(*) AS N
FROM dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = m.ENERGY_LREF
WHERE m.OV_KIND = 'IADE_INV'
UNION ALL
SELECT 'LEFT_IADE_IL', COUNT(*)
FROM dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVLINES il WITH (NOLOCK) ON il.LREF = m.ENERGY_LREF
WHERE m.OV_KIND = 'IADE_IL'
UNION ALL
SELECT 'LEFT_MAIN_CANCEL', COUNT(*)
FROM izgazMGR.dbo.LS_OV_MAIN_UPD u WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = CAST(u.LREF AS INT)
WHERE inv.CANCEL_DATE IS NOT NULL OR inv.RETURN_TARGET_INVREF IS NOT NULL
UNION ALL
SELECT 'MAP_IADE_FILLED', COUNT(*)
FROM dbo.MIG_OV_ID_MAP WITH (NOLOCK)
WHERE OV_KIND IN ('IADE_INV', 'IADE_IL', 'IADE_PT')
  AND ENERGY_LREF IS NOT NULL;

RAISERROR('========== 09b UNDO DONE — beklenen LEFT_*=0, MAP_IADE_FILLED=0 ==========', 0, 1) WITH NOWAIT;
GO
