/*
  22b_597_DEBT_PT_BACKFILL.sql
  ---------------------------------------------------------------
  GATE_FAIL: PAY_PT CROSSREF not debt-PT
  Sebep: CROSSREF_MAIN faturasi energy'de var, debt PT (IOCODE=0) yok.
  MGR LS_DEBT_PAYTRANS'tan eksik debt PT'leri IDENTITY_INSERT ile tamamla,
  sonra: EXEC SP_MIG_597_WIRE @AGR_ID=NULL, @DEBUG=1;
         EXEC SP_MIG_597_GATE @AGR_ID=NULL;

  Kosul: 597 RUNNING olmamali. Dis TRAN YASAK.
*/
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET IMPLICIT_TRANSACTIONS OFF;
SET XACT_ABORT ON;

USE energy;
GO

IF EXISTS (
    SELECT 1 FROM sys.dm_exec_requests r
    CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t
    WHERE r.session_id <> @@SPID AND t.text LIKE N'%SP_MIG_597%'
)
BEGIN
    RAISERROR('597 RUNNING — debt backfill iptal', 16, 1);
    RETURN;
END
GO

RAISERROR('========== 22b DEBT PT BACKFILL (GATE xref) ==========', 0, 1) WITH NOWAIT;

IF OBJECT_ID('tempdb..#fail_main') IS NOT NULL DROP TABLE #fail_main;
SELECT DISTINCT CAST(s.CROSSREF_MAIN_LREF AS INT) AS MAIN_LREF
INTO #fail_main
FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
INNER JOIN dbo.MIG_OV_ID_MAP m WITH (NOLOCK)
    ON m.ENERGY_LREF = pt.LREF AND m.OV_KIND = N'PAY_PT'
INNER JOIN izgazMGR.dbo.LS_OV_PAY_PT s WITH (NOLOCK)
    ON s.SRC_KEY = m.SRC_KEY
WHERE pt.CROSSREF IS NOT NULL
  AND NOT EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS d WITH (NOLOCK)
        WHERE d.LREF = pt.CROSSREF
          AND ISNULL(d.IOCODE, 0) = 0
      )
OPTION (MAXDOP 8);

CREATE UNIQUE CLUSTERED INDEX IX ON #fail_main(MAIN_LREF);

DECLARE @Mains int = (SELECT COUNT(*) FROM #fail_main);
RAISERROR('fail_mains=%d', 0, 1, @Mains) WITH NOWAIT;

IF OBJECT_ID('tempdb..#ins') IS NOT NULL DROP TABLE #ins;
SELECT
    CAST(d.ABYS_ID AS INT) AS LREF,
    CAST(d.INVOICEREF AS INT) AS INVOICEREF,
    CAST(d.[TYPE] AS TINYINT) AS [TYPE],
    CAST(ISNULL(d.IOCODE, 0) AS TINYINT) AS IOCODE,
    CAST(d.PAYTYPE AS TINYINT) AS PAYTYPE,
    CAST(d.TRANSTYPE AS INT) AS TRANSTYPE,
    CAST(d.LINETYPE AS INT) AS LINETYPE,
    CAST(ISNULL(d.INST_NR, 0) AS TINYINT) AS INST_NR,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(d.DATE_ AS DATETIME2)) AS DATE_,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(d.DUEDATE AS DATETIME2)) AS DUEDATE,
    /* LS_001: TLTOTAL=KDV haric; GRANDTOTAL=KDV dahil; alan-alan (MGR yoksa INV) */
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), COALESCE(d.TLTOTAL, inv.TLTOTAL))) AS TLTOTAL,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), COALESCE(d.CURTOTAL, inv.CURTOTAL, d.TLTOTAL, inv.TLTOTAL))) AS CURTOTAL,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), ISNULL(COALESCE(d.TAX, inv.TAX), 0))) AS TAX,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), COALESCE(d.GRANDTOTAL, inv.GRANDTOTAL))) AS GRANDTOTAL,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), COALESCE(d.PAYABLETOTAL, inv.PAYABLETOTAL, d.GRANDTOTAL, inv.GRANDTOTAL))) AS PAYABLETOTAL,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), ISNULL(COALESCE(d.DV, inv.DV), 0))) AS DV,
    CONVERT(FLOAT, CONVERT(DECIMAL(18, 2), ISNULL(d.PAID, 0))) AS PAID,
    CAST(ISNULL(d.CANCELED, 0) AS BIT) AS CANCELED,
    CAST(ISNULL(d.CANCELLATIONPAYMENT, 0) AS BIT) AS CANCELLATIONPAYMENT,
    CAST(d.CLIENTREF AS INT) AS CLIENTREF,
    d.ABYS_ID,
    d.ABYS_ACCOUNT_ID,
    d.ABYS_AGREEMENT_ID,
    CAST(d.CROSSREF AS INT) AS CROSSREF,
    CAST(d.BANKREF AS INT) AS BANKREF,
    CAST(LEFT(d.BANK_RECORD_REF, 100) AS NVARCHAR(100)) AS BANK_RECORD_REF,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(d.LASTPAIDDATE AS DATETIME2)) AS LASTPAIDDATE,
    CAST(d.XTYPE AS INT) AS XTYPE,
    CAST(d.BANKACCREF AS INT) AS BANKACCREF
INTO #ins
FROM izgazMGR.dbo.LS_DEBT_PAYTRANS d WITH (NOLOCK)
INNER JOIN #fail_main f ON f.MAIN_LREF = CAST(d.INVOICEREF AS INT)
LEFT JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.LREF = CAST(d.INVOICEREF AS INT)
WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS e WITH (NOLOCK)
        WHERE e.INVOICEREF = CAST(d.INVOICEREF AS INT)
          AND ISNULL(e.IOCODE, 0) = 0
      )
  AND NOT EXISTS (
        SELECT 1 FROM dbo.LS_005_01_PAYTRANS e WITH (NOLOCK)
        WHERE e.LREF = CAST(d.ABYS_ID AS INT)
      )
  AND d.ABYS_ID BETWEEN 1 AND 2147483647
OPTION (MAXDOP 8);

DECLARE @ToIns int = (SELECT COUNT(*) FROM #ins);
RAISERROR('to_insert=%d', 0, 1, @ToIns) WITH NOWAIT;

IF @ToIns = 0
BEGIN
    RAISERROR('Insert yok — WIRE/GATE dene', 0, 1) WITH NOWAIT;
END
ELSE
BEGIN
    SET IDENTITY_INSERT dbo.LS_005_01_PAYTRANS ON;

    INSERT INTO dbo.LS_005_01_PAYTRANS (
        LREF, INVOICEREF, [TYPE], IOCODE, PAYTYPE, TRANSTYPE, LINETYPE, INST_NR,
        DATE_, DUEDATE, TLTOTAL, CURTOTAL, TAX, GRANDTOTAL, PAYABLETOTAL, DV, PAID,
        CANCELED, CANCELLATIONPAYMENT, CLIENTREF,
        ABYS_ID, ABYS_ACCOUNT_ID, ABYS_AGREEMENT_ID, CROSSREF,
        BANKREF, BANK_RECORD_REF, LASTPAIDDATE, XTYPE, BANKACCREF,
        ABYS_INVOICE_LREF
    )
    SELECT
        LREF, INVOICEREF, [TYPE], IOCODE, PAYTYPE, TRANSTYPE, LINETYPE, INST_NR,
        DATE_, DUEDATE, TLTOTAL, CURTOTAL, TAX, GRANDTOTAL, PAYABLETOTAL, DV, PAID,
        CANCELED, CANCELLATIONPAYMENT, CLIENTREF,
        ABYS_ID, ABYS_ACCOUNT_ID, ABYS_AGREEMENT_ID, CROSSREF,
        BANKREF, BANK_RECORD_REF, LASTPAIDDATE, XTYPE, BANKACCREF,
        INVOICEREF
    FROM #ins
    OPTION (MAXDOP 8);

    DECLARE @N int = @@ROWCOUNT;
    SET IDENTITY_INSERT dbo.LS_005_01_PAYTRANS OFF;
    RAISERROR('inserted=%d', 0, 1, @N) WITH NOWAIT;
END

/* sanity */
SELECT
    (SELECT COUNT(*) FROM #fail_main) AS fail_mains,
    (SELECT COUNT(*) FROM #fail_main f
     WHERE EXISTS (
         SELECT 1 FROM dbo.LS_005_01_PAYTRANS d WITH (NOLOCK)
         WHERE d.INVOICEREF = f.MAIN_LREF AND ISNULL(d.IOCODE, 0) = 0
     )) AS mains_with_debt_now;

RAISERROR('========== 22b DONE — next: WIRE then GATE ==========', 0, 1) WITH NOWAIT;
GO
