-- =============================================================================
-- prodREADY_ENERGY3007 / 30_overlay_590_597.sql
-- C: 590 eksilten  → D: 597 tahsilat
-- Onkosul: B (571/581/575) bitti; deploy 10→11→12→19 ve 20→21→22→29
--
-- @AGR_ID: NULL=FULL | >0=tek AGR | -1=NO_AGR
-- =============================================================================
USE energy;
GO
SET NOCOUNT ON;

/* >>> OPERATOR: 20 ile ayni scope (NULL/ >0 / -1) <<< */
DECLARE @AGR_ID BIGINT = NULL;  -- ornek: 197168 / 1034469 / -1
-- SET @AGR_ID = 197168;

RAISERROR('========== E3007-C) 590 EKSILTEN ==========', 0, 1) WITH NOWAIT;
PRINT 'AGR=' + CASE WHEN @AGR_ID IS NULL THEN 'FULL' WHEN @AGR_ID = -1 THEN 'NO_AGR' ELSE CAST(@AGR_ID AS VARCHAR(20)) END;
IF OBJECT_ID('dbo.SP_MIG_590_ALL', 'P') IS NULL
    RAISERROR('SP_MIG_590_ALL yok — prodREADY_ENERGY 10→19 deploy', 16, 1);
ELSE
    EXEC dbo.SP_MIG_590_ALL @AGR_ID = @AGR_ID, @CLEAN = 1, @DEBUG = 1;

-- GATE_PASS olmadan 597'ye gecme (SP icinde RAISE eder)

RAISERROR('========== E3007-D) 597 TAHSILAT ==========', 0, 1) WITH NOWAIT;
PRINT 'AGR=' + CASE WHEN @AGR_ID IS NULL THEN 'FULL' WHEN @AGR_ID = -1 THEN 'NO_AGR' ELSE CAST(@AGR_ID AS VARCHAR(20)) END;
IF OBJECT_ID('dbo.SP_MIG_597_ALL', 'P') IS NULL
    RAISERROR('SP_MIG_597_ALL yok — prodREADY_ENERGY 20→29 deploy', 16, 1);
ELSE
    EXEC dbo.SP_MIG_597_ALL @AGR_ID = @AGR_ID, @CLEAN = 1, @DEBUG = 1;

/* Soft check (scope) */
SELECT
    COUNT(*) AS DEBT_PAID_SRC,
    SUM(CASE WHEN ISNULL(CLOSED,0)=1 THEN 1 ELSE 0 END) AS CLOSED_N,
    SUM(CASE WHEN LASTPAIDDATE IS NOT NULL THEN 1 ELSE 0 END) AS LPD_N
FROM izgazMGR.dbo.LS_OV_DEBT_PAID_UPD WITH (NOLOCK)
WHERE (
          @AGR_ID IS NULL
       OR (@AGR_ID = -1 AND ABYS_AGREEMENT_ID IS NULL)
       OR (@AGR_ID > 0 AND ABYS_AGREEMENT_ID = @AGR_ID)
      );

SELECT
    SUM(CASE WHEN ISNULL(CLOSED,0)=1 THEN 1 ELSE 0 END) AS EN_CLOSED,
    SUM(CASE WHEN LASTPAIDDATE IS NOT NULL THEN 1 ELSE 0 END) AS EN_LPD,
    SUM(CASE WHEN BANKREF IS NOT NULL THEN 1 ELSE 0 END) AS EN_BANK
FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
WHERE ISNULL(IOCODE,0)=0 AND ISNULL(CANCELED,0)=0
  AND (
          @AGR_ID IS NULL
       OR (@AGR_ID = -1 AND ABYS_AGREEMENT_ID IS NULL AND ABYS_ACCOUNT_ID IS NOT NULL)
       OR (@AGR_ID > 0 AND (OWNERREF = @AGR_ID OR ABYS_AGREEMENT_ID = @AGR_ID))
      );

PRINT '========== E3007-CD OK AGR='
    + CASE WHEN @AGR_ID IS NULL THEN 'FULL' WHEN @AGR_ID = -1 THEN 'NO_AGR' ELSE CAST(@AGR_ID AS VARCHAR(20)) END
    + ' ==========';
GO
