/* ============================================================
   FILE : prodREADY_ENERGY3007 / 91_debt_pt_dup_cleanup.sql
   FAZ  : DUP_2X — INSTALLMENT_PLAN_REF IS NULL faturalarda
          ayni INVOICEREF icin birden fazla aktif ana borc PT (INST_NR=0)

   Onkosul: 575 guard + 576 UX deploy (opsiyonel; cleanup once UX)
   Sonra  : UX_MIG_PT_DEBT_INV_INST0 create (bu script sonunda)
            filter: CANCELED=0 AND (CP=0 OR CP IS NULL)

   KEEP kurali:
     0) CANCELLATIONPAYMENT=1 (CANCEL_REV) → DROP adayi (asla KEEP)
     1) PT.ABYS_ID = INV.ABYS_ID
     2) PT.ABYS_ID = INV.LREF
     3) uzerine tahsilat CROSSREF var
     4) MIN(PT.LREF)
   DROP  : diger aktif INST_NR=0 → CANCELED=1 (soft)
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @DryRun BIT = 1;   -- 0 = uygula
DECLARE @Eps DECIMAL(18,2) = 0.02;

IF OBJECT_ID('tempdb..#DUP') IS NOT NULL DROP TABLE #DUP;
IF OBJECT_ID('tempdb..#KEEP') IS NOT NULL DROP TABLE #KEEP;

;WITH multi AS (
    SELECT INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
    WHERE IOCODE = 0
      AND ISNULL(INST_NR, 0) = 0
      AND ISNULL(CANCELED, 0) = 0
    GROUP BY INVOICEREF
    HAVING COUNT(*) > 1
)
SELECT
    inv.LREF AS INV_LREF,
    inv.ABYS_ID AS INV_ABYS_ID,
    CONVERT(DECIMAL(18,2), inv.PAYABLETOTAL) AS INV_P,
    pt.LREF AS PT_LREF,
    pt.ABYS_ID AS PT_ABYS_ID,
    CONVERT(DECIMAL(18,2), pt.PAYABLETOTAL) AS PT_P,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID,
    CAST(ISNULL(pt.CANCELLATIONPAYMENT, 0) AS TINYINT) AS CP,
    (
        SELECT COUNT(*)
        FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
        WHERE t.CROSSREF = pt.LREF
          AND ISNULL(t.IOCODE, 0) = 1
    ) AS TAH_CNT
INTO #DUP
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN multi m ON m.INVOICEREF = inv.LREF
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND pt.IOCODE = 0
   AND ISNULL(pt.INST_NR, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.INSTALLMENT_PLAN_REF IS NULL;

CREATE CLUSTERED INDEX CX_DUP ON #DUP (INV_LREF, PT_LREF);

;WITH ranked AS (
    SELECT
        d.*,
        ROW_NUMBER() OVER (
            PARTITION BY d.INV_LREF
            ORDER BY
                CASE WHEN d.CP = 1 THEN 1 ELSE 0 END,  /* CANCEL_REV asla KEEP */
                CASE
                    WHEN d.PT_ABYS_ID = d.INV_ABYS_ID THEN 0
                    WHEN d.PT_ABYS_ID = d.INV_LREF THEN 1
                    WHEN d.TAH_CNT > 0 THEN 2
                    ELSE 3
                END,
                d.PT_LREF
        ) AS RN
    FROM #DUP d
)
SELECT INV_LREF, PT_LREF AS KEEP_PT
INTO #KEEP
FROM ranked
WHERE RN = 1;

CREATE UNIQUE CLUSTERED INDEX CX_KEEP ON #KEEP (INV_LREF);

PRINT '========== ADAY ==========';
SELECT
    COUNT(DISTINCT INV_LREF) AS INV_CNT,
    COUNT(*) AS PT_CNT,
    CONVERT(DECIMAL(18,2), SUM(CASE WHEN k.KEEP_PT IS NULL THEN PT_P ELSE 0 END)) AS DROP_PAYABLE_SUM
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF;

PRINT '========== TOP 30 ==========';
SELECT TOP 30
    d.INV_LREF, d.INV_ABYS_ID, d.INV_P,
    d.PT_LREF, d.PT_ABYS_ID, d.PT_P, d.PT_PAID, d.CP, d.TAH_CNT,
    CASE WHEN k.KEEP_PT IS NULL THEN 'DROP' ELSE 'KEEP' END AS ACT
FROM #DUP d
LEFT JOIN #KEEP k ON k.KEEP_PT = d.PT_LREF
ORDER BY d.INV_LREF, d.PT_LREF;

IF @DryRun = 1
BEGIN
    PRINT 'DRY-RUN: UPDATE yok. Uygulamak icin @DryRun=0';
    RETURN;
END

BEGIN TRAN;

UPDATE pay
SET pay.CROSSREF = k.KEEP_PT
FROM dbo.LS_005_01_PAYTRANS pay
INNER JOIN #DUP d ON d.PT_LREF = pay.CROSSREF
INNER JOIN #KEEP k ON k.INV_LREF = d.INV_LREF
WHERE ISNULL(pay.IOCODE, 0) = 1
  AND NOT EXISTS (SELECT 1 FROM #KEEP x WHERE x.KEEP_PT = pay.CROSSREF);

PRINT 'CROSSREF retarget=' + CAST(@@ROWCOUNT AS VARCHAR(20));

UPDATE pt
SET pt.CANCELED = CAST(1 AS BIT)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #DUP d ON d.PT_LREF = pt.LREF
WHERE NOT EXISTS (SELECT 1 FROM #KEEP k WHERE k.KEEP_PT = pt.LREF);

PRINT 'SOFT-CANCEL drop PT=' + CAST(@@ROWCOUNT AS VARCHAR(20));

/* dogrulama */
SELECT COUNT(*) AS STILL_DUP_INV
FROM (
    SELECT INVOICEREF
    FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
    WHERE IOCODE = 0 AND ISNULL(INST_NR, 0) = 0 AND ISNULL(CANCELED, 0) = 0
    GROUP BY INVOICEREF
    HAVING COUNT(*) > 1
) x;

COMMIT;

/* Unique index (cleanup sonrasi) */
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'UX_MIG_PT_DEBT_INV_INST0'
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_PT_DEBT_INV_INST0
        ON dbo.LS_005_01_PAYTRANS (INVOICEREF)
        WHERE IOCODE = 0 AND INST_NR = 0 AND CANCELED = 0
          AND (CANCELLATIONPAYMENT = 0 OR CANCELLATIONPAYMENT IS NULL)
        WITH (MAXDOP = 8, SORT_IN_TEMPDB = ON);
    PRINT 'CREATE UX_MIG_PT_DEBT_INV_INST0 OK';
END

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
      AND name = N'UX_MIG_PT_DEBT_INV_INSTN'
)
BEGIN
    BEGIN TRY
        CREATE UNIQUE NONCLUSTERED INDEX UX_MIG_PT_DEBT_INV_INSTN
            ON dbo.LS_005_01_PAYTRANS (INVOICEREF, INST_NR)
            WHERE IOCODE = 0 AND INST_NR > 0 AND CANCELED = 0
              AND (CANCELLATIONPAYMENT = 0 OR CANCELLATIONPAYMENT IS NULL)
            WITH (MAXDOP = 8, SORT_IN_TEMPDB = ON);
        PRINT 'CREATE UX_MIG_PT_DEBT_INV_INSTN OK';
    END TRY
    BEGIN CATCH
        PRINT 'WARN UX_MIG_PT_DEBT_INV_INSTN: ' + ERROR_MESSAGE();
    END CATCH
END

PRINT '========== 91 DUP CLEANUP DONE ==========';
GO
