/* ============================================================
   SSMS — AGR: ABYS (O59 TTK) vs INV vs AFL + Energy IADE/IPTAL
   Grain: ACCOUNT_ID (1 satir = 1 hesap)

   INV  = SUM(borc) IOCODE=0 AND CANCELED=0
   ABYS = izgazMGR.TUKETIM_TUTAR_KONTROL (O59) / yoksa energy 93
   AFL  = LS_AFL_OPEN_DEBT.BALANCE

   IPTAL_KIND (TAM/KISMI) — birincil: LS_OV_EKS_CLASS.KIND
     TAM   : EKS_AMT ≈ TAH_AMT  | Energy'de TYPE=92 IADE (tam)
     KISMI : EKS_AMT < TAH_AMT  | Energy MAIN PAYABLE = kalan
             (TYPE=92 genelde YOK — 590 KISMI_HDR dusumu)
   !!! IADE_AMT < SUM(INV) ile KISMI UYDURMA (cok borc INV → sahte KISMI)

   Energy (#IADE96):
     IADE  : TYPE=92 | ACT=2 | EXPLAIN IADE
     IPTAL : INV.CANCELED=1 | PT.CANCELLATIONPAYMENT=1
   ============================================================
   KIND_ABYS:
     EKSILTEN (overlay/IADE) | IPTAL | MATCH | ONLY_INV | INV_GT_* | ABYS_GT_*

   Result set:
     1) ACCOUNT detay
     2) ONLY_ABYS
     3) Sozlesme ozeti (ABYS / Energy / AFL — tahakkuk + eksilten adet/tutar)
     4) FRK sayaclari (MATCH/DIFF/TAM/KISMI)
   ============================================================ */
USE energy;
GO

IF OBJECT_ID('tempdb..#EN') IS NOT NULL DROP TABLE #EN;
IF OBJECT_ID('tempdb..#EN96') IS NOT NULL DROP TABLE #EN96;
IF OBJECT_ID('tempdb..#IADE96') IS NOT NULL DROP TABLE #IADE96;
IF OBJECT_ID('tempdb..#EKS96') IS NOT NULL DROP TABLE #EKS96;
IF OBJECT_ID('tempdb..#ABYS96') IS NOT NULL DROP TABLE #ABYS96;
GO

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @Agr BIGINT = 208100;
DECLARE @Eps DECIMAL(18,2) = 0.02;
DECLARE @TtkFrom VARCHAR(20) =
    CASE
        WHEN OBJECT_ID('izgazMGR.dbo.TUKETIM_TUTAR_KONTROL', 'U') IS NOT NULL THEN 'izgazMGR'
        WHEN OBJECT_ID('energy.dbo.TUKETIM_TUTAR_KONTROL', 'U') IS NOT NULL THEN 'energy'
        ELSE NULL
    END;

IF @TtkFrom IS NULL
BEGIN
    RAISERROR('TUKETIM_TUTAR_KONTROL yok (izgazMGR O59 veya energy 93).', 16, 1);
    RETURN;
END;

PRINT N'TTK kaynak: ' + @TtkFrom;

/* ---------- Energy: IADE / IPTAL (account grain) ---------- */
CREATE TABLE #IADE96 (
    ACCOUNT_ID        BIGINT NOT NULL,
    IADE_CNT          INT NOT NULL,
    IADE_AMT          DECIMAL(18,2) NOT NULL,
    IADE_LREF         BIGINT NULL,
    IADE_TYPE         INT NULL,
    INV_CANCELED_CNT  INT NOT NULL,
    INV_CANCELED_AMT  DECIMAL(18,2) NOT NULL,
    PT_CP_CNT         INT NOT NULL,
    PT_CP_AMT         DECIMAL(18,2) NOT NULL
);

;WITH iade_inv AS (
    SELECT
        inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
        inv.LREF,
        inv.TYPE,
        CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL, 0)) AS PAY,
        CASE
            WHEN inv.TYPE = 92 THEN 1
            WHEN inv.ABYS_ACTION_TYPE_ID = 2 THEN 1
            WHEN ISNULL(inv.IOCODE, 0) = 1
             AND ISNULL(inv.TYPE, 0) <> 101
             AND (
                    UPPER(ISNULL(inv.EXPLAIN, '')) LIKE N'%IADE%'
                 OR UPPER(ISNULL(inv.EXPLAIN, '')) LIKE N'%EKSILTEN%'
             ) THEN 1
            ELSE 0
        END AS IS_IADE,
        CASE WHEN ISNULL(inv.CANCELED, 0) = 1 AND ISNULL(inv.IOCODE, 0) = 0 THEN 1 ELSE 0 END AS IS_INV_CANCEL,
        CASE WHEN ISNULL(inv.CANCELED, 0) = 1 AND ISNULL(inv.IOCODE, 0) = 0
             THEN CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL, 0)) ELSE 0 END AS CANCEL_PAY
    FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    WHERE inv.ABYS_AGREEMENT_ID = @Agr
      AND inv.ABYS_ACCOUNT_ID IS NOT NULL
),
pt_cp AS (
    SELECT
        inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
        COUNT(*) AS PT_CP_CNT,
        CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)))) AS PT_CP_AMT
    FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        ON pt.INVOICEREF = inv.LREF
    WHERE inv.ABYS_AGREEMENT_ID = @Agr
      AND inv.ABYS_ACCOUNT_ID IS NOT NULL
      AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 1
      AND ISNULL(pt.CANCELED, 0) = 0
    GROUP BY inv.ABYS_ACCOUNT_ID
)
INSERT INTO #IADE96 (
    ACCOUNT_ID, IADE_CNT, IADE_AMT, IADE_LREF, IADE_TYPE,
    INV_CANCELED_CNT, INV_CANCELED_AMT, PT_CP_CNT, PT_CP_AMT
)
SELECT
    a.ACCOUNT_ID,
    SUM(a.IS_IADE),
    CONVERT(DECIMAL(18,2), SUM(CASE WHEN a.IS_IADE = 1 THEN a.PAY ELSE 0 END)),
    MAX(CASE WHEN a.IS_IADE = 1 THEN a.LREF END),
    MAX(CASE WHEN a.IS_IADE = 1 THEN a.TYPE END),
    SUM(a.IS_INV_CANCEL),
    CONVERT(DECIMAL(18,2), SUM(a.CANCEL_PAY)),
    ISNULL(MAX(p.PT_CP_CNT), 0),
    CONVERT(DECIMAL(18,2), ISNULL(MAX(p.PT_CP_AMT), 0))
FROM iade_inv a
LEFT JOIN pt_cp p ON p.ACCOUNT_ID = a.ACCOUNT_ID
GROUP BY a.ACCOUNT_ID
HAVING SUM(a.IS_IADE) > 0
    OR SUM(a.IS_INV_CANCEL) > 0
    OR ISNULL(MAX(p.PT_CP_CNT), 0) > 0;

CREATE CLUSTERED INDEX CX_IADE96 ON #IADE96 (ACCOUNT_ID);

/* ---------- Overlay KIND (TAM/KISMI) — birincil kaynak ---------- */
CREATE TABLE #EKS96 (
    ACCOUNT_ID   BIGINT NOT NULL,
    EKS_KIND     VARCHAR(10) NULL,
    EKS_AMT      DECIMAL(18,2) NULL,
    TAH_AMT      DECIMAL(18,2) NULL,
    KALAN_AMT    DECIMAL(18,2) NULL,
    MAIN_LREF    BIGINT NULL
);

IF OBJECT_ID('izgazMGR.dbo.LS_OV_EKS_CLASS', 'U') IS NOT NULL
BEGIN
    INSERT INTO #EKS96 (ACCOUNT_ID, EKS_KIND, EKS_AMT, TAH_AMT, KALAN_AMT, MAIN_LREF)
    SELECT
        CAST(c.ACCOUNT_ID AS BIGINT),
        /* KISMI once — ayni hesapta birden fazla satir olursa */
        CASE
            WHEN SUM(CASE WHEN c.KIND = 'KISMI' THEN 1 ELSE 0 END) > 0 THEN 'KISMI'
            WHEN SUM(CASE WHEN c.KIND = 'TAM'   THEN 1 ELSE 0 END) > 0 THEN 'TAM'
            ELSE MAX(LEFT(CAST(c.KIND AS VARCHAR(10)), 10))
        END,
        CONVERT(DECIMAL(18,2), SUM(ISNULL(c.EKS_AMT, 0))),
        CONVERT(DECIMAL(18,2), MAX(ISNULL(c.TAH_AMT, 0))),
        CONVERT(DECIMAL(18,2),
            MAX(ISNULL(c.TAH_AMT, 0)) - SUM(ISNULL(c.EKS_AMT, 0))),
        MAX(CAST(c.MAIN_LREF AS BIGINT))
    FROM izgazMGR.dbo.LS_OV_EKS_CLASS c WITH (NOLOCK)
    WHERE c.AGREEMENT_ID = @Agr
      AND ISNULL(c.KIND, '') IN ('TAM', 'KISMI')
    GROUP BY CAST(c.ACCOUNT_ID AS BIGINT);
END

CREATE CLUSTERED INDEX CX_EKS96 ON #EKS96 (ACCOUNT_ID);

/* ---------- Energy: borc INV (IOCODE=0, CANCELED=0) ---------- */
CREATE TABLE #EN96 (
    ACCOUNT_ID       BIGINT NOT NULL,
    ACCRUE_TYPE_ID   INT NULL,
    ACTION_TYPE_ID   INT NULL,
    INV_CNT          INT NOT NULL,
    TAHAKKUK_TARIHI  DATE NULL,
    ALL_CLOSED       TINYINT NOT NULL,
    INV_SUM          DECIMAL(18,2) NOT NULL,
    PT_P             DECIMAL(18,2) NOT NULL,
    PT_PAID          DECIMAL(18,2) NOT NULL,
    PT_KALAN         DECIMAL(18,2) NOT NULL,
    LINE_SUM         DECIMAL(18,2) NOT NULL
);

INSERT INTO #EN96 (
    ACCOUNT_ID, ACCRUE_TYPE_ID, ACTION_TYPE_ID, INV_CNT,
    TAHAKKUK_TARIHI, ALL_CLOSED, INV_SUM,
    PT_P, PT_PAID, PT_KALAN, LINE_SUM
)
SELECT
    inv.ABYS_ACCOUNT_ID,
    MAX(CAST(inv.ABYS_ACCRUE_TYPE_ID AS INT)),
    MAX(CAST(inv.ABYS_ACTION_TYPE_ID AS INT)),
    COUNT(*),
    MIN(CAST(inv.DATE_ AS DATE)),
    CAST(MIN(CASE WHEN ISNULL(inv.CLOSED,0) = 0 THEN 0 ELSE 1 END) AS TINYINT),
    CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL,0)))),
    CONVERT(DECIMAL(18,2), SUM(ISNULL(pt.PT_PAYABLE,0))),
    CONVERT(DECIMAL(18,2), SUM(ISNULL(pt.PT_PAID,0))),
    CONVERT(DECIMAL(18,2), SUM(ISNULL(pt.PT_KALAN,0))),
    CONVERT(DECIMAL(18,2), SUM(ISNULL(ln.LINE_SUM,0)))
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
LEFT JOIN (
    SELECT
        INVOICEREF,
        SUM(CONVERT(DECIMAL(18,2), ISNULL(PAYABLETOTAL,0))) AS PT_PAYABLE,
        SUM(CONVERT(DECIMAL(18,2), ISNULL(PAID,0))) AS PT_PAID,
        SUM(CONVERT(DECIMAL(18,2), ISNULL(PAYABLETOTAL,0)))
      - SUM(CONVERT(DECIMAL(18,2), ISNULL(PAID,0))) AS PT_KALAN
    FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
    WHERE ISNULL(IOCODE,0) = 0
      AND ISNULL(CANCELED,0) = 0
      AND ISNULL(CANCELLATIONPAYMENT,0) = 0
    GROUP BY INVOICEREF
) pt ON pt.INVOICEREF = inv.LREF
LEFT JOIN (
    SELECT
        il.INVOICEREF,
        SUM(CONVERT(DECIMAL(18,2),
            ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL) * ISNULL(il.ABYS_STATUS, 1)
        )) AS LINE_SUM
    FROM dbo.LS_005_01_INVLINES il WITH (NOLOCK)
    WHERE ISNULL(il.CANCELED, 0) = 0
    GROUP BY il.INVOICEREF
) ln ON ln.INVOICEREF = inv.LREF
WHERE inv.ABYS_AGREEMENT_ID = @Agr
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.ABYS_ACCOUNT_ID IS NOT NULL
GROUP BY inv.ABYS_ACCOUNT_ID;

CREATE CLUSTERED INDEX CX_EN96 ON #EN96 (ACCOUNT_ID);

/* ---------- ABYS TTK (izgazMGR tercih, yoksa energy) ---------- */
IF OBJECT_ID('tempdb..#ABYS96') IS NOT NULL DROP TABLE #ABYS96;
CREATE TABLE #ABYS96 (
    ACCOUNT_ID       BIGINT NOT NULL,
    TOPLAM_TAHAKKUK  DECIMAL(18,2) NULL,
    ODENEN_TUTAR     DECIMAL(18,2) NULL,
    KALAN_TUTAR      DECIMAL(18,2) NULL,
    ACCRUE_TYPE_ID   INT NULL
);

IF @TtkFrom = 'izgazMGR'
    INSERT INTO #ABYS96 (ACCOUNT_ID, TOPLAM_TAHAKKUK, ODENEN_TUTAR, KALAN_TUTAR, ACCRUE_TYPE_ID)
    SELECT
        CAST(ACCOUNT_ID AS BIGINT),
        CONVERT(DECIMAL(18,2), TOPLAM_TAHAKKUK),
        CONVERT(DECIMAL(18,2), ODENEN_TUTAR),
        CONVERT(DECIMAL(18,2), KALAN_TUTAR),
        CAST(ACCRUE_TYPE_ID AS INT)
    FROM izgazMGR.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK)
    WHERE AGREEMENT_ID = @Agr;
ELSE
    INSERT INTO #ABYS96 (ACCOUNT_ID, TOPLAM_TAHAKKUK, ODENEN_TUTAR, KALAN_TUTAR, ACCRUE_TYPE_ID)
    SELECT
        CAST(ACCOUNT_ID AS BIGINT),
        CONVERT(DECIMAL(18,2), TOPLAM_TAHAKKUK),
        CONVERT(DECIMAL(18,2), ODENEN_TUTAR),
        CONVERT(DECIMAL(18,2), KALAN_TUTAR),
        CAST(ACCRUE_TYPE_ID AS INT)
    FROM energy.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK)
    WHERE AGREEMENT_ID = @Agr;

CREATE CLUSTERED INDEX CX_ABYS96 ON #ABYS96 (ACCOUNT_ID);

/* ---------- 1) ACCOUNT grain ---------- */
SELECT
    CASE
        WHEN abys.ACCOUNT_ID IS NULL
         AND iade.ACCOUNT_ID IS NULL
         AND eks.ACCOUNT_ID IS NULL
            THEN 'ONLY_INV'
        /* overlay/IADE once — KISMI'de INV zaten kalan; MATCH gizlemesin */
        WHEN eks.ACCOUNT_ID IS NOT NULL
            THEN 'EKSILTEN'
        WHEN iade.ACCOUNT_ID IS NOT NULL AND ISNULL(iade.IADE_CNT, 0) > 0
            THEN 'EKSILTEN'
        WHEN iade.ACCOUNT_ID IS NOT NULL
         AND (ISNULL(iade.INV_CANCELED_CNT, 0) > 0 OR ISNULL(iade.PT_CP_CNT, 0) > 0)
            THEN 'IPTAL'
        WHEN ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) <= @Eps
            THEN 'MATCH'
        WHEN ISNULL(abys.TOPLAM_TAHAKKUK,0) <= @Eps
         AND ABS(ISNULL(en.INV_SUM,0) - ABS(ISNULL(abys.ODENEN_TUTAR,0))) <= @Eps
         AND ABS(ISNULL(abys.ODENEN_TUTAR,0)) > @Eps
            THEN 'EKSILTEN'
        WHEN ISNULL(en.INV_SUM,0) > ISNULL(abys.TOPLAM_TAHAKKUK,0)
            THEN 'INV_GT_ABYS'
        ELSE 'ABYS_GT_INV'
    END AS KIND_ABYS,

    /* TAM/KISMI: overlay birincil; IADE sadece tek-borc TAM fallback */
    CASE
        WHEN eks.EKS_KIND IN ('TAM', 'KISMI') THEN eks.EKS_KIND
        WHEN ISNULL(iade.IADE_CNT, 0) > 0
         AND en.INV_CNT = 1
         AND ABS(ISNULL(iade.IADE_AMT, 0) - ISNULL(en.INV_SUM, 0)) <= @Eps
            THEN 'TAM'
        WHEN ISNULL(iade.INV_CANCELED_CNT, 0) > 0
         AND en.INV_CNT = 1
         AND ABS(ISNULL(iade.INV_CANCELED_AMT, 0) - ISNULL(en.INV_SUM, 0)) <= @Eps
            THEN 'TAM'
        ELSE NULL
    END AS IPTAL_KIND,

    CASE
        WHEN abys.ACCOUNT_ID IS NULL AND iade.ACCOUNT_ID IS NULL AND eks.ACCOUNT_ID IS NULL
            THEN N'TTK/EKS yok — energy INV var'
        WHEN eks.ACCOUNT_ID IS NOT NULL AND eks.EKS_KIND = 'KISMI'
            THEN N'KISMI eksilten (overlay) | EKS='
               + CONVERT(NVARCHAR(40), eks.EKS_AMT)
               + N' TAH=' + CONVERT(NVARCHAR(40), eks.TAH_AMT)
               + N' kalan=' + CONVERT(NVARCHAR(40), eks.KALAN_AMT)
               + N' | EN_INV≈kalan, TYPE92 genelde yok'
        WHEN eks.ACCOUNT_ID IS NOT NULL AND eks.EKS_KIND = 'TAM'
            THEN N'TAM eksilten (overlay) | EKS='
               + CONVERT(NVARCHAR(40), eks.EKS_AMT)
               + CASE WHEN ISNULL(iade.IADE_CNT, 0) > 0
                      THEN N' | Energy IADE LREF=' + CONVERT(NVARCHAR(40), iade.IADE_LREF)
                      ELSE N'' END
        WHEN iade.ACCOUNT_ID IS NOT NULL AND ISNULL(iade.IADE_CNT, 0) > 0
            THEN N'Energy IADE (TYPE/ACT=2) | AMT='
               + CONVERT(NVARCHAR(40), iade.IADE_AMT)
               + N' | LREF=' + CONVERT(NVARCHAR(40), iade.IADE_LREF)
        WHEN iade.ACCOUNT_ID IS NOT NULL
         AND (ISNULL(iade.INV_CANCELED_CNT, 0) > 0 OR ISNULL(iade.PT_CP_CNT, 0) > 0)
            THEN N'Energy IPTAL | INV.CANCELED='
               + CONVERT(NVARCHAR(20), iade.INV_CANCELED_CNT)
               + N' | PT.CP=' + CONVERT(NVARCHAR(20), iade.PT_CP_CNT)
        WHEN ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) <= @Eps
            THEN N'TTK.TOPLAM ≈ SUM(INV.PAYABLE)'
        WHEN ISNULL(abys.TOPLAM_TAHAKKUK,0) = 0
            THEN N'INV_SUM > TTK.TOPLAM=0 (IADE/EKS yok — incele)'
        WHEN ISNULL(en.INV_SUM,0) > ISNULL(abys.TOPLAM_TAHAKKUK,0)
            THEN N'INV_SUM > TTK (energy fazla)'
        ELSE N'TTK > INV_SUM (energy eksik)'
    END AS ACIKLAMA_ABYS,

    CASE
        WHEN afl.FATURAID IS NULL AND ISNULL(en.PT_KALAN,0) > @Eps THEN 'EN_OPEN_AFL_YOK'
        WHEN afl.FATURAID IS NULL THEN 'EN_CLOSED_AFL_YOK'
        WHEN ABS(ISNULL(en.PT_KALAN,0) - ISNULL(afl.BALANCE,0)) <= @Eps THEN 'AFL_MATCH'
        WHEN ISNULL(en.PT_KALAN,0) > ISNULL(afl.BALANCE,0) THEN 'EN_GT_AFL'
        ELSE 'AFL_GT_EN'
    END AS KIND_AFL,
    CASE
        WHEN afl.FATURAID IS NULL AND ISNULL(en.PT_KALAN,0) > @Eps
            THEN N'Energy acik kalan var, AFL yok'
        WHEN afl.FATURAID IS NULL
            THEN N'Energy kapali, AFL yok (beklenen)'
        WHEN ABS(ISNULL(en.PT_KALAN,0) - ISNULL(afl.BALANCE,0)) <= @Eps
            THEN N'Energy kalan ≈ AFL.BALANCE'
        WHEN ISNULL(en.PT_KALAN,0) > ISNULL(afl.BALANCE,0)
            THEN N'Energy kalan > AFL'
        ELSE N'AFL > Energy kalan'
    END AS ACIKLAMA_AFL,

    en.ACCOUNT_ID,
    en.ACCRUE_TYPE_ID,
    en.ACTION_TYPE_ID,
    en.INV_CNT,
    en.TAHAKKUK_TARIHI,
    en.ALL_CLOSED,
    en.INV_SUM,
    en.LINE_SUM,

    /* Energy IADE / IPTAL */
    ISNULL(iade.IADE_CNT, 0) AS IADE_CNT,
    CONVERT(DECIMAL(18,2), iade.IADE_AMT) AS IADE_AMT,
    iade.IADE_LREF,
    iade.IADE_TYPE,
    ISNULL(iade.INV_CANCELED_CNT, 0) AS INV_CANCELED_CNT,
    CONVERT(DECIMAL(18,2), iade.INV_CANCELED_AMT) AS INV_CANCELED_AMT,
    ISNULL(iade.PT_CP_CNT, 0) AS PT_CP_CNT,
    CONVERT(DECIMAL(18,2), iade.PT_CP_AMT) AS PT_CP_AMT,
    eks.EKS_KIND AS OV_EKS_KIND,
    CONVERT(DECIMAL(18,2), eks.EKS_AMT) AS OV_EKS_AMT,
    CONVERT(DECIMAL(18,2), eks.TAH_AMT) AS OV_TAH_AMT,
    CONVERT(DECIMAL(18,2), eks.KALAN_AMT) AS OV_KALAN_AMT,
    eks.MAIN_LREF AS OV_MAIN_LREF,

    CONVERT(DECIMAL(18,2), abys.TOPLAM_TAHAKKUK) AS ABYS_TAH,
    CONVERT(DECIMAL(18,2), abys.ODENEN_TUTAR) AS ABYS_ODENEN,
    CONVERT(DECIMAL(18,2), abys.KALAN_TUTAR) AS ABYS_KALAN,
    CONVERT(DECIMAL(18,2), afl.BALANCE) AS AFL_TUTAR,
    en.PT_P,
    en.PT_PAID,
    en.PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) AS DELTA_INV_ABYS,
    CONVERT(DECIMAL(18,2), ISNULL(en.INV_SUM,0) - ISNULL(iade.IADE_AMT,0)) AS DELTA_INV_IADE,
    CONVERT(DECIMAL(18,2), ISNULL(en.PT_KALAN,0) - ISNULL(afl.BALANCE,0)) AS DELTA_KALAN_AFL
FROM #EN96 en
LEFT JOIN #ABYS96 abys
    ON abys.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN #IADE96 iade
    ON iade.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN #EKS96 eks
    ON eks.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN dbo.LS_AFL_OPEN_DEBT afl WITH (NOLOCK)
    ON afl.FATURAID = en.ACCOUNT_ID
ORDER BY
    CASE
        WHEN afl.FATURAID IS NULL AND ISNULL(en.PT_KALAN,0) > @Eps THEN 0
        WHEN iade.ACCOUNT_ID IS NOT NULL OR eks.ACCOUNT_ID IS NOT NULL THEN 1
        WHEN ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) > @Eps THEN 2
        ELSE 3
    END,
    ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) DESC;

/* ---------- 2) ONLY_ABYS ---------- */
SELECT
    'ONLY_ABYS' AS KIND_ABYS,
    N'TTK var — aktif borc INV yok' AS ACIKLAMA_ABYS,
    abys.ACCOUNT_ID,
    abys.ACCRUE_TYPE_ID,
    CONVERT(DECIMAL(18,2), abys.TOPLAM_TAHAKKUK) AS ABYS_TAH,
    CONVERT(DECIMAL(18,2), abys.ODENEN_TUTAR) AS ABYS_ODENEN,
    CONVERT(DECIMAL(18,2), abys.KALAN_TUTAR) AS ABYS_KALAN,
    CONVERT(DECIMAL(18,2), afl.BALANCE) AS AFL_TUTAR
FROM #ABYS96 abys
LEFT JOIN dbo.LS_AFL_OPEN_DEBT afl WITH (NOLOCK)
    ON afl.FATURAID = abys.ACCOUNT_ID
WHERE NOT EXISTS (
        SELECT 1 FROM #EN96 en WHERE en.ACCOUNT_ID = abys.ACCOUNT_ID
      )
ORDER BY abys.ACCOUNT_ID;

/* ---------- 3) Sozlesme ozeti — ABYS / Energy / AFL ---------- */
;WITH
en_tah AS (
    SELECT
        COUNT(*) AS TAH_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(INV_SUM), 0)) AS TAH_TUTAR,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(PT_KALAN), 0)) AS KALAN_TUTAR,
        SUM(CASE WHEN PT_KALAN > @Eps THEN 1 ELSE 0 END) AS KALAN_ADET
    FROM #EN96
),
en_eks AS (
    SELECT
        COUNT(*) AS EKS_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(IADE_AMT), 0)) AS EKS_TUTAR
    FROM #IADE96
    WHERE IADE_CNT > 0
),
abys_tah AS (
    SELECT
        COUNT(*) AS TAH_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(ISNULL(TOPLAM_TAHAKKUK, 0)), 0)) AS TAH_TUTAR,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(ISNULL(KALAN_TUTAR, 0)), 0)) AS KALAN_TUTAR,
        SUM(CASE WHEN ISNULL(KALAN_TUTAR, 0) > @Eps THEN 1 ELSE 0 END) AS KALAN_ADET
    FROM #ABYS96
),
abys_eks AS (
    SELECT
        COUNT(*) AS EKS_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(ISNULL(EKS_AMT, 0)), 0)) AS EKS_TUTAR,
        SUM(CASE WHEN EKS_KIND = 'TAM' THEN 1 ELSE 0 END) AS TAM_ADET,
        SUM(CASE WHEN EKS_KIND = 'KISMI' THEN 1 ELSE 0 END) AS KISMI_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(CASE WHEN EKS_KIND = 'TAM' THEN EKS_AMT ELSE 0 END), 0)) AS TAM_TUTAR,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(CASE WHEN EKS_KIND = 'KISMI' THEN EKS_AMT ELSE 0 END), 0)) AS KISMI_TUTAR
    FROM #EKS96
),
afl_sum AS (
    SELECT
        COUNT(*) AS AFL_ADET,
        CONVERT(DECIMAL(18,2), ISNULL(SUM(ISNULL(a.BALANCE, 0)), 0)) AS AFL_TUTAR
    FROM dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    WHERE a.FATURAID IN (
            SELECT ACCOUNT_ID FROM #EN96
            UNION
            SELECT ACCOUNT_ID FROM #ABYS96
        )
)
SELECT
    @Agr AS AGREEMENT_ID,
    v.KAYNAK,
    v.TAH_ADET,
    v.TAH_TUTAR,
    v.EKS_ADET,
    v.EKS_TUTAR,
    v.TAM_ADET,
    v.TAM_TUTAR,
    v.KISMI_ADET,
    v.KISMI_TUTAR,
    v.KALAN_ADET,
    v.KALAN_TUTAR,
    v.NOTLAR
FROM (
    SELECT
        CAST('Energy' AS VARCHAR(10)) AS KAYNAK,
        et.TAH_ADET,
        et.TAH_TUTAR,
        ISNULL(ee.EKS_ADET, 0) AS EKS_ADET,
        ISNULL(ee.EKS_TUTAR, 0) AS EKS_TUTAR,
        CAST(NULL AS INT) AS TAM_ADET,
        CAST(NULL AS DECIMAL(18,2)) AS TAM_TUTAR,
        CAST(NULL AS INT) AS KISMI_ADET,
        CAST(NULL AS DECIMAL(18,2)) AS KISMI_TUTAR,
        et.KALAN_ADET,
        et.KALAN_TUTAR,
        CAST(N'Borc INV (IOCODE=0) | EKS=TYPE92/ACT2 IADE | KALAN=PT' AS NVARCHAR(120)) AS NOTLAR
    FROM en_tah et
    CROSS JOIN en_eks ee

    UNION ALL
    SELECT
        'ABYS',
        at.TAH_ADET,
        at.TAH_TUTAR,
        ISNULL(ae.EKS_ADET, 0),
        ISNULL(ae.EKS_TUTAR, 0),
        ISNULL(ae.TAM_ADET, 0),
        ISNULL(ae.TAM_TUTAR, 0),
        ISNULL(ae.KISMI_ADET, 0),
        ISNULL(ae.KISMI_TUTAR, 0),
        at.KALAN_ADET,
        at.KALAN_TUTAR,
        CAST(N'TTK tahakkuk | EKS=OV_EKS_CLASS TAM/KISMI | KALAN=TTK.KALAN' AS NVARCHAR(120))
    FROM abys_tah at
    CROSS JOIN abys_eks ae

    UNION ALL
    SELECT
        'AFL',
        CAST(NULL AS INT),
        CAST(NULL AS DECIMAL(18,2)),
        CAST(NULL AS INT),
        CAST(NULL AS DECIMAL(18,2)),
        CAST(NULL AS INT),
        CAST(NULL AS DECIMAL(18,2)),
        CAST(NULL AS INT),
        CAST(NULL AS DECIMAL(18,2)),
        afl.AFL_ADET,
        afl.AFL_TUTAR,
        CAST(N'Acik borc master (FATURAID=ACCOUNT) — tahakkuk/eksilten yok' AS NVARCHAR(120))
    FROM afl_sum afl
) v
ORDER BY CASE v.KAYNAK WHEN 'ABYS' THEN 1 WHEN 'Energy' THEN 2 WHEN 'AFL' THEN 3 END;

/* ---------- 4) FRK sayaclari ---------- */
SELECT
    @Agr AS AGREEMENT_ID,
    @TtkFrom AS TTK_SOURCE,
    COUNT(*) AS ACC_CNT,
    SUM(en.INV_CNT) AS INV_CNT,
    CONVERT(DECIMAL(18,2), SUM(en.INV_SUM)) AS EN_TAH_TUTAR,
    CONVERT(DECIMAL(18,2), SUM(ISNULL(abys.TOPLAM_TAHAKKUK,0))) AS ABYS_TAH_TUTAR,
    CONVERT(DECIMAL(18,2),
        SUM(en.INV_SUM) - SUM(ISNULL(abys.TOPLAM_TAHAKKUK,0))
    ) AS DELTA_TAH,
    CONVERT(DECIMAL(18,2), SUM(ISNULL(iade.IADE_AMT,0))) AS EN_IADE_TUTAR,
    CONVERT(DECIMAL(18,2), SUM(ISNULL(eks.EKS_AMT,0))) AS OV_EKS_TUTAR,
    SUM(CASE
            WHEN eks.ACCOUNT_ID IS NOT NULL OR ISNULL(iade.IADE_CNT,0) > 0 THEN 1
            ELSE 0
        END) AS EKSILTEN_CNT,
    SUM(CASE WHEN eks.EKS_KIND = 'TAM' THEN 1 ELSE 0 END) AS TAM_CNT,
    SUM(CASE WHEN eks.EKS_KIND = 'KISMI' THEN 1 ELSE 0 END) AS KISMI_CNT,
    SUM(CASE
            WHEN eks.ACCOUNT_ID IS NOT NULL OR ISNULL(iade.IADE_CNT,0) > 0 THEN 0
            WHEN ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) <= @Eps THEN 1
            ELSE 0
        END) AS TAH_MATCH_CNT,
    SUM(CASE
            WHEN eks.ACCOUNT_ID IS NOT NULL OR ISNULL(iade.IADE_CNT,0) > 0 THEN 0
            WHEN ABS(ISNULL(en.INV_SUM,0) - ISNULL(abys.TOPLAM_TAHAKKUK,0)) <= @Eps THEN 0
            ELSE 1
        END) AS TAH_DIFF_CNT,
    CONVERT(DECIMAL(18,2), SUM(en.PT_KALAN)) AS EN_KALAN,
    CONVERT(DECIMAL(18,2), SUM(ISNULL(afl.BALANCE,0))) AS AFL_KALAN,
    CONVERT(DECIMAL(18,2),
        SUM(en.PT_KALAN) - SUM(ISNULL(afl.BALANCE,0))
    ) AS DELTA_KALAN
FROM #EN96 en
LEFT JOIN #ABYS96 abys
    ON abys.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN #IADE96 iade
    ON iade.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN #EKS96 eks
    ON eks.ACCOUNT_ID = en.ACCOUNT_ID
LEFT JOIN dbo.LS_AFL_OPEN_DEBT afl WITH (NOLOCK)
    ON afl.FATURAID = en.ACCOUNT_ID;
GO
 