/* ============================================================
   FILE : hotfix/03_backfill_iade_invlines.sql
   Amac : TYPE=92 IADE faturalarin eksik INVLINES backfill

   KOK NEDEN:
     UX_LS005_INVLINES_ABYS_ID (ABYS_ID unique)
     OV.ABYS_INCOME_ROW_ID = MAIN satir ABYS_ID → 590 filtresi ~556K satir ATLADI
     Energy'de ~20 IADE satir kaldi; fatura basligi 141595 OK

   COZUM:
     ABYS_ID = IADE satirin kendi LREF (2110…) — unique
     LREF NOT EXISTS resume; CLEAN YOK

   Calistir: PG-098 local / SSMS energy
   @DRY_RUN=1 once say, sonra 0
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @DRY_RUN BIT = 1;   -- <<< once 1, sonra 0
DECLARE @Msg NVARCHAR(400);
DECLARE @N INT, @Missing INT;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121)
    + ' | 03_iade_il DRY_RUN=' + CAST(@DRY_RUN AS VARCHAR(1));

IF OBJECT_ID('izgazMGR.dbo.LS_OV_IADE_INVLINES', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.dbo.LS_OV_IADE_INVLINES yok', 16, 1);
    RETURN;
END

/* ---- aday: OV var, energy LREF yok ---- */
IF OBJECT_ID('tempdb..#IADE_IL') IS NOT NULL DROP TABLE #IADE_IL;

SELECT
    CAST(s.LREF AS INT) AS LREF,
    CAST(s.INVOICEREF AS INT) AS INVOICEREF,
    CAST(s.CLIENTREF AS INT) AS CLIENTREF,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.DATE_ AS DATETIME2)) AS DATE_,
    CAST(s.[TYPE] AS TINYINT) AS [TYPE],
    CAST(s.LINENR AS SMALLINT) AS LINENR,
    CAST(s.TRANSTYPE AS INT) AS TRANSTYPE,
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), s.AMOUNT)) AS AMOUNT,
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), s.TLTOTAL)) AS TLTOTAL,
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), s.TAX)) AS TAX,
    CONVERT(FLOAT, CONVERT(DECIMAL(18,2), s.GRANDTOTAL)) AS GRANDTOTAL,
    LEFT(N'IADE ' + ISNULL(ml.LINEEXP, ISNULL(s.LINEEXP, CAST(s.TRANSTYPE AS NVARCHAR(20)))), 100) AS LINEEXP,
    /* UNIQUE: LREF (2110…) — MAIN ABYS_INCOME_ROW_ID KULLANMA */
    CAST(s.LREF AS BIGINT) AS ABYS_ID,
    s.ABYS_AGREEMENT_ID
INTO #IADE_IL
FROM izgazMGR.dbo.LS_OV_IADE_INVLINES s WITH (NOLOCK)
LEFT JOIN energy.dbo.LS_005_01_INVLINES ml WITH (NOLOCK)
    ON ml.LREF = TRY_CAST(COALESCE(s.ABYS_SOURCE_LINE_LREF, s.ABYS_INCOME_ROW_ID) AS INT)
WHERE s.LREF BETWEEN 1 AND 2147483647
  AND NOT EXISTS (
        SELECT 1 FROM energy.dbo.LS_005_01_INVLINES t WITH (NOLOCK)
        WHERE t.LREF = CAST(s.LREF AS INT)
      )
  /* hedef IADE faturasi energy'de olmali */
  AND EXISTS (
        SELECT 1 FROM energy.dbo.LS_005_01_INVOICE i WITH (NOLOCK)
        WHERE i.LREF = CAST(s.INVOICEREF AS INT)
          AND i.[TYPE] = 92
      )
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_IADE_IL ON #IADE_IL (LREF);

SET @Missing = (SELECT COUNT(*) FROM #IADE_IL);
SET @Msg = N'IADE IL missing (backfill aday)=' + CAST(@Missing AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT TOP 10 LREF, INVOICEREF, ABYS_ID, CONVERT(DECIMAL(18,2), GRANDTOTAL) AS GRANDTOTAL, LINEEXP
FROM #IADE_IL
ORDER BY LREF;

IF @DRY_RUN = 1
BEGIN
    RAISERROR('DRY_RUN=1 — INSERT yapilmadi. @DRY_RUN=0 ile tekrar.', 0, 1) WITH NOWAIT;
END
ELSE IF @Missing > 0
BEGIN
    SET IDENTITY_INSERT energy.dbo.LS_005_01_INVLINES ON;

    INSERT INTO energy.dbo.LS_005_01_INVLINES WITH (TABLOCK) (
        LREF, INVOICEREF, CLIENTREF, DATE_, [TYPE], LINENR, TRANSTYPE,
        AMOUNT, TLTOTAL, TAX, GRANDTOTAL, LINEEXP,
        ABYS_ID, ABYS_AGREEMENT_ID
    )
    SELECT
        LREF, INVOICEREF, CLIENTREF, DATE_, [TYPE], LINENR, TRANSTYPE,
        AMOUNT, TLTOTAL, TAX, GRANDTOTAL, LINEEXP,
        ABYS_ID, ABYS_AGREEMENT_ID
    FROM #IADE_IL
    OPTION (RECOMPILE, MAXDOP 24);

    SET @N = @@ROWCOUNT;
    SET IDENTITY_INSERT energy.dbo.LS_005_01_INVLINES OFF;

    SET @Msg = N'IADE INVLINES inserted=' + CAST(@N AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
END

/* ---- dogrulama ---- */
SELECT
    (SELECT COUNT_BIG(*) FROM izgazMGR.dbo.LS_OV_IADE_INVLINES WITH (NOLOCK)) AS OV_IADE_IL,
    (
        SELECT COUNT_BIG(*)
        FROM energy.dbo.LS_005_01_INVLINES l WITH (NOLOCK)
        INNER JOIN energy.dbo.LS_005_01_INVOICE i WITH (NOLOCK)
            ON i.LREF = l.INVOICEREF
        WHERE i.[TYPE] = 92 AND i.ABYS_ID IS NOT NULL
    ) AS EN_IADE_IL,
    (
        SELECT COUNT_BIG(*)
        FROM izgazMGR.dbo.LS_OV_IADE_INVLINES s WITH (NOLOCK)
        WHERE NOT EXISTS (
            SELECT 1 FROM energy.dbo.LS_005_01_INVLINES e WITH (NOLOCK)
            WHERE e.LREF = CAST(s.LREF AS INT)
        )
    ) AS STILL_MISSING_BY_LREF;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + ' | 03_iade_il bitti';
GO
