/* ============================================================
   SCRIPT_ID : AGR_BNK_MUTABAKAT_CHECK
   SCRIPT_NO : 367
   FILE      : 367_AGR_BNK_MUTABAKAT__check.sql
   VERSION   : 4
   ============================================================ */
-- Manuel kontrol sorgulari (deploy disi)
USE energy;
GO

DECLARE @FirmaId INT = 5;

-- Kaynak vs ABYS hedef sayim (yalnizca FIRMA_ID=@FirmaId)
SELECT
    (SELECT SUM(p.rows)
     FROM izgazMGR.sys.partitions p
     INNER JOIN izgazMGR.sys.tables t ON t.object_id = p.object_id
     INNER JOIN izgazMGR.sys.schemas s ON s.schema_id = t.schema_id
     WHERE s.name = 'dbo' AND t.name = 'LS_BANK_CONFIRM' AND p.index_id IN (0, 1)
    ) AS SRC_APPROX,
    (SELECT COUNT_BIG(*)
     FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
     WHERE ABYS_ID IS NOT NULL AND FIRMA_ID = @FirmaId) AS TGT_ABYS_FIRMA,
    (SELECT COUNT_BIG(*)
     FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
     WHERE FIRMA_ID IS NULL OR FIRMA_ID <> @FirmaId) AS TGT_DIGER_FIRMA_KORUNAN,
    (SELECT COUNT_BIG(*)
     FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
     WHERE ABYS_ID IS NULL AND FIRMA_ID = @FirmaId) AS TGT_NATIVE_FIRMA;

-- FIRMA_ID dogrulama (ABYS satirlari 5 olmali)
SELECT 'ABYS FIRMA_ID <> 5', COUNT(*)
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
WHERE ABYS_ID IS NOT NULL
  AND (FIRMA_ID IS NULL OR FIRMA_ID <> @FirmaId);

-- PRE: kaynak BANK_ID resolve edilemeyen
SELECT 'PRE orphan BANK_ID', COUNT(*)
FROM izgazMGR.dbo.LS_BANK_CONFIRM s
WHERE s.ID BETWEEN 1 AND 2147483647
  AND s.BANK_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM energy.dbo.LS_BANK b WHERE b.ABYS_ID = CAST(s.BANK_ID AS INT)
  );

SELECT 'PRE null BANK_ID', COUNT(*)
FROM izgazMGR.dbo.LS_BANK_CONFIRM s
WHERE s.ID BETWEEN 1 AND 2147483647
  AND s.BANK_ID IS NULL;

-- POST: BANK_REF null / LS_BANK'te yok
SELECT 'POST BANK_REF NULL', COUNT(*)
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
WHERE ABYS_ID IS NOT NULL AND FIRMA_ID = @FirmaId AND BANK_REF IS NULL;

SELECT 'POST BANK_REF orphan (LS_BANK yok)', COUNT(*)
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY t
WHERE t.ABYS_ID IS NOT NULL
  AND t.FIRMA_ID = @FirmaId
  AND t.BANK_REF IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LS_BANK b WHERE b.LREF = t.BANK_REF);

-- BANK_REF ↔ ABYS_BANK_ID tutarliligi
SELECT 'BANK_REF <> LS_BANK.LREF(ABYS_BANK_ID)', COUNT(*)
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY t
INNER JOIN energy.dbo.LS_BANK b ON b.ABYS_ID = t.ABYS_BANK_ID
WHERE t.ABYS_ID IS NOT NULL
  AND t.FIRMA_ID = @FirmaId
  AND t.BANK_REF <> b.LREF;

-- Mutabakat durumu dagilimi (PCMS: 1=Basarili, 0=Basarisiz, 3=Kayit Yok)
SELECT MUTABAKAT_DURUMU, ABYS_APPROVAL_STATUS, COUNT(*) AS CNT
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
WHERE ABYS_ID IS NOT NULL AND FIRMA_ID = @FirmaId
GROUP BY MUTABAKAT_DURUMU, ABYS_APPROVAL_STATUS
ORDER BY MUTABAKAT_DURUMU, ABYS_APPROVAL_STATUS;

-- Tip dagilimi (ABYS_TYPE: 1=PAYMENT; 2=REFUND)
SELECT ABYS_TYPE, COUNT(*) AS CNT
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY
WHERE ABYS_ID IS NOT NULL AND FIRMA_ID = @FirmaId
GROUP BY ABYS_TYPE
ORDER BY ABYS_TYPE;

-- Eksik kaynak (FIRMA_ID=@FirmaId)
SELECT COUNT(*) AS MISSING_IN_TARGET
FROM izgazMGR.dbo.LS_BANK_CONFIRM s
WHERE s.ID BETWEEN 1 AND 2147483647
  AND NOT EXISTS (
      SELECT 1
      FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY t
      WHERE t.ABYS_ID = CAST(s.ID AS INT)
        AND t.FIRMA_ID = @FirmaId
  );

-- Ornek (FIRMA_ID=@FirmaId ABYS)
SELECT TOP 20
    t.ID, t.ABYS_ID, t.FIRMA_ID, t.BANK_REF, t.ABYS_BANK_ID, b.LREF AS LS_BANK_LREF,
    t.MUTABAKAT_TARIHI, t.MUTABAKAT_DURUMU, t.ABYS_TYPE,
    t.TAHSILAT_ADET, t.TAHSILAT_TUTAR, t.IPTAL_ADET, t.IPTAL_TUTAR,
    t.AUTO_PAYMENT_COUNT, t.AUTO_PAYMENT_AMOUNT,
    t.SYS_TAHSILAT_ADET, t.SYS_TAHSILAT_TUTAR, t.SYS_IPTAL_ADET, t.SYS_IPTAL_TUTAR,
    t.TRAN_CODE, t.CREATED, t.CREATED_TIMESTAMP
FROM energy.dbo.LS_BNK_MUTABAKAT_DETAY t
LEFT JOIN energy.dbo.LS_BANK b ON b.LREF = t.BANK_REF
WHERE t.ABYS_ID IS NOT NULL
  AND t.FIRMA_ID = @FirmaId
ORDER BY t.ABYS_ID;
GO

-- Gate (manuel):
-- EXEC energy.dbo.SP_MIG_BNK_MUTABAKAT_VALIDATE_BANK_LREF @FirmaId=5, @RaiseOnMissing=0, @Phase='BOTH';
