/* ============================================================
   SCRIPT_ID : LEGAL_LP_CHECK
   SCRIPT_NO : 603
   FILE      : 603_LEGAL_LP__check.sql
   VERSION   : 1
   ============================================================ */
USE energy;
GO

-- Kaynak / hedef satir sayilari
SELECT 'izgazMGR.LP_EXPENSE_CAUSE_PRM' AS TABLO, COUNT(*) AS SATIR FROM izgazMGR.dbo.LP_EXPENSE_CAUSE_PRM
UNION ALL SELECT 'energy.LP_EXPENSE_CAUSE_PRM (ABYS)', COUNT(*) FROM energy.dbo.LP_EXPENSE_CAUSE_PRM WHERE ABYS_ID IS NOT NULL
UNION ALL SELECT 'izgazMGR.LP_LEGAL_PROCEEDING', COUNT(*) FROM izgazMGR.dbo.LP_LEGAL_PROCEEDING
UNION ALL SELECT 'energy.LP_LEGAL_PROCEEDING (ABYS)', COUNT(*) FROM energy.dbo.LP_LEGAL_PROCEEDING WHERE ABYS_ID IS NOT NULL
UNION ALL SELECT 'izgazMGR.LP_STATUS', COUNT(*) FROM izgazMGR.dbo.LP_STATUS
UNION ALL SELECT 'energy.LP_STATUS (ABYS)', COUNT(*) FROM energy.dbo.LP_STATUS WHERE ABYS_ID IS NOT NULL
UNION ALL SELECT 'izgazMGR.LP_ACCOUNT', COUNT(*) FROM izgazMGR.dbo.LP_ACCOUNT
UNION ALL SELECT 'energy.LP_INVOICE (ABYS)', COUNT(*) FROM energy.dbo.LP_INVOICE WHERE ABYS_ID IS NOT NULL
UNION ALL SELECT 'izgazMGR.LP_INCOME', COUNT(*) FROM izgazMGR.dbo.LP_INCOME
UNION ALL SELECT 'energy.LP_INCOME (ABYS)', COUNT(*) FROM energy.dbo.LP_INCOME WHERE ABYS_ID IS NOT NULL;
GO

-- REGION kontrolu
SELECT COUNT(*) AS REGION_4102_DISI
FROM energy.dbo.LP_LEGAL_PROCEEDING
WHERE ABYS_ID IS NOT NULL AND REGION <> 4102;
GO

SELECT COUNT(*) AS REGION_4102_DISI
FROM energy.dbo.LP_INVOICE
WHERE ABYS_ID IS NOT NULL AND REGION <> 4102;
GO

-- AGREEMENT_ID placeholder
SELECT COUNT(*) AS AGREEMENT_ID_SIFIR
FROM energy.dbo.LP_LEGAL_PROCEEDING
WHERE ABYS_ID IS NOT NULL AND AGREEMENT_ID = 0;
GO

-- Orphan FK kontrolleri
SELECT COUNT(*) AS ESLESMEYEN_LP_STATUS
FROM energy.dbo.LP_STATUS s
WHERE s.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = s.LEGAL_PROCEEDING_ID);
GO

SELECT COUNT(*) AS ESLESMEYEN_LP_INVOICE
FROM energy.dbo.LP_INVOICE i
WHERE i.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = i.LEGAL_PROCEEDING_ID);
GO

SELECT COUNT(*) AS ESLESMEYEN_LP_INCOME_LP
FROM energy.dbo.LP_INCOME i
WHERE i.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = i.LEGAL_PROCEEDING_ID);
GO

SELECT COUNT(*) AS ESLESMEYEN_LP_INCOME_EXPENSE
FROM energy.dbo.LP_INCOME i
WHERE i.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_EXPENSE_CAUSE_PRM e WHERE e.ID = i.EXPENSE_CAUSE_ID);
GO

-- Son hata loglari
SELECT TOP 20 l.MIGRATION_CODE, l.BATCH_NO, l.BRIDGE_FROM, l.BRIDGE_TO, l.ERROR_MSG, l.LOGGED_AT
FROM energy.dbo.MIG_BATCH_LOG l
WHERE l.MIGRATION_CODE IN ('LP_EXPENSE_CAUSE_PRM','LP_LEGAL_PROCEEDING','LP_STATUS','LP_INVOICE','LP_INCOME')
ORDER BY l.LOGGED_AT DESC;
GO

-- Ornek calistirma:
-- EXEC energy.dbo.SP_MIGRATE_LP @HARD_RESET = 1, @REGION_ID = 4102, @BATCH_SIZE = 5000, @DEBUG = 1;
-- :r .\29_lp_restore_relationships.sql

