/* ============================================================
   SCRIPT_ID : INSTALLMENT_TYPE_MIGRATE
   SCRIPT_NO : 614
   FILE      : 614_INSTALLMENT_TYPE__migrate.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- SP_MIGRATE_LS_INSTALLMENT_TYPE
-- Kaynak  : izgazMGR.dbo.CS_INSTALLMENT_TYPE_PRM
--           + CS_INSTALLMENT_TYPE_PRM_LNG (LANG_ID=1)
-- Hedef   : energy.dbo.LS_INSTALLMENT_TYPE
-- ABYS_ID : kaynak ID
-- Native satirlar (ABYS_ID NULL) korunur.
-- ============================================================
USE energy;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.SP_MIG_INSTALLMENT_TYPE_HARD_RESET
    @DEBUG BIT = 0
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM energy.dbo.LS_INSTALLMENT_TYPE WHERE ABYS_ID IS NOT NULL;

    DECLARE @MaxLref INT = ISNULL((SELECT MAX(LREF) FROM energy.dbo.LS_INSTALLMENT_TYPE), 0);
    DBCC CHECKIDENT('energy.dbo.LS_INSTALLMENT_TYPE', RESEED, @MaxLref) WITH NO_INFOMSGS;

    IF @DEBUG = 1
        RAISERROR('HARD RESET LS_INSTALLMENT_TYPE ABYS tamamlandi. CHECKIDENT=%d', 0, 1, @MaxLref) WITH NOWAIT;
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_MIGRATE_LS_INSTALLMENT_TYPE
    @HARD_RESET BIT = 0,
    @DEBUG      BIT = 0
AS
BEGIN
    SET NOCOUNT ON;

    EXEC dbo.SP_MIG_INSTALLMENT_TYPE_VALIDATE_ALL @RaiseOnMissing = 1;

    IF @HARD_RESET = 1
        EXEC dbo.SP_MIG_INSTALLMENT_TYPE_HARD_RESET @DEBUG = @DEBUG;

    INSERT INTO energy.dbo.LS_INSTALLMENT_TYPE (
        CODE, DEFN, ISACTIVE, BEGIN_DATE, END_DATE,
        ACCRUE_TYPE_ID, SUBSCRIBER_TYPE,
        MAX_INSTALLMENT_COUNT, MAX_INSTALLMENT_AMOUNT,
        MIN_INSTALLMENT_COUNT, MIN_INSTALLMENT_AMOUNT,
        COMMISSION_DELAY_TYPE_ID, COMMISSION_DELAY_RATE,
        IS_PARTIALLY_PAYMENT, IS_STAMP_TAX, FIRST_INSTALLMENT_DEBT_RATE,
        INSTALLMENT_VIOLATED_COUNT, INSTALLMENT_VIOLATED_RUN_DAY, INSTALLMENT_VIOLATED_AMOUNT,
        WILL_CANCEL, NEED_TO_APPROVE, FIRST_INSTALLMENT_DATE, INSTALLMENT_PERIOD, CAN_PAY_ONLINE,
        ADDUSER, ADDDATE, UPDUSER, UPDDATE,
        ABYS_ID, ABYS_CORPORATION_ID, ABYS_TYPE,
        ABYS_COMMISSION_DELAY_TYPE_ID, ABYS_START_COMMISSION_DELAY_TYPE_ID, ABYS_AFTER_COMMISSION_DELAY_TYPE_ID,
        ABYS_IS_APPLICATION_REQUIRED, ABYS_LAST_EXPIRY_DATE, ABYS_FIRST_INSTALLMENT_EXPIRY_DATE,
        ABYS_IS_PENALTY_ACCRUE_ONE_FACTOR, ABYS_REPORT_TYPE,
        ABYS_INSTALLMENT_VIOLATED_PROCESS, ABYS_INSTALLMENT_VIOLATED_CONTROL,
        ABYS_VIOLATED_CANCEL_CAUSE_ID, ABYS_DO_OVERDUE_DEBTS_ACCRUE, ABYS_VIOLATED_IS_LEGAL_INFO_TYPE,
        ABYS_DO_ONLINE_INSTALLMENT, ABYS_DO_SELECTED_ALL_ACCRUE_ONLINE, ABYS_CANCELLATION_INSTALLMENT_COUNT,
        ABYS_LATE_CHARGE_INCOME_ID, ABYS_ACCRUED_INCOME_ID, ABYS_IS_LATE_CHARGE_FIXED,
        ABYS_VERSION, ABYS_CREATED_USER_ID, ABYS_UPDATED_USER_ID
    )
    SELECT
        LEFT(s.CODE, 100),
        LEFT(ISNULL(lng.VALUE, s.CODE), 250),
        CAST(s.IS_ACTIVE AS INT),
        CASE
            WHEN s.START_DATE IS NULL THEN NULL
            WHEN CAST(s.START_DATE AS DATETIME2) < CAST('17530101' AS DATETIME2) THEN NULL
            ELSE CAST(s.START_DATE AS DATETIME)
        END,
        CASE
            WHEN s.FINISH_DATE IS NULL THEN NULL
            WHEN CAST(s.FINISH_DATE AS DATETIME2) < CAST('17530101' AS DATETIME2) THEN NULL
            ELSE CAST(s.FINISH_DATE AS DATETIME)
        END,
        CAST(s.TYPE AS NVARCHAR(50)),   -- InstallmentTypeEnm
        NULL,                           -- SUBSCRIBER_TYPE
        NULL,                           -- MAX_INSTALLMENT_COUNT
        NULL,                           -- MAX_INSTALLMENT_AMOUNT
        NULL,                           -- MIN_INSTALLMENT_COUNT
        CAST(s.MIN_INSTALLMENT_AMOUNT AS FLOAT),
        CAST(s.COMMISSION_DELAY_TYPE_ID AS NVARCHAR(50)),
        NULL,                           -- COMMISSION_DELAY_RATE
        CAST(s.IS_PARTIALLY_PAYMENT AS INT),
        CAST(s.IS_STAMP_TAX AS INT),
        CAST(s.FIRST_INSTALLMENT_DEBT_RATE AS FLOAT),
        CAST(s.INSTALLMENT_VIOLATED_COUNT AS INT),
        CAST(s.INSTALLMENT_VIOLATED_RUN_DAY AS INT),
        NULL,                           -- INSTALLMENT_VIOLATED_AMOUNT
        CASE WHEN s.INSTALLMENT_VIOLATED_PROCESS = 1 THEN 1 ELSE 0 END,  -- WILL_CANCEL
        CAST(s.VERIFICATION_ACTIVE AS INT),
        NULL,                           -- FIRST_INSTALLMENT_DATE
        CAST(s.MOUNTLY_PERIOD AS INT),  -- INSTALLMENT_PERIOD
        CAST(s.DO_ONLINE_PAYMENT AS INT),
        CASE WHEN s.CREATED_USER_ID IS NULL THEN NULL ELSE CAST(s.CREATED_USER_ID AS INT) + 10000 END,
        CASE
            WHEN s.CREATED_TIMESTAMP IS NULL THEN CAST('19000101' AS DATETIME)
            WHEN CAST(s.CREATED_TIMESTAMP AS DATETIME2) < CAST('17530101' AS DATETIME2) THEN CAST('19000101' AS DATETIME)
            ELSE CAST(s.CREATED_TIMESTAMP AS DATETIME)
        END,
        CASE WHEN s.UPDATED_USER_ID IS NULL THEN NULL ELSE CAST(s.UPDATED_USER_ID AS INT) + 10000 END,
        CASE
            WHEN s.UPDATED_TIMESTAMP IS NULL THEN NULL
            WHEN CAST(s.UPDATED_TIMESTAMP AS DATETIME2) < CAST('17530101' AS DATETIME2) THEN NULL
            ELSE CAST(s.UPDATED_TIMESTAMP AS DATETIME)
        END,
        CAST(s.ID AS BIGINT),
        CAST(s.CORPORATION_ID AS INT),
        CAST(s.TYPE AS SMALLINT),
        CAST(s.COMMISSION_DELAY_TYPE_ID AS INT),
        CAST(s.START_COMMISSION_DELAY_TYPE_ID AS INT),
        CAST(s.AFTER_COMMISSION_DELAY_TYPE_ID AS INT),
        CAST(s.IS_APPLICATION_REQUIRED AS SMALLINT),
        CASE WHEN s.LAST_EXPIRY_DATE IS NULL THEN NULL ELSE CAST(s.LAST_EXPIRY_DATE AS DATETIME) END,
        CASE WHEN s.FIRST_INSTALLMENT_EXPIRY_DATE IS NULL THEN NULL ELSE CAST(s.FIRST_INSTALLMENT_EXPIRY_DATE AS DATETIME) END,
        CAST(s.IS_PENALTY_ACCRUE_ONE_FACTOR AS SMALLINT),
        CAST(s.REPORT_TYPE AS SMALLINT),
        CAST(s.INSTALLMENT_VIOLATED_PROCESS AS SMALLINT),
        CAST(s.INSTALLMENT_VIOLATED_CONTROL AS SMALLINT),
        CAST(s.VIOLATED_CANCEL_CAUSE_ID AS BIGINT),
        CAST(s.DO_OVERDUE_DEBTS_ACCRUE AS SMALLINT),
        CAST(s.VIOLATED_IS_LEGAL_INFO_TYPE AS SMALLINT),
        CAST(s.DO_ONLINE_INSTALLMENT AS SMALLINT),
        CAST(s.DO_SELECTED_ALL_ACCRUE_ONLINE AS SMALLINT),
        CAST(s.CANCELLATION_INSTALLMENT_COUNT AS SMALLINT),
        CAST(s.LATE_CHARGE_INCOME_ID AS BIGINT),
        CAST(s.ACCRUED_INCOME_ID AS BIGINT),
        CAST(s.IS_LATE_CHARGE_FIXED AS BIGINT),
        CAST(s.VERSION AS BIGINT),
        CAST(s.CREATED_USER_ID AS BIGINT),
        CAST(s.UPDATED_USER_ID AS BIGINT)
    FROM izgazMGR.dbo.CS_INSTALLMENT_TYPE_PRM s
    LEFT JOIN izgazMGR.dbo.CS_INSTALLMENT_TYPE_PRM_LNG lng
        ON lng.PRM_ID = s.ID AND lng.LANG_ID = 1
    WHERE s.ID BETWEEN 1 AND 2147483647
      AND NOT EXISTS (
          SELECT 1 FROM energy.dbo.LS_INSTALLMENT_TYPE t
          WHERE t.ABYS_ID = CAST(s.ID AS BIGINT)
      );

    DECLARE @Inserted INT = @@ROWCOUNT;

    IF @DEBUG = 1
    BEGIN
        DECLARE @Src INT, @Tgt INT, @Native INT;
        SELECT @Src = COUNT(*) FROM izgazMGR.dbo.CS_INSTALLMENT_TYPE_PRM;
        SELECT @Tgt = COUNT(*) FROM energy.dbo.LS_INSTALLMENT_TYPE WHERE ABYS_ID IS NOT NULL;
        SELECT @Native = COUNT(*) FROM energy.dbo.LS_INSTALLMENT_TYPE WHERE ABYS_ID IS NULL;
        RAISERROR('INSTALLMENT_TYPE insert=%d | src=%d tgt_abys=%d native=%d', 0, 1, @Inserted, @Src, @Tgt, @Native) WITH NOWAIT;
    END

    SELECT
        @Inserted AS INSERTED,
        (SELECT COUNT(*) FROM izgazMGR.dbo.CS_INSTALLMENT_TYPE_PRM) AS SRC,
        (SELECT COUNT(*) FROM energy.dbo.LS_INSTALLMENT_TYPE WHERE ABYS_ID IS NOT NULL) AS TGT_ABYS,
        (SELECT COUNT(*) FROM energy.dbo.LS_INSTALLMENT_TYPE WHERE ABYS_ID IS NULL) AS TGT_NATIVE;
END
GO

-- EXEC energy.dbo.SP_MIGRATE_LS_INSTALLMENT_TYPE @HARD_RESET = 0, @DEBUG = 1;
GO
