SELECT COUNT(*) ALLOC FROM MIGRATION.LS_OV_PAY_ALLOC;
SELECT COUNT(*) PAY_PT FROM MIGRATION.LS_OV_PAY_PT;
SELECT COUNT(*) MULTI FROM (SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*)>1);
SELECT * FROM MIGRATION.LS_OV_PAY_ALLOC WHERE MAIN_LREF=20811205;
