USE energy;
SET NOCOUNT ON;
DECLARE @Agr TABLE (ORD INT IDENTITY(1,1) PRIMARY KEY, AGR_ID BIGINT NOT NULL);
INSERT INTO @Agr (AGR_ID) VALUES (276503),(556305),(197168),(5727),(2221),(978259),(1192595);
DECLARE @i INT=1, @n INT, @AGR_ID BIGINT, @Msg NVARCHAR(200);
SELECT @n=COUNT(*) FROM @Agr;
WHILE @i<=@n
BEGIN
  SELECT @AGR_ID=AGR_ID FROM @Agr WHERE ORD=@i;
  SET @Msg=N'===== DEBT PT AGR '+CAST(@AGR_ID AS VARCHAR(20))+N' =====';
  RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
  EXEC dbo.SP_MIGRATE_LS005_DEBT_PAYTRANS
    @AGR_ID=@AGR_ID, @RESUME=0, @HARD_RESET=0, @BATCH_SIZE=1000, @DEBUG=1;
  SET @i+=1;
END

-- re-apply tahsilat PAID after debt PT exists
SET @i=1;
WHILE @i<=@n
BEGIN
  SELECT @AGR_ID=AGR_ID FROM @Agr WHERE ORD=@i;
  SET @Msg=N'===== RE-TAH AGR '+CAST(@AGR_ID AS VARCHAR(20))+N' =====';
  RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
  EXEC dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR @AGR_ID=@AGR_ID, @CLEAN=1, @DEBUG=1;
  SET @i+=1;
END

SELECT i.ABYS_AGREEMENT_ID AGR,
  COUNT(*) DEBT_PT,
  SUM(CASE WHEN ISNULL(p.PAID,0)>0 THEN 1 ELSE 0 END) PAID_GT0
FROM LS_005_01_PAYTRANS p WITH (NOLOCK)
JOIN LS_005_01_INVOICE i WITH (NOLOCK) ON i.LREF=p.INVOICEREF
WHERE i.ABYS_AGREEMENT_ID IN (276503,556305,197168,5727,2221,978259,1192595)
  AND ISNULL(p.IOCODE,0)=0 AND ISNULL(i.IOCODE,0)=0
GROUP BY i.ABYS_AGREEMENT_ID
ORDER BY 1;
