USE energy;
SET NOCOUNT ON;
DECLARE @Agr TABLE (ORD INT IDENTITY(1,1) PRIMARY KEY, AGR_ID BIGINT NOT NULL);
INSERT INTO @Agr (AGR_ID) VALUES (276503),(556305),(197168),(5727),(2221),(978259),(1192595);
DECLARE @i INT=1, @n INT, @AGR_ID BIGINT, @Msg NVARCHAR(200);
SELECT @n=COUNT(*) FROM @Agr;
WHILE @i<=@n
BEGIN
  SELECT @AGR_ID=AGR_ID FROM @Agr WHERE ORD=@i;
  SET @Msg=N'===== AGR '+CAST(@AGR_ID AS VARCHAR(20))+N' =====';
  RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

  IF OBJECT_ID('dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR','P') IS NOT NULL
    EXEC dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR @AGR_ID=@AGR_ID, @CLEAN=1, @DEBUG=1;

  IF OBJECT_ID('dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR','P') IS NOT NULL
    EXEC dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR @AGR_ID=@AGR_ID, @CLEAN=1, @DEBUG=1;

  IF OBJECT_ID('dbo.SP_MIGRATE_LS005_INSTALLMENT_PLAN','P') IS NOT NULL
    EXEC dbo.SP_MIGRATE_LS005_INSTALLMENT_PLAN @AGR_ID=@AGR_ID, @HARD_RESET=1, @RESUME=0, @BATCH_SIZE=5000, @DEBUG=1;

  SET @i+=1;
END

SELECT a.AGR_ID,
  (SELECT COUNT(*) FROM LS_005_01_INVOICE i WITH (NOLOCK) WHERE i.ABYS_AGREEMENT_ID=a.AGR_ID) INV,
  (SELECT COUNT(*) FROM LS_005_01_INVOICE i WITH (NOLOCK) WHERE i.ABYS_AGREEMENT_ID=a.AGR_ID AND i.[TYPE]=92) IADE,
  (SELECT COUNT(*) FROM LS_005_01_INVOICE i WITH (NOLOCK) WHERE i.ABYS_AGREEMENT_ID=a.AGR_ID AND i.[TYPE]=101) TAH,
  (SELECT COUNT(*) FROM LS_005_01_PAYTRANS p WITH (NOLOCK) WHERE p.ABYS_AGREEMENT_ID=a.AGR_ID AND ISNULL(p.IOCODE,0)=1) PAY_PT,
  (SELECT COUNT(*) FROM LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK) WHERE pl.ABYS_AGREEMENT_ID=a.AGR_ID AND pl.ABYS_ID IS NOT NULL) INST
FROM @Agr a ORDER BY a.ORD;
