SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
USE energy;
SET NOCOUNT ON;

UPDATE pt SET CANCELED = 1
FROM energy.dbo.LS_005_01_PAYTRANS pt
WHERE pt.INVOICEREF = 152215477
  AND ISNULL(pt.PAYTYPE, 0) = 120
  AND ISNULL(pt.CANCELED, 0) = 0;

UPDATE pl
SET pl.INVOICE_REF = 152185118,
    pl.PAYTRANS_REF = pt.LREF
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl
INNER JOIN energy.dbo.LS_005_01_PAYTRANS pt
  ON pt.INVOICEREF = 152185118
 AND ISNULL(pt.IOCODE, 0) = 0
 AND ISNULL(pt.CANCELED, 0) = 0
 AND ISNULL(pt.PAYTYPE, 0) = 120
 AND pt.INST_NR = ISNULL(pl.INSTALLMENT_COUNT, pl.ABYS_ORDER_NUMBER)
WHERE pl.ABYS_INSTALLMENT_ID = 808493;

-- 5727: plani dogru faturaya bagla + split
UPDATE energy.dbo.LS_005_01_INVOICE
SET INSTALLMENT_PLAN_REF = 806966,
    ABYS_INSTALLMENT_ID = 806966
WHERE LREF = 150404069
  AND ABYS_AGREEMENT_ID = 5727;

EXEC dbo.SP_MIG_INSTALLMENT_PLAN_WIRE_INVOICE @AGR_ID = 5727, @DEBUG = 1;
EXEC dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR @AGR_ID = 5727, @DEBUG = 1;

SELECT '808493' tag, pl.INSTALLMENT_COUNT, pl.INVOICE_REF, pl.PAYTRANS_REF, pt.PAID, pt.EXPLAIN
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl
LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pt ON pt.LREF = pl.PAYTRANS_REF
WHERE pl.ABYS_INSTALLMENT_ID = 808493
ORDER BY pl.INSTALLMENT_COUNT;

SELECT '5727' tag, LREF, INVOICEREF, INST_NR, PAYTYPE, PAYABLETOTAL, PAID, CANCELED, EXPLAIN
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF = 150404069
ORDER BY CANCELED, INST_NR, LREF;
