SELECT LREF, ABYS_INSTALLMENT_ID, INSTALLMENT_PLAN_REF, PAYABLETOTAL
FROM MIGRATION.LS_INVOICE WHERE ABYS_AGREEMENT_ID=276503 AND (ABYS_INSTALLMENT_ID=758703 OR INSTALLMENT_PLAN_REF=758703);
SELECT LREF, ABYS_INSTALLMENT_ID, INSTALLMENT_PLAN_REF, PAYABLETOTAL
FROM MIGRATION.LS_INVOICE WHERE ABYS_AGREEMENT_ID=5727 AND (ABYS_INSTALLMENT_ID=806966 OR INSTALLMENT_PLAN_REF=806966 OR ABYS_ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM SMS.CS_ACCOUNT WHERE AGREEMENT_ID=5727 AND INSTALLMENT_ID=806966));
