SELECT aa.ID, aa.ACTION_TYPE_ID, atp.TYPE ATP_TYPE, aa.ACTION_DATE,
       (SELECT ROUND(SUM(ai.AMOUNT*ai.STATUS),2) FROM SMS.CS_ACCOUNT_INCOME ai WHERE ai.ACCOUNT_ACTION_ID=aa.ID) TUT,
       aa.REF_DEPOSIT_ACCOUNT_ID, aa.CASH_ID, aa.RECEIPT_NUMBER
FROM SMS.CS_ACCOUNT_ACTION aa
LEFT JOIN SMS.CS_ACTION_TYPE_PRM atp ON atp.ID = aa.ACTION_TYPE_ID
WHERE aa.ACCOUNT_ID = 13841039
ORDER BY aa.ACTION_DATE, aa.ID;
