SELECT a.ID ACC_ID, a.AGREEMENT_ID, a.ACCRUE_TYPE_ID, a.STATUS ACC_STATUS,
       aa.ID ACT_ID, aa.ACTION_TYPE_ID, aa.ACTION_CLASS, aa.ACTION_DATE,
       aa.AMOUNT, aa.REF_DEPOSIT_ACCOUNT_ID, aa.CROSS_ACCOUNT_ACTION_ID,
       aa.INSTALLMENT_ID, aa.INSTALLMENT_ORDER_NUMBER
FROM SMS.CS_ACCOUNT a
JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ACCOUNT_ID = a.ID
WHERE a.ID = 20811205 OR aa.ID = 20811205 OR a.AGREEMENT_ID = 276503 AND aa.ID IN (
  SELECT ID FROM SMS.CS_ACCOUNT_ACTION WHERE ACCOUNT_ID = 20811205
)
ORDER BY aa.ACTION_DATE, aa.ID;
