SELECT aa.ID, aa.ACTION_TYPE_ID, aa.ACTION_CLASS, aa.ACTION_DATE, aa.AMOUNT,
       aa.REF_DEPOSIT_ACCOUNT_ID, aa.REF_DEPOSIT_ACCOUNT_ACTION_ID, aa.POOL_ID,
       aa.BILL_SERIAL, aa.BILL_ORDER_NUMBER
FROM SMS.CS_ACCOUNT_ACTION aa WHERE aa.ACCOUNT_ID = 20811205 ORDER BY aa.ACTION_DATE, aa.ID;
