-- payments that point to this account via CROSSREF heuristic sources
SELECT pay.ID, pay.ACTION_TYPE_ID, pay.ACTION_DATE, pay.AMOUNT, pay.ACCOUNT_ID,
       a.AGREEMENT_ID, pay.REF_DEPOSIT_ACCOUNT_ID
FROM SMS.CS_ACCOUNT_ACTION pay
JOIN SMS.CS_ACCOUNT a ON a.ID = pay.ACCOUNT_ID
WHERE pay.ACTION_CLASS = 2
  AND a.AGREEMENT_ID = 276503
  AND pay.ACTION_DATE BETWEEN DATE '2012-06-01' AND DATE '2013-02-01'
ORDER BY pay.ACTION_DATE, pay.ID;
