USE energy;
SET NOCOUNT ON;
DECLARE @Agr TABLE (ORD INT IDENTITY(1,1), AGR_ID BIGINT);
INSERT INTO @Agr(AGR_ID) VALUES (276503),(556305),(197168),(5727),(2221),(978259),(1192595);
DECLARE @i INT=1,@n INT,@a BIGINT,@m NVARCHAR(200);
SELECT @n=COUNT(*) FROM @Agr;
WHILE @i<=@n
BEGIN
  SELECT @a=AGR_ID FROM @Agr WHERE ORD=@i;
  SET @m=N'===== SPLIT AGR '+CAST(@a AS VARCHAR(20))+N' =====';
  RAISERROR('%s',0,1,@m) WITH NOWAIT;
  EXEC dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR @AGR_ID=@a, @DEBUG=1;
  SET @i+=1;
END
SELECT inv.LREF, inv.ABYS_AGREEMENT_ID, inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID, inv.PAYABLETOTAL, inv.CLOSED,
       (SELECT COUNT(*) FROM LS_005_01_PAYTRANS p WHERE p.INVOICEREF=inv.LREF AND ISNULL(p.IOCODE,0)=0 AND ISNULL(p.CANCELED,0)=0 AND ISNULL(p.INST_NR,0)>0) INST_PT,
       (SELECT COUNT(*) FROM LS_005_01_PAYTRANS p WHERE p.INVOICEREF=inv.LREF AND ISNULL(p.IOCODE,0)=0 AND ISNULL(p.CANCELED,0)=0 AND ISNULL(p.INST_NR,0)=0) RAW_PT
FROM LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.ABYS_AGREEMENT_ID IN (276503,5727,2221,978259,1192595)
  AND inv.ABYS_INSTALLMENT_ID IS NOT NULL
ORDER BY inv.ABYS_AGREEMENT_ID, inv.LREF;
SELECT LREF, INVOICEREF, INST_NR, PAYTYPE, PAYABLETOTAL, PAID, CANCELED, EXPLAIN
FROM LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF=152185118
ORDER BY CANCELED, INST_NR, LREF;
