SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON; USE energy;
EXEC dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR @AGR_ID=5727, @DEBUG=1;
SELECT LREF, INVOICEREF, INST_NR, PAYTYPE, PAYABLETOTAL, PAID, CANCELED, EXPLAIN
FROM LS_005_01_PAYTRANS WHERE INVOICEREF=150404069 ORDER BY CANCELED, INST_NR;
