SET NOCOUNT ON;
DECLARE @Agr TABLE (AGR_ID BIGINT PRIMARY KEY);
INSERT INTO @Agr VALUES (2221),(978259),(1192595),(276503);

PRINT '==== 1) CS_INSTALLMENT cancel flags ====';
SELECT
  ins.AGREEMENT_ID AS AGR_ID,
  CAST(ins.ID AS BIGINT) AS PLAN_ID,
  CASE WHEN ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL THEN 1 ELSE 0 END AS IS_CANCEL,
  CASE WHEN ins.DUE_DATE IS NOT NULL THEN 1 ELSE 0 END AS HAS_MUACCELLE,
  ins.CANCEL_CAUSE_ID, ins.CANCELLATION_DATE, ins.CANCELLATION_USER_ID,
  (SELECT COUNT(*) FROM izgazMGR.dbo.CS_INSTALLMENT_PLAN ip WHERE ip.INSTALLMENT_ID = ins.ID) AS PLAN_ROWS
FROM izgazMGR.dbo.CS_INSTALLMENT ins WITH (NOLOCK)
WHERE ins.AGREEMENT_ID IN (SELECT AGR_ID FROM @Agr)
ORDER BY AGR_ID, IS_CANCEL DESC, PLAN_ID;

PRINT '==== 2) energy INSTALLMENT_PLAN summary ====';
IF OBJECT_ID('energy.dbo.LS_005_01_INSTALLMENT_PLAN','U') IS NULL
  SELECT 'LS_005_01_INSTALLMENT_PLAN YOK' AS MSG;
ELSE
  SELECT
    pl.ABYS_AGREEMENT_ID AS AGR_ID,
    pl.PLAN_ID,
    COUNT(*) AS ROWS_N,
    MAX(ISNULL(pl.ISACTIVE,0)) AS ISACTIVE_MAX,
    MAX(CASE WHEN pl.ABYS_CANCELLATION_DATE IS NOT NULL THEN 1 ELSE 0 END) AS HAS_CDATE,
    MAX(CASE WHEN pl.ABYS_CANCEL_CAUSE_ID IS NOT NULL THEN 1 ELSE 0 END) AS HAS_CAUSE,
    SUM(CASE WHEN pl.PAYTRANS_REF IS NOT NULL THEN 1 ELSE 0 END) AS WIRED_PT
  FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK)
  WHERE pl.ABYS_ID IS NOT NULL AND pl.ABYS_AGREEMENT_ID IN (SELECT AGR_ID FROM @Agr)
  GROUP BY pl.ABYS_AGREEMENT_ID, pl.PLAN_ID
  ORDER BY AGR_ID, PLAN_ID;

PRINT '==== 3) Invoice debt PT gate ====';
;WITH inv AS (
  SELECT inv.LREF, inv.ABYS_AGREEMENT_ID AS AGR_ID,
         inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID,
         inv.PAYABLETOTAL, inv.CLOSED
  FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
  WHERE inv.ABYS_AGREEMENT_ID IN (SELECT AGR_ID FROM @Agr)
    AND ISNULL(inv.IOCODE,0)=0
    AND ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF) IS NOT NULL
)
SELECT
  i.AGR_ID, i.LREF AS INV_LREF,
  i.INSTALLMENT_PLAN_REF, i.ABYS_INSTALLMENT_ID,
  CONVERT(DECIMAL(18,2), i.PAYABLETOTAL) AS PAYABLE,
  SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) AS ACTIVE_TAKSIT_PT,
  SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=1 THEN 1 ELSE 0 END) AS CANC_TAKSIT_PT,
  SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) AS ACTIVE_MAIN_PT,
  SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=1 THEN 1 ELSE 0 END) AS CANC_MAIN_PT,
  MAX(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN CONVERT(DECIMAL(18,2),ISNULL(pt.PAID,0)) END) AS MAIN_PAID,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins
      WHERE ins.ID = ISNULL(i.ABYS_INSTALLMENT_ID, i.INSTALLMENT_PLAN_REF)
        AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
    ) THEN N'CANCEL_PLAN'
    ELSE N'ACTIVE_PLAN'
  END AS PLAN_KIND,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins
      WHERE ins.ID = ISNULL(i.ABYS_INSTALLMENT_ID, i.INSTALLMENT_PLAN_REF)
        AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
    ) THEN
      CASE
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) > 0 THEN N'FAIL_TAKSIT_STILL_ACTIVE'
        WHEN i.INSTALLMENT_PLAN_REF IS NOT NULL THEN N'FAIL_REF_NOT_NULL'
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) < 1 THEN N'FAIL_NO_MAIN'
        ELSE N'OK_CANCEL'
      END
    ELSE
      CASE
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_SPLIT'
        WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_MAIN_ONLY'
        ELSE N'WARN_NO_DEBT_PT'
      END
  END AS GATE
FROM inv i
LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.INVOICEREF = i.LREF
GROUP BY i.AGR_ID, i.LREF, i.INSTALLMENT_PLAN_REF, i.ABYS_INSTALLMENT_ID, i.PAYABLETOTAL, i.CLOSED
ORDER BY GATE, AGR_ID, INV_LREF;

PRINT '==== 4) GATE summary ====';
;WITH inv AS (
  SELECT inv.LREF, inv.ABYS_AGREEMENT_ID AS AGR_ID,
         inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID
  FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
  WHERE inv.ABYS_AGREEMENT_ID IN (SELECT AGR_ID FROM @Agr)
    AND ISNULL(inv.IOCODE,0)=0
    AND ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF) IS NOT NULL
), g AS (
  SELECT
    CASE
      WHEN EXISTS (
        SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins
        WHERE ins.ID = ISNULL(i.ABYS_INSTALLMENT_ID, i.INSTALLMENT_PLAN_REF)
          AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
      ) THEN
        CASE
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) > 0 THEN N'FAIL_TAKSIT_STILL_ACTIVE'
          WHEN i.INSTALLMENT_PLAN_REF IS NOT NULL THEN N'FAIL_REF_NOT_NULL'
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) < 1 THEN N'FAIL_NO_MAIN'
          ELSE N'OK_CANCEL'
        END
      ELSE
        CASE
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_SPLIT'
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_MAIN_ONLY'
          ELSE N'WARN_NO_DEBT_PT'
        END
    END AS GATE
  FROM inv i
  LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.INVOICEREF = i.LREF
  GROUP BY i.AGR_ID, i.LREF, i.INSTALLMENT_PLAN_REF, i.ABYS_INSTALLMENT_ID
)
SELECT GATE, COUNT(*) AS CNT FROM g GROUP BY GATE ORDER BY CNT DESC;

PRINT '==== 5) SP deploy check ====';
SELECT name FROM energy.sys.procedures
WHERE name IN (
  'SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR',
  'SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR',
  'SP_MIGRATE_LS005_INSTALLMENT_PLAN'
)
ORDER BY name;