/* =============================================================================
   FILE : prodEnergy/90_afl_frk/98_TEST_asim_main_close.sql
   TEST ORTAMI — ASIM (EKS>TAH) hesaplarda acik borc PT kapatma

   UYARI:
     Oracle overlay ASIM'i LS_OV_EKS_SKIP'e atar (otomatik IADE yok).
     Bu script PROD zinciri degil — sadece test hizalama, manuel onay.
     DELTA_TAH_NET (INV tutari) kalir; sadece PT kalan / CLOSED hizalanir.

   Mahsup / guvence (ayri bacak — bu script DEGIL):
     Ornek 412056: 778.90 emanet mahsup = 162+1936 (EMANET_MAHSUP_RULE.md);
     kalan iade TYPE110 = O60/E610 (GUVENCE_IADE_110_RULE.md).
     ASIM close sadece eksilten sonrasi acik PT'yi kapatir.

   Kapsam (heal eder):
     OV_EKS KIND=ASIM
     + AFL.BALANCE ≈ 0
     + ABYS TTK TOPLAM_TAHAKKUK ≈ 0 (veya satir yok)
     + Energy hesabinda acik borc PT (kalan > eps)
     → tum uygun PT: PAID=PAYABLE; INV CLOSED=1

   Kapsamaz:
     TAM/IADE → 98_TEST_tam_iade_main_close.sql
     AFL acik borc, ABYS TTK > 0, KISMI tutar duzeltmesi

   Kullanim:
     1) @DryRun=1  → adaylar
     2) Listeyi kontrol et
     3) @DryRun=0  → APPLY + MIG_ASIM_CLOSE_LOG
     4) EXEC SP_AGR_FRK_ALL @Agr=..., @ReturnResult=1

   Ornek:
     DECLARE @Agr BIGINT = 412056;
     -- SET @DryRun = 0;
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun    BIT           = 1;      -- 0 = APPLY (test)
DECLARE @Agr       BIGINT        = 412056; -- NULL=tum | ornek 412056
DECLARE @AccountId BIGINT        = NULL;
DECLARE @Eps       DECIMAL(18,2) = 0.02;
DECLARE @RunId     UNIQUEIDENTIFIER = NEWID();
DECLARE @Ts        DATETIME2(3) = SYSDATETIME();
-- SET @DryRun = 0;

PRINT CONVERT(VARCHAR(30), @Ts, 121)
    + N' | 98_TEST ASIM close DryRun=' + CAST(@DryRun AS VARCHAR(1))
    + N' Agr=' + CASE WHEN @Agr IS NULL THEN N'TUM' ELSE CONVERT(NVARCHAR(20), @Agr) END
    + N' RUN=' + CONVERT(NVARCHAR(36), @RunId);

IF OBJECT_ID('izgazMGR.dbo.LS_OV_EKS_CLASS', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.dbo.LS_OV_EKS_CLASS yok — ASIM adaylari uretilemez.', 16, 1);
    RETURN;
END;

/* ---------- Log tablo ---------- */
IF OBJECT_ID('energy.dbo.MIG_ASIM_CLOSE_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE energy.dbo.MIG_ASIM_CLOSE_LOG (
        LOG_ID         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID         UNIQUEIDENTIFIER NOT NULL,
        SNAPSHOT_TS    DATETIME2(3) NOT NULL
            CONSTRAINT DF_ASIM_CLOSE_TS DEFAULT (SYSDATETIME()),
        DRY_RUN        BIT NOT NULL,
        AGREEMENT_ID   BIGINT NULL,
        ACCOUNT_ID     BIGINT NOT NULL,
        MAIN_LREF      INT NULL,
        INV_LREF       INT NOT NULL,
        PT_LREF        INT NOT NULL,
        EKS_AMT        DECIMAL(18,2) NULL,
        ABYS_TAH       DECIMAL(18,2) NULL,
        PT_PAID_OLD    DECIMAL(18,2) NULL,
        PT_PAYABLE     DECIMAL(18,2) NULL,
        PT_KALAN       DECIMAL(18,2) NULL,
        AFL_BALANCE    DECIMAL(18,2) NULL,
        SOURCE_KIND    VARCHAR(20) NOT NULL,  -- OV_ASIM
        NOTE           NVARCHAR(200) NULL
    );
    CREATE NONCLUSTERED INDEX IX_ASIM_CLOSE_RUN
        ON energy.dbo.MIG_ASIM_CLOSE_LOG (RUN_ID, ACCOUNT_ID);
END;

/* #CAND_ASIM98 adi TAM script ile carpismasin; SELECT INTO ayni batch'te eski semayi tutar */
IF OBJECT_ID('tempdb..#CAND_ASIM98') IS NOT NULL DROP TABLE #CAND_ASIM98;

CREATE TABLE #CAND_ASIM98 (
    AGREEMENT_ID   BIGINT NULL,
    ACCOUNT_ID     BIGINT NOT NULL,
    MAIN_LREF      INT NULL,
    EKS_AMT        DECIMAL(18,2) NULL,
    ABYS_TAH       DECIMAL(18,2) NULL,
    INV_LREF       INT NOT NULL,
    INV_TYPE       INT NULL,
    INV_CLOSED     BIT NULL,
    INV_PAYABLE    DECIMAL(18,2) NULL,
    PT_LREF        INT NOT NULL,
    PT_PAYABLE     DECIMAL(18,2) NULL,
    PT_PAID_OLD    DECIMAL(18,2) NULL,
    PT_PAID_NEW    DECIMAL(18,2) NULL,
    PT_KALAN       DECIMAL(18,2) NULL,
    AFL_BALANCE    DECIMAL(18,2) NULL,
    SOURCE_KIND    VARCHAR(20) NOT NULL
);

;WITH asim AS (
    SELECT
        CAST(e.AGREEMENT_ID AS BIGINT) AS AGREEMENT_ID,
        CAST(e.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
        CAST(e.MAIN_LREF AS INT) AS MAIN_LREF,
        CONVERT(DECIMAL(18,2), ISNULL(e.EKS_AMT, 0)) AS EKS_AMT
    FROM izgazMGR.dbo.LS_OV_EKS_CLASS e WITH (NOLOCK)
    WHERE e.KIND = 'ASIM'
      AND e.ACCOUNT_ID IS NOT NULL
      AND (@Agr IS NULL OR e.AGREEMENT_ID = @Agr)
      AND (@AccountId IS NULL OR e.ACCOUNT_ID = @AccountId)
),
abys_ttk AS (
    SELECT
        CAST(t.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
        CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL(18,2), ISNULL(t.TOPLAM_TAHAKKUK, 0)))) AS ABYS_TAH
    FROM energy.dbo.TUKETIM_TUTAR_KONTROL t WITH (NOLOCK)
    WHERE EXISTS (
        SELECT 1 FROM asim a WHERE a.ACCOUNT_ID = CAST(t.ACCOUNT_ID AS BIGINT)
    )
    GROUP BY CAST(t.ACCOUNT_ID AS BIGINT)
)
INSERT INTO #CAND_ASIM98 (
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, EKS_AMT, ABYS_TAH,
    INV_LREF, INV_TYPE, INV_CLOSED, INV_PAYABLE,
    PT_LREF, PT_PAYABLE, PT_PAID_OLD, PT_PAID_NEW, PT_KALAN,
    AFL_BALANCE, SOURCE_KIND
)
SELECT
    a.AGREEMENT_ID,
    a.ACCOUNT_ID,
    a.MAIN_LREF,
    a.EKS_AMT,
    CONVERT(DECIMAL(18,2), ISNULL(ab.ABYS_TAH, 0)) AS ABYS_TAH,
    inv.LREF AS INV_LREF,
    inv.TYPE AS INV_TYPE,
    ISNULL(inv.CLOSED, 0) AS INV_CLOSED,
    CONVERT(DECIMAL(18,2), ISNULL(inv.PAYABLETOTAL, 0)) AS INV_PAYABLE,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAID_NEW,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(afl.BALANCE, 0)) AS AFL_BALANCE,
    'OV_ASIM' AS SOURCE_KIND
FROM asim a
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    ON inv.ABYS_ACCOUNT_ID = a.ACCOUNT_ID
   AND ISNULL(inv.IOCODE, 0) = 0
   AND ISNULL(inv.CANCELED, 0) = 0
   AND ISNULL(inv.TYPE, 0) <> 92
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
LEFT JOIN abys_ttk ab
    ON ab.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN dbo.LS_AFL_OPEN_DEBT afl WITH (NOLOCK)
    ON CAST(afl.FATURAID AS BIGINT) = a.ACCOUNT_ID
WHERE CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
  AND CONVERT(DECIMAL(18,2), ISNULL(afl.BALANCE, 0)) <= @Eps
  AND CONVERT(DECIMAL(18,2), ISNULL(ab.ABYS_TAH, 0)) <= @Eps
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_CAND_ASIM98 ON #CAND_ASIM98 (PT_LREF);

PRINT N'build_ms=' + CAST(DATEDIFF(MILLISECOND, @Ts, SYSDATETIME()) AS VARCHAR(20));

PRINT '========== TESPIT OZET ==========';
SELECT
    SOURCE_KIND,
    COUNT(*) AS PT_OPEN_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN)) AS SUM_PT_KALAN,
    CONVERT(DECIMAL(18,2), SUM(EKS_AMT)) AS SUM_EKS_AMT_ROW
FROM #CAND_ASIM98
GROUP BY SOURCE_KIND;

PRINT '========== ADAYLAR (TOP 100) ==========';
SELECT TOP 100
    AGREEMENT_ID, ACCOUNT_ID, SOURCE_KIND, MAIN_LREF, INV_LREF, INV_TYPE, INV_CLOSED,
    EKS_AMT, ABYS_TAH,
    PT_LREF, PT_PAYABLE, PT_PAID_OLD, PT_KALAN, AFL_BALANCE
FROM #CAND_ASIM98
ORDER BY PT_KALAN DESC, AGREEMENT_ID, ACCOUNT_ID, INV_LREF;

INSERT INTO energy.dbo.MIG_ASIM_CLOSE_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, INV_LREF, PT_LREF, EKS_AMT, ABYS_TAH,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN, AFL_BALANCE, SOURCE_KIND, NOTE
)
SELECT
    @RunId, @Ts, @DryRun, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, INV_LREF, PT_LREF, EKS_AMT, ABYS_TAH,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN, AFL_BALANCE, SOURCE_KIND,
    CASE WHEN @DryRun = 1 THEN N'DRY_RUN' ELSE N'APPLY' END
FROM #CAND_ASIM98;

PRINT N'LOG n=' + CAST(@@ROWCOUNT AS VARCHAR(20)) + N' RUN=' + CONVERT(NVARCHAR(36), @RunId);

IF NOT EXISTS (SELECT 1 FROM #CAND_ASIM98)
BEGIN
    PRINT N'Aday yok — cikis. (ASIM + AFL≈0 + ABYS≈0 + acik PT yok)';
    RETURN;
END;

IF @DryRun = 1
BEGIN
    PRINT N'DRY_RUN=1 — Energy UPDATE yok.';
    PRINT N'Uygula: SET @DryRun=0;  (once @Agr ile daralt)';
    PRINT N'Dogrula: EXEC dbo.SP_AGR_FRK_ALL @Agr=<id>, @ReturnResult=1;';
    PRINT N'Not: DELTA_KALAN duser; DELTA_TAH_NET (INV) ASIM kokunde kalabilir.';
    PRINT N'Incele: SELECT * FROM MIG_ASIM_CLOSE_LOG WHERE RUN_ID='''
        + CONVERT(NVARCHAR(36), @RunId) + N''';
    RETURN;
END;

PRINT '========== APPLY ==========';
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, c.PT_PAID_NEW)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #CAND_ASIM98 c ON c.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

PRINT N'PT PAID=PAYABLE n=' + CAST(@@ROWCOUNT AS VARCHAR(20));

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT INV_LREF FROM #CAND_ASIM98) c ON c.INV_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 0;

PRINT N'INV CLOSED=1 n=' + CAST(@@ROWCOUNT AS VARCHAR(20));

COMMIT TRAN;

PRINT '========== POST: hala acik aday? (0 beklenir) ==========';
SELECT COUNT(*) AS STILL_OPEN
FROM #CAND_ASIM98 c
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = c.PT_LREF
WHERE CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps;

PRINT '========== Etkilenen sozlesmeler ==========';
SELECT DISTINCT AGREEMENT_ID
FROM #CAND_ASIM98
WHERE AGREEMENT_ID IS NOT NULL
ORDER BY AGREEMENT_ID;

PRINT N'Sonra: EXEC dbo.SP_AGR_FRK_ALL @Agr = <AGREEMENT_ID>, @WriteTable=1, @ReturnResult=1;';
PRINT N'  DELTA_KALAN dusmeli; DELTA_TAH_NET ASIM/TTK kaymasi ayri kalir.';
PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + N' | 98_TEST ASIM DONE APPLY RUN='
    + CONVERT(NVARCHAR(36), @RunId);
GO
