-- =====================================================================================
-- LS_HHD_MSTR CTAS  (v03 — orphan gun grain TRUNC(READ_DATE))
-- HHD master (LS_005_01_hhd_to_hhd_mstr) + detay READ_NO map
--
-- Onkosul : MIGRATION.LS_READING (LS_READING.sql MAIN CTAS)
-- Kaynak  : MIGRATION.LS_READING + SMS.CS_READING_END_OF_DAY (sadece ID varligi)
--
-- FIX v04:
--   - Sentetik (ABYS_NOTE MIG_SYNTH%): orphan grain += ABYS_ACCRUE_TYPE_ID
--   - ROUTE_GRP = ACCRUE aciklama (Energy route_grp)
--   - Organik orphan grain v03 (degismez)
--   - TMP / EOD / ORPHAN ara tablolari GATE oncesi DROP (STG_DROP)
--
-- FIX v03:
--   - ORPHAN (EOD yok): grain = LOC_REGION + READER_PRSNL(+ID) + TRUNC(READ_DATE)
--     ayni kisi ayni gun farkli saat → tek mstr (READ_DATE = gun 00:00)
--   - EOD: grain = ENDOFDAY_ID (+ region/prsnl); READ_DATE GROUP BY'dan cikti
--     READ_DATE = TRUNC(MIN(detay READ_DATE))
--   - TRAN_MAP orphan join: TRUNC(d.READ_DATE) = m.READ_DATE
--
-- FIX v02:
--   - EOD count kolonlari kullanilmaz — TOTAL_COUNT = detay COUNT(*)
--   - EOD_OK bayragi TMP'de; ENDOFDAY_ID NUMBER(18); READ_NO MERGE PDML 56
--
-- Kovalar :
--   A EOD     : ENDOFDAY_ID dolu ve EOD tablosunda var → ENDOFDAY grain
--   B ORPHAN  : EOD null veya EOD satiri yok → gun + okuyucu grain
--   C SKIP    : loc_region / read_date / reader_prsnl_id kirik
--
-- Cikti   :
--   MIGRATION.LS_OV_HHD_MSTR_EOD
--   MIGRATION.LS_OV_HHD_MSTR_ORPHAN
--   MIGRATION.LS_OV_HHD_MSTR
--   MIGRATION.LS_OV_HHD_TRAN_MAP
--   MIGRATION.LS_OV_HHD_MSTR_SKIP
--   MIGRATION.LS_READING.READ_NO
--
-- Gate    : LS_HHD_MSTR_GATE.sql
-- Diag    : LS_HHD_MSTR_DIAG.sql  (once bunu calistir)
-- Energy  : 524_READ_HHD_MSTR__apply.sql
-- =====================================================================================

-- Ilk hata sonrasi cascade ORA-00942 yagmurunu kes
WHENEVER SQLERROR EXIT FAILURE

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========== PRECHECK ==========
-- Not: PL/SQL static SQL role privilege gormez (ORA-00942). Dictionary + SQL*Plus COUNT kullan.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_READING';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,
      'MIGRATION.LS_READING yok. Once @oracleCTAS/LS_READING.sql (MAIN CTAS) calistir; ' ||
      'MIGRATION.LS_READING_HHD_SRC placeholder — kullanma.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'SMS' AND TABLE_NAME = 'CS_READING_END_OF_DAY';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'SMS.CS_READING_END_OF_DAY yok.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_READING'
     AND COLUMN_NAME = 'ABYS_READING_END_OF_DAY_ID';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20003, 'MIGRATION.LS_READING.ABYS_READING_END_OF_DAY_ID yok — LS_READING CTAS eski olabilir.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('PRECHECK OK | MIGRATION.LS_READING + CS_READING_END_OF_DAY + ABYS_READING_END_OF_DAY_ID');
END;
/

PROMPT ========== LS_READING COUNT (SQL, role OK) ==========
SELECT COUNT(*) AS LS_READING_N FROM MIGRATION.LS_READING;
/

-- =============================================================================
-- 0) Detay driver + EOD_OK + READ_DATE_DAY
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_HHD_TRAN_KEY PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_HHD_TRAN_KEY NOLOGGING PARALLEL 56 AS
SELECT /*+ FULL(r) PARALLEL(r 56) */
    r.LREF,
    CAST(r.LOC_REGION AS NUMBER(10))                 AS LOC_REGION,
    r.READ_DATE                                      AS READ_DATE,
    TRUNC(r.READ_DATE)                               AS READ_DATE_DAY,
    r.READER_PRSNL                                   AS READER_PRSNL,
    CAST(r.READER_PRSNL_ID AS NUMBER(10))            AS READER_PRSNL_ID,
    CAST(r.ABYS_READING_END_OF_DAY_ID AS NUMBER(18)) AS ENDOFDAY_ID,
    CASE WHEN e.ID IS NOT NULL THEN 1 ELSE 0 END     AS EOD_OK,
    CASE WHEN NVL(r.ABYS_NOTE, 'x') LIKE 'MIG_SYNTH%' THEN 1 ELSE 0 END AS IS_SYNTH,
    CAST(r.ABYS_ACCRUE_TYPE_ID AS NUMBER(10))        AS ABYS_ACCRUE_TYPE_ID,
    CAST(SUBSTR(
           CASE
             WHEN NVL(r.ABYS_NOTE, 'x') LIKE 'MIG_SYNTH%'
               THEN NVL(
                      (SELECT m.EXPLAIN_PREFIX
                         FROM MIGRATION.MIG_ACCRUE_TYPE_MAP m
                        WHERE m.ABYS_ACCRUE_TYPE_ID = r.ABYS_ACCRUE_TYPE_ID),
                      'ACCRUE=' || TO_CHAR(r.ABYS_ACCRUE_TYPE_ID))
             ELSE NULL
           END, 1, 50) AS VARCHAR2(50))              AS ROUTE_GRP
FROM MIGRATION.LS_READING r
LEFT JOIN SMS.CS_READING_END_OF_DAY e
  ON e.ID = r.ABYS_READING_END_OF_DAY_ID;

CREATE INDEX MIGRATION.IX_TMP_HHD_TRAN_LREF ON MIGRATION.TMP_HHD_TRAN_KEY (LREF) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_TMP_HHD_TRAN_EOD  ON MIGRATION.TMP_HHD_TRAN_KEY (ENDOFDAY_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_TMP_HHD_TRAN_KEY  ON MIGRATION.TMP_HHD_TRAN_KEY (LOC_REGION, READ_DATE_DAY, READER_PRSNL_ID, EOD_OK) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_HHD_TRAN_LREF NOPARALLEL;
ALTER INDEX MIGRATION.IX_TMP_HHD_TRAN_EOD  NOPARALLEL;
ALTER INDEX MIGRATION.IX_TMP_HHD_TRAN_KEY  NOPARALLEL;
BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','TMP_HHD_TRAN_KEY'); END;
/

-- =============================================================================
-- 1A) EOD'li mstr grain  (ENDOFDAY_ID; READ_DATE = gun)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR_EOD PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_HHD_MSTR_EOD NOLOGGING PARALLEL 56 AS
SELECT
    CAST(trn.ENDOFDAY_ID AS NUMBER(18))           AS ENDOFDAY_ID,
    CAST(trn.LOC_REGION AS NUMBER(10))            AS READER_REGION,
    CAST(0 AS NUMBER(10))                         AS READER_CMP,
    TRUNC(MIN(trn.READ_DATE))                     AS READ_DATE,
    trn.READER_PRSNL                              AS READER_PRSNL,
    CAST(trn.READER_PRSNL_ID AS NUMBER(10))       AS READER_PRSNL_ID,
    CAST(COUNT(*) AS NUMBER(10))                  AS TOTAL_COUNT,
    CAST(0 AS NUMBER(10))                         AS NOTREAD_COUNT,
    CAST(1 AS NUMBER(1))                          AS HAS_EOD,
    CAST(3 AS NUMBER(5))                          AS REC_STATUS,
    CAST(0 AS NUMBER(10))                         AS READING_TYPE,
    CAST(NULL AS NUMBER(10))                      AS ABYS_ACCRUE_TYPE_ID,
    CAST(NULL AS VARCHAR2(50))                    AS ROUTE_GRP,
    CAST(0 AS NUMBER(1))                          AS IS_SYNTH
FROM MIGRATION.TMP_HHD_TRAN_KEY trn
WHERE trn.EOD_OK = 1
  AND trn.ENDOFDAY_ID IS NOT NULL
  AND trn.LOC_REGION IS NOT NULL
  AND trn.READ_DATE IS NOT NULL
  AND trn.READER_PRSNL_ID IS NOT NULL
GROUP BY trn.ENDOFDAY_ID, trn.LOC_REGION, trn.READER_PRSNL, trn.READER_PRSNL_ID;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_HHD_MSTR_EOD'); END;
/

-- =============================================================================
-- 1B) Orphan mstr grain
--     organik: region+prsnl+TRUNC(day)  (v03)
--     sentetik: + ABYS_ACCRUE_TYPE_ID + ROUTE_GRP
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR_ORPHAN PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_HHD_MSTR_ORPHAN NOLOGGING PARALLEL 56 AS
SELECT
    CAST(NULL AS NUMBER(18))                      AS ENDOFDAY_ID,
    CAST(trn.LOC_REGION AS NUMBER(10))            AS READER_REGION,
    CAST(0 AS NUMBER(10))                         AS READER_CMP,
    trn.READ_DATE_DAY                             AS READ_DATE,
    trn.READER_PRSNL                              AS READER_PRSNL,
    CAST(trn.READER_PRSNL_ID AS NUMBER(10))       AS READER_PRSNL_ID,
    CAST(COUNT(*) AS NUMBER(10))                  AS TOTAL_COUNT,
    CAST(0 AS NUMBER(10))                         AS NOTREAD_COUNT,
    CAST(0 AS NUMBER(1))                          AS HAS_EOD,
    CAST(3 AS NUMBER(5))                          AS REC_STATUS,
    CAST(9 AS NUMBER(10))                         AS READING_TYPE,
    CAST(NULL AS NUMBER(10))                      AS ABYS_ACCRUE_TYPE_ID,
    CAST(NULL AS VARCHAR2(50))                    AS ROUTE_GRP,
    CAST(0 AS NUMBER(1))                          AS IS_SYNTH
FROM MIGRATION.TMP_HHD_TRAN_KEY trn
WHERE trn.EOD_OK = 0
  AND NVL(trn.IS_SYNTH, 0) = 0
  AND trn.LOC_REGION IS NOT NULL
  AND trn.READ_DATE_DAY IS NOT NULL
  AND trn.READER_PRSNL_ID IS NOT NULL
GROUP BY trn.LOC_REGION, trn.READ_DATE_DAY, trn.READER_PRSNL, trn.READER_PRSNL_ID
UNION ALL
SELECT
    CAST(NULL AS NUMBER(18))                      AS ENDOFDAY_ID,
    CAST(trn.LOC_REGION AS NUMBER(10))            AS READER_REGION,
    CAST(0 AS NUMBER(10))                         AS READER_CMP,
    trn.READ_DATE_DAY                             AS READ_DATE,
    trn.READER_PRSNL                              AS READER_PRSNL,
    CAST(trn.READER_PRSNL_ID AS NUMBER(10))       AS READER_PRSNL_ID,
    CAST(COUNT(*) AS NUMBER(10))                  AS TOTAL_COUNT,
    CAST(0 AS NUMBER(10))                         AS NOTREAD_COUNT,
    CAST(0 AS NUMBER(1))                          AS HAS_EOD,
    CAST(3 AS NUMBER(5))                          AS REC_STATUS,
    CAST(9 AS NUMBER(10))                         AS READING_TYPE,
    CAST(trn.ABYS_ACCRUE_TYPE_ID AS NUMBER(10))   AS ABYS_ACCRUE_TYPE_ID,
    MAX(trn.ROUTE_GRP)                            AS ROUTE_GRP,
    CAST(1 AS NUMBER(1))                          AS IS_SYNTH
FROM MIGRATION.TMP_HHD_TRAN_KEY trn
WHERE trn.EOD_OK = 0
  AND NVL(trn.IS_SYNTH, 0) = 1
  AND trn.LOC_REGION IS NOT NULL
  AND trn.READ_DATE_DAY IS NOT NULL
  AND trn.READER_PRSNL_ID IS NOT NULL
GROUP BY trn.LOC_REGION, trn.READ_DATE_DAY, trn.READER_PRSNL, trn.READER_PRSNL_ID,
         trn.ABYS_ACCRUE_TYPE_ID;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_HHD_MSTR_ORPHAN'); END;
/

-- =============================================================================
-- 2) Birlesik mstr + READ_NO
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_HHD_MSTR NOLOGGING PARALLEL 56 AS
SELECT
    CAST(
      ROW_NUMBER() OVER (
        -- READ_NO = READ_DATE sirali (birebir energy IDENTITY_INSERT)
        ORDER BY x.READ_DATE,
                 x.HAS_EOD DESC,
                 x.ENDOFDAY_ID NULLS LAST,
                 x.READER_REGION,
                 x.READER_PRSNL_ID,
                 NVL(x.READER_PRSNL, CHR(0)),
                 NVL(x.IS_SYNTH, 0),
                 NVL(x.ABYS_ACCRUE_TYPE_ID, -1),
                 NVL(x.ROUTE_GRP, CHR(0))
      ) AS NUMBER(10)
    ) AS READ_NO,
    x.ENDOFDAY_ID,
    x.READER_REGION,
    x.READER_CMP,
    x.READ_DATE,
    x.READER_PRSNL,
    x.READER_PRSNL_ID,
    x.TOTAL_COUNT,
    x.NOTREAD_COUNT,
    x.HAS_EOD,
    x.REC_STATUS,
    x.READING_TYPE,
    x.ABYS_ACCRUE_TYPE_ID,
    x.ROUTE_GRP,
    x.IS_SYNTH,
    x.KIND AS OV_KIND
FROM (
    SELECT
        ENDOFDAY_ID, READER_REGION, READER_CMP, READ_DATE, READER_PRSNL, READER_PRSNL_ID,
        TOTAL_COUNT, NOTREAD_COUNT, HAS_EOD, REC_STATUS, READING_TYPE,
        ABYS_ACCRUE_TYPE_ID, ROUTE_GRP, IS_SYNTH,
        CAST('EOD' AS VARCHAR2(10)) AS KIND
    FROM MIGRATION.LS_OV_HHD_MSTR_EOD
    UNION ALL
    SELECT
        ENDOFDAY_ID, READER_REGION, READER_CMP, READ_DATE, READER_PRSNL, READER_PRSNL_ID,
        TOTAL_COUNT, NOTREAD_COUNT, HAS_EOD, REC_STATUS, READING_TYPE,
        ABYS_ACCRUE_TYPE_ID, ROUTE_GRP, IS_SYNTH,
        CAST('ORPHAN' AS VARCHAR2(10)) AS KIND
    FROM MIGRATION.LS_OV_HHD_MSTR_ORPHAN
) x;

CREATE UNIQUE INDEX MIGRATION.UX_OV_HHD_MSTR_RN
  ON MIGRATION.LS_OV_HHD_MSTR (READ_NO) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_HHD_MSTR_EOD
  ON MIGRATION.LS_OV_HHD_MSTR (ENDOFDAY_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_HHD_MSTR_KEY
  ON MIGRATION.LS_OV_HHD_MSTR (READER_REGION, READ_DATE, READER_PRSNL_ID, HAS_EOD) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.UX_OV_HHD_MSTR_RN NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_HHD_MSTR_EOD NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_HHD_MSTR_KEY NOPARALLEL;
BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_HHD_MSTR'); END;
/

-- =============================================================================
-- 3) Detay → READ_NO map
--    EOD    : ENDOFDAY_ID + okuyucu key
--    ORPHAN : TRUNC(READ_DATE) + okuyucu key
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_TRAN_MAP PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_HHD_TRAN_MAP NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    d.LREF AS SRC_LREF,
    m.READ_NO,
    m.OV_KIND AS MAP_KIND,
    m.ENDOFDAY_ID,
    m.HAS_EOD
FROM MIGRATION.TMP_HHD_TRAN_KEY d
JOIN MIGRATION.LS_OV_HHD_MSTR m
  ON m.READER_REGION   = d.LOC_REGION
 AND m.READER_PRSNL_ID = d.READER_PRSNL_ID
 AND NVL(m.READER_PRSNL, CHR(0)) = NVL(d.READER_PRSNL, CHR(0))
 AND (
        (d.EOD_OK = 1 AND m.HAS_EOD = 1
         AND m.ENDOFDAY_ID = d.ENDOFDAY_ID)
     OR (d.EOD_OK = 0 AND m.HAS_EOD = 0 AND NVL(d.IS_SYNTH, 0) = 0
         AND m.READ_DATE = d.READ_DATE_DAY
         AND NVL(m.IS_SYNTH, 0) = 0)
     OR (d.EOD_OK = 0 AND m.HAS_EOD = 0 AND NVL(d.IS_SYNTH, 0) = 1
         AND m.READ_DATE = d.READ_DATE_DAY
         AND NVL(m.IS_SYNTH, 0) = 1
         AND NVL(m.ABYS_ACCRUE_TYPE_ID, -1) = NVL(d.ABYS_ACCRUE_TYPE_ID, -1))
     );

CREATE INDEX MIGRATION.IX_OV_HHD_TRAN_MAP
  ON MIGRATION.LS_OV_HHD_TRAN_MAP (SRC_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_HHD_TRAN_MAP NOPARALLEL;
BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_HHD_TRAN_MAP'); END;
/

-- =============================================================================
-- 4) SKIP
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR_SKIP PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_HHD_MSTR_SKIP NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    d.LREF,
    d.LOC_REGION,
    d.READ_DATE,
    d.READER_PRSNL,
    d.READER_PRSNL_ID,
    d.ENDOFDAY_ID,
    d.EOD_OK,
    CASE
      WHEN d.LOC_REGION IS NULL THEN 'NULL_LOC_REGION'
      WHEN d.READ_DATE IS NULL THEN 'NULL_READ_DATE'
      WHEN d.READER_PRSNL_ID IS NULL THEN 'NULL_READER_PRSNL_ID'
      ELSE 'NO_MSTR_MATCH'
    END AS REASON
FROM MIGRATION.TMP_HHD_TRAN_KEY d
WHERE NOT EXISTS (
    SELECT 1 FROM MIGRATION.LS_OV_HHD_TRAN_MAP m WHERE m.SRC_LREF = d.LREF
);

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_HHD_MSTR_SKIP'); END;
/

-- =============================================================================
-- 5) MIGRATION.LS_READING.READ_NO guncelle (PDML 56)
-- =============================================================================
ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;
ALTER TABLE MIGRATION.LS_READING PARALLEL 56;

PROMPT ========== LS_READING.read_no MERGE ==========
MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(r 56) PARALLEL(m 56) */
 INTO MIGRATION.LS_READING r
USING MIGRATION.LS_OV_HHD_TRAN_MAP m
   ON (r.LREF = m.SRC_LREF)
 WHEN MATCHED THEN UPDATE SET r.READ_NO = m.READ_NO;

COMMIT;

ALTER TABLE MIGRATION.LS_READING NOPARALLEL;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_READING'); END;
/

-- STG_DROP: ara tablolar (MSTR/MAP/SKIP kalir)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_HHD_TRAN_KEY PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR_EOD PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_HHD_MSTR_ORPHAN PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

PROMPT ========== LS_HHD_MSTR CTAS DONE ==========
SELECT 'MSTR_ALL' K, COUNT(*) N FROM MIGRATION.LS_OV_HHD_MSTR
UNION ALL SELECT 'TRAN_MAP', COUNT(*) FROM MIGRATION.LS_OV_HHD_TRAN_MAP
UNION ALL SELECT 'SKIP', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR_SKIP
UNION ALL SELECT 'LS_READING', COUNT(*) FROM MIGRATION.LS_READING
UNION ALL SELECT 'READING_READNO_GT0', COUNT(*) FROM MIGRATION.LS_READING WHERE NVL(READ_NO,0) > 0
UNION ALL SELECT 'SYNTH_ROUTE', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR WHERE NVL(IS_SYNTH,0)=1;
/
