-- =====================================================================================
-- LS_HHD_MSTR_DIAG — calistirmadan once kolon / onkosul + orphan gun grain riski
-- Schema: MIGRATION.LS_READING (+ MIGRATION.LS_OV_HHD_*)
-- =====================================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========== TABLES ==========
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE (OWNER, TABLE_NAME) IN (
        ('MIGRATION','LS_READING'),
        ('SMS','CS_READING_END_OF_DAY'),
        ('MIGRATION','LS_OV_HHD_MSTR')
      )
 ORDER BY 1,2;

PROMPT ========== LS_READING KEY COLS ==========
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_READING'
   AND COLUMN_NAME IN (
        'LREF','READ_NO','LOC_REGION','READ_DATE','READER_PRSNL','READER_PRSNL_ID',
        'ABYS_READING_END_OF_DAY_ID','ABYS_ACCRUE_TYPE_ID','ABYS_NOTE','ABYS_ACCOUNT_ID'
      )
 ORDER BY COLUMN_NAME;

PROMPT ========== CS_READING_END_OF_DAY ALL COLS ==========
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='SMS' AND TABLE_NAME='CS_READING_END_OF_DAY'
 ORDER BY COLUMN_ID;

PROMPT ========== SAMPLE COUNTS ==========
SELECT 'LS_READING' K, COUNT(*) N FROM MIGRATION.LS_READING
UNION ALL SELECT 'EOD', COUNT(*) FROM SMS.CS_READING_END_OF_DAY
UNION ALL SELECT 'RD_EOD_NOT_NULL', COUNT(*) FROM MIGRATION.LS_READING WHERE ABYS_READING_END_OF_DAY_ID IS NOT NULL
UNION ALL SELECT 'RD_KEY_NULL', COUNT(*) FROM MIGRATION.LS_READING
 WHERE LOC_REGION IS NULL OR READ_DATE IS NULL OR READER_PRSNL_ID IS NULL
UNION ALL SELECT 'RD_ORPHAN_CAND', COUNT(*) FROM MIGRATION.LS_READING r
 WHERE r.ABYS_READING_END_OF_DAY_ID IS NULL
    OR NOT EXISTS (
         SELECT 1 FROM SMS.CS_READING_END_OF_DAY e WHERE e.ID = r.ABYS_READING_END_OF_DAY_ID
       );

PROMPT ========== ORPHAN: ayni gun+okuyucu kac farkli saat (v02 risk) ==========
-- CTAS v03 sonrasi bunlar TEK mstr olmali (TRUNC gun)
SELECT *
  FROM (
    SELECT
        CAST(r.LOC_REGION AS NUMBER(10)) AS LOC_REGION,
        TRUNC(r.READ_DATE)               AS READ_DATE_DAY,
        r.READER_PRSNL,
        CAST(r.READER_PRSNL_ID AS NUMBER(10)) AS READER_PRSNL_ID,
        COUNT(*)                         AS DETAY_N,
        COUNT(DISTINCT r.READ_DATE)      AS DISTINCT_TS,
        MIN(r.READ_DATE)                 AS MIN_TS,
        MAX(r.READ_DATE)                 AS MAX_TS
    FROM MIGRATION.LS_READING r
    WHERE r.LOC_REGION IS NOT NULL
      AND r.READ_DATE IS NOT NULL
      AND r.READER_PRSNL_ID IS NOT NULL
      AND (
            r.ABYS_READING_END_OF_DAY_ID IS NULL
         OR NOT EXISTS (
              SELECT 1 FROM SMS.CS_READING_END_OF_DAY e
               WHERE e.ID = r.ABYS_READING_END_OF_DAY_ID
            )
          )
    GROUP BY CAST(r.LOC_REGION AS NUMBER(10)), TRUNC(r.READ_DATE),
             r.READER_PRSNL, CAST(r.READER_PRSNL_ID AS NUMBER(10))
    HAVING COUNT(DISTINCT r.READ_DATE) > 1
    ORDER BY COUNT(DISTINCT r.READ_DATE) DESC
  )
 WHERE ROWNUM <= 30;

PROMPT ========== MSTR (varsa): ORPHAN gun grain kontrol ==========
SELECT COUNT(*) AS ORPHAN_MSTR_N
  FROM MIGRATION.LS_OV_HHD_MSTR
 WHERE HAS_EOD = 0;

SELECT COUNT(*) AS ORPHAN_WITH_TIME
  FROM MIGRATION.LS_OV_HHD_MSTR
 WHERE HAS_EOD = 0
   AND READ_DATE <> TRUNC(READ_DATE);

SELECT COUNT(*) AS ORPHAN_DUP_DAY_READER_ACCRUE
  FROM (
    SELECT READER_REGION, READ_DATE, READER_PRSNL_ID, NVL(READER_PRSNL, CHR(0)),
           NVL(IS_SYNTH, 0), NVL(ABYS_ACCRUE_TYPE_ID, -1)
      FROM MIGRATION.LS_OV_HHD_MSTR
     WHERE HAS_EOD = 0
     GROUP BY READER_REGION, READ_DATE, READER_PRSNL_ID, NVL(READER_PRSNL, CHR(0)),
              NVL(IS_SYNTH, 0), NVL(ABYS_ACCRUE_TYPE_ID, -1)
    HAVING COUNT(*) > 1
  );

PROMPT ========== SYNTH gap spot ==========
SELECT 'SYNTH_READING' K, COUNT(*) N FROM MIGRATION.LS_READING WHERE ABYS_NOTE LIKE 'MIG_SYNTH%'
UNION ALL SELECT 'MSTR_SYNTH', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR WHERE NVL(IS_SYNTH,0)=1
UNION ALL SELECT 'ACCRUE_NULL_ORG', COUNT(*) FROM MIGRATION.LS_READING
 WHERE NVL(ABYS_NOTE,'x') NOT LIKE 'MIG_SYNTH%' AND ABYS_ACCRUE_TYPE_ID IS NULL;
/
