SELECT a.ACCRUE_TYPE_ID, ip.CODE, ipl.VALUE AS gelir_adi,
       COUNT(*) AS adet, SUM(ai.AMOUNT) AS toplam
FROM SMS.CS_ACCOUNT a
JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ACCOUNT_ID = a.ID
JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
JOIN SMS.CS_INCOME_PRM ip ON ip.ID = ai.INCOME_ID
JOIN SMS.CS_INCOME_PRM_LNG ipl ON ipl.PRM_ID = ip.ID AND ipl.LANG_ID = 1
WHERE a.ACCRUE_TYPE_ID IN (5,14)
  AND ip.IS_DEPOSIT = 0
GROUP BY a.ACCRUE_TYPE_ID, ip.CODE, ipl.VALUE
ORDER BY a.ACCRUE_TYPE_ID, adet DESC;


SELECT aa.ACTION_TYPE_ID, atp.CODE, atpl.VALUE AS islem_adi,
       COUNT(*) AS adet, SUM(ai.AMOUNT) AS toplam
FROM SMS.CS_ACCOUNT_INCOME ai
JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ID = ai.ACCOUNT_ACTION_ID
JOIN SMS.CS_ACTION_TYPE_PRM atp ON atp.ID = aa.ACTION_TYPE_ID
JOIN SMS.CS_ACTION_TYPE_PRM_LNG atpl ON atpl.PRM_ID = atp.ID AND atpl.LANG_ID = 1
JOIN SMS.CS_INCOME_PRM ip ON ip.ID = ai.INCOME_ID
WHERE ip.CODE = 'ICFIR'
GROUP BY aa.ACTION_TYPE_ID, atp.CODE, atpl.VALUE
 