-- ADIM 5 gate — Tahsilat overlay (Oracle MIGRATION)
-- Pilot 197168 beklenen: PAY~249 (1 iptal), TAM_HAS_PAY=1, CANCEL_PAY/REV=1
-- Mahsup: LS_OV_MAHSUP_SRC / LS_OV_MAHSUP_CLOSED (CLOSE_KIND, DEP_MAIN_CNT)
-- Log: AYRI script oracleCTAS/LS_TAHSILAT_LOG.sql → LS_OV_TAH_LOG
--      (NO_XREF / PAY_NO_ALLOC / EMANET_CIKIS_* / DEBT_PARTIAL ...)
-- Sert kontroller (sessiz bozulma):
--   PAY_PT cnt = PAY_ALLOC cnt
--   PAY_NO_XREF = 0
--   PAY_MULTI >= 1 (pilotda multi-alloc beklenir; 0 ise alloc regress)

SELECT 'PAY_PT' K, COUNT(*) N FROM MIGRATION.LS_OV_PAY_PT
UNION ALL SELECT 'PAY_OK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_CANC', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=1
UNION ALL SELECT 'PAY_BANK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='PAY' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_MAHSUP', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='MAHSUP' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_NO_XREF', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL
UNION ALL SELECT 'DEBT_PAID', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD
UNION ALL SELECT 'DEBT_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE CLOSED=1
UNION ALL SELECT 'TAM_HAS_PAY', COUNT(*) FROM MIGRATION.LS_OV_TAM_HAS_PAY WHERE VALID_PAY_CNT>0
UNION ALL SELECT 'CANCEL_PAY', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_PAY
UNION ALL SELECT 'CANCEL_REV', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_REV
UNION ALL SELECT 'MAHSUP_SRC', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_SRC
UNION ALL SELECT 'MAHSUP_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED
UNION ALL SELECT 'MAHSUP_ONLY', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE CLOSE_KIND='MAHSUP_ONLY'
UNION ALL SELECT 'MAHSUP_MIXED', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE CLOSE_KIND='MIXED'
UNION ALL SELECT 'MAHSUP_MULTI_DEP', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE DEP_MAIN_CNT > 1
UNION ALL SELECT 'PAY_ALLOC', COUNT(*) FROM MIGRATION.LS_OV_PAY_ALLOC
UNION ALL SELECT 'PAY_MULTI', COUNT(*) FROM (
    SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*) > 1
);

-- Sert: multi-alloc / xref regress (PL/SQL)
DECLARE
  n_pt NUMBER; n_al NUMBER; n_xr NUMBER; n_multi NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_pt FROM MIGRATION.LS_OV_PAY_PT;
  SELECT COUNT(*) INTO n_al FROM MIGRATION.LS_OV_PAY_ALLOC;
  SELECT COUNT(*) INTO n_xr FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL;
  SELECT COUNT(*) INTO n_multi FROM (
    SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*) > 1
  );
  IF n_pt <> n_al THEN
    RAISE_APPLICATION_ERROR(-20051,
      'GATE FAIL: PAY_PT(' || n_pt || ') <> PAY_ALLOC(' || n_al || ')');
  END IF;
  IF n_xr > 0 THEN
    RAISE_APPLICATION_ERROR(-20052,
      'GATE FAIL: PAY_NO_XREF=' || n_xr);
  END IF;
  IF n_multi < 1 THEN
    RAISE_APPLICATION_ERROR(-20053,
      'GATE FAIL: PAY_MULTI=0 (multi-alloc kayboldu?)');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ADIM5 HARD GATE OK pt=' || n_pt || ' multi=' || n_multi);
END;
/

-- Mahsup kapama detay (1 emanet → N fatura)
SELECT c.MAIN_LREF, c.CLOSE_KIND, c.CLOSED, c.MAHSUP_AMT, c.BANK_AMT,
       c.DEP_ACCOUNT_ID, c.DEP_ACTION_ID, c.DEP_MAIN_CNT, c.EXPLAIN_MARK, c.DETAIL
FROM MIGRATION.LS_OV_MAHSUP_CLOSED c
ORDER BY c.DEP_MAIN_CNT DESC, c.DEP_ACCOUNT_ID, c.MAIN_LREF;

-- Ayni emanet hesabindan kapanan faturalar
SELECT s.DEP_ACCOUNT_ID, COUNT(DISTINCT s.MAIN_LREF) MAIN_CNT,
       COUNT(*) MAHSUP_CNT, ROUND(SUM(s.PAYABLETOTAL), 2) AMT,
       LISTAGG(TO_CHAR(s.MAIN_LREF), ',') WITHIN GROUP (ORDER BY s.MAIN_LREF) MAINS
FROM MIGRATION.LS_OV_MAHSUP_SRC s
WHERE s.DEP_ACCOUNT_ID IS NOT NULL
GROUP BY s.DEP_ACCOUNT_ID
HAVING COUNT(DISTINCT s.MAIN_LREF) > 1
ORDER BY MAIN_CNT DESC;

-- Log detay
SELECT LOG_ID, REASON, SEVERITY, PAY_LREF, MAIN_LREF, ACCOUNT_ID,
       ACTION_TYPE_ID, PAYABLETOTAL, PAID_AMT, DETAIL
FROM MIGRATION.LS_OV_TAH_LOG
ORDER BY REASON, LOG_ID;

-- TAM+pay detay
SELECT t.EKS_ACTION_ID, t.MAIN_LREF, t.IADE_LREF, t.VALID_PAY_CNT,
       cp.LREF CANCEL_PAY_LREF, cr.LREF CANCEL_REV_LREF
FROM MIGRATION.LS_OV_TAM_HAS_PAY t
LEFT JOIN MIGRATION.LS_OV_CANCEL_PAY cp ON cp.ABYS_EKS_ACTION_ID = t.EKS_ACTION_ID
LEFT JOIN MIGRATION.LS_OV_CANCEL_REV cr ON cr.ABYS_EKS_ACTION_ID = t.EKS_ACTION_ID
WHERE t.VALID_PAY_CNT > 0;
