-- =============================================================================
-- ADIM 4a gate — Eksilten overlay (Oracle MIGRATION)
-- Beklenen pilot 197168 (onceki Dilim-1): TAM=3, KISMI=1, ASIM=0
-- =============================================================================

SELECT KIND, COUNT(*) CNT
FROM MIGRATION.LS_OV_EKS_CLASS
GROUP BY KIND
ORDER BY 1;

SELECT
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_EKS_CLASS WHERE KIND='TAM' AND MAIN_LREF IS NOT NULL) TAM,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_INVOICE) IADE,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_MAIN_UPD) MAIN_UPD,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_INVLINES) IADE_IL,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_PAYTRANS) IADE_PT,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_KISMI_INVLINES) KISMI_IL,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_KISMI_HDR) KISMI_HDR,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_EKS_SKIP) ASIM_SKIP
FROM DUAL;

-- MAIN_LREF RETURN_TARGET ... dogrulama + IADE alan kontrolu
SELECT m.LREF MAIN_LREF, m.RETURN_TARGET_INVREF, i.LREF IADE_LREF, i.FICHENO,
       i.GRANDTOTAL, i.IOCODE, i.TYPE, i.CANCELED,
       i.ABYS_AGREEMENT_ID, i.CURID, i.FITNO, i.BN_TYPE, i.AMOUNT,
       i.PERIOD, i.HAS_DISCOUNT, i.DISCOUNT_AMOUNT, i.OWNERTYPE
FROM MIGRATION.LS_OV_MAIN_UPD m
JOIN MIGRATION.LS_OV_IADE_INVOICE i ON i.LREF = m.RETURN_TARGET_INVREF
ORDER BY m.LREF;

-- KISMI detay
SELECT LREF, INVOICEREF, TRANSTYPE, AMOUNT, TLTOTAL, TAX, GRANDTOTAL, LINEEXP, ABYS_EKS_ACTION_ID
FROM MIGRATION.LS_OV_KISMI_INVLINES
ORDER BY INVOICEREF, LREF;

SELECT h.LREF MAIN_LREF, m.GRANDTOTAL OLD_GRAND, h.GRANDTOTAL NEW_GRAND,
       h.TLTOTAL, h.TAX, h.PAYABLETOTAL
FROM MIGRATION.LS_OV_KISMI_HDR h
JOIN MIGRATION.LS_INVOICE m ON m.LREF = h.LREF;
