-- ADIM 5 gate FULL — Tahsilat overlay (Oracle MIGRATION)
-- Onkosul: oracleCTAS/prod/04 + 05; canonical runner: prod/06_adim5_tahsilat_gate_full.sql
-- (00_run_all_full.sql zincirinin son adimi)
-- Sert kontroller:
--   PAY_PT cnt = PAY_ALLOC cnt
--   PAY_NO_XREF = 0
-- NOT: PAY_MULTI >= 1 pilot-only (full'da zorunlu degil)

SELECT 'PAY_PT' K, COUNT(*) N FROM MIGRATION.LS_OV_PAY_PT
UNION ALL SELECT 'PAY_OK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_CANC', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=1
UNION ALL SELECT 'PAY_BANK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='PAY' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_MAHSUP', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='MAHSUP' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_NO_XREF', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL
UNION ALL SELECT 'DEBT_PAID', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD
UNION ALL SELECT 'DEBT_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE CLOSED=1
UNION ALL SELECT 'TAM_HAS_PAY', COUNT(*) FROM MIGRATION.LS_OV_TAM_HAS_PAY WHERE VALID_PAY_CNT>0
UNION ALL SELECT 'CANCEL_PAY', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_PAY
UNION ALL SELECT 'CANCEL_REV', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_REV
UNION ALL SELECT 'MAHSUP_SRC', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_SRC
UNION ALL SELECT 'MAHSUP_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED
UNION ALL SELECT 'MAHSUP_ONLY', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE CLOSE_KIND='MAHSUP_ONLY'
UNION ALL SELECT 'MAHSUP_MIXED', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE CLOSE_KIND='MIXED'
UNION ALL SELECT 'MAHSUP_MULTI_DEP', COUNT(*) FROM MIGRATION.LS_OV_MAHSUP_CLOSED WHERE DEP_MAIN_CNT > 1
UNION ALL SELECT 'PAY_ALLOC', COUNT(*) FROM MIGRATION.LS_OV_PAY_ALLOC
UNION ALL SELECT 'PAY_MULTI', COUNT(*) FROM (
    SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*) > 1
);

-- Sert: PT=ALLOC, NO_XREF=0 (PAY_MULTI soft — sadece rapor)
DECLARE
  n_pt NUMBER; n_al NUMBER; n_xr NUMBER; n_multi NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_pt FROM MIGRATION.LS_OV_PAY_PT;
  SELECT COUNT(*) INTO n_al FROM MIGRATION.LS_OV_PAY_ALLOC;
  SELECT COUNT(*) INTO n_xr FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL;
  SELECT COUNT(*) INTO n_multi FROM (
    SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*) > 1
  );
  IF n_pt <> n_al THEN
    RAISE_APPLICATION_ERROR(-20051,
      'GATE FAIL: PAY_PT(' || n_pt || ') <> PAY_ALLOC(' || n_al || ')');
  END IF;
  IF n_xr > 0 THEN
    RAISE_APPLICATION_ERROR(-20052,
      'GATE FAIL: PAY_NO_XREF=' || n_xr);
  END IF;
  DBMS_OUTPUT.PUT_LINE(
    'ADIM5 FULL HARD GATE OK pt=' || n_pt || ' multi=' || n_multi || ' (multi soft)');
END;
/
