-- =====================================================================================
-- İZGAZ (ABYS/Oracle) -> PCMS (MSSQL)  |  PİLOT CTAS + FIFO + RECON  v0.9
-- Ortam : Oracle 11.2.0.3. TEK DOSYA. AGREEMENT_ID sürücülü. TEST ORTAMI.
--
-- v0.7 ÇEKİRDEK DEĞİŞİMİ — YAPISAL BÜTÜNLÜK (income routing yeniden kuruldu):
--  [R20] KALEM FİLTRESİ SIFIR. Her CS_ACCOUNT_INCOME satırı parent action doğasına göre
--        TEK hedefe gider (hardcode INCOME_ID dışlaması YOK):
--          accrue=14 hesap                -> LEDGER (tüm income; emanet referans+girdi/çıktı)
--          accrue!=14 + accrual action    -> INVLINES (tüm gelirler); 958/1929 ayrıca SPEFEE [R35]
--          tahsilat action                -> PAYTRANS_INCOME
--        => kaynak income adedi == hedef satır adedi (958/1929: INVLINES+SPEFEE dual-write [R35]).
--  [R21] VERİ-GÜDÜMLÜ ROUTING: STG_INCOME_ROUTE, CS_INCOME_PRM bayraklarından türer
--        (IS_DEPOSIT/IS_VAT_INCOME/IS_OVERDUE_INCOME/IS_LEGAL_FEE/IS_BALANCE_INCLUDED).
--        Hardcode IN-liste kalktı; tüm income evrenini kapsar.
--  [R22] INVOICE BAŞLIĞI INVLINES'TAN TÜRER: GRANDTOTAL/TAX/TLTOTAL = SUM(satır).
--        Başlık<->satır tanımı gereği tutar => 9.54 tipi fark imkansız.
--  [R23] SPEFEE = devir (958/1929) PCMS tablosu; INVLINEREF=INVLINES.LREF, INVOICEREF=fatura LREF.
--  [R29] DEVIR artık INVLINES satırında (signed); fatura başlığına ayrıca DEVIR_NET eklenmez.
--  [R35] 958/1929 dual-write: INVLINES + SPEFEE; indirim tutarları negatif signed AMOUNT.
--  [R30] INVLINES signed amount; IS_DISCOUNT CS_ACCOUNT_INCOME satırından -> PCMS_TRANSTYPE (807/808).
--  [R31] Tam eksilten: PCMS CreateReverseTransaction (IADE fatura, IOCODE=Alacak, pozitif tutar)
--        + CancelInvoices IADE tahsilat zinciri (CLOSED=0 ise).
--  [R32] Kısmi eksilten: MAIN INVLINES/INVOICE/PAYTRANS rebuild (aynı fatura).
--  [R33] Taksit staging: STG_INSTALLMENT + STG_INSTALLMENT_PLAN + PAYTRANS.INST_NR.
--  [R34] INVOICE EXPLAIN/FITNO/CLIENTREF — PCMS sözleşme tahakkuk açıklaması:
--        "{Tür} Tes.No : {tesisat} Söz.No : {sözleşme} Abn No : {abone}"
--  [R37] Tahsilat signed income: ABYS Gelir Bazlı Rapor AI.AMOUNT*AI.STATUS;
--        PAYTRANS_INCOME + tahsilat INVLINES; PAYABLE=ABS(SUM net).
--  [R38] Tahakkuk ABYS: AI.STATUS*AI.AMOUNT; TYPE IN (1,5); action 41 gecikme iptali;
--        Açık Fatura kıyas R9; R8 PAYED nakit STATUS=1 istisnası.
--  [R39] Mahsup: REF_DEPOSIT_ACCOUNT(_ACTION)_ID hedefli eşleme (570480 FIFO yığılması giderildi);
--        taksit hesapları nested tree'de ACCRUE_TYPE=10 / INSTALLMENT plan.
--  [R41] Tahsilat: tüm gelirler CS_INCOME_PRM üzerinden; borç CROSSREF yalnız ortak gelir varsa.
--  [R42] Tahsilat iptali (ACTION_TYPE=9): aynı makbuzlu ödeme PT CANCELED; PAID'e sayılmaz
--        (ABYS hesapKarti NOT EXISTS — 51407277 PAID_OVERFLOW giderimi).
--  [R43] Tam eksilten + hiç tahsilat yok: MAIN borç sıfır; IADE dökümantasyon (iade tahsilat gerekmez).
--        Tahsilat varsa R31 CancelInvoices IADE tahsilat zinciri devreye girer.
--
--  KORUNAN (v0.6): AGREEMENT-closure[R13], MAHSUP FIFO[R14], CANCEL RETURN çifti[R15],
--    ledger STATUS_NET[R16], KIYAS 121[R17], RECON warn&log severity[R18], V_REF_CHAIN[R19].
--  LREF bantları: INVOICE ana=ACCOUNT.ID; sentetik=500M+ACTION; collection=1.0B+ACTION;
--    ters=1.5B+ACTION. INVLINES accrual=INCOME.ID; collection=1.2B+ACTION. PAYTRANS=ACTION.
--    MSSQL'de DBCC CHECKIDENT reseed ZORUNLU.
-- =====================================================================================

-- 00. TEMİZLİK
BEGIN
  FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
    ('MIG_PARAM','STG_PILOT_ACC','STG_ACTION_MAP','STG_INCOME_ROUTE','STG_EKSILTEN_CLASS',
     'STG_INVOICE','STG_INVLINES','STG_SPEFEE','STG_PAYTRANS','STG_PAYTRANS_INCOME',
     'STG_ADVANCE_LEDGER','STG_ADV_LEDGER_INCOME','STG_MAHSUP_POOL','STG_CANCEL_POOL',
     'STG_DEVIR_NET','STG_INCOME_COVERAGE','STG_RECON_DIFF','STG_INSTALLMENT','STG_INSTALLMENT_PLAN',
     'STG_EKSILTEN_ADJ','STG_AGR_CONTEXT','MIG_UNMAPPED','MIG_SKIPPED'))
  LOOP EXECUTE IMMEDIATE 'DROP TABLE '||T.TABLE_NAME||' PURGE'; END LOOP;
  FOR V IN (SELECT VIEW_NAME FROM USER_VIEWS WHERE VIEW_NAME='V_REF_CHAIN')
  LOOP EXECUTE IMMEDIATE 'DROP VIEW '||V.VIEW_NAME; END LOOP;
END;
/

-- 01. PARAMETRE — REG_ID veya AGR_ID (biri dolu; full run için tablo bos)
CREATE TABLE MIG_PARAM (REG_ID NUMBER(12), AGR_ID NUMBER(12));
INSERT INTO MIG_PARAM (AGR_ID) VALUES (197168);
COMMIT;

-- 02. STG_PILOT_ACC — AGREEMENT-CLOSURE [R13]
CREATE TABLE STG_PILOT_ACC NOLOGGING AS
SELECT A.ID, A.REGISTER_ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID, A.PERIOD,
       A.TOTAL_DEBT, A.TOTAL_CREDIT,
       CASE WHEN EXISTS (SELECT 1 FROM SMS.CS_ACCOUNT_ACTION X
                          WHERE X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=1) THEN 'A' ELSE 'B' END SINIF
  FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID IN (
        SELECT DISTINCT A2.AGREEMENT_ID FROM SMS.CS_ACCOUNT A2
         WHERE NOT EXISTS (SELECT 1 FROM MIG_PARAM)
            OR A2.AGREEMENT_ID IN (SELECT P.AGR_ID FROM MIG_PARAM P WHERE P.AGR_ID IS NOT NULL)
            OR A2.REGISTER_ID IN (SELECT P.REG_ID FROM MIG_PARAM P WHERE P.REG_ID IS NOT NULL));
CREATE UNIQUE INDEX IX_STG_PACC ON STG_PILOT_ACC (ID);
CREATE INDEX IX_STG_PACC_AGR ON STG_PILOT_ACC (AGREEMENT_ID);
CREATE INDEX IX_STG_PACC_S ON STG_PILOT_ACC (SINIF, ACCRUE_TYPE_ID);

DECLARE V_N NUMBER; BEGIN
  SELECT COUNT(*) INTO V_N FROM STG_PILOT_ACC;
  IF V_N=0 THEN RAISE_APPLICATION_ERROR(-20001,'STG_PILOT_ACC BOS: MIG_PARAM REG_ID/AGR_ID cozmuyor.'); END IF;
END;
/

SELECT CASE WHEN AGREEMENT_ID IN (SELECT AGR_ID FROM MIG_PARAM WHERE AGR_ID IS NOT NULL) THEN 'SECILI_SOZLESME'
            WHEN REGISTER_ID IN (SELECT REG_ID FROM MIG_PARAM WHERE REG_ID IS NOT NULL) THEN 'SECILI_REGISTER'
            WHEN NOT EXISTS (SELECT 1 FROM MIG_PARAM) THEN 'FULL'
            ELSE 'SOZLESME_CLOSURE' END KAYNAK,
       COUNT(*) HESAP, COUNT(DISTINCT AGREEMENT_ID) SOZLESME, COUNT(DISTINCT REGISTER_ID) REGISTER
  FROM STG_PILOT_ACC
 GROUP BY CASE WHEN AGREEMENT_ID IN (SELECT AGR_ID FROM MIG_PARAM WHERE AGR_ID IS NOT NULL) THEN 'SECILI_SOZLESME'
               WHEN REGISTER_ID IN (SELECT REG_ID FROM MIG_PARAM WHERE REG_ID IS NOT NULL) THEN 'SECILI_REGISTER'
               WHEN NOT EXISTS (SELECT 1 FROM MIG_PARAM) THEN 'FULL'
               ELSE 'SOZLESME_CLOSURE' END;

-- 02b. STG_AGR_CONTEXT [R34] — tesisat no / abone / sözleşme (PCMS EXPLAIN alanları)
CREATE TABLE STG_AGR_CONTEXT NOLOGGING AS
SELECT DISTINCT P.AGREEMENT_ID,
       P.REGISTER_ID CLIENTREF,
       P.AGREEMENT_ID OWNERREF,
       (SELECT I.INSTALLATION_NUMBER
          FROM SMS.CS_AGREEMENT AG
          JOIN SMS.CS_INSTALLATION I ON I.ID = AG.INSTALLATION_ID
         WHERE AG.ID = P.AGREEMENT_ID) FITNO
  FROM STG_PILOT_ACC P;
CREATE UNIQUE INDEX IX_STG_AGR_CTX ON STG_AGR_CONTEXT (AGREEMENT_ID);

-- 03. ACTION MAP
CREATE TABLE STG_ACTION_MAP NOLOGGING AS
SELECT ID ACTION_TYPE_ID, TYPE ACTION_CLASS, STATUS,
       CASE WHEN STATUS=1 THEN 0 ELSE 1 END IOCODE FROM SMS.CS_ACTION_TYPE_PRM;

-- 04. LOG
CREATE TABLE MIG_UNMAPPED (KAYNAK VARCHAR2(30), SRC_ID NUMBER(12), SRC_KEY NUMBER(12),
  ACIKLAMA VARCHAR2(200), ADET NUMBER(12), TUTAR NUMBER(19,4));
CREATE TABLE MIG_SKIPPED (KAYNAK VARCHAR2(30), ACCOUNT_ID NUMBER(12), ACTION_ID NUMBER(12),
  ACTION_TYPE NUMBER(6), SEBEP VARCHAR2(200));

-- 04b. STG_INCOME_ROUTE [R21] — VERİ-GÜDÜMLÜ ROUTING (CS_INCOME_PRM bayrakları)
--      IS_DISCOUNT gelir tanımında değil; CS_ACCOUNT_INCOME satırında (R30).
CREATE TABLE STG_INCOME_ROUTE NOLOGGING AS
SELECT ID INCOME_ID,
       CODE INCOME_CODE,
       NVL(IS_DEPOSIT,0) IS_DEPOSIT, NVL(IS_VAT_INCOME,0) IS_VAT_INCOME,
       NVL(IS_OVERDUE_INCOME,0) IS_OVERDUE_INCOME, NVL(IS_LEGAL_FEE,0) IS_LEGAL_FEE,
       NVL(IS_LEGAL_EXPENSE,0) IS_LEGAL_EXPENSE, NVL(IS_BALANCE_INCLUDED,0) IS_BALANCE_INCLUDED,
       OVERDUE_INCOME_ID, VAT_INCOME_ID, INCOME_TYPE,
       'INVLINES' ACCRUAL_DEST,
       ID PCMS_TRANSTYPE
  FROM SMS.CS_INCOME_PRM;
CREATE UNIQUE INDEX IX_INCROUTE ON STG_INCOME_ROUTE (INCOME_ID);

-- 04c. STG_EKSILTEN_CLASS [R1]
CREATE TABLE STG_EKSILTEN_CLASS NOLOGGING AS
SELECT E.ID ACTION_ID, E.ACCOUNT_ID, E.ACTION_DATE, EKS.TUT EKS, NVL(TAH.TUT,0) TAH,
       CASE WHEN EKS.TUT > NVL(TAH.TUT,0)+0.01 THEN 'ASIM'
            WHEN EKS.TUT >= NVL(TAH.TUT,0)*0.995 THEN 'TAM' ELSE 'KISMI' END KIND
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION E ON E.ACCOUNT_ID=A.ID AND E.ACTION_TYPE_ID=2
  JOIN (SELECT ACCOUNT_ACTION_ID,SUM(ABS(AMOUNT)) TUT FROM SMS.CS_ACCOUNT_INCOME GROUP BY ACCOUNT_ACTION_ID) EKS
    ON EKS.ACCOUNT_ACTION_ID=E.ID
  LEFT JOIN (SELECT X.ACCOUNT_ID,SUM(ABS(I.AMOUNT)) TUT FROM SMS.CS_ACCOUNT_ACTION X
               JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
              WHERE X.ACTION_TYPE_ID=1 GROUP BY X.ACCOUNT_ID) TAH ON TAH.ACCOUNT_ID=E.ACCOUNT_ID
 WHERE A.SINIF='A';
CREATE INDEX IX_EKS_ACC ON STG_EKSILTEN_CLASS (ACCOUNT_ID, KIND);
CREATE INDEX IX_EKS_ACT ON STG_EKSILTEN_CLASS (ACTION_ID);
INSERT INTO MIG_SKIPPED SELECT 'EKS_TAH_ASIMI',ACCOUNT_ID,ACTION_ID,2,
  'EKS>TAH' FROM STG_EKSILTEN_CLASS WHERE KIND='ASIM';
COMMIT;

-- 05. STG_INVLINES [R20][R30][R35][R38] — ABYS Tahakkuk Gelir: AI.STATUS*AI.AMOUNT
CREATE TABLE STG_INVLINES NOLOGGING AS
SELECT I.ID LREF,
       CASE WHEN X.ACTION_TYPE_ID=1 THEN A.ID ELSE 500000000+X.ID END INVOICEREF,
       CASE WHEN NVL(I.IS_DISCOUNT,0)=1 THEN 103 ELSE 119 END LINE_TYPE,
       CASE WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=939 THEN 807
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=7658 THEN 808
            ELSE NVL(R.PCMS_TRANSTYPE, I.INCOME_ID) END TRANSTYPE,
       I.AMOUNT*I.STATUS AMOUNT,
       R.IS_VAT_INCOME, R.IS_DEPOSIT, R.IS_OVERDUE_INCOME, R.IS_LEGAL_FEE, NVL(I.IS_DISCOUNT,0) IS_DISCOUNT,
       A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       I.INCOME_ID SRC_INCOME_ID, I.ID SOURCE_ORACLE_INCOME_ID,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID,
       0 CANCELED,
       CASE WHEN I.INCOME_ID=958 THEN 'SONRAKI AYA DEVIR'
            WHEN I.INCOME_ID=1929 THEN 'ONCEKI AYDAN DEVIR'
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=939 THEN 'Gaz Bedeli Indirim'
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=7658 THEN 'SKB Bedeli Indirim'
            ELSE NULL END LINEEXP
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (1,3,10,41)
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID AND M.ACTION_CLASS IN (1,5)
 WHERE A.ACCRUE_TYPE_ID <> 14
   AND R.ACCRUAL_DEST = 'INVLINES'
UNION ALL
SELECT 1200000000+V.SOURCE_ORACLE_ACTION_ID, V.LREF, 101, 173, V.GRANDTOTAL,
       0,0,0,0,0, V.SRC_ACCRUE_TYPE, -1, 1200000000+V.SOURCE_ORACLE_ACTION_ID,
       V.SOURCE_ORACLE_ACCOUNT_ID, V.SOURCE_ORACLE_ACTION_ID, 0, NULL
  FROM (SELECT 1 LREF, 0 GRANDTOTAL, 0 SRC_ACCRUE_TYPE, 0 SOURCE_ORACLE_ACCOUNT_ID,
               0 SOURCE_ORACLE_ACTION_ID FROM DUAL WHERE 1=0) V;
CREATE INDEX IX_STG_IL ON STG_INVLINES (INVOICEREF);
CREATE INDEX IX_STG_IL_SRC ON STG_INVLINES (SOURCE_ORACLE_INCOME_ID);
ALTER TABLE STG_INVLINES MODIFY (LINEEXP VARCHAR2(100));

-- 06. STG_INVOICE [R22] — iskelet (accrual action'lar) + başlık INVLINES'tan türer + [R24][R25]
CREATE TABLE STG_INVOICE NOLOGGING AS
SELECT KEYS.LREF, KEYS.INV_KIND, KEYS.SOURCE_ORACLE_ACCOUNT_ID, KEYS.SOURCE_ORACLE_ACTION_ID,
       KEYS.SRC_REGISTER_ID, KEYS.SRC_AGREEMENT_ID, KEYS.SRC_ACCRUE_TYPE, KEYS.DATE_,
       KEYS.LEGAL_PROCEEDING_ID LAWDETAILREF,                       -- [R24]
       NVL(AGG.TL,0) TLTOTAL, NVL(AGG.VAT,0) TAX, NVL(AGG.TL,0)+NVL(AGG.VAT,0) GRANDTOTAL,
       NVL(AGG.TL,0)+NVL(AGG.VAT,0) PAYABLETOTAL,
       CASE WHEN AGG.HAS_GAZ=0 AND AGG.HAS_GUV>0 THEN 109
            WHEN KEYS.SRC_ACCRUE_TYPE=443 THEN 121 ELSE 119 END INV_TYPE,
       0 IOCODE, 0 CANCELED, 0 CLOSED,
       CAST(NULL AS NUMBER(12)) RETURN_SOURCE_INVREF, CAST(NULL AS NUMBER(12)) RETURN_TARGET_INVREF,
       CAST(NULL AS NUMBER(12)) INVOICECROSSREF,                    -- [R25]
       CAST(NULL AS NUMBER(12)) LINKED_SOURCE_INVREF
  FROM (
     SELECT A.ID LREF, 'MAIN' INV_KIND, A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID,
            A.REGISTER_ID SRC_REGISTER_ID, A.AGREEMENT_ID SRC_AGREEMENT_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
            CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END DATE_,
            X.LEGAL_PROCEEDING_ID
       FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=1
      WHERE A.ACCRUE_TYPE_ID<>14
     UNION ALL
     SELECT 500000000+X.ID, DECODE(X.ACTION_TYPE_ID,3,'ARTTIRAN','GECIKME'), A.ID, X.ID,
            A.REGISTER_ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID,
            CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
            X.LEGAL_PROCEEDING_ID
       FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (3,10,41)
      WHERE (A.ACCRUE_TYPE_ID<>14 OR A.ACCRUE_TYPE_ID IN (8,10))
  ) KEYS
  LEFT JOIN (
     SELECT INVOICEREF,
            SUM(CASE WHEN IS_VAT_INCOME=1 THEN 0 ELSE AMOUNT END) TL,
            SUM(CASE WHEN IS_VAT_INCOME=1 THEN AMOUNT ELSE 0 END) VAT,
            SUM(CASE WHEN TRANSTYPE IN (939,7658,807,808) THEN 1 ELSE 0 END) HAS_GAZ,
            SUM(CASE WHEN IS_DEPOSIT=1 THEN 1 ELSE 0 END) HAS_GUV
       FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1 AND NVL(CANCELED,0)=0 GROUP BY INVOICEREF
  ) AGG ON AGG.INVOICEREF = KEYS.LREF;
CREATE UNIQUE INDEX IX_STG_INV ON STG_INVOICE (LREF);
CREATE INDEX IX_STG_INV_SRC ON STG_INVOICE (SOURCE_ORACLE_ACTION_ID);
CREATE INDEX IX_STG_INV_AGR ON STG_INVOICE (SRC_AGREEMENT_ID);
CREATE INDEX IX_STG_INV_KIND ON STG_INVOICE (INV_KIND);
ALTER TABLE STG_INVOICE ADD (
  FITNO NUMBER(12),
  CLIENTREF NUMBER(12),
  OWNERREF NUMBER(12),
  OWNERTYPE NUMBER(6) DEFAULT 91,
  EXPLAIN VARCHAR2(200)
);

-- 07. STG_SPEFEE [R23][R35] — devir 958/1929; INVLINEREF=INVLINES.LREF, INVOICEREF=fatura LREF
CREATE TABLE STG_SPEFEE NOLOGGING AS
SELECT I.ID LREF, 6 STYPE,
       CASE WHEN I.INCOME_ID=958 THEN 'SONRAKI AYA DEVIR' ELSE 'ONCEKI AYDAN DEVIR' END LINEEXP,
       CASE WHEN X.ACTION_TYPE_ID=1 THEN A.ID ELSE 500000000+X.ID END INVOICEREF,
       I.ID INVLINEREF,
       A.AGREEMENT_ID CLIENTREF, A.AGREEMENT_ID OWNERREF, 91 CLIENTTYPE,
       ABS(I.AMOUNT) TLTOTAL, 0 TAX, ABS(I.AMOUNT) GRANDTOTAL,
       0 CANCELLED, 2 STATUS,
       I.INCOME_ID SRC_INCOME_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID, I.ID SOURCE_ORACLE_INCOME_ID
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (1,3,10,41)
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
 WHERE A.ACCRUE_TYPE_ID<>14 AND I.INCOME_ID IN (958,1929);
CREATE INDEX IX_STG_SP_SRC ON STG_SPEFEE (SOURCE_ORACLE_INCOME_ID);
CREATE INDEX IX_STG_SP_IL ON STG_SPEFEE (INVLINEREF);

-- 07b. STG_DEVIR_NET [R29] — tanı/doğrulama (fatura başlığına artık eklenmez; devir INVLINES'ta)
CREATE TABLE STG_DEVIR_NET NOLOGGING AS
SELECT X.ID SOURCE_ORACLE_ACTION_ID, A.ID SOURCE_ORACLE_ACCOUNT_ID,
       SUM(CASE WHEN I.INCOME_ID=958 THEN ABS(I.AMOUNT)
                WHEN I.INCOME_ID=1929 THEN -ABS(I.AMOUNT) ELSE 0 END) DEVIR_NET
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (1,3,10,41)
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID AND I.INCOME_ID IN (958,1929)
 WHERE A.ACCRUE_TYPE_ID<>14
 GROUP BY X.ID, A.ID;
CREATE INDEX IX_STG_DEVIR_ACT ON STG_DEVIR_NET (SOURCE_ORACLE_ACTION_ID);

-- [R35] Devir artık INVLINES'ta; DEVIR_NET fatura başlığına çift sayım yapmaması için eklenmez.

-- 08. STG_PAYTRANS  (a)borç PT (b)tahsilat class=2 (c)type-12 mahsup
-- [R41] CROSSREF/PAID: ödeme action'ı tahakkuk action ile ortak INCOME_ID paylaşıyorsa borca bağlanır
--        (tüm gelirler CS_INCOME_PRM'den; ortak gelir yoksa CROSSREF NULL, PAID sayılmaz)
CREATE TABLE STG_PAYTRANS NOLOGGING AS
SELECT V.SOURCE_ORACLE_ACTION_ID LREF, V.LREF INVOICEREF, V.INV_TYPE PT_TYPE, V.IOCODE,
       CAST(NULL AS NUMBER(12)) CROSSREF, CAST(NULL AS NUMBER(6)) PAYTYPE,
       CAST(NULL AS NUMBER(12)) INVLINEREF, 0 INST_NR, V.DATE_, V.PAYABLETOTAL, 0 PAID,
       0 CANCELED, 'ACCRUE' PT_KIND, CAST(NULL AS NUMBER(6)) SRC_ACTION_TYPE,
       V.SRC_ACCRUE_TYPE, V.SOURCE_ORACLE_ACCOUNT_ID, V.SOURCE_ORACLE_ACTION_ID,
       0 CANCELLATIONPAYMENT, CAST(NULL AS NUMBER(12)) INSTALLMENT_ID
  FROM STG_INVOICE V
 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')
UNION ALL
SELECT X.ID, 1000000000+X.ID, 101, M.IOCODE,
       (SELECT MIN(G.ID) KEEP (DENSE_RANK FIRST ORDER BY
                 CASE WHEN G.ACTION_DATE<=X.ACTION_DATE THEN 0 ELSE 1 END, G.ACTION_DATE DESC, G.ID DESC)
          FROM SMS.CS_ACCOUNT_ACTION G
         WHERE G.ACCOUNT_ID=A.ID AND G.ACTION_TYPE_ID IN (1,3,10,41)
           AND EXISTS (SELECT 1
                         FROM SMS.CS_ACCOUNT_INCOME PI
                         JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.INCOME_ID=PI.INCOME_ID
                        WHERE PI.ACCOUNT_ACTION_ID=X.ID
                          AND AI.ACCOUNT_ACTION_ID=G.ID)) CROSSREF,
       CASE X.ACTION_TYPE_ID WHEN 4 THEN 32 WHEN 5 THEN 33 WHEN 6 THEN 10 ELSE 174 END,
       1200000000+X.ID, NVL(X.INSTALLMENT_ORDER_NUMBER,0),
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
       (SELECT ABS(SUM(I.AMOUNT*I.STATUS))
          FROM SMS.CS_ACCOUNT_INCOME I
         WHERE I.ACCOUNT_ACTION_ID=X.ID),
       0,0,'PAYMENT', X.ACTION_TYPE_ID, A.ACCRUE_TYPE_ID, A.ID, X.ID,
       0, X.INSTALLMENT_ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID AND M.ACTION_CLASS=2
 WHERE A.ACCRUE_TYPE_ID<>14
UNION ALL
-- Type-12 seed CROSSREF: REF tahakkuk action (PT LREF=action id) [R39]
SELECT X.ID, 1000000000+X.ID, 101, 1,
       NVL(X.REF_DEPOSIT_ACCOUNT_ACTION_ID,
           NVL((SELECT MIN(G.ID) KEEP (DENSE_RANK FIRST ORDER BY G.ACTION_DATE, G.ID)
                  FROM SMS.CS_ACCOUNT_ACTION G
                 WHERE G.ACCOUNT_ID=X.REF_DEPOSIT_ACCOUNT_ID
                   AND G.ACTION_TYPE_ID IN (1,3,10,41)),
               (SELECT MIN(G.ID) KEEP (DENSE_RANK FIRST ORDER BY G.ACTION_DATE, G.ID)
                  FROM SMS.CS_ACCOUNT_ACTION G JOIN STG_PILOT_ACC A2 ON A2.ID=G.ACCOUNT_ID
                 WHERE A2.AGREEMENT_ID=A.AGREEMENT_ID AND G.ACTION_TYPE_ID IN (1,3,10,41)))) CROSSREF,
       10, 1200000000+X.ID, NVL(X.INSTALLMENT_ORDER_NUMBER,0),
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
       (SELECT ABS(SUM(I.AMOUNT*I.STATUS))
          FROM SMS.CS_ACCOUNT_INCOME I
         WHERE I.ACCOUNT_ACTION_ID=X.ID),
       0,0,'PAYMENT', 12, A.ACCRUE_TYPE_ID, A.ID, X.ID,
       0, X.INSTALLMENT_ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
 WHERE A.ACCRUE_TYPE_ID<>14;
CREATE INDEX IX_STG_PT ON STG_PAYTRANS (INVOICEREF);
CREATE INDEX IX_STG_PT_SRC ON STG_PAYTRANS (SOURCE_ORACLE_ACTION_ID);
CREATE INDEX IX_STG_PT_CROSS ON STG_PAYTRANS (CROSSREF);
CREATE INDEX IX_STG_PT_KIND ON STG_PAYTRANS (PT_KIND);

-- collection INVOICE + INVLINES özet (tahsilat + type-12)
INSERT INTO STG_INVOICE (LREF,INV_KIND,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_REGISTER_ID,
       SRC_AGREEMENT_ID,SRC_ACCRUE_TYPE,DATE_,LAWDETAILREF,TLTOTAL,TAX,GRANDTOTAL,PAYABLETOTAL,INV_TYPE,
       IOCODE,CANCELED,CLOSED,RETURN_SOURCE_INVREF,RETURN_TARGET_INVREF,INVOICECROSSREF,LINKED_SOURCE_INVREF)
SELECT 1000000000+P.SOURCE_ORACLE_ACTION_ID,'TAHSILAT',P.SOURCE_ORACLE_ACCOUNT_ID,P.SOURCE_ORACLE_ACTION_ID,
       A.REGISTER_ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,P.DATE_,NULL,
       P.PAYABLETOTAL,0,P.PAYABLETOTAL,P.PAYABLETOTAL,101,1,0,1,
       NULL,NULL,P.CROSSREF,NULL              -- [R25] INVOICECROSSREF=borç PT
  FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
 WHERE P.PT_KIND='PAYMENT';
-- [R37] Tahsilat INVLINES — tüm gelir satırları (CS_INCOME_PRM / STG_INCOME_ROUTE)
INSERT INTO STG_INVLINES (LREF,INVOICEREF,LINE_TYPE,TRANSTYPE,AMOUNT,IS_VAT_INCOME,IS_DEPOSIT,
       IS_OVERDUE_INCOME,IS_LEGAL_FEE,IS_DISCOUNT,SRC_ACCRUE_TYPE,SRC_INCOME_ID,SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,CANCELED,LINEEXP)
SELECT 1200000000+P.SOURCE_ORACLE_ACTION_ID + ROW_NUMBER() OVER (PARTITION BY P.LREF ORDER BY I.ID),
       1000000000+P.SOURCE_ORACLE_ACTION_ID,
       101, NVL(R.PCMS_TRANSTYPE, I.INCOME_ID),
       I.AMOUNT*I.STATUS,
       R.IS_VAT_INCOME, R.IS_DEPOSIT, R.IS_OVERDUE_INCOME, R.IS_LEGAL_FEE, NVL(I.IS_DISCOUNT,0),
       P.SRC_ACCRUE_TYPE, I.INCOME_ID, I.ID,
       P.SOURCE_ORACLE_ACCOUNT_ID, P.SOURCE_ORACLE_ACTION_ID, 0,
       CASE WHEN I.INCOME_ID=958 THEN 'SONRAKI AYA DEVIR'
            WHEN I.INCOME_ID=1929 THEN 'ONCEKI AYDAN DEVIR' ELSE NULL END
  FROM STG_PAYTRANS P
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=P.SOURCE_ORACLE_ACTION_ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
 WHERE P.PT_KIND='PAYMENT';
COMMIT;

-- 09. STG_PAYTRANS_INCOME [R20][R37] — ABYS: AI.AMOUNT*AI.STATUS (tüm gelirler)
CREATE TABLE STG_PAYTRANS_INCOME NOLOGGING AS
SELECT I.ID LREF, P.LREF PAYTRANSREF,
       ROW_NUMBER() OVER (PARTITION BY P.LREF ORDER BY I.ID) LINENR,
       NVL((SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACTION_ID=P.CROSSREF AND ROWNUM=1),P.CROSSREF) DEBT_INVOICEREF,
       P.CROSSREF DEBT_PAYTRANSREF, I.AMOUNT*I.STATUS INCOME_AMOUNT,
       I.INCOME_ID SRC_INCOME_ID, P.SRC_ACCRUE_TYPE, I.ID SOURCE_ORACLE_INCOME_ID,
       P.SOURCE_ORACLE_ACCOUNT_ID, P.SOURCE_ORACLE_ACTION_ID
  FROM STG_PAYTRANS P
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=P.SOURCE_ORACLE_ACTION_ID
 WHERE P.PT_KIND='PAYMENT';
CREATE INDEX IX_STG_PI ON STG_PAYTRANS_INCOME (PAYTRANSREF);
CREATE INDEX IX_STG_PI_SRC ON STG_PAYTRANS_INCOME (SOURCE_ORACLE_INCOME_ID);

-- [R42] Tahsilat iptali — makbuz/vezne/gün eşleşen ödeme geçersiz (hesapKarti NOT EXISTS)
UPDATE STG_PAYTRANS P SET P.CANCELED = 1
 WHERE P.PT_KIND = 'PAYMENT' AND NVL(P.CANCELED, 0) = 0
   AND EXISTS (
     SELECT 1
       FROM SMS.CS_ACCOUNT_ACTION PAY
       JOIN SMS.CS_ACCOUNT_ACTION CAN ON CAN.ACCOUNT_ID = PAY.ACCOUNT_ID
        AND CAN.ACTION_TYPE_ID = 9
        AND CAN.CASH_ID = PAY.CASH_ID
        AND CAN.RECEIPT_NUMBER = PAY.RECEIPT_NUMBER
        AND NVL(CAN.BANK_PAYMENT_DATE, DATE '1900-01-01') = NVL(PAY.BANK_PAYMENT_DATE, DATE '1900-01-01')
      WHERE PAY.ID = P.SOURCE_ORACLE_ACTION_ID);
COMMIT;
UPDATE STG_INVOICE V SET V.CANCELED = 1, V.CLOSED = 0
 WHERE V.INV_KIND = 'TAHSILAT'
   AND EXISTS (
     SELECT 1 FROM STG_PAYTRANS P
      WHERE P.SOURCE_ORACLE_ACTION_ID = V.SOURCE_ORACLE_ACTION_ID
        AND P.PT_KIND = 'PAYMENT' AND NVL(P.CANCELED, 0) = 1);
COMMIT;

UPDATE STG_PAYTRANS D SET D.PAID=NVL((SELECT SUM(C.PAYABLETOTAL) FROM STG_PAYTRANS C
    WHERE C.PT_KIND='PAYMENT' AND C.IOCODE=1 AND C.CROSSREF=D.LREF AND NVL(C.CANCELED,0)=0),0) WHERE D.PT_KIND='ACCRUE'; COMMIT;
UPDATE STG_INVOICE V SET V.CLOSED=1 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')
   AND EXISTS (SELECT 1 FROM STG_PAYTRANS P WHERE P.INVOICEREF=V.LREF AND P.PT_KIND='ACCRUE'
                AND P.PAID>=P.PAYABLETOTAL-0.01 AND P.PAYABLETOTAL>0); COMMIT;

INSERT INTO MIG_SKIPPED SELECT 'CANCEL_SINIFI',X.ACCOUNT_ID,X.ID,X.ACTION_TYPE_ID,'CANCEL_*'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE M.ACTION_CLASS IN (4,8) AND A.ACCRUE_TYPE_ID<>14;
COMMIT;

-- 10. STG_ADVANCE_LEDGER (accrue=14 hesap -> TÜM income LEDGER) [R16][R20]
CREATE TABLE STG_ADVANCE_LEDGER NOLOGGING AS
SELECT X.ID LREF, A.REGISTER_ID SRC_REGISTER_ID, A.AGREEMENT_ID SRC_AGREEMENT_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       CASE WHEN X.ACTION_TYPE_ID IN (20,48,36,39,44) THEN 1 ELSE 2 END DIRECTION,
       SUM(ABS(I.AMOUNT)) AMOUNT, SUM(I.AMOUNT*M.STATUS) STATUS_NET,
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(MIN(X.ACTION_DATE),24000) ELSE MIN(X.ACTION_DATE) END TRANS_DATE,
       X.ACTION_CAUSE_ID CAUSE_CODE, X.ACTION_TYPE_ID SOURCE_ACTION_TYPE,
       X.REF_DEPOSIT_ACCOUNT_ID REF_ACC_ID, X.REF_DEPOSIT_ACCOUNT_ACTION_ID REF_ACT_ID,
       CAST(NULL AS NUMBER(12)) PARENT_LREF, 0 CANCELED,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE A.ACCRUE_TYPE_ID=14
 GROUP BY X.ID,A.ID,A.REGISTER_ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,X.ACTION_TYPE_ID,X.ACTION_CAUSE_ID,
          X.ACTION_DATE,X.REF_DEPOSIT_ACCOUNT_ID,X.REF_DEPOSIT_ACCOUNT_ACTION_ID;
CREATE INDEX IX_STG_LED ON STG_ADVANCE_LEDGER (SOURCE_ORACLE_ACCOUNT_ID, DIRECTION);
CREATE INDEX IX_STG_LED_ACT ON STG_ADVANCE_LEDGER (SOURCE_ORACLE_ACTION_ID);

UPDATE STG_ADVANCE_LEDGER C SET C.PARENT_LREF=(SELECT MAX(G.LREF) FROM STG_ADVANCE_LEDGER G
    WHERE G.SOURCE_ORACLE_ACCOUNT_ID=C.SOURCE_ORACLE_ACCOUNT_ID AND G.DIRECTION=1)
 WHERE C.DIRECTION=2 AND 1=(SELECT COUNT(*) FROM STG_ADVANCE_LEDGER G2
    WHERE G2.SOURCE_ORACLE_ACCOUNT_ID=C.SOURCE_ORACLE_ACCOUNT_ID AND G2.DIRECTION=1); COMMIT;

CREATE TABLE STG_ADV_LEDGER_INCOME NOLOGGING AS
SELECT I.ID LREF, L.LREF LEDGER_LREF, L.DIRECTION, I.INCOME_ID SRC_INCOME_ID, ABS(I.AMOUNT) AMOUNT,
       L.SRC_ACCRUE_TYPE, L.SOURCE_ORACLE_ACCOUNT_ID, L.SOURCE_ORACLE_ACTION_ID, I.ID SOURCE_ORACLE_INCOME_ID
  FROM STG_ADVANCE_LEDGER L JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=L.SOURCE_ORACLE_ACTION_ID;
CREATE INDEX IX_STG_LI_SRC ON STG_ADV_LEDGER_INCOME (SOURCE_ORACLE_INCOME_ID);
CREATE INDEX IX_STG_LI_LED ON STG_ADV_LEDGER_INCOME (LEDGER_LREF);

-- 11. STG_MAHSUP_POOL [R14][R39] — önce REF_DEPOSIT hedefi; yoksa sözleşme-içi FIFO
-- ABYS: EMANET ÇIKIŞI.REF_DEPOSIT_ACCOUNT_ID = referans tahakkuk hesabı (ekranda "Referans Tahakkuk")
CREATE TABLE STG_MAHSUP_POOL NOLOGGING AS
SELECT A.AGREEMENT_ID, X.ACCOUNT_ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID,
       A.ACCRUE_TYPE_ID MAH_ACCRUE_TYPE,
       NVL((SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),0) MAHSUP_TUTAR,
       D.SOURCE_ORACLE_ACCOUNT_ID TARGET_ACCOUNT_ID,
       D.SOURCE_ORACLE_ACTION_ID TARGET_DEBT_ACTION_ID,
       D.LREF TARGET_DEBT_PT,
       NVL((SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),0) PAY_APPLIED,
       CAST('ESLESTI' AS VARCHAR2(20)) DURUM
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
  JOIN STG_PAYTRANS D ON D.PT_KIND='ACCRUE' AND NVL(D.CANCELED,0)=0
   AND (
         (X.REF_DEPOSIT_ACCOUNT_ACTION_ID IS NOT NULL
          AND D.SOURCE_ORACLE_ACTION_ID=X.REF_DEPOSIT_ACCOUNT_ACTION_ID)
      OR (X.REF_DEPOSIT_ACCOUNT_ACTION_ID IS NULL
          AND X.REF_DEPOSIT_ACCOUNT_ID IS NOT NULL
          AND D.SOURCE_ORACLE_ACCOUNT_ID=X.REF_DEPOSIT_ACCOUNT_ID
          AND D.LREF = (
                SELECT MIN(P2.LREF) KEEP (DENSE_RANK FIRST ORDER BY P2.DATE_, P2.LREF)
                  FROM STG_PAYTRANS P2
                 WHERE P2.PT_KIND='ACCRUE' AND NVL(P2.CANCELED,0)=0
                   AND P2.SOURCE_ORACLE_ACCOUNT_ID=X.REF_DEPOSIT_ACCOUNT_ID))
       )
 WHERE A.ACCRUE_TYPE_ID<>14;

-- REF yok: kalanı sözleşme-içi FIFO ile dağıt (REF dolu ama PT yoksa HEDEF_YOK — yanlış hesaba yığma)
INSERT INTO STG_MAHSUP_POOL
SELECT M.AGREEMENT_ID, M.MAH_ACC, M.MAH_ACTION, M.ACCRUE_TYPE_ID, M.TUT,
       B.DEBT_ACC, B.DEBT_ACTION, B.DEBT_PT,
       (LEAST(B.KUM,M.KUM)-GREATEST(B.KUM_PREV,M.KUM_PREV)) PAY_APPLIED, 'ESLESTI'
  FROM (
    SELECT A.AGREEMENT_ID, X.ACCOUNT_ID MAH_ACC, X.ID MAH_ACTION, A.ACCRUE_TYPE_ID, MI.TUT,
           SUM(MI.TUT) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY X.ACTION_DATE,X.ID) KUM,
           SUM(MI.TUT) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY X.ACTION_DATE,X.ID)-MI.TUT KUM_PREV
      FROM STG_PILOT_ACC A
      JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
      JOIN (SELECT ACCOUNT_ACTION_ID,SUM(ABS(AMOUNT)) TUT FROM SMS.CS_ACCOUNT_INCOME GROUP BY ACCOUNT_ACTION_ID) MI
        ON MI.ACCOUNT_ACTION_ID=X.ID
     WHERE A.ACCRUE_TYPE_ID<>14
       AND X.REF_DEPOSIT_ACCOUNT_ID IS NULL
       AND X.REF_DEPOSIT_ACCOUNT_ACTION_ID IS NULL
       AND NOT EXISTS (SELECT 1 FROM STG_MAHSUP_POOL MP WHERE MP.SOURCE_ORACLE_ACTION_ID=X.ID AND MP.DURUM='ESLESTI')
  ) M
  JOIN (
    SELECT A.AGREEMENT_ID, P.SOURCE_ORACLE_ACCOUNT_ID DEBT_ACC, P.SOURCE_ORACLE_ACTION_ID DEBT_ACTION,
           P.LREF DEBT_PT,
           SUM(P.PAYABLETOTAL) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY P.DATE_,P.LREF) KUM,
           SUM(P.PAYABLETOTAL) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY P.DATE_,P.LREF)-P.PAYABLETOTAL KUM_PREV
      FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
     WHERE P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0 AND P.PAYABLETOTAL>0
  ) B ON B.AGREEMENT_ID=M.AGREEMENT_ID
 WHERE (LEAST(B.KUM,M.KUM)-GREATEST(B.KUM_PREV,M.KUM_PREV)) > 0.01;

INSERT INTO STG_MAHSUP_POOL
SELECT A.AGREEMENT_ID, X.ACCOUNT_ID, X.ID, A.ACCRUE_TYPE_ID,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       NULL,NULL,NULL,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID)
        - NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0),
       CASE WHEN NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0)=0
            THEN 'HEDEF_YOK' ELSE 'ARTAN_IADE' END
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
 WHERE A.ACCRUE_TYPE_ID<>14
   AND (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID)
       - NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0) > 0.01;
COMMIT;
CREATE INDEX IX_MAHPOOL_SRC ON STG_MAHSUP_POOL (SOURCE_ORACLE_ACTION_ID);
CREATE INDEX IX_MAHPOOL_DEBT ON STG_MAHSUP_POOL (TARGET_DEBT_PT);

-- [R14b] Mahsup CROSSREF = REF/FIFO hedef borc PT
UPDATE STG_PAYTRANS P SET P.CROSSREF = (
  SELECT MAX(MP.TARGET_DEBT_PT) KEEP (DENSE_RANK FIRST ORDER BY MP.PAY_APPLIED DESC, MP.TARGET_DEBT_PT)
    FROM STG_MAHSUP_POOL MP
   WHERE MP.SOURCE_ORACLE_ACTION_ID = P.SOURCE_ORACLE_ACTION_ID
     AND MP.DURUM = 'ESLESTI' AND MP.TARGET_DEBT_PT IS NOT NULL)
 WHERE P.PT_KIND = 'PAYMENT' AND P.SRC_ACTION_TYPE = 12
   AND EXISTS (SELECT 1 FROM STG_MAHSUP_POOL MP
                WHERE MP.SOURCE_ORACLE_ACTION_ID = P.SOURCE_ORACLE_ACTION_ID
                  AND MP.DURUM = 'ESLESTI' AND MP.TARGET_DEBT_PT IS NOT NULL);
COMMIT;

UPDATE STG_INVOICE V SET V.INVOICECROSSREF = (
  SELECT P.CROSSREF FROM STG_PAYTRANS P
   WHERE P.SOURCE_ORACLE_ACTION_ID = V.SOURCE_ORACLE_ACTION_ID AND P.PT_KIND = 'PAYMENT' AND ROWNUM = 1)
 WHERE V.INV_KIND = 'TAHSILAT'
   AND EXISTS (SELECT 1 FROM STG_PAYTRANS P
                WHERE P.SOURCE_ORACLE_ACTION_ID = V.SOURCE_ORACLE_ACTION_ID
                  AND P.PT_KIND = 'PAYMENT' AND P.SRC_ACTION_TYPE = 12);
COMMIT;

-- PAID yeniden hesap: tahsilat CROSSREF + mahsup FIFO PAY_APPLIED
UPDATE STG_PAYTRANS SET PAID = 0 WHERE PT_KIND = 'ACCRUE'; COMMIT;
UPDATE STG_PAYTRANS D SET D.PAID = NVL((
  SELECT SUM(C.PAYABLETOTAL) FROM STG_PAYTRANS C
   WHERE C.PT_KIND = 'PAYMENT' AND C.IOCODE = 1 AND C.CROSSREF = D.LREF
     AND NVL(C.CANCELED, 0) = 0
     AND NVL(C.SRC_ACTION_TYPE, 0) <> 12), 0)
 WHERE D.PT_KIND = 'ACCRUE'; COMMIT;
UPDATE STG_PAYTRANS D SET D.PAID = D.PAID + NVL((
  SELECT SUM(MP.PAY_APPLIED) FROM STG_MAHSUP_POOL MP
   WHERE MP.TARGET_DEBT_PT = D.LREF AND MP.DURUM = 'ESLESTI'), 0)
 WHERE D.PT_KIND = 'ACCRUE'; COMMIT;
UPDATE STG_INVOICE V SET V.CLOSED = 1
 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')
   AND EXISTS (SELECT 1 FROM STG_PAYTRANS P WHERE P.INVOICEREF = V.LREF AND P.PT_KIND = 'ACCRUE'
                AND P.PAID >= P.PAYABLETOTAL - 0.01 AND P.PAYABLETOTAL > 0); COMMIT;

-- [R36] ABYS uyumu: hesap TD<=TC ise MAIN kapalı (kaynak bakiye)
UPDATE STG_INVOICE V SET V.CLOSED = 1
 WHERE V.INV_KIND = 'MAIN'
   AND EXISTS (SELECT 1 FROM STG_PILOT_ACC A WHERE A.ID = V.LREF
                AND NVL(A.TOTAL_DEBT,0) <= NVL(A.TOTAL_CREDIT,0) + 0.01); COMMIT;

-- 12. STG_CANCEL_POOL [R15]
CREATE TABLE STG_CANCEL_POOL (
  LREF NUMBER(12), REVERSAL_TYPE VARCHAR2(20), RETURN_SOURCE_INVREF NUMBER(12),
  IOCODE NUMBER(1), GRANDTOTAL NUMBER(19,4), STATUS_NET_KATKI NUMBER(19,4),
  SOURCE_ORACLE_ACCOUNT_ID NUMBER(12), SOURCE_ORACLE_ACTION_ID NUMBER(12),
  AGREEMENT_ID NUMBER(12), SRC_ACCRUE_TYPE NUMBER(6), SEBEP VARCHAR2(200));
INSERT INTO STG_CANCEL_POOL
SELECT 1500000000+EC.ACTION_ID,'EKSILTEN_TAM',A.ID,1,EC.EKS,-EC.EKS,EC.ACCOUNT_ID,EC.ACTION_ID,
       A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,'Tam iptal ters kayit'
  FROM STG_EKSILTEN_CLASS EC JOIN STG_PILOT_ACC A ON A.ID=EC.ACCOUNT_ID WHERE EC.KIND='TAM';
INSERT INTO STG_CANCEL_POOL
SELECT 1500000000+X.ID,'CANCEL_CLASS',NULL,CASE WHEN M.STATUS=1 THEN 0 ELSE 1 END,
       (SELECT SUM(ABS(I.AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME I WHERE I.ACCOUNT_ACTION_ID=X.ID),
       (SELECT SUM(I.AMOUNT*I.STATUS) FROM SMS.CS_ACCOUNT_INCOME I WHERE I.ACCOUNT_ACTION_ID=X.ID),
       X.ACCOUNT_ID,X.ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,'Cancel sinifi ters kayit'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID WHERE M.ACTION_CLASS IN (4,8);
COMMIT;
CREATE INDEX IX_CANCPOOL_SRC ON STG_CANCEL_POOL (SOURCE_ORACLE_ACTION_ID);
UPDATE STG_INVOICE V SET V.RETURN_TARGET_INVREF=
  (SELECT MIN(CP.LREF) FROM STG_CANCEL_POOL CP WHERE CP.RETURN_SOURCE_INVREF=V.LREF AND CP.REVERSAL_TYPE='EKSILTEN_TAM')
 WHERE V.INV_KIND='MAIN' AND EXISTS (SELECT 1 FROM STG_CANCEL_POOL CP WHERE CP.RETURN_SOURCE_INVREF=V.LREF); COMMIT;

-- 12b. [R31] Tam eksilten — PCMS CreateReverseTransaction (IADE FATURASI) + CancelInvoices
INSERT INTO STG_INVOICE (LREF,INV_KIND,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_REGISTER_ID,
       SRC_AGREEMENT_ID,SRC_ACCRUE_TYPE,DATE_,LAWDETAILREF,TLTOTAL,TAX,GRANDTOTAL,PAYABLETOTAL,INV_TYPE,
       IOCODE,CANCELED,CLOSED,RETURN_SOURCE_INVREF,RETURN_TARGET_INVREF,INVOICECROSSREF,LINKED_SOURCE_INVREF)
SELECT 1600000000+EC.ACTION_ID,'IADE',MAIN.SOURCE_ORACLE_ACCOUNT_ID,EC.ACTION_ID,
       MAIN.SRC_REGISTER_ID,MAIN.SRC_AGREEMENT_ID,MAIN.SRC_ACCRUE_TYPE,
       CASE WHEN EXTRACT(YEAR FROM E.ACTION_DATE)<1753 THEN ADD_MONTHS(E.ACTION_DATE,24000) ELSE E.ACTION_DATE END,
       MAIN.LAWDETAILREF,
       NVL((SELECT SUM(CASE WHEN IL.IS_VAT_INCOME=1 THEN 0 ELSE IL.AMOUNT END)
              FROM STG_INVLINES IL WHERE IL.INVOICEREF=MAIN.LREF AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0),MAIN.TLTOTAL),
       NVL((SELECT SUM(CASE WHEN IL.IS_VAT_INCOME=1 THEN IL.AMOUNT ELSE 0 END)
              FROM STG_INVLINES IL WHERE IL.INVOICEREF=MAIN.LREF AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0),MAIN.TAX),
       MAIN.GRANDTOTAL, MAIN.PAYABLETOTAL, MAIN.INV_TYPE,
       0, 0, 0, MAIN.LREF, NULL, NULL, NULL
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_PILOT_ACC A ON A.ID=EC.ACCOUNT_ID
  JOIN STG_INVOICE MAIN ON MAIN.LREF=A.ID AND MAIN.INV_KIND='MAIN'
  JOIN SMS.CS_ACCOUNT_ACTION E ON E.ID=EC.ACTION_ID
 WHERE EC.KIND='TAM';
COMMIT;

UPDATE STG_INVOICE V SET V.RETURN_TARGET_INVREF=1600000000+
  (SELECT EC.ACTION_ID FROM STG_EKSILTEN_CLASS EC
    JOIN STG_PILOT_ACC A ON A.ID=EC.ACCOUNT_ID
   WHERE EC.KIND='TAM' AND A.ID=V.LREF AND ROWNUM=1)
 WHERE V.INV_KIND='MAIN' AND EXISTS (SELECT 1 FROM STG_EKSILTEN_CLASS EC WHERE EC.ACCOUNT_ID=V.LREF AND EC.KIND='TAM'); COMMIT;

INSERT INTO STG_INVLINES (LREF,INVOICEREF,LINE_TYPE,TRANSTYPE,AMOUNT,IS_VAT_INCOME,IS_DEPOSIT,
       IS_OVERDUE_INCOME,IS_LEGAL_FEE,IS_DISCOUNT,SRC_ACCRUE_TYPE,SRC_INCOME_ID,SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,CANCELED,LINEEXP)
SELECT 1700000000+IL.LREF, 1600000000+EC.ACTION_ID, IL.LINE_TYPE, IL.TRANSTYPE, IL.AMOUNT,
       IL.IS_VAT_INCOME, IL.IS_DEPOSIT, IL.IS_OVERDUE_INCOME, IL.IS_LEGAL_FEE, IL.IS_DISCOUNT,
       IL.SRC_ACCRUE_TYPE, IL.SRC_INCOME_ID, IL.SOURCE_ORACLE_INCOME_ID,
       IL.SOURCE_ORACLE_ACCOUNT_ID, EC.ACTION_ID, 0,
       'IADE '||NVL(IL.LINEEXP,TO_CHAR(IL.TRANSTYPE))
  FROM STG_INVLINES IL
  JOIN STG_INVOICE MAIN ON MAIN.LREF=IL.INVOICEREF AND MAIN.INV_KIND='MAIN'
  JOIN STG_EKSILTEN_CLASS EC ON EC.ACCOUNT_ID=MAIN.LREF AND EC.KIND='TAM'
 WHERE IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0;
COMMIT;

INSERT INTO STG_PAYTRANS (LREF,INVOICEREF,PT_TYPE,IOCODE,CROSSREF,PAYTYPE,INVLINEREF,INST_NR,DATE_,
       PAYABLETOTAL,PAID,CANCELED,PT_KIND,SRC_ACTION_TYPE,SRC_ACCRUE_TYPE,SOURCE_ORACLE_ACCOUNT_ID,
       SOURCE_ORACLE_ACTION_ID,CANCELLATIONPAYMENT,INSTALLMENT_ID)
SELECT 1600000000+EC.ACTION_ID, 1600000000+EC.ACTION_ID, I.INV_TYPE, 0,
       NULL, NULL, NULL, 0, I.DATE_, I.PAYABLETOTAL, 0, 0, 'IADE', 2,
       I.SRC_ACCRUE_TYPE, I.SOURCE_ORACLE_ACCOUNT_ID, EC.ACTION_ID, 0, NULL
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE I ON I.LREF=1600000000+EC.ACTION_ID AND I.INV_KIND='IADE'
 WHERE EC.KIND='TAM';
COMMIT;

-- CancelInvoices: ödenmemiş MAIN (CLOSED=0) — IADE TAHSİLAT zinciri
INSERT INTO STG_INVOICE (LREF,INV_KIND,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_REGISTER_ID,
       SRC_AGREEMENT_ID,SRC_ACCRUE_TYPE,DATE_,LAWDETAILREF,TLTOTAL,TAX,GRANDTOTAL,PAYABLETOTAL,INV_TYPE,
       IOCODE,CANCELED,CLOSED,RETURN_SOURCE_INVREF,RETURN_TARGET_INVREF,INVOICECROSSREF,LINKED_SOURCE_INVREF)
SELECT 1800000000+EC.ACTION_ID,'TAHSILAT',IADE.SOURCE_ORACLE_ACCOUNT_ID,EC.ACTION_ID,
       IADE.SRC_REGISTER_ID,IADE.SRC_AGREEMENT_ID,IADE.SRC_ACCRUE_TYPE,IADE.DATE_,NULL,
       IADE.PAYABLETOTAL,0,IADE.PAYABLETOTAL,IADE.PAYABLETOTAL,101,1,0,1,
       NULL,NULL,IPT.LREF,NULL
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE MAIN ON MAIN.LREF=EC.ACCOUNT_ID AND MAIN.INV_KIND='MAIN' AND NVL(MAIN.CLOSED,0)=0
  JOIN STG_INVOICE IADE ON IADE.LREF=1600000000+EC.ACTION_ID AND IADE.INV_KIND='IADE'
  JOIN STG_PAYTRANS IPT ON IPT.LREF=1600000000+EC.ACTION_ID AND IPT.PT_KIND='IADE'
 WHERE EC.KIND='TAM';
COMMIT;

INSERT INTO STG_PAYTRANS (LREF,INVOICEREF,PT_TYPE,IOCODE,CROSSREF,PAYTYPE,INVLINEREF,INST_NR,DATE_,
       PAYABLETOTAL,PAID,CANCELED,PT_KIND,SRC_ACTION_TYPE,SRC_ACCRUE_TYPE,SOURCE_ORACLE_ACCOUNT_ID,
       SOURCE_ORACLE_ACTION_ID,CANCELLATIONPAYMENT,INSTALLMENT_ID)
SELECT 1800000000+EC.ACTION_ID, 1800000000+EC.ACTION_ID, 101, 1,
       IPT.LREF, 174, NULL, 0, IADE.DATE_, IADE.PAYABLETOTAL, 0, 0, 'PAYMENT', 2,
       IADE.SRC_ACCRUE_TYPE, IADE.SOURCE_ORACLE_ACCOUNT_ID, EC.ACTION_ID, 1, NULL
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE MAIN ON MAIN.LREF=EC.ACCOUNT_ID AND MAIN.INV_KIND='MAIN' AND NVL(MAIN.CLOSED,0)=0
  JOIN STG_INVOICE IADE ON IADE.LREF=1600000000+EC.ACTION_ID
  JOIN STG_PAYTRANS IPT ON IPT.LREF=1600000000+EC.ACTION_ID AND IPT.PT_KIND='IADE'
 WHERE EC.KIND='TAM';
COMMIT;

INSERT INTO STG_PAYTRANS (LREF,INVOICEREF,PT_TYPE,IOCODE,CROSSREF,PAYTYPE,INVLINEREF,INST_NR,DATE_,
       PAYABLETOTAL,PAID,CANCELED,PT_KIND,SRC_ACTION_TYPE,SRC_ACCRUE_TYPE,SOURCE_ORACLE_ACCOUNT_ID,
       SOURCE_ORACLE_ACTION_ID,CANCELLATIONPAYMENT,INSTALLMENT_ID)
SELECT 1900000000+EC.ACTION_ID+PT.LREF, 1900000000+EC.ACTION_ID, 101, 0,
       PT.LREF, PT.PAYTYPE, PT.INVLINEREF, PT.INST_NR, IADE.DATE_, PT.PAYABLETOTAL, 0, 0, 'PAYMENT', 2,
       PT.SRC_ACCRUE_TYPE, PT.SOURCE_ORACLE_ACCOUNT_ID, EC.ACTION_ID, 1, PT.INSTALLMENT_ID
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE MAIN ON MAIN.LREF=EC.ACCOUNT_ID AND MAIN.INV_KIND='MAIN' AND NVL(MAIN.CLOSED,0)=0
  JOIN STG_INVOICE IADE ON IADE.LREF=1600000000+EC.ACTION_ID
  JOIN STG_PAYTRANS PT ON PT.INVOICEREF=MAIN.LREF AND PT.PT_KIND='ACCRUE' AND NVL(PT.CANCELED,0)=0
 WHERE EC.KIND='TAM';
COMMIT;

-- [R43] Tam eksilten, hesapta geçerli tahsilat yok → MAIN borç sıfır (ABYS net bakiye 0)
-- IADE faturası PCMS ters kayıt dökümantasyonu olarak kalır; iade tahsilat zinciri gerekmez.
UPDATE STG_INVOICE MAIN SET MAIN.TLTOTAL=0, MAIN.TAX=0, MAIN.GRANDTOTAL=0, MAIN.PAYABLETOTAL=0, MAIN.CLOSED=1
 WHERE MAIN.INV_KIND='MAIN'
   AND EXISTS (SELECT 1 FROM STG_EKSILTEN_CLASS EC WHERE EC.ACCOUNT_ID=MAIN.LREF AND EC.KIND='TAM')
   AND NOT EXISTS (
     SELECT 1
       FROM SMS.CS_ACCOUNT_ACTION PAY
       JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=PAY.ACTION_TYPE_ID AND M.ACTION_CLASS=2
      WHERE PAY.ACCOUNT_ID=MAIN.SOURCE_ORACLE_ACCOUNT_ID
        AND NOT EXISTS (
              SELECT 1
                FROM SMS.CS_ACCOUNT_ACTION CAN
               WHERE CAN.ACCOUNT_ID=PAY.ACCOUNT_ID AND CAN.ACTION_TYPE_ID=9
                 AND CAN.CASH_ID=PAY.CASH_ID AND CAN.RECEIPT_NUMBER=PAY.RECEIPT_NUMBER
                 AND NVL(CAN.BANK_PAYMENT_DATE, DATE '1900-01-01')=NVL(PAY.BANK_PAYMENT_DATE, DATE '1900-01-01')));
COMMIT;
UPDATE STG_PAYTRANS PT SET PT.PAYABLETOTAL=0, PT.PAID=0
 WHERE PT.PT_KIND='ACCRUE' AND NVL(PT.CANCELED,0)=0
   AND EXISTS (
     SELECT 1 FROM STG_INVOICE MAIN
     JOIN STG_EKSILTEN_CLASS EC ON EC.ACCOUNT_ID=MAIN.LREF AND EC.KIND='TAM'
    WHERE MAIN.LREF=PT.INVOICEREF AND MAIN.INV_KIND='MAIN'
      AND MAIN.PAYABLETOTAL=0 AND MAIN.GRANDTOTAL=0);
COMMIT;
UPDATE STG_INVLINES IL SET IL.CANCELED=1
 WHERE IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
   AND EXISTS (
     SELECT 1 FROM STG_INVOICE MAIN
     JOIN STG_EKSILTEN_CLASS EC ON EC.ACCOUNT_ID=MAIN.LREF AND EC.KIND='TAM'
    WHERE MAIN.LREF=IL.INVOICEREF AND MAIN.INV_KIND='MAIN'
      AND MAIN.PAYABLETOTAL=0 AND MAIN.GRANDTOTAL=0);
COMMIT;

-- 12c. [R32] Kısmi eksilten — eksilten gelirlerini MAIN'e yaz, net INVLINES + PT rebuild
CREATE TABLE STG_EKSILTEN_ADJ NOLOGGING AS
SELECT EC.ACTION_ID EKS_ACTION_ID, EC.ACCOUNT_ID, EC.EKS, EC.KIND,
       MAIN.LREF MAIN_INVREF, MAIN.SOURCE_ORACLE_ACTION_ID MAIN_ACTION_ID,
       MAIN.PAYABLETOTAL MAIN_PAYABLE_OLD, PT.LREF MAIN_PT_LREF
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE MAIN ON MAIN.LREF=EC.ACCOUNT_ID AND MAIN.INV_KIND='MAIN'
  JOIN STG_PAYTRANS PT ON PT.INVOICEREF=MAIN.LREF AND PT.PT_KIND='ACCRUE' AND NVL(PT.CANCELED,0)=0
 WHERE EC.KIND='KISMI';
CREATE INDEX IX_EKSADJ_ACC ON STG_EKSILTEN_ADJ (ACCOUNT_ID);

INSERT INTO STG_INVLINES (LREF,INVOICEREF,LINE_TYPE,TRANSTYPE,AMOUNT,IS_VAT_INCOME,IS_DEPOSIT,
       IS_OVERDUE_INCOME,IS_LEGAL_FEE,IS_DISCOUNT,SRC_ACCRUE_TYPE,SRC_INCOME_ID,SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,CANCELED,LINEEXP)
SELECT 1750000000+I.ID, EA.MAIN_INVREF,
       CASE WHEN NVL(I.IS_DISCOUNT,0)=1 THEN 103 ELSE 119 END,
       CASE WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=939 THEN 807
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=7658 THEN 808
            ELSE NVL(R.PCMS_TRANSTYPE, I.INCOME_ID) END,
       I.AMOUNT*I.STATUS,
       R.IS_VAT_INCOME, R.IS_DEPOSIT, R.IS_OVERDUE_INCOME, R.IS_LEGAL_FEE, NVL(I.IS_DISCOUNT,0),
       A.ACCRUE_TYPE_ID, I.INCOME_ID, I.ID, A.ID, EA.EKS_ACTION_ID, 0,
       CASE WHEN I.INCOME_ID=958 THEN 'SONRAKI AYA DEVIR'
            WHEN I.INCOME_ID=1929 THEN 'ONCEKI AYDAN DEVIR'
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=939 THEN 'Gaz Bedeli Indirim'
            WHEN NVL(I.IS_DISCOUNT,0)=1 AND I.INCOME_ID=7658 THEN 'SKB Bedeli Indirim'
            ELSE 'EKSILTEN' END
  FROM STG_EKSILTEN_ADJ EA
  JOIN STG_PILOT_ACC A ON A.ID=EA.ACCOUNT_ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=EA.EKS_ACTION_ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
 WHERE R.ACCRUAL_DEST='INVLINES';
COMMIT;

INSERT INTO STG_INVLINES (LREF,INVOICEREF,LINE_TYPE,TRANSTYPE,AMOUNT,IS_VAT_INCOME,IS_DEPOSIT,
       IS_OVERDUE_INCOME,IS_LEGAL_FEE,IS_DISCOUNT,SRC_ACCRUE_TYPE,SRC_INCOME_ID,SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,CANCELED,LINEEXP)
SELECT 1760000000+RN, INVOICEREF, LINE_TYPE, TRANSTYPE, AMOUNT,
       IS_VAT_INCOME, IS_DEPOSIT, IS_OVERDUE_INCOME, IS_LEGAL_FEE, IS_DISCOUNT,
       SRC_ACCRUE_TYPE, SRC_INCOME_ID, SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID, SOURCE_ORACLE_ACTION_ID, 0, LINEEXP
  FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY G.INVOICEREF, G.TRANSTYPE) RN,
           G.INVOICEREF, MIN(G.LINE_TYPE) LINE_TYPE, G.TRANSTYPE, SUM(G.AMOUNT) AMOUNT,
           MAX(G.IS_VAT_INCOME) IS_VAT_INCOME, MAX(G.IS_DEPOSIT) IS_DEPOSIT,
           MAX(G.IS_OVERDUE_INCOME) IS_OVERDUE_INCOME, MAX(G.IS_LEGAL_FEE) IS_LEGAL_FEE,
           MAX(G.IS_DISCOUNT) IS_DISCOUNT, MAX(G.SRC_ACCRUE_TYPE) SRC_ACCRUE_TYPE,
           MAX(G.SRC_INCOME_ID) SRC_INCOME_ID, MIN(G.SOURCE_ORACLE_INCOME_ID) SOURCE_ORACLE_INCOME_ID,
           MAX(G.SOURCE_ORACLE_ACCOUNT_ID) SOURCE_ORACLE_ACCOUNT_ID,
           MAX(G.SOURCE_ORACLE_ACTION_ID) SOURCE_ORACLE_ACTION_ID, MAX(G.LINEEXP) LINEEXP
      FROM STG_INVLINES G
     WHERE G.INVOICEREF IN (SELECT MAIN_INVREF FROM STG_EKSILTEN_ADJ)
       AND G.SRC_INCOME_ID<>-1 AND NVL(G.CANCELED,0)=0
     GROUP BY G.INVOICEREF, G.TRANSTYPE
    HAVING ABS(SUM(G.AMOUNT))>0.0001);
COMMIT;

UPDATE STG_INVLINES IL SET IL.CANCELED=1
 WHERE IL.INVOICEREF IN (SELECT MAIN_INVREF FROM STG_EKSILTEN_ADJ)
   AND IL.LREF < 1760000000 AND IL.SRC_INCOME_ID<>-1; COMMIT;

UPDATE STG_INVOICE V SET (V.TLTOTAL,V.TAX,V.GRANDTOTAL,V.PAYABLETOTAL)=(
       SELECT NVL(SUM(CASE WHEN IL.IS_VAT_INCOME=1 THEN 0 ELSE IL.AMOUNT END),0),
              NVL(SUM(CASE WHEN IL.IS_VAT_INCOME=1 THEN IL.AMOUNT ELSE 0 END),0),
              NVL(SUM(IL.AMOUNT),0), NVL(SUM(IL.AMOUNT),0)
         FROM STG_INVLINES IL
        WHERE IL.INVOICEREF=V.LREF AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0 AND IL.LREF>=1760000000)
 WHERE V.LREF IN (SELECT MAIN_INVREF FROM STG_EKSILTEN_ADJ); COMMIT;

UPDATE STG_PAYTRANS PT SET PT.CANCELED=1
 WHERE PT.PT_KIND='ACCRUE' AND PT.INVOICEREF IN (SELECT MAIN_INVREF FROM STG_EKSILTEN_ADJ); COMMIT;

INSERT INTO STG_PAYTRANS (LREF,INVOICEREF,PT_TYPE,IOCODE,CROSSREF,PAYTYPE,INVLINEREF,INST_NR,DATE_,
       PAYABLETOTAL,PAID,CANCELED,PT_KIND,SRC_ACTION_TYPE,SRC_ACCRUE_TYPE,SOURCE_ORACLE_ACCOUNT_ID,
       SOURCE_ORACLE_ACTION_ID,CANCELLATIONPAYMENT,INSTALLMENT_ID)
SELECT EA.MAIN_ACTION_ID, EA.MAIN_INVREF, V.INV_TYPE, 1, NULL, NULL, NULL, 0, V.DATE_,
       V.PAYABLETOTAL, NVL((SELECT SUM(P2.PAID) FROM STG_PAYTRANS P2 WHERE P2.LREF=EA.MAIN_PT_LREF),0),
       0, 'ACCRUE', NULL, V.SRC_ACCRUE_TYPE, V.SOURCE_ORACLE_ACCOUNT_ID, EA.MAIN_ACTION_ID, 0, NULL
  FROM STG_EKSILTEN_ADJ EA JOIN STG_INVOICE V ON V.LREF=EA.MAIN_INVREF;
COMMIT;

-- 12e. [R34] INVOICE EXPLAIN — PCMS LS_xxx_xx_INVOICE sözleşme tahakkuk formatı
UPDATE STG_INVOICE V SET (
  V.FITNO, V.CLIENTREF, V.OWNERREF, V.OWNERTYPE, V.EXPLAIN) = (
  SELECT C.FITNO,
         NVL(V.SRC_REGISTER_ID, C.CLIENTREF),
         V.SRC_AGREEMENT_ID,
         91,
         CASE WHEN V.INV_TYPE = 109 THEN 'Güvence Bedeli'
              ELSE NVL((SELECT ATL.VALUE FROM SMS.CS_ACCRUE_TYPE_PRM_LNG ATL
                         WHERE ATL.PRM_ID = V.SRC_ACCRUE_TYPE AND ATL.LANG_ID = 1),
                       'Sözleşme Tahakkuku')
         END
         || ' Tes.No : ' || TO_CHAR(C.FITNO)
         || ' Söz.No : ' || TO_CHAR(V.SRC_AGREEMENT_ID)
         || ' Abn No : ' || TO_CHAR(NVL(V.SRC_REGISTER_ID, C.CLIENTREF))
    FROM STG_AGR_CONTEXT C
   WHERE C.AGREEMENT_ID = V.SRC_AGREEMENT_ID)
 WHERE V.INV_TYPE IN (109, 119)
   AND V.INV_KIND IN ('MAIN', 'GECIKME', 'ARTTIRAN')
   AND EXISTS (SELECT 1 FROM STG_AGR_CONTEXT C
                WHERE C.AGREEMENT_ID = V.SRC_AGREEMENT_ID AND C.FITNO IS NOT NULL);
COMMIT;

UPDATE STG_INVOICE I SET (I.EXPLAIN, I.FITNO, I.CLIENTREF, I.OWNERREF, I.OWNERTYPE) = (
  SELECT M.EXPLAIN, M.FITNO, M.CLIENTREF, M.OWNERREF, M.OWNERTYPE
    FROM STG_INVOICE M WHERE M.LREF = I.RETURN_SOURCE_INVREF)
 WHERE I.INV_KIND = 'IADE' AND I.RETURN_SOURCE_INVREF IS NOT NULL;
COMMIT;

UPDATE STG_INVOICE T SET (T.EXPLAIN, T.FITNO, T.CLIENTREF, T.OWNERREF, T.OWNERTYPE) = (
  SELECT D.EXPLAIN, D.FITNO, D.CLIENTREF, D.OWNERREF, D.OWNERTYPE
    FROM STG_PAYTRANS P
    JOIN STG_INVOICE D ON D.LREF = P.INVOICEREF
   WHERE P.LREF = T.INVOICECROSSREF AND ROWNUM = 1)
 WHERE T.INV_KIND = 'TAHSILAT' AND T.INVOICECROSSREF IS NOT NULL;
COMMIT;

-- 12d. [R33] Taksit staging
CREATE TABLE STG_INSTALLMENT NOLOGGING AS
SELECT INS.ID, INS.AGREEMENT_ID, INS.PERIOD, INS.INSTALLMENT_DATE, INS.INSTALLMENT_NUMBER,
       INS.EXPIRY_DAY, INS.TOTAL_AMOUNT, INS.OPTIONAL_AMOUNT, INS.MONTHLY_AMOUNT,
       INS.DUE_DATE, INS.CANCEL_CAUSE_ID, INS.CANCELLATION_DATE, INS.LEGAL_PROCEEDING_ID,
       INS.ACTUAL_REGISTER_ID, INS.FIRST_INSTALLMENT_AMOUNT, INS.INSTALLMENT_TOTAL_AMOUNT
  FROM SMS.CS_INSTALLMENT INS
 WHERE INS.AGREEMENT_ID IN (SELECT DISTINCT AGREEMENT_ID FROM STG_PILOT_ACC);
CREATE INDEX IX_STG_INS_AGR ON STG_INSTALLMENT (AGREEMENT_ID);

CREATE TABLE STG_INSTALLMENT_PLAN NOLOGGING AS
SELECT IP.ID, IP.INSTALLMENT_ID, IP.ORDER_NUMBER INST_NR, IP.AMOUNT, IP.LATE_CHARGE,
       IP.OVERDUE, IP.EXPIRY_DATE, IP.DUE_DATE, IP.PAYMENT_DATE, IP.CASH_ID PAYMENT_ACTION_ID,
       IP.RECEIPT_SERIAL, IP.RECEIPT_NUMBER, IP.POOL_ID, INS.AGREEMENT_ID
  FROM SMS.CS_INSTALLMENT_PLAN IP
  JOIN STG_INSTALLMENT INS ON INS.ID=IP.INSTALLMENT_ID;
CREATE INDEX IX_STG_INSPLAN ON STG_INSTALLMENT_PLAN (INSTALLMENT_ID, INST_NR);
CREATE INDEX IX_STG_INSPLAN_CASH ON STG_INSTALLMENT_PLAN (PAYMENT_ACTION_ID);

-- 13. STG_INCOME_COVERAGE [R40] — hedef sayımı + beklenen dual-write istisnaları
-- Beklenen çift yazım (DUPLICATE DEĞİL):
--   958/1929 accrual: INVLINES + SPEFEE
--   tahsilat (ACT_CLASS=2): TAHSILAT INVLINES + PAYTRANS_INCOME  [R37]
CREATE TABLE STG_INCOME_COVERAGE NOLOGGING AS
SELECT S.SRC_INCOME_ID, S.SRC_ACTION_ID, S.SRC_ACCOUNT_ID, S.AGREEMENT_ID, S.ACCRUE_TYPE_ID,
       S.ACT_CLASS, S.INCOME_ID, S.SRC_AMOUNT,
       (SELECT COUNT(*) FROM STG_INVLINES IL WHERE IL.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1) CNT_IL,
       (SELECT COUNT(*) FROM STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID) CNT_PI,
       (SELECT COUNT(*) FROM STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID) CNT_SP,
       (SELECT COUNT(*) FROM STG_ADV_LEDGER_INCOME LG WHERE LG.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID) CNT_LG,
       (CASE WHEN EXISTS (SELECT 1 FROM STG_CANCEL_POOL CP WHERE CP.SOURCE_ORACLE_ACTION_ID=S.SRC_ACTION_ID)
             THEN (SELECT COUNT(*) FROM STG_CANCEL_POOL CP WHERE CP.SOURCE_ORACLE_ACTION_ID=S.SRC_ACTION_ID
                    AND NOT EXISTS (SELECT 1 FROM STG_INVLINES IL2 WHERE IL2.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID))
             ELSE (SELECT COUNT(*) FROM MIG_SKIPPED SK WHERE SK.ACTION_ID=S.SRC_ACTION_ID) END) CNT_SKIP,
       0 TOTAL_TARGETS
  FROM (SELECT I.ID SRC_INCOME_ID, X.ID SRC_ACTION_ID, A.ID SRC_ACCOUNT_ID, A.AGREEMENT_ID,
               A.ACCRUE_TYPE_ID, M.ACTION_CLASS ACT_CLASS, I.INCOME_ID, ABS(I.AMOUNT) SRC_AMOUNT
          FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID) S;
UPDATE STG_INCOME_COVERAGE SET TOTAL_TARGETS = CNT_IL+CNT_PI+CNT_SP+CNT_LG+CNT_SKIP;
ALTER TABLE STG_INCOME_COVERAGE ADD (DESTINATION VARCHAR2(20));
UPDATE STG_INCOME_COVERAGE SET DESTINATION=
  CASE
       -- Devir dual-write: INVLINES + SPEFEE
       WHEN INCOME_ID IN (958,1929) AND CNT_IL=1 AND CNT_SP=1 AND CNT_PI=0 AND TOTAL_TARGETS=2 THEN 'OK'
       -- Tahsilat dual-write [R37]: TAHSILAT INVLINES + PAYTRANS_INCOME
       WHEN ACT_CLASS=2 AND CNT_IL=1 AND CNT_PI=1 AND CNT_SP=0 AND TOTAL_TARGETS=2 THEN 'OK'
       WHEN TOTAL_TARGETS=0 THEN 'LOST'
       WHEN TOTAL_TARGETS>1 THEN 'DUPLICATE'
       ELSE 'OK' END;
COMMIT;
CREATE INDEX IX_STG_COV ON STG_INCOME_COVERAGE (DESTINATION);

-- 14. STG_RECON_DIFF [R18][R27] — warn&log; DEBT_BALANCE + yapısal bütünlük + custody
CREATE TABLE STG_RECON_DIFF (
  SEVERITY VARCHAR2(10), KATEGORI VARCHAR2(30), AGREEMENT_ID NUMBER(12),
  SOURCE_ORACLE_ACCOUNT_ID NUMBER(12), KAYNAK_NET NUMBER(19,4), STAGING_NET NUMBER(19,4),
  FARK NUMBER(19,4), SUSPECT_ACTION_IDS VARCHAR2(4000), SEBEP VARCHAR2(300),
  IGNORED NUMBER(1) DEFAULT 0, NOTE VARCHAR2(400));

-- (C1) PROBLEMATIC_CUSTODY
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,SEBEP)
SELECT 'CRITICAL','PROBLEMATIC_CUSTODY',A.AGREEMENT_ID,A.ID,SUM(I.AMOUNT*M.STATUS),'Emanet net>0'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE A.ACCRUE_TYPE_ID=14 GROUP BY A.AGREEMENT_ID,A.ID HAVING SUM(I.AMOUNT*M.STATUS)>0.01;

-- (C2) [R28] DEBT_BALANCE: kaynak(accrue!=14 amount*status) vs staging income-net
--      STAGING = hedef ABS * SIGN(kaynak amount) * action STATUS. CROSSREF/PAID bagimsiz.
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,KAYNAK_NET,STAGING_NET,FARK,SEBEP)
SELECT 'CRITICAL','DEBT_BALANCE',K.AGR,K.KN,NVL(S.SN,0),K.KN-NVL(S.SN,0),
       'Kaynak borc vs staging signed income-net'
  FROM (SELECT A.AGREEMENT_ID AGR, SUM(I.AMOUNT*M.STATUS) KN
          FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
          JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
         WHERE A.ACCRUE_TYPE_ID<>14 GROUP BY A.AGREEMENT_ID) K
  LEFT JOIN (
        SELECT S.AGREEMENT_ID AGR,
               SUM(CASE
                 WHEN IL.SOURCE_ORACLE_INCOME_ID IS NOT NULL AND IL.SRC_INCOME_ID<>-1
                   THEN SIGN(I.AMOUNT)*IL.AMOUNT*M.STATUS
                 WHEN PI.SOURCE_ORACLE_INCOME_ID IS NOT NULL
                   THEN SIGN(I.AMOUNT)*PI.INCOME_AMOUNT*M.STATUS
                 WHEN SF.SOURCE_ORACLE_INCOME_ID IS NOT NULL
                   THEN SIGN(I.AMOUNT)*SF.GRANDTOTAL*M.STATUS
                 ELSE I.AMOUNT*M.STATUS
               END) SN
          FROM STG_INCOME_COVERAGE S
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ID=S.SRC_INCOME_ID
          JOIN STG_PILOT_ACC A ON A.ID=S.SRC_ACCOUNT_ID
          JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID=S.SRC_ACTION_ID
          JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
          LEFT JOIN STG_INVLINES IL ON IL.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1
          LEFT JOIN STG_PAYTRANS_INCOME PI ON PI.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID
          LEFT JOIN STG_SPEFEE SF ON SF.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID
         WHERE A.ACCRUE_TYPE_ID<>14
         GROUP BY S.AGREEMENT_ID) S ON S.AGR=K.AGR
 WHERE ABS(K.KN-NVL(S.SN,0))>0.01;

-- (C3) Yapısal bütünlük: LOST/DUPLICATE
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','YAPISAL_'||DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID,SUM(SRC_AMOUNT),
       SUBSTR(LISTAGG(SRC_ACTION_ID,',') WITHIN GROUP (ORDER BY SRC_ACTION_ID),1,4000),'Income '||DESTINATION
  FROM STG_INCOME_COVERAGE WHERE DESTINATION IN ('LOST','DUPLICATE')
 GROUP BY DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID;

-- (C4) Orphan ref
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,SOURCE_ORACLE_ACCOUNT_ID,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','ORPHAN_REF',P.SOURCE_ORACLE_ACCOUNT_ID,TO_CHAR(P.SOURCE_ORACLE_ACTION_ID),'Staging action kaynakta yok'
  FROM STG_PAYTRANS P WHERE NOT EXISTS (SELECT 1 FROM SMS.CS_ACCOUNT_ACTION X WHERE X.ID=P.SOURCE_ORACLE_ACTION_ID);

-- (W1) fatura denge: GRANDTOTAL = SUM(INVLINES) [R35 devir satırda]
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'WARN','FATURA_DENGE',V.SRC_AGREEMENT_ID,V.SOURCE_ORACLE_ACCOUNT_ID,V.GRANDTOTAL,NVL(L.LS,0),
       V.GRANDTOTAL-NVL(L.LS,0),TO_CHAR(V.SOURCE_ORACLE_ACTION_ID),
       'GRANDTOTAL<>SUM(INVLINES)'
  FROM STG_INVOICE V
  LEFT JOIN (SELECT INVOICEREF,SUM(AMOUNT) LS FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1 AND NVL(CANCELED,0)=0 GROUP BY INVOICEREF) L ON L.INVOICEREF=V.LREF
 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')
   AND ABS(V.GRANDTOTAL-NVL(L.LS,0))>0.01;
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'WARN','MAHSUP_HEDEF_YOK',AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,SUM(MAHSUP_TUTAR),
       SUBSTR(LISTAGG(SOURCE_ORACLE_ACTION_ID,',') WITHIN GROUP (ORDER BY SOURCE_ORACLE_ACTION_ID),1,4000),'Kapatacak borc yok'
  FROM STG_MAHSUP_POOL WHERE DURUM='HEDEF_YOK' GROUP BY AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID;

-- (W3) [R29] PAID > PAYABLETOTAL kalan sapma (devir duzeltmesi sonrasi)
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'WARN','PAID_OVERFLOW',A.AGREEMENT_ID,P.SOURCE_ORACLE_ACCOUNT_ID,P.PAYABLETOTAL,P.PAID,
       P.PAID-P.PAYABLETOTAL,TO_CHAR(P.LREF),'Borc PT PAID>PAYABLETOTAL'
  FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
 WHERE P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0 AND P.PAID>P.PAYABLETOTAL+0.01;

-- (W4) [R32] EKSILTEN_BALANCE: MAIN INVOICE.PAYABLE = aktif ACCRUE PT
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','EKSILTEN_BALANCE',V.SRC_AGREEMENT_ID,V.SOURCE_ORACLE_ACCOUNT_ID,V.PAYABLETOTAL,P.PAYABLETOTAL,
       V.PAYABLETOTAL-NVL(P.PAYABLETOTAL,0),TO_CHAR(V.LREF),'Kismi eksilten sonrasi INV<>PT'
  FROM STG_INVOICE V
  JOIN STG_EKSILTEN_ADJ EA ON EA.MAIN_INVREF=V.LREF
  LEFT JOIN STG_PAYTRANS P ON P.INVOICEREF=V.LREF AND P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0
 WHERE ABS(V.PAYABLETOTAL-NVL(P.PAYABLETOTAL,0))>0.01;

-- (W5) [R31][R43] IPTAL_CHAIN: tahsilatlı tam eksilten — IADE tahsilat beklenir
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','IPTAL_CHAIN',MAIN.SRC_AGREEMENT_ID,MAIN.SOURCE_ORACLE_ACCOUNT_ID,1,TO_CHAR(EC.ACTION_ID),
       'Tam eksilten + tahsilat var ama IADE tahsilat yok'
  FROM STG_EKSILTEN_CLASS EC
  JOIN STG_INVOICE MAIN ON MAIN.LREF=EC.ACCOUNT_ID AND MAIN.INV_KIND='MAIN'
 WHERE EC.KIND='TAM'
   AND NVL(MAIN.PAYABLETOTAL,0)>0.01
   AND EXISTS (
     SELECT 1 FROM SMS.CS_ACCOUNT_ACTION PAY
     JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=PAY.ACTION_TYPE_ID AND M.ACTION_CLASS=2
    WHERE PAY.ACCOUNT_ID=MAIN.SOURCE_ORACLE_ACCOUNT_ID
      AND NOT EXISTS (
            SELECT 1 FROM SMS.CS_ACCOUNT_ACTION CAN
             WHERE CAN.ACCOUNT_ID=PAY.ACCOUNT_ID AND CAN.ACTION_TYPE_ID=9
               AND CAN.CASH_ID=PAY.CASH_ID AND CAN.RECEIPT_NUMBER=PAY.RECEIPT_NUMBER
               AND NVL(CAN.BANK_PAYMENT_DATE, DATE '1900-01-01')=NVL(PAY.BANK_PAYMENT_DATE, DATE '1900-01-01')))
   AND NOT EXISTS (SELECT 1 FROM STG_PAYTRANS P WHERE P.SOURCE_ORACLE_ACTION_ID=EC.ACTION_ID
                    AND NVL(P.CANCELLATIONPAYMENT,0)=1);

-- (I1) ICRA avukatlik (Hizmet ayrimi v0.8)
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SEBEP)
SELECT 'INFO','ICRA_LEGAL_FEE',A.AGREEMENT_ID,A.ID,SUM(ABS(I.AMOUNT)),'IS_LEGAL_FEE kalemi Hizmet faturasi (v0.8)'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
 WHERE R.IS_LEGAL_FEE=1 GROUP BY A.AGREEMENT_ID,A.ID;
COMMIT;
CREATE INDEX IX_RECON_SEV ON STG_RECON_DIFF (SEVERITY, KATEGORI);

-- 15. V_REF_CHAIN [R19]
CREATE VIEW V_REF_CHAIN AS
SELECT 'INVOICE' TBL, LREF, SOURCE_ORACLE_ACCOUNT_ID ACC, SOURCE_ORACLE_ACTION_ID ACT, SRC_AGREEMENT_ID AGR, GRANDTOTAL TUT, INV_KIND DETAY FROM STG_INVOICE
UNION ALL SELECT 'INVLINES',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,AMOUNT,TO_CHAR(TRANSTYPE) FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1
UNION ALL SELECT 'PAYTRANS',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,PAYABLETOTAL,PT_KIND FROM STG_PAYTRANS
UNION ALL SELECT 'SPEFEE',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,GRANDTOTAL,LINEEXP FROM STG_SPEFEE
UNION ALL SELECT 'LEDGER',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_AGREEMENT_ID,AMOUNT,'DIR'||DIRECTION FROM STG_ADVANCE_LEDGER
UNION ALL SELECT 'MAHSUP_POOL',NULL,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,AGREEMENT_ID,PAY_APPLIED,DURUM FROM STG_MAHSUP_POOL
UNION ALL SELECT 'CANCEL_POOL',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,AGREEMENT_ID,GRANDTOTAL,REVERSAL_TYPE FROM STG_CANCEL_POOL;

-- =====================================================================================
-- ÇIKTILAR — AGREEMENT_ID sürücülü
-- =====================================================================================
-- R0. RECON severity özeti (CRITICAL=0 hedef)
SELECT SEVERITY,KATEGORI,COUNT(*) SATIR,SUM(NVL(FARK,NVL(KAYNAK_NET,STAGING_NET))) TUTAR
  FROM STG_RECON_DIFF WHERE IGNORED=0 GROUP BY SEVERITY,KATEGORI
 ORDER BY DECODE(SEVERITY,'CRITICAL',1,'WARN',2,'INFO',3),SATIR DESC;

-- R1. CRITICAL detay (DEBT_BALANCE income-net [R28] ile sifir olmali)
SELECT AGREEMENT_ID,KATEGORI,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP
  FROM STG_RECON_DIFF WHERE SEVERITY='CRITICAL' AND IGNORED=0 ORDER BY AGREEMENT_ID,KATEGORI;

-- R2. Yapısal bütünlük: kaynak income = hedef satır (kategori bazında)
SELECT DESTINATION, COUNT(*) SATIR, SUM(SRC_AMOUNT) TUTAR FROM STG_INCOME_COVERAGE GROUP BY DESTINATION;

-- R3. AGREEMENT bazında borç/alacak/emanet net (K5 mantığı)
SELECT A.AGREEMENT_ID,
       SUM(CASE WHEN M.STATUS=1 THEN ABS(I.AMOUNT) ELSE 0 END) TOPLAM_BORC,
       SUM(CASE WHEN M.STATUS=-1 THEN ABS(I.AMOUNT) ELSE 0 END) TOPLAM_ALACAK,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID<>14 THEN I.AMOUNT*M.STATUS ELSE 0 END) DEBT_NET,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID=14 THEN I.AMOUNT*M.STATUS ELSE 0 END) CUSTODY_NET
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 GROUP BY A.AGREEMENT_ID ORDER BY A.AGREEMENT_ID;

-- R4. income hedef dağılımı (nereye gitti)
SELECT 'INVLINES' HEDEF,COUNT(*) SATIR,SUM(AMOUNT) TUTAR FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1
UNION ALL SELECT 'PAYTRANS_INCOME',COUNT(*),SUM(INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME
UNION ALL SELECT 'SPEFEE',COUNT(*),SUM(GRANDTOTAL) FROM STG_SPEFEE
UNION ALL SELECT 'LEDGER',COUNT(*),SUM(AMOUNT) FROM STG_ADV_LEDGER_INCOME;

-- R5. M0 + fatura/iptal
SELECT 'KAPSAMA_VS_KAYNAK' K,(SELECT COUNT(*) FROM STG_INCOME_COVERAGE)||'/'||
       (SELECT COUNT(*) FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID) V FROM DUAL
UNION ALL SELECT 'RETURN_CIFTI',TO_CHAR(COUNT(*)) FROM STG_INVOICE WHERE RETURN_TARGET_INVREF IS NOT NULL
UNION ALL SELECT 'INVOICECROSSREF',TO_CHAR(COUNT(*)) FROM STG_INVOICE WHERE INVOICECROSSREF IS NOT NULL
UNION ALL SELECT 'MAHSUP_ESLESTI',TO_CHAR(COUNT(*)) FROM STG_MAHSUP_POOL WHERE DURUM='ESLESTI';

-- R6. Fatura türü
SELECT INV_KIND,COUNT(*) ADET,SUM(GRANDTOTAL) TUTAR FROM STG_INVOICE GROUP BY INV_KIND ORDER BY 2 DESC;

-- R7. [R36][R38] ABYS panel kıyas — Açık Fatura (CS_ACCOUNT_STATUS_MV + gelir net)
SELECT METRIK, ABYS, STAGING, STAGING-ABYS FARK FROM (
  SELECT 'Gecikmis borc adedi' METRIK, 4 ABYS,
         (SELECT COUNT(*) FROM STG_PILOT_ACC A
           JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID
            AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)) STAGING
    FROM DUAL
  UNION ALL SELECT 'Toplam Borc', 26019.38,
         (SELECT SUM(AMV.BALANCE) FROM STG_PILOT_ACC A
           JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID
            AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)) STAGING
    FROM DUAL
  UNION ALL SELECT 'Toplam Borc (kaynak gelir net)', 26019.38,
         (SELECT SUM(BAL) FROM (
            SELECT SUM(AI.AMOUNT*AI.STATUS) BAL
              FROM STG_PILOT_ACC A
              JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID
               AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
              JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
              JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
             WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
             GROUP BY A.ID)) STAGING
    FROM DUAL
  UNION ALL SELECT 'Toplam Borc (staging PT)', NULL,
         (SELECT SUM(P.PAYABLETOTAL-P.PAID) FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
             AND P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0 AND P.PAYABLETOTAL-P.PAID>0.01) FROM DUAL
  UNION ALL SELECT 'Fatura Adet', 263,
         (SELECT COUNT(*) FROM STG_INVOICE I JOIN STG_PILOT_ACC A ON A.ID=I.SOURCE_ORACLE_ACCOUNT_ID
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
             AND I.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')) FROM DUAL
  UNION ALL SELECT 'Odenmis Fatura', 258,
         (SELECT COUNT(*) FROM STG_INVOICE I JOIN STG_PILOT_ACC A ON A.ID=I.SOURCE_ORACLE_ACCOUNT_ID
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
             AND I.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN') AND NVL(I.CLOSED,0)=1) FROM DUAL
  UNION ALL SELECT 'Kaynak TD-TC (tip1+2)', NULL,
         (SELECT SUM(GREATEST(NVL(A.TOTAL_DEBT,0)-NVL(A.TOTAL_CREDIT,0),0)) FROM STG_PILOT_ACC A
           WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1) AND A.ACCRUE_TYPE_ID IN (1,2)) FROM DUAL
);

-- R8. [R38] Gelir Bazlı kıyas — tahakkuk TYPE IN (1,5); PAYED TYPE=2 + nakit STATUS=1
SELECT A.ID ACCOUNT_ID, A.AGREEMENT_ID,
       SUM(CASE WHEN ATP.TYPE IN (1,5) THEN AI.AMOUNT*AI.STATUS END) KAYNAK_TAHAKKUK,
       SUM(CASE WHEN ATP.TYPE=2 OR (AA.ACTION_TYPE_ID=4 AND AI.STATUS=1)
                THEN AI.AMOUNT*AI.STATUS END) KAYNAK_TAHSILAT,
       SUM(AI.AMOUNT*AI.STATUS) KAYNAK_KALAN,
       NVL((SELECT SUM(IL.AMOUNT) FROM STG_INVLINES IL
             WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
               AND IL.INVOICEREF IN (SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                      AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0) STG_TAHAKKUK,
       NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME PI
             JOIN STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
             JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
             WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
               AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                     SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                      WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0) STG_TAHSILAT,
       NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME PI
             JOIN STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
             JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
             WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
               AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                     SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                      WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0)
     + NVL((SELECT SUM(IL.AMOUNT) FROM STG_INVLINES IL
             WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
               AND IL.INVOICEREF IN (SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                      AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0) STG_KALAN
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=AA.ACTION_TYPE_ID
 WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
 GROUP BY A.ID, A.AGREEMENT_ID
HAVING ABS(NVL(SUM(CASE WHEN ATP.TYPE IN (1,5) THEN AI.AMOUNT*AI.STATUS END),0)
         - NVL((SELECT SUM(IL.AMOUNT) FROM STG_INVLINES IL
                 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
                   AND IL.INVOICEREF IN (SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                          AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0))>0.01
    OR ABS(NVL(SUM(CASE WHEN ATP.TYPE=2 OR (AA.ACTION_TYPE_ID=4 AND AI.STATUS=1)
                     THEN AI.AMOUNT*AI.STATUS END),0)
         - NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME PI
                 JOIN STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
                 JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
                 WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                   AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                         SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                          WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0))>0.01
 ORDER BY A.ID;

-- R9. [R38] Açık Fatura Detay kıyas (AcikFaturaDetayRaporu.sql mantığı)
SELECT K.ACCOUNT_ID, K.AGREEMENT_ID,
       K.KAYNAK_ACRUAL, K.KAYNAK_PAYED, K.KAYNAK_BALANCE,
       NVL(S.ACRUAL,0) STG_ACRUAL, NVL(S.PAYED,0) STG_PAYED, NVL(S.BALANCE,0) STG_BALANCE,
       NVL(S.ACRUAL,0)-K.KAYNAK_ACRUAL FARK_ACRUAL,
       NVL(S.PAYED,0)-K.KAYNAK_PAYED FARK_PAYED,
       NVL(S.BALANCE,0)-K.KAYNAK_BALANCE FARK_BALANCE
  FROM (
    SELECT A.ID ACCOUNT_ID, A.AGREEMENT_ID,
           SUM(CASE WHEN ATP.TYPE IN (1,5) THEN AI.AMOUNT*AI.STATUS ELSE 0 END) KAYNAK_ACRUAL,
           SUM(CASE WHEN ATP.TYPE=2 OR (AA.ACTION_TYPE_ID=4 AND AI.STATUS=1)
                    THEN AI.AMOUNT*AI.STATUS END) KAYNAK_PAYED,
           SUM(AI.AMOUNT*AI.STATUS) KAYNAK_BALANCE
      FROM STG_PILOT_ACC A
      JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
      JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
      JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=AA.ACTION_TYPE_ID
      JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID
       AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
     WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
     GROUP BY A.ID, A.AGREEMENT_ID
    HAVING ABS(SUM(AI.AMOUNT*AI.STATUS))>0.01
  ) K
  LEFT JOIN (
    SELECT A.ID ACCOUNT_ID,
           NVL((SELECT SUM(IL.AMOUNT) FROM STG_INVLINES IL
                 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
                   AND IL.INVOICEREF IN (SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                          AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0) ACRUAL,
           NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME PI
                 JOIN STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
                 JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
                 WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                   AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                         SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                          WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0) PAYED,
           NVL((SELECT SUM(IL.AMOUNT) FROM STG_INVLINES IL
                 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
                   AND IL.INVOICEREF IN (SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                          AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0)
         + NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME PI
                 JOIN STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
                 JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
                 WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                   AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                         SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                          WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0) BALANCE
      FROM STG_PILOT_ACC A
     WHERE A.AGREEMENT_ID=(SELECT AGR_ID FROM MIG_PARAM WHERE ROWNUM=1)
  ) S ON S.ACCOUNT_ID=K.ACCOUNT_ID
 WHERE ABS(NVL(S.ACRUAL,0)-K.KAYNAK_ACRUAL)>0.01
    OR ABS(NVL(S.PAYED,0)-K.KAYNAK_PAYED)>0.01
    OR ABS(NVL(S.BALANCE,0)-K.KAYNAK_BALANCE)>0.01
 ORDER BY K.ACCOUNT_ID;
