-- =====================================================================================
-- İZGAZ (ABYS/Oracle) -> PCMS (MSSQL)  |  PİLOT CTAS + FIFO + RECON  v0.7
-- Ortam : Oracle 11.2.0.3. TEK DOSYA. AGREEMENT_ID sürücülü. TEST ORTAMI.
--
-- v0.7 ÇEKİRDEK DEĞİŞİMİ — YAPISAL BÜTÜNLÜK (income routing yeniden kuruldu):
--  [R20] KALEM FİLTRESİ SIFIR. Her CS_ACCOUNT_INCOME satırı parent action doğasına göre
--        TEK hedefe gider (hardcode INCOME_ID dışlaması YOK):
--          accrue=14 hesap                -> LEDGER (tüm income; emanet referans+girdi/çıktı)
--          accrue!=14 + accrual action    -> 958/1929: SPEFEE ; diğer HEPSİ: INVLINES
--          tahsilat action                -> PAYTRANS_INCOME
--        => kaynak income adedi == hedef satır adedi (kayıp/mükerrer imkansız).
--  [R21] VERİ-GÜDÜMLÜ ROUTING: STG_INCOME_ROUTE, CS_INCOME_PRM bayraklarından türer
--        (IS_DEPOSIT/IS_VAT_INCOME/IS_OVERDUE_INCOME/IS_LEGAL_FEE/IS_BALANCE_INCLUDED).
--        Hardcode IN-liste kalktı; tüm income evrenini kapsar.
--  [R22] INVOICE BAŞLIĞI INVLINES'TAN TÜRER: GRANDTOTAL/TAX/TLTOTAL = SUM(satır).
--        Başlık<->satır tanımı gereği tutar => 9.54 tipi fark imkansız.
--  [R23] SPEFEE = devir (958/1929) tek hedefi: STATUS=2, INVOICEREF=CS_ACCOUNT.ID.
--        (Sistemdeki tek net devir gelirleri; SPEFEE gerçek kolon yapısıyla.)
--  [R24] LAWDETAILREF = CS_ACCOUNT_ACTION.LEGAL_PROCEEDING_ID (ICRA faturaları).
--  [R25] INVOICECROSSREF (tahsilat<->borç bağı; canlı LS_001 örneğiyle doğrulandı).
--  [R26] SRC_ACCRUE_TYPE tüm hedef tablolarda (kontrol/gruplama için).
--  [R27] DEBT_BALANCE recon (CRITICAL): kaynak SUM(accrue!=14, amount*status) vs staging.
--        + Yapısal bütünlük recon: kaynak income = hedef satır (kategori bazında).
--
--  KORUNAN (v0.6): AGREEMENT-closure[R13], MAHSUP FIFO[R14], CANCEL RETURN çifti[R15],
--    ledger STATUS_NET[R16], KIYAS 121[R17], RECON warn&log severity[R18], V_REF_CHAIN[R19].
--  LREF bantları: INVOICE ana=ACCOUNT.ID; sentetik=500M+ACTION; collection=1.0B+ACTION;
--    ters=1.5B+ACTION. INVLINES accrual=INCOME.ID; collection=1.2B+ACTION. PAYTRANS=ACTION.
--    MSSQL'de DBCC CHECKIDENT reseed ZORUNLU.
-- =====================================================================================

-- 00. TEMİZLİK
BEGIN
  FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN
    ('MIG_PARAM','STG_PILOT_ACC','STG_ACTION_MAP','STG_INCOME_ROUTE','STG_EKSILTEN_CLASS',
     'STG_INVOICE','STG_INVLINES','STG_SPEFEE','STG_PAYTRANS','STG_PAYTRANS_INCOME',
     'STG_ADVANCE_LEDGER','STG_ADV_LEDGER_INCOME','STG_MAHSUP_POOL','STG_CANCEL_POOL',
     'STG_INCOME_COVERAGE','STG_RECON_DIFF','MIG_UNMAPPED','MIG_SKIPPED'))
  LOOP EXECUTE IMMEDIATE 'DROP TABLE '||T.TABLE_NAME||' PURGE'; END LOOP;
  FOR V IN (SELECT VIEW_NAME FROM USER_VIEWS WHERE VIEW_NAME='V_REF_CHAIN')
  LOOP EXECUTE IMMEDIATE 'DROP VIEW '||V.VIEW_NAME; END LOOP;
END;
/

-- 01. PARAMETRE
CREATE TABLE MIG_PARAM (REG_ID NUMBER(12));
INSERT INTO MIG_PARAM (REG_ID) VALUES (359459);   -- <-- düzenle / full run için boşalt
COMMIT;

-- 02. STG_PILOT_ACC — AGREEMENT-CLOSURE [R13]
CREATE TABLE STG_PILOT_ACC NOLOGGING AS
SELECT A.ID, A.REGISTER_ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID, A.PERIOD,
       A.TOTAL_DEBT, A.TOTAL_CREDIT,
       CASE WHEN EXISTS (SELECT 1 FROM SMS.CS_ACCOUNT_ACTION X
                          WHERE X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=1) THEN 'A' ELSE 'B' END SINIF
  FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID IN (
        SELECT DISTINCT A2.AGREEMENT_ID FROM SMS.CS_ACCOUNT A2
         WHERE NOT EXISTS (SELECT 1 FROM MIG_PARAM)
            OR A2.REGISTER_ID IN (SELECT REG_ID FROM MIG_PARAM));
CREATE UNIQUE INDEX IX_STG_PACC ON STG_PILOT_ACC (ID);
CREATE INDEX IX_STG_PACC_AGR ON STG_PILOT_ACC (AGREEMENT_ID);
CREATE INDEX IX_STG_PACC_S ON STG_PILOT_ACC (SINIF, ACCRUE_TYPE_ID);

DECLARE V_N NUMBER; BEGIN
  SELECT COUNT(*) INTO V_N FROM STG_PILOT_ACC;
  IF V_N=0 THEN RAISE_APPLICATION_ERROR(-20001,'STG_PILOT_ACC BOS: register hesap cozmuyor.'); END IF;
END;
/

SELECT CASE WHEN REGISTER_ID IN (SELECT REG_ID FROM MIG_PARAM) OR NOT EXISTS (SELECT 1 FROM MIG_PARAM)
            THEN 'SECILI_REGISTER' ELSE 'SOZLESME_CLOSURE' END KAYNAK,
       COUNT(*) HESAP, COUNT(DISTINCT AGREEMENT_ID) SOZLESME, COUNT(DISTINCT REGISTER_ID) REGISTER
  FROM STG_PILOT_ACC
 GROUP BY CASE WHEN REGISTER_ID IN (SELECT REG_ID FROM MIG_PARAM) OR NOT EXISTS (SELECT 1 FROM MIG_PARAM)
               THEN 'SECILI_REGISTER' ELSE 'SOZLESME_CLOSURE' END;

-- 03. ACTION MAP
CREATE TABLE STG_ACTION_MAP NOLOGGING AS
SELECT ID ACTION_TYPE_ID, TYPE ACTION_CLASS, STATUS,
       CASE WHEN STATUS=1 THEN 0 ELSE 1 END IOCODE FROM SMS.CS_ACTION_TYPE_PRM;

-- 04. LOG
CREATE TABLE MIG_UNMAPPED (KAYNAK VARCHAR2(30), SRC_ID NUMBER(12), SRC_KEY NUMBER(12),
  ACIKLAMA VARCHAR2(200), ADET NUMBER(12), TUTAR NUMBER(19,4));
CREATE TABLE MIG_SKIPPED (KAYNAK VARCHAR2(30), ACCOUNT_ID NUMBER(12), ACTION_ID NUMBER(12),
  ACTION_TYPE NUMBER(6), SEBEP VARCHAR2(200));

-- 04b. STG_INCOME_ROUTE [R21] — VERİ-GÜDÜMLÜ ROUTING (CS_INCOME_PRM bayrakları)
--      ACCRUAL_DEST: accrue!=14 accrual income'un hedefi. Emanet(accrue=14) hesap kuralı
--      account bazında uygulanır (aşağıda), income bazında değil.
CREATE TABLE STG_INCOME_ROUTE NOLOGGING AS
SELECT ID INCOME_ID,
       NVL(IS_DEPOSIT,0) IS_DEPOSIT, NVL(IS_VAT_INCOME,0) IS_VAT_INCOME,
       NVL(IS_OVERDUE_INCOME,0) IS_OVERDUE_INCOME, NVL(IS_LEGAL_FEE,0) IS_LEGAL_FEE,
       NVL(IS_LEGAL_EXPENSE,0) IS_LEGAL_EXPENSE, NVL(IS_BALANCE_INCLUDED,0) IS_BALANCE_INCLUDED,
       OVERDUE_INCOME_ID, VAT_INCOME_ID, INCOME_TYPE,
       CASE WHEN ID IN (958,1929) THEN 'SPEFEE'    -- net devir gelirleri (sistemdeki tek ikisi)
            ELSE 'INVLINES' END ACCRUAL_DEST       -- diğer HER income INVLINES (filtre yok)
  FROM SMS.CS_INCOME_PRM;
CREATE UNIQUE INDEX IX_INCROUTE ON STG_INCOME_ROUTE (INCOME_ID);

-- 04c. STG_EKSILTEN_CLASS [R1]
CREATE TABLE STG_EKSILTEN_CLASS NOLOGGING AS
SELECT E.ID ACTION_ID, E.ACCOUNT_ID, E.ACTION_DATE, EKS.TUT EKS, NVL(TAH.TUT,0) TAH,
       CASE WHEN EKS.TUT > NVL(TAH.TUT,0)+0.01 THEN 'ASIM'
            WHEN EKS.TUT >= NVL(TAH.TUT,0)*0.995 THEN 'TAM' ELSE 'KISMI' END KIND
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION E ON E.ACCOUNT_ID=A.ID AND E.ACTION_TYPE_ID=2
  JOIN (SELECT ACCOUNT_ACTION_ID,SUM(ABS(AMOUNT)) TUT FROM SMS.CS_ACCOUNT_INCOME GROUP BY ACCOUNT_ACTION_ID) EKS
    ON EKS.ACCOUNT_ACTION_ID=E.ID
  LEFT JOIN (SELECT X.ACCOUNT_ID,SUM(ABS(I.AMOUNT)) TUT FROM SMS.CS_ACCOUNT_ACTION X
               JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
              WHERE X.ACTION_TYPE_ID=1 GROUP BY X.ACCOUNT_ID) TAH ON TAH.ACCOUNT_ID=E.ACCOUNT_ID
 WHERE A.SINIF='A';
CREATE INDEX IX_EKS_ACC ON STG_EKSILTEN_CLASS (ACCOUNT_ID, KIND);
CREATE INDEX IX_EKS_ACT ON STG_EKSILTEN_CLASS (ACTION_ID);
INSERT INTO MIG_SKIPPED SELECT 'EKS_TAH_ASIMI',ACCOUNT_ID,ACTION_ID,2,
  'EKS>TAH' FROM STG_EKSILTEN_CLASS WHERE KIND='ASIM';
COMMIT;

-- 05. STG_INVLINES [R20] — accrue!=14 accrual income'un TAMAMI (958/1929 hariç -> SPEFEE)
--     Hiçbir INCOME_ID hardcode dışlaması yok. TRANSTYPE=ham INCOME_ID. +SRC_ACCRUE_TYPE.
CREATE TABLE STG_INVLINES NOLOGGING AS
SELECT I.ID LREF,
       CASE WHEN X.ACTION_TYPE_ID=1 THEN A.ID ELSE 500000000+X.ID END INVOICEREF,
       119 LINE_TYPE,                              -- başlık tipi INVOICE'ta hesaplanır
       I.INCOME_ID TRANSTYPE, ABS(I.AMOUNT) AMOUNT,
       R.IS_VAT_INCOME, R.IS_DEPOSIT, R.IS_OVERDUE_INCOME, R.IS_LEGAL_FEE,
       A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       I.INCOME_ID SRC_INCOME_ID, I.ID SOURCE_ORACLE_INCOME_ID,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (1,3,10)
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
 WHERE A.ACCRUE_TYPE_ID <> 14
   AND R.ACCRUAL_DEST = 'INVLINES'
UNION ALL
-- collection özet satırı (tahsilat) — Böl.08 sonrası eklenir; burada placeholder yok
SELECT 1200000000+V.SOURCE_ORACLE_ACTION_ID, V.LREF, 101, 173, V.GRANDTOTAL,
       0,0,0,0, V.SRC_ACCRUE_TYPE, -1, 1200000000+V.SOURCE_ORACLE_ACTION_ID,
       V.SOURCE_ORACLE_ACCOUNT_ID, V.SOURCE_ORACLE_ACTION_ID
  FROM (SELECT 1 LREF, 0 GRANDTOTAL, 0 SRC_ACCRUE_TYPE, 0 SOURCE_ORACLE_ACCOUNT_ID,
               0 SOURCE_ORACLE_ACTION_ID FROM DUAL WHERE 1=0) V;   -- boş; gerçek satır Böl.08'de INSERT
CREATE INDEX IX_STG_IL ON STG_INVLINES (INVOICEREF);
CREATE INDEX IX_STG_IL_SRC ON STG_INVLINES (SOURCE_ORACLE_INCOME_ID);

-- 06. STG_INVOICE [R22] — iskelet (accrual action'lar) + başlık INVLINES'tan türer + [R24][R25]
CREATE TABLE STG_INVOICE NOLOGGING AS
SELECT KEYS.LREF, KEYS.INV_KIND, KEYS.SOURCE_ORACLE_ACCOUNT_ID, KEYS.SOURCE_ORACLE_ACTION_ID,
       KEYS.SRC_REGISTER_ID, KEYS.SRC_AGREEMENT_ID, KEYS.SRC_ACCRUE_TYPE, KEYS.DATE_,
       KEYS.LEGAL_PROCEEDING_ID LAWDETAILREF,                       -- [R24]
       NVL(AGG.TL,0) TLTOTAL, NVL(AGG.VAT,0) TAX, NVL(AGG.TL,0)+NVL(AGG.VAT,0) GRANDTOTAL,
       NVL(AGG.TL,0)+NVL(AGG.VAT,0) PAYABLETOTAL,
       CASE WHEN AGG.HAS_GAZ=0 AND AGG.HAS_GUV>0 THEN 109
            WHEN KEYS.SRC_ACCRUE_TYPE=443 THEN 121 ELSE 119 END INV_TYPE,
       0 IOCODE, 0 CANCELED, 0 CLOSED,
       CAST(NULL AS NUMBER(12)) RETURN_SOURCE_INVREF, CAST(NULL AS NUMBER(12)) RETURN_TARGET_INVREF,
       CAST(NULL AS NUMBER(12)) INVOICECROSSREF,                    -- [R25]
       CAST(NULL AS NUMBER(12)) LINKED_SOURCE_INVREF
  FROM (
     SELECT A.ID LREF, 'MAIN' INV_KIND, A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID,
            A.REGISTER_ID SRC_REGISTER_ID, A.AGREEMENT_ID SRC_AGREEMENT_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
            CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END DATE_,
            X.LEGAL_PROCEEDING_ID
       FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=1
      WHERE A.ACCRUE_TYPE_ID<>14
     UNION ALL
     SELECT 500000000+X.ID, DECODE(X.ACTION_TYPE_ID,3,'ARTTIRAN','GECIKME'), A.ID, X.ID,
            A.REGISTER_ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID,
            CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
            X.LEGAL_PROCEEDING_ID
       FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (3,10)
      WHERE (A.ACCRUE_TYPE_ID<>14 OR A.ACCRUE_TYPE_ID IN (8,10))
  ) KEYS
  LEFT JOIN (
     SELECT INVOICEREF,
            SUM(CASE WHEN IS_VAT_INCOME=1 THEN 0 ELSE AMOUNT END) TL,
            SUM(CASE WHEN IS_VAT_INCOME=1 THEN AMOUNT ELSE 0 END) VAT,
            SUM(CASE WHEN TRANSTYPE IN (939,7658) THEN 1 ELSE 0 END) HAS_GAZ,
            SUM(CASE WHEN IS_DEPOSIT=1 THEN 1 ELSE 0 END) HAS_GUV
       FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1 GROUP BY INVOICEREF
  ) AGG ON AGG.INVOICEREF = KEYS.LREF;
CREATE UNIQUE INDEX IX_STG_INV ON STG_INVOICE (LREF);
CREATE INDEX IX_STG_INV_SRC ON STG_INVOICE (SOURCE_ORACLE_ACTION_ID);
CREATE INDEX IX_STG_INV_AGR ON STG_INVOICE (SRC_AGREEMENT_ID);
CREATE INDEX IX_STG_INV_KIND ON STG_INVOICE (INV_KIND);

-- 07. STG_SPEFEE [R23] — devir 958/1929; STATUS=2, INVOICEREF=CS_ACCOUNT.ID (gerçek kolonlar)
CREATE TABLE STG_SPEFEE NOLOGGING AS
SELECT I.ID LREF, 6 STYPE,
       CASE WHEN I.INCOME_ID=958 THEN 'SONRAKI AYA DEVIR' ELSE 'ONCEKI AYDAN DEVIR' END LINEEXP,
       A.ID INVOICEREF,                       -- [R23] CS_ACCOUNT.ID
       A.AGREEMENT_ID CLIENTREF, A.AGREEMENT_ID OWNERREF, 91 CLIENTTYPE,
       ABS(I.AMOUNT) TLTOTAL, 0 TAX, ABS(I.AMOUNT) GRANDTOTAL,
       0 CANCELLED, 2 STATUS,                  -- [R23] STATUS=2 (fatura üretilmiş)
       I.INCOME_ID SRC_INCOME_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID, I.ID SOURCE_ORACLE_INCOME_ID
  FROM STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID IN (1,3,10)
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
 WHERE A.ACCRUE_TYPE_ID<>14 AND I.INCOME_ID IN (958,1929);
CREATE INDEX IX_STG_SP_SRC ON STG_SPEFEE (SOURCE_ORACLE_INCOME_ID);

-- 08. STG_PAYTRANS  (a)borç PT (b)tahsilat class=2 (c)type-12 mahsup
CREATE TABLE STG_PAYTRANS NOLOGGING AS
SELECT V.SOURCE_ORACLE_ACTION_ID LREF, V.LREF INVOICEREF, V.INV_TYPE PT_TYPE, V.IOCODE,
       CAST(NULL AS NUMBER(12)) CROSSREF, CAST(NULL AS NUMBER(6)) PAYTYPE,
       CAST(NULL AS NUMBER(12)) INVLINEREF, 0 INST_NR, V.DATE_, V.PAYABLETOTAL, 0 PAID,
       0 CANCELED, 'ACCRUE' PT_KIND, CAST(NULL AS NUMBER(6)) SRC_ACTION_TYPE,
       V.SRC_ACCRUE_TYPE, V.SOURCE_ORACLE_ACCOUNT_ID, V.SOURCE_ORACLE_ACTION_ID
  FROM STG_INVOICE V
UNION ALL
SELECT X.ID, 1000000000+X.ID, 101, M.IOCODE,
       (SELECT MIN(G.ID) KEEP (DENSE_RANK FIRST ORDER BY
                 CASE WHEN G.ACTION_DATE<=X.ACTION_DATE THEN 0 ELSE 1 END, G.ACTION_DATE DESC, G.ID DESC)
          FROM SMS.CS_ACCOUNT_ACTION G WHERE G.ACCOUNT_ID=A.ID AND G.ACTION_TYPE_ID IN (1,3,10)) CROSSREF,
       CASE X.ACTION_TYPE_ID WHEN 4 THEN 32 WHEN 5 THEN 33 WHEN 6 THEN 10 ELSE 174 END,
       1200000000+X.ID, 0,
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       0,0,'PAYMENT', X.ACTION_TYPE_ID, A.ACCRUE_TYPE_ID, A.ID, X.ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID AND M.ACTION_CLASS=2
 WHERE A.ACCRUE_TYPE_ID<>14
UNION ALL
SELECT X.ID, 1000000000+X.ID, 101, 1,
       (SELECT MIN(G.ID) KEEP (DENSE_RANK FIRST ORDER BY G.ACTION_DATE, G.ID)
          FROM SMS.CS_ACCOUNT_ACTION G JOIN STG_PILOT_ACC A2 ON A2.ID=G.ACCOUNT_ID
         WHERE A2.AGREEMENT_ID=A.AGREEMENT_ID AND G.ACTION_TYPE_ID IN (1,3,10)) CROSSREF,
       10, 1200000000+X.ID, 0,
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(X.ACTION_DATE,24000) ELSE X.ACTION_DATE END,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       0,0,'PAYMENT', 12, A.ACCRUE_TYPE_ID, A.ID, X.ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
 WHERE A.ACCRUE_TYPE_ID<>14;
CREATE INDEX IX_STG_PT ON STG_PAYTRANS (INVOICEREF);
CREATE INDEX IX_STG_PT_SRC ON STG_PAYTRANS (SOURCE_ORACLE_ACTION_ID);
CREATE INDEX IX_STG_PT_CROSS ON STG_PAYTRANS (CROSSREF);
CREATE INDEX IX_STG_PT_KIND ON STG_PAYTRANS (PT_KIND);

-- collection INVOICE + INVLINES özet (tahsilat + type-12)
INSERT INTO STG_INVOICE (LREF,INV_KIND,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_REGISTER_ID,
       SRC_AGREEMENT_ID,SRC_ACCRUE_TYPE,DATE_,LAWDETAILREF,TLTOTAL,TAX,GRANDTOTAL,PAYABLETOTAL,INV_TYPE,
       IOCODE,CANCELED,CLOSED,RETURN_SOURCE_INVREF,RETURN_TARGET_INVREF,INVOICECROSSREF,LINKED_SOURCE_INVREF)
SELECT 1000000000+P.SOURCE_ORACLE_ACTION_ID,'TAHSILAT',P.SOURCE_ORACLE_ACCOUNT_ID,P.SOURCE_ORACLE_ACTION_ID,
       A.REGISTER_ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,P.DATE_,NULL,
       P.PAYABLETOTAL,0,P.PAYABLETOTAL,P.PAYABLETOTAL,101,1,0,1,
       NULL,NULL,P.CROSSREF,NULL              -- [R25] INVOICECROSSREF=borç PT
  FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
 WHERE P.PT_KIND='PAYMENT';
INSERT INTO STG_INVLINES (LREF,INVOICEREF,LINE_TYPE,TRANSTYPE,AMOUNT,IS_VAT_INCOME,IS_DEPOSIT,
       IS_OVERDUE_INCOME,IS_LEGAL_FEE,SRC_ACCRUE_TYPE,SRC_INCOME_ID,SOURCE_ORACLE_INCOME_ID,
       SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID)
SELECT 1200000000+P.SOURCE_ORACLE_ACTION_ID,1000000000+P.SOURCE_ORACLE_ACTION_ID,101,173,P.PAYABLETOTAL,
       0,0,0,0,P.SRC_ACCRUE_TYPE,-1,1200000000+P.SOURCE_ORACLE_ACTION_ID,
       P.SOURCE_ORACLE_ACCOUNT_ID,P.SOURCE_ORACLE_ACTION_ID
  FROM STG_PAYTRANS P WHERE P.PT_KIND='PAYMENT';
COMMIT;

-- 09. STG_PAYTRANS_INCOME [R20] — tahsilat income'un TAMAMI (filtre yok) +SRC_ACCRUE_TYPE
CREATE TABLE STG_PAYTRANS_INCOME NOLOGGING AS
SELECT I.ID LREF, P.LREF PAYTRANSREF,
       ROW_NUMBER() OVER (PARTITION BY P.LREF ORDER BY I.ID) LINENR,
       NVL((SELECT V.LREF FROM STG_INVOICE V WHERE V.SOURCE_ORACLE_ACTION_ID=P.CROSSREF AND ROWNUM=1),P.CROSSREF) DEBT_INVOICEREF,
       P.CROSSREF DEBT_PAYTRANSREF, ABS(I.AMOUNT) INCOME_AMOUNT,
       I.INCOME_ID SRC_INCOME_ID, P.SRC_ACCRUE_TYPE, I.ID SOURCE_ORACLE_INCOME_ID,
       P.SOURCE_ORACLE_ACCOUNT_ID, P.SOURCE_ORACLE_ACTION_ID
  FROM STG_PAYTRANS P JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=P.SOURCE_ORACLE_ACTION_ID
 WHERE P.PT_KIND='PAYMENT';
CREATE INDEX IX_STG_PI ON STG_PAYTRANS_INCOME (PAYTRANSREF);
CREATE INDEX IX_STG_PI_SRC ON STG_PAYTRANS_INCOME (SOURCE_ORACLE_INCOME_ID);

UPDATE STG_PAYTRANS D SET D.PAID=NVL((SELECT SUM(C.PAYABLETOTAL) FROM STG_PAYTRANS C
    WHERE C.PT_KIND='PAYMENT' AND C.IOCODE=1 AND C.CROSSREF=D.LREF),0) WHERE D.PT_KIND='ACCRUE'; COMMIT;
UPDATE STG_INVOICE V SET V.CLOSED=1 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')
   AND EXISTS (SELECT 1 FROM STG_PAYTRANS P WHERE P.INVOICEREF=V.LREF AND P.PT_KIND='ACCRUE'
                AND P.PAID>=P.PAYABLETOTAL-0.01 AND P.PAYABLETOTAL>0); COMMIT;

INSERT INTO MIG_SKIPPED SELECT 'CANCEL_SINIFI',X.ACCOUNT_ID,X.ID,X.ACTION_TYPE_ID,'CANCEL_*'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE M.ACTION_CLASS IN (4,8) AND A.ACCRUE_TYPE_ID<>14;
COMMIT;

-- 10. STG_ADVANCE_LEDGER (accrue=14 hesap -> TÜM income LEDGER) [R16][R20]
CREATE TABLE STG_ADVANCE_LEDGER NOLOGGING AS
SELECT X.ID LREF, A.REGISTER_ID SRC_REGISTER_ID, A.AGREEMENT_ID SRC_AGREEMENT_ID, A.ACCRUE_TYPE_ID SRC_ACCRUE_TYPE,
       CASE WHEN X.ACTION_TYPE_ID IN (20,48,36,39,44) THEN 1 ELSE 2 END DIRECTION,
       SUM(ABS(I.AMOUNT)) AMOUNT, SUM(I.AMOUNT*M.STATUS) STATUS_NET,
       CASE WHEN EXTRACT(YEAR FROM X.ACTION_DATE)<1753 THEN ADD_MONTHS(MIN(X.ACTION_DATE),24000) ELSE MIN(X.ACTION_DATE) END TRANS_DATE,
       X.ACTION_CAUSE_ID CAUSE_CODE, X.ACTION_TYPE_ID SOURCE_ACTION_TYPE,
       X.REF_DEPOSIT_ACCOUNT_ID REF_ACC_ID, X.REF_DEPOSIT_ACCOUNT_ACTION_ID REF_ACT_ID,
       CAST(NULL AS NUMBER(12)) PARENT_LREF, 0 CANCELED,
       A.ID SOURCE_ORACLE_ACCOUNT_ID, X.ID SOURCE_ORACLE_ACTION_ID
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE A.ACCRUE_TYPE_ID=14
 GROUP BY X.ID,A.ID,A.REGISTER_ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,X.ACTION_TYPE_ID,X.ACTION_CAUSE_ID,
          X.ACTION_DATE,X.REF_DEPOSIT_ACCOUNT_ID,X.REF_DEPOSIT_ACCOUNT_ACTION_ID;
CREATE INDEX IX_STG_LED ON STG_ADVANCE_LEDGER (SOURCE_ORACLE_ACCOUNT_ID, DIRECTION);
CREATE INDEX IX_STG_LED_ACT ON STG_ADVANCE_LEDGER (SOURCE_ORACLE_ACTION_ID);

UPDATE STG_ADVANCE_LEDGER C SET C.PARENT_LREF=(SELECT MAX(G.LREF) FROM STG_ADVANCE_LEDGER G
    WHERE G.SOURCE_ORACLE_ACCOUNT_ID=C.SOURCE_ORACLE_ACCOUNT_ID AND G.DIRECTION=1)
 WHERE C.DIRECTION=2 AND 1=(SELECT COUNT(*) FROM STG_ADVANCE_LEDGER G2
    WHERE G2.SOURCE_ORACLE_ACCOUNT_ID=C.SOURCE_ORACLE_ACCOUNT_ID AND G2.DIRECTION=1); COMMIT;

CREATE TABLE STG_ADV_LEDGER_INCOME NOLOGGING AS
SELECT I.ID LREF, L.LREF LEDGER_LREF, L.DIRECTION, I.INCOME_ID SRC_INCOME_ID, ABS(I.AMOUNT) AMOUNT,
       L.SRC_ACCRUE_TYPE, L.SOURCE_ORACLE_ACCOUNT_ID, L.SOURCE_ORACLE_ACTION_ID, I.ID SOURCE_ORACLE_INCOME_ID
  FROM STG_ADVANCE_LEDGER L JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=L.SOURCE_ORACLE_ACTION_ID;
CREATE INDEX IX_STG_LI_SRC ON STG_ADV_LEDGER_INCOME (SOURCE_ORACLE_INCOME_ID);
CREATE INDEX IX_STG_LI_LED ON STG_ADV_LEDGER_INCOME (LEDGER_LREF);

-- 11. STG_MAHSUP_POOL [R14] — sözleşme-içi FIFO (kümülatif aralık kesişimi)
CREATE TABLE STG_MAHSUP_POOL NOLOGGING AS
SELECT M.AGREEMENT_ID, M.MAH_ACC SOURCE_ORACLE_ACCOUNT_ID, M.MAH_ACTION SOURCE_ORACLE_ACTION_ID,
       M.ACCRUE_TYPE_ID MAH_ACCRUE_TYPE, M.TUT MAHSUP_TUTAR,
       B.DEBT_ACC TARGET_ACCOUNT_ID, B.DEBT_ACTION TARGET_DEBT_ACTION_ID, B.DEBT_PT TARGET_DEBT_PT,
       (LEAST(B.KUM,M.KUM)-GREATEST(B.KUM_PREV,M.KUM_PREV)) PAY_APPLIED, 'ESLESTI' DURUM
  FROM (SELECT A.AGREEMENT_ID, X.ACCOUNT_ID MAH_ACC, X.ID MAH_ACTION, A.ACCRUE_TYPE_ID, MI.TUT,
               SUM(MI.TUT) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY X.ACTION_DATE,X.ID) KUM,
               SUM(MI.TUT) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY X.ACTION_DATE,X.ID)-MI.TUT KUM_PREV
          FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
          JOIN (SELECT ACCOUNT_ACTION_ID,SUM(ABS(AMOUNT)) TUT FROM SMS.CS_ACCOUNT_INCOME GROUP BY ACCOUNT_ACTION_ID) MI
            ON MI.ACCOUNT_ACTION_ID=X.ID) M
  JOIN (SELECT A.AGREEMENT_ID, P.SOURCE_ORACLE_ACCOUNT_ID DEBT_ACC, P.SOURCE_ORACLE_ACTION_ID DEBT_ACTION,
               P.LREF DEBT_PT,
               SUM(P.PAYABLETOTAL) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY P.DATE_,P.LREF) KUM,
               SUM(P.PAYABLETOTAL) OVER (PARTITION BY A.AGREEMENT_ID ORDER BY P.DATE_,P.LREF)-P.PAYABLETOTAL KUM_PREV
          FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
         WHERE P.PT_KIND='ACCRUE' AND P.PAYABLETOTAL>0) B ON B.AGREEMENT_ID=M.AGREEMENT_ID
 WHERE (LEAST(B.KUM,M.KUM)-GREATEST(B.KUM_PREV,M.KUM_PREV)) > 0.01;
INSERT INTO STG_MAHSUP_POOL
SELECT A.AGREEMENT_ID, X.ACCOUNT_ID, X.ID, A.ACCRUE_TYPE_ID,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       NULL,NULL,NULL,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID)
        - NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0),
       CASE WHEN NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0)=0
            THEN 'HEDEF_YOK' ELSE 'ARTAN_IADE' END
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
 WHERE (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID)
       - NVL((SELECT SUM(PAY_APPLIED) FROM STG_MAHSUP_POOL P WHERE P.SOURCE_ORACLE_ACTION_ID=X.ID),0) > 0.01;
COMMIT;
CREATE INDEX IX_MAHPOOL_SRC ON STG_MAHSUP_POOL (SOURCE_ORACLE_ACTION_ID);

-- 12. STG_CANCEL_POOL [R15]
CREATE TABLE STG_CANCEL_POOL (
  LREF NUMBER(12), REVERSAL_TYPE VARCHAR2(20), RETURN_SOURCE_INVREF NUMBER(12),
  IOCODE NUMBER(1), GRANDTOTAL NUMBER(19,4), STATUS_NET_KATKI NUMBER(19,4),
  SOURCE_ORACLE_ACCOUNT_ID NUMBER(12), SOURCE_ORACLE_ACTION_ID NUMBER(12),
  AGREEMENT_ID NUMBER(12), SRC_ACCRUE_TYPE NUMBER(6), SEBEP VARCHAR2(200));
INSERT INTO STG_CANCEL_POOL
SELECT 1500000000+EC.ACTION_ID,'EKSILTEN_TAM',A.ID,1,EC.EKS,-EC.EKS,EC.ACCOUNT_ID,EC.ACTION_ID,
       A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,'Tam iptal ters kayit'
  FROM STG_EKSILTEN_CLASS EC JOIN STG_PILOT_ACC A ON A.ID=EC.ACCOUNT_ID WHERE EC.KIND='TAM';
INSERT INTO STG_CANCEL_POOL
SELECT 1500000000+X.ID,'CANCEL_CLASS',NULL,CASE WHEN M.STATUS=1 THEN 0 ELSE 1 END,
       (SELECT SUM(ABS(AMOUNT)) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       (SELECT SUM(AMOUNT*M.STATUS) FROM SMS.CS_ACCOUNT_INCOME WHERE ACCOUNT_ACTION_ID=X.ID),
       X.ACCOUNT_ID,X.ID,A.AGREEMENT_ID,A.ACCRUE_TYPE_ID,'Cancel sinifi ters kayit'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID WHERE M.ACTION_CLASS IN (4,8);
COMMIT;
CREATE INDEX IX_CANCPOOL_SRC ON STG_CANCEL_POOL (SOURCE_ORACLE_ACTION_ID);
UPDATE STG_INVOICE V SET V.RETURN_TARGET_INVREF=
  (SELECT MIN(CP.LREF) FROM STG_CANCEL_POOL CP WHERE CP.RETURN_SOURCE_INVREF=V.LREF AND CP.REVERSAL_TYPE='EKSILTEN_TAM')
 WHERE V.INV_KIND='MAIN' AND EXISTS (SELECT 1 FROM STG_CANCEL_POOL CP WHERE CP.RETURN_SOURCE_INVREF=V.LREF); COMMIT;

-- 13. STG_INCOME_COVERAGE — yapısal bütünlük artık trivial (her income tek hedef)
CREATE TABLE STG_INCOME_COVERAGE NOLOGGING AS
SELECT S.SRC_INCOME_ID, S.SRC_ACTION_ID, S.SRC_ACCOUNT_ID, S.AGREEMENT_ID, S.ACCRUE_TYPE_ID,
       S.ACT_CLASS, S.INCOME_ID, S.SRC_AMOUNT,
       (SELECT COUNT(*) FROM STG_INVLINES IL WHERE IL.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1)
      +(SELECT COUNT(*) FROM STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID)
      +(SELECT COUNT(*) FROM STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID)
      +(SELECT COUNT(*) FROM STG_ADV_LEDGER_INCOME LG WHERE LG.SOURCE_ORACLE_INCOME_ID=S.SRC_INCOME_ID)
      +(SELECT COUNT(*) FROM MIG_SKIPPED SK WHERE SK.ACTION_ID=S.SRC_ACTION_ID)
      +(SELECT COUNT(*) FROM STG_CANCEL_POOL CP WHERE CP.SOURCE_ORACLE_ACTION_ID=S.SRC_ACTION_ID) TOTAL_TARGETS
  FROM (SELECT I.ID SRC_INCOME_ID, X.ID SRC_ACTION_ID, A.ID SRC_ACCOUNT_ID, A.AGREEMENT_ID,
               A.ACCRUE_TYPE_ID, M.ACTION_CLASS ACT_CLASS, I.INCOME_ID, ABS(I.AMOUNT) SRC_AMOUNT
          FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID) S;
ALTER TABLE STG_INCOME_COVERAGE ADD (DESTINATION VARCHAR2(20));
UPDATE STG_INCOME_COVERAGE SET DESTINATION=
  CASE WHEN TOTAL_TARGETS=0 THEN 'LOST' WHEN TOTAL_TARGETS>1 THEN 'DUPLICATE' ELSE 'OK' END;
COMMIT;
CREATE INDEX IX_STG_COV ON STG_INCOME_COVERAGE (DESTINATION);

-- 14. STG_RECON_DIFF [R18][R27] — warn&log; DEBT_BALANCE + yapısal bütünlük + custody
CREATE TABLE STG_RECON_DIFF (
  SEVERITY VARCHAR2(10), KATEGORI VARCHAR2(30), AGREEMENT_ID NUMBER(12),
  SOURCE_ORACLE_ACCOUNT_ID NUMBER(12), KAYNAK_NET NUMBER(19,4), STAGING_NET NUMBER(19,4),
  FARK NUMBER(19,4), SUSPECT_ACTION_IDS VARCHAR2(4000), SEBEP VARCHAR2(300),
  IGNORED NUMBER(1) DEFAULT 0, NOTE VARCHAR2(400));

-- (C1) PROBLEMATIC_CUSTODY
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,SEBEP)
SELECT 'CRITICAL','PROBLEMATIC_CUSTODY',A.AGREEMENT_ID,A.ID,SUM(I.AMOUNT*M.STATUS),'Emanet net>0'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE A.ACCRUE_TYPE_ID=14 GROUP BY A.AGREEMENT_ID,A.ID HAVING SUM(I.AMOUNT*M.STATUS)>0.01;

-- (C2) [R27] DEBT_BALANCE: kaynak(accrue!=14 amount*status) vs staging(açık borç - devir hariç)
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,KAYNAK_NET,STAGING_NET,FARK,SEBEP)
SELECT 'CRITICAL','DEBT_BALANCE',K.AGR,K.KN,S.SN,K.KN-S.SN,'Kaynak borc vs staging acik borc'
  FROM (SELECT A.AGREEMENT_ID AGR, SUM(I.AMOUNT*M.STATUS) KN
          FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
          JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
         WHERE A.ACCRUE_TYPE_ID<>14 GROUP BY A.AGREEMENT_ID) K
  JOIN (SELECT A.AGREEMENT_ID AGR, SUM(P.PAYABLETOTAL-P.PAID) SN
          FROM STG_PAYTRANS P JOIN STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
         WHERE P.PT_KIND='ACCRUE' GROUP BY A.AGREEMENT_ID) S ON S.AGR=K.AGR
 WHERE ABS(K.KN-S.SN)>0.01;

-- (C3) Yapısal bütünlük: LOST/DUPLICATE
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','YAPISAL_'||DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID,SUM(SRC_AMOUNT),
       SUBSTR(LISTAGG(SRC_ACTION_ID,',') WITHIN GROUP (ORDER BY SRC_ACTION_ID),1,4000),'Income '||DESTINATION
  FROM STG_INCOME_COVERAGE WHERE DESTINATION IN ('LOST','DUPLICATE')
 GROUP BY DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID;

-- (C4) Orphan ref
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,SOURCE_ORACLE_ACCOUNT_ID,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','ORPHAN_REF',P.SOURCE_ORACLE_ACCOUNT_ID,TO_CHAR(P.SOURCE_ORACLE_ACTION_ID),'Staging action kaynakta yok'
  FROM STG_PAYTRANS P WHERE NOT EXISTS (SELECT 1 FROM SMS.CS_ACCOUNT_ACTION X WHERE X.ID=P.SOURCE_ORACLE_ACTION_ID);

-- (W1) fatura denge  (W2) HEDEF_YOK mahsup
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'WARN','FATURA_DENGE',V.SRC_AGREEMENT_ID,V.SOURCE_ORACLE_ACCOUNT_ID,V.GRANDTOTAL,NVL(L.LS,0),
       V.GRANDTOTAL-NVL(L.LS,0),TO_CHAR(V.SOURCE_ORACLE_ACTION_ID),'GRANDTOTAL<>satir toplam'
  FROM STG_INVOICE V LEFT JOIN (SELECT INVOICEREF,SUM(AMOUNT) LS FROM STG_INVLINES GROUP BY INVOICEREF) L ON L.INVOICEREF=V.LREF
 WHERE V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN') AND ABS(V.GRANDTOTAL-NVL(L.LS,0))>0.01;
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'WARN','MAHSUP_HEDEF_YOK',AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,SUM(MAHSUP_TUTAR),
       SUBSTR(LISTAGG(SOURCE_ORACLE_ACTION_ID,',') WITHIN GROUP (ORDER BY SOURCE_ORACLE_ACTION_ID),1,4000),'Kapatacak borc yok'
  FROM STG_MAHSUP_POOL WHERE DURUM='HEDEF_YOK' GROUP BY AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID;

-- (I1) ICRA avukatlik (Hizmet ayrimi v0.8)
INSERT INTO STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SEBEP)
SELECT 'INFO','ICRA_LEGAL_FEE',A.AGREEMENT_ID,A.ID,SUM(ABS(I.AMOUNT)),'IS_LEGAL_FEE kalemi Hizmet faturasi (v0.8)'
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_INCOME_ROUTE R ON R.INCOME_ID=I.INCOME_ID
 WHERE R.IS_LEGAL_FEE=1 GROUP BY A.AGREEMENT_ID,A.ID;
COMMIT;
CREATE INDEX IX_RECON_SEV ON STG_RECON_DIFF (SEVERITY, KATEGORI);

-- 15. V_REF_CHAIN [R19]
CREATE VIEW V_REF_CHAIN AS
SELECT 'INVOICE' TBL, LREF, SOURCE_ORACLE_ACCOUNT_ID ACC, SOURCE_ORACLE_ACTION_ID ACT, SRC_AGREEMENT_ID AGR, GRANDTOTAL TUT, INV_KIND DETAY FROM STG_INVOICE
UNION ALL SELECT 'INVLINES',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,AMOUNT,TO_CHAR(TRANSTYPE) FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1
UNION ALL SELECT 'PAYTRANS',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,PAYABLETOTAL,PT_KIND FROM STG_PAYTRANS
UNION ALL SELECT 'SPEFEE',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,NULL,GRANDTOTAL,LINEEXP FROM STG_SPEFEE
UNION ALL SELECT 'LEDGER',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,SRC_AGREEMENT_ID,AMOUNT,'DIR'||DIRECTION FROM STG_ADVANCE_LEDGER
UNION ALL SELECT 'MAHSUP_POOL',NULL,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,AGREEMENT_ID,PAY_APPLIED,DURUM FROM STG_MAHSUP_POOL
UNION ALL SELECT 'CANCEL_POOL',LREF,SOURCE_ORACLE_ACCOUNT_ID,SOURCE_ORACLE_ACTION_ID,AGREEMENT_ID,GRANDTOTAL,REVERSAL_TYPE FROM STG_CANCEL_POOL;

-- =====================================================================================
-- ÇIKTILAR — AGREEMENT_ID sürücülü
-- =====================================================================================
-- R0. RECON severity özeti (CRITICAL=0 hedef)
SELECT SEVERITY,KATEGORI,COUNT(*) SATIR,SUM(NVL(FARK,NVL(KAYNAK_NET,STAGING_NET))) TUTAR
  FROM STG_RECON_DIFF WHERE IGNORED=0 GROUP BY SEVERITY,KATEGORI
 ORDER BY DECODE(SEVERITY,'CRITICAL',1,'WARN',2,'INFO',3),SATIR DESC;

-- R1. CRITICAL detay (özellikle DEBT_BALANCE farkı burada; 9.54 kapandı mı?)
SELECT AGREEMENT_ID,KATEGORI,KAYNAK_NET,STAGING_NET,FARK,SUSPECT_ACTION_IDS,SEBEP
  FROM STG_RECON_DIFF WHERE SEVERITY='CRITICAL' AND IGNORED=0 ORDER BY AGREEMENT_ID,KATEGORI;

-- R2. Yapısal bütünlük: kaynak income = hedef satır (kategori bazında)
SELECT DESTINATION, COUNT(*) SATIR, SUM(SRC_AMOUNT) TUTAR FROM STG_INCOME_COVERAGE GROUP BY DESTINATION;

-- R3. AGREEMENT bazında borç/alacak/emanet net (K5 mantığı)
SELECT A.AGREEMENT_ID,
       SUM(CASE WHEN M.STATUS=1 THEN ABS(I.AMOUNT) ELSE 0 END) TOPLAM_BORC,
       SUM(CASE WHEN M.STATUS=-1 THEN ABS(I.AMOUNT) ELSE 0 END) TOPLAM_ALACAK,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID<>14 THEN I.AMOUNT*M.STATUS ELSE 0 END) DEBT_NET,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID=14 THEN I.AMOUNT*M.STATUS ELSE 0 END) CUSTODY_NET
  FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 GROUP BY A.AGREEMENT_ID ORDER BY A.AGREEMENT_ID;

-- R4. income hedef dağılımı (nereye gitti)
SELECT 'INVLINES' HEDEF,COUNT(*) SATIR,SUM(AMOUNT) TUTAR FROM STG_INVLINES WHERE SRC_INCOME_ID<>-1
UNION ALL SELECT 'PAYTRANS_INCOME',COUNT(*),SUM(INCOME_AMOUNT) FROM STG_PAYTRANS_INCOME
UNION ALL SELECT 'SPEFEE',COUNT(*),SUM(GRANDTOTAL) FROM STG_SPEFEE
UNION ALL SELECT 'LEDGER',COUNT(*),SUM(AMOUNT) FROM STG_ADV_LEDGER_INCOME;

-- R5. M0 + fatura/iptal
SELECT 'KAPSAMA_VS_KAYNAK' K,(SELECT COUNT(*) FROM STG_INCOME_COVERAGE)||'/'||
       (SELECT COUNT(*) FROM STG_PILOT_ACC A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
          JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID) V FROM DUAL
UNION ALL SELECT 'RETURN_CIFTI',TO_CHAR(COUNT(*)) FROM STG_INVOICE WHERE RETURN_TARGET_INVREF IS NOT NULL
UNION ALL SELECT 'INVOICECROSSREF',TO_CHAR(COUNT(*)) FROM STG_INVOICE WHERE INVOICECROSSREF IS NOT NULL
UNION ALL SELECT 'MAHSUP_ESLESTI',TO_CHAR(COUNT(*)) FROM STG_MAHSUP_POOL WHERE DURUM='ESLESTI';

-- R6. Fatura türü
SELECT INV_KIND,COUNT(*) ADET,SUM(GRANDTOTAL) TUTAR FROM STG_INVOICE GROUP BY INV_KIND ORDER BY 2 DESC;
