/* =============================================================================
   FILE : prodEnergy/90_afl_frk/91g_en_gt_afl_partial_heal.sql
   PATCH (cutover EXEC zincirine KOYMA) — residual EN_GT_AFL kismi heal

   91f sonrasi kalan: AFL_BALANCE > eps VE EN_ACC > AFL (DELTA_KALAN_NET > eps)

   Hesap (FATURAID = ABYS_ACCOUNT_ID):
     EXCESS = SUM(PT_KALAN) - AFL_BALANCE
     FIFO (PT.LREF ASC): ilk AFL tutari ACIK kalsin; fazlayi PAID artir
     Tam kapanan INV → CLOSED=1 (tum borc PT kalan <= eps)

   YAPMAZ:
     AFL≈0 tam close → 91f
     AFL > EN reopen
     CP=1 / CANCELED / IOCODE<>0

   Onkosul: MIG_AGR_FRK_ALL guncel + LS_AFL_OPEN_DEBT (cutover O50)
   Default @DryRun=1
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun BIT           = 1;      /* APPLY: 0 */
DECLARE @Agr    BIGINT        = NULL;   /* NULL = seed EN_GT_AFL | tek AGR */
DECLARE @Eps    DECIMAL(18,2) = 0.02;
-- SET @DryRun = 0;
-- SET @Agr = 948131;

DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
DECLARE @Msg NVARCHAR(400);
DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'SEED' ELSE CONVERT(VARCHAR(30), @Agr) END;
DECLARE @N INT;

SET @Msg = N'========== 91g EN_GT_AFL PARTIAL HEAL DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_AGR_FRK_ALL', 'U') IS NULL
BEGIN
    RAISERROR('MIG_AGR_FRK_ALL yok — once EXEC SP_AGR_FRK_ALL', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_AFL_OPEN_DEBT yok', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG (
        LOG_ID          BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID          BIGINT         NOT NULL,
        SNAPSHOT_TS     DATETIME2(3)   NOT NULL,
        DRY_RUN         BIT            NOT NULL,
        AGREEMENT_ID    BIGINT         NULL,
        ACCOUNT_ID      BIGINT         NULL,
        MAIN_LREF       INT            NOT NULL,
        PT_LREF         INT            NOT NULL,
        PT_PAID_OLD     DECIMAL(18,2)  NULL,
        PT_PAID_NEW     DECIMAL(18,2)  NULL,
        APPLY_AMT       DECIMAL(18,2)  NULL,
        PT_KALAN_OLD    DECIMAL(18,2)  NULL,
        AFL_BALANCE     DECIMAL(18,2)  NULL,
        ACC_EN_KALAN    DECIMAL(18,2)  NULL,
        ACC_EXCESS      DECIMAL(18,2)  NULL,
        AGR_DELTA_NET   DECIMAL(18,2)  NULL,
        NOTE            NVARCHAR(80)   NULL
    );
    CREATE INDEX IX_EN_GT_AFL_PARTIAL_RUN
        ON dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG (RUN_ID, DRY_RUN);
END;

/* Seed AGR */
IF OBJECT_ID('tempdb..#AGR') IS NOT NULL DROP TABLE #AGR;
SELECT
    f.AGREEMENT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(f.DELTA_KALAN_NET, 0)) AS DELTA_KALAN_NET
INTO #AGR
FROM dbo.MIG_AGR_FRK_ALL f WITH (NOLOCK)
WHERE ISNULL(f.DELTA_KALAN_NET, 0) > @Eps
  AND (@Agr IS NULL OR f.AGREEMENT_ID = @Agr)
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_AGR ON #AGR (AGREEMENT_ID);

SET @N = (SELECT COUNT(*) FROM #AGR);
SET @Msg = N'Seed EN_GT_AFL AGR n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('Seed bos — cikis.', 0, 1) WITH NOWAIT;
    RETURN;
END;

/* Open debt PT under seed AGR + AFL>eps */
IF OBJECT_ID('tempdb..#PT0') IS NOT NULL DROP TABLE #PT0;
SELECT
    CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT) AS AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    inv.LREF AS MAIN_LREF,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) AS AFL_BALANCE,
    g.DELTA_KALAN_NET AS AGR_DELTA_NET
INTO #PT0
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #AGR g
    ON g.AGREEMENT_ID = CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
INNER JOIN dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
    ON CAST(a.FATURAID AS BIGINT) = CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
  AND CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) > @Eps
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_PT0 ON #PT0 (ACCOUNT_ID, PT_LREF);

/* Account excess */
IF OBJECT_ID('tempdb..#ACC') IS NOT NULL DROP TABLE #ACC;
SELECT
    ACCOUNT_ID,
    MAX(AFL_BALANCE) AS AFL_BALANCE,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN)) AS ACC_EN_KALAN,
    CONVERT(DECIMAL(18,2), SUM(PT_KALAN) - MAX(AFL_BALANCE)) AS ACC_EXCESS
INTO #ACC
FROM #PT0
GROUP BY ACCOUNT_ID
HAVING CONVERT(DECIMAL(18,2), SUM(PT_KALAN) - MAX(AFL_BALANCE)) > @Eps;

CREATE CLUSTERED INDEX CX_ACC ON #ACC (ACCOUNT_ID);

SET @Msg = N'ACC excess n=' + CAST((SELECT COUNT(*) FROM #ACC) AS VARCHAR(20))
         + N' sum_excess=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(ACC_EXCESS), 0)) FROM #ACC));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* FIFO: keep AFL on earliest PT.LREF; apply excess on later remainder */
IF OBJECT_ID('tempdb..#CAND') IS NOT NULL DROP TABLE #CAND;
;WITH x AS (
    SELECT
        p.AGREEMENT_ID,
        p.ACCOUNT_ID,
        p.MAIN_LREF,
        p.PT_LREF,
        p.PT_PAID_OLD,
        p.PT_PAYABLE,
        p.PT_KALAN,
        a.AFL_BALANCE,
        a.ACC_EN_KALAN,
        a.ACC_EXCESS,
        p.AGR_DELTA_NET,
        CONVERT(DECIMAL(18,2),
            SUM(p.PT_KALAN) OVER (
                PARTITION BY p.ACCOUNT_ID
                ORDER BY p.PT_LREF
                ROWS UNBOUNDED PRECEDING
            ) - p.PT_KALAN
        ) AS RUN_BEFORE
    FROM #PT0 p
    INNER JOIN #ACC a ON a.ACCOUNT_ID = p.ACCOUNT_ID
)
SELECT
    AGREEMENT_ID,
    ACCOUNT_ID,
    MAIN_LREF,
    PT_LREF,
    PT_PAID_OLD,
    PT_PAYABLE,
    PT_KALAN AS PT_KALAN_OLD,
    AFL_BALANCE,
    ACC_EN_KALAN,
    ACC_EXCESS,
    AGR_DELTA_NET,
    RUN_BEFORE,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN RUN_BEFORE >= AFL_BALANCE THEN 0
            WHEN RUN_BEFORE + PT_KALAN <= AFL_BALANCE THEN PT_KALAN
            ELSE AFL_BALANCE - RUN_BEFORE
        END
    ) AS KEEP_AMT,
    CONVERT(DECIMAL(18,2),
        PT_KALAN - CASE
            WHEN RUN_BEFORE >= AFL_BALANCE THEN 0
            WHEN RUN_BEFORE + PT_KALAN <= AFL_BALANCE THEN PT_KALAN
            ELSE AFL_BALANCE - RUN_BEFORE
        END
    ) AS APPLY_AMT
INTO #CAND
FROM x
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #CAND WHERE APPLY_AMT <= @Eps;

CREATE CLUSTERED INDEX CX_CAND ON #CAND (PT_LREF);

IF OBJECT_ID('tempdb..#APPLY') IS NOT NULL DROP TABLE #APPLY;
SELECT
    c.*,
    CONVERT(DECIMAL(18,2), c.PT_PAID_OLD + c.APPLY_AMT) AS PT_PAID_NEW
INTO #APPLY
FROM #CAND c;

CREATE CLUSTERED INDEX CX_APPLY ON #APPLY (PT_LREF);

SET @N = (SELECT COUNT(*) FROM #APPLY);
SET @Msg = N'Aday PT partial n=' + CAST(@N AS VARCHAR(20))
         + N' ACC=' + CAST((SELECT COUNT(DISTINCT ACCOUNT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' AGR=' + CAST((SELECT COUNT(DISTINCT AGREEMENT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' sum_apply=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(APPLY_AMT), 0)) FROM #APPLY));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

PRINT '========== TESPIT OZET ==========';
SELECT
    COUNT(*) AS PT_PARTIAL_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(APPLY_AMT)) AS SUM_APPLY
FROM #APPLY;

SELECT
    CONVERT(DECIMAL(18,2), SUM(DISTINCT_EXCESS)) AS SUM_ACC_EXCESS
FROM (
    SELECT ACCOUNT_ID, MAX(ACC_EXCESS) AS DISTINCT_EXCESS
    FROM #APPLY
    GROUP BY ACCOUNT_ID
) d;

PRINT '========== TOP 30 ADAY ==========';
SELECT TOP 30
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_KALAN_OLD, KEEP_AMT, APPLY_AMT, PT_PAID_OLD, PT_PAID_NEW,
    AFL_BALANCE, ACC_EN_KALAN, ACC_EXCESS, AGR_DELTA_NET
FROM #APPLY
ORDER BY APPLY_AMT DESC, AGREEMENT_ID, ACCOUNT_ID, PT_LREF;

INSERT INTO dbo.MIG_EN_GT_AFL_PARTIAL_HEAL_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT,
    PT_KALAN_OLD, AFL_BALANCE, ACC_EN_KALAN, ACC_EXCESS, AGR_DELTA_NET, NOTE
)
SELECT
    @RunId, @t0, @DryRun, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT,
    PT_KALAN_OLD, AFL_BALANCE, ACC_EN_KALAN, ACC_EXCESS, AGR_DELTA_NET,
    CASE WHEN @DryRun = 1 THEN N'DRY_RUN' ELSE N'APPLY_91g' END
FROM #APPLY;

IF @N = 0
BEGIN
    RAISERROR('Aday yok — kismi excess yok.', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @DryRun = 1
BEGIN
    RAISERROR('DRY_RUN=1 — UPDATE yok. APPLY: SET @DryRun=0', 0, 1) WITH NOWAIT;
    RETURN;
END;

RAISERROR('========== APPLY ==========', 0, 1) WITH NOWAIT;
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, a.PT_PAID_NEW)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #APPLY a ON a.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'PT PAID partial n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #APPLY) x ON x.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 0
  AND NOT EXISTS (
        SELECT 1
        FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
      );

SET @N = @@ROWCOUNT;
SET @Msg = N'INV CLOSED=1 (fully paid) n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

COMMIT TRAN;

PRINT '========== POST CHECK (sample) ==========';
SELECT TOP 30
    a.AGREEMENT_ID, a.ACCOUNT_ID, a.MAIN_LREF, a.PT_LREF,
    a.APPLY_AMT,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_NOW,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN_NOW,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED_NOW
FROM #APPLY a
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = a.PT_LREF
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = a.MAIN_LREF
ORDER BY a.APPLY_AMT DESC;

SET @Msg = CONVERT(VARCHAR(30), SYSDATETIME(), 121)
         + N' | 91g DONE apply RunId=' + CONVERT(VARCHAR(30), @RunId);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
