/* =============================================================================
   FILE : prodEnergy/90_afl_frk/91i_overpay_paid_clamp_heal.sql
   PATCH (cutover EXEC zincirine KOYMA) — EN_KALAN < 0 overpay clamp

   Belirti: MIG DELTA_KALAN_NET < 0 ama AFL≈0; PT.PAID > PAYABLE
   Islem : PAID = PAYABLE (IOCODE=0, CP=0, Canceled=0)
   INV   : kalan<=eps ise CLOSED=1 (opsiyonel hiza)

   Seed  : MIG_AGR_FRK_ALL
           DELTA_KALAN_NET < -@MinAbs
           AFL_KALAN <= @Eps
           EN_KALAN  < -@Eps

   Default @DryRun=1; @MinAbs=10 (material)
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun BIT           = 1;      /* APPLY: 0 */
DECLARE @Agr    BIGINT        = NULL;
DECLARE @Eps    DECIMAL(18,2) = 0.02;
DECLARE @MinAbs DECIMAL(18,2) = 10;     /* material band; eps gurultu icin 1 */
-- SET @DryRun = 0;
-- SET @Agr = 671100;

DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
DECLARE @Msg NVARCHAR(400);
DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'SEED' ELSE CONVERT(VARCHAR(30), @Agr) END;
DECLARE @N INT;

SET @Msg = N'========== 91i OVERPAY PAID CLAMP DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Agr=' + @AgrLabel
         + N' MinAbs=' + CONVERT(VARCHAR(20), @MinAbs)
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('dbo.MIG_AGR_FRK_ALL', 'U') IS NULL
BEGIN
    RAISERROR('MIG_AGR_FRK_ALL yok — once EXEC SP_AGR_FRK_ALL', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.MIG_OVERPAY_PAID_CLAMP_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_OVERPAY_PAID_CLAMP_LOG (
        LOG_ID         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID         BIGINT         NOT NULL,
        SNAPSHOT_TS    DATETIME2(3)   NOT NULL,
        DRY_RUN        BIT            NOT NULL,
        AGREEMENT_ID   BIGINT         NULL,
        ACCOUNT_ID     BIGINT         NULL,
        MAIN_LREF      INT            NOT NULL,
        PT_LREF        INT            NOT NULL,
        PT_PAID_OLD    DECIMAL(18,2)  NULL,
        PT_PAYABLE     DECIMAL(18,2)  NULL,
        OVER_AMT       DECIMAL(18,2)  NULL,
        AGR_EN_KALAN   DECIMAL(18,2)  NULL,
        AGR_DELTA_NET  DECIMAL(18,2)  NULL,
        NOTE           NVARCHAR(80)   NULL
    );
    CREATE INDEX IX_OVERPAY_CLAMP_RUN ON dbo.MIG_OVERPAY_PAID_CLAMP_LOG (RUN_ID, DRY_RUN);
END;

IF OBJECT_ID('tempdb..#AGR') IS NOT NULL DROP TABLE #AGR;
SELECT
    f.AGREEMENT_ID,
    CONVERT(DECIMAL(18,2), ISNULL(f.EN_KALAN, 0)) AS EN_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(f.DELTA_KALAN_NET, 0)) AS DELTA_KALAN_NET
INTO #AGR
FROM dbo.MIG_AGR_FRK_ALL f WITH (NOLOCK)
WHERE ISNULL(f.DELTA_KALAN_NET, 0) <= -@MinAbs
  AND ISNULL(f.AFL_KALAN, 0) <= @Eps
  AND ISNULL(f.EN_KALAN, 0) < -@Eps
  AND (@Agr IS NULL OR f.AGREEMENT_ID = @Agr)
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_AGR ON #AGR (AGREEMENT_ID);

SET @N = (SELECT COUNT(*) FROM #AGR);
SET @Msg = N'Seed OVERPAY AGR n=' + CAST(@N AS VARCHAR(20))
         + N' sum_en_kalan=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(EN_KALAN), 0)) FROM #AGR));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('Seed bos — cikis.', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF OBJECT_ID('tempdb..#APPLY') IS NOT NULL DROP TABLE #APPLY;
SELECT
    CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT) AS AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    inv.LREF AS MAIN_LREF,
    pt.LREF AS PT_LREF,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAID, 0) - ISNULL(pt.PAYABLETOTAL, 0)) AS OVER_AMT,
    g.EN_KALAN AS AGR_EN_KALAN,
    g.DELTA_KALAN_NET AS AGR_DELTA_NET
INTO #APPLY
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #AGR g
    ON g.AGREEMENT_ID = CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  /* guvenli: PAYABLE>=0 ve PAID>PAYABLE; negatif PAYABLE dokunma */
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) >= 0
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0))
    > CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) + @Eps
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_APPLY ON #APPLY (PT_LREF);

SET @N = (SELECT COUNT(*) FROM #APPLY);
SET @Msg = N'Aday overpay PT n=' + CAST(@N AS VARCHAR(20))
         + N' AGR=' + CAST((SELECT COUNT(DISTINCT AGREEMENT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' sum_over=' + CONVERT(VARCHAR(40),
                (SELECT CONVERT(DECIMAL(18,2), ISNULL(SUM(OVER_AMT), 0)) FROM #APPLY));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

PRINT '========== TESPIT OZET ==========';
SELECT
    COUNT(*) AS PT_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(OVER_AMT)) AS SUM_OVER
FROM #APPLY;

PRINT '========== TOP 30 ==========';
SELECT TOP 30
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAYABLE, PT_PAID_OLD, OVER_AMT, AGR_EN_KALAN, AGR_DELTA_NET
FROM #APPLY
ORDER BY OVER_AMT DESC, AGREEMENT_ID;

INSERT INTO dbo.MIG_OVERPAY_PAID_CLAMP_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAYABLE, OVER_AMT,
    AGR_EN_KALAN, AGR_DELTA_NET, NOTE
)
SELECT
    @RunId, @t0, @DryRun, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAYABLE, OVER_AMT,
    AGR_EN_KALAN, AGR_DELTA_NET,
    CASE WHEN @DryRun = 1 THEN N'DRY_RUN' ELSE N'APPLY_91i' END
FROM #APPLY;

IF @N = 0
BEGIN
    RAISERROR('Aday yok.', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @DryRun = 1
BEGIN
    RAISERROR('DRY_RUN=1 — UPDATE yok. APPLY: SET @DryRun=0', 0, 1) WITH NOWAIT;
    RETURN;
END;

RAISERROR('========== APPLY ==========', 0, 1) WITH NOWAIT;
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, a.PT_PAYABLE)
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #APPLY a ON a.PT_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'PT PAID=PAYABLE clamp n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #APPLY) x ON x.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 0
  AND NOT EXISTS (
        SELECT 1
        FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
      );

SET @Msg = N'INV CLOSED=1 n=' + CAST(@@ROWCOUNT AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

COMMIT TRAN;

SET @Msg = CONVERT(VARCHAR(30), SYSDATETIME(), 121)
         + N' | 91i DONE apply RunId=' + CONVERT(VARCHAR(30), @RunId);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
