/* =============================================================================
   FILE : prodEnergy/90_afl_frk/91j_afl_tutar_kalan_heal.sql
   PATCH (cutover EXEC zincirine KOYMA) — AFL.BALANCE taban hesap kalan heal

   Teyit (196): AFL = TTK birebir; kanonik EN kalan (IOCODE=0, CANCELED=0, CP=0)
   hesap grain FATURAID = ABYS_ACCOUNT_ID.

   Bu heal (91f+91g+91h hesap grain, MIG_AGR_FRK_ALL YOK):
     CLOSE  : EN_KALAN > AFL  → APPLY = ACC_DELTA (EN-AFL), oldest-first
              (yeni faturalar acik kalir; AFL≈0 ise 91f tam kapanis)
     REOPEN : AFL > EN_KALAN  → newest-first PAID geri al (91h)
     INV    : kalan<=eps → CLOSED=1+LPD | kalan>eps → CLOSED=0
              kismi PT'de LPD yazilmaz

   YAPMAZ:
     CP=1 / CANCELED / IOCODE<>0
     Yeni PT/INV insert
     TTK guncelleme (AFL=TTK)

   Siralama:
     CLOSE  APPLY excess : INV.DATE_ ASC,  PT.LREF ASC   (eski fazla kapanir)
     REOPEN PAID odasi   : INV.DATE_ DESC, PT.LREF DESC  (yeni tahsilattan geri)

   Kullanim:
     @DryRun=1  — sayim + aday
     @DryRun=0  — APPLY
     @Mode      — ALL | CLOSE | REOPEN
     @Agr / @Acc — spot

   Sonra: EXEC dbo.SP_AGR_FRK_ALL @OnlyDiff=1;
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* >>> OPERATOR <<< */
DECLARE @DryRun  BIT           = 1;      /* APPLY: 0 */
DECLARE @Mode    VARCHAR(10)   = 'ALL';  /* ALL | CLOSE | REOPEN */
DECLARE @Agr     BIGINT        = NULL;   /* NULL = tum | tek sozlesme */
DECLARE @Acc     BIGINT        = NULL;   /* NULL = tum | tek FATURAID */
DECLARE @Eps     DECIMAL(18,2) = 0.02;
DECLARE @OnlyMig BIT           = 1;      /* 1 = MIG_IN_SCOPE=1 */
-- SET @DryRun = 0;
-- SET @Acc = 43775612;
-- SET @Agr = 1196749;

DECLARE @DryRunInt INT = CAST(@DryRun AS INT);
DECLARE @OnlyMigInt INT = CAST(@OnlyMig AS INT);
DECLARE @DoClose INT = CASE WHEN UPPER(@Mode) IN ('ALL', 'CLOSE') THEN 1 ELSE 0 END;
DECLARE @DoReopen INT = CASE WHEN UPPER(@Mode) IN ('ALL', 'REOPEN') THEN 1 ELSE 0 END;
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @RunId BIGINT = CONVERT(BIGINT, REPLACE(REPLACE(REPLACE(CONVERT(VARCHAR(19), @t0, 120), '-', ''), ' ', ''), ':', ''));
DECLARE @Msg NVARCHAR(400);
DECLARE @AgrLabel VARCHAR(30) = CASE WHEN @Agr IS NULL THEN 'ALL' ELSE CONVERT(VARCHAR(30), @Agr) END;
DECLARE @AccLabel VARCHAR(30) = CASE WHEN @Acc IS NULL THEN 'ALL' ELSE CONVERT(VARCHAR(30), @Acc) END;
DECLARE @N INT;

SET @Msg = N'========== 91j AFL TUTAR KALAN HEAL DryRun='
         + CAST(@DryRunInt AS VARCHAR(1))
         + N' Mode=' + @Mode
         + N' Agr=' + @AgrLabel
         + N' Acc=' + @AccLabel
         + N' OnlyMig=' + CAST(@OnlyMigInt AS VARCHAR(1))
         + N' ==========';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF UPPER(@Mode) NOT IN ('ALL', 'CLOSE', 'REOPEN')
BEGIN
    RAISERROR('91j: @Mode ALL|CLOSE|REOPEN olmali.', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_AFL_OPEN_DEBT yok — O50 cutover AFL gerekli', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_005_01_INVOICE', 'U') IS NULL
   OR OBJECT_ID('dbo.LS_005_01_PAYTRANS', 'U') IS NULL
BEGIN
    RAISERROR('91j: INVOICE/PAYTRANS yok.', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.MIG_AFL_TUTAR_KALAN_HEAL_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MIG_AFL_TUTAR_KALAN_HEAL_LOG (
        LOG_ID          BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID          BIGINT         NOT NULL,
        SNAPSHOT_TS     DATETIME2(3)   NOT NULL,
        DRY_RUN         BIT            NOT NULL,
        KIND            VARCHAR(10)    NOT NULL,
        AGREEMENT_ID    BIGINT         NULL,
        ACCOUNT_ID      BIGINT         NULL,
        MAIN_LREF       INT            NOT NULL,
        PT_LREF         INT            NOT NULL,
        PT_PAID_OLD     DECIMAL(18,2)  NULL,
        PT_PAID_NEW     DECIMAL(18,2)  NULL,
        APPLY_AMT       DECIMAL(18,2)  NULL,
        KEEP_AMT        DECIMAL(18,2)  NULL,
        PT_KALAN_OLD    DECIMAL(18,2)  NULL,
        PT_PAYABLE      DECIMAL(18,2)  NULL,
        AFL_BALANCE     DECIMAL(18,2)  NULL,
        ACC_EN_KALAN    DECIMAL(18,2)  NULL,
        ACC_DELTA       DECIMAL(18,2)  NULL,
        NOTE            NVARCHAR(80)   NULL
    );
    CREATE INDEX IX_AFL_TUTAR_KALAN_HEAL_RUN
        ON dbo.MIG_AFL_TUTAR_KALAN_HEAL_LOG (RUN_ID, DRY_RUN, KIND);
END;

IF OBJECT_ID('tempdb..#AGR_ACC') IS NOT NULL DROP TABLE #AGR_ACC;
CREATE TABLE #AGR_ACC (ACCOUNT_ID BIGINT NOT NULL PRIMARY KEY);

IF @Agr IS NOT NULL
BEGIN
    INSERT INTO #AGR_ACC (ACCOUNT_ID)
    SELECT DISTINCT CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
    FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
    WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
      AND (
            CAST(inv.ABYS_AGREEMENT_ID AS BIGINT) = @Agr
         OR CAST(inv.OWNERREF AS BIGINT) = @Agr
          )
    OPTION (RECOMPILE, MAXDOP 8);
END;

/* ---- AFL seed ---- */
IF OBJECT_ID('tempdb..#AFL') IS NOT NULL DROP TABLE #AFL;
SELECT
    CAST(a.FATURAID AS BIGINT) AS ACCOUNT_ID,
    CAST(a.SOZLESME_HESABI AS BIGINT) AS AFL_AGR,
    CONVERT(DECIMAL(18,2), ISNULL(a.BALANCE, 0)) AS AFL_BALANCE
INTO #AFL
FROM dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
WHERE a.FATURAID IS NOT NULL
  AND (@OnlyMigInt = 0 OR a.MIG_IN_SCOPE = 1)
  AND (@Acc IS NULL OR CAST(a.FATURAID AS BIGINT) = @Acc)
  AND (
        @Agr IS NULL
     OR CAST(a.SOZLESME_HESABI AS BIGINT) = @Agr
     OR EXISTS (SELECT 1 FROM #AGR_ACC x WHERE x.ACCOUNT_ID = CAST(a.FATURAID AS BIGINT))
      )
OPTION (RECOMPILE, MAXDOP 8);

CREATE UNIQUE CLUSTERED INDEX CX_AFL ON #AFL (ACCOUNT_ID);

SET @N = (SELECT COUNT(*) FROM #AFL);
SET @Msg = N'AFL seed n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('AFL seed bos — cikis.', 0, 1) WITH NOWAIT;
    RETURN;
END;

/* ---- Kanonik EN kalan (borc PT) ---- */
IF OBJECT_ID('tempdb..#EN') IS NOT NULL DROP TABLE #EN;
SELECT
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2),
        SUM(CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0))
          - CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)))
    ) AS EN_KALAN
INTO #EN
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #AFL a ON a.ACCOUNT_ID = CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
GROUP BY CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
OPTION (RECOMPILE, MAXDOP 8);

CREATE UNIQUE CLUSTERED INDEX CX_EN ON #EN (ACCOUNT_ID);

/* ---- Hesap delta ---- */
IF OBJECT_ID('tempdb..#ACC') IS NOT NULL DROP TABLE #ACC;
SELECT
    a.ACCOUNT_ID,
    a.AFL_AGR,
    a.AFL_BALANCE,
    CONVERT(DECIMAL(18,2), ISNULL(e.EN_KALAN, 0)) AS EN_KALAN,
    CONVERT(DECIMAL(18,2), ISNULL(e.EN_KALAN, 0) - a.AFL_BALANCE) AS ACC_DELTA,
    CASE
        WHEN CONVERT(DECIMAL(18,2), ISNULL(e.EN_KALAN, 0) - a.AFL_BALANCE) > @Eps
            THEN 'CLOSE'
        WHEN CONVERT(DECIMAL(18,2), a.AFL_BALANCE - ISNULL(e.EN_KALAN, 0)) > @Eps
            THEN 'REOPEN'
        ELSE 'MATCH'
    END AS KIND
INTO #ACC
FROM #AFL a
LEFT JOIN #EN e ON e.ACCOUNT_ID = a.ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #ACC WHERE KIND = 'MATCH';
IF @DoClose = 0  DELETE FROM #ACC WHERE KIND = 'CLOSE';
IF @DoReopen = 0 DELETE FROM #ACC WHERE KIND = 'REOPEN';

CREATE UNIQUE CLUSTERED INDEX CX_ACC ON #ACC (ACCOUNT_ID);

PRINT '========== HESAP OZET ==========';
SELECT
    KIND,
    COUNT(*) AS ACC_CNT,
    CONVERT(DECIMAL(18,2), SUM(AFL_BALANCE)) AS AFL_SUM,
    CONVERT(DECIMAL(18,2), SUM(EN_KALAN)) AS EN_SUM,
    CONVERT(DECIMAL(18,2), SUM(ACC_DELTA)) AS SUM_DELTA
FROM #ACC
GROUP BY KIND
ORDER BY KIND;

SET @N = (SELECT COUNT(*) FROM #ACC);
SET @Msg = N'Aday hesap n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF @N = 0
BEGIN
    RAISERROR('Aday hesap yok — AFL=EN (eps).', 0, 1) WITH NOWAIT;
    RETURN;
END;

PRINT '========== BIG_CLOSE (excess>=10000) ==========';
SELECT TOP 20
    ACCOUNT_ID, AFL_AGR, AFL_BALANCE, EN_KALAN, ACC_DELTA
FROM #ACC
WHERE KIND = 'CLOSE'
  AND ACC_DELTA >= 10000
ORDER BY ACC_DELTA DESC;

/* ---- Borc PT (CLOSE: acik kalan | REOPEN: payable>0, paid odasi) ---- */
IF OBJECT_ID('tempdb..#PT0') IS NOT NULL DROP TABLE #PT0;
SELECT
    CAST(ISNULL(inv.ABYS_AGREEMENT_ID, inv.OWNERREF) AS BIGINT) AS AGREEMENT_ID,
    CAST(inv.ABYS_ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    inv.LREF AS MAIN_LREF,
    pt.LREF AS PT_LREF,
    inv.DATE_ AS INV_DATE,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_OLD,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN,
    acc.AFL_BALANCE,
    acc.EN_KALAN AS ACC_EN_KALAN,
    acc.ACC_DELTA,
    acc.KIND
INTO #PT0
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN #ACC acc
    ON acc.ACCOUNT_ID = CAST(inv.ABYS_ACCOUNT_ID AS BIGINT)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
   AND ISNULL(pt.CANCELED, 0) = 0
   AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) > @Eps
  AND (
        (acc.KIND = 'CLOSE'  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps)
     OR (acc.KIND = 'REOPEN' AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) > @Eps)
      )
OPTION (RECOMPILE, MAXDOP 8);

CREATE CLUSTERED INDEX CX_PT0 ON #PT0 (KIND, ACCOUNT_ID, PT_LREF);

/* ---- CLOSE: oldest-first APPLY = ACC_DELTA (overpay PT yuzunden SUM(acik)≠EN) ---- */
IF OBJECT_ID('tempdb..#CLOSE') IS NOT NULL DROP TABLE #CLOSE;
;WITH x AS (
    SELECT
        p.*,
        CONVERT(DECIMAL(18,2), p.ACC_DELTA) AS EXCESS,
        CONVERT(DECIMAL(18,2),
            SUM(p.PT_KALAN) OVER (
                PARTITION BY p.ACCOUNT_ID
                ORDER BY p.INV_DATE ASC, p.PT_LREF ASC
                ROWS UNBOUNDED PRECEDING
            ) - p.PT_KALAN
        ) AS RUN_BEFORE
    FROM #PT0 p
    WHERE p.KIND = 'CLOSE'
)
SELECT
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN AS PT_KALAN_OLD,
    AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA,
    CONVERT(DECIMAL(18,2),
        PT_KALAN - CASE
            WHEN RUN_BEFORE >= EXCESS THEN 0
            WHEN RUN_BEFORE + PT_KALAN <= EXCESS THEN PT_KALAN
            ELSE EXCESS - RUN_BEFORE
        END
    ) AS KEEP_AMT,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN RUN_BEFORE >= EXCESS THEN 0
            WHEN RUN_BEFORE + PT_KALAN <= EXCESS THEN PT_KALAN
            ELSE EXCESS - RUN_BEFORE
        END
    ) AS APPLY_AMT
INTO #CLOSE
FROM x
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #CLOSE WHERE APPLY_AMT <= @Eps;

/* ---- REOPEN: newest-first PAID odasindan shortfall ---- */
IF OBJECT_ID('tempdb..#REOPEN') IS NOT NULL DROP TABLE #REOPEN;
;WITH x AS (
    SELECT
        p.*,
        CONVERT(DECIMAL(18,2), -p.ACC_DELTA) AS SHORTFALL,
        CONVERT(DECIMAL(18,2), CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END) AS PAID_ROOM,
        CONVERT(DECIMAL(18,2),
            SUM(CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END) OVER (
                PARTITION BY p.ACCOUNT_ID
                ORDER BY p.INV_DATE DESC, p.PT_LREF DESC
                ROWS UNBOUNDED PRECEDING
            ) - CASE WHEN p.PT_PAID_OLD > 0 THEN p.PT_PAID_OLD ELSE 0 END
        ) AS RUN_BEFORE
    FROM #PT0 p
    WHERE p.KIND = 'REOPEN'
)
SELECT
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN AS PT_KALAN_OLD,
    AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA,
    CONVERT(DECIMAL(18,2), 0) AS KEEP_AMT,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN PAID_ROOM <= 0 THEN 0
            WHEN RUN_BEFORE >= SHORTFALL THEN 0
            WHEN RUN_BEFORE + PAID_ROOM <= SHORTFALL THEN PAID_ROOM
            ELSE SHORTFALL - RUN_BEFORE
        END
    ) AS APPLY_AMT
INTO #REOPEN
FROM x
OPTION (RECOMPILE, MAXDOP 8);

DELETE FROM #REOPEN WHERE APPLY_AMT <= @Eps;

IF OBJECT_ID('tempdb..#APPLY') IS NOT NULL DROP TABLE #APPLY;
SELECT
    'CLOSE' AS KIND,
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN_OLD,
    AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA, KEEP_AMT, APPLY_AMT,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN PT_PAID_OLD + APPLY_AMT > PT_PAYABLE THEN PT_PAYABLE
            ELSE PT_PAID_OLD + APPLY_AMT
        END
    ) AS PT_PAID_NEW
INTO #APPLY
FROM #CLOSE
UNION ALL
SELECT
    'REOPEN',
    AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAID_OLD, PT_PAYABLE, PT_KALAN_OLD,
    AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA, KEEP_AMT, APPLY_AMT,
    CONVERT(DECIMAL(18,2),
        CASE
            WHEN PT_PAID_OLD - APPLY_AMT < 0 THEN 0
            ELSE PT_PAID_OLD - APPLY_AMT
        END
    )
FROM #REOPEN;

CREATE CLUSTERED INDEX CX_APPLY ON #APPLY (PT_LREF);

PRINT '========== SKIP (hesap var, PT apply yok) ==========';
SELECT
    a.KIND,
    COUNT(*) AS ACC_SKIP
FROM #ACC a
WHERE NOT EXISTS (SELECT 1 FROM #APPLY x WHERE x.ACCOUNT_ID = a.ACCOUNT_ID)
GROUP BY a.KIND;

SELECT TOP 20
    a.KIND, a.ACCOUNT_ID, a.AFL_AGR, a.AFL_BALANCE, a.EN_KALAN, a.ACC_DELTA
FROM #ACC a
WHERE NOT EXISTS (SELECT 1 FROM #APPLY x WHERE x.ACCOUNT_ID = a.ACCOUNT_ID)
ORDER BY ABS(a.ACC_DELTA) DESC, a.ACCOUNT_ID;

SET @N = (SELECT COUNT(*) FROM #APPLY);
SET @Msg = N'Aday PT n=' + CAST(@N AS VARCHAR(20))
         + N' ACC=' + CAST((SELECT COUNT(DISTINCT ACCOUNT_ID) FROM #APPLY) AS VARCHAR(20))
         + N' CLOSE_PT=' + CAST((SELECT COUNT(*) FROM #APPLY WHERE KIND = 'CLOSE') AS VARCHAR(20))
         + N' REOPEN_PT=' + CAST((SELECT COUNT(*) FROM #APPLY WHERE KIND = 'REOPEN') AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

PRINT '========== TESPIT OZET ==========';
SELECT
    KIND,
    COUNT(*) AS PT_CNT,
    COUNT(DISTINCT ACCOUNT_ID) AS ACC_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(APPLY_AMT)) AS SUM_APPLY
FROM #APPLY
GROUP BY KIND
ORDER BY KIND;

PRINT '========== TOP 30 ADAY ==========';
SELECT TOP 30
    KIND, AGREEMENT_ID, ACCOUNT_ID, MAIN_LREF, PT_LREF,
    PT_PAYABLE, PT_PAID_OLD, KEEP_AMT, APPLY_AMT, PT_PAID_NEW,
    PT_KALAN_OLD, AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA
FROM #APPLY
ORDER BY APPLY_AMT DESC, KIND, ACCOUNT_ID, PT_LREF;

INSERT INTO dbo.MIG_AFL_TUTAR_KALAN_HEAL_LOG (
    RUN_ID, SNAPSHOT_TS, DRY_RUN, KIND, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT, KEEP_AMT,
    PT_KALAN_OLD, PT_PAYABLE, AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA, NOTE
)
SELECT
    @RunId, @t0, @DryRun, KIND, AGREEMENT_ID, ACCOUNT_ID,
    MAIN_LREF, PT_LREF, PT_PAID_OLD, PT_PAID_NEW, APPLY_AMT, KEEP_AMT,
    PT_KALAN_OLD, PT_PAYABLE, AFL_BALANCE, ACC_EN_KALAN, ACC_DELTA,
    CASE WHEN @DryRunInt = 1 THEN N'DRY_RUN' ELSE N'APPLY_91j' END
FROM #APPLY;

IF @N = 0
BEGIN
    RAISERROR('Aday PT yok — PAID odasi/excess yok.', 0, 1) WITH NOWAIT;
    RETURN;
END;

IF @DryRunInt = 1
BEGIN
    RAISERROR('DRY_RUN=1 — UPDATE yok. APPLY: SET @DryRun=0', 0, 1) WITH NOWAIT;
    RETURN;
END;

RAISERROR('========== APPLY ==========', 0, 1) WITH NOWAIT;
BEGIN TRAN;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, a.PT_PAID_NEW),
    pt.LASTPAIDDATE = CASE
        WHEN a.KIND = 'REOPEN' THEN pt.LASTPAIDDATE
        WHEN CONVERT(DECIMAL(18,2), a.PT_PAID_NEW)
           < CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) - @Eps
            THEN pt.LASTPAIDDATE
        WHEN pt.LASTPAIDDATE IS NOT NULL THEN pt.LASTPAIDDATE
        WHEN pt.DATE_ IS NOT NULL
             AND CAST(pt.DATE_ AS DATETIME2) >= CAST('1900-01-01' AS DATETIME2)
             AND CAST(pt.DATE_ AS DATETIME2) <= CAST('2079-06-06 23:59:00' AS DATETIME2)
        THEN CAST(CAST(pt.DATE_ AS DATETIME2) AS SMALLDATETIME)
        WHEN inv.DATE_ IS NOT NULL
             AND CAST(inv.DATE_ AS DATETIME2) >= CAST('1900-01-01' AS DATETIME2)
             AND CAST(inv.DATE_ AS DATETIME2) <= CAST('2079-06-06 23:59:00' AS DATETIME2)
        THEN CAST(CAST(inv.DATE_ AS DATETIME2) AS SMALLDATETIME)
        ELSE pt.LASTPAIDDATE
    END
FROM dbo.LS_005_01_PAYTRANS pt
INNER JOIN #APPLY a ON a.PT_LREF = pt.LREF
INNER JOIN dbo.LS_005_01_INVOICE inv ON inv.LREF = pt.INVOICEREF
WHERE ISNULL(pt.IOCODE, 0) = 0
  AND ISNULL(pt.CANCELED, 0) = 0
  AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0;

SET @N = @@ROWCOUNT;
SET @Msg = N'PT PAID n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* CLOSE: tam odenen INV → CLOSED=1 */
UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT),
    inv.LASTPAIDDATE = CASE
        WHEN inv.LASTPAIDDATE IS NOT NULL THEN inv.LASTPAIDDATE
        WHEN inv.DATE_ IS NOT NULL
             AND CAST(inv.DATE_ AS DATETIME2) >= CAST('1900-01-01' AS DATETIME2)
             AND CAST(inv.DATE_ AS DATETIME2) <= CAST('2079-06-06 23:59:00' AS DATETIME2)
        THEN CAST(CAST(inv.DATE_ AS DATETIME2) AS SMALLDATETIME)
        ELSE inv.LASTPAIDDATE
    END
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #APPLY WHERE KIND = 'CLOSE') x
    ON x.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND (
        ISNULL(inv.CLOSED, 0) = 0
     OR inv.LASTPAIDDATE IS NULL
      )
  AND NOT EXISTS (
        SELECT 1
        FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
      );

SET @N = @@ROWCOUNT;
SET @Msg = N'INV CLOSED=1 n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* REOPEN: kalan>eps → CLOSED=0 */
UPDATE inv
SET inv.CLOSED = CAST(0 AS BIT)
FROM dbo.LS_005_01_INVOICE inv
INNER JOIN (SELECT DISTINCT MAIN_LREF FROM #APPLY WHERE KIND = 'REOPEN') x
    ON x.MAIN_LREF = inv.LREF
WHERE ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(inv.CLOSED, 0) = 1
  AND EXISTS (
        SELECT 1
        FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        WHERE pt.INVOICEREF = inv.LREF
          AND ISNULL(pt.IOCODE, 0) = 0
          AND ISNULL(pt.CANCELED, 0) = 0
          AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
          AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) > @Eps
      );

SET @N = @@ROWCOUNT;
SET @Msg = N'INV CLOSED=0 n=' + CAST(@N AS VARCHAR(20));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

COMMIT TRAN;

PRINT '========== POST CHECK (sample) ==========';
SELECT TOP 30
    a.KIND, a.AGREEMENT_ID, a.ACCOUNT_ID, a.MAIN_LREF, a.PT_LREF,
    a.APPLY_AMT, a.AFL_BALANCE, a.ACC_DELTA,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0)) AS PT_PAID_NOW,
    CONVERT(DECIMAL(18,2), ISNULL(pt.PAYABLETOTAL, 0)) AS PT_PAYABLE,
    CONVERT(DECIMAL(18,2),
        ISNULL(pt.PAYABLETOTAL, 0) - ISNULL(pt.PAID, 0)) AS PT_KALAN_NOW,
    ISNULL(inv.CLOSED, 0) AS MAIN_CLOSED_NOW
FROM #APPLY a
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.LREF = a.PT_LREF
INNER JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = a.MAIN_LREF
ORDER BY a.APPLY_AMT DESC;

SET @Msg = CONVERT(VARCHAR(30), SYSDATETIME(), 121)
         + N' | 91j DONE apply RunId=' + CONVERT(VARCHAR(30), @RunId);
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
