/* ============================================================
   FILE : prodEnergy/90_afl_frk/93b_tuketim_tutar_ssms.sql
   SSMS ad-hoc — kalici tablo YOK (#temp only)
   Kaynak (hepsi energy):
     LS_005_01_INVOICE / INVLINES / PAYTRANS
     LS_AFL_OPEN_DEBT  (LEFT ON FATURAID = ACCOUNT_ID)
   Grain: ACCOUNT_ID = ABYS_ACCOUNT_ID = AFL.FATURAID
   DOP : OPTION (RECOMPILE, MAXDOP 24) — 597 WIRE ile ayni
   Cikti: ozet + AFL_CHECK + TOP AMT_DIFF + (istege) #TTK spot
   ============================================================ */
USE energy;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @Eps     DECIMAL(18,2) = 0.02;
DECLARE @TopN    INT = 50;
DECLARE @OnlyMig BIT = 1;   -- 1 = AFL MIG_IN_SCOPE=1
DECLARE @Dop     INT = 24;  -- bilgilendirme; OPTION/INDEX asagida 24
DECLARE @Msg     NVARCHAR(400);

IF OBJECT_ID('dbo.LS_005_01_INVOICE', 'U') IS NULL
   OR OBJECT_ID('dbo.LS_005_01_INVLINES', 'U') IS NULL
   OR OBJECT_ID('dbo.LS_005_01_PAYTRANS', 'U') IS NULL
BEGIN
    RAISERROR('INV/INVLINES/PAYTRANS yok.', 16, 1);
    RETURN;
END

IF OBJECT_ID('dbo.LS_AFL_OPEN_DEBT', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_AFL_OPEN_DEBT yok — once AFL dump energy''ye.', 16, 1);
    RETURN;
END

SET @Msg = N'TTK SSMS START | #temp only | MAXDOP=' + CAST(@Dop AS NVARCHAR(10))
    + N' | AFL LEFT ACCOUNT_ID=FATURAID';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('tempdb..#EN_HDR') IS NOT NULL DROP TABLE #EN_HDR;
IF OBJECT_ID('tempdb..#EN_LINE') IS NOT NULL DROP TABLE #EN_LINE;
IF OBJECT_ID('tempdb..#EN_PAY') IS NOT NULL DROP TABLE #EN_PAY;
IF OBJECT_ID('tempdb..#AFL') IS NOT NULL DROP TABLE #AFL;
IF OBJECT_ID('tempdb..#TTK') IS NOT NULL DROP TABLE #TTK;

/* ---------- 1) Fatura baslik ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    MAX(inv.ABYS_AGREEMENT_ID) AS AGREEMENT_ID,
    MAX(inv.ABYS_ACCRUE_TYPE_ID) AS ACCRUE_TYPE_ID,
    MAX(inv.DUEDATE) AS SON_ODEME_TARIHI,
    MAX(CAST(inv.DATE_ AS DATE)) AS TAHAKKUK_TARIHI,
    MAX(LEFT(CAST(inv.FICHENO AS VARCHAR(45)), 45)) AS FATURA_SERI_SIRA,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_M3, 0)))) AS M3,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_KWH, 0)))) AS KWH,
    CONVERT(DECIMAL(18,6), SUM(CONVERT(DECIMAL(18,6), ISNULL(inv.ABYS_CONSUMPTION, 0)))) AS CONSUMPTION
INTO #EN_HDR
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_EN_HDR ON #EN_HDR (ACCOUNT_ID) WITH (MAXDOP = 24);

/* ---------- 2) Satir tutarlari ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 939
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 7658
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS SKB_TUTARI,
    CONVERT(DECIMAL(18,2), SUM(
        CASE WHEN il.ABYS_INCOME_ID = 169
             THEN CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
                  * ISNULL(il.ABYS_STATUS, 1))
             ELSE 0 END
    )) AS KDV_TUTARI,
    CONVERT(DECIMAL(18,6), MAX(
        CASE WHEN il.ABYS_INCOME_ID = 939
             THEN CONVERT(DECIMAL(18,6), ISNULL(il.UNITPRICE, il.ABYS_UNIT_PRICE))
             ELSE NULL END
    )) AS GAZ_M3_BIRIM_FIYAT,
    CONVERT(DECIMAL(18,2), SUM(
        CONVERT(DECIMAL(18,2), ISNULL(il.ABYS_AMOUNT_RAW, il.GRANDTOTAL)
             * ISNULL(il.ABYS_STATUS, 1))
    )) AS TOPLAM_TAHAKKUK
INTO #EN_LINE
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_INVLINES il WITH (NOLOCK)
    ON il.INVOICEREF = inv.LREF
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
  AND ISNULL(il.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_EN_LINE ON #EN_LINE (ACCOUNT_ID) WITH (MAXDOP = 24);

/* ---------- 3) Odeme ---------- */
SELECT
    inv.ABYS_ACCOUNT_ID AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), SUM(
        CASE
            WHEN ISNULL(pt.CANCELED, 0) = 0
             AND ISNULL(pt.CANCELLATIONPAYMENT, 0) = 0
            THEN CONVERT(DECIMAL(18,2), ISNULL(pt.PAID, 0))
            ELSE 0
        END
    )) AS PAID_SUM
INTO #EN_PAY
FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
INNER JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
    ON pt.INVOICEREF = inv.LREF
   AND ISNULL(pt.IOCODE, 0) = 0
WHERE inv.ABYS_ACCOUNT_ID IS NOT NULL
  AND ISNULL(inv.IOCODE, 0) = 0
  AND ISNULL(inv.CANCELED, 0) = 0
GROUP BY inv.ABYS_ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_EN_PAY ON #EN_PAY (ACCOUNT_ID) WITH (MAXDOP = 24);

/* ---------- 4) AFL ---------- */
SELECT
    CAST(a.FATURAID AS BIGINT) AS ACCOUNT_ID,
    CONVERT(DECIMAL(18,2), a.BALANCE) AS AFL_BALANCE,
    LEFT(CAST(a.TAKSIT_DURUMU AS VARCHAR(1)), 1) AS AFL_TAKSIT,
    LEFT(CAST(a.YT_DURUMU AS VARCHAR(3)), 3) AS AFL_YT,
    CAST(ISNULL(a.MIG_IN_SCOPE, 1) AS TINYINT) AS AFL_MIG_IN_SCOPE
INTO #AFL
FROM dbo.LS_AFL_OPEN_DEBT a WITH (NOLOCK)
WHERE (@OnlyMig = 0 OR ISNULL(a.MIG_IN_SCOPE, 1) = 1)
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_AFL ON #AFL (ACCOUNT_ID) WITH (MAXDOP = 24);

/* ---------- 5) #TTK = energy mirror + AFL LEFT ---------- */
SELECT
    CAST(h.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    CAST(h.AGREEMENT_ID AS BIGINT) AS AGREEMENT_ID,
    CAST(h.ACCRUE_TYPE_ID AS INT) AS ACCRUE_TYPE_ID,
    h.SON_ODEME_TARIHI,
    h.TAHAKKUK_TARIHI,
    h.FATURA_SERI_SIRA,
    CONVERT(DECIMAL(18,6), h.M3) AS M3,
    CONVERT(DECIMAL(18,6), h.KWH) AS KWH,
    CONVERT(DECIMAL(18,6), h.CONSUMPTION) AS CONSUMPTION,
    CONVERT(DECIMAL(18,2), ISNULL(l.GAZ_TUTARI, 0)) AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), ISNULL(l.SKB_TUTARI, 0)) AS SKB_TUTARI,
    CONVERT(DECIMAL(18,2), ISNULL(l.KDV_TUTARI, 0)) AS KDV_TUTARI,
    CONVERT(DECIMAL(18,6), l.GAZ_M3_BIRIM_FIYAT) AS GAZ_M3_BIRIM_FIYAT,
    CONVERT(DECIMAL(18,2), ISNULL(l.TOPLAM_TAHAKKUK, 0)) AS TOPLAM_TAHAKKUK,
    CONVERT(DECIMAL(18,2), -ISNULL(p.PAID_SUM, 0)) AS ODENEN_TUTAR,
    CONVERT(DECIMAL(18,2),
        ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
    ) AS KALAN_TUTAR,
    CASE WHEN afl.ACCOUNT_ID IS NOT NULL THEN CAST(1 AS TINYINT) ELSE CAST(0 AS TINYINT) END AS AFL_HIT,
    afl.AFL_BALANCE,
    afl.AFL_TAKSIT,
    afl.AFL_YT,
    afl.AFL_MIG_IN_SCOPE,
    CONVERT(DECIMAL(18,2),
        CASE WHEN afl.ACCOUNT_ID IS NULL THEN NULL
             ELSE ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
                - ISNULL(afl.AFL_BALANCE, 0)
        END
    ) AS DELTA_AFL_KALAN,
    CASE
        WHEN afl.ACCOUNT_ID IS NULL THEN 'NO_AFL'
        WHEN ABS(
                ISNULL(l.TOPLAM_TAHAKKUK, 0) - ISNULL(p.PAID_SUM, 0)
              - ISNULL(afl.AFL_BALANCE, 0)
             ) <= @Eps THEN 'MATCH'
        ELSE 'AMT_DIFF'
    END AS AFL_CHECK
INTO #TTK
FROM #EN_HDR h
LEFT JOIN #EN_LINE l ON l.ACCOUNT_ID = h.ACCOUNT_ID
LEFT JOIN #EN_PAY  p ON p.ACCOUNT_ID = h.ACCOUNT_ID
LEFT JOIN #AFL afl ON afl.ACCOUNT_ID = h.ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 24);

CREATE CLUSTERED INDEX CX_TTK ON #TTK (ACCOUNT_ID) WITH (MAXDOP = 24);

/* ========== RECON ========== */
PRINT '=== 1) TTK ozet ===';
SELECT
    COUNT(*) AS TTK_CNT,
    COUNT(DISTINCT AGREEMENT_ID) AS AGR_CNT,
    CONVERT(DECIMAL(18,2), SUM(M3)) AS M3_SUM,
    CONVERT(DECIMAL(18,2), SUM(TOPLAM_TAHAKKUK)) AS TAH_SUM,
    CONVERT(DECIMAL(18,2), SUM(ODENEN_TUTAR)) AS ODE_SUM,
    CONVERT(DECIMAL(18,2), SUM(KALAN_TUTAR)) AS KALAN_SUM,
    SUM(CASE WHEN AFL_HIT = 1 THEN 1 ELSE 0 END) AS AFL_HIT_CNT,
    CONVERT(DECIMAL(18,2), SUM(AFL_BALANCE)) AS AFL_BAL_SUM
FROM #TTK
OPTION (RECOMPILE, MAXDOP 24);

PRINT '=== 2) AFL_CHECK (KALAN vs AFL.BALANCE) ===';
SELECT
    AFL_CHECK,
    COUNT(*) AS CNT,
    CONVERT(DECIMAL(18,2), SUM(KALAN_TUTAR)) AS KALAN_SUM,
    CONVERT(DECIMAL(18,2), SUM(AFL_BALANCE)) AS AFL_BAL_SUM,
    CONVERT(DECIMAL(18,2), SUM(DELTA_AFL_KALAN)) AS DELTA_SUM
FROM #TTK
GROUP BY AFL_CHECK
ORDER BY AFL_CHECK
OPTION (RECOMPILE, MAXDOP 24);

PRINT '=== 3) AFL_ONLY (AFL var, energy TTK yok) ===';
SELECT COUNT(*) AS AFL_ONLY_CNT
FROM #AFL a
WHERE NOT EXISTS (SELECT 1 FROM #TTK t WHERE t.ACCOUNT_ID = a.ACCOUNT_ID)
OPTION (RECOMPILE, MAXDOP 24);

PRINT '=== 4) TOP AMT_DIFF ===';
SELECT TOP (@TopN)
    ACCOUNT_ID, AGREEMENT_ID, ACCRUE_TYPE_ID,
    M3, TOPLAM_TAHAKKUK, ODENEN_TUTAR, KALAN_TUTAR,
    AFL_BALANCE, DELTA_AFL_KALAN,
    AFL_TAKSIT, AFL_YT, AFL_MIG_IN_SCOPE, AFL_CHECK
FROM #TTK
WHERE AFL_CHECK = 'AMT_DIFF'
ORDER BY ABS(ISNULL(DELTA_AFL_KALAN, 0)) DESC
OPTION (RECOMPILE, MAXDOP 24);

PRINT '=== 5) Spot MATCH ornek ===';
SELECT TOP (20)
    ACCOUNT_ID, AGREEMENT_ID, KALAN_TUTAR, AFL_BALANCE, DELTA_AFL_KALAN, AFL_CHECK
FROM #TTK
WHERE AFL_CHECK = 'MATCH'
ORDER BY ACCOUNT_ID
OPTION (RECOMPILE, MAXDOP 24);

SET @Msg = N'TTK SSMS DONE | MAXDOP=' + CAST(@Dop AS NVARCHAR(10))
    + N' | #TTK session''da — SELECT * FROM #TTK WHERE AFL_CHECK=''AMT_DIFF''';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
