/* ============================================================
   FILE : prodEnergy/90_afl_frk/94_tuketim_tutar_frk.sql
   FAZ  : B10 standalone — Oracle TTK (master) vs energy TTK FRK + LOG
   Grain: ACCOUNT_ID = CS_ACCOUNT.ID = INVOICE.ABYS_ACCOUNT_ID
   Onkosul:
     - izgazMGR.dbo.TUKETIM_TUTAR_KONTROL (Oracle O59 dump)
     - energy.dbo.TUKETIM_TUTAR_KONTROL (93_tuketim_tutar_kontrol.sql)
   KIND: MATCH | AMT_DIFF | ONLY_ORA | ONLY_EN  (birincil: KALAN + M3)
   @ExcludeEmanet=1 → ACCRUE_TYPE_ID <> 14
   ============================================================ */
USE energy;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @Eps           DECIMAL(18,2) = 0.02;
DECLARE @EpsM3         DECIMAL(18,6) = 0.001;
DECLARE @ExcludeEmanet BIT = 1;          -- 1 = ACCRUE_TYPE_ID <> 14
DECLARE @RunId         UNIQUEIDENTIFIER = NEWID();
DECLARE @AsOf          DATE;
DECLARE @Msg           NVARCHAR(400);

IF OBJECT_ID('izgazMGR.dbo.TUKETIM_TUTAR_KONTROL', 'U') IS NULL
BEGIN
    RAISERROR('izgazMGR.dbo.TUKETIM_TUTAR_KONTROL yok. Once Oracle O59 CTAS + dump.', 16, 1);
    RETURN;
END

IF OBJECT_ID('energy.dbo.TUKETIM_TUTAR_KONTROL', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.TUKETIM_TUTAR_KONTROL yok. Once 93_tuketim_tutar_kontrol.sql', 16, 1);
    RETURN;
END

SELECT TOP (1) @AsOf = TRY_CAST(AS_OF_DATE AS DATE)
FROM izgazMGR.dbo.TUKETIM_TUTAR_KONTROL WITH (NOLOCK);

IF OBJECT_ID('energy.dbo.MIG_TTK_FRK_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE energy.dbo.MIG_TTK_FRK_LOG (
        LOG_ID         BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        RUN_ID         UNIQUEIDENTIFIER NOT NULL,
        AS_OF_DATE     DATE NULL,
        SNAPSHOT_TS    DATETIME2(3) NOT NULL CONSTRAINT DF_TTK_FRK_TS DEFAULT (SYSDATETIME()),
        ACCOUNT_ID     BIGINT NOT NULL,
        AGREEMENT_ID   BIGINT NULL,
        ACCRUE_TYPE_ID INT NULL,
        ORA_M3         DECIMAL(18,6) NULL,
        EN_M3          DECIMAL(18,6) NULL,
        DELTA_M3       DECIMAL(18,6) NULL,
        ORA_TAH        DECIMAL(18,2) NULL,
        EN_TAH         DECIMAL(18,2) NULL,
        DELTA_TAH      DECIMAL(18,2) NULL,
        ORA_GAZ        DECIMAL(18,2) NULL,
        EN_GAZ         DECIMAL(18,2) NULL,
        ORA_KALAN      DECIMAL(18,2) NULL,
        EN_KALAN       DECIMAL(18,2) NULL,
        DELTA_KALAN    DECIMAL(18,2) NULL,
        KIND           VARCHAR(16) NOT NULL,  -- MATCH | AMT_DIFF | ONLY_ORA | ONLY_EN
        NOTE           NVARCHAR(200) NULL
    );
    CREATE NONCLUSTERED INDEX IX_MIG_TTK_FRK_RUN
        ON energy.dbo.MIG_TTK_FRK_LOG (RUN_ID, KIND)
        INCLUDE (ACCOUNT_ID, ORA_KALAN, EN_KALAN, DELTA_KALAN);
END

SET @Msg = N'TTK FRK START run=' + CAST(@RunId AS NVARCHAR(36));
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---------- Energy snapshot ---------- */
IF OBJECT_ID('tempdb..#EN_TTK') IS NOT NULL DROP TABLE #EN_TTK;

SELECT
    CAST(e.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    CAST(e.AGREEMENT_ID AS BIGINT) AS AGREEMENT_ID,
    CAST(e.ACCRUE_TYPE_ID AS INT) AS ACCRUE_TYPE_ID,
    CONVERT(DECIMAL(18,6), e.M3) AS M3,
    CONVERT(DECIMAL(18,2), e.GAZ_TUTARI) AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), e.TOPLAM_TAHAKKUK) AS TOPLAM_TAHAKKUK,
    CONVERT(DECIMAL(18,2), e.KALAN_TUTAR) AS KALAN_TUTAR
INTO #EN_TTK
FROM energy.dbo.TUKETIM_TUTAR_KONTROL e WITH (NOLOCK)
WHERE (@ExcludeEmanet = 0 OR ISNULL(e.ACCRUE_TYPE_ID, -1) <> 14);

CREATE CLUSTERED INDEX CX_EN_TTK ON #EN_TTK (ACCOUNT_ID);

/* ---------- Oracle master dump ---------- */
IF OBJECT_ID('tempdb..#ORA_TTK') IS NOT NULL DROP TABLE #ORA_TTK;

SELECT
    CAST(o.ACCOUNT_ID AS BIGINT) AS ACCOUNT_ID,
    CAST(o.AGREEMENT_ID AS BIGINT) AS AGREEMENT_ID,
    CAST(o.ACCRUE_TYPE_ID AS INT) AS ACCRUE_TYPE_ID,
    CONVERT(DECIMAL(18,6), o.M3) AS M3,
    CONVERT(DECIMAL(18,2), o.GAZ_TUTARI) AS GAZ_TUTARI,
    CONVERT(DECIMAL(18,2), o.TOPLAM_TAHAKKUK) AS TOPLAM_TAHAKKUK,
    CONVERT(DECIMAL(18,2), o.KALAN_TUTAR) AS KALAN_TUTAR
INTO #ORA_TTK
FROM izgazMGR.dbo.TUKETIM_TUTAR_KONTROL o WITH (NOLOCK)
WHERE (@ExcludeEmanet = 0 OR ISNULL(o.ACCRUE_TYPE_ID, -1) <> 14);

CREATE CLUSTERED INDEX CX_ORA_TTK ON #ORA_TTK (ACCOUNT_ID);

/* ---------- Full outer fark → log ---------- */
INSERT INTO energy.dbo.MIG_TTK_FRK_LOG (
    RUN_ID, AS_OF_DATE, ACCOUNT_ID, AGREEMENT_ID, ACCRUE_TYPE_ID,
    ORA_M3, EN_M3, DELTA_M3,
    ORA_TAH, EN_TAH, DELTA_TAH,
    ORA_GAZ, EN_GAZ,
    ORA_KALAN, EN_KALAN, DELTA_KALAN,
    KIND, NOTE
)
SELECT
    @RunId,
    @AsOf,
    COALESCE(o.ACCOUNT_ID, e.ACCOUNT_ID),
    COALESCE(o.AGREEMENT_ID, e.AGREEMENT_ID),
    COALESCE(o.ACCRUE_TYPE_ID, e.ACCRUE_TYPE_ID),
    o.M3,
    e.M3,
    CONVERT(DECIMAL(18,6), ISNULL(e.M3, 0) - ISNULL(o.M3, 0)),
    o.TOPLAM_TAHAKKUK,
    e.TOPLAM_TAHAKKUK,
    CONVERT(DECIMAL(18,2), ISNULL(e.TOPLAM_TAHAKKUK, 0) - ISNULL(o.TOPLAM_TAHAKKUK, 0)),
    o.GAZ_TUTARI,
    e.GAZ_TUTARI,
    o.KALAN_TUTAR,
    e.KALAN_TUTAR,
    CONVERT(DECIMAL(18,2), ISNULL(e.KALAN_TUTAR, 0) - ISNULL(o.KALAN_TUTAR, 0)),
    CASE
        WHEN o.ACCOUNT_ID IS NULL THEN 'ONLY_EN'
        WHEN e.ACCOUNT_ID IS NULL THEN 'ONLY_ORA'
        WHEN ABS(ISNULL(e.KALAN_TUTAR, 0) - ISNULL(o.KALAN_TUTAR, 0)) <= @Eps
         AND ABS(ISNULL(e.M3, 0) - ISNULL(o.M3, 0)) <= @EpsM3
            THEN 'MATCH'
        ELSE 'AMT_DIFF'
    END,
    CASE
        WHEN o.ACCOUNT_ID IS NULL THEN N'Energy var, Oracle TTK yok'
        WHEN e.ACCOUNT_ID IS NULL THEN N'Oracle TTK var, energy yok'
        WHEN ABS(ISNULL(e.KALAN_TUTAR, 0) - ISNULL(o.KALAN_TUTAR, 0)) <= @Eps
         AND ABS(ISNULL(e.M3, 0) - ISNULL(o.M3, 0)) <= @EpsM3
            THEN NULL
        WHEN ABS(ISNULL(e.KALAN_TUTAR, 0) - ISNULL(o.KALAN_TUTAR, 0)) > @Eps
         AND ABS(ISNULL(e.M3, 0) - ISNULL(o.M3, 0)) > @EpsM3
            THEN N'Kalan+M3 farki'
        WHEN ABS(ISNULL(e.KALAN_TUTAR, 0) - ISNULL(o.KALAN_TUTAR, 0)) > @Eps
            THEN N'Kalan farki'
        ELSE N'M3 farki'
    END
FROM #ORA_TTK o
FULL OUTER JOIN #EN_TTK e ON e.ACCOUNT_ID = o.ACCOUNT_ID;

/* Ozet */
SELECT
    KIND,
    COUNT(*) AS CNT,
    SUM(ORA_M3) AS ORA_M3_SUM,
    SUM(EN_M3) AS EN_M3_SUM,
    SUM(ORA_TAH) AS ORA_TAH_SUM,
    SUM(EN_TAH) AS EN_TAH_SUM,
    SUM(ORA_KALAN) AS ORA_KALAN_SUM,
    SUM(EN_KALAN) AS EN_KALAN_SUM,
    SUM(DELTA_KALAN) AS DELTA_KALAN_SUM
FROM energy.dbo.MIG_TTK_FRK_LOG WITH (NOLOCK)
WHERE RUN_ID = @RunId
GROUP BY KIND
ORDER BY KIND;

SELECT TOP (50)
    ACCOUNT_ID, AGREEMENT_ID, ACCRUE_TYPE_ID,
    ORA_M3, EN_M3, DELTA_M3,
    ORA_TAH, EN_TAH, DELTA_TAH,
    ORA_GAZ, EN_GAZ,
    ORA_KALAN, EN_KALAN, DELTA_KALAN,
    KIND, NOTE
FROM energy.dbo.MIG_TTK_FRK_LOG WITH (NOLOCK)
WHERE RUN_ID = @RunId
  AND KIND <> 'MATCH'
ORDER BY ABS(ISNULL(DELTA_KALAN, 0)) DESC, ABS(ISNULL(DELTA_M3, 0)) DESC, KIND;

SET @Msg = N'TTK FRK DONE run=' + CAST(@RunId AS NVARCHAR(36))
    + N' | incele: SELECT * FROM energy.dbo.MIG_TTK_FRK_LOG WHERE RUN_ID='''
    + CAST(@RunId AS NVARCHAR(36)) + N'''';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
GO
