 CREATE TABLE MIGRATION.LS_AGR_DEVICE AS 
     
--APD.ID LREF,	
 SELECT   
--APD.ID LREF,	
CASE PKL.PRM_ID
    WHEN 1704 THEN 73
    WHEN 344  THEN 2
    WHEN 347  THEN 4
    WHEN 358  THEN 3
    WHEN 364  THEN 8
    WHEN 371  THEN 1
    WHEN 378  THEN 14
    WHEN 379  THEN 22
    WHEN 382  THEN 7
    WHEN 386  THEN 13
    WHEN 389  THEN 83
    WHEN 392  THEN 99
    WHEN 395  THEN 31
    WHEN 396  THEN 72
    WHEN 398  THEN 111
    WHEN 399  THEN 74
    WHEN 405  THEN 11
    WHEN 409  THEN 6
    WHEN 412  THEN 16
    WHEN 414  THEN 93
    WHEN 417  THEN 21
    WHEN 418  THEN 90
    WHEN 421  THEN 78
    WHEN 428  THEN 32
    WHEN 429  THEN 29
    WHEN 432  THEN 5
    WHEN 438  THEN 27
    WHEN 444  THEN 119
    WHEN 451  THEN 112
    WHEN 453  THEN 66
    WHEN 1758 THEN 84
    WHEN 1786 THEN 103
    WHEN 1794 THEN 82
    WHEN 1797 THEN 52
    WHEN 1755 THEN 8
    ELSE -99
END AS DEVID,
agr.ID  AGRID,
PID.MIN_DEBIT ,0 WORKDAY,0 WORKHOUR,0 FEE,160 EXCNR,0 BLIND_PLUG,APP.UPDATED_TIMESTAMP  UPDDATE,APP.UPDATED_USER_ID UPDUSER,1 ISACTIVE, APP.CREATED_USER_ID ADDUSER,APP.CREATED_TIMESTAMP ADDDATE, 
PKL.PRM_ID ABYS_DEV_ID, PKL.VALUE ABYS_DEVICE_KIND  , -- DEVICE_TYPE_ID , 
PRB.PROJECT_ID ABYS_PROJECT_ID  ,agr.INSTALLATION_ID ABYS_INSTALLATION_ID,  DVM.CODE ABYS_MARK_CODE,DVM.VALUE ABYS_MARK_VALUE
                  FROM CS_AGREEMENT agr    
                  JOIN CS_INSTALLATION INS ON AGR.INSTALLATION_ID=INS.ID    
                  JOIN II_PROJECT_INSTALLATION_DEVICE PID ON PID.PROJECT_INSTALLATION_ID=F_GET_LAST_PRJ_INSTALLATION(INS.ID)    
                  JOIN II_PROJECT_INSTALLATION PRI ON PRI.ID=PID.PROJECT_INSTALLATION_ID    
                  JOIN II_PROJECT_BUILDING PRB ON PRB.ID = PRI.PROJECT_BUILDING_ID    
                  JOIN II_PROJECT PRJ ON PRJ.ID = PRB.PROJECT_ID
                  LEFT JOIN II_APPOINTMENT APP ON APP.ID = F_GET_LAST_APPOINTMENT(INS.ID) 
                  LEFT JOIN II_APPOINTMENT_DEVICE APD ON APD.APPOINTMENT_ID =APP.ID AND APD.PROJECT_INSTALLATION_DEVICE_ID=PID.ID      
                  LEFT JOIN II_DEVICE_TYPE_PRM DVT ON DVT.ID = PID.DEVICE_TYPE_ID    
                  LEFT JOIN II_DEVICE_TYPE_PRM_LNG PDL ON DVT.ID = PDL.PRM_ID AND PDL.LANG_ID = 1    
                  LEFT JOIN II_DEVICE_TYPE_PRM_LNG PKL ON DVT.PARENT_ID = PKL.PRM_ID AND PKL.LANG_ID = 1    
                  LEFT JOIN II_DEVICE_MARK_PRM DVM ON DVM.ID = APD.DEVICE_MARK_ID
                  LEFT JOIN CS_AGREEMENT_DEVICE AAD ON (AAD.APPOINTMENT_DEVICE_ID=APD.ID)