-- =====================================================================
-- LS_BANK_CONFIRM  (Oracle staging - CTAS)
-- Kaynak : SMS.CS_BANK_CONFIRM
-- Hedef  : MIGRATION.LS_BANK_CONFIRM  →  izgazMGR.dbo.LS_BANK_CONFIRM
--          → energy.dbo.LS_BNK_MUTABAKAT_DETAY  (364/365)
-- Pattern: kaynak kolon isimleri birebir; ABYS_ID = ID bridge
-- Aciklama: Banka mutabakat / tahsilat onay kayitlari
-- =====================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_BANK_CONFIRM PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE MIGRATION.LS_BANK_CONFIRM
NOLOGGING
PARALLEL 56
AS
SELECT /*+ FULL(c) PARALLEL(c 56) */
    c.ID                                                    AS ID,
    c.ID                                                    AS ABYS_ID,
    c.BANK_ID                                               AS BANK_ID,
    c.CASH_ID                                               AS CASH_ID,
    c.ACTION_DATE                                           AS ACTION_DATE,
    c.PAYMENT_COUNT                                         AS PAYMENT_COUNT,
    c.PAYMENT_AMOUNT                                        AS PAYMENT_AMOUNT,
    c.CANCELLATION_COUNT                                    AS CANCELLATION_COUNT,
    c.CANCELLATION_AMOUNT                                   AS CANCELLATION_AMOUNT,
    c.APPROVAL_STATUS                                       AS APPROVAL_STATUS,
    c.APPROVAL_DESCRIPTION                                  AS APPROVAL_DESCRIPTION,
    c.APPROVAL_DATE                                         AS APPROVAL_DATE,
    c.APPROVAL_USER_ID                                      AS APPROVAL_USER_ID,
    c.CREATED_USER_ID                                       AS CREATED_USER_ID,
    CAST(c.CREATED_TIMESTAMP AS TIMESTAMP)                  AS CREATED_TIMESTAMP,
    c.UPDATED_USER_ID                                       AS UPDATED_USER_ID,
    CAST(c.UPDATED_TIMESTAMP AS TIMESTAMP)                  AS UPDATED_TIMESTAMP,
    c.VERSION                                               AS VERSION,
    c.BANK_OFFICE_NUMBER                                    AS BANK_OFFICE_NUMBER,
    c.BANK_DESK_NUMBER                                      AS BANK_DESK_NUMBER,
    c.AUTO_PAYMENT_COUNT                                    AS AUTO_PAYMENT_COUNT,
    c.AUTO_PAYMENT_AMOUNT                                   AS AUTO_PAYMENT_AMOUNT,
    c.TYPE                                                  AS TYPE,
    c.SERVICE_RECEIPT_NUMBER                                AS SERVICE_RECEIPT_NUMBER,
    c.SERVICE_PAYMENT_DATE                                  AS SERVICE_PAYMENT_DATE,
    c.SERVICE_CHARGE                                        AS SERVICE_CHARGE
FROM SMS.CS_BANK_CONFIRM c
;

ALTER TABLE MIGRATION.LS_BANK_CONFIRM NOPARALLEL LOGGING;

CREATE UNIQUE INDEX MIGRATION.UX_LS_BNKCNF_ID
    ON MIGRATION.LS_BANK_CONFIRM (ID) NOLOGGING PARALLEL 4;

CREATE UNIQUE INDEX MIGRATION.UX_LS_BNKCNF_ABYS_ID
    ON MIGRATION.LS_BANK_CONFIRM (ABYS_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_BANK
    ON MIGRATION.LS_BANK_CONFIRM (BANK_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_CASH
    ON MIGRATION.LS_BANK_CONFIRM (CASH_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_ACTION
    ON MIGRATION.LS_BANK_CONFIRM (ACTION_DATE) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_STATUS
    ON MIGRATION.LS_BANK_CONFIRM (APPROVAL_STATUS) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_TYPE
    ON MIGRATION.LS_BANK_CONFIRM (TYPE) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_BNKCNF_APPR_USER
    ON MIGRATION.LS_BANK_CONFIRM (APPROVAL_USER_ID) NOLOGGING PARALLEL 4;

ALTER INDEX MIGRATION.UX_LS_BNKCNF_ID        NOPARALLEL;
ALTER INDEX MIGRATION.UX_LS_BNKCNF_ABYS_ID   NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_BANK     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_CASH     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_ACTION   NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_STATUS   NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_TYPE     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_BNKCNF_APPR_USER NOPARALLEL;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
    'MIGRATION', 'LS_BANK_CONFIRM', cascade => TRUE, degree => 56);
END;
/

-- dogrulama
SELECT 'CS_BANK_CONFIRM' KAYNAK, COUNT(*) CNT
FROM SMS.CS_BANK_CONFIRM
UNION ALL
SELECT 'LS_BANK_CONFIRM', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM
UNION ALL
SELECT 'LS_BNKCNF_STATUS_1_NEW', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM WHERE APPROVAL_STATUS = 1
UNION ALL
SELECT 'LS_BNKCNF_STATUS_2_APPROVED', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM WHERE APPROVAL_STATUS = 2
UNION ALL
SELECT 'LS_BNKCNF_STATUS_3_REJECTED', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM WHERE APPROVAL_STATUS = 3
UNION ALL
SELECT 'LS_BNKCNF_TYPE_1_PAYMENT', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM WHERE TYPE = 1
UNION ALL
SELECT 'LS_BNKCNF_TYPE_2_REFUND', COUNT(*)
FROM MIGRATION.LS_BANK_CONFIRM WHERE TYPE = 2;

PROMPT ========== LS_BANK_CONFIRM OK ==========
/
