-- =============================================================================
-- O41 EARLY_PAY_GHOST diag (118) — O30 yeniden ONCE kosulmali
-- sqlplus ... @41_diag_early_pay_ghost.sql
-- =============================================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 100 LINESIZE 220
COLUMN PAY_LREF FORMAT 999999999999
COLUMN ACCOUNT_ID FORMAT 999999999999
COLUMN PAY_AD FORMAT A20
COLUMN WHY FORMAT A40

PROMPT ========== 0) O30 dosya imzasi (MAIN_ACTION_DATE var mi?) ==========
PROMPT Sunucuda: FINDSTR MAIN_ACTION_DATE 041_30_LS_TAHSILAT_OVERLAY.SQL
PROMPT Yoksa sync eksik. Varsa asagidaki ghost hâlâ doluysa O30 yeniden kos.

PROMPT ========== 1) Ghost sayisi (O41 ile ayni) ==========
SELECT COUNT(DISTINCT pay.ID) AS GHOST_N
FROM SMS.CS_ACCOUNT_ACTION pay
JOIN MIGRATION.TMP_MIG_ACC m ON m.ACCOUNT_ID = pay.ACCOUNT_ID
JOIN SMS.CS_ACTION_TYPE_PRM atp ON atp.ID = pay.ACTION_TYPE_ID AND atp.TYPE = 2
WHERE pay.ACTION_TYPE_ID NOT IN (36, 37, 39, 44, 6, 24)
  AND NOT EXISTS (SELECT 1 FROM MIGRATION.TMP_PAY_CANCEL c WHERE c.PAY_ID = pay.ID)
  AND NOT EXISTS (SELECT 1 FROM MIGRATION.LS_OV_PAY_ALLOC a WHERE a.PAY_LREF = pay.ID)
  AND EXISTS (
        SELECT 1
        FROM SMS.CS_ACCOUNT_INCOME pi
        JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
        JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
        WHERE pi.ACCOUNT_ACTION_ID = pay.ID
          AND g.ACCOUNT_ID = pay.ACCOUNT_ID
          AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
          AND g.ACTION_DATE > pay.ACTION_DATE
          AND ABS(NVL(pi.AMOUNT * pi.STATUS, 0)) > 0.0001
      )
  AND (
        SELECT ABS(SUM(pi2.AMOUNT * pi2.STATUS))
        FROM SMS.CS_ACCOUNT_INCOME pi2
        WHERE pi2.ACCOUNT_ACTION_ID = pay.ID
      ) > 0.0001;

PROMPT ========== 2) Ornek 30 ghost + neden tahmini ==========
SELECT * FROM (
  SELECT
      pay.ID AS PAY_LREF,
      pay.ACCOUNT_ID,
      pay.ACTION_TYPE_ID AS PAY_TYPE,
      TO_CHAR(pay.ACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PAY_AD,
      CAST(ROUND((
        SELECT ABS(SUM(pi2.AMOUNT * pi2.STATUS))
        FROM SMS.CS_ACCOUNT_INCOME pi2
        WHERE pi2.ACCOUNT_ACTION_ID = pay.ID
      ), 2) AS NUMBER(15,3)) AS PAY_FULL,
      (SELECT COUNT(*) FROM SMS.CS_ACCOUNT_INCOME pi
        JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
        JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
       WHERE pi.ACCOUNT_ACTION_ID = pay.ID
         AND g.ACCOUNT_ID = pay.ACCOUNT_ID
         AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
         AND g.ACTION_DATE > pay.ACTION_DATE
         AND ABS(NVL(pi.AMOUNT * pi.STATUS, 0)) > 0.0001
      ) AS LATER_MAIN_N,
      (SELECT COUNT(*) FROM SMS.CS_ACCOUNT_INCOME pi
        JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
        JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
       WHERE pi.ACCOUNT_ACTION_ID = pay.ID
         AND g.ACCOUNT_ID = pay.ACCOUNT_ID
         AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
         AND ABS(NVL(pi.AMOUNT * pi.STATUS, 0)) > 0.0001
      ) AS ANY_MAIN_N,
      (SELECT COUNT(*) FROM MIGRATION.LS_INVOICE inv
        WHERE inv.LREF IN (
          SELECT g.ID FROM SMS.CS_ACCOUNT_INCOME pi
          JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
          JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
          WHERE pi.ACCOUNT_ACTION_ID = pay.ID
            AND g.ACCOUNT_ID = pay.ACCOUNT_ID
            AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
            AND g.ACTION_DATE > pay.ACTION_DATE
        )
      ) AS LATER_INV_N,
      CASE
        WHEN NOT EXISTS (
          SELECT 1 FROM SMS.CS_ACCOUNT_INCOME pi
          JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
          JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
          WHERE pi.ACCOUNT_ACTION_ID = pay.ID
            AND g.ACCOUNT_ID = pay.ACCOUNT_ID
            AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
            AND ABS(NVL(pi.AMOUNT * pi.STATUS, 0)) > 0.0001
        ) THEN 'NO_MAIN_INCOME_MATCH'
        WHEN NOT EXISTS (
          SELECT 1 FROM MIGRATION.LS_INVOICE inv
          JOIN SMS.CS_ACCOUNT_INCOME pi ON 1=1
          JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
          JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
          WHERE pi.ACCOUNT_ACTION_ID = pay.ID
            AND g.ACCOUNT_ID = pay.ACCOUNT_ID
            AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
            AND inv.LREF = g.ID
        ) THEN 'MAIN_NOT_IN_LS_INVOICE'
        ELSE 'IN_PAY_INC_SHOULD_ALLOC_AFTER_O30_FIX'
      END AS WHY
  FROM SMS.CS_ACCOUNT_ACTION pay
  JOIN MIGRATION.TMP_MIG_ACC m ON m.ACCOUNT_ID = pay.ACCOUNT_ID
  JOIN SMS.CS_ACTION_TYPE_PRM atp ON atp.ID = pay.ACTION_TYPE_ID AND atp.TYPE = 2
  WHERE pay.ACTION_TYPE_ID NOT IN (36, 37, 39, 44, 6, 24)
    AND NOT EXISTS (SELECT 1 FROM MIGRATION.TMP_PAY_CANCEL c WHERE c.PAY_ID = pay.ID)
    AND NOT EXISTS (SELECT 1 FROM MIGRATION.LS_OV_PAY_ALLOC a WHERE a.PAY_LREF = pay.ID)
    AND EXISTS (
          SELECT 1
          FROM SMS.CS_ACCOUNT_INCOME pi
          JOIN SMS.CS_ACCOUNT_INCOME gi ON gi.INCOME_ID = pi.INCOME_ID
          JOIN SMS.CS_ACCOUNT_ACTION g ON g.ID = gi.ACCOUNT_ACTION_ID
          WHERE pi.ACCOUNT_ACTION_ID = pay.ID
            AND g.ACCOUNT_ID = pay.ACCOUNT_ID
            AND g.ACTION_TYPE_ID IN (1, 3, 10, 41)
            AND g.ACTION_DATE > pay.ACTION_DATE
            AND ABS(NVL(pi.AMOUNT * pi.STATUS, 0)) > 0.0001
        )
    AND (
          SELECT ABS(SUM(pi2.AMOUNT * pi2.STATUS))
          FROM SMS.CS_ACCOUNT_INCOME pi2
          WHERE pi2.ACCOUNT_ACTION_ID = pay.ID
        ) > 0.0001
  ORDER BY pay.ID
) WHERE ROWNUM <= 30;

PROMPT ========== 3) O30 yeniden kosuldu mu? ==========
PROMPT PAY_ALLOC su an: asagidaki ile onceki 66860830 karsilastir — ayniysa O30 yeniden YOK
SELECT COUNT(*) AS PAY_ALLOC_N FROM MIGRATION.LS_OV_PAY_ALLOC;

PROMPT Sonra: @041_30_LS_TAHSILAT_OVERLAY.SQL  (yeni MAIN_ACTION_DATE surumu)
PROMPT Sonra zincir: O32 O34 O33 O14b O35 @047_41_GATE_TAHSILAT.SQL
/
