-- =============================================================================
-- oracleCTAS3007 / 54 — LS_ARTIRAN (arttiran tahakkuk) + LS_EMANET (ACCRUE=14)
-- Onkosul: O11 LS_INVOICE; emanet icin SMS.CS_ACCOUNT
-- Dogal ID; MAP/SRC_KEY yok
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_INVOICE';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20054, 'MIGRATION.LS_INVOICE yok — once O11.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O54', 'ls_artiran_emanet', 'START', NULL, 'ARTIRAN+EMANET');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_ARTIRAN PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_ARTIRAN NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(INV.LREF AS NUMBER(12))                                 AS MAIN_LREF,
    CAST(INV.ABYS_ACCOUNT_ID AS NUMBER(12))                      AS FATURAID,
    CAST(INV.ABYS_AGREEMENT_ID AS NUMBER(12))                    AS SOZLESME,
    CAST(INV.ABYS_ACTION_ID AS NUMBER(12))                       AS ACTION_ID,
    CAST(INV.ABYS_ACTION_TYPE_ID AS NUMBER(10))                  AS ACTION_TYPE_ID,
    CAST(INV.PAYABLETOTAL AS NUMBER(15,3))                       AS PAYABLETOTAL,
    INV.DATE_                                                    AS ACCRUE_DATE,
    CAST(INV.TYPE AS NUMBER(10))                                 AS INV_TYPE,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_INVOICE INV
WHERE INV.ABYS_ACTION_TYPE_ID IN (3, 10, 41)
  AND NVL(INV.CANCELED, 0) = 0;

CREATE UNIQUE INDEX MIGRATION.IX_LS_ART_MAIN ON MIGRATION.LS_ARTIRAN (MAIN_LREF) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_ART_AGR ON MIGRATION.LS_ARTIRAN (SOZLESME) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_ART_MAIN NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_ART_AGR NOPARALLEL;
ALTER TABLE MIGRATION.LS_ARTIRAN NOPARALLEL LOGGING;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_EMANET PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_EMANET NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(A.ID AS NUMBER(12))                                     AS FATURAID,
    CAST(A.AGREEMENT_ID AS NUMBER(12))                           AS SOZLESME,
    CAST(A.ACCRUE_TYPE_ID AS NUMBER(10))                         AS ACCRUE_TYPE_ID,
    CAST(ROUND(NVL((
        SELECT SUM(AI.STATUS * AI.AMOUNT)
          FROM SMS.CS_ACCOUNT_ACTION AA
          JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID = AA.ID
         WHERE AA.ACCOUNT_ID = A.ID
    ), 0), 2) AS NUMBER(15,3))                                   AS BALANCE,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM SMS.CS_ACCOUNT A
WHERE A.ACCRUE_TYPE_ID = 14;

CREATE UNIQUE INDEX MIGRATION.IX_LS_EMANET_ACC ON MIGRATION.LS_EMANET (FATURAID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_EMANET_AGR ON MIGRATION.LS_EMANET (SOZLESME) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_EMANET_ACC NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_EMANET_AGR NOPARALLEL;
ALTER TABLE MIGRATION.LS_EMANET NOPARALLEL LOGGING;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_ARTIRAN', degree => 40);
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_EMANET', degree => 40);
END;
/

DECLARE
  n_a NUMBER; n_e NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_a FROM MIGRATION.LS_ARTIRAN;
  SELECT COUNT(*) INTO n_e FROM MIGRATION.LS_EMANET;
  MIGRATION.P_MIG_CTAS_LOG('O54', 'ls_artiran_emanet', 'OK', n_a + n_e,
    'ARTIRAN=' || n_a || ' EMANET=' || n_e);
  DBMS_OUTPUT.PUT_LINE('========== O54 ARTIRAN/EMANET OK | A=' || n_a || ' E=' || n_e || ' ==========');
END;
/
