/* ============================================================
   SCRIPT_ID : SPEFEE_CHECK
   SCRIPT_NO : 586
   FILE      : 586_SPEFEE__check.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- LS_005_01_SPEFEE — kontrol sorgulari
-- ============================================================
USE energy;
GO

IF OBJECT_ID('energy.dbo.LS_005_01_SPEFEE', 'U') IS NULL
BEGIN
    SELECT 'LS_005_01_SPEFEE tablosu yok' AS UYARI;
    RETURN;
END
GO

SELECT 'LS_005_01_SPEFEE toplam' AS METRIK, COUNT(*) AS DEGER
FROM energy.dbo.LS_005_01_SPEFEE
UNION ALL
SELECT 'ABYS migrate satirlari', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT 'LREF <> ABYS_ID', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL AND LREF <> ABYS_ID
UNION ALL
SELECT 'CANCELLED=1', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL AND CANCELLED = 1
UNION ALL
SELECT 'READING_ID dolu', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL AND READING_ID IS NOT NULL
UNION ALL
SELECT 'INVOICEREF NULL', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL AND INVOICEREF IS NULL
UNION ALL
SELECT 'CUSTNAME NULL/bos', COUNT(*)
FROM energy.dbo.LS_005_01_SPEFEE
WHERE ABYS_ID IS NOT NULL AND (CUSTNAME IS NULL OR LTRIM(RTRIM(CUSTNAME)) = N'');
GO

-- Kaynak vs hedef adet
IF OBJECT_ID('izgazMGR.dbo.LS_SPEFEE', 'U') IS NOT NULL
BEGIN
    SELECT
        (SELECT COUNT_BIG(*) FROM izgazMGR.dbo.LS_SPEFEE) AS SRC_CNT,
        (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_SPEFEE WHERE ABYS_ID IS NOT NULL) AS TGT_CNT,
        (SELECT COUNT_BIG(*) FROM izgazMGR.dbo.LS_SPEFEE) -
        (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_SPEFEE WHERE ABYS_ID IS NOT NULL) AS DIFF;
END
GO

-- Tutar rekonsil
IF OBJECT_ID('izgazMGR.dbo.LS_SPEFEE', 'U') IS NOT NULL
BEGIN
    SELECT
        (SELECT SUM(TRY_CAST(GRANDTOTAL AS FLOAT)) FROM izgazMGR.dbo.LS_SPEFEE) AS SRC_GRANDTOTAL,
        (SELECT SUM(GRANDTOTAL) FROM energy.dbo.LS_005_01_SPEFEE WHERE ABYS_ID IS NOT NULL) AS TGT_GRANDTOTAL;
END
GO

EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_01_SPEFEE';
GO
