/* ============================================================
   SCRIPT_ID : OPS_AFTER_ADHOC
   SCRIPT_NO : 910
   FILE      : 910_OPS_AFTER__adhoc.sql
   VERSION   : 1
   ============================================================ */
 

select  * from LS_USER
------





;;;


UPDATE
    mgg_cbs_kapi
SET
    mgg_cbs_kapi.OkumaBolgeKodu = RAN.Id
FROM
    mgg_cbs_kapi SI
INNER JOIN
    mgg_cbs_okuma_bolge RAN
ON 
    RAN.KonumWkt.STIntersects(SI.KonumWkt)=1 
    where SI.SirketKodu=4102 and RAN.Id = 15177




   ------
   -- OBSOLETE: user remap (ABYS_ID → USERID). Insert artik FN_MIG_MAP_USER_USERID (ABYS+10000) kullanir.
   -- select  usr.USERID, usr.ABYS_ID from  LS_USER usr
   -- JOIN  LS_005_01_AGR agr on usr.ABYS_ID = agr.ADDUSER
   -- UPDATE agr set  agr.ADDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_01_AGR agr on usr.ABYS_ID = agr.ADDUSER
   -- UPDATE agr set  agr.UPDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_01_AGR agr on usr.ABYS_ID = agr.UPDUSER
   -- UPDATE agr set  agr.ADDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_01_AGR_GUARANTY agr on usr.ABYS_ID = agr.ADDUSER
   -- UPDATE agr set  agr.UPDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_01_AGR_GUARANTY agr on usr.ABYS_ID = agr.UPDUSER

-----
select * from LS_005_01_AGR_GUARANTY

-- 196: AGR wire YOK — AGRID = ABYS AGREEMENT_ID (CTAS/migrate aynen). Asagidaki UPDATE calistirilmaz.
-- UPDATE agrGua set  agrGua.AGRID = agr.LREF
-- from  LS_005_01_AGR agr
-- JOIN  LS_005_01_AGR_GUARANTY agrGua on agr.ABYS_ID = agrGua.ABYS_AGRID  and agr.TP2 = 'KUL'

-- =============================================================================
-- 196 AGR_GUARANTY preflight (wire yok; AGRID=ABYS AGREEMENT_ID)
-- Once: 310_AGR_GUARANTY__setup.sql  →  sonra HARD_RESET migrate
-- EXEC energy.dbo.SP_MIGRATE_LS005_DEPOSIT_GUARANTY @HARD_RESET=1, @BATCH_SIZE=5000, @DEBUG=1;
-- =============================================================================
SET NOCOUNT ON;
SELECT
  CASE WHEN OBJECT_DEFINITION(OBJECT_ID('dbo.VW_MIG_DEPOSIT_GUARANTY_SOURCE')) LIKE '%CONVERTED_TO_CASH%'
       THEN 'VW_CONV_OK' ELSE 'VW_CONV_HARDCODE0_REDEPLOY_310' END AS VW_CONV,
  COL_LENGTH('izgazMGR.dbo.LS_AGR_GUARANTY','MIG_ROW_ID') AS MGR_MIG_ROW_ID,
  (SELECT COUNT(*) FROM izgazMGR.dbo.LS_AGR_GUARANTY) AS MGR_CNT,
  (SELECT COUNT(*) FROM dbo.LS_005_01_AGR_GUARANTY WHERE ABYS_MIG_ROW_ID IS NOT NULL) AS EN_ABYS_CNT;

SELECT
  SUM(CASE WHEN AGRID IS NULL OR ABYS_AGREEMENT_ID IS NULL THEN 1 ELSE 0 END) AS MGR_AGRID_NULL,
  SUM(CASE WHEN AGRID <> ABYS_AGREEMENT_ID THEN 1 ELSE 0 END) AS MGR_AGRID_NE_ABYS,
  SUM(CASE WHEN GTYPE=39 THEN 1 ELSE 0 END) AS G39,
  SUM(CASE WHEN GTYPE IN (40,41) THEN 1 ELSE 0 END) AS G40_41,
  SUM(CASE WHEN ISNULL(CONVERTED_TO_CASH,0)=1 THEN 1 ELSE 0 END) AS CONV1
FROM izgazMGR.dbo.LS_AGR_GUARANTY;

-- energy: AGRID hâlâ ABYS mi (wire uygulanmamis)
SELECT
  SUM(CASE WHEN g.AGRID = g.ABYS_AGRID THEN 1 ELSE 0 END) AS AGRID_EQ_ABYSAGR,
  SUM(CASE WHEN g.AGRID <> g.ABYS_AGRID THEN 1 ELSE 0 END) AS AGRID_WIRED_DIFF,
  COUNT(*) AS EN_CNT
FROM dbo.LS_005_01_AGR_GUARANTY g
WHERE g.ABYS_MIG_ROW_ID IS NOT NULL;

-- EXEC dbo.SP_MIG_DEPOSIT_GUAR_VALIDATE_SOURCE @RaiseOnMissing = 1;
---------------------------

select * from LS_005_01_PROJECTLINE  where ABYS_STG_TESISAT_NO  =1438
  
select * from LS_005_01_PROJECTLINE   order by LREF desc

1242500
-----------------------

   UPDATE agt set  agt.AGRID = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_PROJECTLINE agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID  
   where ISNULL(AGRID,0)>0

   select agr.LREF , agr.ABYS_ID , agt.AGRID  
      from  LS_005_01_AGR agr 
   JOIN  LS_005_01_PROJECTLINE agt on agr.ABYS_ID = agt.AGRID    and agr.TP2='KUL'
   where   agr.FITNO =  983113

   UPDATE agt SET agt.AGRID = agr.LREF, agt.BNA_ID= agr.BNA_ID 
        from  LS_005_01_AGR agr 
   JOIN  LS_005_01_PROJECTLINE agt on agr.ABYS_ID = agt.AGRID    and agr.TP2='KUL'
   where   agr.FITNO =  983113
   ----
   
   select top 10 * from LS_005_01_PROJECTLINE where 983113


   select * from LS_005_01_AGR where ABYS_ID = 124500

  ----------------------------
   UPDATE agt set  agt.AGRID = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_AGR_DEV_TR agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID 

   select top 100  * from LS_005_01_AGR_DEV_TR

 
   UPDATE agt set  agt.AGRID = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_AGR_SERVEQ_TR agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID   and agr.TP2 = 'KUL'

   -- SERVEQ aktarimi sonrasi: AGR.CALCPRESSID ← SERVEQ (COUNTERID = ITEMID)
   -- AGR CTAS sadece 21→34; SERVEQ tam USED_PRESSURE → lookup
   EXEC energy.dbo.SP_MIG_AGR_SYNC_CALCPRESS_FROM_SERVEQ @DEBUG = 1;
   /*
   UPDATE agr SET agr.CALCPRESSID = sq.CALCPRESSID
   FROM LS_005_01_AGR agr
   JOIN LS_005_01_AGR_SERVEQ_TR sq ON sq.ITEMID = agr.COUNTERID
   WHERE ISNULL(agr.COUNTERID, 0) <> 0
     AND sq.CALCPRESSID IS NOT NULL
     AND sq.CALCPRESSID > 0
     AND ISNULL(agr.CALCPRESSID, -1) <> sq.CALCPRESSID;
   */


    UPDATE agt set  agt.AGRID = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_AGR_FITMENTFEE_TR agt on agr.FITNO = agt.ABYS_INSTALLATION_ID and agr.TP2 = 'ABN'


      UPDATE agt set  agt.AGRID = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_CS_APPOINTMENT agt on agr.ABYS_ID = agt.AGRID  and agr.TP2 = 'KUL'


UPDATE LS_005_01_AGR SET IS_BILL_PRINT = 0;

UPDATE LS_005_01_AGR SET IS_BILL_PRINT = 1   where  TP2='KUL'  and ABYS_ID in (466757	,
521756	,
34125	,
39744	,
83990	,
499209	,
140877	,
150269	,
168638	,
258939	,
351082	,
547967	,
531346	,
563670	,
620520	,
607584	,
664477	,
644018	,
669415	,
650355	,
690535	,
717891	,
764088	,
835070	,
808281	,
848951	,
833192	,
798254	,
900608	,
893790	,
905114	,
852762	,
868435	,
248937	,
927718	,
1021480	,
1004690	,
1007844	,
1015926	,
1048055	,
1068659	,
1077317	,
1077314	,
1065041	,
1032991	,
1061246	)


   
UPDATE  
LS_005_01_hhd_loc_inv_tran  set corr_volume=ISNULL(ABYS_CONSUMPTION,
ROUND(ISNULL((((corr_volume*corr_coef) *avg_top_cal_value)/9155),2),ABYS_CONSUMPTION))   where AGRID = 28996


 -- select STYPE,pr.VALUE_TR ,COUNT(1)
  
  UPDATE sp SET sp.OWNERREF = agr.LREF  from  LS_005_01_SPEFEE  sp
 JOIN LS_005_01_AGR agr on  agr.ABYS_ID = sp.ABYS_AGREEMENT_ID and agr.TP2='KUL'

 ;;
 select STYPE,pr.VALUE_TR ,COUNT(1) from LS_005_01_SPEFEE  sp
 JOIN LS_005_01_AGR agr on  agr.ABYS_ID = sp.ABYS_AGREEMENT_ID
 JOIN LS_INCOME_PRM pr on  pr.CODE = sp.STYPE
 --where agr.ABYS_ID = 379527
 group by STYPE,pr.VALUE_TR
 order by 2 desc

   ;;

   select COUNTER_STAT , count(1) from LS_005_01_AGR  --where ISNULL(COUNTER_STAT , 0)=0
      group by COUNTER_STAT

   and ISNULL(COUNTERID,0) = 0 ;


   ;;;

   select  * from mgg_cbs_okuma_bolge where SirketKodu = 4102


   ;;;

   --UPDATE LS_005_01_AGR SET COUNTER_STAT = 0  where ISNULL(COUNTER_STAT , 0)=0   and ISNULL(COUNTERID,0) =0
   ;;




  -- UPDATE agt set  agt.AGRID = agr.LREF
  select agr.LREF, agr.AGREEMENT_NUMBER,agt.ABYS_AGREEMENT_ID, agt.SOZLESME_NUMARASI, agt.SOZLESME_HESABI,agt.ABONE_NUMARASI,agr.CON,agr.FRMID, agt.TESISAT_NUMARASI,agr.FITNO
      from  LS_005_01_AGR agr 
   JOIN  LS_BNK_TALIMAT agt on agr.ABYS_ID = agt.SOZLESME_NUMARASI  and agr.TP2 = 'KUL' and agt.FIRMA_KODU=5

   UPDATE agt set  agt.SOZLESME_NUMARASI = agr.LREF
   from  LS_005_01_AGR agr 
   JOIN  LS_BNK_TALIMAT agt on agr.ABYS_ID = agt.SOZLESME_NUMARASI  and agr.TP2 = 'KUL' and agt.FIRMA_KODU=5


   ;;;

   CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_FRI] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_GEA] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_MON] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_SAT] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_SUN] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_THU] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_TUE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_WED] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EARCHIVE_F005_WEE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_FRE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_GEF] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_MNE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_SAE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_SUE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_TEE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_THE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_THU] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_TUE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_EINVOICE_F005_WEE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_FB_EARCHIVE_F005_GBE] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;
CREATE SEQUENCE [dbo].[SEQ_FB_EINVOICE_F005_GBF] AS bigint START WITH 2026000000001 INCREMENT BY 1 MINVALUE 2026000000000 MAXVALUE 2026999999999 NO CYCLE NO CACHE;


--   UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 162 WHERE WO_TYPE_ID = 1 AND WO_CAUSE_ID = 1
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 79  WHERE WO_TYPE_ID = 2 AND WO_CAUSE_ID = 5
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 163 WHERE WO_TYPE_ID = 2 AND WO_CAUSE_ID = 4
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 188 WHERE WO_TYPE_ID = 1 AND WO_CAUSE_ID = 2
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 669 WHERE WO_TYPE_ID = 6 AND WO_CAUSE_ID = 18
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 741 WHERE WO_TYPE_ID = 1 AND WO_CAUSE_ID = 97
--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 171 WHERE WO_TYPE_ID = 7 AND WO_CAUSE_ID = 19

--UPDATE LS_005_01_CS_APPOINTMENT SET TYPEID = 676 WHERE WO_TYPE_ID = 3 AND WO_CAUSE_ID = 87


      select top 100  agt.AGRID, agr.LREF   from  LS_FLAT"
   JOIN  LS_005_01_AGR_SERVEQ_TR agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID 


   
      select top 100  agt.AGRID, agr.LREF   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_AGR_SERVEQ_TR agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID 



      select top 100  agt.AGRID, agr.LREF   from  LS_005_01_AGR agr 
   JOIN  LS_005_01_AGR_SERVEQ_TR agt on agr.ABYS_ID = agt.ABYS_AGREEMENT_ID 



   select top 100   *from LS_005_01_AGR_CLOSE

select  *from LS_005_01_AGR_GUARANTY where ABYS_AGRID= 1197101

   select * from LS_005_01_AGR where LREF =    3102752 
------

   select fr.LREF, * from LS_005_01_AGR agr
    LEFT JOIN LS_005_SUBSCR sb on sb.LREF = agr.con
   LEFT JOIN LS_005_FIRM fr on fr.LREF = agr.con
   where sb.LREF is null


   --UPDATE agr set agr.CON = null , agr.FRMID = fr.LREF from LS_005_01_AGR agr
   --LEFT JOIN LS_005_SUBSCR sb on sb.LREF = agr.con
   --LEFT JOIN LS_005_FIRM fr on fr.LREF = agr.con
   --where sb.LREF is null  

   --select  * from LS_005_01_AGR agr
   --LEFT JOIN LS_005_SUBSCR sb on sb.LREF = agr.con
   --LEFT JOIN LS_005_FIRM fr on fr.LREF = agr.con
   --where fr.LREF is null


   --UPDATE agr set agr.CON = null , agr.FRMID = fr.LREF from LS_005_01_AGR agr
   --LEFT JOIN LS_005_SUBSCR sb on sb.LREF = agr.con
   --LEFT JOIN LS_005_FIRM fr on fr.LREF = agr.con
   --where fr.LREF is null



   ------
   -- OBSOLETE: FIRM/SUBSCR user remap — insert-time offset (FN_MIG_MAP_USER_USERID)
   -- UPDATE fr set  fr.ADDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_FIRM fr on usr.ABYS_ID = fr.ADDUSER
   -- UPDATE sb set  sb.UPDUSER = usr.USERID
   -- from  LS_USER usr
   -- JOIN  LS_005_SUBSCR sb on usr.ABYS_ID = sb.UPDUSER


 select *   from LS_005_01_INVOICE  inv 
 JOIN LS_005_01_AGR agr on inv.ABYS_AGREEMENT_ID = agr.ABYS_ID and agr.TP2 = 'KUL'
 where inv.ABYS_AGREEMENT_ID= 197168 and inv.TYPE =119
  

UPDATE inv SET   
inv.CLIENTREF =ISNULL(agr.CON,agr.FRMID),
inv.OWNERTYPE= CASE WHEN ISNULL(agr.CON,0) >0 THEN 91 ELSE 90 END ,
inv.OWNERREF = agr.LREF
  from LS_005_01_INVOICE  inv 
  JOIN LS_005_01_AGR agr on inv.OWNERREF = agr.ABYS_ID and agr.TP2 = 'KUL'
 



UPDATE invl SET   
invl.INVOICEREF = inv.LREF 
  from LS_005_01_INVLINES invl  
  JOIN  LS_005_01_INVOICE  inv   on inv.ABYS_ACCOUNT_ID = invl.ABYS_ACCOUNT_ID

  select * from LS_INCOME_PRM


 
--UPDATE  LS_005_01_INVLINES   CURID = 160 , CURRATE = 1 , CURTOTAL =TLTOTAL , UNITPRICE = ABYS_UNIT_PRICE  , AMOUNT = ABYS_QUANTITY 

 select ABYS_INCOME_ID , LINEEXP from LS_005_01_INVLINES
 group by ABYS_INCOME_ID , LINEEXP

 select top 1000000 * from LS_002_01_INVLINES
 
 select  *  
  from LS_005_01_INVOICE  inv 
  JOIN LS_005_01_INVLINES invl on inv.LREF = invl.INVOICEREF
 


  select  top 1000 *  
  from LS_005_01_INVLINES invl
 LEFT JOIN  LS_INCOME_PRM  inv  on inv.CODE = invl.TRANSTYPE
 where inv.LREF is null
 
 
  


--------------------------
UPDATE agr SET 
agr.LASTREAD_DATE = itm.ABYS_READING_DATE
  from LS_005_01_AGR   agr 
  JOIN LS_005_ITEMS itm on itm.LREF = agr.COUNTERID
  where agr.FITNO= 813400






  ----
UPDATE agr SET 
COUNTERSN = itm.SNNO_TEXT, COUNTERMODEL=itm.MID,COUNTERMBAR = itm.METER_PRESSURE_REF
  from LS_005_01_AGR   agr 
  JOIN LS_005_ITEMS itm on itm.LREF = agr.COUNTERID
  where agr.FITNO= 813400
  -----------------------
  UPDATE  LS_005_01_AGR set  IS_GS  =0


 UPDATE LS_005_01_AGR SET TP3 ='NOR' where ISNULL(COUNTERID,0)=0

 /*
 16	Büyük Sanayi
 4	İşyeri
 13	Kamu 
 */

  select agr.COUNTERID,* 
    from LS_005_01_AGR   agr 
  LEFT JOIN LS_005_ITEMS itm on itm.LREF = agr.COUNTERID
  where agr.FITNO= 813400

select * from LS_005_ITEMS where LREF = 126658


select COUNT(1)  from LS_005_01_AGR agr
LEFT JOIN LS_005_ITEMS itm on  itm.LREF = agr.COUNTERID
LEFT JOIN izgazMGR.dbo.LS_ITEM_CHECK itc on itc.METER_ID= agr.COUNTERID
where itm.LREF is null   and  agr.COUNTERID is not null


select agr.COUNTERID  from LS_005_01_AGR agr  
where TP2 ='KUL' and agr.AGR_EDATE is null
group by agr.COUNTERID
having COUNT(1)>1
 

 select * from LS_USER order by USERID desc

 select top 100 ADDUSER,UPDUSER from LS_005_01_AGR   where FITNO ='1036011'



 select pAgr.ABYS_ID , agr.ID , pAgr.FITNO , agr.INSTALLATION_ID
 from  izgazMGR.dbo.CS_AGREEMENT  agr
 JOIN LS_005_01_AGR pAgr on pAgr.ABYS_ID = agr.ID and pAgr.TP2='KUL'
 where pAgr.ABYS_ID = agr.ID and pAgr.FITNO <> agr.INSTALLATION_ID


select  top 100 agr.LREF, agr.ABYS_ID,agr.AGREEMENT_NUMBER,  itc.METER_NUMBER , agr.COUNTERSN, itm.SNNO_NR, agr.*   from LS_005_01_AGR agr
LEFT JOIN LS_005_ITEMS itm on  itm.ABYS_INSTALLATION_ID = agr.FITNO
LEFT JOIN izgazMGR.dbo.LS_ITEM_CHECK itc on itc.INSTALLATION_ID = agr.FITNO
where agr.COUNTERID <> itc.METER_ID



select  top 100 agr.LREF, agr.ABYS_ID,agr.AGREEMENT_NUMBER,  itc.METER_NUMBER , agr.COUNTERSN, itm.SNNO_NR, itm.ABYS_READING_DATE   from LS_005_01_AGR agr
LEFT JOIN LS_005_ITEMS itm on  itm.ABYS_INSTALLATION_ID = agr.FITNO
LEFT JOIN izgazMGR.dbo.LS_ITEM_CHECK itc on itc.INSTALLATION_ID = agr.FITNO
where agr.AGREEMENT_NUMBER= 1896

select *  from LS_005_01_CS_APPOINTMENT

select * from izgazMGR.dbo.LS_005_ITEMS   where METER_ID = 645346

select * from LS_STC_MODEL


  select  top 100  * from LS_005_ITEMS  itm
  JOIN LS_STC_MODEL stc on stc.MDEFN = itm.DEFN






  select  * from LS_005_01_AGR_GUARANTY
  
  select  * from LS_005_01_AGR_DEV_TR

  select  * from LS_005_01_AGR_CLOSE



  select * from LS_005_01_AGR 
  group by FLATID 
  order by ADDDATE


  -----------------------------------------

     UPDATE  LS_005_01_AGR set STATID = 2 where TP2 = 'ABN'  and ABYS_PROJECT_STATUS in (200,300,400);
      
     UPDATE  LS_005_01_AGR set STATID = 1 where TP2 = 'ABN'  and ABYS_PROJECT_STATUS in (100);

     UPDATE  LS_005_01_AGR set STATID = 4 where TP2 = 'ABN'  and ABYS_PROJECT_STATUS in (888,999);

     UPDATE  LS_005_01_AGR set STATID = 1 where TP2 = 'ABN'  and ABYS_PROJECT_STATUS is NULL ;
     
        
 select ABYS_PROJECT_STATUS, 
 CASE   WHEN    ABYS_PROJECT_STATUS is null THEN 1 
        WHEN    ABYS_PROJECT_STATUS =0 THEN 1   
        WHEN    ABYS_PROJECT_STATUS = 100 THEN 1    
        WHEN    ABYS_PROJECT_STATUS = 200 THEN 2    
        WHEN    ABYS_PROJECT_STATUS = 200 THEN 2    
        WHEN    ABYS_PROJECT_STATUS = 300 THEN 2  
        WHEN    ABYS_PROJECT_STATUS = 400 THEN 2             
        WHEN    ABYS_PROJECT_STATUS = 888 THEN 4 
        WHEN    ABYS_PROJECT_STATUS = 999 THEN 4 
            END   ABYS_PROJECT_STATUS ,count(1) from  LS_005_01_AGR 
where TP2 = 'ABN'
group by ABYS_PROJECT_STATUS       





  



--

select * from LS_WAREHOUSE where ENT_ID = 4102 and NR = 44


select WAREHOUSE,count(1) from energy.dbo.LS_005_ITEMS 
group by WAREHOUSE

select top 10 *  from energy.dbo.LS_005_ITEMS 
WHERE ABYS_WA = 44   


select * from energy.dbo.LS_005_FIRM  where NAME_ like 'ACT%'

-- Marka (supplier) insert'leri icin native band: sonraki LREF = 1000001
--DBCC CHECKIDENT('energy.dbo.LS_005_FIRM', RESEED, 1000000) WITH NO_INFOMSGS;







select STATID,COUNT(1) from energy.dbo.LS_005_ITEMS itm
group by STATID



--UPDATE itm set  itm.WAREHOUSE = fr.LREF   from energy.dbo.LS_005_ITEMS itm
--JOIN  energy.dbo.LS_WAREHOUSE fr on fr.DEFN = itm.ABYS_WAREHOUSE  
--where itm.WAREHOUSE is null 




-- İZGAZ 7 HANE Tel değişikliği

update prm
SET prm.COMMUNICATION_TEXT='( ' + CAST(prm.PHONE_AREA_CODE_ID AS VARCHAR(10)) + ' ) ' 
        + SUBSTRING(prm.COMMUNICATION_TEXT, 1, 3) + ' ' 
        + SUBSTRING(prm.COMMUNICATION_TEXT, 4, 2) + ' ' 
        + SUBSTRING(prm.COMMUNICATION_TEXT, 6, 2),
    prm.PHONE_AREA_CODE_ID=null,
    prm.PHONE_EXTENSION=null
 from LS_005_SUBSCRIBER_COMMUNICATION prm (NOLOCK) 
 WHERE prm.PHONE_AREA_CODE_ID is not null and LEN(prm.COMMUNICATION_TEXT)=7
 
 
-- İZGAZ 9 Hane Tel Değişikliği ve '-' kaldırma

update prm
SET prm.COMMUNICATION_TEXT='( ' + CAST(prm.PHONE_AREA_CODE_ID AS VARCHAR(10)) + ' ) ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 1, 3) + ' ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 4, 2) + ' ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 6, 2),
    prm.PHONE_AREA_CODE_ID=null,
    prm.PHONE_EXTENSION=null
 from LS_005_SUBSCRIBER_COMMUNICATION prm (NOLOCK) 
 WHERE prm.PHONE_AREA_CODE_ID is not null and LEN(prm.COMMUNICATION_TEXT)=9
 

-- İZGAZ Kalan Tel Değiştirme

update prm
SET prm.COMMUNICATION_TEXT='( ' + CAST(prm.PHONE_AREA_CODE_ID AS VARCHAR(10)) + ' ) ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 1, 3) + ' ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 4, 2) + ' ' 
        + SUBSTRING(REPLACE(prm.COMMUNICATION_TEXT, '-', ''), 6, 2),
    prm.PHONE_AREA_CODE_ID=null,
    prm.PHONE_EXTENSION=null
 from LS_005_SUBSCRIBER_COMMUNICATION prm (NOLOCK) 
WHERE prm.PHONE_AREA_CODE_ID is not null and prm.COMMUNICATION_TYPE in(2,3,4,5)
;;;

select COUNT(1)
FROM LS_005_01_AGR agr1
JOIN LS_005_01_AGR agr2 
    ON agr1.FITNO = agr2.FITNO   
WHERE agr1.TP2 = 'ABN'           
  AND agr2.TP2 = 'KUL'       
   --AND ISNULL(agr2.PARID,0) =0

--1.562.263
--1150172

select  ABYS_ID,FITNO, FMETHOD,FPARID,PARID,STATID,COUNTER_STAT,
*  from LS_005_01_AGR agr2    where ISNULL(agr2.PARID,0) =0 and agr2.TP2 = 'KUL'  and STATID not in (11,15)
--group by TP1, STATID
;

742172

select  ABYS_ID,
*  from LS_005_01_AGR agr2    where   agr2.FITNO=742172  and STATID not in (11,15)
;;;

UPDATE agr2
SET agr2.PARID = agr1.LREF
FROM LS_005_01_AGR agr1
JOIN LS_005_01_AGR agr2 
    ON agr1.FLATID = agr2.FLATID   
WHERE agr1.TP2 = 'ABN'           
  AND agr2.TP2 = 'KUL'           
 
 ;;;;;;;


 SELECT COUNT(1)   
 FROM LS_005_01_AGR agr1
JOIN LS_005_01_AGR agr2     ON agr1.FLATID = agr2.FLATID   
WHERE  agr2.TP2 = 'KUL'    AND agr2.PARID is null  

 ;;;;

 select count(1)
 FROM LS_005_01_AGR agr1
JOIN LS_005_01_AGR agr2 
    ON agr1.FLATID = agr2.FLATID   
WHERE agr1.TP2 = 'ABN'    AND agr2.TP2 = 'KUL'           
 
 ;;
 --MHA ve Toplu konutlarda KAzandan bedeller ilk abonelik bedelinden katılım olarka alınıyor ve Bağlantı sözleşmesi

 select * from LS_005_01_AGR where TP2 = 'KUL'   and ISNULL(PARID , 0 )=0  --and ABYS_ID = 1054609
  
  ;;;
   select COUNT(1) from LS_005_01_AGR where AGR_EDATE is not null AND REFUND = 1 AND TP2 = 'KUL'
   ;;;
   select COUNT(1) from LS_005_01_AGR where AGR_EDATE is  null AND ISNULL(REFUND,0) = 0 AND TP2 = 'KUL' 
      ;;;
   select COUNT(1) from LS_005_01_AGR where AGR_EDATE is not null AND ISNULL(REFUND,0) = 0 AND TP2 = 'KUL' 
   ;;;
   --ISACTIVE = 0 SON Sözleşmede sayaç Bilgisi varsa güncellenecek
   select ABYS_INSTALLATION_STATUS,count(1)  from LS_005_01_AGR where COUNTERSN is null AND COUNTERID is null 
   AND TP2 = 'KUL'  AND ISACTIVE = 0
   group by  ABYS_INSTALLATION_STATUS

   ;;;

      select ABYS_INSTALLATION_STATUS , COUNT(1) from LS_005_01_AGR where  
     TP2 = 'KUL'  AND ISACTIVE = 1 and LASTREAD_DATE is NULL  and ABYS_INSTALLATION_STATUS = 'GAZ AÇILDI'
     group by ABYS_INSTALLATION_STATUS
     ;;;


           select  FITNO,*  from LS_005_01_AGR where  
     TP2 = 'KUL'  AND ISACTIVE = 1 and LASTREAD_DATE is NULL  and ABYS_INSTALLATION_STATUS = 'GAZ AÇILDI' AND AGR_EDATE is null
    
    ;;;


    select  top 100 *  from izgazMGR.dbo.LS_ITEMS where LASTENDEX is null  and ISACTIVE = 0  
  ;;;;


   --select itm.LASTENDEX ,  itmMgr.LASTENDEX  


   select 
   itm.LASTENDEX , itmMgr.LASTENDEX  , itmMgr.ABYS_INS_LAST_INDEX  ,itmMgr.ABYS_INSTALLATION_ID
   from LS_005_ITEMS itm
   JOIN  izgazMGR.dbo.LS_ITEMS itmMgr on itm.LREF =itmMgr.METER_ID 
   where 1=1
   --and ISNULL(itm.LASTENDEX,0)=0 
   and ISNULL(itmMgr.ABYS_INS_LAST_INDEX ,0)=0 
   and ISNULL(itmMgr.LASTENDEX ,0)>0 
   and itm.ISACTIVE = 1  
   and ISNULL(itmMgr.ABYS_INSTALLATION_ID,0)>0 

  ;;;


    WITH CTE_KUL AS (
    SELECT 
        KUL.LREF AS KUL_LREF,
        KUL.FITNO AS FITNO,
        KUL.TP1 AS KUL_TP1,      KUL.TP3 AS KUL_TP3,      KUL.
        AS KUL_BN_TYPE,
        ROW_NUMBER() OVER (PARTITION BY KUL.FITNO ORDER BY KUL.LREF) AS RN
    FROM LS_003_01_AGR KUL
    WHERE KUL.TP2 = 'KUL'
)
 


-- ============================================================
-- TESPIT: FLATID'de AGR_EDATE dolu STATID=11 aktif iken,
--         oncesinde (LREF daha kucuk) STATID=9 (EDATE null) var
-- Ornek: FITNO=50190 → aktif 908283(11/EDATE dolu), beklenen 908271(9)
-- ============================================================
;WITH kul AS (
    SELECT
        LREF, FITNO, FLATID, STATID, ISACTIVE, AGR_EDATE, AGR_SDATE
    FROM dbo.LS_005_01_AGR WITH (NOLOCK)
    WHERE TP2 = 'KUL'
      AND FLATID IS NOT NULL
),
prob AS (
    SELECT
        a11.FLATID,
        a11.FITNO,
        a11.LREF        AS LREF_11_ACTIVE,
        a11.STATID      AS STATID_11,
        a11.AGR_EDATE   AS EDATE_11,
        a9.LREF         AS LREF_9_CANDIDATE,
        a9.STATID       AS STATID_9,
        a9.ISACTIVE     AS ISACTIVE_9,
        a9.AGR_EDATE    AS EDATE_9,
        a9.AGR_SDATE    AS SDATE_9
    FROM kul a11
    JOIN kul a9
      ON a9.FLATID = a11.FLATID
     AND a9.STATID = 9
     AND a9.AGR_EDATE IS NULL
     AND a9.LREF < a11.LREF          -- 11'den once
    WHERE a11.STATID = 11
      AND a11.AGR_EDATE IS NOT NULL   -- EDATE dolu
      AND a11.ISACTIVE = 1           -- su an yanlis aktif
)
SELECT
    FLATID, FITNO,
    LREF_9_CANDIDATE, STATID_9, ISACTIVE_9, EDATE_9, SDATE_9,
    LREF_11_ACTIVE, STATID_11, EDATE_11
FROM prob
ORDER BY FITNO, LREF_11_ACTIVE DESC;

-- Ozet
-- SELECT COUNT(DISTINCT FLATID) AS flatid_cnt, COUNT(*) AS row_cnt FROM (...prob...);

-- Tek FITNO detay:
-- SELECT STATID, LREF, FITNO, FLATID, ISACTIVE, AGR_EDATE, AGR_SDATE
-- FROM dbo.LS_005_01_AGR WITH (NOLOCK)
-- WHERE FITNO = 50190 AND TP2 = 'KUL'
-- ORDER BY LREF DESC;


 WITH CTE_KUL AS (
    SELECT 
        KUL.LREF AS KUL_LREF,
        KUL.FITNO AS FITNO,
        KUL.TP1 AS KUL_TP1,      KUL.TP3 AS KUL_TP3,      KUL.BN_TYPE AS KUL_BN_TYPE,
        ROW_NUMBER() OVER (PARTITION BY KUL.FITNO ORDER BY KUL.LREF DESC) AS RN
    FROM LS_005_01_AGR KUL 
    WHERE KUL.TP2 = 'KUL' --and KUL.FITNO = '695760' 
)
UPDATE KUL_SON SET ISACTIVE=1
FROM LS_005_01_AGR KUL_SON
JOIN CTE_KUL KUL    ON KUL_SON.LREF = KUL.KUL_LREF    AND KUL.RN = 1  
WHERE KUL_SON.TP2 = 'KUL'  
;

-- ============================================================
-- UPDATE (CTE_KUL SONRASI): tespit edilenler
-- STATID=9 → ISACTIVE=1, EDATE dolu STATID=11 → 0
-- FLATID basina en yakin (max LREF) STATID=9
-- ============================================================
;WITH kul AS (
    SELECT LREF, FLATID, STATID, ISACTIVE, AGR_EDATE
    FROM dbo.LS_005_01_AGR WITH (NOLOCK)
    WHERE TP2 = 'KUL'
      AND FLATID IS NOT NULL
),
prob AS (
    SELECT
        a11.LREF AS LREF_11,
        a9.LREF  AS LREF_9,
        ROW_NUMBER() OVER (
            PARTITION BY a11.FLATID
            ORDER BY a9.LREF DESC
        ) AS RN
    FROM kul a11
    JOIN kul a9
      ON a9.FLATID = a11.FLATID
     AND a9.STATID = 9
     AND a9.AGR_EDATE IS NULL
     AND a9.LREF < a11.LREF
    WHERE a11.STATID = 11
      AND a11.AGR_EDATE IS NOT NULL
      AND a11.ISACTIVE = 1
),
fix AS (
    SELECT LREF_11, LREF_9
    FROM prob
    WHERE RN = 1
)
UPDATE a
SET a.ISACTIVE = CASE
                    WHEN a.LREF = f.LREF_9  THEN 1
                    WHEN a.LREF = f.LREF_11 THEN 0
                    ELSE a.ISACTIVE
                 END
FROM dbo.LS_005_01_AGR a
JOIN fix f ON a.LREF IN (f.LREF_9, f.LREF_11)
WHERE a.TP2 = 'KUL';
-- kontrol: TESPIT tekrar bos; 50190 → 908271=1, 908283=0

-- O30 tahsilat CTAS export:
--   ABYS_PAYTYPE = Oracle ACTION_TYPE_ID (ham)
--   PAYTYPE / XTYPE = PayType enum (4→32, 5→33, 45→178, 6/24→10, else 174)
-- Overlay sonrasi energy sync ornegi:
-- BEGIN TRAN;
-- UPDATE pt SET
--     pt.PAYTYPE = ov.PAYTYPE,
--     pt.XTYPE   = ov.XTYPE
-- FROM dbo.LS_005_01_PAYTRANS pt
-- JOIN izgazMGR.dbo.LS_OV_PAY_PT ov ON ov.ABYS_ID = pt.ABYS_ID AND ov.ALLOC_RN = 1
-- WHERE ISNULL(pt.TYPE, 0) = 101;
-- COMMIT TRAN;

-- 109 guvence tutar heal — LS_001 kural:
--   TLTOTAL = KDV haric; GRANDTOTAL = KDV dahil (~TL+TAX; 109'da ~TL+DV); alan-alan INV'den
--   Formül: net bedel = GRANDTOTAL - DV
-- calisti energy 2026-08-05: BORC=3964, TAH=1008218; TAX backfill asagida
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
BEGIN TRAN;
UPDATE PAY
SET
    PAY.TLTOTAL      = INV.TLTOTAL,
    PAY.CURTOTAL     = INV.CURTOTAL,
    PAY.TAX          = ISNULL(INV.TAX, 0),
    PAY.GRANDTOTAL   = INV.GRANDTOTAL,
    PAY.PAYABLETOTAL = ISNULL(PAY.PAYABLETOTAL, INV.PAYABLETOTAL),
    PAY.DV           = ISNULL(INV.DV, 0)
FROM dbo.LS_005_01_PAYTRANS AS PAY
INNER JOIN dbo.LS_005_01_INVOICE AS INV ON INV.LREF = PAY.INVOICEREF
WHERE PAY.TYPE = 109
  AND ISNULL(PAY.IOCODE, 0) = 0
  AND (
        (PAY.GRANDTOTAL IS NULL AND PAY.DV IS NULL AND INV.GRANDTOTAL IS NOT NULL)
     OR (PAY.TAX IS NULL AND INV.TAX IS NOT NULL)
      );
-- @@ROWCOUNT borc

UPDATE TAH
SET
    TAH.TLTOTAL      = ISNULL(BORC.TLTOTAL, INV.TLTOTAL),
    TAH.CURTOTAL     = ISNULL(BORC.CURTOTAL, INV.CURTOTAL),
    TAH.TAX          = ISNULL(BORC.TAX, ISNULL(INV.TAX, 0)),
    TAH.GRANDTOTAL   = ISNULL(BORC.GRANDTOTAL, INV.GRANDTOTAL),
    TAH.PAYABLETOTAL = ISNULL(TAH.PAYABLETOTAL, ISNULL(BORC.PAYABLETOTAL, INV.PAYABLETOTAL)),
    TAH.DV           = ISNULL(BORC.DV, ISNULL(INV.DV, 0))
FROM dbo.LS_005_01_PAYTRANS AS TAH
INNER JOIN dbo.LS_005_01_PAYTRANS AS BORC ON TAH.CROSSREF = BORC.LREF
INNER JOIN dbo.LS_005_01_INVOICE AS INV ON INV.LREF = BORC.INVOICEREF
WHERE BORC.TYPE = 109
  AND ISNULL(BORC.IOCODE, 0) = 0
  AND ISNULL(TAH.IOCODE, 0) = 1
  AND (
        (TAH.TLTOTAL IS NULL AND TAH.DV IS NULL AND ISNULL(BORC.TLTOTAL, INV.TLTOTAL) IS NOT NULL)
     OR (TAH.TAX IS NULL AND ISNULL(BORC.TAX, INV.TAX) IS NOT NULL)
      );
-- @@ROWCOUNT tah
COMMIT TRAN;


-- Aktif AGR'ye bagli pasif SERVEQ: ISACTIVE=1 (AGRID = AGR.LREF; wire yok)
EXEC energy.dbo.SP_MIG_AGR_SERVEQ_SYNC_ISACTIVE @DEBUG = 1;
-- AGR.CALCPRESSID ← SERVEQ (COUNTERID = ITEMID)
EXEC energy.dbo.SP_MIG_AGR_SYNC_CALCPRESS_FROM_SERVEQ @DEBUG = 1;

UPDATE opr SET 
opr.REGISTER_REL_ID = USR.USERID
from LS_OPR_SYNC_CLIENT  opr 
JOIN LS_USER  usr on usr.USERCODE = opr.CODE 
Where opr.LREF >639 --and usr.USERCODE = 'Y044' 
;

select * from LS_005_01_AGR where TP2='KUL'

;



--select  ist2.IstasyonNo,sk.KutuNo  , agr.LREF, ABYS_ID AGR_ID, agr.FITNO , agr.BNA_ID, fl.LREF FLAT_ID, fl.BUILDING_DOOR_ID 
select ist2.IstasyonNo,COUNT(1)
from LS_005_01_AGR agr (NOLOCK)
LEFT JOIN LS_FLAT fl (NOLOCK) ON   fl.LREF = agr.FLATID
LEFT JOIN mgg_cbs_kapi t (NOLOCK)  on fl.bna_ID = t.BNA_ID and t .SirketKodu = 4102
LEFT JOIN mgg_cbs_bina_kutu kbna(NOLOCK) ON kbna.bina_id = t .CbsKapiId  
LEFT JOIN mgg_cbs_servis_kutu sk(NOLOCK) ON sk.KutuId = kbna.kutu_id 
LEFT JOIN mgg_cbs_istasyon ist(NOLOCK) ON sk.IstasyonId = ist.IstasyonKodu
LEFT JOIN mgg_cbs_istasyon ist2(NOLOCK) ON ist.UstIstasyonKodu = ist2.IstasyonKodu
where agr.TP2='KUL'  and agr.AGR_EDATE is null -- and ist2.IstasyonNo is null --and sk.KutuNo is not null
group by ist2.IstasyonNo



select dbo.F_GET_ADDRESS(5, LREF),* from LS_005_01_AGR where BNA_ID =1515431;

select agr.BNA_ID,agr.FLATID , lf.LREF,
 mcb.AbysBinaKodu, bn.bina_id 
 from LS_005_01_AGR agr
LEFT JOIN mgg_cbs_kapi mcb  (NOLOCK) ON mcb.AbysBinaKodu =agr.BNA_ID and mcb.SirketKodu =4102
LEFT JOIN mgg_bna bn (NOLOCK) ON bn.bina_id=mcb.AbysBinaKodu and bn.ent_id=4102
lEFT JOIN LS_FLAT lf (NOLOCK) ON lf.LREF=agr.FLATID and lf.ENT_ID=4102
LEFT JOIN LS_FLATDEFN fd (NOLOCK) ON fd.LREF=lf.FLATDEFN
where agr.FITNO=982017


select * from LS_FLAT where LREF = 10577847

select agr.BNA_ID, fl.BNA_ID ,fl.BUILDING_DOOR_ID,dbo.F_GET_ADDRESS( agr.LREF,5)   from LS_005_01_AGR agr
JOIN LS_FLAT fl on fl.LREF = agr.FLATID
where agr.BNA_ID <> -9   and agr.BNA_ID<> fl.BNA_ID
;;;


select ABYS_INSTALLATION_STATUS,count(1) from LS_005_01_AGR  where TP2 = 'KUL'  group by ABYS_INSTALLATION_STATUS,  order by 2 




;;;
SELECT   * FROM izgazMGR.dbo.LS_FLAT mgrFl
JOIN 


select * from mgg_cbs_kapi  where SirketKodu = 4102 and BNA_ID=410904218
;;;;


;;;;
select agr.BNA_ID ,
bn.ic_str+' '+
bn.mh_str+' '+
Case bn.yol_id when 0 then '-' else bn.yol_str end+' '+case bn.site_id when 0 then '-' else bn.site_str end+' '+ISNULL((isnull(bn.blok,'') + ' ' + isnull(bn.biname,'') + '/ No: ' + isnull(bn.bino,'')),'TANIMSIZ')+'/'+fd.LDEFN+':'+cast(lf.FLATNR as nvarchar) as Adres  
from LS_005_01_AGR agr
LEFT JOIN mgg_cbs_kapi mcb  (NOLOCK) ON mcb.AbysBinaKodu =agr.BNA_ID and mcb.SirketKodu =4102
LEFT JOIN mgg_bna bn (NOLOCK) ON bn.bina_id=mcb.AbysBinaKodu and bn.ent_id=4102
lEFT JOIN LS_FLAT lf (NOLOCK) ON lf.LREF=agr.FLATID and lf.ENT_ID=4102
LEFT JOIN LS_FLATDEFN fd (NOLOCK) ON fd.LREF=lf.FLATDEFN
where agr.LREF=1549192

/*

60003
72513
74606
75319
85730
95767
101943
113003
113233
113474
113481
125118
128265
131730
142082
143214
146527
147014
149976
152051
152334
152697
152956
154698
155078
155083
158174
159201

*/

select  ist2.IstasyonNo,sk.KutuNo,kbna.bina_id ,t.BinaAdi , agr.LREF, ABYS_ID AGR_ID, agr.FITNO , agr.BNA_ID, fl.LREF FLAT_ID, fl.BUILDING_DOOR_ID 
from LS_005_01_AGR agr (NOLOCK)
LEFT JOIN LS_FLAT fl (NOLOCK) ON   fl.LREF = agr.FLATID
LEFT JOIN   mgg_cbs_kapi t (NOLOCK)  on fl.bna_ID = t.BNA_ID and t .SirketKodu = 4102
LEFT JOIN  mgg_cbs_bina_kutu kbna(NOLOCK) ON kbna.bina_id = t .CbsKapiId  
LEFT JOIN  mgg_cbs_servis_kutu sk(NOLOCK) ON sk.KutuId = kbna.kutu_id 
LEFT JOIN  mgg_cbs_istasyon ist(NOLOCK) ON sk.IstasyonId = ist.IstasyonKodu
LEFT JOIN  mgg_cbs_istasyon ist2(NOLOCK) ON ist.UstIstasyonKodu = ist2.IstasyonKodu
where agr.TP2='KUL'  and agr.AGR_EDATE is null  and ist2.IstasyonNo is null --and sk.KutuNo is not null
and agr.FITNO=967004
--group by ist2.IstasyonNo


select ist2.IstasyonNo,COUNT(1)
from LS_005_01_AGR agr (NOLOCK)
LEFT JOIN LS_FLAT fl (NOLOCK) ON   fl.LREF = agr.FLATID
LEFT JOIN   mgg_cbs_kapi t (NOLOCK)  on fl.bna_ID = t.BNA_ID and t .SirketKodu = 4102
LEFT JOIN  mgg_cbs_bina_kutu kbna(NOLOCK) ON kbna.bina_id = t .CbsKapiId  
LEFT JOIN  mgg_cbs_servis_kutu sk(NOLOCK) ON sk.KutuId = kbna.kutu_id 
LEFT JOIN  mgg_cbs_istasyon ist(NOLOCK) ON sk.IstasyonId = ist.IstasyonKodu
LEFT JOIN  mgg_cbs_istasyon ist2(NOLOCK) ON ist.UstIstasyonKodu = ist2.IstasyonKodu
where agr.TP2='KUL'  and agr.AGR_EDATE is null   and ist2.IstasyonNo is null -- and sk.KutuNo is not null
 group by ist2.IstasyonNo


select * from izgazMGR.dbo.LS_FLAT where ABYS_ID = 122104



 INSERT INTO energy.dbo.LS_INCOME_PRM (PARENT_ID,COMPANY_CODE,CODE,OVERDUE_INCOME_ID,PRIORITY_PAYMENT_ORDER,PRIORITY_INSTALLMENT_PAY_ORDER,PRIORITY_LEGAL_PAY_ORDER,VAT_INCOME_ID,ACCOUNT_CODE,ACCOUNT_CODE_FINANCE,ACCOUNT_DETAIL_CODE,DUE_ACCOUNT_CODE,INCOME_EXPENSE,COMMISSION_DELAY_TYP_ID,HAS_CPI,IS_VAT_EXCEPT,IS_LEGAL_EXPENSE,IS_LEGAL_FEE,IS_DEPOSIT,IS_BALANCE_INCLUDED,IS_CALC_STAMP_DUTY,IS_CALC_CONSUMPTION,IS_OVERDUE_INCOME,IS_VAT_INCOME,ACCRUE_GROUP_ID,IS_ACTIVE,CREATED_USER_ID,CREATED_TIMESTAMP,UPDATED_USER_ID,UPDATED_TIMESTAMP,VERSION,CURRENT_ACCOUNT_CODE,INSTALLMENT_OVERDUE_INCOME_ID,ACTION_TYPE_ID,IS_CALC_DEPOSIT,ACCOUNT_CODE_LEGAL,ACCOUNT_INTEGRATION_BY_REG,PRIORITY_CUSTODY_PAY_ORDER,OPR_UNIT_TYPE_ID,USE_FOR_ONLINE_APPLICATION,INCOME_TYPE,MAX_INSTALLMENT_COUNT,VALUE_TR,VALUE_ENG,OLD_REF,CODE_2) VALUES
	 (NULL,0,N'924',NULL,NULL,NULL,NULL,NULL,N'',N'',N'',N'',1,NULL,0,1,0,0,0,0,0,1,0,0,86,1,1,'2025-12-24 15:21:58.443',1,'2026-04-01 18:53:31.013',0,N'',NULL,NULL,0,N'',0,NULL,NULL,NULL,NULL,NULL,N'Haberleşme Ünitesi Geliri',NULL,NULL,NULL),
	 (NULL,0,N'937',NULL,NULL,NULL,NULL,NULL,N'',N'',N'',N'',1,NULL,0,1,0,0,0,0,0,0,0,0,86,1,31,'2026-04-27 11:18:30.380',NULL,NULL,0,N'',NULL,NULL,0,N'',0,NULL,NULL,NULL,NULL,NULL,N'Sayaç Fark Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'938',NULL,NULL,NULL,NULL,NULL,N'',N'',N'',N'',1,NULL,0,1,0,0,0,0,0,0,0,0,86,1,31,'2026-04-28 09:42:30.380',NULL,NULL,0,N'',NULL,NULL,0,N'',0,NULL,NULL,NULL,NULL,NULL,N'Hat Deplase Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Emanet Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'29',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'İlave',NULL,NULL,NULL),
	 (NULL,0,N'30',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Fark Kartı',NULL,NULL,NULL),
	 (NULL,0,N'31',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Mahsuplasma',NULL,NULL,NULL),
	 (NULL,0,N'49',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Gecikme Faizi',NULL,NULL,NULL),
	 (NULL,0,N'50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Guvence Bedeli Taksit',NULL,NULL,NULL),
	 (NULL,0,N'55',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'İndirim',NULL,NULL,NULL);
INSERT INTO energy.dbo.LS_INCOME_PRM (PARENT_ID,COMPANY_CODE,CODE,OVERDUE_INCOME_ID,PRIORITY_PAYMENT_ORDER,PRIORITY_INSTALLMENT_PAY_ORDER,PRIORITY_LEGAL_PAY_ORDER,VAT_INCOME_ID,ACCOUNT_CODE,ACCOUNT_CODE_FINANCE,ACCOUNT_DETAIL_CODE,DUE_ACCOUNT_CODE,INCOME_EXPENSE,COMMISSION_DELAY_TYP_ID,HAS_CPI,IS_VAT_EXCEPT,IS_LEGAL_EXPENSE,IS_LEGAL_FEE,IS_DEPOSIT,IS_BALANCE_INCLUDED,IS_CALC_STAMP_DUTY,IS_CALC_CONSUMPTION,IS_OVERDUE_INCOME,IS_VAT_INCOME,ACCRUE_GROUP_ID,IS_ACTIVE,CREATED_USER_ID,CREATED_TIMESTAMP,UPDATED_USER_ID,UPDATED_TIMESTAMP,VERSION,CURRENT_ACCOUNT_CODE,INSTALLMENT_OVERDUE_INCOME_ID,ACTION_TYPE_ID,IS_CALC_DEPOSIT,ACCOUNT_CODE_LEGAL,ACCOUNT_INTEGRATION_BY_REG,PRIORITY_CUSTODY_PAY_ORDER,OPR_UNIT_TYPE_ID,USE_FOR_ONLINE_APPLICATION,INCOME_TYPE,MAX_INSTALLMENT_COUNT,VALUE_TR,VALUE_ENG,OLD_REF,CODE_2) VALUES
	 (NULL,0,N'71',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Limit altı',NULL,NULL,NULL),
	 (NULL,0,N'80',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'İcra Masrafı',NULL,NULL,NULL),
	 (NULL,0,N'87',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Abonelik Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'88',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Proje Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'89',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Kullanım Sözleşmesi Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'94',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Proje Ret Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'96',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'BBS FARKI',NULL,NULL,NULL),
	 (NULL,0,N'98',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Servis Kutusu Yer Değişiklik Talep Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'113',NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'GazTuketim',NULL,NULL,NULL),
	 (NULL,0,N'123',NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Usulsüz Kullanım',NULL,NULL,NULL);
INSERT INTO energy.dbo.LS_INCOME_PRM (PARENT_ID,COMPANY_CODE,CODE,OVERDUE_INCOME_ID,PRIORITY_PAYMENT_ORDER,PRIORITY_INSTALLMENT_PAY_ORDER,PRIORITY_LEGAL_PAY_ORDER,VAT_INCOME_ID,ACCOUNT_CODE,ACCOUNT_CODE_FINANCE,ACCOUNT_DETAIL_CODE,DUE_ACCOUNT_CODE,INCOME_EXPENSE,COMMISSION_DELAY_TYP_ID,HAS_CPI,IS_VAT_EXCEPT,IS_LEGAL_EXPENSE,IS_LEGAL_FEE,IS_DEPOSIT,IS_BALANCE_INCLUDED,IS_CALC_STAMP_DUTY,IS_CALC_CONSUMPTION,IS_OVERDUE_INCOME,IS_VAT_INCOME,ACCRUE_GROUP_ID,IS_ACTIVE,CREATED_USER_ID,CREATED_TIMESTAMP,UPDATED_USER_ID,UPDATED_TIMESTAMP,VERSION,CURRENT_ACCOUNT_CODE,INSTALLMENT_OVERDUE_INCOME_ID,ACTION_TYPE_ID,IS_CALC_DEPOSIT,ACCOUNT_CODE_LEGAL,ACCOUNT_INTEGRATION_BY_REG,PRIORITY_CUSTODY_PAY_ORDER,OPR_UNIT_TYPE_ID,USE_FOR_ONLINE_APPLICATION,INCOME_TYPE,MAX_INSTALLMENT_COUNT,VALUE_TR,VALUE_ENG,OLD_REF,CODE_2) VALUES
	 (NULL,0,N'124',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Sertifika Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'125',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Vize Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'129',NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Gaz Kapama Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'130',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Kalibrasyon Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'131',NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Sökme Takma Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'132',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Özel Hizmet Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'173',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Tahsilat',NULL,NULL,NULL),
	 (NULL,0,N'347',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Ön Ödemeli Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'665',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Kolon Tadilat Cihaz Değişiklik Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'674',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Azami Çekiş Fiyat Farkı',NULL,NULL,NULL);
INSERT INTO energy.dbo.LS_INCOME_PRM (PARENT_ID,COMPANY_CODE,CODE,OVERDUE_INCOME_ID,PRIORITY_PAYMENT_ORDER,PRIORITY_INSTALLMENT_PAY_ORDER,PRIORITY_LEGAL_PAY_ORDER,VAT_INCOME_ID,ACCOUNT_CODE,ACCOUNT_CODE_FINANCE,ACCOUNT_DETAIL_CODE,DUE_ACCOUNT_CODE,INCOME_EXPENSE,COMMISSION_DELAY_TYP_ID,HAS_CPI,IS_VAT_EXCEPT,IS_LEGAL_EXPENSE,IS_LEGAL_FEE,IS_DEPOSIT,IS_BALANCE_INCLUDED,IS_CALC_STAMP_DUTY,IS_CALC_CONSUMPTION,IS_OVERDUE_INCOME,IS_VAT_INCOME,ACCRUE_GROUP_ID,IS_ACTIVE,CREATED_USER_ID,CREATED_TIMESTAMP,UPDATED_USER_ID,UPDATED_TIMESTAMP,VERSION,CURRENT_ACCOUNT_CODE,INSTALLMENT_OVERDUE_INCOME_ID,ACTION_TYPE_ID,IS_CALC_DEPOSIT,ACCOUNT_CODE_LEGAL,ACCOUNT_INTEGRATION_BY_REG,PRIORITY_CUSTODY_PAY_ORDER,OPR_UNIT_TYPE_ID,USE_FOR_ONLINE_APPLICATION,INCOME_TYPE,MAX_INSTALLMENT_COUNT,VALUE_TR,VALUE_ENG,OLD_REF,CODE_2) VALUES
	 (NULL,0,N'675',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Asgari Çekiş Fiyat Farkı',NULL,NULL,NULL),
	 (NULL,0,N'806',NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'SKB Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'807',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Gaz Bedeli Indirim',NULL,NULL,NULL),
	 (NULL,0,N'808',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'SKB Bedeli Indirim',NULL,NULL,NULL),
	 (NULL,0,N'823',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Guvence Bedeli İade',NULL,NULL,NULL),
	 (NULL,0,N'876',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Emanet Bedeli',NULL,NULL,NULL),
	 (NULL,0,N'877',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Emanet Bedeli İade',NULL,NULL,NULL),
	 (NULL,0,N'878',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'Taksit',NULL,NULL,NULL),
	 (NULL,0,N'977',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'KDV',NULL,NULL,NULL),
	 (NULL,0,N'978',NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,0,0,0,0,0,0,0,0,0,0,1,1,1,'2026-05-14 01:19:29.483',NULL,NULL,1,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'DV',NULL,NULL,NULL);
