USE [energy]
GO
/****** Object:  Table [dbo].[LP_EXPENSE_CAUSE_PRM]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_EXPENSE_CAUSE_PRM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [int] NULL,
	[INCOME_ID] [int] NULL,
	[VALUE] [varchar](100) NULL,
	[EXPENSE_TYPE] [int] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[IS_LISTED] [bit] NULL,
	[CREATED_USER_ID] [int] NOT NULL,
	[CREATED_TIMESTAMP] [datetime] NOT NULL,
	[UPDATED_USER_ID] [int] NULL,
	[UPDATED_TIMESTAMP] [datetime] NULL,
	[ABYS_ID] [bigint] NULL,
	[ABYS_CORPORATION_ID] [int] NULL,
	[ABYS_MAIL_ID] [int] NULL,
	[ABYS_LIEN_TYPE_ID] [bigint] NULL,
	[ABYS_VERSION] [bigint] NULL,
	[ABYS_CODE_RAW] [nvarchar](10) NULL,
 CONSTRAINT [LP_EXPENSE_CAUSE_PRM_ID] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LP_INCOME]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_INCOME](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LEGAL_PROCEEDING_ID] [int] NOT NULL,
	[EXPENSE_CAUSE_ID] [int] NOT NULL,
	[AMOUNT] [decimal](10, 2) NOT NULL,
	[INVOICE_ID] [bigint] NULL,
	[STATUS] [tinyint] NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[CREATED_USER_ID] [int] NOT NULL,
	[CREATED_TIMESTAMP] [datetimeoffset](6) NOT NULL,
	[UPDATED_USER_ID] [int] NULL,
	[UPDATED_TIMESTAMP] [datetimeoffset](6) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[ACTION_DATE] [date] NULL,
	[SEND_PAYED_DATE] [datetime2](0) NULL,
	[SEND_PAYED_USER_ID] [int] NULL,
	[ABYS_ID] [bigint] NULL,
	[ABYS_VERSION] [bigint] NULL,
	[ABYS_ACCOUNT_ID] [bigint] NULL,
 CONSTRAINT [PK_LS_LP_EXPENSE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LP_INVOICE]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_INVOICE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REGION] [int] NOT NULL,
	[LEGAL_PROCEEDING_ID] [int] NOT NULL,
	[INVOICE_ID] [int] NOT NULL,
	[AMOUNT] [decimal](10, 2) NULL,
	[OVERDUE] [decimal](10, 2) NULL,
	[OVERDUE_VAT] [decimal](10, 2) NULL,
	[COMMISSION_DELAY_TYPE_ID] [int] NULL,
	[DEBT_GROUP_ID] [int] NULL,
	[EXPIRY_DATE] [datetime] NULL,
	[DUE_INSTALLMENT_ID] [int] NULL,
	[CREATED_USER_ID] [int] NOT NULL,
	[CREATED_TIMESTAMP] [datetime] NOT NULL,
	[UPDATED_USER_ID] [int] NULL,
	[UPDATED_TIMESTAMP] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[ORDER_NUMBER] [int] NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[ABYS_ID] [bigint] NULL,
	[ABYS_VERSION] [bigint] NULL,
	[ABYS_ACCOUNT_ID] [bigint] NULL,
 CONSTRAINT [PK_LS_LP_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LP_LEGAL_PROCEEDING]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_LEGAL_PROCEEDING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REGION] [int] NOT NULL,
	[CODE] [nvarchar](10) NULL,
	[EXECUTIVE_BRANCH_ID] [int] NULL,
	[AGREEMENT_ID] [int] NOT NULL,
	[INSTALLATION_ID] [nvarchar](20) NOT NULL,
	[REGISTER_ID] [int] NOT NULL,
	[PRE_PROCEEDING_DATE] [datetime] NOT NULL,
	[LEGAL_PROCEEDING_DATE] [datetime] NULL,
	[NOTIFICATION_DATE] [datetime] NULL,
	[NOTIFICATION_RECIPIENT] [nvarchar](50) NULL,
	[LAST_PAYMENT_DATE] [datetime] NULL,
	[ENFORCEMENT_OFFICE_ID] [int] NULL,
	[DEBTOR_ATTORNEY_REG_ID] [int] NULL,
	[LAW_TRANSACTION_DATE] [datetime] NULL,
	[LAW_DOC_DATE] [datetime] NULL,
	[LAW_DOC_NUMBER] [nvarchar](50) NULL,
	[RECORD_NUMBER] [nvarchar](50) NULL,
	[CASE_NUMBER] [nvarchar](30) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[SENTENCE_DESCRIPTION] [nvarchar](max) NULL,
	[STATUS] [int] NOT NULL,
	[DEBT] [decimal](10, 2) NOT NULL,
	[OVERDUE] [decimal](10, 2) NOT NULL,
	[OVERDUE_VAT] [decimal](10, 2) NOT NULL,
	[STANDART_EXPENSES] [decimal](10, 2) NOT NULL,
	[LEGAL_PROCEEDING_AMOUNT] [decimal](10, 2) NOT NULL,
	[CHARGE_RATE_ID] [int] NOT NULL,
	[CANCELLATION_DATE] [datetime] NULL,
	[CANCELLATION_USER_ID] [int] NULL,
	[CANCELLATION_CAUSE_ID] [int] NULL,
	[CANCELLATION_DESCRIPTION] [nvarchar](max) NULL,
	[CREATED_USER_ID] [int] NOT NULL,
	[CREATED_TIMESTAMP] [datetime] NOT NULL,
	[UPDATED_USER_ID] [int] NULL,
	[UPDATED_TIMESTAMP] [datetime] NULL,
	[APPEAL_DATE] [datetime] NULL,
	[LAW_ISSUE_ID] [int] NULL,
	[CONFIRMATION_NUMBER] [nvarchar](30) NULL,
	[OLD_LAST_PAYMENT_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[ABYS_ID] [bigint] NULL,
	[ABYS_CORPORATION_ID] [int] NULL,
	[ABYS_TYPE] [smallint] NULL,
	[ABYS_CTV_OVERDUE] [decimal](10, 2) NULL,
	[ABYS_CTV_OVERDUE_VAT] [decimal](10, 2) NULL,
	[ABYS_POOL_ID] [bigint] NULL,
	[ABYS_POOL_DEBT] [decimal](10, 2) NULL,
	[ABYS_POOL_DEBT_COUNT] [smallint] NULL,
	[ABYS_DISTRICT_ID] [int] NULL,
	[ABYS_MTS_NUMBER] [nvarchar](20) NULL,
	[ABYS_JAIL_CHARGE_AMOUNT] [decimal](10, 2) NULL,
	[ABYS_VERSION] [bigint] NULL,
	[ABYS_INSTALLATION_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LP_LEGAL_PROCEEDING_STATUS]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_LEGAL_PROCEEDING_STATUS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [int] NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATED_USER_ID] [int] NOT NULL,
	[CREATED_TIMESTAMP] [datetime] NOT NULL,
	[UPDATED_USER_ID] [int] NULL,
	[UPDATED_TIMESTAMP] [datetime] NULL,
	[COLOR] [nvarchar](20) NULL,
 CONSTRAINT [LP_LEGAL_PROCEEDING_STATUS_ID] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LP_STATUS]    Script Date: 7.08.2026 02:03:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LP_STATUS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LEGAL_PROCEEDING_ID] [int] NOT NULL,
	[STATUS] [int] NOT NULL,
	[STATUS_DATE] [datetime] NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[ABYS_ID] [bigint] NULL,
	[ABYS_VERSION] [bigint] NULL,
	[CREATED_USER_ID] [bigint] NULL,
	[CREATED_TIMESTAMP] [datetimeoffset](7) NULL,
	[UPDATED_USER_ID] [bigint] NULL,
	[UPDATED_TIMESTAMP] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_LP_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LP_EXPENSE_CAUSE_PRM] ADD  CONSTRAINT [DF__LP_EXPENS__IS_AC__78D718B7]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[LP_EXPENSE_CAUSE_PRM] ADD  CONSTRAINT [DF__LP_EXPENS__CREAT__79CB3CF0]  DEFAULT (getdate()) FOR [CREATED_TIMESTAMP]
GO
ALTER TABLE [dbo].[LP_INCOME] ADD  DEFAULT (sysdatetimeoffset()) FOR [CREATED_TIMESTAMP]
GO
ALTER TABLE [dbo].[LP_INCOME] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[LP_INVOICE] ADD  DEFAULT (getdate()) FOR [CREATED_TIMESTAMP]
GO
ALTER TABLE [dbo].[LP_INVOICE] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[LP_LEGAL_PROCEEDING_STATUS] ADD  CONSTRAINT [DF__LP_LEGAL___IS_AC__7CA7A99B]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[LP_LEGAL_PROCEEDING_STATUS] ADD  CONSTRAINT [DF__LP_LEGAL___CREAT__7D9BCDD4]  DEFAULT (getdate()) FOR [CREATED_TIMESTAMP]
GO
