/* =============================================================================
   prodREADY_ENERGY3007 / 90_check_queries.sql
   CREATE OR ALTER PROCEDURE dbo.SP_MIG_90_CHECK  (R24 2026-08-11)
   Cutover sonrası doğrulama (read-only).
   EXEC dbo.SP_MIG_90_CHECK;
   ============================================================================= */
USE energy;
GO
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO
CREATE OR ALTER PROCEDURE dbo.SP_MIG_90_CHECK
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    RAISERROR('========== 1) STEP LOG ==========', 0, 1) WITH NOWAIT;
    IF OBJECT_ID('dbo.MIG_STEP_LOG','U') IS NOT NULL
        SELECT TOP 40 * FROM dbo.MIG_STEP_LOG ORDER BY LOG_ID DESC;
    ELSE IF OBJECT_ID('dbo.SP_MIG_LOG_STATUS','P') IS NOT NULL
        EXEC dbo.SP_MIG_LOG_STATUS;

    RAISERROR('========== 2) ENERGY core counts ==========', 0, 1) WITH NOWAIT;
    SELECT 'INVOICE' T, COUNT_BIG(*) N FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
    UNION ALL SELECT 'INVLINES', COUNT_BIG(*) FROM dbo.LS_005_01_INVLINES WITH (NOLOCK)
    UNION ALL SELECT 'PAYTRANS_DEBT', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
     WHERE ISNULL(IOCODE,0)=0
    UNION ALL SELECT 'PAYTRANS_TAH', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
     WHERE ISNULL(IOCODE,0)=1
    UNION ALL SELECT 'INST_NR_GT0', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
     WHERE ISNULL(IOCODE,0)=0 AND ISNULL(INST_NR,0)>0;

    RAISERROR('========== 3) Checkpoint delta ==========', 0, 1) WITH NOWAIT;
    IF OBJECT_ID('izgazMGR.dbo.CTAS_VALIDATION_CHECKPOINT','U') IS NOT NULL
        SELECT m.TABLE_NAME, m.PHASE, m.ROW_COUNT AS MGR_CNT, m.SUM_AMT AS MGR_SUM,
               m.MAX_LREF, m.CHECKPOINT_TIME, m.NOTE
          FROM izgazMGR.dbo.CTAS_VALIDATION_CHECKPOINT m WITH (NOLOCK)
         WHERE m.PHASE IN ('PRE_ENERGY','SUM_PAYABLE_IO0','LREF_CHECK','PAY_PAID_GAP')
         ORDER BY m.CHECKPOINT_ID DESC;

    SELECT COUNT_BIG(*) EN_INV_IO0,
           SUM(CONVERT(DECIMAL(18,2), ISNULL(PAYABLETOTAL,0))) EN_PAYABLE
      FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
     WHERE ISNULL(IOCODE,0)=0 AND ISNULL(CANCELED,0)=0;

    RAISERROR('========== 4) Taksit PAID gap ==========', 0, 1) WITH NOWAIT;
    SELECT COUNT(*) INST_UNPAID_OPEN
      FROM dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
      JOIN dbo.LS_005_01_INVOICE inv WITH (NOLOCK) ON inv.LREF = pt.INVOICEREF
     WHERE ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.CANCELED,0)=0 AND ISNULL(pt.INST_NR,0)>0
       AND ISNULL(inv.CLOSED,0)=1
       AND ISNULL(pt.PAID,0)+0.01 < ISNULL(pt.PAYABLETOTAL,0);

    RAISERROR('========== 5) IPP vs ENERGY paid ==========', 0, 1) WITH NOWAIT;
    IF OBJECT_ID('izgazMGR.dbo.LS_INSTALLMENT_PLAN_PAY','U') IS NOT NULL
    SELECT
      (SELECT COUNT(*) FROM izgazMGR.dbo.LS_INSTALLMENT_PLAN_PAY WITH (NOLOCK) WHERE ISNULL(IS_PAID,0)=1) IPP_PAID,
      (SELECT COUNT(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
        WHERE ISNULL(IOCODE,0)=0 AND ISNULL(INST_NR,0)>0 AND ISNULL(PAID,0)>0.01) EN_INST_PAID,
      (SELECT COUNT(*) FROM dbo.LS_005_01_PAYTRANS debt WITH (NOLOCK)
        JOIN dbo.LS_005_01_PAYTRANS pay WITH (NOLOCK)
          ON pay.CROSSREF = debt.LREF AND ISNULL(pay.IOCODE,0)=1
       WHERE ISNULL(debt.IOCODE,0)=0 AND ISNULL(debt.INST_NR,0)>0
         AND ISNULL(debt.PAID,0)>0.01) EN_INST_WITH_TAH;

    RAISERROR('========== 6) BANK_RECORD_REF sample ==========', 0, 1) WITH NOWAIT;
    SELECT TOP 20 inv.OWNERREF, inv.LREF, inv.CLOSED, inv.LASTPAIDDATE, inv.BANKREF,
           pt.INST_NR, pt.PAID, pt.BANKREF PT_BANK, pt.BANK_RECORD_REF, pt.LASTPAIDDATE PT_LPD
      FROM dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
      JOIN dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
        ON pt.INVOICEREF = inv.LREF AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0
     WHERE ISNULL(pt.PAID,0)>0.01
     ORDER BY inv.LREF DESC, pt.INST_NR;

    RAISERROR('========== 7) FRK soft AFL ==========', 0, 1) WITH NOWAIT;
    IF OBJECT_ID('izgazMGR.dbo.LS_AFL_OPEN_DEBT','U') IS NOT NULL
        SELECT
          (SELECT COUNT(*) FROM izgazMGR.dbo.LS_AFL_OPEN_DEBT WITH (NOLOCK) WHERE MIG_IN_SCOPE=1) AFL_MIG,
          (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
            WHERE ISNULL(IOCODE,0)=0 AND ISNULL(CANCELED,0)=0 AND ISNULL(CLOSED,0)=0) EN_OPEN;
    ELSE
        SELECT
          (SELECT COUNT(*) FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
            WHERE ISNULL(IOCODE,0)=0 AND ISNULL(CANCELED,0)=0 AND ISNULL(CLOSED,0)=0) EN_OPEN;

    RAISERROR('========== SP_MIG_90_CHECK DONE ==========', 0, 1) WITH NOWAIT;
END
GO
/* EXEC dbo.SP_MIG_90_CHECK; */
