/* =============================================================================
   prodREADY_ENERGY3007 / 91d_debt_paid_sync_from_tah.sql
   SSMS — residual heal (PAID ← tahsilat tutarı)

   Sadece gerçek gap: açık borç PAYABLE>0 ve
     PAID < LEAST(SUM(tah.PAID|PAYABLETOTAL|TLTOTAL), PAYABLE)

   TLTOTAL şişmesi heal etmez (yanlış alarm); tutar tah.PAID öncelikli.

   @DryRun=1 tespit | 0 uygula
   ============================================================================= */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @DryRun    BIT    = 1;
DECLARE @AGR_ID    BIGINT = NULL;
DECLARE @INV_LREF  INT    = NULL;
DECLARE @DEBT_LREF INT    = NULL;
DECLARE @CloseInv  BIT    = 1;
-- SET @DryRun = 0;

DECLARE @t0 DATETIME2(3) = SYSDATETIME();
PRINT CONVERT(VARCHAR(30), @t0, 121)
    + N' | 91d PAID heal DryRun=' + CAST(@DryRun AS VARCHAR(1));

IF OBJECT_ID('tempdb..#NEED') IS NOT NULL DROP TABLE #NEED;

;WITH tah AS (
    SELECT
        t.CROSSREF AS DEBT_LREF,
        CONVERT(DECIMAL(18,2), SUM(
            CASE
                WHEN ISNULL(t.PAYABLETOTAL, 0) <> 0
                    THEN CONVERT(DECIMAL(18,2), t.PAYABLETOTAL)
                WHEN ISNULL(t.PAID, 0) <> 0
                    THEN CONVERT(DECIMAL(18,2), t.PAID)
                ELSE CONVERT(DECIMAL(18,2), ISNULL(t.TLTOTAL, 0))
            END
        )) AS SUM_AMT,
        COUNT(*) AS TAH_CNT
    FROM dbo.LS_005_01_PAYTRANS t WITH (NOLOCK)
    WHERE t.CROSSREF IS NOT NULL
      AND t.IOCODE = 1
      AND ISNULL(t.CANCELED, 0) = 0
      AND (
            ISNULL(t.PAID, 0) > 0.01
         OR ISNULL(t.PAYABLETOTAL, 0) > 0.01
         OR ISNULL(t.TLTOTAL, 0) > 0.01
      )
      AND (@DEBT_LREF IS NULL OR t.CROSSREF = @DEBT_LREF)
    GROUP BY t.CROSSREF
)
SELECT
    d.LREF AS DEBT_LREF,
    d.INVOICEREF,
    d.ABYS_AGREEMENT_ID AS AGR,
    ISNULL(d.INST_NR, 0) AS INST_NR,
    CONVERT(DECIMAL(18,2), ISNULL(d.PAID, 0)) AS OLD_PAID,
    CONVERT(DECIMAL(18,2), d.PAYABLETOTAL) AS PAYABLE,
    tah.SUM_AMT,
    tah.TAH_CNT,
    CONVERT(DECIMAL(18,2),
        CASE WHEN tah.SUM_AMT > CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
             THEN CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
             ELSE tah.SUM_AMT END
    ) AS NEW_PAID
INTO #NEED
FROM tah
INNER JOIN dbo.LS_005_01_PAYTRANS d WITH (NOLOCK)
    ON d.LREF = tah.DEBT_LREF
WHERE d.IOCODE = 0
  AND ISNULL(d.CANCELED, 0) = 0
  AND ISNULL(d.CANCELLATIONPAYMENT, 0) = 0
  AND CONVERT(DECIMAL(18,2), ISNULL(d.PAYABLETOTAL, 0)) > 0.01
  AND (@AGR_ID IS NULL OR d.ABYS_AGREEMENT_ID = @AGR_ID)
  AND (@INV_LREF IS NULL OR d.INVOICEREF = @INV_LREF)
  AND CONVERT(DECIMAL(18,2), ISNULL(d.PAID, 0)) + 0.01 <
      CASE WHEN tah.SUM_AMT > CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
           THEN CONVERT(DECIMAL(18,2), d.PAYABLETOTAL)
           ELSE tah.SUM_AMT END
OPTION (RECOMPILE, MAXDOP 8);

CREATE UNIQUE CLUSTERED INDEX CX_NEED ON #NEED (DEBT_LREF);

PRINT '========== TESPIT ==========';
SELECT
    COUNT(*) AS DEBT_NEED,
    CONVERT(DECIMAL(18,2), SUM(NEW_PAID - OLD_PAID)) AS TOTAL_DELTA,
    CASE WHEN COUNT(*) = 0 THEN N'PASS — heal gerekmez'
         ELSE N'RESIDUAL — apply ile duzelir' END AS STATUS
FROM #NEED;

SELECT
    DEBT_LREF, INVOICEREF, AGR, INST_NR,
    OLD_PAID, PAYABLE, SUM_AMT, TAH_CNT, NEW_PAID,
    CONVERT(DECIMAL(18,2), NEW_PAID - OLD_PAID) AS DELTA
FROM #NEED
ORDER BY DELTA DESC;

IF @DryRun = 1
BEGIN
    PRINT 'DRY_RUN=1 — UPDATE yok';
    RETURN;
END

BEGIN TRAN;
UPDATE d
SET d.PAID = CONVERT(FLOAT, n.NEW_PAID)
FROM dbo.LS_005_01_PAYTRANS d
INNER JOIN #NEED n ON n.DEBT_LREF = d.LREF;
PRINT 'PAID updated=' + CAST(@@ROWCOUNT AS VARCHAR(20));

IF @CloseInv = 1
BEGIN
    UPDATE inv
    SET inv.CLOSED = 1
    FROM dbo.LS_005_01_INVOICE inv
    INNER JOIN #NEED n ON n.INVOICEREF = inv.LREF
    WHERE n.NEW_PAID + 0.01 >= n.PAYABLE
      AND ISNULL(inv.CLOSED, 0) = 0
      AND ISNULL(inv.IOCODE, 0) = 0
      AND ISNULL(inv.CANCELED, 0) = 0;
    PRINT 'INV CLOSED=' + CAST(@@ROWCOUNT AS VARCHAR(20));
END
COMMIT TRAN;

PRINT CONVERT(VARCHAR(30), SYSDATETIME(), 121) + N' | 91d DONE';
GO
