/* ============================================================
   SCRIPT_ID : REF_TARIFF_CHECK
   SCRIPT_NO : 133
   FILE      : 133_REF_TARIFF__check.sql
   VERSION   : 1
   ============================================================ */
USE energy;
GO

-- Tarife ozet
SELECT 'LS_TARIFF_TYPE_PRM' AS TABLO, COUNT(*) AS SATIR FROM energy.dbo.LS_TARIFF_TYPE_PRM
UNION ALL
SELECT 'LS_TARIFF_PRM', COUNT(*) FROM energy.dbo.LS_TARIFF_PRM
UNION ALL
SELECT 'LS_TARIFF_INCOME_PRM', COUNT(*) FROM energy.dbo.LS_TARIFF_INCOME_PRM
UNION ALL
SELECT 'LS_TARIFF_INCOME_DISCOUNT_PRM', COUNT(*) FROM energy.dbo.LS_TARIFF_INCOME_DISCOUNT_PRM;
GO

-- ABYS aktarim sayilari
SELECT 'LS_TARIFF_TYPE_PRM' AS TABLO, COUNT(*) AS ABYS_SATIR
FROM energy.dbo.LS_TARIFF_TYPE_PRM
WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT 'LS_TARIFF_PRM', COUNT(*)
FROM energy.dbo.LS_TARIFF_PRM
WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT 'LS_TARIFF_INCOME_PRM', COUNT(*)
FROM energy.dbo.LS_TARIFF_INCOME_PRM
WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT 'LS_TARIFF_INCOME_DISCOUNT_PRM', COUNT(*)
FROM energy.dbo.LS_TARIFF_INCOME_DISCOUNT_PRM
WHERE ABYS_ID IS NOT NULL;
GO

-- Eslesmeyen subscriber type
SELECT COUNT(*) AS ESLESMEYEN_SUBSCRIBER_TYPE
FROM energy.dbo.LS_TARIFF_TYPE_PRM t
WHERE t.SUBSCRIBER_TYPE_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM energy.dbo.LS_AGR_TYPE a
      WHERE a.LREF = t.SUBSCRIBER_TYPE_ID
  );
GO

-- Eslesmeyen tariff
SELECT COUNT(*) AS ESLESMEYEN_TARIFF_ID
FROM energy.dbo.LS_TARIFF_INCOME_PRM i
WHERE i.TARIFF_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM energy.dbo.LS_TARIFF_PRM t
      WHERE t.ID = i.TARIFF_ID
  );
GO

-- Eslesmeyen income
SELECT COUNT(*) AS ESLESMEYEN_INCOME_ID
FROM energy.dbo.LS_TARIFF_INCOME_PRM i
WHERE i.INCOME_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM energy.dbo.LS_INCOME_PRM p
      WHERE p.LREF = i.INCOME_ID
  );
GO

-- Indirim tablosu eslesmeyen income
SELECT COUNT(*) AS ESLESMEYEN_DISCOUNT_INCOME_ID
FROM energy.dbo.LS_TARIFF_INCOME_DISCOUNT_PRM d
WHERE d.INCOME_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM energy.dbo.LS_INCOME_PRM p
      WHERE p.LREF = d.INCOME_ID
  );
GO

-- Son hata loglari
SELECT TOP 20
    l.MIGRATION_CODE,
    l.BATCH_NO,
    l.BRIDGE_FROM,
    l.BRIDGE_TO,
    l.ERROR_MSG,
    l.LOGGED_AT
FROM energy.dbo.MIG_BATCH_LOG l
WHERE l.MIGRATION_CODE IN (
    'LS_TARIFF_TYPE_PRM',
    'LS_TARIFF_PRM',
    'LS_TARIFF_INCOME_PRM',
    'LS_TARIFF_INCOME_DISCOUNT_PRM'
)
ORDER BY l.LOGGED_AT DESC;
GO

