/* ============================================================
   SCRIPT_ID : MASTER_ITEMS_SETUP
   SCRIPT_NO : 240
   FILE      : 240_MASTER_ITEMS__setup.sql
   VERSION   : 2
   ============================================================ */
-- ============================================================
-- izgazMGR.dbo.LS_ITEMS → energy.dbo.LS_005_ITEMS
-- ABYS köprü kolonları + kaynak view + MIG_ROW_ID (ADDDATE sırası)
-- LREF ← METER_ID (IDENTITY_INSERT ON → insert → OFF; sonra CHECKIDENT)
--
-- Not: Kaynak staging'de UPDUSER (datetimeoffset) / UPDDATE (bigint)
--      kolonları tip olarak yer değiştirmiş olabilir — view'da düzeltilir.
-- ============================================================
USE energy;
GO

-- ------------------------------------------------------------
-- Hedef ABYS kolonları
-- ------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_MIG_ROW_ID')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_MIG_ROW_ID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_METER_ID')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_METER_ID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_OLREF')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_OLREF BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_INSTALLATION_ID')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_INSTALLATION_ID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_WAREHOUSE')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_WAREHOUSE NVARCHAR(1000) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_INS_LAST_INDEX')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_INS_LAST_INDEX DECIMAL(25, 3) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_KORR_LAST_INDEX')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_KORR_LAST_INDEX DECIMAL(25, 3) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_READING_DATE')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_READING_DATE DATETIME2(0) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_KORR_READING_DATE')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_KORR_READING_DATE DATETIME2(0) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_METER_MODEL')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_METER_MODEL NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_METER_TYPE_ID')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_METER_TYPE_ID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_MARK')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_MARK NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'ABYS_METER_KIND')
    ALTER TABLE energy.dbo.LS_005_ITEMS ADD ABYS_METER_KIND SMALLINT NULL;
GO

-- DESCRIPTION: kaynak nvarchar(2000) ile hizala
IF EXISTS (
    SELECT 1
    FROM sys.columns c
    WHERE c.object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS')
      AND c.name = 'DESCRIPTION'
      AND c.max_length > 0
      AND c.max_length < 4000  -- nvarchar bytes; 2000 char = 4000
)
    ALTER TABLE energy.dbo.LS_005_ITEMS ALTER COLUMN DESCRIPTION NVARCHAR(2000) NULL;
GO

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'UX_LS005_ITEMS_ABYS_MIG')
    DROP INDEX UX_LS005_ITEMS_ABYS_MIG ON energy.dbo.LS_005_ITEMS;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'UX_LS005_ITEMS_ABYS_MIG')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LS005_ITEMS_ABYS_MIG
        ON energy.dbo.LS_005_ITEMS (ABYS_MIG_ROW_ID)
        WHERE ABYS_MIG_ROW_ID IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('energy.dbo.LS_005_ITEMS') AND name = 'UX_LS005_ITEMS_ABYS_METER')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LS005_ITEMS_ABYS_METER
        ON energy.dbo.LS_005_ITEMS (ABYS_METER_ID)
        WHERE ABYS_METER_ID IS NOT NULL;
GO

-- ------------------------------------------------------------
-- Kaynak: MIG_ROW_ID köprüsü (view'dan once kolonlar)
-- ------------------------------------------------------------
IF OBJECT_ID('izgazMGR.dbo.LS_ITEMS', 'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('izgazMGR.dbo.LS_ITEMS', 'MIG_ROW_ID') IS NOT NULL
       AND COLUMNPROPERTY(OBJECT_ID('izgazMGR.dbo.LS_ITEMS'), 'MIG_ROW_ID', 'IsIdentity') = 1
    BEGIN
        IF EXISTS (
            SELECT 1 FROM izgazMGR.sys.indexes
            WHERE object_id = OBJECT_ID('izgazMGR.dbo.LS_ITEMS')
              AND name = 'UX_LS_005_ITEMS_MIG_ROW'
        )
            DROP INDEX UX_LS_005_ITEMS_MIG_ROW ON izgazMGR.dbo.LS_ITEMS;

        ALTER TABLE izgazMGR.dbo.LS_ITEMS DROP COLUMN MIG_ROW_ID;
    END

    IF COL_LENGTH('izgazMGR.dbo.LS_ITEMS', 'MIG_ROW_ID') IS NULL
        ALTER TABLE izgazMGR.dbo.LS_ITEMS ADD MIG_ROW_ID BIGINT NULL;

    IF COL_LENGTH('izgazMGR.dbo.LS_ITEMS', '_MIG_UID') IS NULL
        ALTER TABLE izgazMGR.dbo.LS_ITEMS ADD _MIG_UID INT IDENTITY(1, 1) NOT NULL;
END
GO

/*

INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (114,N'ESAGUN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (121,N'OSIMSEK',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (123,N'AKINA',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (417,N'BCOBAN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (213,N'KKARAKOC',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (120,N'MAKIN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (119,N'MKARACAYIR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (12,N'YASAKLI SAYAÇ AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (412,N'SYAYLA',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (514,N'GAZDAŞ AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (2,N'MÜŞTERİ AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (5,N'İZMİT ABONELİK OFİSİ',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (6,N'HURDA AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (124,N'YAKGUN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (513,N'PALEN GAZ AMBAR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (1,N'MERKEZ AMBAR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (4,N'YEDİKAT FİRMA AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (8,N'İÇ TESİSAT MÜTEAHHİT AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (10,N'VAVEN-KALİBRASYON FIRMASI 2 ',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (117,N'VOZDEMIR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (112,N'ASERT',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (415,N'ODEMIR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (512,N'PALGAZ AMBAR',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (118,N'UOGUZ',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (212,N'HYILDIZ',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (418,N'AKARE_YUNUSEMRE',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (116,N'MEHMETORKUN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (7,N'SAYAÇ OKUMA BİRİMİ AMBARI',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (214,N'FTURAN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (122,N'SAMETERAY',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (414,N'EHURMAN',5,1,4102,1);
INSERT INTO energy.dbo.LS_WAREHOUSE (NR,DEFN,FIRMNR,ISACTIVE,ENT_ID,IS_REMOVE_WAREHOUSE)VALUES (115,N'EKABA',5,1,4102,1);



INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'SCHLUMBERGER' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'ITRON' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FABRICANT PAR DEFAUT' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'DRESSER' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'ECA' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'METRIX' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'INSTROMET' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'KALE_KALIP' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'MAGNOL' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'ACTARIS' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'RMG' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'SACOFGAZ' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FMG' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FIORENTİNİ' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'IMETER' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FİORENTİNİ' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FEDERAL' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'GWF' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'MANAR' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'GMT' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'AEM' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'NATEK' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'FMG' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'METER' ,0,1,GETDATE())
INSERT INTO energy.dbo.LS_005_FIRM ([TYPE],NAME_,STATUS ,ADDUSER,ADDDATE)VALUES (0,'RMG' ,0,1,GETDATE())


*/

CREATE OR ALTER PROCEDURE dbo.SP_MIG_ITEMS_PREP_SOURCE
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('izgazMGR.dbo.LS_ITEMS', 'U') IS NULL
        RETURN;

    IF COL_LENGTH('izgazMGR.dbo.LS_ITEMS', 'MIG_ROW_ID') IS NULL
       OR COL_LENGTH('izgazMGR.dbo.LS_ITEMS', '_MIG_UID') IS NULL
    BEGIN
        RAISERROR('LS_005_ITEMS: MIG_ROW_ID veya _MIG_UID yok. Once 19_ls005_items_setup.sql calistirin.', 16, 1);
        RETURN;
    END

    ;WITH Ordered AS (
        SELECT
            s._MIG_UID,
            ROW_NUMBER() OVER (
                ORDER BY
                    CAST(s.ADDDATE AS DATETIME2),
                    s.METER_ID,
                    s._MIG_UID
            ) AS NewMigRowId
        FROM izgazMGR.dbo.LS_ITEMS s
    )
    UPDATE s
    SET s.MIG_ROW_ID = o.NewMigRowId
    FROM izgazMGR.dbo.LS_ITEMS s
    INNER JOIN Ordered o ON o._MIG_UID = s._MIG_UID;

    IF EXISTS (
        SELECT 1 FROM izgazMGR.dbo.LS_ITEMS WHERE MIG_ROW_ID IS NULL
    )
        RAISERROR('LS_005_ITEMS: MIG_ROW_ID atamasi tamamlanamadi.', 16, 1);

    IF EXISTS (
        SELECT 1 FROM izgazMGR.sys.indexes
        WHERE object_id = OBJECT_ID('izgazMGR.dbo.LS_ITEMS')
          AND name = 'UX_LS_005_ITEMS_MIG_ROW'
    )
        DROP INDEX UX_LS_005_ITEMS_MIG_ROW ON izgazMGR.dbo.LS_ITEMS;

    CREATE UNIQUE NONCLUSTERED INDEX UX_LS_005_ITEMS_MIG_ROW
        ON izgazMGR.dbo.LS_ITEMS (MIG_ROW_ID);
END
GO

EXEC dbo.SP_MIG_ITEMS_PREP_SOURCE;
GO

-- MID / WAREHOUSE: kaynak kolon adlari (MID, WAREHOUSE) ile cakismayi onlemek icin
-- scalar fonksiyon + RESOLVED_* alias kullanilir
CREATE OR ALTER FUNCTION dbo.FN_MIG_ITEMS_RESOLVE_MID (@MarkRef BIGINT)
RETURNS INT
AS
BEGIN
    DECLARE @R INT;

    SELECT TOP (1) @R = sm.LREF
    FROM energy.dbo.LS_STC_MODEL sm
    WHERE sm.ABYS_CODE = @MarkRef
    ORDER BY sm.LREF;

    RETURN @R;
END
GO

CREATE OR ALTER FUNCTION dbo.FN_MIG_ITEMS_RESOLVE_WH (@WhNr BIGINT)
RETURNS INT
AS
BEGIN
    DECLARE @R INT;

    SELECT TOP (1) @R = wr.LREF
    FROM energy.dbo.LS_WAREHOUSE wr
    WHERE wr.NR = TRY_CAST(@WhNr AS INT)
      AND wr.ENT_ID = 4102
    ORDER BY wr.LREF;

    RETURN @R;
END
GO

-- ------------------------------------------------------------
-- Kaynak view (MIG_ROW_ID PREP sonrasi)
-- RESOLVED_MID  ← LS_STC_MODEL.LREF (ABYS_CODE = MARK_REF)
-- RESOLVED_WH   ← LS_WAREHOUSE.LREF (NR = kaynak WAREHOUSE, ENT_ID = 4102)
-- Cap / Tip     ← kaynak CAP / TIP
-- Basinc        ← METER_PRESSURE_REF (kaynakta Basinc yok)
-- ------------------------------------------------------------
CREATE OR ALTER VIEW dbo.VW_MIG_LS005_ITEMS_SOURCE
AS
SELECT
    s.MIG_ROW_ID,
    s.METER_ID,
    energy.dbo.FN_MIG_ITEMS_RESOLVE_MID(s.MARK_REF)           AS RESOLVED_MID,
    LEFT(s.DEFN, 50)                                          AS DEFN,
    LEFT(s.ACCCODE, 50)                                       AS ACCCODE,
    LEFT(s.STOCKCODE, 50)                                     AS STOCKCODE,
    CAST(s.LASTENDEX AS FLOAT)                                AS LASTENDEX,
    LEFT(s.SNNO_TEXT, 50)                                     AS SNNO_TEXT,
    LEFT(s.SNNO_NR, 50)                                       AS SNNO_NR,
    energy.dbo.FN_MIG_ITEMS_RESOLVE_WH(s.WAREHOUSE)           AS RESOLVED_WH,
    CAST(TRY_CAST(s.SUPLID AS BIGINT) AS INT)                 AS SUPLID,
    CAST(TRY_CAST(s.STATID AS BIGINT) AS INT)                 AS STATID,
    CAST(ISNULL(s.ISACTIVE, 0) AS BIT)                        AS ISACTIVE,
    energy.dbo.FN_MIG_MAP_USER_USERID(CAST(s.ADDUSER AS INT)) AS ADDUSER,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.ADDDATE AS DATETIME2)) AS ADDDATE,
    energy.dbo.FN_MIG_MAP_USER_USERID(CAST(TRY_CAST(s.UPDDATE AS BIGINT) AS INT)) AS UPDUSER,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.UPDUSER AS DATETIME2)) AS UPDDATE,
    CAST(TRY_CAST(s.CNT_DIGIT AS BIGINT) AS TINYINT)          AS CNT_DIGIT,
    CAST(CASE WHEN ISNULL(s.CNT_DIRECTION, 0) <> 0 THEN 1 ELSE 0 END AS BIT) AS CNT_DIRECTION,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.INV_DATE AS DATETIME2)) AS INV_DATE,
    LEFT(s.INV_NO, 50)                                        AS INV_NO,
    s.OLREF                                                   AS ABYS_OLREF_RAW,
    CAST(TRY_CAST(s.OLREF AS BIGINT) AS INT)                  AS OLREF,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.PRODDATE AS DATETIME2)) AS PRODDATE,
    CAST(energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(s.CALIBRATIONDATE AS DATETIME2)) AS DATE) AS CALIBRATIONDATE,
    CAST(TRY_CAST(s.CALIBRATIONCOUNT AS BIGINT) AS INT)       AS CALIBRATIONCOUNT,
    CAST(TRY_CAST(s.CALIBRATIONFIRM AS BIGINT) AS INT)        AS CALIBRATIONFIRM,
    LEFT(s.DESCRIPTION, 2000)                                 AS DESCRIPTION,
    CAST(CASE WHEN ISNULL(s.HAS_CORRECTOR_MODULE, 0) <> 0 THEN 1 ELSE 0 END AS BIT) AS HAS_CORRECTOR_MODULE,
    CAST(s.MARK_REF AS INT)                                   AS MARK_REF,
    CAST(s.METER_CLASS_REF AS INT)                            AS METER_CLASS_REF,
    CAST(TRY_CAST(s.METER_DIAMETER_REF AS BIGINT) AS INT)     AS METER_DIAMETER_REF,
    CAST(s.METER_PRESSURE_REF AS INT)                         AS METER_PRESSURE_REF,
    LEFT(s.CAP, 50)                                           AS Cap,
    CAST(s.METER_PRESSURE_REF AS NVARCHAR(50))                AS Basinc,
    LEFT(s.TIP, 50)                                           AS Tip,
    s.ABYS_WAREHOUSE,
    s.ABYS_INSTALLATION_ID,
    s.ABYS_INS_LAST_INDEX,
    s.ABYS_KORR_LAST_INDEX,
    s.ABYS_READING_DATE,
    s.ABYS_KORR_READING_DATE,
    s.ABYS_METER_MODEL,
    s.ABYS_METER_TYPE_ID,
    s.ABYS_MARK,
    s.ABYS_METER_KIND,
    s.MARK_REF                                                AS ABYS_MARK_REF,
    s.WAREHOUSE                                               AS ABYS_WAREHOUSE_NR
FROM izgazMGR.dbo.LS_ITEMS s
WHERE s.MIG_ROW_ID IS NOT NULL;
GO

IF OBJECT_ID('dbo.SP_MIG_ITEMS_INSERT_ONE', 'P') IS NOT NULL
    EXEC sys.sp_refreshsqlmodule N'dbo.SP_MIG_ITEMS_INSERT_ONE';
IF OBJECT_ID('dbo.SP_MIGRATE_LS005_ITEMS', 'P') IS NOT NULL
    EXEC sys.sp_refreshsqlmodule N'dbo.SP_MIGRATE_LS005_ITEMS';
GO

CREATE OR ALTER PROCEDURE dbo.SP_MIG_ITEMS_VALIDATE_SOURCE
    @RaiseOnMissing BIT = 1
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('izgazMGR.dbo.LS_ITEMS', 'U') IS NULL
    BEGIN
        IF @RaiseOnMissing = 1
            RAISERROR('izgazMGR.dbo.LS_ITEMS bulunamadi.', 16, 1);
        RETURN 1;
    END

    DECLARE @Missing NVARCHAR(MAX) = N'';

    ;WITH Required (COL_NAME) AS (
        SELECT v.COL_NAME FROM (VALUES
            ('METER_ID'), ('DEFN'), ('ACCCODE'), ('STOCKCODE'),
            ('LASTENDEX'), ('SNNO_TEXT'), ('SNNO_NR'), ('WAREHOUSE'),
            ('SUPLID'), ('STATID'), ('ISACTIVE'), ('ADDDATE'), ('ADDUSER'),
            ('UPDUSER'), ('UPDDATE'), ('CNT_DIGIT'), ('CNT_DIRECTION'),
            ('INV_DATE'), ('INV_NO'), ('OLREF'), ('PRODDATE'),
            ('CALIBRATIONDATE'), ('CALIBRATIONCOUNT'), ('CALIBRATIONFIRM'),
            ('DESCRIPTION'), ('HAS_CORRECTOR_MODULE'), ('MARK_REF'),
            ('METER_CLASS_REF'), ('METER_DIAMETER_REF'), ('METER_PRESSURE_REF'),
            ('CAP'), ('TIP'),
            ('ABYS_WAREHOUSE'), ('ABYS_INSTALLATION_ID'),
            ('ABYS_INS_LAST_INDEX'), ('ABYS_KORR_LAST_INDEX'),
            ('ABYS_READING_DATE'), ('ABYS_KORR_READING_DATE'),
            ('ABYS_METER_MODEL'), ('ABYS_METER_TYPE_ID'),
            ('ABYS_MARK'), ('ABYS_METER_KIND')
        ) v(COL_NAME)
    )
    SELECT @Missing = STRING_AGG(r.COL_NAME, ', ')
    FROM Required r
    WHERE NOT EXISTS (
        SELECT 1
        FROM izgazMGR.sys.columns c
        INNER JOIN izgazMGR.sys.tables t ON t.object_id = c.object_id
        INNER JOIN izgazMGR.sys.schemas sch ON sch.schema_id = t.schema_id
        WHERE sch.name = 'dbo' AND t.name = 'LS_ITEMS' AND c.name = r.COL_NAME
    );

    IF @Missing IS NOT NULL AND @Missing <> N''
    BEGIN
        DECLARE @Msg NVARCHAR(4000) = N'LS_005_ITEMS eksik kolonlar: ' + @Missing;
        IF @RaiseOnMissing = 1 RAISERROR(@Msg, 16, 1);
        RETURN 1;
    END

    IF @RaiseOnMissing = 0
        SELECT N'izgazMGR.dbo.LS_ITEMS kaynak dogrulama OK' AS VALIDATION_MESSAGE;

    RETURN 0;
END
GO

-- ------------------------------------------------------------
-- Aktarim sonrasi duzeltmeler (manuel calistir)
-- Onerilen sira:
--   1) WAREHOUSE ← ABYS_WAREHOUSE
--   2) STATID/ISACTIVE (+ gerekiyorsa LREF remap)
--   3) SUPLID ← ABYS_MARK
-- Warehouse / Firm seed INSERT'leri yukaridaki comment blogunda kalir; calistirilmaz.
-- ------------------------------------------------------------
/*

-- 1) WAREHOUSE ← ABYS_WAREHOUSE (ENT_ID = 4102)
UPDATE itm
SET itm.WAREHOUSE = fr.LREF
FROM energy.dbo.LS_005_ITEMS itm
JOIN energy.dbo.LS_WAREHOUSE fr ON fr.DEFN = itm.ABYS_WAREHOUSE
WHERE fr.ENT_ID = 4102
  AND itm.ABYS_MIG_ROW_ID IS NOT NULL;

-- 2) STATID / ISACTIVE / WAREHOUSE remap (WHERE = hedef LREF; ortama gore dogrulayin)
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 2, ISACTIVE = 1 WHERE WAREHOUSE = 2  AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1 WHERE WAREHOUSE = 1  AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1 WHERE WAREHOUSE = 5  AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 3, ISACTIVE = 0 WHERE WAREHOUSE = 44 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 3, ISACTIVE = 1 WHERE WAREHOUSE = 35 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1 WHERE WAREHOUSE = 43 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 5, ISACTIVE = 1 WHERE WAREHOUSE = 7  AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 5, ISACTIVE = 1 WHERE WAREHOUSE = 38  AND ABYS_MIG_ROW_ID IS NOT NULL;

UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1 WHERE WAREHOUSE = 42  AND ABYS_MIG_ROW_ID IS NOT NULL;

UPDATE energy.dbo.LS_005_ITEMS SET STATID = 4, ISACTIVE = 1 WHERE WAREHOUSE = 53 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 0 WHERE WAREHOUSE = 40 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 0 WHERE WAREHOUSE = 48 AND ABYS_MIG_ROW_ID IS NOT NULL;
UPDATE energy.dbo.LS_005_ITEMS SET STATID = 5, ISACTIVE = 0 WHERE WAREHOUSE IN (45, 6, 33, 31, 57, 46, 52, 32, 49, 56, 34, 47, 54, 29, 28, 27,26, 50, 39, 51)   AND ABYS_MIG_ROW_ID IS NOT NULL;

UPDATE LS_005_ITEMS set  SNNO_TEXT= TRIM(SNNO_TEXT),SNNO_NR = TRIM(SNNO_NR)



--select WAREHOUSE,ABYS_WAREHOUSE ,STATID ,count(1) from energy.dbo.LS_005_ITEMS  group  BY WAREHOUSE,ABYS_WAREHOUSE  ,STATID 




 

-- 3) SUPLID ← ABYS_MARK → LS_005_FIRM
UPDATE itm
SET itm.SUPLID = fr.LREF
FROM energy.dbo.LS_005_ITEMS itm
JOIN energy.dbo.LS_005_FIRM fr ON fr.NAME_ = itm.ABYS_MARK
WHERE itm.ABYS_MIG_ROW_ID IS NOT NULL;




*/

