/* ============================================================
   SCRIPT_ID : INSTALLMENT_PLAN_CHECK
   SCRIPT_NO : 612
   FILE      : 612_INSTALLMENT_PLAN__check.sql
   VERSION   : 1
   ============================================================ */
-- Manuel kontrol sorgulari (deploy disi)
USE energy;
GO

-- Kaynak vs ABYS hedef sayim
SELECT
    (SELECT SUM(p.rows)
     FROM izgazMGR.sys.partitions p
     INNER JOIN izgazMGR.sys.tables t ON t.object_id = p.object_id
     INNER JOIN izgazMGR.sys.schemas s ON s.schema_id = t.schema_id
     WHERE s.name = 'dbo' AND t.name = 'CS_INSTALLMENT_PLAN' AND p.index_id IN (0, 1)
    ) AS SRC_APPROX,
    (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WHERE ABYS_ID IS NOT NULL) AS TGT_ABYS,
    (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WHERE ABYS_ID IS NULL) AS TGT_NATIVE,
    (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WHERE ABYS_ID IS NOT NULL AND ISACTIVE = 1) AS TGT_ACTIVE,
    (SELECT COUNT_BIG(*) FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WHERE ABYS_ID IS NOT NULL AND ISACTIVE = 0) AS TGT_INACTIVE;
GO

-- TOTAL_AMOUNT = AMOUNT + LATE + OVERDUE tutarsizligi
SELECT 'TOTAL_AMOUNT mismatch', COUNT(*) AS CNT
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN
WHERE ABYS_ID IS NOT NULL
  AND ABS(
        ISNULL(TOTAL_AMOUNT, 0)
      - (ISNULL(ABYS_AMOUNT, 0) + ISNULL(ABYS_LATE_CHARGE, 0) + ISNULL(ABYS_OVERDUE, 0))
      ) > 0.01;
GO

-- ISACTIVE vs iptal/muaccelle tutarsizligi
SELECT 'ISACTIVE vs cancel/due mismatch', COUNT(*) AS CNT
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN
WHERE ABYS_ID IS NOT NULL
  AND (
        (ISACTIVE = 1 AND (ABYS_CANCELLATION_DATE IS NOT NULL OR ABYS_INSTALLMENT_DUE_DATE IS NOT NULL))
     OR (ISACTIVE = 0 AND ABYS_CANCELLATION_DATE IS NULL AND ABYS_INSTALLMENT_DUE_DATE IS NULL)
  );
GO

-- PLAN_ID = ABYS_INSTALLMENT_ID olmali
SELECT 'PLAN_ID <> ABYS_INSTALLMENT_ID', COUNT(*) AS CNT
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN
WHERE ABYS_ID IS NOT NULL
  AND (PLAN_ID IS NULL OR CAST(PLAN_ID AS BIGINT) <> ABYS_INSTALLMENT_ID);
GO

-- INSTALLMENT_COUNT vs ORDER_NUMBER
SELECT 'INSTALLMENT_COUNT <> ABYS_ORDER_NUMBER', COUNT(*) AS CNT
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN
WHERE ABYS_ID IS NOT NULL
  AND ISNULL(INSTALLMENT_COUNT, -1) <> ISNULL(ABYS_ORDER_NUMBER, -2);
GO

-- Eksik kaynak
SELECT COUNT(*) AS MISSING_IN_TARGET
FROM izgazMGR.dbo.CS_INSTALLMENT_PLAN s
WHERE s.ID BETWEEN 1 AND 2147483647
  AND EXISTS (
      SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins WHERE ins.ID = s.INSTALLMENT_ID
  )
  AND NOT EXISTS (
      SELECT 1 FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN t WHERE t.ABYS_ID = CAST(s.ID AS BIGINT)
  );
GO

-- Fatura wire orani
SELECT
    COUNT(*) AS TGT_TOTAL,
    SUM(CASE WHEN INVOICE_REF IS NOT NULL THEN 1 ELSE 0 END) AS WITH_INVOICE,
    SUM(CASE WHEN INVOICE_REF IS NULL THEN 1 ELSE 0 END) AS WITHOUT_INVOICE
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN
WHERE ABYS_ID IS NOT NULL;
GO

-- Ornek
SELECT TOP 20
    t.LREF, t.ABYS_ID, t.PLAN_ID, t.ABYS_INSTALLMENT_ID, t.INSTALLMENT_COUNT,
    t.TOTAL_AMOUNT, t.ABYS_AMOUNT, t.ABYS_LATE_CHARGE, t.ABYS_OVERDUE,
    t.ISACTIVE, t.INVOICE_REF, t.PAYTRANS_REF,
    t.OWNERREF, t.ABYS_AGREEMENT_ID,
    t.ABYS_EXPIRY_DATE, t.ABYS_PAYMENT_DATE,
    t.ABYS_CANCELLATION_DATE, t.ABYS_INSTALLMENT_DUE_DATE
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN t
WHERE t.ABYS_ID IS NOT NULL
ORDER BY t.ABYS_ID;
GO

-- Coklu pilot AGR ozet (MIG_PARAM seti ile ayni)
SELECT
    v.AGR_ID,
    COUNT(*) AS PLAN_ROWS,
    SUM(CASE WHEN ISACTIVE = 1 THEN 1 ELSE 0 END) AS ACTIVE_ROWS,
    SUM(CASE WHEN INVOICE_REF IS NOT NULL THEN 1 ELSE 0 END) AS WITH_INVOICE,
    SUM(CASE WHEN PAYTRANS_REF IS NOT NULL THEN 1 ELSE 0 END) AS WITH_PAYTRANS
FROM (VALUES
    (CAST(276503 AS BIGINT)),
    (556305),(197168),(5727),(2221),(978259),(1192595)
) v(AGR_ID)
LEFT JOIN energy.dbo.LS_005_01_INSTALLMENT_PLAN t WITH (NOLOCK)
    ON t.ABYS_AGREEMENT_ID = v.AGR_ID AND t.ABYS_ID IS NOT NULL
GROUP BY v.AGR_ID
ORDER BY v.AGR_ID;
GO
