/* ============================================================
   SCRIPT_ID : OPS_MIGLOG_CHECK
   SCRIPT_NO : 900
   FILE      : 900_OPS_MIGLOG__check.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- Migrasyon log — raporlama sorguları
-- ============================================================
USE energy;
GO

-- Son çalıştırmalar (tüm tablolar)
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = NULL;

-- IT_USER son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'IT_USER';

-- CS_REGISTER son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'CS_REGISTER';

-- CS_REGISTER_COMMUNICATION son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'CS_REGISTER_COMMUNICATION';

-- GIS_BUILDING_FLAT / LS_FLAT son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_FLAT';

-- LS_005_01_AGR_GUARANTY son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_01_AGR_GUARANTY';

-- LS_005_01_AGR son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_01_AGR';

-- LS_005_01_AGR_CLOSE son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_01_AGR_CLOSE';

-- LS_005_01_AGR_DEV_TR son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_01_AGR_DEV_TR';

-- LS_005_ITEMS son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_ITEMS';

-- LS_005_FUID son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'LS_005_FUID';

-- MGG_CBS_OKUMA_BOLGE son run
EXEC energy.dbo.SP_MIG_LOG_GET_SUMMARY @MigrationCode = 'MGG_CBS_OKUMA_BOLGE';

-- Canlı ilerleme (RUNNING)
SELECT
    r.MIGRATION_CODE,
    r.INSERTED_COUNT   AS AKTARILAN,
    r.SOURCE_ROW_COUNT AS TOPLAM_KAYNAK,
    r.SKIPPED_COUNT    AS ATLANAN,
    r.ERROR_COUNT      AS HATA,
    CASE
        WHEN r.SOURCE_ROW_COUNT > 0
        THEN CAST(100.0 * r.INSERTED_COUNT / r.SOURCE_ROW_COUNT AS DECIMAL(6,2))
    END AS ILERLEME_YUZDE,
    r.LAST_BRIDGE_KEY,
    r.MAX_BRIDGE_KEY,
    r.STARTED_AT,
    DATEDIFF(SECOND, r.STARTED_AT, SYSDATETIME()) AS GECEN_SN
FROM energy.dbo.MIG_RUN r
WHERE r.STATUS = 'RUNNING';

-- Batch hataları
SELECT TOP 100
    l.MIGRATION_CODE,
    l.PHASE,
    l.BATCH_NO,
    l.BRIDGE_FROM,
    l.BRIDGE_TO,
    l.SOURCE_ID,
    l.ERROR_MSG,
    l.LOGGED_AT
FROM energy.dbo.MIG_BATCH_LOG l
WHERE l.STATUS = 'ERROR'
ORDER BY l.LOGGED_AT DESC;

-- Eksik kayıt kontrolü (IT_USER)
SELECT COUNT(*) AS EKSIK
FROM izgazMGR.dbo.IT_USER u
WHERE NOT EXISTS (
    SELECT 1 FROM energy.dbo.LS_USER t WHERE t.ABYS_ID = u.ID
);

-- USERID offset dogrulama (USERID = ABYS_ID + 10000)
SELECT COUNT(*) AS OFFSET_MISMATCH
FROM energy.dbo.LS_USER t
WHERE t.ABYS_ID IS NOT NULL
  AND t.USERID <> t.ABYS_ID + 10000;

-- Native USERID bandi (1..10000) cakisma riski
SELECT
    ISNULL(MAX(CASE WHEN ABYS_ID IS NULL THEN USERID END), 0) AS NATIVE_MAX_USERID,
    ISNULL(MAX(CASE WHEN ABYS_ID IS NOT NULL THEN ABYS_ID END), 0) AS MAX_ABYS_ID,
    ISNULL(MAX(CASE WHEN ABYS_ID IS NOT NULL THEN USERID END), 0) AS MAX_MAPPED_USERID
FROM energy.dbo.LS_USER;

-- Kaynak / hedef karşılaştırma (CS_REGISTER)
SELECT 'KAYNAK' AS TABLO, COUNT(*) AS SATIR FROM izgazMGR.dbo.CS_REGISTER
UNION ALL SELECT 'SUBSCR', COUNT(*) FROM energy.dbo.LS_005_SUBSCR
UNION ALL SELECT 'FIRM',   COUNT(*) FROM energy.dbo.LS_005_FIRM;

-- CS_REGISTER batch hataları
SELECT TOP 100
    l.MIGRATION_CODE, l.PHASE, l.BATCH_NO,
    l.BRIDGE_FROM, l.BRIDGE_TO, l.SOURCE_ID, l.ERROR_MSG, l.LOGGED_AT
FROM energy.dbo.MIG_BATCH_LOG l
WHERE l.MIGRATION_CODE = 'CS_REGISTER'
  AND l.STATUS = 'ERROR'
ORDER BY l.LOGGED_AT DESC;

-- Tip haritası dışı kayıtlar
SELECT r.ID, pt.PRIMARY_TYPE_ID
FROM izgazMGR.dbo.CS_REGISTER r
LEFT JOIN (
    SELECT REGISTER_ID, MIN(REGISTER_TYPE_ID) AS PRIMARY_TYPE_ID
    FROM izgazMGR.dbo.CS_REGISTER_REGISTER_TYPE
    GROUP BY REGISTER_ID
) pt ON pt.REGISTER_ID = r.ID
WHERE pt.PRIMARY_TYPE_ID IS NULL
   OR pt.PRIMARY_TYPE_ID NOT IN (
        1,13,14,15,72,2,3,4,5,6,7,8,9,10,11,12,32,33,53,92,93,94);

-- Kaynak / hedef karşılaştırma (CS_REGISTER_COMMUNICATION)
SELECT 'KAYNAK' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.CS_REGISTER_COMMUNICATION
UNION ALL
SELECT 'HEDEF', COUNT(*)
FROM energy.dbo.LS_005_SUBSCRIBER_COMMUNICATION;

-- Geçersiz tarih (datetime aralığı dışı) — ADDDATE GETDATE() ile doldurulur
SELECT COUNT(*) AS GECERSIZ_TARIH_SAYISI
FROM izgazMGR.dbo.CS_REGISTER_COMMUNICATION c
WHERE CAST(c.CREATED_TIMESTAMP AS DATETIME2) < '1753-01-01'
   OR (c.UPDATED_TIMESTAMP IS NOT NULL
       AND CAST(c.UPDATED_TIMESTAMP AS DATETIME2) < '1753-01-01');

SELECT TOP 100
    c.ID,
    c.CREATED_TIMESTAMP,
    c.UPDATED_TIMESTAMP,
    energy.dbo.FN_SAFE_DT(CAST(c.CREATED_TIMESTAMP AS DATETIME2)) AS ADDDATE_HEDEF,
    energy.dbo.FN_SAFE_DT(CAST(c.UPDATED_TIMESTAMP AS DATETIME2)) AS UPDDATE_HEDEF
FROM izgazMGR.dbo.CS_REGISTER_COMMUNICATION c
WHERE CAST(c.CREATED_TIMESTAMP AS DATETIME2) < '1753-01-01'
   OR (c.UPDATED_TIMESTAMP IS NOT NULL
       AND CAST(c.UPDATED_TIMESTAMP AS DATETIME2) < '1753-01-01')
ORDER BY c.ID;

-- Eksik kayıt (CS_REGISTER_COMMUNICATION → LREF = kaynak ID)
SELECT COUNT(*) AS EKSIK
FROM izgazMGR.dbo.CS_REGISTER_COMMUNICATION c
WHERE NOT EXISTS (
    SELECT 1
    FROM energy.dbo.LS_005_SUBSCRIBER_COMMUNICATION t
    WHERE t.LREF = c.ID
);

-- Kaynak / hedef (izgazMGR.dbo.LS_FLAT → energy.dbo.LS_FLAT, ENT_ID=4102)
SELECT 'KAYNAK_STAGING' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.LS_FLAT
WHERE ABYS_INSTALLATION_ID IS NOT NULL AND TRY_CAST(ENT_ID AS BIGINT) = 4102
UNION ALL
SELECT 'VIEW_ENT_4102', COUNT(*)
FROM energy.dbo.VW_MIG_LS_FLAT_SOURCE
WHERE ENT_ID = 4102
UNION ALL
SELECT 'HEDEF_ABYS', COUNT(*)
FROM energy.dbo.LS_FLAT
WHERE ENT_ID = 4102 AND ABYS_INSTALLATION_ID IS NOT NULL;

SELECT COUNT(*) AS EKSIK_FLAT
FROM energy.dbo.VW_MIG_LS_FLAT_SOURCE s
WHERE s.ENT_ID = 4102
  AND NOT EXISTS (
    SELECT 1 FROM energy.dbo.LS_FLAT t
    WHERE t.ABYS_INSTALLATION_ID = s.ABYS_INSTALLATION_ID AND t.ENT_ID = 4102
);

-- Kaynak / hedef (LS_AGR_GUARANTY → LS_005_01_AGR_GUARANTY)
SELECT 'KAYNAK_STAGING' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.LS_AGR_GUARANTY
UNION ALL
SELECT 'HEDEF_ABYS', COUNT(*)
FROM energy.dbo.LS_005_01_AGR_GUARANTY
WHERE ABYS_MIG_ROW_ID IS NOT NULL;

SELECT COUNT(*) AS EKSIK_GUARANTY
FROM izgazMGR.dbo.LS_AGR_GUARANTY s
WHERE NOT EXISTS (
    SELECT 1 FROM energy.dbo.LS_005_01_AGR_GUARANTY t
    WHERE t.ABYS_MIG_ROW_ID = s.MIG_ROW_ID
);

-- datetimeoffset örnek kontrol (ADDDATE/UPDDATE)
SELECT TOP 20
    s.MIG_ROW_ID,
    st.ADDDATE AS KAYNAK_ADDDATE,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(st.ADDDATE AS DATETIME2)) AS HEDEF_ADDDATE,
    st.UPDDATE AS KAYNAK_UPDDATE,
    energy.dbo.FN_SAFE_SMALLDT_DEP(CAST(st.UPDDATE AS DATETIME2)) AS HEDEF_UPDDATE
FROM izgazMGR.dbo.LS_AGR_GUARANTY st
INNER JOIN energy.dbo.VW_MIG_DEPOSIT_GUARANTY_SOURCE s ON s.MIG_ROW_ID = st.MIG_ROW_ID
WHERE st.ADDDATE IS NOT NULL OR st.UPDDATE IS NOT NULL;

-- Kaynak / hedef (izgazMGR.dbo.LS_AGR_DEVICE → energy.dbo.LS_005_01_AGR_DEV_TR)
SELECT 'KAYNAK_STAGING' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.LS_AGR_DEVICE
UNION ALL
SELECT 'VIEW', COUNT(*)
FROM energy.dbo.VW_MIG_AGR_DEVICE_SOURCE
UNION ALL
SELECT 'HEDEF_ABYS', COUNT(*)
FROM energy.dbo.LS_005_01_AGR_DEV_TR
WHERE ABYS_MIG_ROW_ID IS NOT NULL;

SELECT COUNT(*) AS EKSIK_AGR_DEV_TR
FROM energy.dbo.VW_MIG_AGR_DEVICE_SOURCE s
WHERE NOT EXISTS (
    SELECT 1 FROM energy.dbo.LS_005_01_AGR_DEV_TR t
    WHERE t.ABYS_MIG_ROW_ID = s.MIG_ROW_ID
);

-- Kaynak / hedef (izgazMGR.dbo.LS_005_ITEMS → energy.dbo.LS_005_ITEMS)
SELECT 'KAYNAK_STAGING' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.LS_005_ITEMS
UNION ALL
SELECT 'VIEW', COUNT(*)
FROM energy.dbo.VW_MIG_LS005_ITEMS_SOURCE
UNION ALL
SELECT 'HEDEF_ABYS', COUNT(*)
FROM energy.dbo.LS_005_ITEMS
WHERE ABYS_MIG_ROW_ID IS NOT NULL;

SELECT COUNT(*) AS EKSIK_ITEMS
FROM energy.dbo.VW_MIG_LS005_ITEMS_SOURCE s
WHERE NOT EXISTS (
    SELECT 1 FROM energy.dbo.LS_005_ITEMS t
    WHERE t.ABYS_MIG_ROW_ID = s.MIG_ROW_ID
);

-- MID / WAREHOUSE join eslesme kontrolu
SELECT COUNT(*) AS ESLESMEYEN_MID
FROM energy.dbo.VW_MIG_LS005_ITEMS_SOURCE v
WHERE v.RESOLVED_MID IS NULL AND v.ABYS_MARK_REF IS NOT NULL;

SELECT COUNT(*) AS ESLESMEYEN_WAREHOUSE
FROM energy.dbo.VW_MIG_LS005_ITEMS_SOURCE v
WHERE v.RESOLVED_WH IS NULL AND v.ABYS_WAREHOUSE_NR IS NOT NULL;

SELECT TOP 20
    v.MIG_ROW_ID, v.METER_ID,
    v.ABYS_MARK_REF, v.RESOLVED_MID,
    v.ABYS_WAREHOUSE_NR, v.RESOLVED_WH,
    st.MID AS KAYNAK_MID_KOLONU
FROM energy.dbo.VW_MIG_LS005_ITEMS_SOURCE v
INNER JOIN izgazMGR.dbo.LS_005_ITEMS st ON st.MIG_ROW_ID = v.MIG_ROW_ID
WHERE v.RESOLVED_MID IS NULL OR v.RESOLVED_WH IS NULL;

-- KonumWkt SRID / koordinat kontrolu (KonumWkt = LOCATION__wkt → geometry 3857)
SELECT TOP 5
    src.CODE,
    LEFT(src.LOCATION__wkt, 120) AS Kaynak_Wkt_OnEk,
    s.KonumWkt.STAsText() AS GeomWkt,
    s.KonumWkt.STSrid AS Hedef_SRID,
    LEFT(CONVERT(VARCHAR(MAX), s.KonumWkt.STAsBinary(), 2), 8) AS Hex_OnEk
FROM energy.dbo.VW_MIG_READING_PLAN_SOURCE s
INNER JOIN izgazMGR.dbo.CS_READING_PLAN src ON src.MIG_ROW_ID = s.MIG_ROW_ID
WHERE s.KonumWkt IS NOT NULL;

SELECT COUNT(*) AS LOCATION__wkt_BOS
FROM izgazMGR.dbo.CS_READING_PLAN
WHERE LOCATION__wkt IS NULL OR LTRIM(RTRIM(LOCATION__wkt)) = N'';

-- Kaynak / hedef (CS_READING_PLAN → mgg_cbs_okuma_bolge)
SELECT 'KAYNAK' AS TABLO, COUNT(*) AS SATIR
FROM izgazMGR.dbo.CS_READING_PLAN
UNION ALL
SELECT 'VIEW', COUNT(*)
FROM energy.dbo.VW_MIG_READING_PLAN_SOURCE
UNION ALL
SELECT 'HEDEF_ABYS', COUNT(*)
FROM energy.dbo.mgg_cbs_okuma_bolge
WHERE ABYS_MIG_ROW_ID IS NOT NULL;

SELECT COUNT(*) AS EKSIK_OKUMA_BOLGE
FROM energy.dbo.VW_MIG_READING_PLAN_SOURCE s
WHERE NOT EXISTS (
    SELECT 1 FROM energy.dbo.mgg_cbs_okuma_bolge t
    WHERE t.ABYS_MIG_ROW_ID = s.MIG_ROW_ID
);

SELECT TOP 10
    s.MIG_ROW_ID, s.ABYS_ID, s.ABYS_CODE, s.OkumaBolgeAdi,
    CASE WHEN s.KonumWkt IS NULL THEN 0 ELSE 1 END AS KONUM_VAR
FROM energy.dbo.VW_MIG_READING_PLAN_SOURCE s;

-- UPDUSER/UPDDATE swap kontrol (kaynak tipine gore)
SELECT TOP 20
    MIG_ROW_ID, METER_ID,
    ADDUSER, ADDDATE,
    UPDUSER AS KAYNAK_UPDUSER_DT,
    UPDDATE AS KAYNAK_UPDDATE_USR,
    v.UPDUSER AS HEDEF_UPDUSER,
    v.UPDDATE AS HEDEF_UPDDATE
FROM izgazMGR.dbo.LS_005_ITEMS st
INNER JOIN energy.dbo.VW_MIG_LS005_ITEMS_SOURCE v ON v.MIG_ROW_ID = st.MIG_ROW_ID;

-- ============================================================
-- ÇALIŞTIRMA ÖRNEKLERİ
-- ============================================================
-- Tam sıfırla + insert:
-- EXEC energy.dbo.SP_MIGRATE_IT_USER
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- Kaldığı yerden (STOPPED/PAUSED sonrası):
-- EXEC energy.dbo.SP_MIGRATE_IT_USER
--      @RESUME = 1, @DEBUG = 1;
--
-- İlk çalıştırma (mevcut LS_USER korunur, idempotent):
-- EXEC energy.dbo.SP_MIGRATE_IT_USER
--      @RESUME = 0, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- CS_REGISTER tam sıfırla + insert:
-- EXEC energy.dbo.SP_MIGRATE_CS_REGISTER
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @MAX_ERROR = 500, @DEBUG = 1;
--
-- CS_REGISTER kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_CS_REGISTER
--      @RESUME = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- CS_REGISTER_COMMUNICATION tam sıfırla:
-- EXEC energy.dbo.SP_MIGRATE_CS_REGISTER_COMMUNICATION
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @MAX_ERROR = 500, @DEBUG = 1;
--
-- CS_REGISTER_COMMUNICATION kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_CS_REGISTER_COMMUNICATION
--      @RESUME = 1, @DEBUG = 1;
--
-- GIS_BUILDING_FLAT tam sıfırla (sadece ENT_ID=4102 ABYS kayitlari, batch delete):
-- EXEC energy.dbo.SP_MIG_FLAT_HARD_RESET @ENT_ID = 4102, @DELETE_BATCH = 5000, @DEBUG = 1;
-- EXEC energy.dbo.SP_MIGRATE_GIS_BUILDING_FLAT
--      @HARD_RESET = 1, @ENT_ID = 4102, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- GIS_BUILDING_FLAT kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_GIS_BUILDING_FLAT
--      @RESUME = 1, @ENT_ID = 4102, @DEBUG = 1;
--
-- LS_005 teminat tam sıfırla:
-- EXEC energy.dbo.SP_MIGRATE_LS005_DEPOSIT_GUARANTY
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- LS_005 teminat kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_LS005_DEPOSIT_GUARANTY
--      @RESUME = 1, @DEBUG = 1;
--
-- LS_005_ITEMS tam sıfırla:
-- EXEC energy.dbo.SP_MIGRATE_LS005_ITEMS
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- LS_005_ITEMS kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_LS005_ITEMS
--      @RESUME = 1, @DEBUG = 1;
--
-- LS_005_FUID tam sıfırla:
-- EXEC energy.dbo.SP_MIGRATE_LS005_FUID
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- LS_005_FUID kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_LS005_FUID
--      @RESUME = 1, @DEBUG = 1;
--
-- LS_005_01_AGR_DEV_TR tam sıfırla:
-- EXEC energy.dbo.SP_MIGRATE_LS005_AGR_DEV
--      @HARD_RESET = 1, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- LS_005_01_AGR_DEV_TR kaldığı yerden:
-- EXEC energy.dbo.SP_MIGRATE_LS005_AGR_DEV
--      @RESUME = 1, @DEBUG = 1;
--
-- AGR migrate sonrası AGRID wiring:
-- EXEC energy.dbo.SP_MIG_WIRE_AGR_DEV_AGRID @Debug = 1;
--
-- Kaynak / hedef (me_factor_value → LS_005_FUID)
-- SELECT COUNT(*) AS KAYNAK FROM izgazMGR.dbo.me_factor_value;
-- SELECT COUNT(*) AS HEDEF  FROM energy.dbo.LS_005_FUID;
-- SELECT COUNT(*) AS RMS_ESLESMEYEN
-- FROM izgazMGR.dbo.me_factor_value s
-- WHERE NOT EXISTS (
--     SELECT 1 FROM energy.dbo.LS_005_RMS r WHERE r.DEFN = CONVERT(NVARCHAR(50), s.SERVICE_BOX_ID)
-- );
--
-- CS_READING_PLAN → mgg_cbs_okuma_bolge tam sıfırla:
 EXEC energy.dbo.SP_MIGRATE_CS_READING_PLAN_OKUMA_BOLGE
      @HARD_RESET = 1, @SIRKET_KODU = 4102, @BATCH_SIZE = 5000, @DEBUG = 1;
--
-- CS_READING_PLAN kaldığı yerden:
 EXEC energy.dbo.SP_MIGRATE_CS_READING_PLAN_OKUMA_BOLGE
      @RESUME = 1, @SIRKET_KODU = 4102, @DEBUG = 1;
-- ============================================================

