/* ============================================================
   FILE : adim3_verify_indexes.sql
   Dogrulama / clean icin destek index (idempotent)
   CREATE: WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON)
   ============================================================ */
USE izgazMGR;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INVOICE') AND name = 'IX_MIG_LSINV_AGR_ACTION'
)
CREATE NONCLUSTERED INDEX IX_MIG_LSINV_AGR_ACTION
    ON dbo.LS_INVOICE (ABYS_AGREEMENT_ID, ABYS_ACTION_ID)
    INCLUDE (PAYABLETOTAL, TLTOTAL, TAX, GRANDTOTAL, IOCODE, LREF)
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

/* Full 571 ARITH/BETWEEN: heap uzerinde ABYS_ACTION_ID index sart */
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INVOICE') AND name = 'IX_MIG_LSINV_ACTION'
)
CREATE NONCLUSTERED INDEX IX_MIG_LSINV_ACTION
    ON dbo.LS_INVOICE (ABYS_ACTION_ID)
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF OBJECT_ID('dbo.LS_INVLINES', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INVLINES') AND name = 'IX_MIG_LSIL_AGR'
)
CREATE NONCLUSTERED INDEX IX_MIG_LSIL_AGR
    ON dbo.LS_INVLINES (ABYS_AGREEMENT_ID)
    INCLUDE (LREF, INVOICEREF, GRANDTOTAL, TLTOTAL, TAX, ABYS_INCOME_ROW_ID)
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF OBJECT_ID('dbo.LS_INVLINES', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INVLINES') AND name = 'IX_MIG_LSIL_INVREF'
)
CREATE NONCLUSTERED INDEX IX_MIG_LSIL_INVREF
    ON dbo.LS_INVLINES (INVOICEREF)
    INCLUDE (LREF, GRANDTOTAL, ABYS_INCOME_ROW_ID)
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

/* 581 KEYSET: her batch TOP..ORDER BY LREF — index yoksa full scan */
IF OBJECT_ID('dbo.LS_INVLINES', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_INVLINES') AND name = 'IX_MIG_LSINVLINES_LREF'
)
CREATE NONCLUSTERED INDEX IX_MIG_LSINVLINES_LREF
    ON dbo.LS_INVLINES (LREF)
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

USE energy;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVOICE') AND name = 'IX_MIG_INV_ABYS_AGR'
)
CREATE NONCLUSTERED INDEX IX_MIG_INV_ABYS_AGR
    ON dbo.LS_005_01_INVOICE (ABYS_AGREEMENT_ID)
    INCLUDE (LREF, ABYS_ID, PAYABLETOTAL, TLTOTAL, TAX, GRANDTOTAL, IOCODE, OWNERREF)
    WHERE ABYS_ID IS NOT NULL
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVOICE') AND name = 'IX_MIG_INV_ABYS_ID'
)
CREATE NONCLUSTERED INDEX IX_MIG_INV_ABYS_ID
    ON dbo.LS_005_01_INVOICE (ABYS_ID)
    INCLUDE (LREF, ABYS_AGREEMENT_ID, OWNERREF)
    WHERE ABYS_ID IS NOT NULL
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS') AND name = 'IX_MIG_PT_INVREF_IO'
)
CREATE NONCLUSTERED INDEX IX_MIG_PT_INVREF_IO
    ON dbo.LS_005_01_PAYTRANS (INVOICEREF, IOCODE)
    INCLUDE (LREF, ABYS_ID, PAYABLETOTAL, PAYTYPE, TRANSTYPE, LINETYPE, PAID, ABYS_AGREEMENT_ID)
    WHERE ABYS_ID IS NOT NULL
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF OBJECT_ID('dbo.LS_005_01_INVLINES', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVLINES') AND name = 'IX_MIG_IL_ABYS_AGR'
)
CREATE NONCLUSTERED INDEX IX_MIG_IL_ABYS_AGR
    ON dbo.LS_005_01_INVLINES (ABYS_AGREEMENT_ID)
    INCLUDE (LREF, INVOICEREF, GRANDTOTAL, ABYS_ID)
    WHERE ABYS_ID IS NOT NULL
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

IF OBJECT_ID('dbo.LS_005_01_INVLINES', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVLINES') AND name = 'IX_MIG_IL_INVREF'
)
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_005_01_INVLINES') AND name = 'IX_LS005_INVLINES_INVOICEREF'
)
CREATE NONCLUSTERED INDEX IX_MIG_IL_INVREF
    ON dbo.LS_005_01_INVLINES (INVOICEREF)
    INCLUDE (LREF, ABYS_ID, GRANDTOTAL)
    WHERE INVOICEREF IS NOT NULL
    WITH (MAXDOP = 8, ONLINE = OFF, SORT_IN_TEMPDB = ON);
GO

PRINT 'adim3_verify_indexes OK';
GO
