/* ============================================================
   FILE : adim_layer4plus_continue.sql
   581/582 SONRASI — sirayla: 575(+576) → 611 → 613 → 590 → 597
   Her katman basinda/sonunda RAISERROR WITH NOWAIT (anlik log)
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @DEBUG BIT = 1;
DECLARE @BATCH INT = 100000;
DECLARE @Msg NVARCHAR(400);
DECLARE @tAll DATETIME2(3) = SYSDATETIME();
DECLARE @t0 DATETIME2(3);

SET @Msg = N'===== LAYER4+ CONTINUE START ' + CONVERT(VARCHAR(30), @tAll, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 575 DEBT ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== LAYER 4/8 DEBT PAYTRANS (575) START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

EXEC energy.dbo.SP_MIGRATE_LS005_DEBT_PAYTRANS
    @AGR_ID = NULL, @RESUME = 0, @HARD_RESET = 1,
    @BATCH_SIZE = @BATCH, @DEBUG = @DEBUG;

IF OBJECT_ID('energy.dbo.SP_MIG_DEBT_PAYTRANS_POST_INDEXES', 'P') IS NOT NULL
BEGIN
    SET @Msg = N'===== LAYER 4b 576 DEBT POST INDEXES =====';
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
    EXEC energy.dbo.SP_MIG_DEBT_PAYTRANS_POST_INDEXES @DEBUG = @DEBUG;
END

SET @Msg = N'===== LAYER 4 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 611 INSTALLMENT ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== LAYER 5/8 INSTALLMENT PLAN (611) START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIGRATE_LS005_INSTALLMENT_PLAN', 'P') IS NOT NULL
    EXEC energy.dbo.SP_MIGRATE_LS005_INSTALLMENT_PLAN
        @AGR_ID = NULL, @HARD_RESET = 1, @RESUME = 0,
        @BATCH_SIZE = @BATCH, @DEBUG = @DEBUG;

SET @Msg = N'===== LAYER 5 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 613 normalize+split ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== LAYER 6/8 INSTALLMENT NORMALIZE+SPLIT (613) START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR', 'P') IS NOT NULL
BEGIN
    DECLARE @Agr TABLE (ORD INT IDENTITY(1,1) PRIMARY KEY, AGR_ID BIGINT NOT NULL);
    INSERT INTO @Agr (AGR_ID)
    SELECT DISTINCT pl.ABYS_AGREEMENT_ID
    FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK)
    WHERE pl.ABYS_ID IS NOT NULL AND pl.ABYS_AGREEMENT_ID IS NOT NULL
    ORDER BY pl.ABYS_AGREEMENT_ID;

    DECLARE @i INT = 1, @n INT, @AGR_ID BIGINT;
    SELECT @n = COUNT(*) FROM @Agr;
    SET @Msg = N'Plan AGR_CNT=' + CAST(@n AS VARCHAR(20));
    RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

    WHILE @i <= @n
    BEGIN
        SELECT @AGR_ID = AGR_ID FROM @Agr WHERE ORD = @i;
        IF @i = 1 OR @i = @n OR @i % 500 = 0
        BEGIN
            SET @Msg = N'--- 613 AGR ' + CAST(@AGR_ID AS VARCHAR(20))
                     + N' (' + CAST(@i AS VARCHAR(10)) + N'/' + CAST(@n AS VARCHAR(10)) + N') ---';
            RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;
        END

        EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR
            @AGR_ID = @AGR_ID, @DEBUG = 0;

        IF OBJECT_ID('energy.dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR', 'P') IS NOT NULL
            EXEC energy.dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR
                @AGR_ID = @AGR_ID, @DEBUG = 0;

        SET @i += 1;
    END
END

SET @Msg = N'===== LAYER 6 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 590 EKSILTEN ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== LAYER 7/8 EKSILTEN (590) START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR', 'P') IS NOT NULL
   AND OBJECT_ID('izgazMGR.dbo.LS_OV_IADE_INVOICE', 'U') IS NOT NULL
    EXEC energy.dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR
        @AGR_ID = NULL, @CLEAN = 1, @DEBUG = @DEBUG;

SET @Msg = N'===== LAYER 7 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 597 TAHSILAT ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== LAYER 8/8 TAHSILAT (597) START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR', 'P') IS NOT NULL
   AND OBJECT_ID('izgazMGR.dbo.LS_OV_PAY_PT', 'U') IS NOT NULL
    EXEC energy.dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR
        @AGR_ID = NULL, @CLEAN = 1, @DEBUG = @DEBUG;

SET @Msg = N'===== LAYER 8 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SET @Msg = N'===== LAYER4+ ALL DONE total_sec='
         + CAST(DATEDIFF(SECOND, @tAll, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT 'INV' K, COUNT_BIG(*) N FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
UNION ALL
SELECT 'IL', COUNT_BIG(*) FROM dbo.LS_005_01_INVLINES WITH (NOLOCK) WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT 'DEBT', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
 WHERE ISNULL(IOCODE,0)=0 AND ABYS_ID IS NOT NULL
UNION ALL
SELECT 'PAY', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
 WHERE ISNULL(IOCODE,0)=1
UNION ALL
SELECT 'INST', COUNT_BIG(*) FROM dbo.LS_005_01_INSTALLMENT_PLAN WITH (NOLOCK)
 WHERE ABYS_ID IS NOT NULL;
GO
