USE energy;
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
RAISERROR('571 v10 RESUME ARITH batch=100000', 0, 1) WITH NOWAIT;
EXEC energy.dbo.SP_MIGRATE_LS005_INVOICE
  @AGR_ID = NULL,
  @RESUME = 1,
  @HARD_RESET = 0,
  @BATCH_SIZE = 100000,
  @DEBUG = 1;
GO
