-- =============================================================================
-- oracleCTAS3007 / 32 — DEBT_PAID_UPD + LASTPAIDDATE (hotfix CTAS)
-- Onkosul: O30 (LS_OV_PAY_PT + LS_INVOICE)
-- Amac:
--   energy.LS_005_01_INVOICE: tahsilat var ama CLOSED=0 / LASTPAIDDATE NULL
--   → Oracle overlay yeniden uretir; dump + 597 WIRE uygular
--
-- Cikti:
--   MIGRATION.LS_OV_DEBT_PAID_UPD   (PAID_AMT, CLOSED, LASTPAIDDATE)
--   MIGRATION.LS_OV_INV_PAY_GAP    (diag: odeme var, CLOSED=0 veya LPD null)
--
-- Energy: prodREADY_ENERGY/21_597_WIRE.sql (DEBT_PAID CLOSED + LASTPAIDDATE)
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

-- TERMINAL DUMP final: LS_OV_INV_PAY_GAP INDEX/STATS yok (LS_OV_DEBT_PAID_UPD zincir IX kalir).

ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_PAY_PT';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20032, 'MIGRATION.LS_OV_PAY_PT yok — once O30 calistir.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_INVOICE';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20033, 'MIGRATION.LS_INVOICE yok.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O32', 'debt_paid_lastpaid', 'START', NULL, 'CLOSED+LASTPAIDDATE');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- =============================================================================
-- 1) DEBT_PAID_UPD yeniden (LASTPAIDDATE dahil)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_DEBT_PAID_UPD PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_DEBT_PAID_UPD NOLOGGING AS
SELECT
    x.MAIN_LREF,
    CAST(x.PAID_AMT AS NUMBER(15,3))                             AS PAID_AMT,
    x.ABYS_AGREEMENT_ID,
    CASE
      WHEN NVL(x.PAYABLE_AMT, 0) <= 0.01 THEN 1
      WHEN x.PAID_AMT >= x.PAYABLE_AMT - 0.01 THEN 1
      ELSE 0
    END                                                          AS CLOSED,
    x.LASTPAIDDATE
FROM (
    SELECT
        p.CROSSREF_MAIN_LREF                                     AS MAIN_LREF,
        CAST(ROUND(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.PAYABLETOTAL ELSE 0 END), 2) AS NUMBER(15,3)) AS PAID_AMT,
        MAX(p.ABYS_AGREEMENT_ID)                                 AS ABYS_AGREEMENT_ID,
        CAST(ROUND(NVL(MAX(inv.PAYABLETOTAL), 0), 2) AS NUMBER(15,3)) AS PAYABLE_AMT,
        MAX(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.DATE_ END)   AS LASTPAIDDATE
    FROM MIGRATION.LS_OV_PAY_PT p
    LEFT JOIN MIGRATION.LS_INVOICE inv ON inv.LREF = p.CROSSREF_MAIN_LREF
    WHERE p.CROSSREF_MAIN_LREF IS NOT NULL
    GROUP BY p.CROSSREF_MAIN_LREF

    UNION ALL

    /* PAYABLETOTAL=0 > CLOSED=1 (odeme olmasa da) */
    SELECT
        inv.LREF                                                 AS MAIN_LREF,
        CAST(0 AS NUMBER(15,3))                                  AS PAID_AMT,
        inv.ABYS_AGREEMENT_ID                                    AS ABYS_AGREEMENT_ID,
        CAST(ROUND(NVL(inv.PAYABLETOTAL, 0), 2) AS NUMBER(15,3)) AS PAYABLE_AMT,
        CAST(NULL AS DATE)                                       AS LASTPAIDDATE
    FROM MIGRATION.LS_INVOICE inv
    WHERE ABS(NVL(inv.PAYABLETOTAL, 0)) <= 0.01
      AND NVL(inv.IOCODE, 0) = 0
      AND NOT EXISTS (
            SELECT 1 FROM MIGRATION.LS_OV_PAY_PT p
             WHERE p.CROSSREF_MAIN_LREF = inv.LREF
          )
) x;

CREATE UNIQUE INDEX MIGRATION.IX_OV_DEBT_PAID ON MIGRATION.LS_OV_DEBT_PAID_UPD (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_DEBT_PAID NOPARALLEL;
/
CREATE INDEX MIGRATION.IX_OV_DEBT_PAID_AGR ON MIGRATION.LS_OV_DEBT_PAID_UPD (ABYS_AGREEMENT_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_DEBT_PAID_AGR NOPARALLEL;
/
BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_OV_DEBT_PAID_UPD'); END;
/

-- =============================================================================
-- 2) GAP diag — odeme var, kapanmamis veya LASTPAIDDATE yok (energy hedef aday)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_INV_PAY_GAP PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_INV_PAY_GAP NOLOGGING AS
SELECT
    d.MAIN_LREF,
    d.ABYS_AGREEMENT_ID,
    d.PAID_AMT,
    CAST(ROUND(NVL(inv.PAYABLETOTAL, 0), 2) AS NUMBER(15,3))     AS PAYABLE_AMT,
    d.CLOSED,
    d.LASTPAIDDATE,
    CASE
      WHEN NVL(d.CLOSED, 0) = 0 AND d.PAID_AMT > 0.01
           AND d.PAID_AMT < NVL(inv.PAYABLETOTAL, 0) - 0.01
        THEN CAST('PARTIAL_OK_NEED_LPD' AS VARCHAR2(30))
      WHEN NVL(d.CLOSED, 0) = 1 AND d.LASTPAIDDATE IS NULL AND d.PAID_AMT > 0.01
        THEN CAST('FULL_CLOSED_LPD_NULL' AS VARCHAR2(30))
      WHEN NVL(d.CLOSED, 0) = 1 AND d.LASTPAIDDATE IS NOT NULL
        THEN CAST('FULL_READY' AS VARCHAR2(30))
      WHEN NVL(d.CLOSED, 0) = 0 AND d.PAID_AMT >= NVL(inv.PAYABLETOTAL, 0) - 0.01
        THEN CAST('SHOULD_CLOSE' AS VARCHAR2(30))
      ELSE CAST('OTHER' AS VARCHAR2(30))
    END                                                          AS GAP_KIND,
    CAST('INV_PAY_GAP' AS VARCHAR2(14))                          AS OV_KIND
FROM MIGRATION.LS_OV_DEBT_PAID_UPD d
LEFT JOIN MIGRATION.LS_INVOICE inv ON inv.LREF = d.MAIN_LREF
WHERE d.PAID_AMT > 0.01
  AND (
        NVL(d.CLOSED, 0) = 0
     OR d.LASTPAIDDATE IS NULL
  );

/
/

PROMPT ========== O32 DEBT_PAID + LASTPAIDDATE ==========
SELECT 'DEBT_PAID' K, COUNT(*) N FROM MIGRATION.LS_OV_DEBT_PAID_UPD
UNION ALL SELECT 'DEBT_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE CLOSED = 1
UNION ALL SELECT 'DEBT_LPD', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE LASTPAIDDATE IS NOT NULL
UNION ALL SELECT 'GAP_ALL', COUNT(*) FROM MIGRATION.LS_OV_INV_PAY_GAP
UNION ALL SELECT 'GAP_' || GAP_KIND, COUNT(*) FROM MIGRATION.LS_OV_INV_PAY_GAP GROUP BY GAP_KIND;

DECLARE
  n_paid NUMBER;
  n_lpd  NUMBER;
  n_gap  NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_paid FROM MIGRATION.LS_OV_DEBT_PAID_UPD;
  SELECT COUNT(*) INTO n_lpd  FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE LASTPAIDDATE IS NOT NULL;
  SELECT COUNT(*) INTO n_gap  FROM MIGRATION.LS_OV_INV_PAY_GAP;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O32', 'debt_paid_lastpaid', 'OK', n_paid,
      'lpd=' || n_lpd || ' gap=' || n_gap);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  DBMS_OUTPUT.PUT_LINE('========== O32 OK | debt_paid=' || n_paid
    || ' lastpaid=' || n_lpd || ' gap=' || n_gap || ' ==========');
END;
/
