/* Layer 2-3: 572 post indexes → 581 INVLINES (timed) */
USE energy;
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

DECLARE @Msg NVARCHAR(400);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();

SET @Msg = N'===== LAYER 2/8 INVOICE POST INDEXES (572) START ' + CONVERT(VARCHAR(30), @t0, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

EXEC energy.dbo.SP_MIG_INVOICE_POST_INDEXES @DEBUG = 1;

SET @Msg = N'===== LAYER 2/8 DONE elapsed_sec='
         + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

DECLARE @t1 DATETIME2(3) = SYSDATETIME();
SET @Msg = N'===== LAYER 3/8 INVLINES (581) START ' + CONVERT(VARCHAR(30), @t1, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

EXEC energy.dbo.SP_MIGRATE_LS005_INVLINES
    @RESUME     = 0,
    @HARD_RESET = 1,
    @BATCH_SIZE = 100000,
    @RANGE_MODE = 'KEYSET',
    @DEBUG      = 1;

SET @Msg = N'===== LAYER 3/8 DONE elapsed_sec='
         + CAST(DATEDIFF(SECOND, @t1, SYSDATETIME()) AS VARCHAR(20))
         + N' | total_sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20))
         + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT 'ENERGY_INV' K, COUNT_BIG(*) N FROM energy.dbo.LS_005_01_INVOICE WITH (NOLOCK)
UNION ALL
SELECT 'ENERGY_IL', COUNT_BIG(*) FROM energy.dbo.LS_005_01_INVLINES WITH (NOLOCK)
WHERE ABYS_ID IS NOT NULL;
GO
