/* 575 DEBT + 576 post — INVLINES 582 ile paralel guvenli (kaynak=INVOICE) */
USE energy;
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

DECLARE @Msg NVARCHAR(400);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();

SET @Msg = N'===== 575 DEBT PAYTRANS START ' + CONVERT(VARCHAR(30), @t0, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

EXEC energy.dbo.SP_MIGRATE_LS005_DEBT_PAYTRANS
    @AGR_ID = NULL,
    @RESUME = 0,
    @HARD_RESET = 1,
    @BATCH_SIZE = 100000,
    @DEBUG = 1;

SET @Msg = N'===== 575 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

DECLARE @t1 DATETIME2(3) = SYSDATETIME();
SET @Msg = N'===== 576 DEBT POST INDEXES START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIG_DEBT_PAYTRANS_POST_INDEXES', 'P') IS NOT NULL
    EXEC energy.dbo.SP_MIG_DEBT_PAYTRANS_POST_INDEXES @DEBUG = 1;

SET @Msg = N'===== 576 DONE sec=' + CAST(DATEDIFF(SECOND, @t1, SYSDATETIME()) AS VARCHAR(20))
         + N' | total=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT 'DEBT_PT' K, COUNT_BIG(*) N
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE ISNULL(IOCODE, 0) = 0 AND ABYS_ID IS NOT NULL;
GO
