USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT OFF; -- deadlock retry icin
SET QUOTED_IDENTIFIER ON;

DECLARE @DEBUG BIT = 0;
DECLARE @Msg NVARCHAR(400);
DECLARE @tAll DATETIME2(3) = SYSDATETIME();
DECLARE @t0 DATETIME2(3) = SYSDATETIME();
DECLARE @i INT = 1, @n INT, @AGR_ID BIGINT;
DECLARE @try INT, @ok BIT;

SET @Msg = N'===== 613 SERIAL FAST START ' + CONVERT(VARCHAR(30), @tAll, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.LS_005_01_PAYTRANS') AND name='UX_LS005_PAYTRANS_DEBT_INVOICEREF')
    DROP INDEX UX_LS005_PAYTRANS_DEBT_INVOICEREF ON dbo.LS_005_01_PAYTRANS;

/* wire once */
IF OBJECT_ID('dbo.SP_MIG_INSTALLMENT_PLAN_WIRE_INVOICE','P') IS NOT NULL
    EXEC dbo.SP_MIG_INSTALLMENT_PLAN_WIRE_INVOICE @AGR_ID=NULL, @DEBUG=1;
SET @Msg = N'WIRE DONE sec=' + CAST(DATEDIFF(SECOND,@t0,SYSDATETIME()) AS VARCHAR(20));
RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

IF OBJECT_ID('tempdb..#Agr') IS NOT NULL DROP TABLE #Agr;
CREATE TABLE #Agr (ORD INT NOT NULL PRIMARY KEY, AGR_ID BIGINT NOT NULL);
INSERT INTO #Agr (ORD, AGR_ID)
SELECT ROW_NUMBER() OVER (ORDER BY AGR_ID), AGR_ID
FROM (
  SELECT DISTINCT ABYS_AGREEMENT_ID AS AGR_ID
  FROM dbo.LS_005_01_INSTALLMENT_PLAN WITH (NOLOCK)
  WHERE ABYS_ID IS NOT NULL AND ABYS_AGREEMENT_ID IS NOT NULL
) d;
SELECT @n = COUNT(*) FROM #Agr;
SET @Msg = N'AGR_CNT=' + CAST(@n AS VARCHAR(20));
RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

SET @t0 = SYSDATETIME();
WHILE @i <= @n
BEGIN
  SELECT @AGR_ID = AGR_ID FROM #Agr WHERE ORD = @i;
  SET @ok = 0; SET @try = 0;
  WHILE @try < 3 AND @ok = 0
  BEGIN
    SET @try += 1;
    BEGIN TRY
      EXEC dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=@AGR_ID, @DEBUG=0;
      EXEC dbo.SP_MIG_INSTALLMENT_SPLIT_DEBT_BY_AGR @AGR_ID=@AGR_ID, @DEBUG=0;
      SET @ok = 1;
    END TRY
    BEGIN CATCH
      IF ERROR_NUMBER() = 1205
      BEGIN
        SET @Msg = N'DEADLOCK retry ' + CAST(@try AS VARCHAR(5)) + N' AGR=' + CAST(@AGR_ID AS VARCHAR(20));
        RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
        WAITFOR DELAY '00:00:00.200';
      END
      ELSE
      BEGIN
        SET @Msg = N'ERR AGR=' + CAST(@AGR_ID AS VARCHAR(20)) + N' ' + ERROR_MESSAGE();
        RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
        SET @ok = 1; -- skip
      END
    END CATCH
  END

  IF @i = 1 OR @i = @n OR @i % 500 = 0
  BEGIN
    SET @Msg = N'--- 613 ' + CAST(@i AS VARCHAR(10)) + N'/' + CAST(@n AS VARCHAR(10))
             + N' AGR=' + CAST(@AGR_ID AS VARCHAR(20))
             + N' sec=' + CAST(DATEDIFF(SECOND,@t0,SYSDATETIME()) AS VARCHAR(20))
             + N' rate_ms=' + CASE WHEN @i>1 THEN CAST((DATEDIFF(MILLISECOND,@t0,SYSDATETIME())/(@i*1.0)) AS VARCHAR(20)) ELSE '?' END;
    RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
  END
  SET @i += 1;
END

SET @Msg = N'===== 613 DONE sec=' + CAST(DATEDIFF(SECOND,@tAll,SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

SET @t0 = SYSDATETIME();
SET @Msg = N'===== 590 EKSILTEN START ====='; RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
IF OBJECT_ID('dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR','P') IS NOT NULL AND OBJECT_ID('izgazMGR.dbo.LS_OV_IADE_INVOICE','U') IS NOT NULL
  EXEC dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR @AGR_ID=NULL, @CLEAN=1, @DEBUG=1;
SET @Msg = N'===== 590 DONE sec=' + CAST(DATEDIFF(SECOND,@t0,SYSDATETIME()) AS VARCHAR(20)); RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

SET @t0 = SYSDATETIME();
SET @Msg = N'===== 597 TAHSILAT START ====='; RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
IF OBJECT_ID('dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR','P') IS NOT NULL AND OBJECT_ID('izgazMGR.dbo.LS_OV_PAY_PT','U') IS NOT NULL
  EXEC dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR @AGR_ID=NULL, @CLEAN=1, @DEBUG=1;
SET @Msg = N'===== 597 DONE sec=' + CAST(DATEDIFF(SECOND,@t0,SYSDATETIME()) AS VARCHAR(20)); RAISERROR('%s',0,1,@Msg) WITH NOWAIT;

SET @Msg = N'===== ALL DONE total_sec=' + CAST(DATEDIFF(SECOND,@tAll,SYSDATETIME()) AS VARCHAR(20)); RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
GO
