/* 581 INVLINES resume + 582 post indexes */
USE energy;
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

DECLARE @Msg NVARCHAR(400);
DECLARE @t0 DATETIME2(3) = SYSDATETIME();

SET @Msg = N'===== 581 INVLINES RESUME START ' + CONVERT(VARCHAR(30), @t0, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

EXEC energy.dbo.SP_MIGRATE_LS005_INVLINES
    @RESUME     = 1,
    @HARD_RESET = 0,
    @BATCH_SIZE = 100000,
    @RANGE_MODE = 'KEYSET',
    @DEBUG      = 1;

SET @Msg = N'===== 581 DONE elapsed_sec='
         + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

DECLARE @t1 DATETIME2(3) = SYSDATETIME();
SET @Msg = N'===== 582 INVLINES POST INDEXES START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIG_INVLINES_POST_INDEXES', 'P') IS NOT NULL
    EXEC energy.dbo.SP_MIG_INVLINES_POST_INDEXES @DEBUG = 1;

SET @Msg = N'===== 582 DONE elapsed_sec='
         + CAST(DATEDIFF(SECOND, @t1, SYSDATETIME()) AS VARCHAR(20))
         + N' | total_sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20))
         + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT 'ENERGY_IL' K, COUNT_BIG(*) N
FROM energy.dbo.LS_005_01_INVLINES WITH (NOLOCK)
WHERE ABYS_ID IS NOT NULL;
GO
