-- =============================================================================
-- prod2 / 27 — GATE eksilten (soft + hard 1:1 TAM↔IADE)
-- Onkosul: 20_ls_eksilten_overlay.sql
-- =============================================================================

SELECT KIND, COUNT(*) CNT
FROM MIGRATION.LS_OV_EKS_CLASS
GROUP BY KIND
ORDER BY 1;

SELECT
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_EKS_CLASS WHERE KIND='TAM' AND MAIN_LREF IS NOT NULL) TAM,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_INVOICE) IADE,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_MAIN_UPD) MAIN_UPD,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_INVLINES) IADE_IL,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_IADE_PAYTRANS) IADE_PT,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_KISMI_INVLINES) KISMI_IL,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_KISMI_HDR) KISMI_HDR,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_KISMI_PAYTRANS) KISMI_PT,
    (SELECT COUNT(*) FROM MIGRATION.LS_OV_EKS_SKIP) ASIM_SKIP
FROM DUAL;

DECLARE
  n_tam NUMBER; n_iade NUMBER; n_upd NUMBER; n_pt NUMBER;
  n_kh NUMBER; n_kpt NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_tam FROM MIGRATION.LS_OV_EKS_CLASS WHERE KIND='TAM' AND MAIN_LREF IS NOT NULL;
  SELECT COUNT(*) INTO n_iade FROM MIGRATION.LS_OV_IADE_INVOICE;
  SELECT COUNT(*) INTO n_upd FROM MIGRATION.LS_OV_MAIN_UPD;
  SELECT COUNT(*) INTO n_pt FROM MIGRATION.LS_OV_IADE_PAYTRANS;
  SELECT COUNT(*) INTO n_kh FROM MIGRATION.LS_OV_KISMI_HDR;
  SELECT COUNT(*) INTO n_kpt FROM MIGRATION.LS_OV_KISMI_PAYTRANS;
  IF n_tam <> n_iade THEN
    RAISE_APPLICATION_ERROR(-20027, 'GATE FAIL: TAM(' || n_tam || ') <> IADE(' || n_iade || ')');
  END IF;
  IF n_tam <> n_pt THEN
    RAISE_APPLICATION_ERROR(-20028, 'GATE FAIL: TAM(' || n_tam || ') <> IADE_PT(' || n_pt || ')');
  END IF;
  /* MAIN_UPD <= TAM (coklu TAM ayni MAIN → tek upd) */
  IF n_upd > n_tam THEN
    RAISE_APPLICATION_ERROR(-20029, 'GATE FAIL: MAIN_UPD(' || n_upd || ') > TAM(' || n_tam || ')');
  END IF;
  IF n_kh <> n_kpt THEN
    RAISE_APPLICATION_ERROR(-20030, 'GATE FAIL: KISMI_HDR(' || n_kh || ') <> KISMI_PT(' || n_kpt || ')');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ADIM4 EKSILTEN GATE OK tam=' || n_tam || ' main_upd=' || n_upd || ' kismi_pt=' || n_kpt);
END;
/

PROMPT ========== 27 GATE EKSILTEN OK ==========
/