-- =============================================================================
-- prodREADY / 53 — LS_EKSILTEN (TAM only) + LS_PARTIAL_EKSILTEN (KISMI)
-- Onkosul: O20 LS_OV_EKS_CLASS
-- ASIM buraya girmez → LS_OV_EKS_SKIP
-- Dogal ID; MAP/SRC_KEY yok
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_EKS_CLASS';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20053, 'MIGRATION.LS_OV_EKS_CLASS yok — once O20.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O53', 'ls_eksilten_family', 'START', NULL, 'TAM+KISMI from EKS_CLASS');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_EKSILTEN PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_EKSILTEN NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(EC.EKS_ACTION_ID AS NUMBER(12))                         AS EKS_ACTION_ID,
    CAST(EC.ACCOUNT_ID AS NUMBER(12))                            AS FATURAID,
    CAST(EC.AGREEMENT_ID AS NUMBER(12))                          AS SOZLESME,
    CAST(EC.KIND AS VARCHAR2(10))                                AS KIND,
    CAST(EC.EKS_AMT AS NUMBER(15,3))                             AS EKS_AMT,
    CAST(EC.TAH_AMT AS NUMBER(15,3))                             AS TAH_AMT,
    CAST(EC.MAIN_LREF AS NUMBER(12))                             AS MAIN_LREF,
    CAST(EC.MAIN_ACTION_ID AS NUMBER(12))                        AS MAIN_ACTION_ID,
    EC.EKS_DATE,
    CAST(EC.EKS_USER_ID AS NUMBER(12))                           AS EKS_USER_ID,
    CAST(EC.MAIN_PAYABLETOTAL AS NUMBER(15,3))                   AS MAIN_PAYABLETOTAL,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_OV_EKS_CLASS EC
WHERE EC.KIND = 'TAM';

CREATE UNIQUE INDEX MIGRATION.IX_LS_EKS_ACT ON MIGRATION.LS_EKSILTEN (EKS_ACTION_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_EKS_AGR ON MIGRATION.LS_EKSILTEN (SOZLESME) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_EKS_MAIN ON MIGRATION.LS_EKSILTEN (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_EKS_ACT NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_EKS_AGR NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_EKS_MAIN NOPARALLEL;
ALTER TABLE MIGRATION.LS_EKSILTEN NOPARALLEL LOGGING;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_PARTIAL_EKSILTEN PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_PARTIAL_EKSILTEN NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(EC.EKS_ACTION_ID AS NUMBER(12))                         AS EKS_ACTION_ID,
    CAST(EC.ACCOUNT_ID AS NUMBER(12))                            AS FATURAID,
    CAST(EC.AGREEMENT_ID AS NUMBER(12))                          AS SOZLESME,
    CAST(EC.KIND AS VARCHAR2(10))                                AS KIND,
    CAST(EC.EKS_AMT AS NUMBER(15,3))                             AS EKS_AMT,
    CAST(EC.TAH_AMT AS NUMBER(15,3))                             AS TAH_AMT,
    CAST(EC.MAIN_LREF AS NUMBER(12))                             AS MAIN_LREF,
    CAST(EC.MAIN_ACTION_ID AS NUMBER(12))                        AS MAIN_ACTION_ID,
    EC.EKS_DATE,
    CAST(EC.EKS_USER_ID AS NUMBER(12))                           AS EKS_USER_ID,
    CAST(EC.MAIN_PAYABLETOTAL AS NUMBER(15,3))                   AS MAIN_PAYABLETOTAL,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_OV_EKS_CLASS EC
WHERE EC.KIND = 'KISMI';

CREATE UNIQUE INDEX MIGRATION.IX_LS_PEKS_ACT ON MIGRATION.LS_PARTIAL_EKSILTEN (EKS_ACTION_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_PEKS_AGR ON MIGRATION.LS_PARTIAL_EKSILTEN (SOZLESME) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_PEKS_MAIN ON MIGRATION.LS_PARTIAL_EKSILTEN (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_PEKS_ACT NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_PEKS_AGR NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_PEKS_MAIN NOPARALLEL;
ALTER TABLE MIGRATION.LS_PARTIAL_EKSILTEN NOPARALLEL LOGGING;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_EKSILTEN', degree => 40);
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_PARTIAL_EKSILTEN', degree => 40);
END;
/

DECLARE
  n_t NUMBER; n_k NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_t FROM MIGRATION.LS_EKSILTEN;
  SELECT COUNT(*) INTO n_k FROM MIGRATION.LS_PARTIAL_EKSILTEN;
  MIGRATION.P_MIG_CTAS_LOG('O53', 'ls_eksilten_family', 'OK', n_t + n_k,
    'TAM=' || n_t || ' KISMI=' || n_k);
  DBMS_OUTPUT.PUT_LINE('========== O53 EKSILTEN OK | TAM=' || n_t || ' KISMI=' || n_k || ' ==========');
END;
/
