-- =============================================================================
-- diag_o11_precision — ORA-01438 hangi CAST? (O11 oncesi / hata sonrasi)
-- sqlplus @diag_o11_precision.sql
-- Beklenen: tum BAD_* = 0. >0 olan kolon fail nedeni.
-- =============================================================================

SET PAGESIZE 200
SET LINESIZE 200
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========== NUMBER(1) flag adaylari (ABS>9 veya >1 digit) ==========
SELECT
  SUM(CASE WHEN acc.IS_E_BILL IS NOT NULL AND ABS(acc.IS_E_BILL) > 9 THEN 1 ELSE 0 END) AS BAD_IS_E_BILL,
  SUM(CASE WHEN acc.IS_FPS IS NOT NULL AND ABS(acc.IS_FPS) > 9 THEN 1 ELSE 0 END) AS BAD_IS_FPS,
  SUM(CASE WHEN acc.DO_DISCHARGE IS NOT NULL AND ABS(acc.DO_DISCHARGE) > 9 THEN 1 ELSE 0 END) AS BAD_DO_DISCHARGE,
  MAX(acc.IS_E_BILL) AS MAX_IS_E_BILL,
  MAX(acc.IS_FPS) AS MAX_IS_FPS,
  MAX(acc.DO_DISCHARGE) AS MAX_DO_DISCHARGE
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;

PROMPT ========== NUMBER(12) ID — 12 haneyi asan ==========
SELECT
  SUM(CASE WHEN acc.ID IS NOT NULL AND ABS(acc.ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_ACCOUNT_ID,
  SUM(CASE WHEN acc.REGISTER_ID IS NOT NULL AND ABS(acc.REGISTER_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_REGISTER,
  SUM(CASE WHEN acc.AGREEMENT_ID IS NOT NULL AND ABS(acc.AGREEMENT_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_AGR,
  SUM(CASE WHEN acc.INSTALLATION_ID IS NOT NULL AND ABS(acc.INSTALLATION_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_INST,
  SUM(CASE WHEN acc.METER_ID IS NOT NULL AND ABS(acc.METER_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_METER,
  SUM(CASE WHEN acc.AREA_ID IS NOT NULL AND ABS(acc.AREA_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_AREA,
  SUM(CASE WHEN acc.PROJECT_ID IS NOT NULL AND ABS(acc.PROJECT_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_PROJECT,
  SUM(CASE WHEN aa.BILL_ORDER_NUMBER IS NOT NULL AND ABS(aa.BILL_ORDER_NUMBER) >= 1E12 THEN 1 ELSE 0 END) AS BAD_BILL_ORD,
  MAX(acc.INSTALLATION_ID) AS MAX_INST,
  MAX(acc.REGISTER_ID) AS MAX_REG,
  MAX(aa.BILL_ORDER_NUMBER) AS MAX_BILL_ORD
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;

PROMPT ========== NUMBER(10) — 10 haneyi asan ==========
SELECT
  SUM(CASE WHEN aa.BILL_PRINT_NUMBER IS NOT NULL AND ABS(aa.BILL_PRINT_NUMBER) >= 1E10 THEN 1 ELSE 0 END) AS BAD_PRINT,
  SUM(CASE WHEN aa.VERSION IS NOT NULL AND ABS(aa.VERSION) >= 1E10 THEN 1 ELSE 0 END) AS BAD_VERSION,
  SUM(CASE WHEN aa.ARCHIVE_SEND_STATUS IS NOT NULL AND ABS(aa.ARCHIVE_SEND_STATUS) >= 1E10 THEN 1 ELSE 0 END) AS BAD_ARCH_SEND,
  SUM(CASE WHEN aa.ARCHIVE_MAIL_SEND_STATUS IS NOT NULL AND ABS(aa.ARCHIVE_MAIL_SEND_STATUS) >= 1E10 THEN 1 ELSE 0 END) AS BAD_ARCH_MAIL,
  SUM(CASE WHEN acc.PERIOD IS NOT NULL AND ABS(acc.PERIOD) >= 1E10 THEN 1 ELSE 0 END) AS BAD_PERIOD,
  SUM(CASE WHEN aa.CREATED_USER_ID IS NOT NULL AND ABS(aa.CREATED_USER_ID + 10000) >= 1E10 THEN 1 ELSE 0 END) AS BAD_ADDUSER,
  SUM(CASE WHEN aa.UPDATED_USER_ID IS NOT NULL AND ABS(aa.UPDATED_USER_ID + 10000) >= 1E10 THEN 1 ELSE 0 END) AS BAD_UPDUSER,
  MAX(aa.BILL_PRINT_NUMBER) AS MAX_PRINT,
  MAX(acc.PERIOD) AS MAX_PERIOD,
  MAX(aa.CREATED_USER_ID) AS MAX_CREATE_USER
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;

PROMPT ========== NUMBER(18,6) tuketim — integer hane >12 ==========
SELECT
  SUM(CASE WHEN aa.CONSUMPTION IS NOT NULL AND ABS(TRUNC(aa.CONSUMPTION)) >= 1E12 THEN 1 ELSE 0 END) AS BAD_CONS,
  SUM(CASE WHEN aa.M3 IS NOT NULL AND ABS(TRUNC(aa.M3)) >= 1E12 THEN 1 ELSE 0 END) AS BAD_M3,
  SUM(CASE WHEN aa.KWH IS NOT NULL AND ABS(TRUNC(aa.KWH)) >= 1E12 THEN 1 ELSE 0 END) AS BAD_KWH,
  MAX(ABS(aa.CONSUMPTION)) AS MAX_ABS_CONS,
  MAX(ABS(aa.M3)) AS MAX_ABS_M3,
  MAX(ABS(aa.KWH)) AS MAX_ABS_KWH
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;

PROMPT ========== NUMBER(18,3) tutar (STG) — integer hane >15 ==========
SELECT
  SUM(CASE WHEN ABS(TRUNC(NVL(TOTAL_EXCL_TAX,0))) >= 1E15 THEN 1 ELSE 0 END) AS BAD_TLTOTAL,
  SUM(CASE WHEN ABS(TRUNC(NVL(PAYABLE_TOTAL,0))) >= 1E15 THEN 1 ELSE 0 END) AS BAD_PAYABLE,
  SUM(CASE WHEN ABS(TRUNC(NVL(TOTAL_TAX,0))) >= 1E15 THEN 1 ELSE 0 END) AS BAD_TAX,
  MAX(ABS(TOTAL_EXCL_TAX)) AS MAX_ABS_EXCL,
  MAX(ABS(PAYABLE_TOTAL)) AS MAX_ABS_PAY,
  MAX(ABS(HAS_DISCOUNT)) AS MAX_HAS_DISC
FROM MIGRATION.STG_INV_ACC_INC;

PROMPT ========== READING_ID NUMBER(12) ==========
SELECT
  SUM(CASE WHEN r.READING_ID IS NOT NULL AND ABS(r.READING_ID) >= 1E12 THEN 1 ELSE 0 END) AS BAD_READ,
  MAX(r.READING_ID) AS MAX_READ
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
LEFT JOIN (
  SELECT ACCOUNT_ID, MAX(ID) AS READING_ID
  FROM SMS.CS_READING
  GROUP BY ACCOUNT_ID
) r ON r.ACCOUNT_ID = acc.ID
WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;

PROMPT ========== Ornek: flag >1 (ilk 20) ==========
SELECT * FROM (
  SELECT aa.ID AS ACA_ID, acc.ID AS ACC_ID,
         acc.IS_E_BILL, acc.IS_FPS, acc.DO_DISCHARGE
  FROM SMS.CS_ACCOUNT_ACTION aa
  JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
  WHERE aa.ACTION_TYPE_ID IN (1, 3, 10, 41)
    AND NVL(acc.ACCRUE_TYPE_ID, -1) <> 14
    AND aa.ID BETWEEN 1 AND 2147483647
    AND (
      NVL(ABS(acc.IS_E_BILL),0) > 1
      OR NVL(ABS(acc.IS_FPS),0) > 1
      OR NVL(ABS(acc.DO_DISCHARGE),0) > 1
    )
  ORDER BY aa.ID
) WHERE ROWNUM <= 20;

PROMPT ========== DIAG DONE — BAD_*>0 satiri fail kolonu ==========
/
