create table reading_information_202605 as  
  select 
--Tesisat Bilgileri
i.id INSTALLATION_ID,
i.READING_ORDER_NUMBER,
DECODE(i.STATUS,0,'????',1,'POTANSIYEL',2,'ILK PASIF',3,'PASIF',4,'ILK AKTIF', 5,'AKTIF',6,'IPTAL') INSTALLATION_STATUS,
DECODE(i.reading_status,0,'OKUNMADI',1,'OKUNMAK ICIN TERMINALDE',2,'ISEMRI ICIN TERMINALDE') INSTALLATION_READING_STATUS,


--Tesisat Saya� Bilgileri
m.id METER_ID,
m.meter_number ,
m.PRODUCTION_YEAR ,
m.STAMP_YEAR  METER_STAMP_YEAR,
m.CALIBRATION_DATE  METER_CALIBRATION_DATE,
m.card_module_id METER_CARD_MODULE,
m.corrector_module_id METER_CORR_MODULE,
mi.value METER_MARK,
mtp.code METER_TYPE, 

--Servis Kutusu Bilgileri
I.SERVICE_BOX_ID,
GSB.CODE,
GSB.GAS_OPENING_DATE SK_GAZ_ACMA_TARIH,
GSB.COLON_STARTUP_DATE SK_KOLON_DEVREYE_ALMA_TARIH,
GSB.HAS_GAS SK_GAZ_VAR_MI,
GSB.IS_ACTIVE SK_AKTIFMI,
GSB.INSTALLATION_DATE  SK_TESISAT_DEVREYE_ALMA_TARIHI,
DECODE(GSB.TYPE , 1,'SERVIS KUTUSU', 2,'MUSTERI REGULATORU (CR)', 3,'BOLGE REGULATORU (DR)') SK_TIP,
DECODE(GSB.STATUS , 1 , 'POTANSIYEL', 2,'BASVURU ALINDI', 3 , 'AKTIF', 4,'KOLON GAZ BO�ALTILDI', 5,'KOLON GAZ BO�ALTILACAK') SK_DURUM,
GSB.IS_VIRTUAL_BOX SANAL_KUTU_MU,
GSB.IS_REMOVE SK_SOKUK_MU,
GSB.IS_PSP SK_MAL_HIZMET,
GSB.IS_HOUSING_ESTATE SK_TOPLU_KONUT_MU,
GSB.IS_E_SUBSCRIPTION SK_ONLINE_ABONE_YAPLBLR_MI,
GSB.IS_CR SK_MUSTERI_REGULATORU_MU,
GSB.IS_BUILD_BY_CUSTOMER SK_MUSTERI_MI_YAPTIRDI,
 

--Proje Bilgileri 
XYZ.PRJ_NO, 
XYZ.PRJ_ONAY_TARIHI,
XYZ.PRJ_DURUM,
XYZ.PRJ_TOPLAM_ALAN,
XYZ.PRJ_KULLANIM_ALANI,
XYZ.PRJ_PRJE_TIPI,

--S�ralanan Katmana G�re Okuma 
bdst.read�ng_day LAYER_READING_DAY,
bdst.term�nal_code LAYER_TERMINAL_CODE,
--rp.read�ng_date,
--S�zle�me Bilgileri
L_AGR.AGR_ID LAST_AGREEMENT_ID , 
agr.id AGREEMENT_ID,
DECODE(agr.status,1,'AKTIF',2,'FESIH',3,'DEVIR AKTIF',0,'PASIF',' ') AGREEMENT_STATUS,
reg.FIRST_NAME ||' '|| reg.LAST_NAME FULL_NAME,
reg.IDENTITY_NUMBER,
reg.TAX_NUMBER,
reg.TAX_OFFICE,
reg.E_BILL_CUSTOMER_DATE,
reg.IS_COMMINICATION_PERMIT,
reg.IS_E_BILL_CUSTOMER,
reg.POOL_ID REGISTER_POOL_ID,
agr.POOL_ID AGREEMENT_POOL_ID,
agr.IS_TAX_DISCOUNT TAX_DISCOUNT,
agr.IS_VAT_DISCOUNT OTV_DISCOUNT,
agr.EXPIRY_DAY,
agr.CANCELLATION_DATE,
agr.STARTUP_DATE,
agr.STARTING_DATE,
agr.agreement_date,
ttpl.value AGREEMENT_TARIFF_TYPE,
ttplskb.value  AGREEMENT_SKB_TARIFF_TYPE,
--Son Okuma Bilgieri
L_READING.L_READING_ID LAST_READING_ID,
TRUNC(L_READING_INFO.CREATED_TIMESTAMP) L_READING_CREATED_TS,
L_READING_INFO.BILL_DATE,
 
L_READING_INFO.BILL_SERIAL ||'-'||L_READING_INFO.BILL_NUMBER L_READING_INFO_BILL_SERIAL,
L_READING_INFO.PERIOD,
L_READING_INFO.READING_DAY,
--L_READING_INFO.L_READING_ID,
L_READING_INFO.PRE_BILL_DATE L_READING_INFO_PRE_BILL_DATE,
L_READING_INFO.POOL_DEBT_COUNT  L_READING_INFO_POOL_DEBT_COUNT ,
L_READING_INFO.POOL_DEBT L_READING_INFO_POOL_DEBT,

L_READING_INFO.ACCOUNT_ID L_READING_ACCOUNT_ID,
L_READING_INFO.STATUS L_READING_INFO_STATUS_ID,
DECODE( L_READING_INFO.STATUS , 0 ,'OKUMA HAZIRLANDI-S�STEMDE',1  ,'OKUMA TERMINALE YUKLENDI',2 ,'ENDEKS B�LG�S� S�STEME AKTARILDI', 3 ,'TAHAKKUK S�STEME AKTARILDI',4 ,'EKS�K OKUMA (SAYA� H�� OKUNMADI)',5 ,'OKUMA BILGISI IPTAL (EKS�K HAZIRLANAB�L�R)',6 ,'HATALI TAHAKKUK',7 ,'D�ZELT�LM�� TAHAKKUK',8 ,'TAHAKKUK �NCES� ��LEM BULUNDU',9 ,'D�ZELT�LM�� OKUMA',10 ,'D�NEMSEL OKUNMA L�M�T�NE ULA�ILDI' ) L_READING_INFO_STATUS ,
L_READING_INFO.METER_STATUS_ID,
mspl.value   METER_STATUS,
L_READING_INFO.PRE_METER_STATUS_ID,  
mspl2.value    PRE_METER_STATUS,
sc.code  L_READING_INFO_TERMINAL,
stpl.value SUBSCRIBER_TYPE,
atpl.value ACTIVITY_TYPE,
agpl.value AGREEMENT_TYPE
from SMS.CS_INSTALLATION i
LEFT JOIN
(select 
agrz.INSTALLATION_ID , MAX(agrz.id) AGR_ID
from   SMS.CS_AGREEMENT agrz   group by  agrz.INSTALLATION_ID) L_AGR on (L_AGR.INSTALLATION_ID = i.id )
LEFT JOIN SMS.CS_AGREEMENT agr on (agr.id = L_AGR.AGR_ID  )
LEFT JOIN 
(select MAX(rr.ID) L_READING_ID,rr.INSTALLATION_ID FROM SMS.CS_READING  rr where rr.WORK_ID IS NULL
GROUP BY rr.INSTALLATION_ID) L_READING on (i.id = L_READING.INSTALLATION_ID )
LEFT join SMS.CS_subscriber_type_prm_lng stpl on (stpl.prm_id = agr.subscriber_Type_id and stpl.lang_id = 1 )
LEFT join SMS.CS_activity_type_Prm_lng atpl on (atpl.prm_id = agr.activity_type_id and atpl.lang_id = 1)
LEFT join SMS.CS_agreement_type_prm_lng agpl on (agpl.prm_id = agr.agreement_type_id and agpl.lang_id = 1)
left join SMS.CS_REGISTER reg on (agr.BENEFITED_REGISTER_ID = reg.id)
LEFT JOIN SMS.CS_READING L_READING_INFO on ( L_READING_INFO.ID =  L_READING.L_READING_ID )
left JOIN SMS.CS_subscriber_type_prm_lng stpl on (stpl.prm_id=agr.subscriber_type_id and stpl.lang_id=1) 
left JOIN SMS.CS_tariff_type_prm_lng ttpl on (ttpl.prm_id=agr.tariff_type_id and ttpl.lang_id=1) 
left JOIN SMS.CS_tariff_type_prm_lng ttplskb on (ttplskb.prm_id=agr.skb_tariff_type_id and ttplskb.lang_id=1)
left JOIN SMS.CS_meter_status_prm msp on (L_READING_INFO.meter_status_id=msp.id)
left JOIN SMS.CS_meter_status_prm_lng mspl on (msp.id=mspl.prm_id and mspl.lang_id=1)
left JOIN SMS.CS_meter_status_prm_lng mspl2 on (L_READING_INFO.pre_meter_status_id=mspl2.prm_id and mspl2.lang_id=1)
left JOIN SMS.CS_meter  m  on (m.id=i.meter_id)
left JOIN SMS.CS_meter_model_prm mmp on (m.meter_model_id=mmp.id)
left JOIN SMS.CS_meter_model_prm_lng mmpl on (mmpl.prm_id=mmp.id and mmpl.lang_id=1)
left JOIN SMS.CS_meter_mark_prm mi on (mi.id=mmp.meter_mark_id)
left JOIN SMS.CS_meter_type_prm mtp on (mtp.id=mmp.meter_type_id)
left JOIN GBAYER.READING_DATA_BDST_202505  BDST on (BDST.INSTALLATION_NUMBER = i.id)
--LEFT JOIN SMS.CS_READING_PERIOD rp on (BDST.READING_DAY = rp.READING_DAY )
LEFT JOIN SMS.OPR_SYNC_CLIENT  sc on (sc.id = L_READING_INFO.TERMINAL_SYNC_CLIENT_ID )
LEFT JOIN (select i.id IINS_ID, 
IP.PROJECT_YEAR ||'-'|| IP.PROJECT_NUMBER  PRJ_NO, 
�p.approval_date  PRJ_ONAY_TARIHI,
IP.PROJECT_STATUS PRJ_DURUM,
IP.TOTAL_AREA PRJ_TOPLAM_ALAN,
IPX.USED_AREA PRJ_KULLANIM_ALANI,
DECODE(IPX.TYPE ,1 , 'DAIRE ICI ILAVE',2 , 'DAIRE ICI TADILAT', 3,'MERKEZI ILAVE', 4 , 'MERKEZI TADILAT')PRJ_PRJE_TIPI
from SMS.CS_INSTALLATION  i
LEFT JOIN SMS.II_PROJECT_INSTALLATION IPX  ON (IPX.ID=SMS.F_GET_LAST_PRJ_INSTALLATION(I.ID))
LEFT JOIN SMS.II_PROJECT IP ON (IP.SERVICE_BOX_ID=I.SERVICE_BOX_ID)
   JOIN (SELECT MAX(APPROVAL_DATE),MAX(ID) ID
              FROM SMS.II_PROJECT IPR WHERE PROJECT_STATUS IN (888,999) GROUP BY SERVICE_BOX_ID) X ON (IP.ID=X.ID) )  XYZ on ( XYZ.IINS_ID = i.id)              
LEFT JOIN SMS.GIS_SERVICE_BOX GSB ON(GSB.ID = I.SERVICE_BOX_ID)