USE energy;
SET NOCOUNT ON;
DECLARE @Agr TABLE (ORD INT IDENTITY(1,1) PRIMARY KEY, AGR_ID BIGINT NOT NULL);
INSERT INTO @Agr (AGR_ID) VALUES (276503),(556305),(197168),(5727),(2221),(978259),(1192595);
DECLARE @i INT=1, @n INT, @AGR_ID BIGINT, @Msg NVARCHAR(200);
SELECT @n=COUNT(*) FROM @Agr;
WHILE @i<=@n
BEGIN
  SELECT @AGR_ID=AGR_ID FROM @Agr WHERE ORD=@i;
  SET @Msg=N'===== TAH AGR '+CAST(@AGR_ID AS VARCHAR(20))+N' =====';
  RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
  BEGIN TRY
    EXEC dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR @AGR_ID=@AGR_ID, @CLEAN=1, @DEBUG=1;
  END TRY
  BEGIN CATCH
    SET @Msg=N'FAIL AGR '+CAST(@AGR_ID AS VARCHAR(20))+N' '+ERROR_MESSAGE();
    RAISERROR('%s',0,1,@Msg) WITH NOWAIT;
  END CATCH
  SET @i+=1;
END

SELECT 'INV_20811205' k, inv.LREF, inv.CLOSED, inv.PAYABLETOTAL, inv.GRANDTOTAL
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK) WHERE inv.LREF=20811205;

SELECT 'DEBT_PT_208' k, pt.LREF, pt.INVOICEREF, pt.IOCODE, pt.PAYABLETOTAL, pt.PAID, pt.CANCELED
FROM energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
WHERE pt.INVOICEREF=20811205 AND ISNULL(pt.IOCODE,0)=0;

SELECT 'PAY_XREF_208' k, pt.LREF, pt.INVOICEREF, pt.CROSSREF, pt.PAYABLETOTAL, pt.PAYTYPE
FROM energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK)
WHERE pt.LREF=49747798 OR pt.INVOICEREF=49747798;

SELECT a.AGR_ID,
  (SELECT COUNT(*) FROM LS_005_01_INVOICE i WITH (NOLOCK) WHERE i.ABYS_AGREEMENT_ID=a.AGR_ID AND i.[TYPE]=101) TAH_INV,
  (SELECT COUNT(*) FROM LS_005_01_PAYTRANS p WITH (NOLOCK)
    WHERE p.ABYS_AGREEMENT_ID=a.AGR_ID AND ISNULL(p.IOCODE,0)=1 AND ISNULL(p.CANCELLATIONPAYMENT,0)=0) PAY_PT
FROM @Agr a ORDER BY a.ORD;
