SELECT COUNT(*) ALLOC_CNT FROM MIGRATION.LS_OV_PAY_ALLOC;
SELECT CASE WHEN COUNT(*)>0 THEN 'EXISTS' ELSE 'MISSING' END PAY_PT_STATUS FROM ALL_TABLES WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_PAY_PT';
