SET NOCOUNT ON;
DECLARE @Inv INT = 150404069;

PRINT '==== CS_INSTALLMENT 806966 ====';
SELECT CAST(ins.ID AS BIGINT) PLAN_ID, ins.AGREEMENT_ID,
  CASE WHEN ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL THEN 1 ELSE 0 END IS_CANCEL,
  ins.CANCEL_CAUSE_ID, ins.CANCELLATION_DATE, ins.CANCELLATION_USER_ID, ins.DUE_DATE,
  CONVERT(DECIMAL(18,2),ins.TOTAL_AMOUNT) TOTAL, CONVERT(DECIMAL(18,2),ins.MONTHLY_AMOUNT) MONTHLY
FROM izgazMGR.dbo.CS_INSTALLMENT ins WITH (NOLOCK) WHERE ins.ID=806966;

PRINT '==== CS_INSTALLMENT_PLAN ====';
SELECT ip.ORDER_NUMBER, CONVERT(DECIMAL(18,2),ip.AMOUNT) AMT,
       ip.PAYMENT_DATE, ip.EXPIRY_DATE, ip.RECEIPT_NUMBER
FROM izgazMGR.dbo.CS_INSTALLMENT_PLAN ip WITH (NOLOCK)
WHERE ip.INSTALLMENT_ID=806966 ORDER BY ip.ORDER_NUMBER;

PRINT '==== energy plan ====';
SELECT INSTALLMENT_COUNT, ISACTIVE, CONVERT(DECIMAL(18,2),TOTAL_AMOUNT) AMT,
       ABYS_PAYMENT_DATE, PAYTRANS_REF
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WITH (NOLOCK)
WHERE PLAN_ID=806966 ORDER BY INSTALLMENT_COUNT;

PRINT '==== payments CROSSREF ====';
SELECT LREF, IOCODE, INST_NR, CONVERT(DECIMAL(18,2),PAYABLETOTAL) P,
       CONVERT(DECIMAL(18,2),PAID) PAID, CANCELED, CROSSREF, EXPLAIN
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF=@Inv AND ISNULL(IOCODE,0)=1
ORDER BY LREF;

PRINT '==== payment pointing to taksit ====';
SELECT pay.LREF, CONVERT(DECIMAL(18,2),pay.PAYABLETOTAL) PAY_AMT, pay.CROSSREF, pay.INST_NR,
       d.INST_NR AS DEBT_INST, CONVERT(DECIMAL(18,2),d.PAYABLETOTAL) DEBT_AMT, CONVERT(DECIMAL(18,2),d.PAID) DEBT_PAID
FROM energy.dbo.LS_005_01_PAYTRANS pay WITH (NOLOCK)
LEFT JOIN energy.dbo.LS_005_01_PAYTRANS d ON d.LREF=pay.CROSSREF
WHERE pay.INVOICEREF=@Inv AND ISNULL(pay.IOCODE,0)=1;