SET NOCOUNT ON;
DECLARE @Inv INT = 150404089;

PRINT '==== INVOICE ====';
SELECT LREF, ABYS_AGREEMENT_ID, INSTALLMENT_PLAN_REF, ABYS_INSTALLMENT_ID,
       CONVERT(DECIMAL(18,2),PAYABLETOTAL) PAYABLE, CLOSED, CANCELED
FROM energy.dbo.LS_005_01_INVOICE WITH (NOLOCK) WHERE LREF=@Inv;

PRINT '==== PAYTRANS ====';
SELECT LREF, IOCODE, INST_NR, PAYTYPE,
       CONVERT(DECIMAL(18,2),PAYABLETOTAL) PAYABLE,
       CONVERT(DECIMAL(18,2),PAID) PAID, CANCELED, CROSSREF, EXPLAIN
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF=@Inv OR LREF=@Inv
ORDER BY IOCODE, INST_NR, LREF;

PRINT '==== PLAN ====';
SELECT pl.PLAN_ID, pl.INSTALLMENT_COUNT, pl.ISACTIVE,
       CONVERT(DECIMAL(18,2),pl.TOTAL_AMOUNT) AMT,
       pl.ABYS_PAYMENT_DATE, pl.PAYTRANS_REF,
       pl.ABYS_CANCEL_CAUSE_ID, pl.ABYS_CANCELLATION_DATE, pl.ABYS_CANCELLATION_USER_ID
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN pl WITH (NOLOCK)
WHERE pl.INVOICE_REF=@Inv
   OR pl.PLAN_ID=(SELECT ISNULL(ABYS_INSTALLMENT_ID,INSTALLMENT_PLAN_REF) FROM energy.dbo.LS_005_01_INVOICE WHERE LREF=@Inv)
ORDER BY INSTALLMENT_COUNT;

PRINT '==== CS_INSTALLMENT ====';
SELECT CAST(ins.ID AS BIGINT) PLAN_ID, ins.AGREEMENT_ID,
       CASE WHEN ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL THEN 1 ELSE 0 END IS_CANCEL,
       ins.CANCEL_CAUSE_ID, ins.CANCELLATION_DATE, ins.CANCELLATION_USER_ID, ins.DUE_DATE
FROM izgazMGR.dbo.CS_INSTALLMENT ins WITH (NOLOCK)
WHERE ins.ID = (SELECT ISNULL(ABYS_INSTALLMENT_ID,INSTALLMENT_PLAN_REF) FROM energy.dbo.LS_005_01_INVOICE WHERE LREF=@Inv)
   OR ins.ID IN (SELECT PLAN_ID FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WHERE INVOICE_REF=@Inv);

PRINT '==== CS_INSTALLMENT_PLAN payments ====';
SELECT ip.ORDER_NUMBER, CONVERT(DECIMAL(18,2),ip.AMOUNT) AMT, ip.PAYMENT_DATE, ip.EXPIRY_DATE
FROM izgazMGR.dbo.CS_INSTALLMENT_PLAN ip WITH (NOLOCK)
WHERE ip.INSTALLMENT_ID = (SELECT ISNULL(ABYS_INSTALLMENT_ID,INSTALLMENT_PLAN_REF) FROM energy.dbo.LS_005_01_INVOICE WHERE LREF=@Inv)
ORDER BY ip.ORDER_NUMBER;