SET NOCOUNT ON;
PRINT '==== normalize all remaining pilot AGRs ====';
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=5727, @DEBUG=1;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=556305, @DEBUG=1;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=197168, @DEBUG=1;

PRINT '==== 150404069 after ====';
SELECT LREF, INSTALLMENT_PLAN_REF, ABYS_INSTALLMENT_ID, CONVERT(DECIMAL(18,2),PAYABLETOTAL) PAYABLE
FROM energy.dbo.LS_005_01_INVOICE WITH (NOLOCK) WHERE LREF=150404069;

SELECT LREF, IOCODE, INST_NR, PAYTYPE,
       CONVERT(DECIMAL(18,2),PAYABLETOTAL) PAYABLE,
       CONVERT(DECIMAL(18,2),PAID) PAID, CANCELED, EXPLAIN
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF=150404069
ORDER BY IOCODE, INST_NR, LREF;

PRINT '==== plan PAYTRANS_REF ====';
SELECT INSTALLMENT_COUNT, ISACTIVE, PAYTRANS_REF
FROM energy.dbo.LS_005_01_INSTALLMENT_PLAN WITH (NOLOCK)
WHERE PLAN_ID=806966 ORDER BY 1;