SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

UPDATE pt
SET pt.PAID = CONVERT(FLOAT, CONVERT(DECIMAL(18,2), s.SUM_AMT))
FROM energy.dbo.LS_005_01_PAYTRANS pt
INNER JOIN (
    SELECT pay.CROSSREF AS MAIN_LREF,
           SUM(CONVERT(DECIMAL(18,2), ISNULL(pay.PAYABLETOTAL,0))) AS SUM_AMT
    FROM energy.dbo.LS_005_01_PAYTRANS pay WITH (NOLOCK)
    WHERE ISNULL(pay.IOCODE,0)=1
      AND ISNULL(pay.CANCELED,0)=0
      AND ISNULL(pay.CANCELLATIONPAYMENT,0)=0
      AND pay.CROSSREF IS NOT NULL
      AND pay.ABYS_AGREEMENT_ID IN (5727,276503,2221,978259,1192595,556305,197168)
    GROUP BY pay.CROSSREF
) s ON s.MAIN_LREF = pt.LREF
WHERE ISNULL(pt.IOCODE,0)=0
  AND ISNULL(pt.INST_NR,0)=0
  AND ISNULL(pt.CANCELED,0)=0
  AND CONVERT(DECIMAL(18,2), ISNULL(pt.PAID,0)) + 0.01 < s.SUM_AMT;

PRINT 'PAID patched rows=' + CAST(@@ROWCOUNT AS VARCHAR(20));

UPDATE inv
SET inv.CLOSED = CAST(1 AS BIT)
FROM energy.dbo.LS_005_01_INVOICE inv
INNER JOIN energy.dbo.LS_005_01_PAYTRANS pt
  ON pt.INVOICEREF = inv.LREF
 AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0
WHERE inv.ABYS_AGREEMENT_ID IN (5727,276503,2221,978259,1192595,556305,197168)
  AND ISNULL(inv.CLOSED,0)=0
  AND ISNULL(inv.CANCELED,0)=0
  AND CONVERT(DECIMAL(18,2),ISNULL(pt.PAID,0)) + 0.01
      >= CONVERT(DECIMAL(18,2),ISNULL(inv.PAYABLETOTAL,0));

PRINT 'CLOSED patched rows=' + CAST(@@ROWCOUNT AS VARCHAR(20));

SELECT inv.LREF, inv.CLOSED, CONVERT(DECIMAL(18,2),inv.PAYABLETOTAL) PAYABLE,
       pt.LREF AS MAIN_PT, CONVERT(DECIMAL(18,2),pt.PAID) PAID, pt.CANCELED AS MAIN_CANC,
       pay.LREF AS PAY_LREF, CONVERT(DECIMAL(18,2),pay.PAYABLETOTAL) PAY_AMT, pay.CROSSREF
FROM energy.dbo.LS_005_01_INVOICE inv
JOIN energy.dbo.LS_005_01_PAYTRANS pt
  ON pt.INVOICEREF=inv.LREF AND ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0
LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pay
  ON pay.CROSSREF=pt.LREF AND ISNULL(pay.IOCODE,0)=1 AND ISNULL(pay.CANCELED,0)=0
WHERE inv.LREF=150404069;