SELECT ip.ID, ip.INSTALLMENT_ID, ip.ORDER_NUMBER, ip.AMOUNT, ip.DUE_DATE, ip.PAYMENT_DATE,
       ins.AGREEMENT_ID, ins.ID INS_ID
FROM SMS.CS_INSTALLMENT_PLAN ip
JOIN SMS.CS_INSTALLMENT ins ON ins.ID = ip.INSTALLMENT_ID
WHERE ip.INSTALLMENT_ID = 808493
ORDER BY ip.ORDER_NUMBER;
