SELECT a.ID, a.AGREEMENT_ID, a.ACCRUE_TYPE_ID FROM SMS.CS_ACCOUNT a WHERE a.ID = 20811205;
SELECT LREF, TYPE, IOCODE, CLOSED, CANCELED, PAYABLETOTAL, ABYS_ACCOUNT_ID, ABYS_AGREEMENT_ID
FROM MIGRATION.LS_INVOICE WHERE LREF = 20811205 OR ABYS_ACCOUNT_ID = 20811205;
