SET NOCOUNT ON;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=2221, @DEBUG=1;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=978259, @DEBUG=1;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=1192595, @DEBUG=1;
EXEC energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR @AGR_ID=276503, @DEBUG=1;

PRINT '==== POST GATE ====';
;WITH inv AS (
  SELECT inv.LREF, inv.ABYS_AGREEMENT_ID AS AGR_ID,
         inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID
  FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
  WHERE inv.ABYS_AGREEMENT_ID IN (2221,978259,1192595,276503)
    AND ISNULL(inv.IOCODE,0)=0
    AND ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF) IS NOT NULL
), g AS (
  SELECT
    CASE
      WHEN EXISTS (
        SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins
        WHERE ins.ID = ISNULL(i.ABYS_INSTALLMENT_ID, i.INSTALLMENT_PLAN_REF)
          AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
      ) THEN
        CASE
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) > 0 THEN N'FAIL_TAKSIT_STILL_ACTIVE'
          WHEN i.INSTALLMENT_PLAN_REF IS NOT NULL THEN N'FAIL_REF_NOT_NULL'
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) < 1 THEN N'FAIL_NO_MAIN'
          ELSE N'OK_CANCEL'
        END
      ELSE
        CASE
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_SPLIT'
          WHEN SUM(CASE WHEN ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND ISNULL(pt.CANCELED,0)=0 THEN 1 ELSE 0 END) >= 1 THEN N'OK_MAIN_ONLY'
          ELSE N'WARN_NO_DEBT_PT'
        END
    END AS GATE
  FROM inv i
  LEFT JOIN energy.dbo.LS_005_01_PAYTRANS pt WITH (NOLOCK) ON pt.INVOICEREF = i.LREF
  GROUP BY i.AGR_ID, i.LREF, i.INSTALLMENT_PLAN_REF, i.ABYS_INSTALLMENT_ID
)
SELECT GATE, COUNT(*) AS CNT FROM g GROUP BY GATE ORDER BY CNT DESC;

PRINT '==== 276503 REF ====';
SELECT LREF, INSTALLMENT_PLAN_REF, ABYS_INSTALLMENT_ID
FROM energy.dbo.LS_005_01_INVOICE WITH (NOLOCK)
WHERE ABYS_AGREEMENT_ID=276503 AND LREF IN (19701495,19733171,20133086,20257454,20360857,20622609);