SET NOCOUNT ON;
PRINT '==== DRY: normalize would touch (276503 cancel plan) ====';
;WITH cancel_plan AS (
  SELECT DISTINCT CAST(ins.ID AS BIGINT) AS PLAN_ID
  FROM izgazMGR.dbo.CS_INSTALLMENT ins WITH (NOLOCK)
  WHERE ins.AGREEMENT_ID IN (2221,978259,1192595,276503)
    AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
), inv AS (
  SELECT inv.LREF, inv.ABYS_AGREEMENT_ID, inv.INSTALLMENT_PLAN_REF, inv.ABYS_INSTALLMENT_ID
  FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
  INNER JOIN cancel_plan c ON c.PLAN_ID = ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF)
  WHERE ISNULL(inv.IOCODE,0)=0
)
SELECT
  'INV_CLEAR_REF' AS ACTION, COUNT(*) AS N
FROM inv WHERE INSTALLMENT_PLAN_REF IS NOT NULL
UNION ALL
SELECT 'TAKSIT_PT_SOFT_CANCEL', COUNT(*)
FROM energy.dbo.LS_005_01_PAYTRANS pt
JOIN inv i ON i.LREF = pt.INVOICEREF
WHERE ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)>0 AND ISNULL(pt.CANCELED,0)=0
UNION ALL
SELECT 'MAIN_PT_RESTORE', COUNT(*)
FROM energy.dbo.LS_005_01_PAYTRANS pt
JOIN inv i ON i.LREF = pt.INVOICEREF
WHERE ISNULL(pt.IOCODE,0)=0 AND ISNULL(pt.INST_NR,0)=0 AND (ISNULL(pt.CANCELED,0)=1 OR ISNULL(pt.PAID,0)<>0);

PRINT '==== FAIL_REF invoices detail ====';
SELECT inv.ABYS_AGREEMENT_ID AS AGR, inv.LREF, inv.INSTALLMENT_PLAN_REF,
  (SELECT COUNT(*) FROM energy.dbo.LS_005_01_PAYTRANS p WHERE p.INVOICEREF=inv.LREF AND ISNULL(p.IOCODE,0)=0 AND ISNULL(p.INST_NR,0)>0 AND ISNULL(p.CANCELED,0)=0) AS ACT_TAKSIT,
  (SELECT COUNT(*) FROM energy.dbo.LS_005_01_PAYTRANS p WHERE p.INVOICEREF=inv.LREF AND ISNULL(p.IOCODE,0)=0 AND ISNULL(p.INST_NR,0)=0 AND ISNULL(p.CANCELED,0)=0) AS ACT_MAIN
FROM energy.dbo.LS_005_01_INVOICE inv WITH (NOLOCK)
WHERE inv.ABYS_AGREEMENT_ID = 276503
  AND ISNULL(inv.IOCODE,0)=0
  AND inv.INSTALLMENT_PLAN_REF IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM izgazMGR.dbo.CS_INSTALLMENT ins
    WHERE ins.ID = ISNULL(inv.ABYS_INSTALLMENT_ID, inv.INSTALLMENT_PLAN_REF)
      AND (ins.CANCEL_CAUSE_ID IS NOT NULL OR ins.CANCELLATION_DATE IS NOT NULL OR ins.CANCELLATION_USER_ID IS NOT NULL)
  );

PRINT '==== WARN 152215477 detail ====';
SELECT LREF, IOCODE, INST_NR, PAYTYPE, CONVERT(DECIMAL(18,2),PAYABLETOTAL) PAYABLE,
       CONVERT(DECIMAL(18,2),PAID) PAID, CANCELED, CROSSREF, EXPLAIN
FROM energy.dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE INVOICEREF = 152215477
ORDER BY IOCODE, INST_NR, LREF;

PRINT '==== SP missing ====';
SELECT CASE WHEN OBJECT_ID('energy.dbo.SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR','P') IS NULL
  THEN 'SP_MIG_INSTALLMENT_CANCEL_NORMALIZE_BY_AGR NOT DEPLOYED'
  ELSE 'DEPLOYED' END AS NORMALIZE_SP;