import java.sql.*;
public class Cont {
  static void run(Connection c, String sql) throws Exception {
    System.out.println("--- " + sql.substring(0, Math.min(80, sql.length())).replace('\n',' '));
    try (Statement s = c.createStatement()) {
      boolean has = s.execute(sql);
      if (has) {
        try (ResultSet rs = s.getResultSet()) {
          ResultSetMetaData md = rs.getMetaData();
          int cols = md.getColumnCount();
          while (rs.next()) {
            StringBuilder row = new StringBuilder();
            for (int i=1;i<=cols;i++) {
              if (i>1) row.append(" | ");
              row.append(md.getColumnLabel(i)).append("=").append(rs.getString(i));
            }
            System.out.println(row);
          }
        }
      } else System.out.println("ok uc=" + s.getUpdateCount());
    }
  }
  public static void main(String[] a) throws Exception {
    Class.forName("oracle.jdbc.OracleDriver");
    try (Connection c = DriverManager.getConnection(
        "jdbc:oracle:thin:@//172.16.1.201:1521/izgaz","SMS","RepSmS26!IzGx")) {
      c.setAutoCommit(true);
      run(c, "BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_DEBT_PAID_UPD PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;");
      run(c, """
CREATE TABLE MIGRATION.LS_OV_DEBT_PAID_UPD NOLOGGING AS
SELECT
    p.CROSSREF_MAIN_LREF AS MAIN_LREF,
    ROUND(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.PAYABLETOTAL ELSE 0 END), 2) AS PAID_AMT,
    MAX(p.ABYS_AGREEMENT_ID) AS ABYS_AGREEMENT_ID,
    CASE
      WHEN ROUND(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.PAYABLETOTAL ELSE 0 END), 2)
           >= NVL(MAX(inv.PAYABLETOTAL), 0) - 0.01
           AND NVL(MAX(inv.PAYABLETOTAL), 0) > 0
      THEN 1 ELSE 0
    END AS CLOSED
FROM MIGRATION.LS_OV_PAY_PT p
LEFT JOIN MIGRATION.LS_INVOICE inv ON inv.LREF = p.CROSSREF_MAIN_LREF
WHERE p.CROSSREF_MAIN_LREF IS NOT NULL
GROUP BY p.CROSSREF_MAIN_LREF
""");
      run(c, "CREATE UNIQUE INDEX MIGRATION.IX_OV_DEBT_PAID ON MIGRATION.LS_OV_DEBT_PAID_UPD (MAIN_LREF)");

      run(c, "BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_TAM_HAS_PAY PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;");
      run(c, """
CREATE TABLE MIGRATION.LS_OV_TAM_HAS_PAY NOLOGGING AS
SELECT
    ec.EKS_ACTION_ID,
    ec.ACCOUNT_ID,
    ec.MAIN_LREF,
    ec.AGREEMENT_ID AS ABYS_AGREEMENT_ID,
    1600000000 + ec.EKS_ACTION_ID AS IADE_LREF,
    ec.MAIN_GRANDTOTAL,
    ec.MAIN_PAYABLETOTAL,
    ec.EKS_DATE,
    ec.CLIENTREF,
    NVL(ec.MAIN_TYPE, 119) AS MAIN_TYPE,
    (
      SELECT COUNT(*)
      FROM SMS.CS_ACCOUNT_ACTION pay
      JOIN SMS.CS_ACTION_TYPE_PRM atp ON atp.ID = pay.ACTION_TYPE_ID AND atp.TYPE = 2
      WHERE pay.ACCOUNT_ID = ec.ACCOUNT_ID
        AND pay.ACTION_TYPE_ID NOT IN (36, 37, 39, 44, 6, 24)
        AND NOT EXISTS (
              SELECT 1 FROM SMS.CS_ACCOUNT_ACTION can
             WHERE can.ACCOUNT_ID = pay.ACCOUNT_ID AND can.ACTION_TYPE_ID = 9
               AND can.CASH_ID = pay.CASH_ID AND can.RECEIPT_NUMBER = pay.RECEIPT_NUMBER
               AND NVL(can.BANK_PAYMENT_DATE, DATE '1900-01-01')
                 = NVL(pay.BANK_PAYMENT_DATE, DATE '1900-01-01')
            )
    ) AS VALID_PAY_CNT
FROM MIGRATION.LS_OV_EKS_CLASS ec
WHERE ec.KIND = 'TAM' AND ec.MAIN_LREF IS NOT NULL
""");
      run(c, "CREATE UNIQUE INDEX MIGRATION.IX_OV_TAM_HAS_PAY ON MIGRATION.LS_OV_TAM_HAS_PAY (EKS_ACTION_ID)");

      run(c, "BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_CANCEL_PAY PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;");
      run(c, """
CREATE TABLE MIGRATION.LS_OV_CANCEL_PAY NOLOGGING AS
SELECT
    1800000000 + t.EKS_ACTION_ID AS LREF,
    t.IADE_LREF AS INVOICEREF,
    CAST(92 AS NUMBER(3)) AS TYPE,
    CAST(1 AS NUMBER(3)) AS IOCODE,
    t.IADE_LREF AS CROSSREF_IADE_LREF,
    CAST(174 AS NUMBER) AS PAYTYPE,
    CAST(113 AS NUMBER) AS TRANSTYPE,
    CAST(103 AS NUMBER) AS LINETYPE,
    CAST(0 AS NUMBER) AS INST_NR,
    CASE WHEN EXTRACT(YEAR FROM t.EKS_DATE) < 1753 THEN ADD_MONTHS(t.EKS_DATE, 24000) ELSE t.EKS_DATE END AS DATE_,
    ROUND(NVL(t.MAIN_PAYABLETOTAL, t.MAIN_GRANDTOTAL), 2) AS PAYABLETOTAL,
    CAST(0 AS NUMBER) AS PAID,
    CAST(0 AS NUMBER(1)) AS CANCELED,
    CAST(1 AS NUMBER) AS CANCELLATIONPAYMENT,
    t.CLIENTREF,
    t.EKS_ACTION_ID AS ABYS_ID,
    t.ACCOUNT_ID AS ABYS_ACCOUNT_ID,
    t.ABYS_AGREEMENT_ID,
    t.MAIN_LREF AS ABYS_MAIN_LREF,
    t.EKS_ACTION_ID AS ABYS_EKS_ACTION_ID,
    CAST('CANCEL_PAY' AS VARCHAR2(12)) AS OV_KIND
FROM MIGRATION.LS_OV_TAM_HAS_PAY t
WHERE t.VALID_PAY_CNT > 0 AND (1800000000 + t.EKS_ACTION_ID) <= 2147483647
""");
      run(c, "CREATE UNIQUE INDEX MIGRATION.IX_OV_CANCEL_PAY ON MIGRATION.LS_OV_CANCEL_PAY (LREF)");

      run(c, "BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_CANCEL_REV PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;");
      run(c, """
CREATE TABLE MIGRATION.LS_OV_CANCEL_REV NOLOGGING AS
SELECT
    1900000000 + t.EKS_ACTION_ID AS LREF,
    t.MAIN_LREF AS INVOICEREF,
    t.MAIN_TYPE AS TYPE,
    CAST(0 AS NUMBER(3)) AS IOCODE,
    t.MAIN_LREF AS CROSSREF_MAIN_LREF,
    CAST(174 AS NUMBER) AS PAYTYPE,
    CAST(113 AS NUMBER) AS TRANSTYPE,
    CAST(103 AS NUMBER) AS LINETYPE,
    CAST(0 AS NUMBER) AS INST_NR,
    CASE WHEN EXTRACT(YEAR FROM t.EKS_DATE) < 1753 THEN ADD_MONTHS(t.EKS_DATE, 24000) ELSE t.EKS_DATE END AS DATE_,
    ROUND(NVL(t.MAIN_PAYABLETOTAL, t.MAIN_GRANDTOTAL), 2) AS PAYABLETOTAL,
    CAST(0 AS NUMBER) AS PAID,
    CAST(0 AS NUMBER(1)) AS CANCELED,
    CAST(1 AS NUMBER) AS CANCELLATIONPAYMENT,
    t.CLIENTREF,
    t.EKS_ACTION_ID AS ABYS_ID,
    t.ACCOUNT_ID AS ABYS_ACCOUNT_ID,
    t.ABYS_AGREEMENT_ID,
    t.MAIN_LREF AS ABYS_MAIN_LREF,
    t.EKS_ACTION_ID AS ABYS_EKS_ACTION_ID,
    CAST('CANCEL_REV' AS VARCHAR2(12)) AS OV_KIND
FROM MIGRATION.LS_OV_TAM_HAS_PAY t
WHERE t.VALID_PAY_CNT > 0 AND (1900000000 + t.EKS_ACTION_ID) <= 2147483647
""");
      run(c, "CREATE UNIQUE INDEX MIGRATION.IX_OV_CANCEL_REV ON MIGRATION.LS_OV_CANCEL_REV (LREF)");

      run(c, """
SELECT 'PAY_PT' K, COUNT(*) N FROM MIGRATION.LS_OV_PAY_PT
UNION ALL SELECT 'PAY_OK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_CANC', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=1
UNION ALL SELECT 'PAY_NO_XREF', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL
UNION ALL SELECT 'DEBT_PAID', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD
UNION ALL SELECT 'DEBT_CLOSED', COUNT(*) FROM MIGRATION.LS_OV_DEBT_PAID_UPD WHERE CLOSED=1
UNION ALL SELECT 'TAM_HAS_PAY', COUNT(*) FROM MIGRATION.LS_OV_TAM_HAS_PAY WHERE VALID_PAY_CNT>0
UNION ALL SELECT 'CANCEL_PAY', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_PAY
UNION ALL SELECT 'CANCEL_REV', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_REV
""");
    }
  }
}