/* ============================================================
   FILE : adim_590_597_only.sql
   Taksit (613) ATLANDI
   Sira: 590 EKSILTEN → 597 TAHSILAT
   ============================================================ */
USE energy;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @Msg NVARCHAR(400);
DECLARE @tAll DATETIME2(3) = SYSDATETIME();
DECLARE @t0 DATETIME2(3);

SET @Msg = N'===== 590+597 ONLY (613 SKIP) START ' + CONVERT(VARCHAR(30), @tAll, 121) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 590 EKSILTEN ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== 590 EKSILTEN START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR', 'P') IS NOT NULL
   AND OBJECT_ID('izgazMGR.dbo.LS_OV_IADE_INVOICE', 'U') IS NOT NULL
    EXEC energy.dbo.SP_MIGRATE_EKSILTEN_OVERLAY_AGR
        @AGR_ID = NULL, @CLEAN = 1, @DEBUG = 1;
ELSE
    RAISERROR('590 SP veya LS_OV_IADE_INVOICE yok — atlandi', 16, 1);

SET @Msg = N'===== 590 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

/* ---- 597 TAHSILAT ---- */
SET @t0 = SYSDATETIME();
SET @Msg = N'===== 597 TAHSILAT START =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

IF OBJECT_ID('energy.dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR', 'P') IS NOT NULL
   AND OBJECT_ID('izgazMGR.dbo.LS_OV_PAY_PT', 'U') IS NOT NULL
    EXEC energy.dbo.SP_MIGRATE_TAHSILAT_OVERLAY_AGR
        @AGR_ID = NULL, @CLEAN = 1, @DEBUG = 1;
ELSE
    RAISERROR('597 SP veya LS_OV_PAY_PT yok — atlandi', 16, 1);

SET @Msg = N'===== 597 DONE sec=' + CAST(DATEDIFF(SECOND, @t0, SYSDATETIME()) AS VARCHAR(20)) + N' =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SET @Msg = N'===== 590+597 ALL DONE total_sec='
         + CAST(DATEDIFF(SECOND, @tAll, SYSDATETIME()) AS VARCHAR(20))
         + N' | 613 SKIPPED =====';
RAISERROR('%s', 0, 1, @Msg) WITH NOWAIT;

SELECT 'INV' K, COUNT_BIG(*) N FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
UNION ALL
SELECT 'DEBT', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
 WHERE ISNULL(IOCODE,0)=0 AND ABYS_ID IS NOT NULL
UNION ALL
SELECT 'PAY', COUNT_BIG(*) FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
 WHERE ISNULL(IOCODE,0)=1
UNION ALL
SELECT 'OV_PAY_SRC', COUNT_BIG(*) FROM izgazMGR.dbo.LS_OV_PAY_PT WITH (NOLOCK)
UNION ALL
SELECT 'OV_IADE_SRC', COUNT_BIG(*) FROM izgazMGR.dbo.LS_OV_IADE_INVOICE WITH (NOLOCK);
GO
