WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

-- =============================================================================
-- oracleCTAS3007 / 10 — STG_INV_ACC_INC (income aggregate + fee pivot)
-- Onkosul: 00_session + 00_mig_param
-- DOP: FORCE 56 (hash aggregate — PGA/TEMP RISK yuksek)
-- Tutar kolonlari: CAST NUMBER(18,3) — dump/migrator scale kaybi onlenir
-- LS_001 DV ayirimi (yalniz guvence tahakkuk tipleri):
--   ACCRUE 5/6 → PCMS 109 | ACCRUE 21/341 → PCMS 111
--   Bu tiplerde: TOTAL_DV = 23032/938/1863; TOTAL_EXCL_TAX bunlari haric
--   Diger ACCRUE: TOTAL_DV=0; damga TOTAL_EXCL_TAX icinde (eski davranis)
-- Sonraki: 11_ls_invoice.sql
-- =============================================================================

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER='MIGRATION' AND TABLE_NAME='MIG_PARAM';
  IF n = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE TABLE MIGRATION.MIG_PARAM (REG_ID NUMBER(12), AGR_ID NUMBER(12))';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.STG_INV_ACC_INC PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
CREATE TABLE MIGRATION.STG_INV_ACC_INC NOLOGGING PARALLEL 56 AS
SELECT /*+ FULL(aca) FULL(ai) PARALLEL(56) */
    CAST(aca.ACCOUNT_ID AS NUMBER(12))                          AS ACCOUNT_ID,
    CAST(aca.ID AS NUMBER(12))                                  AS ACA_ID,

    /* ACCRUE 5/6/21/341 = guvence ailesi (109/111) — DV ayir */
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID IN (939, 7658)  THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS EXPEND_FEE,
    CAST(ROUND(SUM(CASE
        WHEN a.ACCRUE_TYPE_ID IN (5, 6, 21, 341)
             AND ai.INCOME_ID NOT IN (169, 60, 23032, 938, 1863) THEN ai.AMOUNT
        WHEN NVL(a.ACCRUE_TYPE_ID, -1) NOT IN (5, 6, 21, 341)
             AND ai.INCOME_ID NOT IN (169, 60) THEN ai.AMOUNT
      END), 3) AS NUMBER(18,3))                                 AS TOTAL_EXCL_TAX,
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID IN (169, 60)    THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS TOTAL_TAX,
    CAST(ROUND(SUM(CASE
        WHEN a.ACCRUE_TYPE_ID IN (5, 6, 21, 341)
             AND ai.INCOME_ID IN (23032, 938, 1863) THEN ai.AMOUNT
      END), 3) AS NUMBER(18,3))                                 AS TOTAL_DV,
    CAST(ROUND(SUM(ai.AMOUNT), 3) AS NUMBER(18,3))              AS PAYABLE_TOTAL,

    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID = 1861 THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS GAS_OPEN_FEE,
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID = 1864 THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS DEFAULT_FINE,
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID = 1905 THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS DEFAULT_FINE_TAX,
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID = 1902 THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS ILLEGAL_USE_FEE,
    CAST(ROUND(SUM(CASE WHEN ai.INCOME_ID = 100  THEN ai.AMOUNT END), 3) AS NUMBER(18,3)) AS DISCOUNT_ADDITION,
    CAST(ROUND(SUM(CASE
        WHEN ai.INCOME_ID IN
            (2981, 572, 23033, 573, 23034, 23031, 2982,
             576, 574, 3251, 12531, 579, 47, 578, 581, 575, 7709,
             577, 7504, 2521, 7528, 7464, 2847, 2446, 2649, 2520,
             7408, 2591, 7496, 2583, 3067)
          THEN ai.AMOUNT
        /* damga: yalniz guvence disi tahakkukta SPEC_SERV (eski) */
        WHEN NVL(a.ACCRUE_TYPE_ID, -1) NOT IN (5, 6, 21, 341)
             AND ai.INCOME_ID IN (938, 23032) THEN ai.AMOUNT
      END), 3) AS NUMBER(18,3))                                 AS SPEC_SERV_FEE,

    CAST(SUM(CASE WHEN ai.INCOME_ID IN (939, 7658) THEN 1 ELSE 0 END) AS NUMBER(10)) AS HAS_GAZ,
    CAST(SUM(CASE WHEN ai.INCOME_ID IN
            (162, 163, 164, 165, 1936, 3198, 3199,
             7649, 7650, 7651, 7652, 12531, 23032)
         THEN 1 ELSE 0 END) AS NUMBER(10))                      AS HAS_GUV,
    CAST(MAX(CASE WHEN NVL(ai.IS_DISCOUNT, 0) = 1 THEN 1 ELSE 0 END) AS NUMBER(1)) AS HAS_DISCOUNT,
    CAST(ROUND(SUM(CASE WHEN NVL(ai.IS_DISCOUNT, 0) = 1 THEN ABS(ai.AMOUNT) ELSE 0 END), 3) AS NUMBER(18,3)) AS DISCOUNT_AMOUNT

FROM SMS.CS_ACCOUNT_ACTION aca
JOIN SMS.CS_ACCOUNT a ON a.ID = aca.ACCOUNT_ID
LEFT JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aca.ID
WHERE aca.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(a.ACCRUE_TYPE_ID, -1) <> 14
  /* MIG_PARAM.AGR_ID doluysa pilot; bos = FULL */
  AND (
        NOT EXISTS (SELECT 1 FROM MIGRATION.MIG_PARAM p WHERE p.AGR_ID IS NOT NULL)
     OR a.AGREEMENT_ID IN (SELECT p.AGR_ID FROM MIGRATION.MIG_PARAM p WHERE p.AGR_ID IS NOT NULL)
      )
GROUP BY aca.ACCOUNT_ID, aca.ID;

CREATE UNIQUE INDEX MIGRATION.IX_STG_INV_ACC_INC ON MIGRATION.STG_INV_ACC_INC (ACA_ID)
  PARALLEL 56 NOLOGGING;

ALTER INDEX MIGRATION.IX_STG_INV_ACC_INC NOPARALLEL;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'STG_INV_ACC_INC', degree => 40); END;
/

PROMPT ========== 10 STG_INV_ACC_INC OK ==========
/
