-- =============================================================================
-- oracleCTAS3007 / 55 — LS_MAHSUP (mahsus PAY→MAIN / emanet izi)
-- Onkosul: O30 LS_OV_MAHSUP_SRC (yoksa LS_OV_PAY_PT OV_KIND=MAHSUP)
-- Dogal ID; MAP/SRC_KEY yok (PAY_SRC_KEY diag icin tutulabilir)
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n_src NUMBER;
  n_pt  NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_src FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_MAHSUP_SRC';
  SELECT COUNT(*) INTO n_pt FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_PAY_PT';
  IF n_src = 0 AND n_pt = 0 THEN
    RAISE_APPLICATION_ERROR(-20055, 'MAHSUP kaynagi yok — once O30.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O55', 'ls_mahsup', 'START', NULL, 'MAHSUP_SRC or PAY_PT');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_MAHSUP PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

DECLARE
  n_src NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_src FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_MAHSUP_SRC';
  IF n_src > 0 THEN
    EXECUTE IMMEDIATE q'[
CREATE TABLE MIGRATION.LS_MAHSUP NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(M.PAY_LREF AS NUMBER(12))                               AS PAY_LREF,
    CAST(M.MAIN_LREF AS NUMBER(12))                              AS MAIN_LREF,
    CAST(M.ABYS_AGREEMENT_ID AS NUMBER(12))                      AS SOZLESME,
    CAST(M.ACCOUNT_ID AS NUMBER(12))                             AS FATURAID,
    CAST(M.ACTION_TYPE_ID AS NUMBER(10))                         AS ACTION_TYPE_ID,
    CAST(M.PAYABLETOTAL AS NUMBER(15,3))                         AS PAYABLETOTAL,
    CAST(M.DEP_ACCOUNT_ID AS NUMBER(12))                         AS DEP_ACCOUNT_ID,
    CAST(M.DEP_ACTION_ID AS NUMBER(12))                          AS DEP_ACTION_ID,
    CAST(M.CASH_ID AS NUMBER(12))                                AS VEZNE_ID,
    CAST(M.RECEIPT_NUMBER AS VARCHAR2(40))                       AS TAH_MAKBUZ_NO,
    CAST(M.PAY_SRC_KEY AS VARCHAR2(80))                          AS PAY_SRC_KEY,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_OV_MAHSUP_SRC M
]';
  ELSE
    EXECUTE IMMEDIATE q'[
CREATE TABLE MIGRATION.LS_MAHSUP NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(P.ABYS_ID AS NUMBER(12))                                AS PAY_LREF,
    CAST(P.CROSSREF_MAIN_LREF AS NUMBER(12))                     AS MAIN_LREF,
    CAST(P.ABYS_AGREEMENT_ID AS NUMBER(12))                      AS SOZLESME,
    CAST(P.ABYS_ACCOUNT_ID AS NUMBER(12))                        AS FATURAID,
    CAST(P.ABYS_ACTION_TYPE_ID AS NUMBER(10))                    AS ACTION_TYPE_ID,
    CAST(P.PAYABLETOTAL AS NUMBER(15,3))                         AS PAYABLETOTAL,
    CAST(P.REF_DEPOSIT_ACCOUNT_ID AS NUMBER(12))                 AS DEP_ACCOUNT_ID,
    CAST(P.REF_DEPOSIT_ACCOUNT_ACTION_ID AS NUMBER(12))          AS DEP_ACTION_ID,
    CAST(P.CASH_ID AS NUMBER(12))                                AS VEZNE_ID,
    CAST(P.RECEIPT_NUMBER AS VARCHAR2(40))                       AS TAH_MAKBUZ_NO,
    CAST(P.SRC_KEY AS VARCHAR2(80))                              AS PAY_SRC_KEY,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_OV_PAY_PT P
WHERE P.OV_KIND = 'MAHSUP'
  AND NVL(P.CANCELED, 0) = 0
  AND P.CROSSREF_MAIN_LREF IS NOT NULL
]';
  END IF;
END;
/

CREATE INDEX MIGRATION.IX_LS_MAHSUP_PAY ON MIGRATION.LS_MAHSUP (PAY_LREF) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_MAHSUP_MAIN ON MIGRATION.LS_MAHSUP (MAIN_LREF) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_MAHSUP_AGR ON MIGRATION.LS_MAHSUP (SOZLESME) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_MAHSUP_PAY NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_MAHSUP_MAIN NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_MAHSUP_AGR NOPARALLEL;
ALTER TABLE MIGRATION.LS_MAHSUP NOPARALLEL LOGGING;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_MAHSUP', degree => 40); END;
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM MIGRATION.LS_MAHSUP;
  MIGRATION.P_MIG_CTAS_LOG('O55', 'ls_mahsup', 'OK', n, 'mahsup=' || n);
  DBMS_OUTPUT.PUT_LINE('========== O55 LS_MAHSUP OK | n=' || n || ' ==========');
END;
/
