-- =============================================================================
-- oracleCTAS3007 / 56 — LS_TAKSIT (TÜM taksitli hesaplar — açık+kapalı)
-- Onkosul: O50 (opsiyonel join), SMS.CS_ACCOUNT + CS_INSTALLMENT
--
-- Pilot: AFL yalnızca BALANCE>0 → kapalı taksitler kayboluyordu (5 SMS / 0 ENERGY).
-- Grain : ACCOUNT_ID = FATURAID; INSTALLMENT_ID zorunlu
-- DURUM : ACIK | KAPALI | IPTAL | FAZLA_ODEME (wizard ile uyumlu)
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'SMS' AND TABLE_NAME = 'CS_INSTALLMENT';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20056, 'SMS.CS_INSTALLMENT yok.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O56', 'ls_taksit', 'START', NULL,
      'ALL installment accounts open+closed+cancel');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_TAKSIT PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE MIGRATION.LS_TAKSIT NOLOGGING PARALLEL 56 AS
WITH bal AS (
  SELECT /*+ PARALLEL(56) */
      a.ID AS ACCOUNT_ID,
      a.AGREEMENT_ID,
      a.INSTALLMENT_ID,
      a.ACCRUE_TYPE_ID,
      CAST(ROUND(SUM(ai.STATUS * ai.AMOUNT), 2) AS NUMBER(15,3)) AS BALANCE
  FROM SMS.CS_ACCOUNT a
  JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ACCOUNT_ID = a.ID
  JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
  WHERE a.INSTALLMENT_ID IS NOT NULL
  GROUP BY a.ID, a.AGREEMENT_ID, a.INSTALLMENT_ID, a.ACCRUE_TYPE_ID
),
inst AS (
  SELECT
      i.ID AS INSTALLMENT_ID,
      i.AGREEMENT_ID,
      i.INSTALLMENT_NUMBER,
      i.TOTAL_AMOUNT,
      i.CANCEL_CAUSE_ID,
      i.CANCELLATION_DATE,
      i.CANCELLATION_USER_ID
  FROM SMS.CS_INSTALLMENT i
)
SELECT /*+ PARALLEL(56) */
    CAST(b.ACCOUNT_ID AS NUMBER(12))                             AS FATURAID,
    CAST(b.AGREEMENT_ID AS NUMBER(12))                           AS SOZLESME,
    CAST(b.BALANCE AS NUMBER(15,3))                              AS BALANCE,
    CAST(CASE
           WHEN i.CANCEL_CAUSE_ID IS NOT NULL
             OR i.CANCELLATION_DATE IS NOT NULL
             OR i.CANCELLATION_USER_ID IS NOT NULL
             THEN 'IPTAL'
           WHEN ABS(NVL(b.BALANCE, 0)) <= 0.01 THEN 'KAPALI'
           WHEN NVL(b.BALANCE, 0) < -0.01 THEN 'FAZLA_ODEME'
           ELSE 'ACIK'
         END AS VARCHAR2(12))                                    AS TAKSIT_DURUMU,
    CAST('T' AS VARCHAR2(1))                                     AS TAKSIT_FLAG,
    CAST(b.INSTALLMENT_ID AS NUMBER(12))                         AS INSTALLMENT_ID,
    CAST(i.INSTALLMENT_NUMBER AS NUMBER(10))                     AS TAKSIT_NO,
    CAST(i.TOTAL_AMOUNT AS NUMBER(15,3))                         AS TAKSIT_TUTARI,
    CAST(INV.LREF AS NUMBER(12))                                 AS MAIN_LREF,
    CAST(CASE WHEN NVL(b.ACCRUE_TYPE_ID, -1) <> 14 THEN 1 ELSE 0 END
         AS NUMBER(1))                                           AS MIG_IN_SCOPE,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM bal b
JOIN inst i ON i.INSTALLMENT_ID = b.INSTALLMENT_ID
LEFT JOIN MIGRATION.LS_INVOICE INV
  ON INV.ABYS_ACCOUNT_ID = b.ACCOUNT_ID
 AND INV.ABYS_ACTION_TYPE_ID = 1
 AND NVL(INV.CANCELED, 0) = 0;

CREATE INDEX MIGRATION.IX_LS_TAKSIT_INST ON MIGRATION.LS_TAKSIT (INSTALLMENT_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_TAKSIT_AGR ON MIGRATION.LS_TAKSIT (SOZLESME) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_TAKSIT_FAT ON MIGRATION.LS_TAKSIT (FATURAID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_LS_TAKSIT_DUR ON MIGRATION.LS_TAKSIT (TAKSIT_DURUMU) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_LS_TAKSIT_INST NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_TAKSIT_AGR NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_TAKSIT_FAT NOPARALLEL;
ALTER INDEX MIGRATION.IX_LS_TAKSIT_DUR NOPARALLEL;
ALTER TABLE MIGRATION.LS_TAKSIT NOPARALLEL LOGGING;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_TAKSIT', degree => 40); END;
/

DECLARE
  n NUMBER; n_acik NUMBER; n_kap NUMBER; n_ipt NUMBER;
BEGIN
  SELECT COUNT(*),
         COUNT(CASE WHEN TAKSIT_DURUMU='ACIK' THEN 1 END),
         COUNT(CASE WHEN TAKSIT_DURUMU='KAPALI' THEN 1 END),
         COUNT(CASE WHEN TAKSIT_DURUMU='IPTAL' THEN 1 END)
    INTO n, n_acik, n_kap, n_ipt FROM MIGRATION.LS_TAKSIT;
  MIGRATION.P_MIG_CTAS_LOG('O56', 'ls_taksit', 'OK', n,
    'all=' || n || ' acik=' || n_acik || ' kapali=' || n_kap || ' iptal=' || n_ipt);
  DBMS_OUTPUT.PUT_LINE('========== O56 LS_TAKSIT OK | n=' || n
    || ' ACIK=' || n_acik || ' KAPALI=' || n_kap || ' IPTAL=' || n_ipt || ' ==========');
END;
/
