-- =============================================================================
-- oracleCTAS3007 / 60 — LS_OV_GUVENCE_IADE_* (TYPE 110 GÜVENCE BEDELİ İADE)
-- Kaynak : SMS CS_ACCOUNT (ACCRUE=14) + ACTION tip20/12/40 + INCOME güvence seti
-- Degil  : LS_AGR_GUARANTY / energy patch
-- Cikti  : LS_OV_GUVENCE_IADE_INVOICE / INVLINES / PAYTRANS (+ ID_MAP append)
-- Kural  : Migratorv0/Services/Staging/GUVENCE_IADE_110_RULE.md
-- Onkosul: MIG_PARAM (yoksa FULL olusturulur); SMS erisim
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'MIG_PARAM';
  IF n = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE TABLE MIGRATION.MIG_PARAM (REG_ID NUMBER(12), AGR_ID NUMBER(12))';
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O60', 'ls_ov_guvence_iade', 'START', NULL,
      'ACCRUE14 tip20/12/40 + guv incomes → TYPE110');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

/* ---------------------------------------------------------------------------
   0) Pivot staging — hesap basina tip20 / tip12 / tediye
--------------------------------------------------------------------------- */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.STG_GUV_IADE_PIVOT PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.STG_GUV_IADE_PIVOT NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST(p.ACCOUNT_ID AS NUMBER(12))                             AS ACCOUNT_ID,
    CAST(p.AGREEMENT_ID AS NUMBER(12))                           AS AGREEMENT_ID,
    CAST(p.REGISTER_ID AS NUMBER(12))                            AS REGISTER_ID,
    CAST(p.FITNO AS NUMBER(19))                                  AS FITNO,
    CAST(p.BN_TYPE AS NUMBER(10))                                AS BN_TYPE,
    CAST(ROUND(p.TIP20, 2) AS NUMBER(18,3))                      AS TIP20,
    CAST(ROUND(p.TIP12, 2) AS NUMBER(18,3))                      AS TIP12,
    CAST(ROUND(p.TEDIYE, 2) AS NUMBER(18,3))                     AS TEDIYE,
    CAST(ROUND(p.G162, 2) AS NUMBER(18,3))                       AS G162,
    CAST(ROUND(p.G1936, 2) AS NUMBER(18,3))                      AS G1936,
    CAST(ROUND(ABS(p.TEDIYE), 2) AS NUMBER(18,3))                AS TLTOTAL_110,
    p.IADE_DATE,
    CAST(p.TEDIYE_ACTION_ID AS NUMBER(12))                       AS TEDIYE_ACTION_ID,
    CAST(p.TEDIYE_ACTION_TYPE_ID AS NUMBER(10))                  AS TEDIYE_ACTION_TYPE_ID,
    CAST(p.TIP20_ACTION_ID AS NUMBER(12))                        AS TIP20_ACTION_ID
FROM (
  SELECT
      a.ID                                                       AS ACCOUNT_ID,
      a.AGREEMENT_ID,
      a.REGISTER_ID,
      i.INSTALLATION_NUMBER                                      AS FITNO,
      CAST(NULL AS NUMBER(10))                                   AS BN_TYPE,
      SUM(CASE WHEN aa.ACTION_TYPE_ID = 20
               THEN ai.AMOUNT * ai.STATUS ELSE 0 END)            AS TIP20,
      SUM(CASE WHEN aa.ACTION_TYPE_ID = 12
               THEN ai.AMOUNT * ai.STATUS ELSE 0 END)            AS TIP12,
      SUM(CASE WHEN aa.ACTION_TYPE_ID IN (40, 11, 29)
               THEN ai.AMOUNT * ai.STATUS ELSE 0 END)            AS TEDIYE,
      SUM(CASE WHEN aa.ACTION_TYPE_ID = 20 AND ai.INCOME_ID = 162
               THEN ai.AMOUNT * ai.STATUS ELSE 0 END)            AS G162,
      SUM(CASE WHEN aa.ACTION_TYPE_ID = 20 AND ai.INCOME_ID = 1936
               THEN ai.AMOUNT * ai.STATUS ELSE 0 END)            AS G1936,
      MAX(CASE WHEN aa.ACTION_TYPE_ID IN (40, 11, 29)
               THEN aa.ACTION_DATE END)                          AS IADE_DATE,
      MAX(CASE WHEN aa.ACTION_TYPE_ID IN (40, 11, 29)
               THEN aa.ID END)                                   AS TEDIYE_ACTION_ID,
      MAX(CASE WHEN aa.ACTION_TYPE_ID IN (40, 11, 29)
               THEN aa.ACTION_TYPE_ID END)                       AS TEDIYE_ACTION_TYPE_ID,
      MAX(CASE WHEN aa.ACTION_TYPE_ID = 20 THEN aa.ID END)       AS TIP20_ACTION_ID
  FROM SMS.CS_ACCOUNT a
  JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ACCOUNT_ID = a.ID
  JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
  JOIN SMS.CS_AGREEMENT ag ON ag.ID = a.AGREEMENT_ID
  LEFT JOIN SMS.CS_INSTALLATION i ON i.ID = ag.INSTALLATION_ID
  WHERE a.ACCRUE_TYPE_ID = 14
    AND ai.INCOME_ID IN (
          162, 163, 164, 165, 1936, 3198, 3199,
          7649, 7650, 7651, 7652, 12531, 23032
        )
    AND aa.ACTION_TYPE_ID IN (20, 12, 40, 11, 29)
    AND (
          NOT EXISTS (SELECT 1 FROM MIGRATION.MIG_PARAM p WHERE p.AGR_ID IS NOT NULL)
       OR a.AGREEMENT_ID IN (SELECT p.AGR_ID FROM MIGRATION.MIG_PARAM p WHERE p.AGR_ID IS NOT NULL)
        )
  GROUP BY a.ID, a.AGREEMENT_ID, a.REGISTER_ID, i.INSTALLATION_NUMBER
) p
WHERE ABS(NVL(p.TEDIYE, 0)) > 0.02;

CREATE UNIQUE INDEX MIGRATION.IX_STG_GUV_IADE_ACC
  ON MIGRATION.STG_GUV_IADE_PIVOT (ACCOUNT_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_STG_GUV_IADE_AGR
  ON MIGRATION.STG_GUV_IADE_PIVOT (AGREEMENT_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_STG_GUV_IADE_ACC NOPARALLEL;
ALTER INDEX MIGRATION.IX_STG_GUV_IADE_AGR NOPARALLEL;
ALTER TABLE MIGRATION.STG_GUV_IADE_PIVOT NOPARALLEL LOGGING;

/* ---------------------------------------------------------------------------
   1) INVOICE — TYPE 110, IOCODE Alacak, EXPLAIN mahsup kalan
--------------------------------------------------------------------------- */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVOICE PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVOICE NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST('GUV_IADE_INV|' || TO_CHAR(p.ACCOUNT_ID) AS VARCHAR2(80)) AS SRC_KEY,
    CAST(NULL AS NUMBER(12))                                     AS LREF_HINT,
    CAST(1 AS NUMBER(3))                                         AS IOCODE,          -- Alacak
    CAST('I' || LPAD(TO_CHAR(MOD(NVL(p.TEDIYE_ACTION_ID, p.ACCOUNT_ID), 10000000)), 7, '0')
         AS VARCHAR2(16))                                        AS FICHENO,
    CASE
      WHEN p.IADE_DATE IS NULL THEN CAST(NULL AS DATE)
      WHEN p.IADE_DATE < DATE '1900-01-01' THEN DATE '1900-01-01'
      WHEN p.IADE_DATE > DATE '2079-06-06' THEN DATE '2079-06-06'
      ELSE p.IADE_DATE
    END                                                          AS DATE_,
    CASE
      WHEN p.IADE_DATE IS NULL THEN CAST(NULL AS DATE)
      WHEN p.IADE_DATE < DATE '1900-01-01' THEN DATE '1900-01-01'
      WHEN p.IADE_DATE > DATE '2079-06-06' THEN DATE '2079-06-06'
      ELSE p.IADE_DATE
    END                                                          AS DUEDATE,
    CAST(110 AS NUMBER(3))                                       AS TYPE,            -- GÜVENCE BEDELİ İADE
    CAST(NVL(p.REGISTER_ID, 0) AS NUMBER(12))                    AS CLIENTREF,
    CAST(p.TLTOTAL_110 AS NUMBER(18,3))                          AS TLTOTAL,
    CAST(160 AS NUMBER(5))                                       AS CURID,
    CAST(p.TLTOTAL_110 AS NUMBER(18,3))                          AS CURTOTAL,
    CAST(UPPER(TO_CHAR(NVL(p.FITNO, 0)) || ' Mahsuplaşma sonrası kalan bedel')
         AS VARCHAR2(250))                                       AS EXPLAIN,
    CAST(0 AS NUMBER(1))                                         AS CANCELED,
    CAST(p.AGREEMENT_ID AS NUMBER(12))                           AS OWNERREF,
    CAST(91 AS NUMBER(3))                                        AS OWNERTYPE,       -- AGR
    CAST(0 AS NUMBER(18,3))                                      AS TAX,
    CAST(0 AS NUMBER(18,3))                                      AS DV,
    CAST(p.TLTOTAL_110 AS NUMBER(18,3))                          AS GRANDTOTAL,
    CAST(0 AS NUMBER(10))                                        AS PRINTCOUNT,
    CAST(p.TLTOTAL_110 AS NUMBER(18,3))                          AS PAYABLETOTAL,
    CAST(1 AS NUMBER(1))                                         AS CLOSED,
    CAST(NULL AS NUMBER(12))                                     AS RETURN_SOURCE_INVREF,
    CAST(NULL AS NUMBER(12))                                     AS RETURN_TARGET_INVREF,
    CAST(p.FITNO AS NUMBER(19))                                  AS FITNO,
    CAST(p.BN_TYPE AS NUMBER(10))                                AS BN_TYPE,
    CAST(p.TLTOTAL_110 AS NUMBER(18,3))                          AS AMOUNT,
    CAST(CASE WHEN p.IADE_DATE IS NULL THEN NULL
              ELSE TO_NUMBER(TO_CHAR(p.IADE_DATE, 'YYYYMM')) END AS NUMBER(10)) AS PERIOD,
    CAST(0 AS NUMBER(1))                                         AS HAS_DISCOUNT,
    CAST(0 AS NUMBER(18,3))                                      AS DISCOUNT_AMOUNT,
    CASE
      WHEN p.IADE_DATE IS NULL THEN CAST(NULL AS DATE)
      WHEN p.IADE_DATE < DATE '1900-01-01' THEN DATE '1900-01-01'
      WHEN p.IADE_DATE > DATE '2079-06-06' THEN DATE '2079-06-06'
      ELSE p.IADE_DATE
    END                                                          AS ADDDATE,
    CAST(NULL AS NUMBER(10))                                     AS ADDUSER,
    CAST(NVL(p.TEDIYE_ACTION_ID, p.ACCOUNT_ID) AS NUMBER(12))    AS ABYS_ID,
    CAST(p.ACCOUNT_ID AS NUMBER(12))                             AS ABYS_ACCOUNT_ID,
    CAST(NVL(p.TEDIYE_ACTION_TYPE_ID, 40) AS NUMBER(10))         AS ABYS_ACTION_TYPE_ID,
    CAST(p.AGREEMENT_ID AS NUMBER(12))                           AS ABYS_AGREEMENT_ID,
    CAST(p.ACCOUNT_ID AS NUMBER(12))                             AS ABYS_MAIN_LREF,   -- emanet hesabi
    CAST(p.TEDIYE_ACTION_ID AS NUMBER(12))                       AS ABYS_TEDIYE_ACTION_ID,
    CAST(p.TIP20_ACTION_ID AS NUMBER(12))                        AS ABYS_TIP20_ACTION_ID,
    CAST(p.TIP20 AS NUMBER(18,3))                                AS TIP20_NET,
    CAST(p.TIP12 AS NUMBER(18,3))                                AS TIP12_NET,
    CAST(p.TEDIYE AS NUMBER(18,3))                               AS TEDIYE_NET,
    CAST('GUV_IADE' AS VARCHAR2(10))                             AS OV_KIND
FROM MIGRATION.STG_GUV_IADE_PIVOT p;

CREATE UNIQUE INDEX MIGRATION.IX_OV_GUV_IADE_INV
  ON MIGRATION.LS_OV_GUVENCE_IADE_INVOICE (SRC_KEY) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_GUV_IADE_INV_AGR
  ON MIGRATION.LS_OV_GUVENCE_IADE_INVOICE (ABYS_AGREEMENT_ID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_GUV_IADE_INV_ACC
  ON MIGRATION.LS_OV_GUVENCE_IADE_INVOICE (ABYS_ACCOUNT_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_INV NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_INV_AGR NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_INV_ACC NOPARALLEL;
ALTER TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVOICE NOPARALLEL LOGGING;

/* ---------------------------------------------------------------------------
   2) INVLINES — tip40 gelir kirilimi (162/1936…); yoksa tek satir 823
--------------------------------------------------------------------------- */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVLINES PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVLINES NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */ * FROM (
  SELECT
      CAST('GUV_IADE_IL|' || TO_CHAR(inv.ABYS_ACCOUNT_ID) || '|' || TO_CHAR(ln.INCOME_ID)
           AS VARCHAR2(80))                                      AS SRC_KEY,
      CAST(NULL AS NUMBER(12))                                   AS LREF_HINT,
      inv.SRC_KEY                                                AS INVOICE_SRC_KEY,
      inv.CLIENTREF,
      inv.DATE_,
      CAST(110 AS NUMBER(3))                                     AS TYPE,
      CAST(ROW_NUMBER() OVER (PARTITION BY inv.ABYS_ACCOUNT_ID
                              ORDER BY ln.INCOME_ID) AS NUMBER(5)) AS LINENR,
      CAST(ln.INCOME_ID AS NUMBER(10))                           AS TRANSTYPE,
      CAST(ABS(ln.NET) AS NUMBER(18,3))                          AS AMOUNT,
      CAST(ABS(ln.NET) AS NUMBER(18,3))                          AS TLTOTAL,
      CAST(0 AS NUMBER(18,3))                                    AS TAX,
      CAST(ABS(ln.NET) AS NUMBER(18,3))                          AS GRANDTOTAL,
      CAST(CASE ln.INCOME_ID
             WHEN 162  THEN 'GÜVENCE BEDELİ'
             WHEN 1936 THEN 'GÜVENCE FARK BEDELİ'
             ELSE 'Guvence Bedeli İade'
           END AS VARCHAR2(100))                                 AS LINEEXP,
      CAST(ln.INCOME_ID AS NUMBER(10))                           AS ABYS_INCOME_ID,
      CAST(823 AS NUMBER(10))                                    AS PCMS_INCOME_CODE, -- 823 Guvence Bedeli İade
      CAST(NULL AS NUMBER(12))                                   AS ABYS_ID,
      inv.ABYS_TEDIYE_ACTION_ID                                  AS ABYS_TEDIYE_ACTION_ID,
      inv.ABYS_AGREEMENT_ID,
      inv.ABYS_ACCOUNT_ID,
      CAST('GUV_IADE' AS VARCHAR2(10))                           AS OV_KIND
  FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE inv
  JOIN (
    SELECT aa.ACCOUNT_ID,
           ai.INCOME_ID,
           ROUND(SUM(ai.AMOUNT * ai.STATUS), 2) AS NET
      FROM SMS.CS_ACCOUNT_ACTION aa
      JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
      JOIN MIGRATION.STG_GUV_IADE_PIVOT p ON p.ACCOUNT_ID = aa.ACCOUNT_ID
     WHERE aa.ACTION_TYPE_ID IN (40, 11, 29)
       AND ai.INCOME_ID IN (
             162, 163, 164, 165, 1936, 3198, 3199,
             7649, 7650, 7651, 7652, 12531, 23032
           )
     GROUP BY aa.ACCOUNT_ID, ai.INCOME_ID
    HAVING ABS(SUM(ai.AMOUNT * ai.STATUS)) > 0.02
  ) ln ON ln.ACCOUNT_ID = inv.ABYS_ACCOUNT_ID
  UNION ALL
  /* tip40 gelir satiri yoksa tek 823 satiri */
  SELECT
      CAST('GUV_IADE_IL|' || TO_CHAR(inv.ABYS_ACCOUNT_ID) || '|823' AS VARCHAR2(80)),
      CAST(NULL AS NUMBER(12)),
      inv.SRC_KEY,
      inv.CLIENTREF,
      inv.DATE_,
      CAST(110 AS NUMBER(3)),
      CAST(1 AS NUMBER(5)),
      CAST(823 AS NUMBER(10)),
      inv.TLTOTAL,
      inv.TLTOTAL,
      CAST(0 AS NUMBER(18,3)),
      inv.TLTOTAL,
      CAST('Guvence Bedeli İade' AS VARCHAR2(100)),
      CAST(823 AS NUMBER(10)),
      CAST(823 AS NUMBER(10)),
      CAST(NULL AS NUMBER(12)),
      inv.ABYS_TEDIYE_ACTION_ID,
      inv.ABYS_AGREEMENT_ID,
      inv.ABYS_ACCOUNT_ID,
      CAST('GUV_IADE' AS VARCHAR2(10))
  FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE inv
  WHERE NOT EXISTS (
    SELECT 1
      FROM SMS.CS_ACCOUNT_ACTION aa
      JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
     WHERE aa.ACCOUNT_ID = inv.ABYS_ACCOUNT_ID
       AND aa.ACTION_TYPE_ID IN (40, 11, 29)
       AND ai.INCOME_ID IN (
             162, 163, 164, 165, 1936, 3198, 3199,
             7649, 7650, 7651, 7652, 12531, 23032
           )
       AND ABS(ai.AMOUNT * ai.STATUS) > 0.02
  )
);

CREATE UNIQUE INDEX MIGRATION.IX_OV_GUV_IADE_IL
  ON MIGRATION.LS_OV_GUVENCE_IADE_INVLINES (SRC_KEY) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_GUV_IADE_IL_INV
  ON MIGRATION.LS_OV_GUVENCE_IADE_INVLINES (INVOICE_SRC_KEY) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_IL NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_IL_INV NOPARALLEL;
ALTER TABLE MIGRATION.LS_OV_GUVENCE_IADE_INVLINES NOPARALLEL LOGGING;

/* ---------------------------------------------------------------------------
   3) PAYTRANS — tediye / mahsuplasma alacak satiri
--------------------------------------------------------------------------- */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    CAST('GUV_IADE_PT|' || TO_CHAR(i.ABYS_ACCOUNT_ID) AS VARCHAR2(80)) AS SRC_KEY,
    i.SRC_KEY                                                    AS INVOICE_SRC_KEY,
    CAST(NULL AS NUMBER(12))                                     AS LREF_HINT,
    CAST(110 AS NUMBER(3))                                       AS TYPE,
    CAST(1 AS NUMBER(3))                                         AS IOCODE,          -- Alacak
    CAST(NULL AS NUMBER(12))                                     AS CROSSREF,
    CAST(174 AS NUMBER(10))                                      AS PAYTYPE,         -- Banka/PTT ailesi (IADE ile ayni)
    CAST(NVL(i.ABYS_ACTION_TYPE_ID, 40) AS NUMBER(10))           AS TRANSTYPE,       -- tip40/11/29
    CAST(103 AS NUMBER(10))                                      AS LINETYPE,
    CAST(0 AS NUMBER(10))                                        AS INST_NR,
    i.DATE_,
    i.PAYABLETOTAL,
    CAST(0 AS NUMBER(18,3))                                      AS PAID,
    CAST(0 AS NUMBER(1))                                         AS CANCELED,
    i.CLIENTREF,
    i.ABYS_ID,
    i.ABYS_ACCOUNT_ID,
    i.ABYS_AGREEMENT_ID,
    i.ABYS_TEDIYE_ACTION_ID,
    i.ABYS_MAIN_LREF,
    CAST('GUV_IADE' AS VARCHAR2(10))                             AS OV_KIND
FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE i;

CREATE UNIQUE INDEX MIGRATION.IX_OV_GUV_IADE_PT
  ON MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS (SRC_KEY) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_OV_GUV_IADE_PT_AGR
  ON MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS (ABYS_AGREEMENT_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_PT NOPARALLEL;
ALTER INDEX MIGRATION.IX_OV_GUV_IADE_PT_AGR NOPARALLEL;
ALTER TABLE MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS NOPARALLEL LOGGING;

/* ---------------------------------------------------------------------------
   4) ID_MAP append (O35 sonrasi kosulursa) / yoksa atla
   ORA-12838: FORCE PARALLEL DML + DELETE sonra ayni TX'de APPEND INSERT yasak.
   Bu blok seri DML; APPEND yok.
--------------------------------------------------------------------------- */
ALTER SESSION DISABLE PARALLEL DML;

DECLARE
  n_map NUMBER;
  n_dup NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_map FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_ID_MAP';
  IF n_map = 0 THEN
    DBMS_OUTPUT.PUT_LINE('O60 ID_MAP skip — LS_OV_ID_MAP yok (O35 once/sonra)');
    RETURN;
  END IF;

  DELETE FROM MIGRATION.LS_OV_ID_MAP
   WHERE OV_KIND IN ('GUV_IADE_INV', 'GUV_IADE_IL', 'GUV_IADE_PT');
  COMMIT;

  INSERT INTO MIGRATION.LS_OV_ID_MAP
    (OV_KIND, SRC_KEY, LREF_HINT, PARENT_SRC_KEY, REF_MAIN_LREF,
     ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, ABYS_ID_BUSINESS, ENERGY_LREF)
  SELECT CAST('GUV_IADE_INV' AS VARCHAR2(20)), SRC_KEY, LREF_HINT,
         CAST(NULL AS VARCHAR2(80)), ABYS_MAIN_LREF,
         ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID, ABYS_ID, CAST(NULL AS NUMBER(12))
    FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE
  UNION ALL
  SELECT 'GUV_IADE_IL', SRC_KEY, LREF_HINT, INVOICE_SRC_KEY,
         CAST(NULL AS NUMBER(12)), ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID,
         CAST(NULL AS NUMBER(12)), CAST(NULL AS NUMBER(12))
    FROM MIGRATION.LS_OV_GUVENCE_IADE_INVLINES
  UNION ALL
  SELECT 'GUV_IADE_PT', SRC_KEY, LREF_HINT, INVOICE_SRC_KEY,
         ABYS_MAIN_LREF, ABYS_AGREEMENT_ID, ABYS_ACCOUNT_ID,
         ABYS_ID, CAST(NULL AS NUMBER(12))
    FROM MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS;

  COMMIT;

  SELECT COUNT(*) INTO n_dup FROM MIGRATION.LS_OV_ID_MAP
   WHERE SRC_KEY IS NULL;
  IF n_dup > 0 THEN
    RAISE_APPLICATION_ERROR(-20060, 'O60 ID_MAP SRC_KEY NULL=' || n_dup);
  END IF;
END;
/

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'STG_GUV_IADE_PIVOT', degree => 40);
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'LS_OV_GUVENCE_IADE_INVOICE', degree => 40);
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'LS_OV_GUVENCE_IADE_INVLINES', degree => 40);
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'LS_OV_GUVENCE_IADE_PAYTRANS', degree => 40);
END;
/

/* diag */
SELECT 'GUV_IADE_INV' K, COUNT(*) N FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE
UNION ALL
SELECT 'GUV_IADE_IL', COUNT(*) FROM MIGRATION.LS_OV_GUVENCE_IADE_INVLINES
UNION ALL
SELECT 'GUV_IADE_PT', COUNT(*) FROM MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS
UNION ALL
SELECT 'PIVOT', COUNT(*) FROM MIGRATION.STG_GUV_IADE_PIVOT;

SELECT 'INV_NO_SRC' ISSUE, COUNT(*) N
  FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE WHERE SRC_KEY IS NULL
UNION ALL
SELECT 'IL_NO_SRC', COUNT(*)
  FROM MIGRATION.LS_OV_GUVENCE_IADE_INVLINES
 WHERE SRC_KEY IS NULL OR INVOICE_SRC_KEY IS NULL
UNION ALL
SELECT 'TEDIYE_TIP20_GAP', COUNT(*)
  FROM MIGRATION.STG_GUV_IADE_PIVOT
 WHERE ABS(ABS(NVL(TIP20,0)) - ABS(NVL(TIP12,0)) - ABS(NVL(TEDIYE,0))) > 0.05;

DECLARE
  n_inv NUMBER; n_il NUMBER; n_pt NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_inv FROM MIGRATION.LS_OV_GUVENCE_IADE_INVOICE;
  SELECT COUNT(*) INTO n_il  FROM MIGRATION.LS_OV_GUVENCE_IADE_INVLINES;
  SELECT COUNT(*) INTO n_pt  FROM MIGRATION.LS_OV_GUVENCE_IADE_PAYTRANS;
  MIGRATION.P_MIG_CTAS_LOG('O60', 'ls_ov_guvence_iade', 'OK', n_inv,
    'inv=' || n_inv || ' il=' || n_il || ' pt=' || n_pt || ' TYPE=110 SRC_KEY');
  DBMS_OUTPUT.PUT_LINE('========== O60 GUVENCE_IADE OK | inv=' || n_inv
    || ' il=' || n_il || ' pt=' || n_pt || ' ==========');
END;
/
