-- =====================================================================
-- LS_AGR_DEVICE  (Oracle staging - CTAS)
-- Kaynak : SMS.CS_AGREEMENT + II_PROJECT_* / II_APPOINTMENT_*
-- Hedef  : MIGRATION.LS_AGR_DEVICE  →  izgazMGR.dbo.LS_AGR_DEVICE
-- Pattern: hedef kolon isimleri birebir; ABYS_* bridge dahil
--
-- UYARI - F_GET_LAST_*:
--   Scalar PL/SQL satir basina cagrilir; PARALLEL CTAS fiilen
--   serilesebilir. Fonksiyonlar SMS. nitelikli tutuldu.
-- =====================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

-- TERMINAL DUMP: Oracle INDEX / GATHER_TABLE_STATS yok (CTAS zincirinde tuketilmiyor; IX -> izgazMGR/energy).

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_AGR_DEVICE PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE MIGRATION.LS_AGR_DEVICE
NOLOGGING
PARALLEL 56
AS
SELECT
    CASE PKL.PRM_ID
        WHEN 1704 THEN 73
        WHEN 344  THEN 2
        WHEN 347  THEN 4
        WHEN 358  THEN 3
        WHEN 364  THEN 8
        WHEN 371  THEN 1
        WHEN 378  THEN 14
        WHEN 379  THEN 22
        WHEN 382  THEN 7
        WHEN 386  THEN 13
        WHEN 389  THEN 83
        WHEN 392  THEN 99
        WHEN 395  THEN 31
        WHEN 396  THEN 72
        WHEN 398  THEN 111
        WHEN 399  THEN 74
        WHEN 405  THEN 11
        WHEN 409  THEN 6
        WHEN 412  THEN 16
        WHEN 414  THEN 93
        WHEN 417  THEN 21
        WHEN 418  THEN 90
        WHEN 421  THEN 78
        WHEN 428  THEN 32
        WHEN 429  THEN 29
        WHEN 432  THEN 5
        WHEN 438  THEN 27
        WHEN 444  THEN 119
        WHEN 451  THEN 112
        WHEN 435  THEN 125
        WHEN 453  THEN 66
        WHEN 1758 THEN 84
        WHEN 1786 THEN 103
        WHEN 1794 THEN 82
        WHEN 1797 THEN 52
        WHEN 1755 THEN 8
        ELSE 122
    END                                                     AS DEVID,
    agr.ID                                                  AS AGRID,
    PID.MIN_DEBIT                                           AS MIN_DEBIT,
    CAST(0 AS NUMBER(10))                                   AS WORKDAY,
    CAST(0 AS NUMBER(10))                                   AS WORKHOUR,
    CAST(0 AS NUMBER(10))                                   AS FEE,
    CAST(160 AS NUMBER(10))                                 AS EXCNR,
    CAST(0 AS NUMBER(1))                                    AS BLIND_PLUG,
    APP.UPDATED_TIMESTAMP                                   AS UPDDATE,
    APP.UPDATED_USER_ID                                     AS UPDUSER,
    CAST(1 AS NUMBER(1))                                    AS ISACTIVE,
    APP.CREATED_USER_ID                                     AS ADDUSER,
    APP.CREATED_TIMESTAMP                                   AS ADDDATE,
    PKL.PRM_ID                                              AS ABYS_DEV_ID,
    PKL.VALUE                                               AS ABYS_DEVICE_KIND,
    PRB.PROJECT_ID                                          AS ABYS_PROJECT_ID,
    agr.INSTALLATION_ID                                     AS ABYS_INSTALLATION_ID,
    DVM.CODE                                                AS ABYS_MARK_CODE,
    DVM.VALUE                                               AS ABYS_MARK_VALUE
FROM SMS.CS_AGREEMENT agr
JOIN SMS.CS_INSTALLATION INS
    ON agr.INSTALLATION_ID = INS.ID
JOIN SMS.II_PROJECT_INSTALLATION_DEVICE PID
    ON PID.PROJECT_INSTALLATION_ID = SMS.F_GET_LAST_PRJ_INSTALLATION(INS.ID)
JOIN SMS.II_PROJECT_INSTALLATION PRI
    ON PRI.ID = PID.PROJECT_INSTALLATION_ID
JOIN SMS.II_PROJECT_BUILDING PRB
    ON PRB.ID = PRI.PROJECT_BUILDING_ID
JOIN SMS.II_PROJECT PRJ
    ON PRJ.ID = PRB.PROJECT_ID
LEFT JOIN SMS.II_APPOINTMENT APP
    ON APP.ID = SMS.F_GET_LAST_APPOINTMENT(INS.ID)
LEFT JOIN SMS.II_APPOINTMENT_DEVICE APD
    ON APD.APPOINTMENT_ID = APP.ID
   AND APD.PROJECT_INSTALLATION_DEVICE_ID = PID.ID
LEFT JOIN SMS.II_DEVICE_TYPE_PRM DVT
    ON DVT.ID = PID.DEVICE_TYPE_ID
LEFT JOIN SMS.II_DEVICE_TYPE_PRM_LNG PDL
    ON DVT.ID = PDL.PRM_ID
   AND PDL.LANG_ID = 1
LEFT JOIN SMS.II_DEVICE_TYPE_PRM_LNG PKL
    ON DVT.PARENT_ID = PKL.PRM_ID
   AND PKL.LANG_ID = 1
LEFT JOIN SMS.II_DEVICE_MARK_PRM DVM
    ON DVM.ID = APD.DEVICE_MARK_ID
LEFT JOIN SMS.CS_AGREEMENT_DEVICE AAD
    ON AAD.APPOINTMENT_DEVICE_ID = APD.ID
;

ALTER TABLE MIGRATION.LS_AGR_DEVICE NOPARALLEL LOGGING;


-- dogrulama
SELECT 'CS_AGREEMENT' KAYNAK, COUNT(*) CNT FROM SMS.CS_AGREEMENT
UNION ALL
SELECT 'LS_AGR_DEVICE', COUNT(*) FROM MIGRATION.LS_AGR_DEVICE
UNION ALL
SELECT 'DEVID_UNMAPPED', COUNT(*) FROM MIGRATION.LS_AGR_DEVICE WHERE DEVID = 122;
