-- =====================================================================
-- LS_INSTALLMENT  (Oracle staging - CTAS)
-- Kaynak : SMS.CS_INSTALLMENT
-- Hedef  : MIGRATION.LS_INSTALLMENT  →  izgazMGR.dbo.LS_INSTALLMENT
-- Pattern: kaynak kolon isimleri birebir; ABYS_ID = ID bridge
-- =====================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_INSTALLMENT PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE MIGRATION.LS_INSTALLMENT
NOLOGGING
PARALLEL 56
AS
SELECT
    i.ID                                                    AS ID,
    i.ID                                                    AS ABYS_ID,
    i.INSTALLMENT_TYPE_ID                                   AS INSTALLMENT_TYPE_ID,
    i.AREA_ID                                               AS AREA_ID,
    i.AGREEMENT_ID                                          AS AGREEMENT_ID,
    i.REGISTER_ID                                           AS REGISTER_ID,
    i.INSTALLATION_ID                                       AS INSTALLATION_ID,
    i.PERIOD                                                AS PERIOD,
    i.INSTALLMENT_DATE                                      AS INSTALLMENT_DATE,
    i.INSTALLMENT_NUMBER                                    AS INSTALLMENT_NUMBER,
    i.EXPIRY_DAY                                            AS EXPIRY_DAY,
    i.TOTAL_AMOUNT                                          AS TOTAL_AMOUNT,
    i.OPTIONAL_AMOUNT                                       AS OPTIONAL_AMOUNT,
    i.MONTHLY_AMOUNT                                        AS MONTHLY_AMOUNT,
    i.DUE_DATE                                              AS DUE_DATE,
    i.CANCEL_CAUSE_ID                                       AS CANCEL_CAUSE_ID,
    i.CANCELLATION_DATE                                     AS CANCELLATION_DATE,
    i.CANCELLATION_USER_ID                                  AS CANCELLATION_USER_ID,
    i.LEGAL_PROCEEDING_ID                                   AS LEGAL_PROCEEDING_ID,
    i.ACTUAL_REGISTER_ID                                    AS ACTUAL_REGISTER_ID,
    i.CUSTOM_LATE_RATE                                      AS CUSTOM_LATE_RATE,
    i.CREATED_USER_ID                                       AS CREATED_USER_ID,
    CAST(i.CREATED_TIMESTAMP AS TIMESTAMP)                  AS CREATED_TIMESTAMP,
    i.UPDATED_USER_ID                                       AS UPDATED_USER_ID,
    CAST(i.UPDATED_TIMESTAMP AS TIMESTAMP)                  AS UPDATED_TIMESTAMP,
    i.VERSION                                               AS VERSION,
    i.STAMP_COUNT                                           AS STAMP_COUNT,
    i.TEFE_MI_                                              AS TEFE_MI_,
    i.TAKSIT_AFFI_                                          AS TAKSIT_AFFI_,
    i.TAKSIT_ID_                                            AS TAKSIT_ID_,
    i.EVRAK_NO_                                             AS EVRAK_NO_,
    i.TAKSIT_TURU_                                          AS TAKSIT_TURU_,
    i.FIRST_INSTALLMENT_AMOUNT                              AS FIRST_INSTALLMENT_AMOUNT,
    i.IHBARNAME_MAKBUZ_NO_                                  AS IHBARNAME_MAKBUZ_NO_,
    i.FATURA_NUMARASI_                                      AS FATURA_NUMARASI_,
    i.SOZLESME_NUMARASI_                                    AS SOZLESME_NUMARASI_,
    i.FATURA_TARIHI_                                        AS FATURA_TARIHI_,
    i.TURU_                                                 AS TURU_,
    i.CANCEL_DESCRIPTION                                    AS CANCEL_DESCRIPTION,
    i.DESCRIPTION                                           AS DESCRIPTION,
    i.INSTALLMENT_TOTAL_AMOUNT                              AS INSTALLMENT_TOTAL_AMOUNT
FROM SMS.CS_INSTALLMENT i
;

ALTER TABLE MIGRATION.LS_INSTALLMENT NOPARALLEL LOGGING;

CREATE UNIQUE INDEX MIGRATION.UX_LS_INST_ID
    ON MIGRATION.LS_INSTALLMENT (ID) NOLOGGING PARALLEL 4;

CREATE UNIQUE INDEX MIGRATION.UX_LS_INST_ABYS_ID
    ON MIGRATION.LS_INSTALLMENT (ABYS_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_INST_AGR
    ON MIGRATION.LS_INSTALLMENT (AGREEMENT_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_INST_REG
    ON MIGRATION.LS_INSTALLMENT (REGISTER_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_INST_INS
    ON MIGRATION.LS_INSTALLMENT (INSTALLATION_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_INST_TYPE
    ON MIGRATION.LS_INSTALLMENT (INSTALLMENT_TYPE_ID) NOLOGGING PARALLEL 4;

CREATE INDEX MIGRATION.IDX_LS_INST_CANCEL
    ON MIGRATION.LS_INSTALLMENT (CANCELLATION_DATE, LEGAL_PROCEEDING_ID) NOLOGGING PARALLEL 4;

ALTER INDEX MIGRATION.UX_LS_INST_ID      NOPARALLEL;
ALTER INDEX MIGRATION.UX_LS_INST_ABYS_ID NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_INST_AGR     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_INST_REG     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_INST_INS     NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_INST_TYPE    NOPARALLEL;
ALTER INDEX MIGRATION.IDX_LS_INST_CANCEL  NOPARALLEL;

BEGIN
  DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'LS_INSTALLMENT', cascade => TRUE, degree => 4);
END;
/

-- dogrulama
SELECT 'CS_INSTALLMENT' KAYNAK, COUNT(*) CNT FROM SMS.CS_INSTALLMENT
UNION ALL
SELECT 'LS_INSTALLMENT', COUNT(*) FROM MIGRATION.LS_INSTALLMENT
UNION ALL
SELECT 'LS_INSTALLMENT_ACTIVE', COUNT(*) FROM MIGRATION.LS_INSTALLMENT WHERE CANCELLATION_DATE IS NULL
UNION ALL
SELECT 'LS_INSTALLMENT_CANCELLED', COUNT(*) FROM MIGRATION.LS_INSTALLMENT WHERE CANCELLATION_DATE IS NOT NULL;
