using Oracle.ManagedDataAccess.Client;

const string connStr = "User Id=SMS;Password=sms;Data Source=10.32.67.200:1521/test;";
var scriptPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "izgaz_pilot_ctas_v09.sql"));

if (!File.Exists(scriptPath))
    scriptPath = @"c:\Users\HW5536\source\repos\Migratorv0\sql\IZGAZ2PCMS\IZGAZ2PCMS\oracleControl\izgaz_pilot_ctas_v09.sql";

if (!File.Exists(scriptPath))
    scriptPath = @"c:\Users\HW5536\source\repos\Migratorv0\sql\IZGAZ2PCMS\IZGAZ2PCMS\oracleControl\izgaz_pilot_ctas_v08.sql";

var mode = args.Length > 0 ? args[0].ToLowerInvariant() : "pilot";

if (mode == "pilot")
{
    await OracleSqlRunner.RunFileAsync(connStr, scriptPath, saveAdapted: true);
}
else if (mode == "recon")
{
    var adapted = OracleSqlRunner.AdaptForSmsAudit(await File.ReadAllTextAsync(scriptPath));
    var start = adapted.IndexOf("-- (C1) PROBLEMATIC_CUSTODY", StringComparison.Ordinal);
    var section15 = adapted.IndexOf("-- 15. V_REF_CHAIN", StringComparison.Ordinal);
    var end = adapted.LastIndexOf("COMMIT;", section15 > 0 ? section15 : adapted.Length - 1, StringComparison.Ordinal);
    if (end < start) end = section15;
    else end += "COMMIT;".Length;
    if (start < 0 || end < 0) throw new InvalidOperationException("Recon section not found");
    var reconSql = "DELETE FROM SMS_AUDIT.STG_RECON_DIFF;\nCOMMIT;\n" + adapted[start..end];
    var tmp = Path.Combine(Path.GetTempPath(), "izgaz_recon_only.sql");
    await File.WriteAllTextAsync(tmp, reconSql);
    await OracleSqlRunner.RunFileAsync(connStr, tmp, saveAdapted: false);
    await RunDiagnostics(connStr);
}
else if (mode == "investigate")
{
    await Investigate18031386(connStr);
}
else if (mode == "investigate-dup")
{
    await InvestigateDuplicate197168(connStr);
}
else if (mode == "diag")
{
    await RunDiagnostics(connStr);
}
else if (mode == "compare-197168")
{
    await CompareAbys197168(connStr);
}
else if (mode == "account-15640062")
{
    await InvestigateAccount15640062(connStr);
}
else if (mode == "compare-acik-fatura")
{
    await CompareAcikFatura197168(connStr);
}
else if (mode == "account-570480")
{
    await InvestigateAccount570480(connStr);
}
else if (mode == "dup-570480")
{
    await ExplainDuplicate570480(connStr);
}
else if (mode == "account-11881154")
{
    await InvestigateAccount11881154(connStr);
}
else if (mode == "account-51407277")
{
    await InvestigateAccount51407277(connStr);
}
else if (mode == "account-11091398")
{
    await InvestigateAccount11091398(connStr);
}
else if (mode == "fix-cov-r40")
{
    await FixCoverageR40(connStr);
}
else if (mode == "schema")
{
    await SchemaProbe(connStr);
}
else
{
    Console.WriteLine("Usage: OracleProbe [pilot|recon|diag|investigate|investigate-dup|compare-197168|compare-acik-fatura|account-15640062|account-570480|account-11881154|account-51407277|account-11091398|dup-570480|fix-cov-r40|schema]");
}

static async Task InvestigateDuplicate197168(string connStr)
{
    const long agrId = 197168;
    const long dupAction = 109510543;
    const long lostAction = 63338506;

    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();

    async Task Q(string title, string sql, int max = 50)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(r.GetName)));
        var n = 0;
        while (await r.ReadAsync())
        {
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
            if (++n >= max) break;
        }
        if (n == 0) Console.WriteLine("(no rows)");
    }

    await Q("DUPLICATE COVERAGE (197168)", $@"
SELECT C.SRC_INCOME_ID, C.SRC_ACTION_ID, C.INCOME_ID, C.SRC_AMOUNT, C.TOTAL_TARGETS, C.DESTINATION,
       C.ACT_CLASS
  FROM SMS_AUDIT.STG_INCOME_COVERAGE C
 WHERE C.AGREEMENT_ID = {agrId} AND C.DESTINATION = 'DUPLICATE'
 ORDER BY C.SRC_ACTION_ID, C.SRC_INCOME_ID");

    await Q("LOST COVERAGE (197168)", $@"
SELECT C.SRC_INCOME_ID, C.SRC_ACTION_ID, C.INCOME_ID, C.SRC_AMOUNT, C.TOTAL_TARGETS, C.ACT_CLASS
  FROM SMS_AUDIT.STG_INCOME_COVERAGE C
 WHERE C.AGREEMENT_ID = {agrId} AND C.DESTINATION = 'LOST'
 ORDER BY C.SRC_INCOME_ID");

    await Q($"ACTION {dupAction} KAYNAK", $@"
SELECT X.ID, X.ACCOUNT_ID, A.AGREEMENT_ID, X.ACTION_TYPE_ID, T.TYPE ACTION_CLASS, T.STATUS,
       TO_CHAR(X.ACTION_DATE,'YYYY-MM-DD') DT
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT A ON A.ID = X.ACCOUNT_ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID = X.ACTION_TYPE_ID
 WHERE X.ID = {dupAction}");

    await Q("INSTALLMENT kolonlari (ACTION)", @"
SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS
 WHERE OWNER='SMS' AND TABLE_NAME='CS_ACCOUNT_ACTION'
   AND UPPER(COLUMN_NAME) LIKE '%INSTALL%'
 ORDER BY COLUMN_ID");

    await Q($"ACTION {dupAction} INCOME", $@"
SELECT I.ID INCOME_ROW_ID, I.INCOME_ID, I.AMOUNT, T.STATUS, I.AMOUNT*T.STATUS NET
  FROM SMS.CS_ACCOUNT_INCOME I
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID = I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID = X.ACTION_TYPE_ID
 WHERE X.ID = {dupAction}
 ORDER BY I.ID");

    await Q("HEDEF DAGILIMI (dup incomes)", $@"
SELECT C.SRC_INCOME_ID,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVLINES IL
         WHERE IL.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1) C_IL,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI
         WHERE PI.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID) C_PI,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_SPEFEE SP
         WHERE SP.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID) C_SP,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_ADV_LEDGER_INCOME LG
         WHERE LG.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID) C_LG,
       (SELECT COUNT(*) FROM SMS_AUDIT.MIG_SKIPPED SK
         WHERE SK.ACTION_ID=C.SRC_ACTION_ID) C_SKIP,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_CANCEL_POOL CP
         WHERE CP.SOURCE_ORACLE_ACTION_ID=C.SRC_ACTION_ID) C_CANC
  FROM SMS_AUDIT.STG_INCOME_COVERAGE C
 WHERE C.AGREEMENT_ID={agrId} AND C.DESTINATION='DUPLICATE'
 ORDER BY C.SRC_INCOME_ID");

    await Q("CS_INSTALLMENT_PLAN kolonlari", @"
SELECT COLUMN_NAME, DATA_TYPE FROM ALL_TAB_COLUMNS
 WHERE OWNER='SMS' AND TABLE_NAME='CS_INSTALLMENT_PLAN'
 ORDER BY COLUMN_ID");

    await Q("INSTALLMENT_PLAN (action INSTALLMENT_ID)", $@"
SELECT X.ID ACTION_ID, X.INSTALLMENT_ID, X.INSTALLMENT_ORDER_NUMBER, X.CREDIT_INSTALLMENT_NUMBER,
       IP.ID PLAN_ROW_ID, IP.ORDER_NUMBER, IP.AMOUNT, TO_CHAR(IP.DUE_DATE,'YYYY-MM-DD') DUE_DT,
       TO_CHAR(IP.PAYMENT_DATE,'YYYY-MM-DD') PAY_DT
  FROM SMS.CS_ACCOUNT_ACTION X
  LEFT JOIN SMS.CS_INSTALLMENT_PLAN IP ON IP.INSTALLMENT_ID = X.INSTALLMENT_ID
      AND IP.ORDER_NUMBER = X.INSTALLMENT_ORDER_NUMBER
 WHERE X.ID = {dupAction}");

    await Q("SOZLESME TAKSIT (INSTALLMENT master)", $@"
SELECT INS.ID, INS.AGREEMENT_ID FROM SMS.CS_INSTALLMENT INS
 WHERE INS.AGREEMENT_ID = {agrId} AND ROWNUM <= 10");

    await Q($"ACTION {lostAction} KAYNAK + ROUTE", $@"
SELECT X.ID, X.ACTION_TYPE_ID, T.TYPE ACT_CLASS, X.ACCOUNT_ID,
       I.ID INCOME_ROW_ID, I.INCOME_ID, I.AMOUNT, R.ACCRUAL_DEST
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID = X.ACTION_TYPE_ID
  LEFT JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID = X.ID
  LEFT JOIN SMS_AUDIT.STG_INCOME_ROUTE R ON R.INCOME_ID = I.INCOME_ID
 WHERE X.ID = {lostAction}");

    await Q($"LOST {lostAction} STAGING ARAMA", $@"
SELECT 'INVLINES' T, COUNT(*) C FROM SMS_AUDIT.STG_INVLINES
 WHERE SOURCE_ORACLE_ACTION_ID={lostAction}
UNION ALL SELECT 'SPEFEE', COUNT(*) FROM SMS_AUDIT.STG_SPEFEE WHERE SOURCE_ORACLE_ACTION_ID={lostAction}
UNION ALL SELECT 'PAYTRANS_INCOME', COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS_INCOME WHERE SOURCE_ORACLE_ACTION_ID={lostAction}
UNION ALL SELECT 'INVOICE', COUNT(*) FROM SMS_AUDIT.STG_INVOICE WHERE SOURCE_ORACLE_ACTION_ID={lostAction}
UNION ALL SELECT 'CANCEL_POOL', COUNT(*) FROM SMS_AUDIT.STG_CANCEL_POOL WHERE SOURCE_ORACLE_ACTION_ID={lostAction}");

    await Q("TAKSIT ODEME ACTION TIPLERI (197168)", $@"
SELECT X.ACTION_TYPE_ID, T.TYPE, COUNT(*) ADET
  FROM SMS_AUDIT.STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID = A.ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID = X.ACTION_TYPE_ID
 WHERE A.AGREEMENT_ID = {agrId} AND T.TYPE = 2
 GROUP BY X.ACTION_TYPE_ID, T.TYPE
 ORDER BY ADET DESC");

    await Q("CANCEL ACTION 109510543 POOL/SKIP", $@"
SELECT 'MIG_SKIPPED' T, ACTION_ID, ACTION_TYPE, SEBEP FROM SMS_AUDIT.MIG_SKIPPED WHERE ACTION_ID={dupAction}
UNION ALL
SELECT 'CANCEL_POOL', SOURCE_ORACLE_ACTION_ID, REVERSAL_TYPE, TO_CHAR(GRANDTOTAL)
  FROM SMS_AUDIT.STG_CANCEL_POOL WHERE SOURCE_ORACLE_ACTION_ID={dupAction}");
}

static async Task Investigate18031386(string connStr)
{
    const long accId = 18031386;
    const long borcPt = 25004895;

    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();

    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(r.GetName)));
        var n = 0;
        while (await r.ReadAsync())
        {
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
            if (++n >= 40) break;
        }
        if (n == 0) Console.WriteLine("(no rows)");
    }

    await Q("KAYNAK INCOME (action 25004895)", $@"
SELECT I.ID, I.INCOME_ID, I.AMOUNT, M.STATUS, I.AMOUNT*M.STATUS NET, R.ACCRUAL_DEST
  FROM SMS.CS_ACCOUNT_INCOME I
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID = I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID = X.ACTION_TYPE_ID
  LEFT JOIN SMS_AUDIT.STG_INCOME_ROUTE R ON R.INCOME_ID = I.INCOME_ID
 WHERE X.ID = {borcPt} ORDER BY I.INCOME_ID");

    await Q("958/1929 KAYNAK", $@"
SELECT I.INCOME_ID, I.AMOUNT SRC_AMT, ABS(I.AMOUNT) ABS_AMT, I.AMOUNT*M.STATUS NET
  FROM SMS.CS_ACCOUNT_INCOME I
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID = I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID = X.ACTION_TYPE_ID
 WHERE X.ID = {borcPt} AND I.INCOME_ID IN (958,1929)");

    await Q("STG INVLINES + SPEFEE", $@"
SELECT 'INVLINES' T, TRANSTYPE INCOME_ID, AMOUNT FROM SMS_AUDIT.STG_INVLINES
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID<>-1
UNION ALL SELECT 'SPEFEE', SRC_INCOME_ID, GRANDTOTAL FROM SMS_AUDIT.STG_SPEFEE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} ORDER BY 1,2");

    await Q("STG BORC PT + BAGLI ODEME", $@"
SELECT LREF, PT_KIND, PAYABLETOTAL, PAID, CROSSREF, TO_CHAR(DATE_,'YYYY-MM-DD') DT
  FROM SMS_AUDIT.STG_PAYTRANS
 WHERE LREF={borcPt} OR (CROSSREF={borcPt} AND PT_KIND='PAYMENT')");

    await Q("ODEME INCOME KIRILIMI (CROSSREF={borcPt})", $@"
SELECT PI.SOURCE_ORACLE_ACTION_ID PAY_ACT, PI.SRC_INCOME_ID, PI.INCOME_AMOUNT,
       I.AMOUNT SRC_RAW, I.AMOUNT*M.STATUS SRC_NET
  FROM SMS_AUDIT.STG_PAYTRANS P
  JOIN SMS_AUDIT.STG_PAYTRANS_INCOME PI ON PI.PAYTRANSREF = P.LREF
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ID = PI.SOURCE_ORACLE_INCOME_ID
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID = I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID = X.ACTION_TYPE_ID
 WHERE P.CROSSREF = {borcPt} AND P.PT_KIND='PAYMENT'
 ORDER BY PI.SRC_INCOME_ID");

    await Q("TUTAR OZET", $@"
SELECT 'KAYNAK_NET' K, SUM(I.AMOUNT*M.STATUS) V FROM SMS.CS_ACCOUNT_INCOME I
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID=I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID=X.ACTION_TYPE_ID WHERE X.ID={borcPt}
UNION ALL SELECT 'INVLINES', SUM(AMOUNT) FROM SMS_AUDIT.STG_INVLINES
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID<>-1
UNION ALL SELECT 'SPEFEE_958', SUM(GRANDTOTAL) FROM SMS_AUDIT.STG_SPEFEE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID=958
UNION ALL SELECT 'SPEFEE_1929', SUM(GRANDTOTAL) FROM SMS_AUDIT.STG_SPEFEE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID=1929
UNION ALL SELECT 'INVOICE_GRAND', MAX(GRANDTOTAL) FROM SMS_AUDIT.STG_INVOICE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt}
UNION ALL SELECT 'PT_PAYABLE', MAX(PAYABLETOTAL) FROM SMS_AUDIT.STG_PAYTRANS WHERE LREF={borcPt}
UNION ALL SELECT 'PAID', SUM(PAYABLETOTAL) FROM SMS_AUDIT.STG_PAYTRANS
 WHERE CROSSREF={borcPt} AND PT_KIND='PAYMENT'
UNION ALL SELECT 'DEVIR_NET_KAYNAK', SUM(I.AMOUNT*M.STATUS) FROM SMS.CS_ACCOUNT_INCOME I
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID=I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID=X.ACTION_TYPE_ID
 WHERE X.ID={borcPt} AND I.INCOME_ID IN (958,1929)
UNION ALL SELECT 'DEVIR_ABS_STG', NVL((SELECT SUM(GRANDTOTAL) FROM SMS_AUDIT.STG_SPEFEE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID=958),0)
 - NVL((SELECT SUM(GRANDTOTAL) FROM SMS_AUDIT.STG_SPEFEE
 WHERE SOURCE_ORACLE_ACTION_ID={borcPt} AND SRC_INCOME_ID=1929),0)
 FROM DUAL");
}

static async Task RunDiagnostics(string connStr)
{
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();

    var queries = new (string Label, string Sql)[]
    {
        ("R0 RECON SUMMARY", @"
            SELECT SEVERITY, KATEGORI, COUNT(*) SATIR,
                   SUM(NVL(FARK, NVL(KAYNAK_NET, STAGING_NET))) TUTAR
              FROM SMS_AUDIT.STG_RECON_DIFF
             WHERE IGNORED = 0
             GROUP BY SEVERITY, KATEGORI
             ORDER BY DECODE(SEVERITY,'CRITICAL',1,'WARN',2,'INFO',3), SATIR DESC"),
        ("R1 CRITICAL DETAIL", @"
            SELECT AGREEMENT_ID, KATEGORI, KAYNAK_NET, STAGING_NET, FARK, SEBEP
              FROM SMS_AUDIT.STG_RECON_DIFF
             WHERE SEVERITY = 'CRITICAL' AND IGNORED = 0
             ORDER BY AGREEMENT_ID, KATEGORI"),
        ("PAID_OVERFLOW DETAIL", @"
            SELECT R.AGREEMENT_ID, R.SOURCE_ORACLE_ACCOUNT_ID, R.SUSPECT_ACTION_IDS BORC_PT,
                   R.KAYNAK_NET PAYABLE, R.STAGING_NET PAID, R.FARK
              FROM SMS_AUDIT.STG_RECON_DIFF R
             WHERE R.KATEGORI = 'PAID_OVERFLOW' AND R.IGNORED = 0"),
        ("R2 YAPISAL BUTUNLUK", @"
            SELECT DESTINATION, COUNT(*) SATIR, SUM(SRC_AMOUNT) TUTAR
              FROM SMS_AUDIT.STG_INCOME_COVERAGE
             GROUP BY DESTINATION"),
        ("DEBT ODEME_ADET>1", @"
            SELECT A.AGREEMENT_ID, P.SOURCE_ORACLE_ACCOUNT_ID, P.LREF BORC_PT,
                   P.PAYABLETOTAL, P.PAID, P.PAYABLETOTAL - P.PAID FARK,
                   (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS C
                     WHERE C.CROSSREF = P.LREF AND C.PT_KIND = 'PAYMENT') ODEME_ADET
              FROM SMS_AUDIT.STG_PAYTRANS P
              JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID = P.SOURCE_ORACLE_ACCOUNT_ID
             WHERE P.PT_KIND = 'ACCRUE' AND ABS(P.PAYABLETOTAL - P.PAID) > 0.01
             ORDER BY A.AGREEMENT_ID, FARK"),
        ("R5 KAPSAMA", @"
            SELECT 'KAPSAMA' K,
                   (SELECT COUNT(*) FROM SMS_AUDIT.STG_INCOME_COVERAGE)||'/'||
                   (SELECT COUNT(*) FROM SMS_AUDIT.STG_PILOT_ACC A
                      JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID = A.ID
                      JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID = X.ID) V
              FROM DUAL")
    };

    foreach (var (label, sql) in queries)
    {
        Console.WriteLine($"\n=== {label} ===");
        await using var cmd = new OracleCommand(sql, conn) { BindByName = true };
        await using var reader = await cmd.ExecuteReaderAsync();
        var cols = Enumerable.Range(0, reader.FieldCount).Select(reader.GetName);
        Console.WriteLine(string.Join(" | ", cols));
        while (await reader.ReadAsync())
        {
            var vals = Enumerable.Range(0, reader.FieldCount)
                .Select(i => reader.IsDBNull(i) ? "NULL" : Convert.ToString(reader.GetValue(i)));
            Console.WriteLine(string.Join(" | ", vals));
        }
    }
}

static async Task CompareAbys197168(string connStr)
{
    const long agrId = 197168;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();

    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(r.GetName)));
        var n = 0;
        while (await r.ReadAsync())
        {
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
            if (++n >= 80) break;
        }
        if (n == 0) Console.WriteLine("(no rows)");
    }

    await Q("ABYS HEDEF vs STAGING OZET", $@"
WITH ABYS AS (
  SELECT 4 GECIKMIS_BORC_ADET, 26019.38 TOPLAM_BORC, 170 GECIKMIS_ODENEN,
         0 EMANET_ADET, 0 EMANET_TUTAR, 246 DEPOZITO, 0 TEMINAT,
         263 FATURA_ADET, 258 ODENMIS_FATURA FROM DUAL
),
STG AS (
  SELECT
    (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS P
      JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
     WHERE A.AGREEMENT_ID={agrId} AND P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0
       AND P.PAYABLETOTAL-P.PAID>0.01) OPEN_DEBT_CNT,
    (SELECT SUM(P.PAYABLETOTAL-P.PAID) FROM SMS_AUDIT.STG_PAYTRANS P
      JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
     WHERE A.AGREEMENT_ID={agrId} AND P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0
       AND P.PAYABLETOTAL-P.PAID>0.01) OPEN_DEBT_SUM,
    (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVOICE I
      JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=I.SOURCE_ORACLE_ACCOUNT_ID
     WHERE A.AGREEMENT_ID={agrId} AND I.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN')) FATURA_CNT,
    (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVOICE I
      JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=I.SOURCE_ORACLE_ACCOUNT_ID
     WHERE A.AGREEMENT_ID={agrId} AND I.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN') AND NVL(I.CLOSED,0)=1) ODENMIS_CNT,
    (SELECT SUM(I.AMOUNT*M.STATUS) FROM SMS_AUDIT.STG_PILOT_ACC A
      JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
      JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
      JOIN SMS_AUDIT.STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
     WHERE A.AGREEMENT_ID={agrId} AND A.ACCRUE_TYPE_ID<>14) DEBT_NET,
    (SELECT SUM(I.AMOUNT*M.STATUS) FROM SMS_AUDIT.STG_PILOT_ACC A
      JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
      JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
      JOIN SMS_AUDIT.STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
     WHERE A.AGREEMENT_ID={agrId} AND A.ACCRUE_TYPE_ID=14) CUSTODY_NET
  FROM DUAL
)
SELECT 'Gecikmis borc adedi' METRIK, TO_CHAR(ABYS.GECIKMIS_BORC_ADET) ABYS, TO_CHAR(S.OPEN_DEBT_CNT) STAGING,
       TO_CHAR(S.OPEN_DEBT_CNT-ABYS.GECIKMIS_BORC_ADET) FARK FROM ABYS, STG S
UNION ALL SELECT 'Toplam Borc', TO_CHAR(ABYS.TOPLAM_BORC), TO_CHAR(S.OPEN_DEBT_SUM), TO_CHAR(S.OPEN_DEBT_SUM-ABYS.TOPLAM_BORC) FROM ABYS, STG S
UNION ALL SELECT 'Fatura Adet', TO_CHAR(ABYS.FATURA_ADET), TO_CHAR(S.FATURA_CNT), TO_CHAR(S.FATURA_CNT-ABYS.FATURA_ADET) FROM ABYS, STG S
UNION ALL SELECT 'Odenmis Fatura', TO_CHAR(ABYS.ODENMIS_FATURA), TO_CHAR(S.ODENMIS_CNT), TO_CHAR(S.ODENMIS_CNT-ABYS.ODENMIS_FATURA) FROM ABYS, STG S
UNION ALL SELECT 'Debt Net (kaynak)', NULL, TO_CHAR(S.DEBT_NET), NULL FROM STG S
UNION ALL SELECT 'Custody Net', TO_CHAR(ABYS.EMANET_TUTAR), TO_CHAR(S.CUSTODY_NET), TO_CHAR(S.CUSTODY_NET-ABYS.EMANET_TUTAR) FROM ABYS, STG S");

    await Q("KAYNAK ABYS DEBT_NET + TOPLAM_BORC", $@"
SELECT A.AGREEMENT_ID,
       SUM(CASE WHEN M.STATUS=1 THEN ABS(I.AMOUNT) ELSE 0 END) TOPLAM_BORC_ABS,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID<>14 THEN I.AMOUNT*M.STATUS ELSE 0 END) DEBT_NET,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID=14 THEN I.AMOUNT*M.STATUS ELSE 0 END) CUSTODY_NET,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID IN (5,6) THEN I.AMOUNT*M.STATUS ELSE 0 END) DEPO_NET
  FROM SMS_AUDIT.STG_PILOT_ACC A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN SMS_AUDIT.STG_ACTION_MAP M ON M.ACTION_TYPE_ID=X.ACTION_TYPE_ID
 WHERE A.AGREEMENT_ID={agrId}
 GROUP BY A.AGREEMENT_ID");

    await Q("STG INVOICE BY KIND", $@"
SELECT I.INV_KIND, COUNT(*) ADET, SUM(I.GRANDTOTAL) TUTAR,
       SUM(CASE WHEN NVL(I.CLOSED,0)=1 THEN 1 ELSE 0 END) CLOSED_CNT
  FROM SMS_AUDIT.STG_INVOICE I
  JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=I.SOURCE_ORACLE_ACCOUNT_ID
 WHERE A.AGREEMENT_ID={agrId}
 GROUP BY I.INV_KIND ORDER BY 2 DESC");

    await Q("ACCRUE PT OPEN BALANCE", $@"
SELECT P.LREF, P.PAYABLETOTAL, P.PAID, P.PAYABLETOTAL-P.PAID KALAN, P.INVOICEREF,
       TO_CHAR(P.DATE_,'YYYY-MM-DD') DT, NVL(P.CANCELED,0) CANC
  FROM SMS_AUDIT.STG_PAYTRANS P
  JOIN SMS_AUDIT.STG_PILOT_ACC A ON A.ID=P.SOURCE_ORACLE_ACCOUNT_ID
 WHERE A.AGREEMENT_ID={agrId} AND P.PT_KIND='ACCRUE'
   AND ABS(P.PAYABLETOTAL-P.PAID)>0.01
 ORDER BY P.PAYABLETOTAL-P.PAID DESC");

    await Q("RECON 197168", $@"
SELECT SEVERITY, KATEGORI, KAYNAK_NET, STAGING_NET, FARK, SEBEP
  FROM SMS_AUDIT.STG_RECON_DIFF
 WHERE AGREEMENT_ID={agrId} AND NVL(IGNORED,0)=0
 ORDER BY DECODE(SEVERITY,'CRITICAL',1,'WARN',2,'INFO',3), KATEGORI");
}

static async Task InvestigateAccount15640062(string connStr)
{
    const long accId = 15640062;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();

    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(r.GetName)));
        var n = 0;
        while (await r.ReadAsync())
        {
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
            if (++n >= 40) break;
        }
        if (n == 0) Console.WriteLine("(no rows)");
    }

    await Q("HESAP", $@"
SELECT A.ID, A.AGREEMENT_ID, A.PERIOD, A.ACCRUE_TYPE_ID, A.TOTAL_DEBT, A.TOTAL_CREDIT
  FROM SMS.CS_ACCOUNT A WHERE A.ID={accId}");

    await Q("KAYNAK ACTION + INCOME", $@"
SELECT X.ID ACTION_ID, X.ACTION_TYPE_ID, T.TYPE ACT_CLASS, T.STATUS,
       TO_CHAR(X.ACTION_DATE,'YYYY-MM-DD HH24:MI') DT,
       I.ID INCOME_ROW_ID, I.INCOME_ID, I.AMOUNT RAW_AMT,
       I.AMOUNT*T.STATUS NET, IP.CODE, IPL.VALUE
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  LEFT JOIN SMS.CS_INCOME_PRM IP ON IP.ID=I.INCOME_ID
  LEFT JOIN SMS.CS_INCOME_PRM_LNG IPL ON IPL.PRM_ID=IP.ID AND IPL.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID, I.INCOME_ID");

    await Q("KAYNAK TUTAR OZET", $@"
SELECT X.ID ACTION_ID, T.TYPE, T.STATUS,
       SUM(I.AMOUNT) SUM_RAW, SUM(I.AMOUNT*T.STATUS) SUM_NET,
       SUM(ABS(I.AMOUNT)) SUM_ABS,
       SUM(CASE WHEN I.INCOME_ID=958 THEN ABS(I.AMOUNT)
                WHEN I.INCOME_ID=1929 THEN -ABS(I.AMOUNT)
                ELSE ABS(I.AMOUNT) END) SUM_DEVIR_ABS_FORMULA
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
 WHERE X.ACCOUNT_ID={accId}
 GROUP BY X.ID, T.TYPE, T.STATUS
 ORDER BY X.ID");

    await Q("STG INVOICE", $@"
SELECT V.LREF, V.INV_KIND, V.SOURCE_ORACLE_ACTION_ID, V.GRANDTOTAL, V.PAYABLETOTAL, V.CLOSED
  FROM SMS_AUDIT.STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID={accId} ORDER BY V.DATE_, V.LREF");

    await Q("STG INVLINES (tahakkuk)", $@"
SELECT IL.LREF, IL.INVOICEREF, IL.TRANSTYPE, IL.SRC_INCOME_ID, IL.AMOUNT, IL.LINEEXP
  FROM SMS_AUDIT.STG_INVLINES IL
 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID={accId} AND IL.SRC_INCOME_ID<>-1
 ORDER BY IL.INVOICEREF, IL.TRANSTYPE");

    await Q("STG PAYTRANS", $@"
SELECT P.LREF, P.PT_KIND, P.PAYABLETOTAL, P.PAID, P.CROSSREF, P.INVOICEREF,
       TO_CHAR(P.DATE_,'YYYY-MM-DD') DT
  FROM SMS_AUDIT.STG_PAYTRANS P WHERE P.SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY P.DATE_, P.LREF");

    await Q("STG PAYTRANS_INCOME", $@"
SELECT PI.PAYTRANSREF, PI.SRC_INCOME_ID, PI.INCOME_AMOUNT, PI.SOURCE_ORACLE_ACTION_ID PAY_ACT,
       I.AMOUNT SRC_RAW, I.AMOUNT*M.STATUS SRC_NET
  FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ID=PI.SOURCE_ORACLE_INCOME_ID
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ID=I.ACCOUNT_ACTION_ID
  JOIN SMS.CS_ACTION_TYPE_PRM M ON M.ID=X.ACTION_TYPE_ID
 WHERE PI.SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY PI.PAYTRANSREF, PI.SRC_INCOME_ID");

    await Q("STG SPEFEE devir", $@"
SELECT SP.SRC_INCOME_ID, SP.GRANDTOTAL, SP.INVOICEREF, SP.INVLINEREF, SP.SOURCE_ORACLE_ACTION_ID
  FROM SMS_AUDIT.STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_ACCOUNT_ID={accId}");

    await Q("DEVIR NET KARSILASTIRMA", $@"
WITH ACC AS (
  SELECT X.ID ACT, I.INCOME_ID, I.AMOUNT*T.STATUS NET
    FROM SMS.CS_ACCOUNT_ACTION X
    JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
    JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
   WHERE X.ACCOUNT_ID={accId} AND I.INCOME_ID IN (958,1929)
),
STG AS (
  SELECT 'INVLINES' T, IL.SRC_INCOME_ID INCOME_ID, IL.AMOUNT AMT
    FROM SMS_AUDIT.STG_INVLINES IL WHERE IL.SOURCE_ORACLE_ACCOUNT_ID={accId} AND IL.SRC_INCOME_ID IN (958,1929)
  UNION ALL
  SELECT 'PAYTRANS_INC', PI.SRC_INCOME_ID, PI.INCOME_AMOUNT
    FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_ACCOUNT_ID={accId} AND PI.SRC_INCOME_ID IN (958,1929)
)
SELECT * FROM ACC ORDER BY ACT, INCOME_ID");
    await Q("STG devir satirlari", $@"
SELECT * FROM (
  SELECT 'INVLINES' T, IL.SOURCE_ORACLE_ACTION_ID ACT, IL.SRC_INCOME_ID, IL.AMOUNT
    FROM SMS_AUDIT.STG_INVLINES IL WHERE IL.SOURCE_ORACLE_ACCOUNT_ID={accId} AND IL.SRC_INCOME_ID IN (958,1929)
  UNION ALL
  SELECT 'PAYTRANS_INC', PI.SOURCE_ORACLE_ACTION_ID, PI.SRC_INCOME_ID, PI.INCOME_AMOUNT
    FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_ACCOUNT_ID={accId} AND PI.SRC_INCOME_ID IN (958,1929)
) ORDER BY ACT, SRC_INCOME_ID");
}

static async Task SchemaProbe(string connStr)
{
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(r.GetName)));
        while (await r.ReadAsync())
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }
    await Q("CS_ACCOUNT_INCOME STATUS col", @"SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='SMS' AND TABLE_NAME='CS_ACCOUNT_INCOME' AND COLUMN_NAME='STATUS'");
    await Q("ABYS gelir raporu 15640062", $@"
SELECT A.ID, A.AGREEMENT_ID,
       MAX(CASE WHEN ATP.TYPE=1 THEN AA.ACTION_DATE END) TAHAKKUK_TARIHI,
       MAX(CASE WHEN ATP.TYPE=2 THEN AA.ACTION_DATE END) TAHSILAT_TARIHI,
       SUM(CASE WHEN ATP.TYPE=1 THEN AI.AMOUNT*AI.STATUS END) TAHAKKUK,
       SUM(CASE WHEN ATP.TYPE=2 THEN AI.AMOUNT*AI.STATUS END) TAHSILAT,
       SUM(AI.AMOUNT*AI.STATUS) KALAN_TUTAR
  FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=AA.ACTION_TYPE_ID
 WHERE A.ID=15640062
 GROUP BY A.ID, A.AGREEMENT_ID");
    await Q("CS_AGREEMENT install", @"SELECT AG.ID, AG.INSTALLATION_ID, I.INSTALLATION_NUMBER FROM SMS.CS_AGREEMENT AG LEFT JOIN SMS.CS_INSTALLATION I ON I.ID=AG.INSTALLATION_ID WHERE AG.ID=197168");
    await Q("TOTAL_DEBT on account", @"SELECT SUM(TOTAL_DEBT), SUM(TOTAL_CREDIT), COUNT(*) FROM SMS.CS_ACCOUNT WHERE AGREEMENT_ID=197168");
    await Q("Open debt variants", @"
SELECT 'TOTAL_DEBT sum' METRIK, SUM(A.TOTAL_DEBT) V FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168
UNION ALL SELECT 'TOTAL_DEBT-TOTAL_CREDIT', SUM(A.TOTAL_DEBT-A.TOTAL_CREDIT) FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID<>14
UNION ALL SELECT 'income debt net', SUM(I.AMOUNT*T.STATUS) FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID<>14
UNION ALL SELECT 'accrue type 1 debt', SUM(A.TOTAL_DEBT) FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=1
UNION ALL SELECT 'deposit accr5', SUM(I.AMOUNT*T.STATUS) FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=5");
    await Q("Invoice count source", @"
SELECT COUNT(DISTINCT X.ID) ACTION_CNT, COUNT(DISTINCT A.ID) ACC_CNT
  FROM SMS.CS_ACCOUNT A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
 WHERE A.AGREEMENT_ID=197168 AND T.TYPE=1 AND T.STATUS=1");
    await Q("Debt by accrue type", @"
SELECT A.ACCRUE_TYPE_ID, COUNT(*) CNT, SUM(A.TOTAL_DEBT) TD, SUM(A.TOTAL_CREDIT) TC, SUM(A.TOTAL_DEBT-A.TOTAL_CREDIT) NET
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168
 GROUP BY A.ACCRUE_TYPE_ID ORDER BY 1");
    await Q("Positive TOTAL_DEBT accounts", @"
SELECT SUM(A.TOTAL_DEBT) TD_SUM, SUM(A.TOTAL_DEBT-A.TOTAL_CREDIT) NET_SUM, COUNT(*) CNT
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.TOTAL_DEBT>A.TOTAL_CREDIT+0.01 AND A.ACCRUE_TYPE_ID NOT IN (14)");
    await Q("Agreement fields", @"SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='SMS' AND TABLE_NAME='CS_AGREEMENT' AND (UPPER(COLUMN_NAME) LIKE '%DEBT%' OR UPPER(COLUMN_NAME) LIKE '%BALANCE%' OR UPPER(COLUMN_NAME) LIKE '%INVOICE%') ORDER BY COLUMN_ID");
    await Q("Agreement 197168 debt fields", @"SELECT ID, POOL_DEBT, POOL_DEBT_COUNT FROM SMS.CS_AGREEMENT WHERE ID=197168");
    await Q("Open accrual actions", @"
SELECT SUM(ACT_DEBT) OPEN_SUM, COUNT(*) OPEN_CNT FROM (
  SELECT X.ID, SUM(I.AMOUNT*T.STATUS) ACT_DEBT
    FROM SMS.CS_ACCOUNT A
    JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
    JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
    JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
   WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID IN (1,2) AND T.TYPE=1 AND T.STATUS=1
   GROUP BY X.ID
  HAVING SUM(I.AMOUNT*T.STATUS)>0.01)");
    await Q("Net debt positive by type", @"
SELECT A.ACCRUE_TYPE_ID, SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0)) POS_NET, COUNT(*) POS_CNT
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
 GROUP BY A.ACCRUE_TYPE_ID ORDER BY 1");
    await Q("Type1+2 positive net sum", @"
SELECT SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0)) FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID IN (1,2) AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01");
    await Q("Top open accounts", @"
SELECT * FROM (
  SELECT A.ID, A.ACCRUE_TYPE_ID, A.PERIOD, A.TOTAL_DEBT, A.TOTAL_CREDIT,
         GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) NET
    FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168
     AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
   ORDER BY NET DESC) WHERE ROWNUM<=10");
    await Q("Type2 net only + type1 top4", @"
SELECT 23440.74 + (SELECT SUM(NET) FROM (
  SELECT GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) NET FROM SMS.CS_ACCOUNT A
   WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=1 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
   ORDER BY NET DESC) WHERE ROWNUM<=4) V FROM DUAL");
    await Q("Gecikme/arttiran actions", @"
SELECT X.ACTION_TYPE_ID, COUNT(*) CNT FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
 WHERE A.AGREEMENT_ID=197168 AND X.ACTION_TYPE_ID IN (3,10) GROUP BY X.ACTION_TYPE_ID");
    await Q("Deposit account 5", @"
SELECT A.ID, A.TOTAL_DEBT, A.TOTAL_CREDIT,
       (SELECT SUM(I.AMOUNT*T.STATUS) FROM SMS.CS_ACCOUNT_ACTION X
         JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
         JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE X.ACCOUNT_ID=A.ID) INC_NET
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=5");
    await Q("Find 26019 combo", @"
SELECT SUM(NET) S, COUNT(*) C FROM (
  SELECT GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) NET FROM SMS.CS_ACCOUNT A
   WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=2 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
) UNION ALL SELECT 26019.38 - 23440.74, NULL FROM DUAL");
    await Q("Top4 type2 open", @"
SELECT * FROM (
  SELECT A.ID, A.PERIOD, A.TOTAL_DEBT, A.TOTAL_CREDIT, GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) NET
    FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=2
     AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01 ORDER BY NET DESC) WHERE ROWNUM<=4");
    await Q("Sum top4 type2", @"
SELECT SUM(NET) FROM (
  SELECT GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) NET FROM SMS.CS_ACCOUNT A
   WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=2 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
   ORDER BY NET DESC) WHERE ROWNUM<=4");
    await Q("ABYS toplam borc formula", @"
SELECT 'type2_pos' M, TO_CHAR(SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0))) V FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=2 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
UNION ALL SELECT 'type1_pos', TO_CHAR(SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0))) FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=1 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
UNION ALL SELECT 't2+t1_subset', TO_CHAR(23440.74+2578.64) FROM DUAL
UNION ALL SELECT 'installment open', TO_CHAR(SUM(IP.AMOUNT)) FROM SMS.CS_INSTALLMENT INS
 JOIN SMS.CS_INSTALLMENT_PLAN IP ON IP.INSTALLMENT_ID=INS.ID
 WHERE INS.AGREEMENT_ID=197168 AND IP.PAYMENT_DATE IS NULL");
    await Q("Invoice count ABYS variants", @"
SELECT 'action_t1_s1' M, TO_CHAR(COUNT(DISTINCT X.ID)) FROM SMS.CS_ACCOUNT A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
 JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE A.AGREEMENT_ID=197168 AND T.TYPE=1 AND T.STATUS=1
UNION ALL SELECT 'action_t1_all', TO_CHAR(COUNT(DISTINCT X.ID)) FROM SMS.CS_ACCOUNT A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID
 JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE A.AGREEMENT_ID=197168 AND T.TYPE=1
UNION ALL SELECT 'accrue26_accts', TO_CHAR(COUNT(*)) FROM SMS.CS_ACCOUNT WHERE AGREEMENT_ID=197168 AND ACCRUE_TYPE_ID=26
UNION ALL SELECT '257+6', TO_CHAR(257+6) FROM DUAL");
    await Q("Debt views", @"SELECT VIEW_NAME FROM ALL_VIEWS WHERE OWNER='SMS' AND (VIEW_NAME LIKE '%DEBT%' OR VIEW_NAME LIKE '%AGREE%') AND ROWNUM<=30 ORDER BY VIEW_NAME");
    await Q("Paid invoice source", @"
SELECT COUNT(*) PAID_CNT FROM SMS.CS_ACCOUNT A
 WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID IN (1,2,26)
   AND NVL(A.TOTAL_DEBT,0) <= NVL(A.TOTAL_CREDIT,0)+0.01 AND EXISTS (
     SELECT 1 FROM SMS.CS_ACCOUNT_ACTION X JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
      WHERE X.ACCOUNT_ID=A.ID AND T.TYPE=1)");
    await Q("VW_DEBT_STATUS cols", @"SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='SMS' AND TABLE_NAME='VW_DEBT_STATUS' ORDER BY COLUMN_ID");
    await Q("VW_DEBT_STATUS 197168", @"SELECT * FROM SMS.VW_DEBT_STATUS WHERE ROWNUM<=3");
    await Q("VW_DEBT_STATUS view def", @"SELECT TEXT FROM ALL_VIEWS WHERE OWNER='SMS' AND VIEW_NAME='VW_DEBT_STATUS'");
    await Q("type26 actions", @"SELECT COUNT(DISTINCT X.ID) CNT FROM SMS.CS_ACCOUNT A JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=26 AND T.TYPE=1");
    await Q("type26 accounts", @"SELECT A.ID, A.PERIOD FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=26");
    await Q("ABYS debt try pool", @"
SELECT SUM(GREATEST(NVL(A.TOTAL_DEBT,0)-NVL(A.TOTAL_CREDIT,0),0)) ALL_OPEN,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID=2 THEN GREATEST(NVL(A.TOTAL_DEBT,0)-NVL(A.TOTAL_CREDIT,0),0) ELSE 0 END) T2,
       SUM(CASE WHEN A.ACCRUE_TYPE_ID=1 AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01 AND A.PERIOD>=202001
                THEN GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0) ELSE 0 END) T1_RECENT
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID IN (1,2)");
    await Q("type1 period sums", @"
SELECT A.PERIOD, SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0)) NET, COUNT(*) CNT
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=1
   AND A.TOTAL_DEBT>NVL(A.TOTAL_CREDIT,0)+0.01
 GROUP BY A.PERIOD ORDER BY NET DESC");
    await Q("AGR subscriber", @"
SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='SMS' AND TABLE_NAME='CS_AGREEMENT_SUBSCRIBER'
 AND (UPPER(COLUMN_NAME) LIKE '%DEBT%' OR UPPER(COLUMN_NAME) LIKE '%BALANCE%' OR UPPER(COLUMN_NAME) LIKE '%INVOICE%')
 ORDER BY COLUMN_ID");
    await Q("AGR sub 197168", @"SELECT * FROM SMS.CS_AGREEMENT_SUBSCRIBER WHERE ROWNUM<=1");
    await Q("installment debt", @"
SELECT SUM(GREATEST(A.TOTAL_DEBT-NVL(A.TOTAL_CREDIT,0),0)) T1_INST
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID=197168 AND A.ACCRUE_TYPE_ID=1
   AND EXISTS (SELECT 1 FROM SMS.CS_INSTALLMENT INS JOIN SMS.CS_INSTALLMENT_PLAN IP ON IP.INSTALLMENT_ID=INS.ID
                WHERE INS.AGREEMENT_ID=197168 AND IP.POOL_ID=A.ID)");
    await Q("overdue installment", @"
SELECT COUNT(*) CNT, SUM(IP.AMOUNT) AMT
  FROM SMS.CS_INSTALLMENT INS JOIN SMS.CS_INSTALLMENT_PLAN IP ON IP.INSTALLMENT_ID=INS.ID
 WHERE INS.AGREEMENT_ID=197168 AND IP.PAYMENT_DATE IS NULL AND NVL(IP.OVERDUE,0)>0");
}

static async Task CompareAcikFatura197168(string connStr)
{
    const long agrId = 197168;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        while (await r.ReadAsync())
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }
    await Q("ABYS Açık Fatura — hesap özeti (gelir net)", $@"
SELECT A.ID ACCOUNT_ID,
       SUM(CASE WHEN ATP.TYPE IN (1,5) THEN AI.AMOUNT*AI.STATUS ELSE 0 END) ACRUAL,
       SUM(CASE WHEN ATP.TYPE=2 OR (AA.ACTION_TYPE_ID=4 AND AI.STATUS=1)
                THEN AI.AMOUNT*AI.STATUS END) PAYED,
       SUM(AI.AMOUNT*AI.STATUS) BALANCE
  FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
  JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
  JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=AA.ACTION_TYPE_ID
 WHERE A.AGREEMENT_ID={agrId}
 GROUP BY A.ID
 ORDER BY ABS(SUM(AI.AMOUNT*AI.STATUS)) DESC");
    await Q("ABYS açık hesap adedi + toplam bakiye", $@"
SELECT COUNT(*) ACCT_CNT, SUM(BALANCE) MV_TOTAL, SUM(BAL) GELIR_NET_TOTAL FROM (
  SELECT A.ID, AMV.BALANCE BALANCE, SUM(AI.AMOUNT*AI.STATUS) BAL
    FROM SMS.CS_ACCOUNT A
    JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
    JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
    JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
   WHERE A.AGREEMENT_ID={agrId}
   GROUP BY A.ID, AMV.BALANCE)");
    await Q("Staging R9 sapmalar", $@"
SELECT K.ACCOUNT_ID, K.KAYNAK_BALANCE, NVL(S.BALANCE,0) STG_BALANCE,
       NVL(S.BALANCE,0)-K.KAYNAK_BALANCE FARK
  FROM (
    SELECT A.ID ACCOUNT_ID, SUM(AI.AMOUNT*AI.STATUS) KAYNAK_BALANCE
      FROM SMS.CS_ACCOUNT A
      JOIN SMS.CS_ACCOUNT_STATUS_MV AMV ON AMV.ACCOUNT_ID=A.ID
       AND AMV.BALANCE BETWEEN 0.01 AND 9999999999
      JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID
      JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
     WHERE A.AGREEMENT_ID={agrId}
     GROUP BY A.ID
  ) K
  LEFT JOIN (
    SELECT A.ID ACCOUNT_ID,
           NVL((SELECT SUM(IL.AMOUNT) FROM SMS_AUDIT.STG_INVLINES IL
                 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID=A.ID AND IL.SRC_INCOME_ID<>-1 AND NVL(IL.CANCELED,0)=0
                   AND IL.INVOICEREF IN (SELECT V.LREF FROM SMS_AUDIT.STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                                          AND V.INV_KIND IN ('MAIN','GECIKME','ARTTIRAN'))),0)
         + NVL((SELECT SUM(PI.INCOME_AMOUNT) FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI
                 JOIN SMS_AUDIT.STG_PAYTRANS P ON P.LREF=PI.PAYTRANSREF
                 JOIN SMS_AUDIT.STG_ACTION_MAP M ON M.ACTION_TYPE_ID=P.SRC_ACTION_TYPE
                 WHERE PI.SOURCE_ORACLE_ACCOUNT_ID=A.ID
                   AND (M.ACTION_CLASS=2 OR (P.SRC_ACTION_TYPE=4 AND EXISTS (
                         SELECT 1 FROM SMS.CS_ACCOUNT_INCOME I2
                          WHERE I2.ID=PI.SOURCE_ORACLE_INCOME_ID AND I2.STATUS=1)))),0) BALANCE
      FROM SMS_AUDIT.STG_PILOT_ACC A WHERE A.AGREEMENT_ID={agrId}
  ) S ON S.ACCOUNT_ID=K.ACCOUNT_ID
 WHERE ABS(NVL(S.BALANCE,0)-K.KAYNAK_BALANCE)>0.01
 ORDER BY ABS(NVL(S.BALANCE,0)-K.KAYNAK_BALANCE) DESC");
    await Q("Action 41 gecikme iptali", $@"
SELECT COUNT(*) CNT, SUM(AI.AMOUNT*AI.STATUS) NET
  FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION AA ON AA.ACCOUNT_ID=A.ID AND AA.ACTION_TYPE_ID=41
  JOIN SMS.CS_ACCOUNT_INCOME AI ON AI.ACCOUNT_ACTION_ID=AA.ID
 WHERE A.AGREEMENT_ID={agrId}");
}

static async Task InvestigateAccount570480(string connStr)
{
    const long accId = 570480;
    const long agrId = 197168;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        var n = 0;
        while (await r.ReadAsync() && n++ < 60)
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Q("Account 570480", $@"
SELECT ID, AGREEMENT_ID, ACCRUE_TYPE_ID, PERIOD, TOTAL_DEBT, TOTAL_CREDIT
  FROM SMS.CS_ACCOUNT WHERE ID={accId}");

    await Q("Actions on 570480", $@"
SELECT X.ID, X.ACTION_TYPE_ID, T.VALUE, T2.TYPE, X.ACTION_DATE,
       X.REF_DEPOSIT_ACCOUNT_ID, X.REF_DEPOSIT_ACCOUNT_ACTION_ID, X.INSTALLMENT_ID, X.INSTALLMENT_ORDER_NUMBER
  FROM SMS.CS_ACCOUNT_ACTION X
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG T ON T.PRM_ID=X.ACTION_TYPE_ID AND T.LANG_ID=1
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM T2 ON T2.ID=X.ACTION_TYPE_ID
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID");

    await Q("Type-12 on agreement — owner vs REF", $@"
SELECT X.ID ACTION_ID, X.ACCOUNT_ID SRC_ACC, X.ACTION_DATE,
       X.REF_DEPOSIT_ACCOUNT_ID REF_ACC, X.REF_DEPOSIT_ACCOUNT_ACTION_ID REF_ACT,
       (SELECT SUM(I.AMOUNT*I.STATUS) FROM SMS.CS_ACCOUNT_INCOME I WHERE I.ACCOUNT_ACTION_ID=X.ID) NET
  FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
 WHERE A.AGREEMENT_ID={agrId}
 ORDER BY X.ACTION_DATE, X.ID");

    await Q("STG mahsup targeting 570480", $@"
SELECT SOURCE_ORACLE_ACCOUNT_ID SRC_ACC, SOURCE_ORACLE_ACTION_ID ACT,
       TARGET_ACCOUNT_ID, TARGET_DEBT_PT, PAY_APPLIED, DURUM
  FROM SMS_AUDIT.STG_MAHSUP_POOL
 WHERE TARGET_ACCOUNT_ID={accId} OR SOURCE_ORACLE_ACCOUNT_ID={accId}
    OR TARGET_DEBT_PT IN (
         SELECT SOURCE_ORACLE_ACTION_ID FROM SMS_AUDIT.STG_INVOICE WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}
         UNION SELECT LREF FROM SMS_AUDIT.STG_PAYTRANS WHERE SOURCE_ORACLE_ACCOUNT_ID={accId} AND PT_KIND='ACCRUE')
 ORDER BY 1,2");

    await Q("Type-12 PTs CROSSREF dump toward 570480 debt", $@"
SELECT P.LREF, P.SOURCE_ORACLE_ACCOUNT_ID SRC_ACC, P.CROSSREF, P.PAYABLETOTAL
  FROM SMS_AUDIT.STG_PAYTRANS P
 WHERE P.SRC_ACTION_TYPE=12
   AND (P.SOURCE_ORACLE_ACCOUNT_ID={accId}
     OR P.CROSSREF IN (SELECT LREF FROM SMS_AUDIT.STG_PAYTRANS WHERE SOURCE_ORACLE_ACCOUNT_ID={accId} AND PT_KIND='ACCRUE')
     OR P.CROSSREF={accId})
 ORDER BY P.LREF");

    await Q("Accrue types with TAKSIT name", @"
SELECT PRM_ID, VALUE FROM SMS.CS_ACCRUE_TYPE_PRM_LNG
 WHERE LANG_ID=1 AND (UPPER(VALUE) LIKE '%TAKS%' OR UPPER(VALUE) LIKE '%MÜŞTER%' OR UPPER(VALUE) LIKE '%MUSTERI%')
 ORDER BY PRM_ID");

    await Q("Screenshot account IDs", @"
SELECT A.ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID, L.VALUE ACCRUE_NAME, A.PERIOD,
       A.TOTAL_DEBT, A.TOTAL_CREDIT, A.INSTALLMENT_ID
  FROM SMS.CS_ACCOUNT A
  LEFT JOIN SMS.CS_ACCRUE_TYPE_PRM_LNG L ON L.PRM_ID=A.ACCRUE_TYPE_ID AND L.LANG_ID=1
 WHERE A.ID IN (676618,676619,676620,676621,132783995,132783885,570480)
 ORDER BY A.ID");

    await Q("CS_ACCOUNT installment cols", @"
SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS
 WHERE OWNER='SMS' AND TABLE_NAME='CS_ACCOUNT'
   AND (UPPER(COLUMN_NAME) LIKE '%INST%' OR UPPER(COLUMN_NAME) LIKE '%POOL%' OR UPPER(COLUMN_NAME) LIKE '%PARENT%' OR UPPER(COLUMN_NAME) LIKE '%REF%')
 ORDER BY COLUMN_ID");

    await Q("Installments 197168", $@"
SELECT ID, PERIOD, INSTALLMENT_NUMBER, TOTAL_AMOUNT, MONTHLY_AMOUNT, DUE_DATE, INSTALLMENT_DATE
  FROM SMS.CS_INSTALLMENT WHERE AGREEMENT_ID={agrId} ORDER BY ID");

    await Q("Installment plan + pool_id accounts", $@"
SELECT IP.ID, IP.INSTALLMENT_ID, IP.ORDER_NUMBER, IP.AMOUNT, IP.DUE_DATE, IP.POOL_ID,
       IP.PAYMENT_DATE, A.ACCRUE_TYPE_ID, L.VALUE
  FROM SMS.CS_INSTALLMENT I
  JOIN SMS.CS_INSTALLMENT_PLAN IP ON IP.INSTALLMENT_ID=I.ID
  LEFT JOIN SMS.CS_ACCOUNT A ON A.ID=IP.POOL_ID
  LEFT JOIN SMS.CS_ACCRUE_TYPE_PRM_LNG L ON L.PRM_ID=A.ACCRUE_TYPE_ID AND L.LANG_ID=1
 WHERE I.AGREEMENT_ID={agrId}
 ORDER BY IP.INSTALLMENT_ID, IP.ORDER_NUMBER");

    await Q("STG installment", $@"
SELECT (SELECT COUNT(*) FROM SMS_AUDIT.STG_INSTALLMENT WHERE AGREEMENT_ID={agrId}) INS,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_INSTALLMENT_PLAN WHERE AGREEMENT_ID={agrId}) PLN FROM DUAL");

    await Q("STG invoices for screenshot IDs", @"
SELECT LREF, INV_KIND, SOURCE_ORACLE_ACCOUNT_ID, SOURCE_ORACLE_ACTION_ID, GRANDTOTAL, CLOSED
  FROM SMS_AUDIT.STG_INVOICE
 WHERE SOURCE_ORACLE_ACCOUNT_ID IN (676618,676619,676620,676621,132783995,132783885,570480)
    OR LREF IN (676618,676619,676620,676621,132783995,132783885,570480)
 ORDER BY LREF");

    await Q("Pilot has 676618?", @"
SELECT ID, ACCRUE_TYPE_ID, PERIOD FROM SMS_AUDIT.STG_PILOT_ACC
 WHERE ID IN (676618,676619,676620,676621,132783995,132783885,570480)");

    await Q("Accounts period 202602 agreement", $@"
SELECT A.ID, A.ACCRUE_TYPE_ID, L.VALUE, A.PERIOD, A.TOTAL_DEBT, A.TOTAL_CREDIT
  FROM SMS.CS_ACCOUNT A
  LEFT JOIN SMS.CS_ACCRUE_TYPE_PRM_LNG L ON L.PRM_ID=A.ACCRUE_TYPE_ID AND L.LANG_ID=1
 WHERE A.AGREEMENT_ID={agrId} AND A.PERIOD=202602
 ORDER BY A.ID");

    await Q("570480 PT state", $@"
SELECT LREF,PT_KIND,PAYABLETOTAL,PAID,CANCELED,DATE_
  FROM SMS_AUDIT.STG_PAYTRANS WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}");

    await Q("Type10 TAKSIT accounts", $@"
SELECT A.ID, A.PERIOD, A.INSTALLMENT_ID, A.POOL_ID, A.TOTAL_DEBT, A.TOTAL_CREDIT
  FROM SMS.CS_ACCOUNT A WHERE A.AGREEMENT_ID={agrId} AND A.ACCRUE_TYPE_ID=10 ORDER BY A.ID");

    await Q("Accounts linked installment", $@"
SELECT COUNT(*) CNT FROM SMS.CS_ACCOUNT WHERE AGREEMENT_ID={agrId} AND INSTALLMENT_ID IS NOT NULL");

    await Q("REF resolve vs debt PT", $@"
SELECT X.ID ACT, X.ACCOUNT_ID SRC, X.REF_DEPOSIT_ACCOUNT_ID REF_ACC,
       X.REF_DEPOSIT_ACCOUNT_ACTION_ID REF_ACT,
       RA.AGREEMENT_ID REF_AGR, RA.ACCRUE_TYPE_ID,
       (SELECT MIN(P.LREF) FROM SMS_AUDIT.STG_PAYTRANS P
         WHERE P.PT_KIND='ACCRUE' AND NVL(P.CANCELED,0)=0
           AND (P.SOURCE_ORACLE_ACTION_ID=X.REF_DEPOSIT_ACCOUNT_ACTION_ID
             OR (X.REF_DEPOSIT_ACCOUNT_ACTION_ID IS NULL AND P.SOURCE_ORACLE_ACCOUNT_ID=X.REF_DEPOSIT_ACCOUNT_ID))) REF_PT
  FROM SMS.CS_ACCOUNT A
  JOIN SMS.CS_ACCOUNT_ACTION X ON X.ACCOUNT_ID=A.ID AND X.ACTION_TYPE_ID=12
  LEFT JOIN SMS.CS_ACCOUNT RA ON RA.ID=X.REF_DEPOSIT_ACCOUNT_ID
 WHERE A.AGREEMENT_ID={agrId}");

    await Q("Screenshot IDs anywhere", @"
SELECT 'ACCOUNT' T, TO_CHAR(ID) ID, TO_CHAR(AGREEMENT_ID) AGR FROM SMS.CS_ACCOUNT WHERE ID IN (676618,676619,676620,676621)
UNION ALL SELECT 'INSTALLMENT', TO_CHAR(ID), TO_CHAR(AGREEMENT_ID) FROM SMS.CS_INSTALLMENT WHERE ID IN (676618,676619,676620,676621)
UNION ALL SELECT 'INST_PLAN', TO_CHAR(ID), TO_CHAR(INSTALLMENT_ID) FROM SMS.CS_INSTALLMENT_PLAN WHERE ID IN (676618,676619,676620,676621)
UNION ALL SELECT 'ACTION', TO_CHAR(ID), TO_CHAR(ACCOUNT_ID) FROM SMS.CS_ACCOUNT_ACTION WHERE ID IN (676618,676619,676620,676621)
UNION ALL SELECT 'ACCOUNT_AGR', TO_CHAR(ID), TO_CHAR(AGREEMENT_ID) FROM SMS.CS_ACCOUNT WHERE AGREEMENT_ID=197168 AND ID BETWEEN 676600 AND 676700");

    await Q("Installation 136283", @"
SELECT I.ID, I.INSTALLATION_NUMBER, AG.ID AGR FROM SMS.CS_INSTALLATION I
 LEFT JOIN SMS.CS_AGREEMENT AG ON AG.INSTALLATION_ID=I.ID
 WHERE I.INSTALLATION_NUMBER=136283 OR I.ID=136283");

    await Q("Installment masters 801225/6", @"
SELECT ID, AGREEMENT_ID, PERIOD, INSTALLMENT_NUMBER, TOTAL_AMOUNT, MONTHLY_AMOUNT, DUE_DATE
  FROM SMS.CS_INSTALLMENT WHERE ID IN (801225,801226)
UNION ALL
SELECT ID, AGREEMENT_ID, PERIOD, INSTALLMENT_NUMBER, TOTAL_AMOUNT, MONTHLY_AMOUNT, DUE_DATE
  FROM SMS.CS_INSTALLMENT WHERE AGREEMENT_ID=197168");

    await Q("Plan rows 676618-21 detail", @"
SELECT IP.ID, IP.INSTALLMENT_ID, IP.ORDER_NUMBER, IP.AMOUNT, IP.DUE_DATE, IP.POOL_ID, IP.PAYMENT_DATE,
       I.AGREEMENT_ID, I.PERIOD
  FROM SMS.CS_INSTALLMENT_PLAN IP
  JOIN SMS.CS_INSTALLMENT I ON I.ID=IP.INSTALLMENT_ID
 WHERE IP.ID IN (676618,676619,676620,676621)
 ORDER BY IP.ID");

    await Q("Accounts 873507-10", @"
SELECT A.ID, A.AGREEMENT_ID, A.ACCRUE_TYPE_ID, L.VALUE, A.PERIOD, A.INSTALLMENT_ID, A.POOL_ID,
       A.TOTAL_DEBT, A.TOTAL_CREDIT
  FROM SMS.CS_ACCOUNT A
  LEFT JOIN SMS.CS_ACCRUE_TYPE_PRM_LNG L ON L.PRM_ID=A.ACCRUE_TYPE_ID AND L.LANG_ID=1
 WHERE A.ID IN (873507,873508,873509,873510)
 ORDER BY A.ID");

    await Q("Mahsup sample after R39", @"
SELECT SOURCE_ORACLE_ACCOUNT_ID, SOURCE_ORACLE_ACTION_ID, TARGET_ACCOUNT_ID, TARGET_DEBT_PT, PAY_APPLIED, DURUM
  FROM SMS_AUDIT.STG_MAHSUP_POOL WHERE AGREEMENT_ID=197168 ORDER BY SOURCE_ORACLE_ACTION_ID");
}

static async Task ExplainDuplicate570480(string connStr)
{
    const long accId = 570480;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        var n = 0;
        while (await r.ReadAsync() && n++ < 80)
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Q("Recon rows", $@"
SELECT SEVERITY,KATEGORI,SOURCE_ORACLE_ACCOUNT_ID,KAYNAK_NET,STAGING_NET,FARK,SEBEP
  FROM SMS_AUDIT.STG_RECON_DIFF WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}");

    await Q("Coverage detail", $@"
SELECT SRC_INCOME_ID, SRC_ACTION_ID, INCOME_ID, SRC_AMOUNT, ACT_CLASS, TOTAL_TARGETS, DESTINATION,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVLINES IL WHERE IL.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1) CNT_IL,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID) CNT_PI,
       (SELECT COUNT(*) FROM SMS_AUDIT.STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID) CNT_SP
  FROM SMS_AUDIT.STG_INCOME_COVERAGE C
 WHERE SRC_ACCOUNT_ID={accId}
 ORDER BY SRC_ACTION_ID, SRC_INCOME_ID");

    await Q("Targets per income", $@"
SELECT 'INVLINES' T, IL.SOURCE_ORACLE_INCOME_ID INC, IL.SRC_INCOME_ID CODE, IL.AMOUNT AMT, IL.INVOICEREF REF, V.INV_KIND
  FROM SMS_AUDIT.STG_INVLINES IL
  JOIN SMS_AUDIT.STG_INVOICE V ON V.LREF=IL.INVOICEREF
 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID={accId} AND IL.SRC_INCOME_ID<>-1
UNION ALL
SELECT 'PAYINC', PI.SOURCE_ORACLE_INCOME_ID, PI.SRC_INCOME_ID, PI.INCOME_AMOUNT, PI.PAYTRANSREF, 'PAYMENT'
  FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_ACCOUNT_ID={accId}
UNION ALL
SELECT 'SPEFEE', SP.SOURCE_ORACLE_INCOME_ID, SP.SRC_INCOME_ID, SP.GRANDTOTAL, SP.INVOICEREF, 'SPEFEE'
  FROM SMS_AUDIT.STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY 2,1");
}

static async Task InvestigateAccount11091398(string connStr)
{
    const long accId = 11091398;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        while (await r.ReadAsync())
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Q("Pilot account SINIF", $@"
SELECT ID, AGREEMENT_ID, SINIF, TOTAL_DEBT, TOTAL_CREDIT FROM SMS_AUDIT.STG_PILOT_ACC WHERE ID={accId}");

    await Q("Source actions", $@"
SELECT X.ID, X.ACTION_TYPE_ID, T.TYPE, L.VALUE, TO_CHAR(X.ACTION_DATE,'YYYY-MM-DD HH24:MI') DT
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG L ON L.PRM_ID=T.ID AND L.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId} ORDER BY X.ACTION_DATE, X.ID");

    await Q("Source incomes", $@"
SELECT X.ID ACT, X.ACTION_TYPE_ID, L.VALUE TUR, I.INCOME_ID, IP.CODE, I.AMOUNT, I.STATUS, I.AMOUNT*I.STATUS NET
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  LEFT JOIN SMS.CS_INCOME_PRM IP ON IP.ID=I.INCOME_ID
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG L ON L.PRM_ID=X.ACTION_TYPE_ID AND L.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId} ORDER BY X.ID, I.ID");

    await Q("ABYS gelir net", $@"
SELECT SUM(CASE WHEN ATP.TYPE IN (1,5) THEN I.AMOUNT*I.STATUS ELSE 0 END) TAHAKKUK,
       SUM(CASE WHEN ATP.TYPE=2 THEN I.AMOUNT*I.STATUS ELSE 0 END) TAHSILAT,
       SUM(I.AMOUNT*I.STATUS) BALANCE
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=X.ACTION_TYPE_ID
 WHERE X.ACCOUNT_ID={accId}");

    await Q("EKSILTEN class", $@"
SELECT * FROM SMS_AUDIT.STG_EKSILTEN_CLASS WHERE ACCOUNT_ID={accId}");

    await Q("Staging invoices", $@"
SELECT LREF, INV_KIND, SOURCE_ORACLE_ACTION_ID, GRANDTOTAL, PAYABLETOTAL, CLOSED, CANCELED,
       RETURN_SOURCE_INVREF, RETURN_TARGET_INVREF
  FROM SMS_AUDIT.STG_INVOICE WHERE SOURCE_ORACLE_ACCOUNT_ID={accId} OR LREF={accId}
 ORDER BY DATE_, LREF");

    await Q("Staging paytrans", $@"
SELECT LREF, PT_KIND, SOURCE_ORACLE_ACTION_ID, PAYABLETOTAL, PAID, CANCELED, CROSSREF
  FROM SMS_AUDIT.STG_PAYTRANS WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY DATE_, LREF");

    await Q("Staging invlines (active)", $@"
SELECT IL.INVOICEREF, IL.SRC_INCOME_ID, IL.AMOUNT, IL.CANCELED, IL.LINEEXP
  FROM SMS_AUDIT.STG_INVLINES IL
 WHERE IL.SOURCE_ORACLE_ACCOUNT_ID={accId} AND IL.SRC_INCOME_ID<>-1
 ORDER BY IL.INVOICEREF, IL.LREF");

    await Q("Cancel pool / recon", $@"
SELECT 'POOL' T, REVERSAL_TYPE, GRANDTOTAL, SOURCE_ORACLE_ACTION_ID FROM SMS_AUDIT.STG_CANCEL_POOL WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}
UNION ALL SELECT 'RECON', KATEGORI, FARK, SEBEP FROM SMS_AUDIT.STG_RECON_DIFF WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}");
}

static async Task InvestigateAccount51407277(string connStr)
{
    const long accId = 51407277;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        while (await r.ReadAsync())
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Q("Source actions", $@"
SELECT X.ID, X.ACTION_TYPE_ID, T.TYPE, L.VALUE, T.STATUS,
       TO_CHAR(X.ACTION_DATE,'YYYY-MM-DD HH24:MI') DT,
       X.CASH_ID, X.RECEIPT_NUMBER, TO_CHAR(X.BANK_PAYMENT_DATE,'YYYY-MM-DD') BPD
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG L ON L.PRM_ID=T.ID AND L.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID");

    await Q("Source incomes (gelir kirilimi)", $@"
SELECT X.ID ACT, X.ACTION_TYPE_ID, L.VALUE TUR, I.INCOME_ID, IP.CODE, I.AMOUNT, I.STATUS, I.AMOUNT*I.STATUS NET
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  LEFT JOIN SMS.CS_INCOME_PRM IP ON IP.ID=I.INCOME_ID
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG L ON L.PRM_ID=X.ACTION_TYPE_ID AND L.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID, I.ID");

    await Q("Tahsilat iptal eslesmesi (ABYS hesapKarti NOT EXISTS)", $@"
SELECT PAY.ID PAY_ACTION, CAN.ID CANCEL_ACTION, PAY.RECEIPT_NUMBER, PAY.CASH_ID
  FROM SMS.CS_ACCOUNT_ACTION PAY
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=PAY.ACTION_TYPE_ID AND ATP.TYPE=2
  JOIN SMS.CS_ACCOUNT_ACTION CAN ON CAN.ACCOUNT_ID=PAY.ACCOUNT_ID
   AND CAN.ACTION_TYPE_ID=9
   AND CAN.CASH_ID=PAY.CASH_ID
   AND CAN.RECEIPT_NUMBER=PAY.RECEIPT_NUMBER
   AND NVL(CAN.BANK_PAYMENT_DATE,DATE'1900-01-01')=NVL(PAY.BANK_PAYMENT_DATE,DATE'1900-01-01')
 WHERE PAY.ACCOUNT_ID={accId}");

    await Q("ABYS gelir net ozet", $@"
SELECT SUM(CASE WHEN ATP.TYPE IN (1,5) THEN I.AMOUNT*I.STATUS ELSE 0 END) TAHAKKUK,
       SUM(CASE WHEN ATP.TYPE=2 THEN I.AMOUNT*I.STATUS ELSE 0 END) TAHSILAT,
       SUM(I.AMOUNT*I.STATUS) BALANCE
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
  JOIN SMS.CS_ACTION_TYPE_PRM ATP ON ATP.ID=X.ACTION_TYPE_ID
 WHERE X.ACCOUNT_ID={accId}
   AND NOT EXISTS (
         SELECT 1 FROM SMS.CS_ACCOUNT_ACTION CAN
          WHERE CAN.ACCOUNT_ID=X.ACCOUNT_ID AND CAN.ACTION_TYPE_ID=9
            AND CAN.CASH_ID=X.CASH_ID AND CAN.RECEIPT_NUMBER=X.RECEIPT_NUMBER
            AND NVL(CAN.BANK_PAYMENT_DATE,DATE'1900-01-01')=NVL(X.BANK_PAYMENT_DATE,DATE'1900-01-01')
            AND X.ACTION_TYPE_ID IN (SELECT ID FROM SMS.CS_ACTION_TYPE_PRM WHERE TYPE=2))");

    await Q("Staging invoice/paytrans", $@"
SELECT 'INV' T, V.LREF, V.INV_KIND, V.SOURCE_ORACLE_ACTION_ID, V.GRANDTOTAL, V.PAYABLETOTAL, V.CLOSED
  FROM SMS_AUDIT.STG_INVOICE V WHERE V.SOURCE_ORACLE_ACCOUNT_ID={accId}
UNION ALL
SELECT 'PT', P.LREF, P.PT_KIND, P.SOURCE_ORACLE_ACTION_ID, P.PAYABLETOTAL, P.PAID, P.CANCELED
  FROM SMS_AUDIT.STG_PAYTRANS P WHERE P.SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY 1,4");

    await Q("Payment PT CROSSREF", $@"
SELECT P.LREF, P.SOURCE_ORACLE_ACTION_ID, P.CROSSREF, P.PAYABLETOTAL, P.CANCELED, P.CANCELLATIONPAYMENT
  FROM SMS_AUDIT.STG_PAYTRANS P
 WHERE P.SOURCE_ORACLE_ACCOUNT_ID={accId} AND P.PT_KIND='PAYMENT'
 ORDER BY P.DATE_, P.LREF");

    await Q("MIG_SKIPPED cancel", $@"
SELECT * FROM SMS_AUDIT.MIG_SKIPPED WHERE ACCOUNT_ID={accId}");

    await Q("Recon", $@"
SELECT SEVERITY, KATEGORI, FARK, SEBEP FROM SMS_AUDIT.STG_RECON_DIFF WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}");
}

static async Task InvestigateAccount11881154(string connStr)
{
    const long accId = 11881154;
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        var n = 0;
        while (await r.ReadAsync() && n++ < 120)
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Q("Source actions", $@"
SELECT X.ID, X.ACTION_TYPE_ID, T.TYPE, T.STATUS, L.VALUE,
       TO_CHAR(X.ACTION_DATE,'YYYY-MM-DD HH24:MI:SS') DT,
       X.REF_DEPOSIT_ACCOUNT_ID, X.REF_DEPOSIT_ACCOUNT_ACTION_ID
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACTION_TYPE_PRM T ON T.ID=X.ACTION_TYPE_ID
  LEFT JOIN SMS.CS_ACTION_TYPE_PRM_LNG L ON L.PRM_ID=T.ID AND L.LANG_ID=1
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID");

    await Q("Source incomes", $@"
SELECT X.ID ACT, X.ACTION_TYPE_ID, I.ID INC_ROW, I.INCOME_ID, I.AMOUNT, I.STATUS, I.AMOUNT*I.STATUS NET
  FROM SMS.CS_ACCOUNT_ACTION X
  JOIN SMS.CS_ACCOUNT_INCOME I ON I.ACCOUNT_ACTION_ID=X.ID
 WHERE X.ACCOUNT_ID={accId}
 ORDER BY X.ACTION_DATE, X.ID, I.ID");

    await Q("Income metadata 36/162", @"
SELECT I.ID, I.CODE, L.VALUE, I.IS_DEPOSIT, I.IS_VAT_INCOME, I.IS_OVERDUE_INCOME,
       I.IS_LEGAL_FEE, I.IS_BALANCE_INCLUDED, I.INCOME_TYPE, I.OVERDUE_INCOME_ID, I.VAT_INCOME_ID
  FROM SMS.CS_INCOME_PRM I
  LEFT JOIN SMS.CS_INCOME_PRM_LNG L ON L.PRM_ID=I.ID AND L.LANG_ID=1
 WHERE I.ID IN (36,162)");

    await Q("Staging invoice/paytrans", $@"
SELECT 'INV' T, V.LREF, V.INV_KIND, V.SOURCE_ORACLE_ACTION_ID, V.GRANDTOTAL, V.PAYABLETOTAL, V.CLOSED, V.INVOICECROSSREF
  FROM SMS_AUDIT.STG_INVOICE V
 WHERE V.SOURCE_ORACLE_ACCOUNT_ID={accId}
UNION ALL
SELECT 'PT', P.LREF, P.PT_KIND, P.SOURCE_ORACLE_ACTION_ID, P.PAYABLETOTAL, P.PAID, P.CANCELED, P.CROSSREF
  FROM SMS_AUDIT.STG_PAYTRANS P
 WHERE P.SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY 1,2");

    await Q("Paytrans income", $@"
SELECT PAYTRANSREF, SRC_INCOME_ID, INCOME_AMOUNT, SOURCE_ORACLE_ACTION_ID
  FROM SMS_AUDIT.STG_PAYTRANS_INCOME
 WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY PAYTRANSREF, SRC_INCOME_ID");

    await Q("Mahsup pool relevant", $@"
SELECT SOURCE_ORACLE_ACCOUNT_ID, SOURCE_ORACLE_ACTION_ID, TARGET_ACCOUNT_ID, TARGET_DEBT_PT, PAY_APPLIED, DURUM
  FROM SMS_AUDIT.STG_MAHSUP_POOL
 WHERE SOURCE_ORACLE_ACCOUNT_ID={accId} OR TARGET_ACCOUNT_ID={accId}
 ORDER BY SOURCE_ORACLE_ACTION_ID, TARGET_DEBT_PT");

    await Q("Recon rows", $@"
SELECT SEVERITY, KATEGORI, SOURCE_ORACLE_ACCOUNT_ID, KAYNAK_NET, STAGING_NET, FARK, SEBEP
  FROM SMS_AUDIT.STG_RECON_DIFF
 WHERE SOURCE_ORACLE_ACCOUNT_ID={accId}
 ORDER BY KATEGORI");
}

static async Task FixCoverageR40(string connStr)
{
    await using var conn = new OracleConnection(connStr);
    await conn.OpenAsync();
    async Task Exec(string sql)
    {
        await using var cmd = new OracleCommand(sql, conn);
        await cmd.ExecuteNonQueryAsync();
    }
    async Task Q(string title, string sql)
    {
        Console.WriteLine($"\n=== {title} ===");
        await using var cmd = new OracleCommand(sql, conn);
        await using var r = await cmd.ExecuteReaderAsync();
        if (!r.HasRows) { Console.WriteLine("(no rows)"); return; }
        Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount).Select(i => r.GetName(i))));
        while (await r.ReadAsync())
            Console.WriteLine(string.Join(" | ", Enumerable.Range(0, r.FieldCount)
                .Select(i => r.IsDBNull(i) ? "NULL" : Convert.ToString(r.GetValue(i)))));
    }

    await Exec(@"
UPDATE SMS_AUDIT.STG_INCOME_COVERAGE C SET DESTINATION=
 CASE
  WHEN INCOME_ID IN (958,1929)
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVLINES IL WHERE IL.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1)=1
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID)=1
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID)=0
   AND TOTAL_TARGETS=2 THEN 'OK'
  WHEN ACT_CLASS=2
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_INVLINES IL WHERE IL.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID AND IL.SRC_INCOME_ID<>-1)=1
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_PAYTRANS_INCOME PI WHERE PI.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID)=1
   AND (SELECT COUNT(*) FROM SMS_AUDIT.STG_SPEFEE SP WHERE SP.SOURCE_ORACLE_INCOME_ID=C.SRC_INCOME_ID)=0
   AND TOTAL_TARGETS=2 THEN 'OK'
  WHEN TOTAL_TARGETS=0 THEN 'LOST'
  WHEN TOTAL_TARGETS>1 THEN 'DUPLICATE'
  ELSE 'OK' END");
    await Exec("DELETE FROM SMS_AUDIT.STG_RECON_DIFF WHERE KATEGORI LIKE 'YAPISAL_%'");
    await Exec(@"
INSERT INTO SMS_AUDIT.STG_RECON_DIFF (SEVERITY,KATEGORI,AGREEMENT_ID,SOURCE_ORACLE_ACCOUNT_ID,FARK,SUSPECT_ACTION_IDS,SEBEP)
SELECT 'CRITICAL','YAPISAL_'||DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID,SUM(SRC_AMOUNT),
       SUBSTR(LISTAGG(SRC_ACTION_ID,',') WITHIN GROUP (ORDER BY SRC_ACTION_ID),1,4000),'Income '||DESTINATION
  FROM SMS_AUDIT.STG_INCOME_COVERAGE WHERE DESTINATION IN ('LOST','DUPLICATE')
 GROUP BY DESTINATION,AGREEMENT_ID,SRC_ACCOUNT_ID");
    await Exec("COMMIT");

    await Q("570480 after R40", @"
SELECT DESTINATION, COUNT(*), SUM(SRC_AMOUNT) FROM SMS_AUDIT.STG_INCOME_COVERAGE
 WHERE SRC_ACCOUNT_ID=570480 GROUP BY DESTINATION");
    await Q("197168 coverage", @"
SELECT DESTINATION, COUNT(*), SUM(SRC_AMOUNT) FROM SMS_AUDIT.STG_INCOME_COVERAGE
 WHERE AGREEMENT_ID=197168 GROUP BY DESTINATION ORDER BY 1");
    await Q("Remaining YAPISAL on 197168", @"
SELECT KATEGORI, SOURCE_ORACLE_ACCOUNT_ID, FARK, SEBEP
  FROM SMS_AUDIT.STG_RECON_DIFF
 WHERE AGREEMENT_ID=197168 AND KATEGORI LIKE 'YAPISAL_%'
 ORDER BY KATEGORI, SOURCE_ORACLE_ACCOUNT_ID");
}

