/* ============================================================
   SCRIPT_ID : REF_BANK_ACC_SETUP
   SCRIPT_NO : 125
   FILE      : 125_REF_BANK_ACC__setup.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- SMS.IT_CASH (+ IT_BANK_PRM)
--   → izgazMGR.dbo.LS_BANK_ACC  (CTAS dump)
--   → energy.dbo.LS_BANK_ACC
--
-- LREF    : IDENTITY (yeni)
-- ABYS_ID : IT_CASH.ID
-- BANKREF : LS_BANK.LREF WHERE ABYS_ID = BANK_ID
-- Önkoşul : 121_REF_BANK__migrate.sql (LS_BANK.ABYS_ID dolu)
-- Oracle  : oracleCTAS3007/LS_BANK_ACC.sql → dump LS_BANK_ACC
-- ============================================================
USE energy;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('energy.dbo.LS_BANK_ACC', 'U') IS NULL
BEGIN
    RAISERROR('energy.dbo.LS_BANK_ACC bulunamadi. Once hedef tabloyu olusturun.', 16, 1);
    RETURN;
END
GO

-- ------------------------------------------------------------
-- ABYS_ kopru kolonlari
-- ------------------------------------------------------------
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_CODE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_CODE NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_BANK_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_BANK_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_CORPORATION_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_CORPORATION_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_RECEIPT_SERIAL') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_RECEIPT_SERIAL NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_RECEIPT_NUMBER') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_RECEIPT_NUMBER INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_RECEIPT_TYPE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_RECEIPT_TYPE INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_ACCOUNT_CODE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_ACCOUNT_CODE NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_ACCOUNT_CODE_FINANCE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_ACCOUNT_CODE_FINANCE NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_BANK_ACCOUNT_NUMBER') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_BANK_ACCOUNT_NUMBER NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_OPENING_TIME') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_OPENING_TIME NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_CLOSING_TIME') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_CLOSING_TIME NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_BANK_INTEGRATION_CODE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_BANK_INTEGRATION_CODE NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_RECONCILIATION_DATE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_RECONCILIATION_DATE DATETIME NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_PAYMENT_RETURN_DAY') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_PAYMENT_RETURN_DAY INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_IS_ONLINE_DISCHARGE') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_IS_ONLINE_DISCHARGE BIT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_CASH_TYPE_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_CASH_TYPE_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_WORK_PLACE_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_WORK_PLACE_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_ACCOUNT_CODE_CREDIT') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_ACCOUNT_CODE_CREDIT NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_CREATED_USER_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_CREATED_USER_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_UPDATED_USER_ID') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_UPDATED_USER_ID INT NULL;
GO
IF COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_VERSION') IS NULL
    ALTER TABLE dbo.LS_BANK_ACC ADD ABYS_VERSION INT NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_BANK_ACC')
      AND name = 'UX_LS_BANK_ACC_ABYS_ID'
)
    CREATE UNIQUE NONCLUSTERED INDEX UX_LS_BANK_ACC_ABYS_ID
        ON dbo.LS_BANK_ACC (ABYS_ID)
        WHERE ABYS_ID IS NOT NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.LS_BANK_ACC')
      AND name = 'IX_LS_BANK_ACC_BANKREF'
)
    CREATE NONCLUSTERED INDEX IX_LS_BANK_ACC_BANKREF
        ON dbo.LS_BANK_ACC (BANKREF)
        INCLUDE (ABYS_ID, ABYS_BANK_ID, ISACTIVE);
GO

PRINT '125_REF_BANK_ACC__setup OK';
GO
