/* ============================================================
   SCRIPT_ID : REF_BANK_ACC_MIGRATE
   SCRIPT_NO : 126
   FILE      : 126_REF_BANK_ACC__migrate.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- IT_CASH (+ IT_BANK_PRM) → energy.dbo.LS_BANK_ACC
--
-- @SourceMode:
--   MANUAL — asagidaki 5 ornek satır (Oracle sorgusu ornek dump)
--   MGR    — izgazMGR.dbo.LS_BANK_ACC (CTAS + dump sonrasi standart)
--
-- Mapping:
--   DEFN                  = CASH_NAME
--   ACCNO                 = COALESCE(BANK_ACCOUNT_NUMBER, CODE)
--   IBAN                  = BANK_ACCOUNT_NUMBER
--   BANKREF               = LS_BANK.LREF WHERE ABYS_ID = BANK_ID
--   LOGOCODE              = ACCOUNT_CODE
--   ENT_ID                = 4102
--   IS_INTERGRATION_BANK  = BANK_INTEGRATION_CODE IS NOT NULL
--   ISACTIVE              = IS_ACTIVE
--   VALOR                 = PAYMENT_RETURN_DAY
--   NR                    = 0
--   ABYS_*                = kaynak kolonlar
--
-- Idempotent: NOT EXISTS (ABYS_ID)
-- Önkoşul: 121_REF_BANK + 125_REF_BANK_ACC__setup
-- ============================================================
USE energy;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @SourceMode VARCHAR(10) = 'MGR';  -- MGR (izgazMGR dump) | MANUAL (5 ornek)
DECLARE @Inserted   INT = 0;

IF OBJECT_ID('dbo.LS_BANK_ACC', 'U') IS NULL
   OR COL_LENGTH('dbo.LS_BANK_ACC', 'ABYS_ID') IS NULL
BEGIN
    RAISERROR('LS_BANK_ACC.ABYS_ID yok. Once 125_REF_BANK_ACC__setup.sql calistirin.', 16, 1);
    RETURN;
END;

IF OBJECT_ID('dbo.LS_BANK', 'U') IS NULL
   OR COL_LENGTH('dbo.LS_BANK', 'ABYS_ID') IS NULL
BEGIN
    RAISERROR('LS_BANK.ABYS_ID yok. Once 121_REF_BANK__migrate.sql calistirin.', 16, 1);
    RETURN;
END;

IF @SourceMode NOT IN ('MANUAL', 'MGR')
BEGIN
    RAISERROR('@SourceMode MANUAL veya MGR olmali.', 16, 1);
    RETURN;
END;

IF @SourceMode = 'MANUAL'
BEGIN
    ;WITH src AS (
        SELECT *
        FROM (VALUES
            (502, 1, N'502', N'VAKIFBANK İZMİT MRK. GAZ TAH', N'A', 18, 2,
             N'102.01.03.17001', CAST(NULL AS NVARCHAR(50)), 30, CAST(NULL AS NVARCHAR(50)),
             N'10:50', N'10:50', CAST(NULL AS NVARCHAR(50)), CAST(NULL AS DATETIME),
             2, 0, 0, 22, 213, 58, CAST(NULL AS INT), CAST(NULL AS INT), CAST(NULL AS NVARCHAR(50))),
            (524, 1, N'524', N'HALKBANK KÖRFEZ GAZ TAH', N'A', 1, 2,
             N'102.01.03.07002', NULL, 17, NULL,
             N'08:30', N'17:30', NULL, NULL,
             CAST(NULL AS INT), 0, 0, 22, CAST(NULL AS INT), 0, NULL, NULL, NULL),
            (503, 1, N'503', N'VAKIFBANK İZM YENİTURAN GAZ TA', N'A', 1, 2,
             N'102.01.03.17003', NULL, 30, NULL,
             N'14:29', N'14:29', NULL, NULL,
             NULL, 0, 0, 22, NULL, 0, NULL, NULL, NULL),
            (504, 1, N'504', N'VAKIFBANK İZM Y.KAPTAN GAZ TAH', N'A', 1, 2,
             N'102.01.03.17005', NULL, 30, NULL,
             N'14:09', N'14:09', NULL, NULL,
             NULL, 0, 0, 22, NULL, 0, NULL, NULL, NULL),
            (506, 1, N'506', N'VAKIFBANK KÖRFEZ GAZ TAH 1', N'A', 1, 2,
             N'102.01.03.17002', NULL, 30, NULL,
             N'08:30', N'17:30', NULL, NULL,
             NULL, 0, 0, 22, NULL, 1, NULL, NULL, NULL)
        ) v (
            ID, CORPORATION_ID, CODE, CASH_NAME, RECEIPT_SERIAL, RECEIPT_NUMBER, RECEIPT_TYPE,
            ACCOUNT_CODE, ACCOUNT_CODE_FINANCE, BANK_ID, BANK_ACCOUNT_NUMBER,
            OPENING_TIME, CLOSING_TIME, BANK_INTEGRATION_CODE, RECONCILIATION_DATE,
            PAYMENT_RETURN_DAY, IS_ONLINE_DISCHARGE, IS_ACTIVE,
            CREATED_USER_ID, UPDATED_USER_ID, VERSION, CASH_TYPE_ID, WORK_PLACE_ID, ACCOUNT_CODE_CREDIT
        )
    )
    INSERT INTO dbo.LS_BANK_ACC (
        ACCNO, IBAN, DEFN, BANKREF, NR, LOGOCODE, ENT_ID,
        IS_INTERGRATION_BANK, ISACTIVE, EXCNR, ISDEFAULT_CC, VALOR,
        ABYS_ID, ABYS_CODE, ABYS_BANK_ID, ABYS_CORPORATION_ID,
        ABYS_RECEIPT_SERIAL, ABYS_RECEIPT_NUMBER, ABYS_RECEIPT_TYPE,
        ABYS_ACCOUNT_CODE, ABYS_ACCOUNT_CODE_FINANCE, ABYS_BANK_ACCOUNT_NUMBER,
        ABYS_OPENING_TIME, ABYS_CLOSING_TIME, ABYS_BANK_INTEGRATION_CODE,
        ABYS_RECONCILIATION_DATE, ABYS_PAYMENT_RETURN_DAY, ABYS_IS_ONLINE_DISCHARGE,
        ABYS_CASH_TYPE_ID, ABYS_WORK_PLACE_ID, ABYS_ACCOUNT_CODE_CREDIT,
        ABYS_CREATED_USER_ID, ABYS_UPDATED_USER_ID, ABYS_VERSION
    )
    SELECT
        LEFT(COALESCE(NULLIF(LTRIM(RTRIM(s.BANK_ACCOUNT_NUMBER)), N''), s.CODE), 30),
        LEFT(NULLIF(LTRIM(RTRIM(s.BANK_ACCOUNT_NUMBER)), N''), 34),
        LEFT(s.CASH_NAME, 250),
        bk.LREF,
        0,
        LEFT(s.ACCOUNT_CODE, 50),
        4102,
        CASE WHEN s.BANK_INTEGRATION_CODE IS NOT NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        CASE WHEN ISNULL(s.IS_ACTIVE, 0) = 1 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        NULL,
        CAST(0 AS BIT),
        s.PAYMENT_RETURN_DAY,
        s.ID,
        LEFT(s.CODE, 50),
        s.BANK_ID,
        s.CORPORATION_ID,
        LEFT(s.RECEIPT_SERIAL, 20),
        s.RECEIPT_NUMBER,
        s.RECEIPT_TYPE,
        LEFT(s.ACCOUNT_CODE, 50),
        LEFT(s.ACCOUNT_CODE_FINANCE, 50),
        LEFT(s.BANK_ACCOUNT_NUMBER, 50),
        LEFT(s.OPENING_TIME, 20),
        LEFT(s.CLOSING_TIME, 20),
        LEFT(s.BANK_INTEGRATION_CODE, 50),
        s.RECONCILIATION_DATE,
        s.PAYMENT_RETURN_DAY,
        CASE WHEN ISNULL(s.IS_ONLINE_DISCHARGE, 0) = 1 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        s.CASH_TYPE_ID,
        s.WORK_PLACE_ID,
        LEFT(s.ACCOUNT_CODE_CREDIT, 50),
        s.CREATED_USER_ID,
        s.UPDATED_USER_ID,
        s.VERSION
    FROM src s
    OUTER APPLY (
        SELECT TOP (1) b.LREF
        FROM dbo.LS_BANK b
        WHERE b.ABYS_ID = s.BANK_ID
        ORDER BY b.LREF
    ) bk
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LS_BANK_ACC t WHERE t.ABYS_ID = s.ID
    );

    SET @Inserted = @@ROWCOUNT;
END
ELSE
BEGIN
    IF OBJECT_ID('izgazMGR.dbo.LS_BANK_ACC', 'U') IS NULL
    BEGIN
        RAISERROR('izgazMGR.dbo.LS_BANK_ACC yok. Once Oracle CTAS LS_BANK_ACC + dump calistirin.', 16, 1);
        RETURN;
    END;

    INSERT INTO dbo.LS_BANK_ACC (
        ACCNO, IBAN, DEFN, BANKREF, NR, LOGOCODE, ENT_ID,
        IS_INTERGRATION_BANK, ISACTIVE, EXCNR, ISDEFAULT_CC, VALOR,
        ABYS_ID, ABYS_CODE, ABYS_BANK_ID, ABYS_CORPORATION_ID,
        ABYS_RECEIPT_SERIAL, ABYS_RECEIPT_NUMBER, ABYS_RECEIPT_TYPE,
        ABYS_ACCOUNT_CODE, ABYS_ACCOUNT_CODE_FINANCE, ABYS_BANK_ACCOUNT_NUMBER,
        ABYS_OPENING_TIME, ABYS_CLOSING_TIME, ABYS_BANK_INTEGRATION_CODE,
        ABYS_RECONCILIATION_DATE, ABYS_PAYMENT_RETURN_DAY, ABYS_IS_ONLINE_DISCHARGE,
        ABYS_CASH_TYPE_ID, ABYS_WORK_PLACE_ID, ABYS_ACCOUNT_CODE_CREDIT,
        ABYS_CREATED_USER_ID, ABYS_UPDATED_USER_ID, ABYS_VERSION
    )
    SELECT
        LEFT(COALESCE(NULLIF(LTRIM(RTRIM(CAST(s.BANK_ACCOUNT_NUMBER AS NVARCHAR(50)))), N''), CAST(s.CODE AS NVARCHAR(50))), 30),
        LEFT(NULLIF(LTRIM(RTRIM(CAST(s.BANK_ACCOUNT_NUMBER AS NVARCHAR(50)))), N''), 34),
        LEFT(CAST(s.CASH_NAME AS NVARCHAR(250)), 250),
        bk.LREF,
        0,
        LEFT(CAST(s.ACCOUNT_CODE AS NVARCHAR(50)), 50),
        4102,
        CASE WHEN s.BANK_INTEGRATION_CODE IS NOT NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        CASE WHEN ISNULL(CAST(s.IS_ACTIVE AS INT), 0) = 1 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        NULL,
        CAST(0 AS BIT),
        CAST(s.PAYMENT_RETURN_DAY AS INT),
        CAST(s.ID AS INT),
        LEFT(CAST(s.CODE AS NVARCHAR(50)), 50),
        CAST(s.BANK_ID AS INT),
        CAST(s.CORPORATION_ID AS INT),
        LEFT(CAST(s.RECEIPT_SERIAL AS NVARCHAR(20)), 20),
        CAST(s.RECEIPT_NUMBER AS INT),
        CAST(s.RECEIPT_TYPE AS INT),
        LEFT(CAST(s.ACCOUNT_CODE AS NVARCHAR(50)), 50),
        LEFT(CAST(s.ACCOUNT_CODE_FINANCE AS NVARCHAR(50)), 50),
        LEFT(CAST(s.BANK_ACCOUNT_NUMBER AS NVARCHAR(50)), 50),
        LEFT(CAST(s.OPENING_TIME AS NVARCHAR(20)), 20),
        LEFT(CAST(s.CLOSING_TIME AS NVARCHAR(20)), 20),
        LEFT(CAST(s.BANK_INTEGRATION_CODE AS NVARCHAR(50)), 50),
        CASE
            WHEN s.RECONCILIATION_DATE IS NULL THEN NULL
            WHEN CAST(s.RECONCILIATION_DATE AS DATETIME2) < CAST('17530101' AS DATETIME2) THEN NULL
            ELSE CAST(s.RECONCILIATION_DATE AS DATETIME)
        END,
        CAST(s.PAYMENT_RETURN_DAY AS INT),
        CASE WHEN ISNULL(CAST(s.IS_ONLINE_DISCHARGE AS INT), 0) = 1 THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END,
        CAST(s.CASH_TYPE_ID AS INT),
        CAST(s.WORK_PLACE_ID AS INT),
        LEFT(CAST(s.ACCOUNT_CODE_CREDIT AS NVARCHAR(50)), 50),
        CAST(s.CREATED_USER_ID AS INT),
        CAST(s.UPDATED_USER_ID AS INT),
        CAST(s.VERSION AS INT)
    FROM izgazMGR.dbo.LS_BANK_ACC s
    OUTER APPLY (
        SELECT TOP (1) b.LREF
        FROM dbo.LS_BANK b
        WHERE b.ABYS_ID = CAST(s.BANK_ID AS INT)
        ORDER BY b.LREF
    ) bk
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.LS_BANK_ACC t WHERE t.ABYS_ID = CAST(s.ID AS INT)
    );

    SET @Inserted = @@ROWCOUNT;
END;

-- ---- RECON ----
SELECT
    @SourceMode AS SOURCE_MODE,
    @Inserted   AS INSERTED_ROWS;

SELECT
    'POST_ABYS_CNT' AS METRIC,
    COUNT(*) AS CNT
FROM dbo.LS_BANK_ACC
WHERE ABYS_ID IS NOT NULL
UNION ALL
SELECT
    'POST_BANKREF_NULL',
    COUNT(*)
FROM dbo.LS_BANK_ACC
WHERE ABYS_ID IS NOT NULL
  AND BANKREF IS NULL
UNION ALL
SELECT
    'POST_BANKREF_ORPHAN',
    COUNT(*)
FROM dbo.LS_BANK_ACC t
WHERE t.ABYS_ID IS NOT NULL
  AND t.BANKREF IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM dbo.LS_BANK b WHERE b.LREF = t.BANKREF);

SELECT TOP (20)
    t.LREF, t.ACCNO, t.IBAN, t.DEFN, t.BANKREF, t.LOGOCODE, t.ENT_ID,
    t.IS_INTERGRATION_BANK, t.ISACTIVE, t.VALOR,
    t.ABYS_ID, t.ABYS_BANK_ID, b.DEFN AS BANK_DEFN, b.ABYS_ID AS BANK_ABYS_ID
FROM dbo.LS_BANK_ACC t
LEFT JOIN dbo.LS_BANK b ON b.LREF = t.BANKREF
WHERE t.ABYS_ID IS NOT NULL
ORDER BY t.ABYS_ID;

PRINT CONCAT('126_REF_BANK_ACC__migrate OK — mode=', @SourceMode, ' inserted=', @Inserted);
GO
