/* ============================================================
   SCRIPT_ID : MASTER_ITEMS_POST
   SCRIPT_NO : 242
   FILE      : 242_MASTER_ITEMS__post.sql
   VERSION   : 1
   Amac      : LS_005_ITEMS aktarim sonrasi WAREHOUSE / STATID / SUPLID
   ============================================================ */
USE energy;
GO

---- 1) WAREHOUSE <- ABYS_WAREHOUSE (ENT_ID = 4102)
--UPDATE itm
--SET itm.WAREHOUSE = fr.LREF
--FROM energy.dbo.LS_005_ITEMS itm
--JOIN energy.dbo.LS_WAREHOUSE fr ON fr.DEFN = itm.ABYS_WAREHOUSE
--WHERE fr.ENT_ID = 4102
--  AND itm.ABYS_MIG_ROW_ID IS NOT NULL;
--GO

---- 2) STATID / ISACTIVE / WAREHOUSE remap (LREF dogrulayin)
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 2, ISACTIVE = 1, WAREHOUSE = 36 WHERE WAREHOUSE = 2  AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1, WAREHOUSE = 41 WHERE WAREHOUSE = 1  AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1, WAREHOUSE = 37 WHERE WAREHOUSE = 5  AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 3, ISACTIVE = 0 WHERE WAREHOUSE = 44 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 3, ISACTIVE = 1 WHERE WAREHOUSE = 35 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 1 WHERE WAREHOUSE = 43 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 5, ISACTIVE = 1 WHERE WAREHOUSE = 7  AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 4, ISACTIVE = 1 WHERE WAREHOUSE = 53 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 0 WHERE WAREHOUSE = 40 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 1, ISACTIVE = 0 WHERE WAREHOUSE = 48 AND ABYS_MIG_ROW_ID IS NOT NULL;
--UPDATE energy.dbo.LS_005_ITEMS SET STATID = 5, ISACTIVE = 0
--WHERE WAREHOUSE IN (45, 6, 33, 31, 57, 46, 52, 32, 49, 56, 34, 47, 54, 29, 28, 27, 50, 39, 51)
--  AND ABYS_MIG_ROW_ID IS NOT NULL;
--GO

---- 3) SUPLID <- ABYS_MARK
--UPDATE itm
--SET itm.SUPLID = fr.LREF
--FROM energy.dbo.LS_005_ITEMS itm
--JOIN energy.dbo.LS_005_FIRM fr ON fr.NAME_ = itm.ABYS_MARK
--WHERE itm.ABYS_MIG_ROW_ID IS NOT NULL;
--GO
