/* ============================================================
   SCRIPT_ID : LEGAL_LP_WIRE
   SCRIPT_NO : 602
   FILE      : 602_LEGAL_LP__wire.sql
   VERSION   : 1
   ============================================================ */
-- ============================================================
-- LP aktarımında geçici kaldırılan FK'leri geri kur
-- Önce orphan kontrolü, sonra WITH CHECK ile ekler.
-- ============================================================
USE energy;
GO

IF OBJECT_ID('tempdb..#LpRestoreState') IS NOT NULL
    DROP TABLE #LpRestoreState;

CREATE TABLE #LpRestoreState (CAN_RESTORE BIT NOT NULL);
INSERT INTO #LpRestoreState (CAN_RESTORE) VALUES (1);
GO

-- Orphan raporları
SELECT 'LP_STATUS -> LP_LEGAL_PROCEEDING' AS RELATION_NAME, COUNT(*) AS ORPHAN_COUNT
FROM energy.dbo.LP_STATUS c
WHERE c.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID);
GO

SELECT 'LP_INVOICE -> LP_LEGAL_PROCEEDING' AS RELATION_NAME, COUNT(*) AS ORPHAN_COUNT
FROM energy.dbo.LP_INVOICE c
WHERE c.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID);
GO

SELECT 'LP_INCOME -> LP_LEGAL_PROCEEDING' AS RELATION_NAME, COUNT(*) AS ORPHAN_COUNT
FROM energy.dbo.LP_INCOME c
WHERE c.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID);
GO

SELECT 'LP_INCOME -> LP_EXPENSE_CAUSE_PRM' AS RELATION_NAME, COUNT(*) AS ORPHAN_COUNT
FROM energy.dbo.LP_INCOME c
WHERE c.ABYS_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_EXPENSE_CAUSE_PRM p WHERE p.ID = c.EXPENSE_CAUSE_ID);
GO

SELECT 'LP_LEGAL_PROCEEDING AGREEMENT_ID=0' AS RELATION_NAME, COUNT(*) AS ORPHAN_COUNT
FROM energy.dbo.LP_LEGAL_PROCEEDING c
WHERE c.ABYS_ID IS NOT NULL AND c.AGREEMENT_ID = 0;
GO

-- Orphan varsa durdur
IF EXISTS (
    SELECT 1 FROM energy.dbo.LP_STATUS c
    WHERE c.ABYS_ID IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID)
)
BEGIN
    PRINT 'FK geri yukleme durdu: LP_STATUS orphan kayitlari var.';
    UPDATE #LpRestoreState SET CAN_RESTORE = 0;
END
GO

IF EXISTS (
    SELECT 1 FROM energy.dbo.LP_INVOICE c
    WHERE c.ABYS_ID IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID)
)
BEGIN
    PRINT 'FK geri yukleme durdu: LP_INVOICE orphan kayitlari var.';
    UPDATE #LpRestoreState SET CAN_RESTORE = 0;
END
GO

IF EXISTS (
    SELECT 1 FROM energy.dbo.LP_INCOME c
    WHERE c.ABYS_ID IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_LEGAL_PROCEEDING p WHERE p.ID = c.LEGAL_PROCEEDING_ID)
)
BEGIN
    PRINT 'FK geri yukleme durdu: LP_INCOME -> LP_LEGAL_PROCEEDING orphan kayitlari var.';
    UPDATE #LpRestoreState SET CAN_RESTORE = 0;
END
GO

IF EXISTS (
    SELECT 1 FROM energy.dbo.LP_INCOME c
    WHERE c.ABYS_ID IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM energy.dbo.LP_EXPENSE_CAUSE_PRM p WHERE p.ID = c.EXPENSE_CAUSE_ID)
)
BEGIN
    PRINT 'FK geri yukleme durdu: LP_INCOME -> LP_EXPENSE_CAUSE_PRM orphan kayitlari var.';
    UPDATE #LpRestoreState SET CAN_RESTORE = 0;
END
GO

-- FK geri yükleme
IF EXISTS (SELECT 1 FROM #LpRestoreState WHERE CAN_RESTORE = 1)
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_LP_STATUS_LP_LEGAL_PROCEEDING')
BEGIN
    ALTER TABLE energy.dbo.LP_STATUS WITH CHECK
    ADD CONSTRAINT FK_LP_STATUS_LP_LEGAL_PROCEEDING
        FOREIGN KEY (LEGAL_PROCEEDING_ID) REFERENCES energy.dbo.LP_LEGAL_PROCEEDING (ID);
    ALTER TABLE energy.dbo.LP_STATUS CHECK CONSTRAINT FK_LP_STATUS_LP_LEGAL_PROCEEDING;
END
GO

IF EXISTS (SELECT 1 FROM #LpRestoreState WHERE CAN_RESTORE = 1)
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_LP_INVOICE_LP_LEGAL_PROCEEDING')
BEGIN
    ALTER TABLE energy.dbo.LP_INVOICE WITH CHECK
    ADD CONSTRAINT FK_LP_INVOICE_LP_LEGAL_PROCEEDING
        FOREIGN KEY (LEGAL_PROCEEDING_ID) REFERENCES energy.dbo.LP_LEGAL_PROCEEDING (ID);
    ALTER TABLE energy.dbo.LP_INVOICE CHECK CONSTRAINT FK_LP_INVOICE_LP_LEGAL_PROCEEDING;
END
GO

IF EXISTS (SELECT 1 FROM #LpRestoreState WHERE CAN_RESTORE = 1)
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_LP_INCOME_LP_LEGAL_PROCEEDING')
BEGIN
    ALTER TABLE energy.dbo.LP_INCOME WITH CHECK
    ADD CONSTRAINT FK_LP_INCOME_LP_LEGAL_PROCEEDING
        FOREIGN KEY (LEGAL_PROCEEDING_ID) REFERENCES energy.dbo.LP_LEGAL_PROCEEDING (ID);
    ALTER TABLE energy.dbo.LP_INCOME CHECK CONSTRAINT FK_LP_INCOME_LP_LEGAL_PROCEEDING;
END
GO

IF EXISTS (SELECT 1 FROM #LpRestoreState WHERE CAN_RESTORE = 1)
   AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_LP_INCOME_LP_EXPENSE_CAUSE_PRM')
BEGIN
    ALTER TABLE energy.dbo.LP_INCOME WITH CHECK
    ADD CONSTRAINT FK_LP_INCOME_LP_EXPENSE_CAUSE_PRM
        FOREIGN KEY (EXPENSE_CAUSE_ID) REFERENCES energy.dbo.LP_EXPENSE_CAUSE_PRM (ID);
    ALTER TABLE energy.dbo.LP_INCOME CHECK CONSTRAINT FK_LP_INCOME_LP_EXPENSE_CAUSE_PRM;
END
GO

IF EXISTS (SELECT 1 FROM #LpRestoreState WHERE CAN_RESTORE = 1)
    PRINT 'LP FK geri yukleme scripti tamamlandi.';
ELSE
    PRINT 'LP FK geri yukleme tam yapilmadi. Once orphan kayitlar duzeltilmeli.';
GO

