-- =====================================================================================
-- LS_HHD_MSTR_GATE  (v04 — orphan gun grain + synth ACCRUE)
-- PASS:
--   TRAN_MAP + SKIP = LS_READING
--   SKIP sadece key-kirik (NO_MSTR_MATCH = 0 tercih)
--   MAP SRC_LREF unique
--   MSTR READ_NO unique / INT-safe
--   MSTR READ_NO monotonik READ_DATE (ORDER BY READ_DATE ...)
--   ORPHAN: (REGION, READ_DATE gun, PRSNL_ID, PRSNL, IS_SYNTH, ABYS_ACCRUE_TYPE_ID) tekil
--   ORPHAN READ_DATE = TRUNC(READ_DATE)  (saat yok)
--
-- Not: EOD/ORPHAN ara tablolari MSTR sonrasi DROP; sayimlar LS_OV_HHD_MSTR uzerinden
-- =====================================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========== HHD MSTR COUNTS ==========
SELECT 'LS_READING' K, COUNT(*) N FROM MIGRATION.LS_READING
UNION ALL SELECT 'MSTR_EOD', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR WHERE HAS_EOD = 1
UNION ALL SELECT 'MSTR_ORPHAN', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR WHERE HAS_EOD = 0
UNION ALL SELECT 'MSTR_SYNTH', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR WHERE NVL(IS_SYNTH, 0) = 1
UNION ALL SELECT 'MSTR_ALL', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR
UNION ALL SELECT 'TRAN_MAP', COUNT(*) FROM MIGRATION.LS_OV_HHD_TRAN_MAP
UNION ALL SELECT 'SKIP', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR_SKIP
UNION ALL SELECT 'SKIP_NO_MATCH', COUNT(*) FROM MIGRATION.LS_OV_HHD_MSTR_SKIP WHERE REASON = 'NO_MSTR_MATCH'
UNION ALL SELECT 'READING_READNO0', COUNT(*) FROM MIGRATION.LS_READING WHERE NVL(READ_NO,0) = 0
UNION ALL SELECT 'MAP_EOD', COUNT(*) FROM MIGRATION.LS_OV_HHD_TRAN_MAP WHERE MAP_KIND = 'EOD'
UNION ALL SELECT 'MAP_ORPHAN', COUNT(*) FROM MIGRATION.LS_OV_HHD_TRAN_MAP WHERE MAP_KIND = 'ORPHAN'
UNION ALL SELECT 'SYNTH_READING', COUNT(*) FROM MIGRATION.LS_READING WHERE ABYS_NOTE LIKE 'MIG_SYNTH%';

DECLARE
  n_rd   NUMBER;
  n_map  NUMBER;
  n_skip NUMBER;
  n_nom  NUMBER;
  n_dup  NUMBER;
  n_bad  NUMBER;
  n_rn0  NUMBER;
  n_mstr NUMBER;
  n_ord  NUMBER;
  n_orph_dup NUMBER;
  n_orph_tod NUMBER;
  v_note VARCHAR2(500);
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM MIGRATION.LS_READING' INTO n_rd;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM MIGRATION.LS_READING WHERE NVL(READ_NO,0) = 0' INTO n_rn0;

  SELECT COUNT(*) INTO n_map  FROM MIGRATION.LS_OV_HHD_TRAN_MAP;
  SELECT COUNT(*) INTO n_skip FROM MIGRATION.LS_OV_HHD_MSTR_SKIP;
  SELECT COUNT(*) INTO n_nom  FROM MIGRATION.LS_OV_HHD_MSTR_SKIP WHERE REASON = 'NO_MSTR_MATCH';
  SELECT COUNT(*) INTO n_mstr FROM MIGRATION.LS_OV_HHD_MSTR;

  SELECT COUNT(*) INTO n_dup FROM (
    SELECT SRC_LREF FROM MIGRATION.LS_OV_HHD_TRAN_MAP
    GROUP BY SRC_LREF HAVING COUNT(*) > 1
  );

  SELECT COUNT(*) INTO n_bad FROM MIGRATION.LS_OV_HHD_MSTR
  WHERE READ_NO IS NULL
     OR READ_NO < 1
     OR READ_NO > 2147483647;

  SELECT COUNT(*) INTO n_ord FROM (
    SELECT READ_NO, READ_DATE,
           LAG(READ_DATE) OVER (ORDER BY READ_NO) AS PREV_DT
    FROM MIGRATION.LS_OV_HHD_MSTR
  )
  WHERE PREV_DT IS NOT NULL
    AND READ_DATE < PREV_DT;

  -- ORPHAN: organik = gun+okuyucu; sentetik = + ABYS_ACCRUE_TYPE_ID
  SELECT COUNT(*) INTO n_orph_dup FROM (
    SELECT READER_REGION, READ_DATE, READER_PRSNL_ID, NVL(READER_PRSNL, CHR(0)),
           NVL(IS_SYNTH, 0), NVL(ABYS_ACCRUE_TYPE_ID, -1)
      FROM MIGRATION.LS_OV_HHD_MSTR
     WHERE HAS_EOD = 0
     GROUP BY READER_REGION, READ_DATE, READER_PRSNL_ID, NVL(READER_PRSNL, CHR(0)),
              NVL(IS_SYNTH, 0), NVL(ABYS_ACCRUE_TYPE_ID, -1)
    HAVING COUNT(*) > 1
  );

  SELECT COUNT(*) INTO n_orph_tod FROM MIGRATION.LS_OV_HHD_MSTR
   WHERE HAS_EOD = 0
     AND READ_DATE <> TRUNC(READ_DATE);

  IF n_map + n_skip <> n_rd THEN
    v_note := 'MAP(' || n_map || ')+SKIP(' || n_skip || ') <> READING(' || n_rd || ')';
    RAISE_APPLICATION_ERROR(-20101, 'GATE FAIL: ' || v_note);
  END IF;

  IF n_dup > 0 THEN
    RAISE_APPLICATION_ERROR(-20102, 'GATE FAIL: TRAN_MAP duplicate SRC_LREF=' || n_dup);
  END IF;

  IF n_bad > 0 THEN
    RAISE_APPLICATION_ERROR(-20103, 'GATE FAIL: MSTR READ_NO not INT-safe count=' || n_bad);
  END IF;

  IF n_nom > 0 THEN
    RAISE_APPLICATION_ERROR(-20104,
      'GATE FAIL: SKIP NO_MSTR_MATCH=' || n_nom || ' (key OK ama mstr eslesmedi)');
  END IF;

  IF n_ord > 0 THEN
    RAISE_APPLICATION_ERROR(-20105,
      'GATE FAIL: MSTR READ_NO not READ_DATE-ordered inversions=' || n_ord);
  END IF;

  IF n_orph_dup > 0 THEN
    RAISE_APPLICATION_ERROR(-20106,
      'GATE FAIL: ORPHAN duplicate day+reader(+accrue) grains=' || n_orph_dup);
  END IF;

  IF n_orph_tod > 0 THEN
    RAISE_APPLICATION_ERROR(-20107,
      'GATE FAIL: ORPHAN READ_DATE has time component count=' || n_orph_tod);
  END IF;

  v_note := 'rd=' || n_rd || ' map=' || n_map || ' skip=' || n_skip
         || ' mstr=' || n_mstr || ' read_no0=' || n_rn0;
  DBMS_OUTPUT.PUT_LINE('========== HHD MSTR GATE PASS | ' || v_note || ' ==========');
END;
/
