-- =============================================================================
-- oracleCTAS3007 / 34 — LS_OV_PAY_PT banka + PAID + LPD + XTYPE enrich (pilot)
-- Onkosul: O30 LS_OV_PAY_PT
-- Güvenli: kolon ADD + UPDATE (O30 şema kırılmaz)
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
  PROCEDURE add_col(p_col VARCHAR2, p_def VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM ALL_TAB_COLUMNS
     WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_PAY_PT' AND COLUMN_NAME=p_col;
    IF c = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE MIGRATION.LS_OV_PAY_PT ADD (' || p_col || ' ' || p_def || ')';
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_PAY_PT';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20034, 'LS_OV_PAY_PT yok — once O30.');
  END IF;
  add_col('BANKREF', 'NUMBER(12)');
  add_col('BANK_RECORD_REF', 'VARCHAR2(50)');
  add_col('LASTPAIDDATE', 'DATE');
  add_col('XTYPE', 'NUMBER(10)');
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O34', 'pay_pt_bank_paid', 'START', NULL,
      'PAID=PAYABLE + BANK/LPD/XTYPE');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- PAID + banka/makbuz/tarih/kanal — PDML 56
ALTER TABLE MIGRATION.LS_OV_PAY_PT PARALLEL 56;
MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(p 56) PARALLEL(s 56) */
 INTO MIGRATION.LS_OV_PAY_PT p
USING (
  SELECT /*+ PARALLEL(56) */
      pt.ROWID AS RID,
      act.BANK_ID AS BANKREF,
      CAST(SUBSTR(NVL(act.BANK_RECEIPT_NUMBER, TO_CHAR(act.RECEIPT_NUMBER)), 1, 50)
           AS VARCHAR2(50)) AS BANK_RECORD_REF
  FROM MIGRATION.LS_OV_PAY_PT pt
  LEFT JOIN SMS.CS_ACCOUNT_ACTION act ON act.ID = pt.ABYS_ID
) s
ON (p.ROWID = s.RID)
WHEN MATCHED THEN UPDATE SET
  p.PAID = CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.PAYABLETOTAL ELSE 0 END,
  p.BANKREF = COALESCE(s.BANKREF, p.BANKREF),
  p.BANK_RECORD_REF = COALESCE(s.BANK_RECORD_REF, p.BANK_RECORD_REF),
  p.LASTPAIDDATE = CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.DATE_ ELSE p.LASTPAIDDATE END,
  /* O30 XTYPE = PayType kanali; yoksa 1 */
  p.XTYPE = NVL(p.XTYPE, 1);

COMMIT;
ALTER TABLE MIGRATION.LS_OV_PAY_PT NOPARALLEL;

-- DEBT_PAID banka kolonları
-- Not: Oracle DECLARE'da değişkenler nested PROCEDURE'dan ÖNCE gelmeli
DECLARE
  n NUMBER;
  PROCEDURE add_col(p_col VARCHAR2, p_def VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM ALL_TAB_COLUMNS
     WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_DEBT_PAID_UPD' AND COLUMN_NAME=p_col;
    IF c = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE MIGRATION.LS_OV_DEBT_PAID_UPD ADD (' || p_col || ' ' || p_def || ')';
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_DEBT_PAID_UPD';
  IF n = 0 THEN RETURN; END IF;
  add_col('BANKREF', 'NUMBER(12)');
  add_col('BANK_RECORD_REF', 'VARCHAR2(50)');
  add_col('XTYPE', 'NUMBER(10)');
END;
/

ALTER TABLE MIGRATION.LS_OV_DEBT_PAID_UPD PARALLEL 56;
MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(d 56) PARALLEL(lp 56) */
 INTO MIGRATION.LS_OV_DEBT_PAID_UPD d
USING (
  SELECT /*+ PARALLEL(56) */ CROSSREF_MAIN_LREF AS MAIN_LREF,
         BANKREF, BANK_RECORD_REF,
         ROW_NUMBER() OVER (
           PARTITION BY CROSSREF_MAIN_LREF
           ORDER BY DATE_ DESC NULLS LAST, ABYS_ID DESC
         ) RN
    FROM MIGRATION.LS_OV_PAY_PT
   WHERE NVL(CANCELED,0)=0 AND OV_KIND='PAY' AND CROSSREF_MAIN_LREF IS NOT NULL
) lp
ON (d.MAIN_LREF = lp.MAIN_LREF AND lp.RN = 1)
WHEN MATCHED THEN UPDATE SET
  d.BANKREF = COALESCE(lp.BANKREF, d.BANKREF),
  d.BANK_RECORD_REF = COALESCE(lp.BANK_RECORD_REF, d.BANK_RECORD_REF),
  d.XTYPE = NVL(d.XTYPE, 1);

COMMIT;
ALTER TABLE MIGRATION.LS_OV_DEBT_PAID_UPD NOPARALLEL;

-- TAH_INV bank/LPD (O30 CTAS + O34 senkron; 597 TYPE=101 INSERT)
DECLARE
  n NUMBER;
  PROCEDURE add_col(p_col VARCHAR2, p_def VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM ALL_TAB_COLUMNS
     WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_TAH_INVOICE' AND COLUMN_NAME=p_col;
    IF c = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE MIGRATION.LS_OV_TAH_INVOICE ADD (' || p_col || ' ' || p_def || ')';
    END IF;
  END;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER='MIGRATION' AND TABLE_NAME='LS_OV_TAH_INVOICE';
  IF n = 0 THEN RETURN; END IF;
  add_col('BANKREF', 'NUMBER(12)');
  add_col('BANK_RECORD_REF', 'VARCHAR2(50)');
  add_col('LASTPAIDDATE', 'DATE');
END;
/

ALTER TABLE MIGRATION.LS_OV_TAH_INVOICE PARALLEL 56;
MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(t 56) PARALLEL(s 56) */
 INTO MIGRATION.LS_OV_TAH_INVOICE t
USING (
  SELECT /*+ PARALLEL(56) */
      tah.ROWID AS RID,
      pt.BANKREF,
      pt.BANK_RECORD_REF,
      CASE WHEN NVL(pt.CANCELED, 0) = 0 THEN pt.DATE_ ELSE CAST(NULL AS DATE) END AS LASTPAIDDATE
  FROM MIGRATION.LS_OV_TAH_INVOICE tah
  INNER JOIN MIGRATION.LS_OV_PAY_PT pt
    ON pt.INVOICEREF = tah.LREF
   AND pt.ALLOC_RN = 1
) s
ON (t.ROWID = s.RID)
WHEN MATCHED THEN UPDATE SET
  t.BANKREF = COALESCE(s.BANKREF, t.BANKREF),
  t.BANK_RECORD_REF = COALESCE(s.BANK_RECORD_REF, t.BANK_RECORD_REF),
  t.LASTPAIDDATE = COALESCE(s.LASTPAIDDATE, t.LASTPAIDDATE);

COMMIT;
ALTER TABLE MIGRATION.LS_OV_TAH_INVOICE NOPARALLEL;

DECLARE
  n NUMBER; n_paid NUMBER; n_bank NUMBER; n_tah_bank NUMBER;
BEGIN
  SELECT COUNT(*),
         COUNT(CASE WHEN NVL(PAID,0) > 0.01 THEN 1 END),
         COUNT(CASE WHEN BANKREF IS NOT NULL THEN 1 END)
    INTO n, n_paid, n_bank
    FROM MIGRATION.LS_OV_PAY_PT
   WHERE NVL(CANCELED,0)=0 AND OV_KIND='PAY';
  SELECT COUNT(CASE WHEN BANKREF IS NOT NULL THEN 1 END)
    INTO n_tah_bank
    FROM MIGRATION.LS_OV_TAH_INVOICE
   WHERE NVL(CANCELED,0)=0;
  MIGRATION.P_MIG_CTAS_LOG('O34', 'pay_pt_bank_paid', 'OK', n,
    'pay=' || n || ' paid_gt0=' || n_paid || ' bank=' || n_bank
    || ' tah_bank=' || n_tah_bank);
  DBMS_OUTPUT.PUT_LINE('========== O34 PAY_PT+TAH ENRICH OK | n=' || n
    || ' paid=' || n_paid || ' bank=' || n_bank
    || ' tah_bank=' || n_tah_bank || ' ==========');
END;
/
