-- =============================================================================
-- oracleCTAS3007 / 33 -- LS_INVOICE CLOSED + LASTPAIDDATE + BANK (pilot)
-- Onkosul: O11 LS_INVOICE, O30 LS_OV_PAY_PT, O32 LS_OV_DEBT_PAID_UPD
--
-- Pilot: O11 ham CLOSED=0 / LASTPAIDDATE=NULL -> ENERGY'de FRK/kapama sapmasi.
--         BANKREF/BANK_RECORD_REF son gecerli tip2/3 odemeden.
-- Amac : LS_INVOICE uzerine UPDATE (CTAS yeniden degil)
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_INVOICE';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20033, 'LS_INVOICE yok - once O11.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_DEBT_PAID_UPD';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20033, 'LS_OV_DEBT_PAID_UPD yok - once O30/O32.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O33', 'invoice_close_bank', 'START', NULL,
      'CLOSED+LPD+BANK from DEBT_PAID + last pay action');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- Son gecerli odeme (tip2 veya ACTION_TYPE=3) - MAIN grain
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_LAST_PAY PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O33_LAST_PAY NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */ *
FROM (
  SELECT
      p.CROSSREF_MAIN_LREF                                       AS MAIN_LREF,
      p.DATE_                                                    AS PAY_DATE,
      act.BANK_ID                                                AS BANKREF,
      CAST(SUBSTR(NVL(act.BANK_RECEIPT_NUMBER, TO_CHAR(act.RECEIPT_NUMBER)), 1, 50)
           AS VARCHAR2(50))                                      AS BANK_RECORD_REF,
      NVL(act.CASH_ID, 0)                                        AS CASH_ID,
      ROW_NUMBER() OVER (
        PARTITION BY p.CROSSREF_MAIN_LREF
        ORDER BY p.DATE_ DESC NULLS LAST, p.ABYS_ID DESC
      )                                                          AS RN
  FROM MIGRATION.LS_OV_PAY_PT p
  JOIN SMS.CS_ACCOUNT_ACTION act ON act.ID = p.ABYS_ID
  WHERE NVL(p.CANCELED, 0) = 0
    AND p.OV_KIND = 'PAY'
    AND p.CROSSREF_MAIN_LREF IS NOT NULL
)
WHERE RN = 1;

CREATE UNIQUE INDEX MIGRATION.IX_TMP_O33_LP ON MIGRATION.TMP_O33_LAST_PAY (MAIN_LREF) PARALLEL 56 NOLOGGING;
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX MIGRATION.IX_TMP_O33_LP NOPARALLEL'; END;
/

-- CLOSED / LPD / BANK / XTYPE patch (DEBT_PAID) — PDML 56
ALTER TABLE MIGRATION.LS_INVOICE PARALLEL 56;
MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(inv 56) PARALLEL(s 56) */
 INTO MIGRATION.LS_INVOICE inv
USING (
  SELECT /*+ PARALLEL(56) */
      d.MAIN_LREF,
      d.CLOSED,
      d.LASTPAIDDATE,
      lp.BANKREF,
      lp.BANK_RECORD_REF
  FROM MIGRATION.LS_OV_DEBT_PAID_UPD d
  LEFT JOIN MIGRATION.TMP_O33_LAST_PAY lp ON lp.MAIN_LREF = d.MAIN_LREF
) s
ON (inv.LREF = s.MAIN_LREF AND NVL(inv.IOCODE, 0) = 0)
WHEN MATCHED THEN UPDATE SET
  inv.CLOSED = DECODE(NVL(s.CLOSED, 0), 1, 1, inv.CLOSED),
  inv.LASTPAIDDATE = COALESCE(s.LASTPAIDDATE, inv.LASTPAIDDATE),
  inv.BANKREF = COALESCE(s.BANKREF, inv.BANKREF),
  inv.BANK_RECORD_REF = COALESCE(s.BANK_RECORD_REF, inv.BANK_RECORD_REF),
  inv.XTYPE = NVL(inv.XTYPE, 1);

COMMIT;

-- CLOSED_CALC: sadece HALA ACIK fatura hesaplari (tum SMS ledger degil)
-- Bakiye ~0 olanlari kapat (pilot SyncClosedFromMgr)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_OPEN_ACC PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O33_OPEN_ACC NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */ DISTINCT ABYS_ACCOUNT_ID AS ACCOUNT_ID
FROM MIGRATION.LS_INVOICE
WHERE NVL(IOCODE, 0) = 0
  AND NVL(CANCELED, 0) = 0
  AND NVL(CLOSED, 0) = 0
  AND ABYS_ACCOUNT_ID IS NOT NULL;

CREATE UNIQUE INDEX MIGRATION.IX_TMP_O33_OA ON MIGRATION.TMP_O33_OPEN_ACC (ACCOUNT_ID) PARALLEL 56 NOLOGGING;
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX MIGRATION.IX_TMP_O33_OA NOPARALLEL'; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_BAL PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O33_BAL NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) LEADING(oa aa ai) USE_HASH(aa ai) */
    oa.ACCOUNT_ID,
    CAST(ROUND(SUM(ai.STATUS * ai.AMOUNT), 2) AS NUMBER(15,3)) AS BALANCE
FROM MIGRATION.TMP_O33_OPEN_ACC oa
JOIN SMS.CS_ACCOUNT_ACTION aa ON aa.ACCOUNT_ID = oa.ACCOUNT_ID
JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aa.ID
GROUP BY oa.ACCOUNT_ID
HAVING ABS(ROUND(SUM(ai.STATUS * ai.AMOUNT), 2)) <= 0.01;

CREATE UNIQUE INDEX MIGRATION.IX_TMP_O33_BAL ON MIGRATION.TMP_O33_BAL (ACCOUNT_ID) PARALLEL 56 NOLOGGING;
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX MIGRATION.IX_TMP_O33_BAL NOPARALLEL'; END;
/

-- Sadece zero-balance hesaplar; CASE..END yok (SQL Developer ORA-00911)
UPDATE /*+ ENABLE_PARALLEL_DML PARALLEL(inv 56) */
       MIGRATION.LS_INVOICE inv
   SET inv.CLOSED = 1
 WHERE NVL(inv.IOCODE, 0) = 0
   AND NVL(inv.CANCELED, 0) = 0
   AND NVL(inv.CLOSED, 0) = 0
   AND EXISTS (
         SELECT /*+ HASH_SJ */ 1
           FROM MIGRATION.TMP_O33_BAL b
          WHERE b.ACCOUNT_ID = inv.ABYS_ACCOUNT_ID
       );

COMMIT;
ALTER TABLE MIGRATION.LS_INVOICE NOPARALLEL;

-- LS_DEBT_PAYTRANS varsa banka/LPD hizala (O14 erken calistiysa)
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_DEBT_PAYTRANS';
  IF n > 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE MIGRATION.LS_DEBT_PAYTRANS PARALLEL 56
    ]';
    EXECUTE IMMEDIATE q'[
      MERGE /*+ ENABLE_PARALLEL_DML PARALLEL(pt 56) PARALLEL(s 56) */
       INTO MIGRATION.LS_DEBT_PAYTRANS pt
      USING (
        SELECT /*+ PARALLEL(56) */ inv.LREF, inv.BANKREF, inv.BANK_RECORD_REF, inv.LASTPAIDDATE, inv.XTYPE,
               d.PAID_AMT, d.CLOSED
          FROM MIGRATION.LS_INVOICE inv
          LEFT JOIN MIGRATION.LS_OV_DEBT_PAID_UPD d ON d.MAIN_LREF = inv.LREF
         WHERE NVL(inv.IOCODE,0)=0
      ) s
      ON (pt.INVOICEREF = s.LREF)
      WHEN MATCHED THEN UPDATE SET
        pt.BANKREF = COALESCE(s.BANKREF, pt.BANKREF),
        pt.BANK_RECORD_REF = COALESCE(s.BANK_RECORD_REF, pt.BANK_RECORD_REF),
        pt.LASTPAIDDATE = COALESCE(s.LASTPAIDDATE, pt.LASTPAIDDATE),
        pt.XTYPE = NVL(COALESCE(pt.XTYPE, s.XTYPE), 1),
        pt.PAID = DECODE(NVL(s.CLOSED,0), 1, pt.PAYABLETOTAL, pt.PAID)
    ]';
    COMMIT;
    EXECUTE IMMEDIATE q'[ALTER TABLE MIGRATION.LS_DEBT_PAYTRANS NOPARALLEL]';
  END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_LAST_PAY PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_OPEN_ACC PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O33_BAL PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

DECLARE
  n_closed NUMBER; n_lpd NUMBER; n_bank NUMBER;
BEGIN
  SELECT
    COUNT(CASE WHEN NVL(CLOSED,0)=1 THEN 1 END),
    COUNT(CASE WHEN LASTPAIDDATE IS NOT NULL THEN 1 END),
    COUNT(CASE WHEN BANKREF IS NOT NULL THEN 1 END)
  INTO n_closed, n_lpd, n_bank
  FROM MIGRATION.LS_INVOICE
  WHERE NVL(IOCODE,0)=0 AND NVL(CANCELED,0)=0;

  MIGRATION.P_MIG_CTAS_LOG('O33', 'invoice_close_bank', 'OK', n_closed,
    'closed=' || n_closed || ' lpd=' || n_lpd || ' bank=' || n_bank);
  DBMS_OUTPUT.PUT_LINE('========== O33 INVOICE CLOSE/BANK OK | closed='
    || n_closed || ' lpd=' || n_lpd || ' bank=' || n_bank || ' ==========');
END;
/
