-- oracleCTAS3007 / 99 — CTAS log ozeti (salt okuma)
-- Satir / boyut / baslangic / bitis / sure
SET PAGESIZE 200
SET LINESIZE 260
COLUMN STEP_ID FORMAT A8
COLUMN STATUS FORMAT A12
COLUMN STEP_NAME FORMAT A28
COLUMN TABLE_NAME FORMAT A36
COLUMN NOTE FORMAT A50
COLUMN LOG_TS FORMAT A28
COLUMN START_TS FORMAT A28
COLUMN END_TS FORMAT A28
COLUMN SIZE_MB FORMAT 999,990.99
COLUMN ELAPSED_SEC FORMAT 999,990.99
COLUMN ROW_CNT FORMAT 999,999,999,990

PROMPT ========== MIG_CTAS_LOG — son 60 (ham) ==========
SELECT LOG_ID, LOG_TS, STEP_ID, STATUS, STEP_NAME, ROW_CNT, SIZE_MB, ELAPSED_SEC, TABLE_NAME, NOTE
FROM (
  SELECT LOG_ID, LOG_TS, STEP_ID, STATUS, STEP_NAME, ROW_CNT, SIZE_MB, ELAPSED_SEC, TABLE_NAME, NOTE
  FROM MIGRATION.MIG_CTAS_LOG
  ORDER BY LOG_ID DESC
)
WHERE ROWNUM <= 60
ORDER BY LOG_ID;

PROMPT ========== Adim ozeti (OK/DONE — sure + satir + MB) ==========
SELECT STEP_ID, STEP_NAME, STATUS, ROW_CNT, SIZE_MB,
       START_TS, END_TS, ELAPSED_SEC, TABLE_NAME
FROM (
  SELECT STEP_ID, STEP_NAME, STATUS, ROW_CNT, SIZE_MB,
         START_TS, END_TS, ELAPSED_SEC, TABLE_NAME, LOG_ID,
         ROW_NUMBER() OVER (
           PARTITION BY STEP_ID
           ORDER BY CASE WHEN STATUS = 'OK' THEN 1 WHEN STATUS LIKE 'GATE%' THEN 2 ELSE 3 END,
                    LOG_ID DESC
         ) RN
  FROM MIGRATION.MIG_CTAS_LOG
  WHERE STATUS IN ('OK', 'GATE_PASS', 'GATE_FAIL', 'FAIL')
)
WHERE RN = 1
ORDER BY LOG_ID;

PROMPT ========== Timeline (START → OK eslestirme) ==========
-- ORA-01799: LEFT JOIN ON ... = (subquery) yasak → end_id CTE ile
WITH s AS (
  SELECT STEP_ID, STEP_NAME, LOG_TS AS START_TS, LOG_ID
  FROM MIGRATION.MIG_CTAS_LOG
  WHERE STATUS = 'START'
),
end_id AS (
  SELECT s.LOG_ID AS START_LOG_ID,
         MAX(e2.LOG_ID) AS END_LOG_ID
  FROM s
  JOIN MIGRATION.MIG_CTAS_LOG e2
    ON e2.STEP_ID = s.STEP_ID
   AND e2.LOG_ID > s.LOG_ID
   AND e2.STATUS IN ('OK', 'GATE_PASS', 'GATE_FAIL', 'FAIL')
  GROUP BY s.LOG_ID
),
e AS (
  SELECT STEP_ID, STATUS, ROW_CNT, SIZE_MB, BYTES, TABLE_NAME,
         NVL(END_TS, LOG_TS) AS END_TS, ELAPSED_SEC, LOG_ID, NOTE
  FROM MIGRATION.MIG_CTAS_LOG
  WHERE STATUS IN ('OK', 'GATE_PASS', 'GATE_FAIL', 'FAIL')
)
SELECT s.STEP_ID,
       s.STEP_NAME,
       s.START_TS,
       e.END_TS,
       NVL(e.ELAPSED_SEC,
           ROUND(EXTRACT(DAY FROM (e.END_TS - s.START_TS)) * 86400
               + EXTRACT(HOUR FROM (e.END_TS - s.START_TS)) * 3600
               + EXTRACT(MINUTE FROM (e.END_TS - s.START_TS)) * 60
               + EXTRACT(SECOND FROM (e.END_TS - s.START_TS)), 2)
       ) AS ELAPSED_SEC,
       e.ROW_CNT,
       e.SIZE_MB,
       e.TABLE_NAME,
       e.STATUS
FROM s
LEFT JOIN end_id x ON x.START_LOG_ID = s.LOG_ID
LEFT JOIN e ON e.LOG_ID = x.END_LOG_ID
ORDER BY s.LOG_ID;

PROMPT ========== GATE / FAIL var mi? ==========
SELECT STEP_ID, STATUS, NOTE, LOG_TS, ELAPSED_SEC
FROM MIGRATION.MIG_CTAS_LOG
WHERE STATUS IN ('FAIL', 'GATE_FAIL')
ORDER BY LOG_ID DESC;

PROMPT ========== Toplam (OK wrap adimlari) ==========
SELECT COUNT(*) AS OK_STEPS,
       SUM(ROW_CNT) AS SUM_ROWS,
       ROUND(SUM(NVL(SIZE_MB, 0)), 2) AS SUM_MB,
       ROUND(SUM(NVL(ELAPSED_SEC, 0)), 2) AS SUM_SEC
FROM (
  SELECT STEP_ID, ROW_CNT, SIZE_MB, ELAPSED_SEC,
         ROW_NUMBER() OVER (PARTITION BY STEP_ID ORDER BY LOG_ID DESC) RN
  FROM MIGRATION.MIG_CTAS_LOG
  WHERE STATUS = 'OK'
    AND ELAPSED_SEC IS NOT NULL
)
WHERE RN = 1;
/
