-- =============================================================================
-- oracleCTAS3007 / VERIFY_SYNTH_GAP.sql
-- Spot: gap CNT, ACCRUE doluluk, GATE (ayri), TYPE/EXPLAIN, READ_TRANSREF
-- =============================================================================
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========== 1) ABYS_ACCRUE_TYPE_ID doluluk ==========
SELECT
  SUM(CASE WHEN ABYS_ACCRUE_TYPE_ID IS NOT NULL THEN 1 ELSE 0 END) AS ACCRUE_OK,
  SUM(CASE WHEN ABYS_ACCRUE_TYPE_ID IS NULL THEN 1 ELSE 0 END) AS ACCRUE_NULL,
  SUM(CASE WHEN ABYS_NOTE LIKE 'MIG_SYNTH%' THEN 1 ELSE 0 END) AS SYNTH_N,
  COUNT(*) AS TOTAL
FROM MIGRATION.LS_READING;

PROMPT ========== 2) Gap CNT = NEEDS_READING ∩ okumasız (synth sonrasi 0 olmali) ==========
SELECT COUNT(*) AS REMAINING_GAP
FROM SMS.CS_ACCOUNT acc
JOIN MIGRATION.MIG_ACCRUE_TYPE_MAP map
  ON map.ABYS_ACCRUE_TYPE_ID = acc.ACCRUE_TYPE_ID
 AND map.NEEDS_READING = 1
WHERE NOT EXISTS (
  SELECT 1 FROM MIGRATION.LS_READING r
   WHERE r.ABYS_ACCOUNT_ID = acc.ID
);

PROMPT ========== 3) Map seed ==========
SELECT COUNT(*) AS MAP_ROWS FROM MIGRATION.MIG_ACCRUE_TYPE_MAP;
SELECT ABYS_ACCRUE_TYPE_ID, PCMS_TYPE, EXPLAIN_PREFIX, EXPLAIN_FMT, NEEDS_READING
  FROM MIGRATION.MIG_ACCRUE_TYPE_MAP
 ORDER BY ABYS_ACCRUE_TYPE_ID;

PROMPT ========== 4) O11 TYPE/EXPLAIN / READ_TRANSREF spot (NEEDS_READING) ==========
SELECT *
  FROM (
    SELECT inv.LREF, inv.ABYS_ACCOUNT_ID, inv.ABYS_ACCRUE_TYPE_ID,
           inv.TYPE, inv.EXPLAIN, inv.READ_TRANSREF,
           map.PCMS_TYPE, map.EXPLAIN_PREFIX
      FROM MIGRATION.LS_INVOICE inv
      JOIN MIGRATION.MIG_ACCRUE_TYPE_MAP map
        ON map.ABYS_ACCRUE_TYPE_ID = inv.ABYS_ACCRUE_TYPE_ID
     WHERE map.NEEDS_READING = 1
       AND inv.READ_TRANSREF IS NOT NULL
     ORDER BY inv.LREF DESC
  )
 WHERE ROWNUM <= 20;

PROMPT ========== 5) Synth READ_TRANSREF = sentetik LREF ==========
SELECT COUNT(*) AS SYNTH_LINKED
  FROM MIGRATION.LS_INVOICE inv
  JOIN MIGRATION.LS_READING r ON r.LREF = inv.READ_TRANSREF
 WHERE r.ABYS_NOTE LIKE 'MIG_SYNTH%';

PROMPT ========== 6) Katalog IX spot ==========
SELECT INDEX_NAME, TABLE_NAME
  FROM ALL_INDEXES
 WHERE OWNER = 'MIGRATION'
   AND (
        INDEX_NAME LIKE 'IX_LS_READING%'
     OR INDEX_NAME LIKE '%HHD_MSTR%'
     OR INDEX_NAME LIKE '%HHD_TRAN_MAP%'
   )
 ORDER BY 1;

PROMPT ========== VERIFY_SYNTH_GAP DONE — sonra @LS_HHD_MSTR_GATE.sql ==========
/
