-- =============================================================================
-- prodREADY / 41 — GATE tahsilat HARD
-- PASS: PAY_PT = PAY_ALLOC; CROSSREF_MAIN NULL = 0
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED

BEGIN
  MIGRATION.P_MIG_CTAS_LOG('O41', 'gate_tahsilat', 'START', NULL, 'hard gate');
END;
/

SELECT 'PAY_PT' K, COUNT(*) N FROM MIGRATION.LS_OV_PAY_PT
UNION ALL SELECT 'PAY_OK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_CANC', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE NVL(CANCELED,0)=1
UNION ALL SELECT 'PAY_BANK', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='PAY' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_MAHSUP', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE OV_KIND='MAHSUP' AND NVL(CANCELED,0)=0
UNION ALL SELECT 'PAY_NO_XREF', COUNT(*) FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL
UNION ALL SELECT 'PAY_ALLOC', COUNT(*) FROM MIGRATION.LS_OV_PAY_ALLOC
UNION ALL SELECT 'CANCEL_PAY', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_PAY
UNION ALL SELECT 'CANCEL_REV', COUNT(*) FROM MIGRATION.LS_OV_CANCEL_REV
UNION ALL SELECT 'MAP_ROWS', COUNT(*) FROM MIGRATION.LS_OV_ID_MAP;

DECLARE
  n_pt NUMBER; n_al NUMBER; n_xr NUMBER; n_multi NUMBER; n_map NUMBER;
  v_note VARCHAR2(400);
BEGIN
  SELECT COUNT(*) INTO n_pt FROM MIGRATION.LS_OV_PAY_PT;
  SELECT COUNT(*) INTO n_al FROM MIGRATION.LS_OV_PAY_ALLOC;
  SELECT COUNT(*) INTO n_xr FROM MIGRATION.LS_OV_PAY_PT WHERE CROSSREF_MAIN_LREF IS NULL;
  SELECT COUNT(*) INTO n_multi FROM (
    SELECT PAY_LREF FROM MIGRATION.LS_OV_PAY_ALLOC GROUP BY PAY_LREF HAVING COUNT(*) > 1
  );
  SELECT COUNT(*) INTO n_map FROM MIGRATION.LS_OV_ID_MAP;

  IF n_pt <> n_al THEN
    v_note := 'PAY_PT(' || n_pt || ') <> PAY_ALLOC(' || n_al || ')';
    MIGRATION.P_MIG_CTAS_LOG('O41', 'gate_tahsilat', 'GATE_FAIL', n_pt, v_note);
    RAISE_APPLICATION_ERROR(-20051, 'GATE FAIL: ' || v_note);
  END IF;
  IF n_xr > 0 THEN
    v_note := 'PAY_NO_XREF=' || n_xr;
    MIGRATION.P_MIG_CTAS_LOG('O41', 'gate_tahsilat', 'GATE_FAIL', n_xr, v_note);
    RAISE_APPLICATION_ERROR(-20052, 'GATE FAIL: ' || v_note);
  END IF;

  v_note := 'pt=' || n_pt || ' alloc=' || n_al || ' multi=' || n_multi
         || ' map=' || n_map || ' (multi soft)';
  MIGRATION.P_MIG_CTAS_LOG('O41', 'gate_tahsilat', 'GATE_PASS', n_pt, v_note);
  DBMS_OUTPUT.PUT_LINE('========== O41 GATE TAHSILAT PASS | ' || v_note || ' ==========');
END;
/
