-- =============================================================================
-- prodREADY / 51 — STG INV PAY CLOSE (energy temizligi ara tablo)
-- Ortam : Oracle 11.2 | Schema: MIGRATION
-- Onkosul: O11 LS_INVOICE, O30 LS_OV_PAY_PT, O30/O32 LS_OV_DEBT_PAID_UPD, O50 LS_AFL_OPEN_DEBT
--
-- Grain : MAIN_LREF = LS_INVOICE.LREF  (energy: LS_005_01_INVOICE.LREF)
-- Amac  : TYPE kullanmadan banka-borc 2 kontrol icin hizli join ara tablo
--         1) PAYTRANS PAID ≈ PAYABLETOTAL
--         2) INVOICE CLOSED + LASTPAIDDATE
--
-- Tahsilat kimlik (ayri kavramlar — karistirma):
--   BANKA_ID / BANKA_CODE / BANKA  ← banka (BANK_ID + IT_BANK_PRM)  ≠ kisi degil
--   VEZNE_ID / VEZNE_CODE / VEZNE  ← vezne/kasa (CASH_ID + IT_CASH_PRM)  ≠ kisi degil
--   USERID          ← CREATED_USER_ID (ilk kayit; TEK BASINA GUVENME)
--   UPDATED_USER_ID ← son guncelleyen (CREATED ile farkli olabilir)
--   TAH_MAKBUZ_NO / TAH_MAKBUZ_SERIAL ← RECEIPT_NUMBER / RECEIPT_SERIAL
--   BANK_RECORD_REF ← BANK_RECEIPT_NUMBER
--
-- Kisi alanlari (SMS.CS_ACCOUNT_ACTION — projede bilinen):
--   CREATED_USER_ID, UPDATED_USER_ID
--   Iptal kisi: tip9 iptal action'inin kendi CREATED_USER_ID'si (odeme satirinda degil)
--   Tam liste icin: SELECT COLUMN_NAME FROM ALL_TAB_COLUMNS
--                   WHERE OWNER='SMS' AND TABLE_NAME='CS_ACCOUNT_ACTION'
--                     AND COLUMN_NAME LIKE '%USER%';
--
-- FIX_KIND:
--   AFL_OPEN   — AFL master acik → energy'de acik kalsin (dokunma)
--   CLOSE_FULL — OV_PAID >= PAYABLE - 0.01 → tam kapama
--   CLOSE_EPS  — OV_PAID >= PAYABLE - EPS (0.50) → kurus bandi kapama
--   KEEP_OPEN  — kismi / yetersiz odeme
--   NO_PAY     — odeme yok (PAYABLE>0)
--
-- Dump → izgazMGR.dbo.LS_STG_INV_PAY_CLOSE
-- DOP: FORCE 56
-- =============================================================================

WHENEVER SQLERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_INVOICE';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20051, 'MIGRATION.LS_INVOICE yok — once O11.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_PAY_PT';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20051, 'MIGRATION.LS_OV_PAY_PT yok — once O30.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_DEBT_PAID_UPD';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20051, 'MIGRATION.LS_OV_DEBT_PAID_UPD yok — once O30/O32.');
  END IF;
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_AFL_OPEN_DEBT';
  IF n = 0 THEN
    RAISE_APPLICATION_ERROR(-20051, 'MIGRATION.LS_AFL_OPEN_DEBT yok — once O50.');
  END IF;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O51', 'stg_inv_pay_close', 'START', NULL,
      'MAIN grain + AFL + PAY_PT + DEBT_PAID');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- =============================================================================
-- 0) PAY_PT aggregate + son odeme satiri
--    banka / vezne / tahsilat makbuz / BANK_RECORD_REF  (CS_ACCOUNT_ACTION)
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_PAY_AGG PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_STG_PAY_AGG NOLOGGING PARALLEL 56 AS
SELECT /*+ PARALLEL(56) */
    p.CROSSREF_MAIN_LREF                                         AS MAIN_LREF,
    MAX(p.ABYS_ACCOUNT_ID)                                       AS FATURAID,
    MAX(p.ABYS_AGREEMENT_ID)                                     AS SOZLESME,
    CAST(ROUND(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0
                        THEN p.PAYABLETOTAL ELSE 0 END), 2)
         AS NUMBER(15,3))                                        AS OV_PAID_AMT,
    CAST(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN 1 ELSE 0 END)
         AS NUMBER(10))                                          AS OV_PAY_CNT,
    MAX(CASE WHEN NVL(p.CANCELED, 0) = 0 THEN p.DATE_ END)       AS OV_LAST_PAY_DATE,
    CAST(ROUND(SUM(CASE WHEN NVL(p.CANCELED, 0) = 0
                        THEN NVL(p.PAY_FULL_AMT, 0) ELSE 0 END), 2)
         AS NUMBER(15,3))                                        AS OV_PAY_FULL_SUM
FROM MIGRATION.LS_OV_PAY_PT p
WHERE p.CROSSREF_MAIN_LREF IS NOT NULL
GROUP BY p.CROSSREF_MAIN_LREF;

CREATE UNIQUE INDEX MIGRATION.IX_TMP_STG_PAY_AGG
  ON MIGRATION.TMP_STG_PAY_AGG (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_STG_PAY_AGG NOPARALLEL;
/

/* Banka adi: SMS.IT_BANK_PRM(+_LNG) varsa kullan */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_BANK_NM PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'SMS' AND TABLE_NAME = 'IT_BANK_PRM';
  IF n > 0 THEN
    SELECT COUNT(*) INTO n FROM ALL_TABLES
     WHERE OWNER = 'SMS' AND TABLE_NAME = 'IT_BANK_PRM_LNG';
    IF n > 0 THEN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE MIGRATION.TMP_STG_BANK_NM NOLOGGING PARALLEL 56 AS
        SELECT /*+ PARALLEL(56) */
            CAST(b.ID AS NUMBER(12)) AS BANKA_ID,
            CAST(SUBSTR(b.CODE, 1, 40) AS VARCHAR2(40)) AS BANKA_CODE,
            CAST(SUBSTR(NVL(l.VALUE, b.CODE), 1, 100) AS VARCHAR2(100)) AS BANKA
        FROM SMS.IT_BANK_PRM b
        LEFT JOIN SMS.IT_BANK_PRM_LNG l
          ON l.PRM_ID = b.ID AND l.LANG_ID = 1
      ]';
    ELSE
      EXECUTE IMMEDIATE q'[
        CREATE TABLE MIGRATION.TMP_STG_BANK_NM NOLOGGING PARALLEL 56 AS
        SELECT /*+ PARALLEL(56) */
            CAST(b.ID AS NUMBER(12)) AS BANKA_ID,
            CAST(SUBSTR(b.CODE, 1, 40) AS VARCHAR2(40)) AS BANKA_CODE,
            CAST(SUBSTR(b.CODE, 1, 100) AS VARCHAR2(100)) AS BANKA
        FROM SMS.IT_BANK_PRM b
      ]';
    END IF;
  ELSE
    EXECUTE IMMEDIATE q'[
      CREATE TABLE MIGRATION.TMP_STG_BANK_NM NOLOGGING AS
      SELECT CAST(NULL AS NUMBER(12)) AS BANKA_ID,
             CAST(NULL AS VARCHAR2(40)) AS BANKA_CODE,
             CAST(NULL AS VARCHAR2(100)) AS BANKA
      FROM DUAL WHERE 1 = 0
    ]';
  END IF;
END;
/
CREATE UNIQUE INDEX MIGRATION.IX_TMP_STG_BANK_NM
  ON MIGRATION.TMP_STG_BANK_NM (BANKA_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_STG_BANK_NM NOPARALLEL;
/

/* Vezne adi: SMS.IT_CASH_PRM(+_LNG) veya CS_CASH varsa */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_CASH_NM PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
DECLARE
  n NUMBER;
  v_sql VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES
   WHERE OWNER = 'SMS' AND TABLE_NAME = 'IT_CASH_PRM';
  IF n > 0 THEN
    SELECT COUNT(*) INTO n FROM ALL_TABLES
     WHERE OWNER = 'SMS' AND TABLE_NAME = 'IT_CASH_PRM_LNG';
    IF n > 0 THEN
      v_sql := q'[
        CREATE TABLE MIGRATION.TMP_STG_CASH_NM NOLOGGING PARALLEL 56 AS
        SELECT /*+ PARALLEL(56) */
            CAST(c.ID AS NUMBER(12)) AS VEZNE_ID,
            CAST(SUBSTR(c.CODE, 1, 40) AS VARCHAR2(40)) AS VEZNE_CODE,
            CAST(SUBSTR(NVL(l.VALUE, c.CODE), 1, 100) AS VARCHAR2(100)) AS VEZNE
        FROM SMS.IT_CASH_PRM c
        LEFT JOIN SMS.IT_CASH_PRM_LNG l
          ON l.PRM_ID = c.ID AND l.LANG_ID = 1
      ]';
    ELSE
      v_sql := q'[
        CREATE TABLE MIGRATION.TMP_STG_CASH_NM NOLOGGING PARALLEL 56 AS
        SELECT /*+ PARALLEL(56) */
            CAST(c.ID AS NUMBER(12)) AS VEZNE_ID,
            CAST(SUBSTR(c.CODE, 1, 40) AS VARCHAR2(40)) AS VEZNE_CODE,
            CAST(SUBSTR(c.CODE, 1, 100) AS VARCHAR2(100)) AS VEZNE
        FROM SMS.IT_CASH_PRM c
      ]';
    END IF;
    EXECUTE IMMEDIATE v_sql;
  ELSE
    /* IT_CASH_PRM yoksa VEZNE adi bos; VEZNE_ID yine CASH_ID'den gelir */
    EXECUTE IMMEDIATE q'[
      CREATE TABLE MIGRATION.TMP_STG_CASH_NM NOLOGGING AS
      SELECT CAST(NULL AS NUMBER(12)) AS VEZNE_ID,
             CAST(NULL AS VARCHAR2(40)) AS VEZNE_CODE,
             CAST(NULL AS VARCHAR2(100)) AS VEZNE
      FROM DUAL WHERE 1 = 0
    ]';
  END IF;
END;
/
CREATE UNIQUE INDEX MIGRATION.IX_TMP_STG_CASH_NM
  ON MIGRATION.TMP_STG_CASH_NM (VEZNE_ID) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_STG_CASH_NM NOPARALLEL;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_PAY_LAST PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
DECLARE
  n_ser NUMBER;
  v_ser_expr VARCHAR2(200);
BEGIN
  SELECT COUNT(*) INTO n_ser FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'SMS' AND TABLE_NAME = 'CS_ACCOUNT_ACTION'
     AND COLUMN_NAME = 'RECEIPT_SERIAL';
  IF n_ser > 0 THEN
    v_ser_expr := 'CAST(SUBSTR(TO_CHAR(aa.RECEIPT_SERIAL), 1, 20) AS VARCHAR2(20))';
  ELSE
    v_ser_expr := 'CAST(NULL AS VARCHAR2(20))';
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE MIGRATION.TMP_STG_PAY_LAST NOLOGGING PARALLEL 56 AS
    SELECT /*+ PARALLEL(56) */
        x.MAIN_LREF,
        x.LAST_PAYTYPE,
        x.LAST_OV_KIND,
        x.LAST_PAY_LREF,
        x.LAST_BANK_PAY_DATE,
        x.BANKA_ID,
        x.VEZNE_ID,
        x.USERID,
        x.UPDATED_USER_ID,
        x.TAH_MAKBUZ_SERIAL,
        x.TAH_MAKBUZ_NO,
        x.BANK_RECORD_REF,
        CAST(bn.BANKA_CODE AS VARCHAR2(40))                       AS BANKA_CODE,
        CAST(bn.BANKA AS VARCHAR2(100))                           AS BANKA,
        CAST(cn.VEZNE_CODE AS VARCHAR2(40))                       AS VEZNE_CODE,
        CAST(cn.VEZNE AS VARCHAR2(100))                           AS VEZNE
    FROM (
        SELECT
            p.CROSSREF_MAIN_LREF                                  AS MAIN_LREF,
            CAST(p.PAYTYPE AS NUMBER(10))                         AS LAST_PAYTYPE,
            CAST(p.OV_KIND AS VARCHAR2(10))                       AS LAST_OV_KIND,
            CAST(p.INVOICEREF AS NUMBER(12))                      AS LAST_PAY_LREF,
            aa.BANK_PAYMENT_DATE                                  AS LAST_BANK_PAY_DATE,
            CAST(aa.BANK_ID AS NUMBER(12))                        AS BANKA_ID,
            CAST(NVL(aa.CASH_ID, p.CASH_ID) AS NUMBER(12))        AS VEZNE_ID,
            /* kisi: CREATED kalsin; UPDATED ayri — tekine guvenme */
            CAST(aa.CREATED_USER_ID AS NUMBER(12))                AS USERID,
            CAST(aa.UPDATED_USER_ID AS NUMBER(12))                AS UPDATED_USER_ID,
            ' || v_ser_expr || '                                  AS TAH_MAKBUZ_SERIAL,
            CAST(SUBSTR(TO_CHAR(NVL(aa.RECEIPT_NUMBER, p.RECEIPT_NUMBER)), 1, 50)
                 AS VARCHAR2(50))                                 AS TAH_MAKBUZ_NO,
            CAST(SUBSTR(TO_CHAR(aa.BANK_RECEIPT_NUMBER), 1, 50)
                 AS VARCHAR2(50))                                 AS BANK_RECORD_REF,
            ROW_NUMBER() OVER (
              PARTITION BY p.CROSSREF_MAIN_LREF
              ORDER BY p.DATE_ DESC NULLS LAST, p.SRC_KEY DESC
            )                                                     AS RN
        FROM MIGRATION.LS_OV_PAY_PT p
        LEFT JOIN SMS.CS_ACCOUNT_ACTION aa
          ON aa.ID = p.INVOICEREF
        WHERE p.CROSSREF_MAIN_LREF IS NOT NULL
          AND NVL(p.CANCELED, 0) = 0
    ) x
    LEFT JOIN MIGRATION.TMP_STG_BANK_NM bn ON bn.BANKA_ID = x.BANKA_ID
    LEFT JOIN MIGRATION.TMP_STG_CASH_NM cn ON cn.VEZNE_ID = x.VEZNE_ID
    WHERE x.RN = 1
  ';
END;
/
CREATE UNIQUE INDEX MIGRATION.IX_TMP_STG_PAY_LAST
  ON MIGRATION.TMP_STG_PAY_LAST (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_STG_PAY_LAST NOPARALLEL;
/

-- DEBT_PAID normalize (LASTPAIDDATE yoksa NULL — eski dump dayanikli)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_DEBT PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
DECLARE
  n_lpd NUMBER;
BEGIN
  SELECT COUNT(*) INTO n_lpd FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'MIGRATION' AND TABLE_NAME = 'LS_OV_DEBT_PAID_UPD'
     AND COLUMN_NAME = 'LASTPAIDDATE';
  IF n_lpd > 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE MIGRATION.TMP_STG_DEBT NOLOGGING PARALLEL 56 AS
      SELECT /*+ PARALLEL(56) */
          CAST(MAIN_LREF AS NUMBER(12)) AS MAIN_LREF,
          CAST(CLOSED AS NUMBER(1))     AS CLOSED,
          LASTPAIDDATE                  AS LASTPAIDDATE,
          CAST(PAID_AMT AS NUMBER(15,3)) AS PAID_AMT
      FROM MIGRATION.LS_OV_DEBT_PAID_UPD
    ]';
  ELSE
    EXECUTE IMMEDIATE q'[
      CREATE TABLE MIGRATION.TMP_STG_DEBT NOLOGGING PARALLEL 56 AS
      SELECT /*+ PARALLEL(56) */
          CAST(MAIN_LREF AS NUMBER(12)) AS MAIN_LREF,
          CAST(CLOSED AS NUMBER(1))     AS CLOSED,
          CAST(NULL AS DATE)            AS LASTPAIDDATE,
          CAST(PAID_AMT AS NUMBER(15,3)) AS PAID_AMT
      FROM MIGRATION.LS_OV_DEBT_PAID_UPD
    ]';
  END IF;
END;
/
CREATE UNIQUE INDEX MIGRATION.IX_TMP_STG_DEBT
  ON MIGRATION.TMP_STG_DEBT (MAIN_LREF) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_TMP_STG_DEBT NOPARALLEL;
/

-- =============================================================================
-- 1) LS_STG_INV_PAY_CLOSE
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.LS_STG_INV_PAY_CLOSE PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.LS_STG_INV_PAY_CLOSE
NOLOGGING
PARALLEL 56
AS
SELECT /*+ PARALLEL(56) */
    CAST(inv.LREF AS NUMBER(12))                                 AS MAIN_LREF,
    CAST(NVL(pay.FATURAID, inv.ABYS_ACCOUNT_ID) AS NUMBER(12))   AS FATURAID,
    CAST(NVL(pay.SOZLESME, inv.ABYS_AGREEMENT_ID) AS NUMBER(12)) AS SOZLESME,
    CAST(ROUND(NVL(inv.PAYABLETOTAL, 0), 2) AS NUMBER(15,3))     AS PAYABLE_AMT,
    CAST(NVL(pay.OV_PAID_AMT, 0) AS NUMBER(15,3))                AS OV_PAID_AMT,
    CAST(NVL(pay.OV_PAY_CNT, 0) AS NUMBER(10))                   AS OV_PAY_CNT,
    pay.OV_LAST_PAY_DATE                                         AS OV_LAST_PAY_DATE,
    CAST(NVL(pay.OV_PAY_FULL_SUM, 0) AS NUMBER(15,3))            AS OV_PAY_FULL_SUM,
    CAST(debt.CLOSED AS NUMBER(1))                               AS OV_CLOSED,
    debt.LASTPAIDDATE                                            AS OV_LASTPAIDDATE,
    lp.LAST_PAYTYPE                                              AS LAST_PAYTYPE,
    lp.LAST_OV_KIND                                              AS LAST_OV_KIND,
    lp.LAST_PAY_LREF                                             AS LAST_PAY_LREF,
    lp.LAST_BANK_PAY_DATE                                        AS LAST_BANK_PAY_DATE,
    /* banka / vezne = kanal; USERID = islemi yapan kisi (ayri) */
    lp.BANKA_ID                                                  AS BANKA_ID,
    lp.BANKA_CODE                                                AS BANKA_CODE,
    lp.BANKA                                                     AS BANKA,
    lp.VEZNE_ID                                                  AS VEZNE_ID,
    lp.VEZNE_CODE                                                AS VEZNE_CODE,
    lp.VEZNE                                                     AS VEZNE,
    lp.USERID                                                    AS USERID,
    lp.UPDATED_USER_ID                                           AS UPDATED_USER_ID,
    lp.TAH_MAKBUZ_SERIAL                                         AS TAH_MAKBUZ_SERIAL,
    lp.TAH_MAKBUZ_NO                                             AS TAH_MAKBUZ_NO,
    lp.BANK_RECORD_REF                                           AS BANK_RECORD_REF,
    CAST(CASE WHEN afl.FATURAID IS NOT NULL THEN 1 ELSE 0 END
         AS NUMBER(1))                                           AS AFL_OPEN,
    CAST(afl.BALANCE AS NUMBER(15,3))                            AS AFL_BAL,
    CAST(0.50 AS NUMBER(15,3))                                   AS EPS_AMT,
    /* WANT_CLOSED: AFL acik → 0; aksi halde PAID≈PAYABLE (EPS) veya PAYABLE=0 */
    CAST(
      CASE
        WHEN afl.FATURAID IS NOT NULL THEN 0
        WHEN ABS(NVL(inv.PAYABLETOTAL, 0)) <= 0.01 THEN 1
        WHEN NVL(pay.OV_PAID_AMT, 0)
             >= ROUND(NVL(inv.PAYABLETOTAL, 0), 2) - 0.50
         AND ROUND(NVL(inv.PAYABLETOTAL, 0), 2) > 0.01
        THEN 1
        ELSE 0
      END AS NUMBER(1)
    )                                                            AS WANT_CLOSED,
    CASE
      WHEN afl.FATURAID IS NOT NULL THEN CAST(NULL AS DATE)
      WHEN debt.LASTPAIDDATE IS NOT NULL THEN debt.LASTPAIDDATE
      WHEN pay.OV_LAST_PAY_DATE IS NOT NULL THEN pay.OV_LAST_PAY_DATE
      WHEN lp.LAST_BANK_PAY_DATE IS NOT NULL THEN lp.LAST_BANK_PAY_DATE
      ELSE CAST(NULL AS DATE)
    END                                                          AS WANT_LPD,
    CAST(
      CASE
        WHEN afl.FATURAID IS NOT NULL THEN 'AFL_OPEN'
        WHEN NVL(pay.OV_PAY_CNT, 0) = 0
         AND ABS(NVL(inv.PAYABLETOTAL, 0)) <= 0.01
          THEN 'CLOSE_FULL'
        WHEN NVL(pay.OV_PAY_CNT, 0) = 0 THEN 'NO_PAY'
        WHEN NVL(pay.OV_PAID_AMT, 0)
             >= ROUND(NVL(inv.PAYABLETOTAL, 0), 2) - 0.01
          THEN 'CLOSE_FULL'
        WHEN NVL(pay.OV_PAID_AMT, 0)
             >= ROUND(NVL(inv.PAYABLETOTAL, 0), 2) - 0.50
          THEN 'CLOSE_EPS'
        ELSE 'KEEP_OPEN'
      END AS VARCHAR2(16)
    )                                                            AS FIX_KIND,
    CAST(
      ROUND(
        NVL(pay.OV_PAID_AMT, 0) - ROUND(NVL(inv.PAYABLETOTAL, 0), 2)
      , 2) AS NUMBER(15,3)
    )                                                            AS PAID_MINUS_PAYABLE,
    CAST(SYSDATE AS DATE)                                        AS SNAPSHOT_DATE
FROM MIGRATION.LS_INVOICE inv
LEFT JOIN MIGRATION.TMP_STG_PAY_AGG pay
  ON pay.MAIN_LREF = inv.LREF
LEFT JOIN MIGRATION.TMP_STG_PAY_LAST lp
  ON lp.MAIN_LREF = inv.LREF
LEFT JOIN MIGRATION.TMP_STG_DEBT debt
  ON debt.MAIN_LREF = inv.LREF
LEFT JOIN MIGRATION.LS_AFL_OPEN_DEBT afl
  ON afl.FATURAID = inv.ABYS_ACCOUNT_ID
 AND NVL(afl.MIG_IN_SCOPE, 1) = 1
WHERE NVL(inv.IOCODE, 0) = 0
  AND inv.ABYS_ACCOUNT_ID IS NOT NULL;

CREATE UNIQUE INDEX MIGRATION.IX_STG_IPC_MAIN
  ON MIGRATION.LS_STG_INV_PAY_CLOSE (MAIN_LREF) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_STG_IPC_FATURA
  ON MIGRATION.LS_STG_INV_PAY_CLOSE (FATURAID) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_STG_IPC_FIX
  ON MIGRATION.LS_STG_INV_PAY_CLOSE (FIX_KIND) PARALLEL 56 NOLOGGING;
CREATE INDEX MIGRATION.IX_STG_IPC_WANT
  ON MIGRATION.LS_STG_INV_PAY_CLOSE (WANT_CLOSED, FIX_KIND) PARALLEL 56 NOLOGGING;
ALTER INDEX MIGRATION.IX_STG_IPC_MAIN NOPARALLEL;
ALTER INDEX MIGRATION.IX_STG_IPC_FATURA NOPARALLEL;
ALTER INDEX MIGRATION.IX_STG_IPC_FIX NOPARALLEL;
ALTER INDEX MIGRATION.IX_STG_IPC_WANT NOPARALLEL;
ALTER TABLE MIGRATION.LS_STG_INV_PAY_CLOSE NOPARALLEL LOGGING;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION','LS_STG_INV_PAY_CLOSE', degree => 40); END;
/

-- TMP temizligi (opsiyonel; dump gerekmez)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_PAY_AGG PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_PAY_LAST PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_DEBT PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_BANK_NM PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_STG_CASH_NM PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- RECON
PROMPT ========== O51 LS_STG_INV_PAY_CLOSE ==========
SELECT FIX_KIND, COUNT(*) CNT,
       ROUND(SUM(PAYABLE_AMT), 2) PAYABLE_SUM,
       ROUND(SUM(OV_PAID_AMT), 2) PAID_SUM
FROM MIGRATION.LS_STG_INV_PAY_CLOSE
GROUP BY FIX_KIND
ORDER BY FIX_KIND;

SELECT
    COUNT(*) AS STG_CNT,
    COUNT(CASE WHEN AFL_OPEN = 1 THEN 1 END) AS AFL_OPEN_CNT,
    COUNT(CASE WHEN WANT_CLOSED = 1 THEN 1 END) AS WANT_CLOSED_CNT,
    COUNT(CASE WHEN FIX_KIND = 'CLOSE_EPS' THEN 1 END) AS CLOSE_EPS_CNT,
    COUNT(CASE WHEN WANT_LPD IS NOT NULL THEN 1 END) AS WANT_LPD_CNT,
    COUNT(CASE WHEN LAST_BANK_PAY_DATE IS NOT NULL THEN 1 END) AS BANK_DATE_CNT,
    COUNT(CASE WHEN BANKA_ID IS NOT NULL THEN 1 END) AS BANKA_CNT,
    COUNT(CASE WHEN VEZNE_ID IS NOT NULL THEN 1 END) AS VEZNE_CNT,
    COUNT(CASE WHEN USERID IS NOT NULL THEN 1 END) AS USERID_CNT,
    COUNT(CASE WHEN UPDATED_USER_ID IS NOT NULL THEN 1 END) AS UPD_USER_CNT,
    COUNT(CASE WHEN USERID IS NOT NULL AND UPDATED_USER_ID IS NOT NULL
                AND USERID <> UPDATED_USER_ID THEN 1 END) AS USER_DIFF_CNT,
    COUNT(CASE WHEN TAH_MAKBUZ_NO IS NOT NULL THEN 1 END) AS MAKBUZ_CNT,
    COUNT(CASE WHEN BANK_RECORD_REF IS NOT NULL THEN 1 END) AS BANK_REF_CNT
FROM MIGRATION.LS_STG_INV_PAY_CLOSE;

DECLARE
  n_stg NUMBER; n_want NUMBER; n_eps NUMBER;
BEGIN
  SELECT COUNT(*),
         COUNT(CASE WHEN WANT_CLOSED = 1 THEN 1 END),
         COUNT(CASE WHEN FIX_KIND = 'CLOSE_EPS' THEN 1 END)
    INTO n_stg, n_want, n_eps
    FROM MIGRATION.LS_STG_INV_PAY_CLOSE;
  BEGIN
    MIGRATION.P_MIG_CTAS_LOG('O51', 'stg_inv_pay_close', 'OK', n_stg,
      'want_closed=' || n_want || ' close_eps=' || n_eps || ' dump→izgazMGR');
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  DBMS_OUTPUT.PUT_LINE('========== O51 OK | stg=' || n_stg
    || ' want_closed=' || n_want || ' close_eps=' || n_eps
    || ' | CTAS BITTI → dump LS_STG_INV_PAY_CLOSE ==========');
END;
/
