-- =============================================================================
-- diag_o11_ctas_smoke — hizli ORA-01438 ayristirma (kucuk CTAS)
-- Calistir: @diag_o11_ctas_smoke.sql
-- Hangisi FAIL ederse o grupta sorun var.
-- =============================================================================

ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 8;

PROMPT === A) sadece kimlik (CAST yok) ===
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O11_A PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O11_A NOLOGGING PARALLEL 8 AS
SELECT /*+ PARALLEL(8) */ aa.ID LREF, acc.ID ACC_ID, acc.AGREEMENT_ID,
       acc.INSTALLATION_ID, acc.REGISTER_ID, acc.METER_ID,
       acc.IS_E_BILL, acc.IS_FPS, acc.DO_DISCHARGE,
       aa.CONSUMPTION, aa.M3, aa.KWH, aa.VERSION, aa.BILL_PRINT_NUMBER,
       aa.BILL_ORDER_NUMBER, acc.PERIOD, aa.ARCHIVE_SEND_STATUS
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
WHERE aa.ACTION_TYPE_ID IN (1,3,10,41)
  AND NVL(acc.ACCRUE_TYPE_ID,-1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;
PROMPT A OK

PROMPT === B) + STG tutar ROUND ===
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O11_B PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O11_B NOLOGGING PARALLEL 8 AS
SELECT /*+ PARALLEL(8) */ aa.ID LREF,
       ROUND(COALESCE(av.TOTAL_EXCL_TAX,0),3) TLTOTAL,
       ROUND(COALESCE(av.PAYABLE_TOTAL,0),3) PAYABLE,
       ROUND(COALESCE(av.TOTAL_TAX,0),3) TAX
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
LEFT JOIN MIGRATION.STG_INV_ACC_INC av ON av.ACA_ID = aa.ID
WHERE aa.ACTION_TYPE_ID IN (1,3,10,41)
  AND NVL(acc.ACCRUE_TYPE_ID,-1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;
PROMPT B OK

PROMPT === C) + TYPE NUMBER(3) + CURID ===
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O11_C PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O11_C NOLOGGING PARALLEL 8 AS
SELECT /*+ PARALLEL(8) */ aa.ID LREF,
       CAST(CASE
         WHEN NVL(av.HAS_GAZ,0)=0 AND NVL(av.HAS_GUV,0)>0 THEN 109
         WHEN acc.ACCRUE_TYPE_ID=443 THEN 121
         WHEN aa.ACTION_TYPE_ID IN (3,10,41) THEN 93
         ELSE 119 END AS NUMBER(3)) AS TYPE,
       CAST(160 AS NUMBER(10)) AS CURID
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
LEFT JOIN MIGRATION.STG_INV_ACC_INC av ON av.ACA_ID = aa.ID
WHERE aa.ACTION_TYPE_ID IN (1,3,10,41)
  AND NVL(acc.ACCRUE_TYPE_ID,-1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;
PROMPT C OK

PROMPT === D) + NUMBER(18,3) CAST tutar (eski riskli model) ===
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.TMP_O11_D PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE MIGRATION.TMP_O11_D NOLOGGING PARALLEL 8 AS
SELECT /*+ PARALLEL(8) */ aa.ID LREF,
       CAST(ROUND(COALESCE(av.TOTAL_EXCL_TAX,0),3) AS NUMBER(18,3)) TLTOTAL,
       CAST(ROUND(COALESCE(av.PAYABLE_TOTAL,0),3) AS NUMBER(18,3)) PAYABLE
FROM SMS.CS_ACCOUNT_ACTION aa
JOIN SMS.CS_ACCOUNT acc ON acc.ID = aa.ACCOUNT_ID
LEFT JOIN MIGRATION.STG_INV_ACC_INC av ON av.ACA_ID = aa.ID
WHERE aa.ACTION_TYPE_ID IN (1,3,10,41)
  AND NVL(acc.ACCRUE_TYPE_ID,-1) <> 14
  AND aa.ID BETWEEN 1 AND 2147483647;
PROMPT D OK — eger burasi FAIL: tutar > NUMBER(18,3)

PROMPT === cleanup ===
BEGIN
  FOR t IN (
    SELECT table_name FROM all_tables
     WHERE owner='MIGRATION' AND table_name LIKE 'TMP_O11_%'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.'||t.table_name||' PURGE';
  END LOOP;
END;
/
PROMPT ========== SMOKE DONE ==========
/
