/* Pilot tahsilat hasar tespiti — energy @ 172.16.1.193 */
USE energy;
SET NOCOUNT ON;

PRINT '========== 0) FAIL LOG ==========';
SELECT TOP 20 LOG_ID, STEP_ID, STATUS, LEFT(NOTE,120) AS NOTE, STARTED_AT
FROM dbo.MIG_STEP_LOG
WHERE STATUS IN ('FAIL','GATE_FAIL')
ORDER BY LOG_ID DESC;

PRINT '========== 1) Pilot AGR adaylari (MAP PAY filled) ==========';
SELECT TOP 10 ABYS_AGREEMENT_ID AS AGR, COUNT(*) PAY_FILLED
FROM dbo.MIG_OV_ID_MAP
WHERE OV_KIND = 'PAY_PT' AND ENERGY_LREF IS NOT NULL
GROUP BY ABYS_AGREEMENT_ID
ORDER BY COUNT(*) DESC;

DECLARE @AGR BIGINT =
(
    SELECT TOP 1 ABYS_AGREEMENT_ID
    FROM dbo.MIG_OV_ID_MAP
    WHERE OV_KIND = 'PAY_PT' AND ENERGY_LREF IS NOT NULL
    GROUP BY ABYS_AGREEMENT_ID
    ORDER BY COUNT(*) DESC
);

PRINT '========== 2) Secilen AGR ==========';
SELECT @AGR AS PILOT_AGR;

PRINT '========== 3) MAP fill (pilot) ==========';
SELECT m.OV_KIND,
       COUNT(*) CNT,
       SUM(CASE WHEN m.ENERGY_LREF IS NULL THEN 1 ELSE 0 END) ENERGY_NULL,
       SUM(CASE WHEN m.ENERGY_LREF IS NOT NULL THEN 1 ELSE 0 END) ENERGY_FILLED
FROM dbo.MIG_OV_ID_MAP m
WHERE m.ABYS_AGREEMENT_ID = @AGR
GROUP BY m.OV_KIND
ORDER BY 1;

PRINT '========== 4) Kaynak vs hedef ==========';
SELECT 'MGR_PAY_PT' K, COUNT(*) N
FROM izgazMGR.dbo.LS_OV_PAY_PT WITH (NOLOCK)
WHERE ABYS_AGREEMENT_ID = @AGR
UNION ALL SELECT 'MGR_TAH_INV', COUNT(*)
FROM izgazMGR.dbo.LS_OV_TAH_INVOICE WITH (NOLOCK)
WHERE ABYS_AGREEMENT_ID = @AGR
UNION ALL SELECT 'EN_PAY_MAP', COUNT(*)
FROM dbo.MIG_OV_ID_MAP
WHERE ABYS_AGREEMENT_ID = @AGR AND OV_KIND='PAY_PT' AND ENERGY_LREF IS NOT NULL
UNION ALL SELECT 'EN_TAH_MAP', COUNT(*)
FROM dbo.MIG_OV_ID_MAP
WHERE ABYS_AGREEMENT_ID = @AGR AND OV_KIND='TAH_INV' AND ENERGY_LREF IS NOT NULL
UNION ALL SELECT 'EN_PT_ABYS_IO1', COUNT(*)
FROM dbo.LS_005_01_PAYTRANS WITH (NOLOCK)
WHERE ABYS_AGREEMENT_ID = @AGR AND ISNULL(IOCODE,0) <> 0
UNION ALL SELECT 'EN_INV_TYPE101', COUNT(*)
FROM dbo.LS_005_01_INVOICE WITH (NOLOCK)
WHERE ABYS_AGREEMENT_ID = @AGR AND [TYPE] = 101;

PRINT '========== 5) Hasar metrikleri ==========';
SELECT
 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT' AND m.ENERGY_LREF IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM dbo.LS_005_01_PAYTRANS pt WHERE pt.LREF=m.ENERGY_LREF)
 ) AS PAY_MAP_ORPHAN,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT' AND pt.CROSSREF IS NULL
 ) AS PAY_CROSSREF_NULL,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT'
    AND pt.CROSSREF IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM dbo.LS_005_01_PAYTRANS x WHERE x.LREF=pt.CROSSREF)
 ) AS PAY_CROSSREF_DEAD,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT'
    AND ISNULL(pt.IOCODE,0)=0
 ) AS MAP_TO_DEBT_PT,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT'
    AND pt.CROSSREF IS NOT NULL
    AND EXISTS (SELECT 1 FROM dbo.LS_005_01_INVOICE i WHERE i.LREF=pt.CROSSREF)
    AND NOT EXISTS (SELECT 1 FROM dbo.LS_005_01_PAYTRANS x WHERE x.LREF=pt.CROSSREF)
 ) AS CROSSREF_IS_INVOICE_NOT_PT,

 (SELECT COUNT(*) FROM izgazMGR.dbo.LS_OV_TAH_INVOICE s WITH (NOLOCK)
  JOIN dbo.LS_005_01_INVOICE inv ON inv.LREF=CAST(s.LREF_HINT AS INT)
  WHERE s.ABYS_AGREEMENT_ID=@AGR AND ISNULL(inv.[TYPE],0)<>101
 ) AS TAH_HINT_COLLIDE_MAIN,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_INVOICE inv ON inv.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='TAH_INV' AND ISNULL(inv.[TYPE],0)<>101
 ) AS TAH_MAP_POINTS_NON101,

 (SELECT COUNT(*) FROM dbo.MIG_OV_ID_MAP m
  JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF=m.ENERGY_LREF
  WHERE m.ABYS_AGREEMENT_ID=@AGR AND m.OV_KIND='PAY_PT'
    AND (
      pt.INVOICEREF IS NULL
      OR NOT EXISTS (SELECT 1 FROM dbo.LS_005_01_INVOICE i WHERE i.LREF=pt.INVOICEREF)
      OR EXISTS (SELECT 1 FROM dbo.LS_005_01_INVOICE i WHERE i.LREF=pt.INVOICEREF AND ISNULL(i.[TYPE],0)<>101)
    )
 ) AS PAY_INVOICEREF_BAD,

 (SELECT COUNT(*) FROM izgazMGR.dbo.LS_OV_PAY_PT WITH (NOLOCK)
  WHERE ABYS_AGREEMENT_ID=@AGR AND LREF_HINT IS NULL
 ) AS PAY_NO_HINT;

PRINT '========== 6) FK CROSSREF hedef ==========';
SELECT fk.name, OBJECT_NAME(fk.referenced_object_id) AS REF_TABLE, fk.is_disabled
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
WHERE fk.parent_object_id = OBJECT_ID('dbo.LS_005_01_PAYTRANS')
  AND COL_NAME(fkc.parent_object_id, fkc.parent_column_id) = 'CROSSREF';

PRINT '========== 7) Spot PAY (5) ==========';
SELECT TOP 5
    m.SRC_KEY, m.ENERGY_LREF AS PT_LREF,
    pt.IOCODE, pt.INVOICEREF, pt.CROSSREF, pt.PAYABLETOTAL,
    inv101.[TYPE] AS TAH_TYPE, main.[TYPE] AS MAIN_TYPE
FROM dbo.MIG_OV_ID_MAP m
LEFT JOIN dbo.LS_005_01_PAYTRANS pt ON pt.LREF = m.ENERGY_LREF
LEFT JOIN dbo.LS_005_01_INVOICE inv101 ON inv101.LREF = pt.INVOICEREF
LEFT JOIN dbo.LS_005_01_INVOICE main ON main.LREF = pt.CROSSREF
WHERE m.ABYS_AGREEMENT_ID = @AGR AND m.OV_KIND = 'PAY_PT'
ORDER BY m.ENERGY_LREF DESC;

PRINT '========== DIAG DONE ==========';
GO
