-- =============================================================================
-- prod2 / 10 — STG_INV_ACC_INC (income aggregate + fee pivot)
-- Onkosul: 00_session + 00_mig_param
-- DOP: FORCE 56 (hash aggregate — PGA/TEMP RISK yuksek)
-- Sonraki: 11_ls_invoice.sql
-- =============================================================================

ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 56;
ALTER SESSION FORCE PARALLEL DML PARALLEL 56;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MIGRATION.STG_INV_ACC_INC PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
CREATE TABLE MIGRATION.STG_INV_ACC_INC NOLOGGING PARALLEL 56 AS
SELECT /*+ FULL(aca) FULL(ai) PARALLEL(56) */
    CAST(aca.ACCOUNT_ID AS NUMBER(12))                          AS ACCOUNT_ID,
    CAST(aca.ID AS NUMBER(12))                                  AS ACA_ID,

    SUM(CASE WHEN ai.INCOME_ID IN (939, 7658)  THEN ai.AMOUNT END)      AS EXPEND_FEE,
    SUM(CASE WHEN ai.INCOME_ID NOT IN (169, 60) THEN ai.AMOUNT END)     AS TOTAL_EXCL_TAX,
    SUM(CASE WHEN ai.INCOME_ID IN (169, 60)    THEN ai.AMOUNT END)      AS TOTAL_TAX,
    SUM(ai.AMOUNT)                                                      AS PAYABLE_TOTAL,

    SUM(CASE WHEN ai.INCOME_ID = 1861 THEN ai.AMOUNT END)               AS GAS_OPEN_FEE,
    SUM(CASE WHEN ai.INCOME_ID = 1864 THEN ai.AMOUNT END)               AS DEFAULT_FINE,
    SUM(CASE WHEN ai.INCOME_ID = 1905 THEN ai.AMOUNT END)               AS DEFAULT_FINE_TAX,
    SUM(CASE WHEN ai.INCOME_ID = 1902 THEN ai.AMOUNT END)               AS ILLEGAL_USE_FEE,
    SUM(CASE WHEN ai.INCOME_ID = 100  THEN ai.AMOUNT END)               AS DISCOUNT_ADDITION,
    SUM(CASE WHEN ai.INCOME_ID IN
            (2981, 572, 938, 23033, 573, 23034, 23031, 23032, 2982,
             576, 574, 3251, 12531, 579, 47, 578, 581, 575, 7709,
             577, 7504, 2521, 7528, 7464, 2847, 2446, 2649, 2520,
             7408, 2591, 7496, 2583, 3067)
         THEN ai.AMOUNT END)                                            AS SPEC_SERV_FEE,

    SUM(CASE WHEN ai.INCOME_ID IN (939, 7658) THEN 1 ELSE 0 END)        AS HAS_GAZ,
    SUM(CASE WHEN ai.INCOME_ID IN
            (162, 163, 164, 165, 1936, 3198, 3199,
             7649, 7650, 7651, 7652, 12531, 23032)
         THEN 1 ELSE 0 END)                                             AS HAS_GUV,
    MAX(CASE WHEN NVL(ai.IS_DISCOUNT, 0) = 1 THEN 1 ELSE 0 END)         AS HAS_DISCOUNT,
    SUM(CASE WHEN NVL(ai.IS_DISCOUNT, 0) = 1 THEN ABS(ai.AMOUNT) ELSE 0 END) AS DISCOUNT_AMOUNT

FROM SMS.CS_ACCOUNT_ACTION aca
JOIN SMS.CS_ACCOUNT a ON a.ID = aca.ACCOUNT_ID
LEFT JOIN SMS.CS_ACCOUNT_INCOME ai ON ai.ACCOUNT_ACTION_ID = aca.ID
WHERE aca.ACTION_TYPE_ID IN (1, 3, 10, 41)
  AND NVL(a.ACCRUE_TYPE_ID, -1) <> 14
GROUP BY aca.ACCOUNT_ID, aca.ID;

CREATE UNIQUE INDEX MIGRATION.IX_STG_INV_ACC_INC ON MIGRATION.STG_INV_ACC_INC (ACA_ID)
  PARALLEL 56 NOLOGGING;

ALTER INDEX MIGRATION.IX_STG_INV_ACC_INC NOPARALLEL;

BEGIN DBMS_STATS.GATHER_TABLE_STATS('MIGRATION', 'STG_INV_ACC_INC', degree => 40); END;
/

PROMPT ========== 10 STG_INV_ACC_INC OK ==========
/