-- prodREADY / 99 — son CTAS log ozeti (salt okuma)
SET PAGESIZE 100
SET LINESIZE 220
COLUMN STEP_ID FORMAT A8
COLUMN STATUS FORMAT A12
COLUMN STEP_NAME FORMAT A36
COLUMN NOTE FORMAT A60
COLUMN LOG_TS FORMAT A28

PROMPT ========== MIG_CTAS_LOG — son 40 ==========
SELECT LOG_ID, LOG_TS, STEP_ID, STATUS, STEP_NAME, ROW_CNT, NOTE
FROM (
  SELECT LOG_ID, LOG_TS, STEP_ID, STATUS, STEP_NAME, ROW_CNT, NOTE
  FROM MIGRATION.MIG_CTAS_LOG
  ORDER BY LOG_ID DESC
)
WHERE ROWNUM <= 40
ORDER BY LOG_ID;

PROMPT ========== Son durum (STEP bazinda en son) ==========
SELECT STEP_ID, STATUS, STEP_NAME, ROW_CNT, LOG_TS, NOTE
FROM (
  SELECT STEP_ID, STATUS, STEP_NAME, ROW_CNT, LOG_TS, NOTE,
         ROW_NUMBER() OVER (PARTITION BY STEP_ID ORDER BY LOG_ID DESC) RN
  FROM MIGRATION.MIG_CTAS_LOG
)
WHERE RN = 1
ORDER BY STEP_ID;

PROMPT ========== GATE / FAIL var mi? ==========
SELECT STEP_ID, STATUS, NOTE, LOG_TS
FROM MIGRATION.MIG_CTAS_LOG
WHERE STATUS IN ('FAIL', 'GATE_FAIL')
ORDER BY LOG_ID DESC;
/
